### ISSUE TITLE
lastest cask "weiyun" is requested

### ISSUE THREAD

**Issue by zhangyafeikimi** [Homebrew/homebrew-cask#100076]
<https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/weiyun.rb>

version: 5.2.970
url: <https://dldir1.qq.com/weiyun/electron-update/release/mac/Weiyun-mac-x64-5.2.970.dmg>

**Comment by miccal** [comment]
Please open a Pull Request to update the Cask following the instructions [here](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

**Comment by zhangyafeikimi** [comment]
brew bump-cask-pr weiyun --version 5.2.970 --url https://dldir1.qq.com/weiyun/electron-update/release/mac/Weiyun-mac-x64-5.2.970.dmg
