### ISSUE TITLE
livecheck for coteditor and eaglefiler

### ISSUE THREAD

**Issue by tiiiecherle** [Homebrew/homebrew-cask#100024]
### Description of feature/enhancement

Two casks that we are using, coteditor and eaglefiler, do not have the livecheck yet.
It would be nice if it could be added.
Thanks

I'm sorry I am not familiar with the syntax. Is there a wiki/manual about the options and syntax of livecheck for the next time?
Thanks

**Comment by adithyasunil26** [comment]
The documentation for the livecheck stanza can be found [here](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/livecheck.md )

**Comment by tiiiecherle** [comment]
@adithyasunil26 Thanks. But how do I know which strategy to apply?

For coteditor guessing was not so hard and
```
  livecheck do
    url :url
    strategy :github_latest
  end
```
seems to work.

After trial an error this seems to work for eaglefiler:
```
  livecheck do
    url :homepage
    strategy :page_match
    regex(%r{href=.*?/EagleFiler-(\d+(?:\.\d+)*)\.dmg}i)
  end
```

Does that seem right? My first try was using the download url "https://c-command.com/downloads/" but I couldn't get it to work.

**Comment by tiiiecherle** [comment]
Trying a first pull request for coteditor [here](https://github.com/Homebrew/homebrew-cask/pull/100028).

**Comment by tiiiecherle** [comment]
Coteditor failed due to a style issue I don't know how to solve.

Trying eaglefiler [here](https://github.com/Homebrew/homebrew-cask/pull/100030).

**Comment by vitorgalvao** [comment]
Both of these are on their way to being merged. Thank you for doing them.
