### ISSUE TITLE
Update cask GIMP to revision 3

### ISSUE THREAD

**Issue by leonschmidlin** [Homebrew/homebrew-cask#100146]
While the version number "2.10.22" remains unchanged, the url and sha256 need to be updated for GIMP 2.10.22 DMG revision 3.
https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/gimp.rb#L5
Installing GIMP with homebrew will result in gimp-2.10.22-x86_64.dmg instead of the current gimp-2.10.22-x86_64-3.dmg

**Comment by vitorgalvao** [comment]
Please [submit an update to it](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/100122#pullrequestreview-594992658
