### ISSUE TITLE
Bad instruction in reporting_bugs/curl_error.md: Error: Unknown command: cask

### ISSUE THREAD

**Issue by anatawa12** [Homebrew/homebrew-cask#100123]
In [reporting_bugs/curl_error.md](https://github.com/Homebrew/homebrew-cask/blob/6dd2e92dfe7531a8e1d1e143ea6a851fbf47bc84/doc/reporting_bugs/curl_error.md), The instruction says "Take a look at the cask’s version (`brew cask _stanza version {{cask_name}}`) and verify it is indeed outdated." but `brew cask _stanza version {{cask_name}}` is not working.

**Comment by vitorgalvao** [comment]
Fixing in https://github.com/Homebrew/homebrew-cask/pull/100220.
