### ISSUE TITLE
New updates aren't appearing in brew

### ISSUE THREAD

**Issue by mhdmyz** [Homebrew/homebrew-cask#100145]
#### General troubleshooting steps

- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Hi. I installed miniforge using `brew install miniforge` command in my mac terminal but I can't update it to the newer releases (Miniforge3-4.9.2-6 or Miniforge3-4.9.2-7) using the `brew update miniforge` command. After 4 days the version shown in the brew website is still Miniforge3-4.9.2-5! (reference: https://formulae.brew.sh/cask/miniforge) When are they going to be available on brew? Thanks!

#### Command that failed

```
{{replace this}}
```

#### Output of command with `--verbose --debug`

```
{{replace this}}
```

#### Output of `brew doctor --verbose`

```
{{replace this}}
```

#### Output of `brew tap`

```
{{replace this}}
```

**Comment by vitorgalvao** [comment]
`brew update` is for updating cask and formulae definitions. It’s `brew upgrade` which upgrades packages.

> When are they going to be available on brew?

When someone submits updates to them! We’re a volunteer effort; if you see something is outdated, update it. In most cases it’s [literally one command](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).
