### ISSUE TITLE
Broken Cask - `figmadaemon`.

### ISSUE THREAD

**Issue by miralize** [Homebrew/homebrew-cask#100110]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Apologies if this was created incorrectly

The [`figmadaemon`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/figmadaemon.rb) cask appears to be non-functional. 

According to the website, they expose a dmg directly at https://font-daemon.figma.com/FigmaInstaller.pkg

But the sparkle version referenced returns an invalid daemon.

![image](https://user-images.githubusercontent.com/1761115/108597542-7375af80-7381-11eb-8681-7f8c679d5909.png)

#### Command that failed

```sh
brew install figmadaemon
```

#### Output of command with `--verbose --debug`

```
N/A
```

#### Output of `brew doctor --verbose`

```
N/A
```

#### Output of `brew tap`

```
N/A
```

**Comment by miccal** [comment]
The `figmadaemon` Cask installs the desktop app, while the `pkg` you linked is for something else, namely the font installers as it says [here](https://www.figma.com/downloads/).

Do you still get this error if you install the `figmadaemon` Cask using the `--no-quarantine` flag?

**Comment by miralize** [comment]
figmadaemon is the font installer, I think the naming is just off for this Cask. See https://github.com/Homebrew/homebrew-cask/blob/47d5dda6a4703fde612b1448dafcfdf090ac4808/Casks/figmadaemon.rb#L5

The Desktop app is installed via [`figma`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/figma.rb)

I tried the no-quarantine flag, got the same issue
