### ISSUE TITLE
brew bump-cask-pr does not update all hashes

### ISSUE THREAD

**Issue by domoritz** [Homebrew/homebrew-cask#100230]
See https://github.com/Homebrew/homebrew-cask/pull/100158. The hash for the ARM package was not updated.

**Comment by miccal** [comment]
This is being looked at in https://github.com/Homebrew/brew/pull/10345.

**Comment by domoritz** [comment]
It looks like the pr might get closed. Should this issue stay open until people decided on the right solution?
