### ISSUE TITLE
Webstorm for ARM64

### ISSUE THREAD

**Issue by eladcandroid** [Homebrew/homebrew-cask#100326]
https://github.com/Homebrew/homebrew-cask/blob/142a8530c4c09cbf19b4cc2742eaf2a1c5685bdc/Casks/webstorm.rb

Doesn't install the ARM64 version for Apple Silicon

**Comment by vitorgalvao** [comment]
[From the README](https://github.com/Homebrew/homebrew-cask/#requests):

> Issues requesting new casks will be closed. If you want a cask added to the main repositories, [submit a pull request](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#adding-a-cask).

This is also explicit in [the issue templates](https://github.com/Homebrew/homebrew-cask/issues/new/choose), where the one labeled `Cask Request` with the subtitle `For requesting new casks`, states the same thing.

A request for support for a new architectures or versions of macOS falls in the same category. We accept PRs for those.
