### ISSUE TITLE
objectivesharpie cask site disabled

### ISSUE THREAD

**Issue by antonioser** [Homebrew/homebrew-cask#100325]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Seams `objectivesharpie` site is disabled. When i run command i get error 
```
curl: (22) The requested URL returned error: 403 Site Disabled
Error: Download failed on Cask 'objectivesharpie' with message: Download failed: https://download.xamarin.com/objective-sharpie/ObjectiveSharpie-3.4.0.pkg
```
I open link https://download.xamarin.com/objective-sharpie/ObjectiveSharpie in browser i get same 403 Site Disabled Error

#### Command that failed

```
brew install --cask objectivesharpie
```

#### Output of command with `--verbose --debug`

```
N/A
```

#### Output of `brew doctor --verbose`

```
N/A
```

#### Output of `brew tap`

```
N/A
```

**Comment by cho-m** [comment]
Probably can change Cask URL from using https://download.xamarin.com to https://dl.xamarin.com (which redirects back to https://download.visualstudio.microsoft.com)

```xml
❯ curl "https://docs.microsoft.com/en-us/xamarin/cross-platform/macios/binding/objective-sharpie/releases?context=xamarin/ios" 2>/dev/null | grep 3.4.0
<p><a href="https://dl.xamarin.com/objective-sharpie/ObjectiveSharpie-3.4.0.pkg" data-linktype="external">Download v3.4.0</a></p>

❯ curl https://dl.xamarin.com/objective-sharpie/ObjectiveSharpie-3.4.0.pkg
Found. Redirecting to https://download.visualstudio.microsoft.com/download/pr/100173119/c367c913219cdfa307b98fe912d07691/ObjectiveSharpie-3.4.0.pkg%
```

**Comment by vitorgalvao** [comment]
Anyone care to submit a PR with the fix (if possible) or deletion (if not)?
