### ISSUE TITLE
there is broken link in /doc/development/adding_a_cask.md 

### ISSUE THREAD

**Issue by rustiever** [Homebrew/homebrew-cask#100691]
this issue is not related to the tool,
[here](https://github.com/rustiever/homebrew-cask/blob/master/doc/development/adding_a_cask.md) there is broken link

exactly in `it can be accepted by checking the Rejected Casks FAQ document,` this line

**Comment by vitorgalvao** [comment]
Thank you. Fixing in https://github.com/Homebrew/homebrew-cask/pull/100696.
