### ISSUE TITLE
Cannot install any cask.

### ISSUE THREAD

**Issue by RDKRACZ** [Homebrew/homebrew-cask#100650]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

I can't install a cask - tried `copyq` and `microsoft-edge`

#### Command that failed

`brew install copyq`, `brew install --cask copyq` and `brew install microsoft-edge`

#### Output of command with `--verbose --debug`

```
Updating Homebrew...
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "copyq".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
/usr/bin/curl --disable --globoff --show-error --user-agent Linuxbrew/3.0.4-14-g9d62a13\ \(Linux\;\ x86_64\ Ubuntu\ 20.10\)\ curl/7.68.0 --header Accept-Language:\ en --retry 3 --location https://api.github.com/search/code\?q=user\%3AHomebrew\+path\%3AFormula\+path\%3ACasks\+path\%3A.\+filename\%3Acopyq\+extension\%3Arb\&per_page=100 --header Accept:\ application/vnd.github.v3\+json --write-out '
'\%\{http_code\} --header Accept:\ application/vnd.github.antiope-preview\+json --dump-header /tmp/github_api_headers20210303-54117-1ss2bs
Error: No formulae found in taps.
```

#### Output of `brew doctor --verbose`

```
Your system is ready to brew.
```

#### Output of `brew tap`

```
homebrew/core
```

Also

https://formulae.brew.sh/formula-linux/ here I typed copyq and it is available.

```
brew home copyq
Error: No available formula or cask with the name "copyq".
```

**Comment by miccal** [comment]
Try running `brew tap homebrew/cask` first.
