### ISSUE TITLE
sogouinput should be labeled auto_updates true

### ISSUE THREAD

**Issue by NeighbourDYY** [Homebrew/homebrew-cask#100653]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

sogouinput auto updates itself. Also, the cask can only unzip the installer for the user to execute, but the brew cask upgrade uninstalls the previous installation. It means the brew cask upgrade is not only unnecessary but also destructive. Note, I cannot re-install the old version to reproduce this bug, but it's a very simple fix I believe.

#### Command that failed

```
brew upgrade
```

#### Output of command with `--verbose --debug`

```
==> Upgrading sogouinput
==> Downloading http://cdn2.ime.sogou.com/dl/index/1612884268/sogou_mac_601a.zip
######################################################################## 100.0%
==> Removing launchctl service com.sogou.SogouServices
Password:
==> Removing files:
/Library/Input Methods/SogouInput.app
/Library/QuickLook/SogouSkinFileQuickLook.qlgenerator
To complete the installation of Cask sogouinput, you must also
run the installer at:
  /usr/local/Caskroom/sogouinput/601a,1612884268/sogou_mac_601a.app
==> Purging files for version 58a,1588947491 of Cask sogouinput
🍺  sogouinput was successfully upgraded!
```

#### Output of `brew doctor --verbose`

```
{{replace this}}
```

#### Output of `brew tap`

```
{{replace this}}
```

**Comment by miccal** [comment]
Please submit a PR to add `auto_updates true` to this Cask, thanks.
