### ISSUE TITLE
`brew pin` for casks

### ISSUE THREAD

**Issue by alexreg** [Homebrew/homebrew-cask#100700]
### Description of feature/enhancement

Could we get `brew pin` working for casks? At least ones that don't auto-update.

### Justification

The feature is useful for casks just as much as ordinary formulas.

### Example use case

Same as for pinning formulas — when you don't want something to upgrade.

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/issues/90242

**Comment by alexreg** [comment]
I'm not sure I see the rationale. What's wrong worth having this feature for casks that don't auto-update?
