### ISSUE TITLE
iina bumped to beta channel in error

### ISSUE THREAD

**Issue by lucario** [Homebrew/homebrew-cask#100755]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

#99432
iina latest stable release is still 1.1.2. As it is now, anyone who has this cask installed is now on the beta channel. Users with M1 machines who need 1.2.0 can simply enroll into the beta channel themselves. 
https://iina.io/download/
https://github.com/iina/iina/releases

#### Command that failed

```
{{replace this}}
```

#### Output of command with `--verbose --debug`

```
{{replace this}}
```

#### Output of `brew doctor --verbose`

```
{{replace this}}
```

#### Output of `brew tap`

```
{{replace this}}
```

**Comment by vitorgalvao** [comment]
It’s not an error, and it’s not a beta. [See the Github releases](https://github.com/iina/iina/releases). The only change from the precious version is that it’s a universal build.

**Comment by vitorgalvao** [comment]
Fixing in https://github.com/Homebrew/homebrew-cask/pull/100761.
