### ISSUE TITLE
running brew install visual-studio-code on apple silicon macs won't install arm native version

### ISSUE THREAD

**Issue by alimehasin** [Homebrew/homebrew-cask#100705]
### Description of feature/enhancement

[vscode version 1.54](https://code.visualstudio.com/updates/v1_54) has been released with [native apple silicon support](https://code.visualstudio.com/updates/v1_54#_apple-silicon), but running `brew install visual-studio-code` on apple silicon macs won't install the native apple silicon version.

**Comment by robertlonnqvist** [comment]
Noticed this too, the URL for the universal binary is slightly different. Created a pull request #100706.

**Comment by miccal** [comment]
Will be fixed by https://github.com/Homebrew/homebrew-cask/pull/98725.
