### ISSUE TITLE
Metasploit version is outdated in brew. 

### ISSUE THREAD

**Issue by heatwave998** [Homebrew/homebrew-cask#100911]
As of March 8th, 2021, the latest URL for Metasploit is: 

https://osx.metasploit.com/metasploit-framework-6.0.34%2B20210307112933-1rapid7-1.pkg

Brew upgrade is trying to grab this one instead: 
https://osx.metasploit.com/metasploit-framework-6.0.32%2B20210222112915-1rapid7-1.pkg
which will 404. 

Cheers!

**Comment by miccal** [comment]
Please submit a PR to update this Cask, thanks.
