### ISSUE TITLE
Failure to uninstall google-chrome

### ISSUE THREAD

**Issue by lennyheath** [Homebrew/homebrew-cask#100928]
I just want to uninstall google-chrome.  I try

  brew uninstall --force homebrew/cask/google-chrome

and get this failure message:

Warning: Unexpected method 'license' called on Cask google-chrome.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Error: Cask 'google-chrome' definition is invalid: invalid 'depends_on macos' value: unknown or unsupported macOS version: :mavericks

Help will be much appreciated.

I am running MacOS Big Sur 11.2.2 .

**Comment by vitorgalvao** [comment]
You installation is very old.

Remove the directory at `$(brew --caskroom)/google-chrome` then uninstall the app manually.
