### ISSUE TITLE
RetroArch version is outdated

### ISSUE THREAD

**Issue by windowswithoutborders** [Homebrew/homebrew-cask#101087]
https://www.libretro.com/index.php/retroarch-for-apple-mac-m1-softlaunches-today/

Hope to see the cask updated soon for this exciting new update from the RetroArch team.

And if possible, it would be nice to use the nightly builds for the --head formula

From the article:
> **There are two versions for now:**
> RetroArch with OpenGL (for x86 x64 Macs) (latest nightly [here](https://buildbot.libretro.com/nightly/apple/osx/x86_64/RetroArch.dmg))
> RetroArch with Metal (for x86 x64 / ARM Macs) (latest nightly [here](https://buildbot.libretro.com/nightly/apple/osx/universal/RetroArch_Metal.dmg))

**Comment by ran-dall** [comment]
@windowswithoutborders 🔧 Fix is incoming. Next time, I would encourage you to try updating the cask yourself with our dev tools. The command that you would have needed to run is `brew bump-cask-pr --url http://buildbot.libretro.com/stable/#{version}/apple/osx/universal/RetroArch_Metal.dmg --version 1.9.0 retroarch`.

Now, the cask was already at 1.9.0, so all we're doing is switching the links. If need be we could make 2 casks but I don't think there are that many users to really require the extra burden. Besides, FMU the Metal version should be compatible with macOSs all-the-way down to High Sierra, which is well beyond what we support.

As for the nightly versions, you're more than welcome to try to submit them to [`versions`](https://github.com/Homebrew/homebrew-cask-versions), but again, I don't know if there's that many users to really support such a request. The other option you have is to simply make a personal tap.

**Comment by windowswithoutborders** [comment]
@ran-dall 

Appreciate you looking into this. Thanks for sharing that command also, that’ll be useful for the future. It’s worth mentioning that the OpenGL version supports different cores (plugins, so to speak) that utilize OpenGL than the metal version, and the retroarch team mention in the article to have both versions on your system (as cumbersome as that might be), for access to all the cores they offer. 

With that being said, it would be great to have the OpenGL RetroArch added to the casks as well.

**Comment by ran-dall** [comment]
@windowswithoutborders Hmm, tbh I didn't read the article, but I'm really glad you caught that. If that's the case, then frankly I wouldn't be opposed to having both casks in the tap. However, I think it would be wise to get the opinion of @vitorgalvao and/or @miccal on this, as well.

**Comment by windowswithoutborders** [comment]
@ran-dall 
No worries, as I have some familiarity with this program I'm happy to kind of navigate and present some options that might be most practical for brew.

That being said:
- Currently, the stable branch only has an updated version of RetroArch_Metal, available here:
http://buildbot.libretro.com/stable/1.9.0/apple/osx/universal/RetroArch_Metal.dmg
- The stable OpenGL version available [here](http://buildbot.libretro.com/stable/1.9.0/apple/osx/x86_64/) has not been updated and is still the version release 2020-08.

There are nightly's available for the two versions here (as mentioned in the article and my post above):
- RetroArch with OpenGL (for x86 x64 Macs): https://buildbot.libretro.com/nightly/apple/osx/x86_64/RetroArch.dmg
- RetroArch with Metal (for x86 x64 / ARM Macs): https://buildbot.libretro.com/nightly/apple/osx/universal/RetroArch_Metal.dmg

As you might've noticed from the nightly links above, they simply have the name "RetroArch.dmg", meaning if the a --head formula was implemented, it would simply have to point to that static link. I believe I've seen that it's possible to skip the sha256 check in formulas as well, so that would simplify things as well. And if I'm not mistaken, I think that would mean the package wouldn't nag the user either, it would just detect that RetroArch was installed, and the user would have to know to pass `brew reinstall --cask --head retroarch` to update their nightly.

I think there's a legitimate case for the retroarch casks to implement a --head formula for the nightlies, but whether it's practical or feasible, I'll leave that up to those with a better grasp at the cask code than me.

**Comment by ran-dall** [comment]
@windowswithoutborders The thing is, to my knowledge, `--head` only works on `core` formula and doesn't work on `cask` because all the apps are pre-compiled. The `--head` command pulls from the source and complies with the latest code in the source repo, hence why it doesn't work on `cask`. That said, we've had similar situations before, and the only solution is to put them in [`versions`](https://github.com/Homebrew/homebrew-cask-versions); in fact, it's why we maintain that tap.

As for the two casks, I do see a legitimate need for 2 casks. However, let's wait to see what the other maintainers think though, as I'm not the only one that maintains this repo and it is an unusual case to have 2 different casks for the same program (even if they aren't really the same program inside).

**Comment by windowswithoutborders** [comment]
@ran-dall 
Ooohh, okay. Haha, I'm showing off my layman understanding of brew. Btw doing a quick `brew search retroarch` I see brew already maintains the two casks, one for open gl and one for metal:
https://formulae.brew.sh/cask/retroarch#default
https://formulae.brew.sh/cask/retroarch-metal#default

I suppose this been raised before. So it's entirely satisfactory to just maintain these casks as is, but it would be nice (though not necessary) to see their nightly counterparts in cask-versions.

**Comment by ran-dall** [comment]
@windowswithoutborders Awesome! Although we probably should have started there. Lol. I'll close this out as I would consider this issue solved.

As for the nightly versions, you can just copy the cask formula and make a simple PR to add it to `versions`. Otherwise, I'd say wait and see if there's more interest in adding to `versions`, maybe someone will add it.
