### ISSUE TITLE
Attempted brew install ghc M1 Chip Mac

### ISSUE THREAD

**Issue by DevinSuttles** [Homebrew/homebrew-cask#101001]
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

ghc: no bottle avaliable

### Command that failed

brew install ghc

### Output of command with `--verbose --debug`

Error: ghc: no bottle available!
You can try to install from source with:
  brew install --build-from-source ghc
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.

### Output of `brew doctor --verbose`

Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /opt/homebrew/share/zsh/site-functions/_brew_cask

### Output of `brew tap`

homebrew/cask
homebrew/core

**Comment by ran-dall** [comment]
@DevinSuttles This isn't the right repo for your issue. You should to open this up with [`core`](https://github.com/Homebrew/homebrew-core).
