### ISSUE TITLE
iShowU Audio Capture

### ISSUE THREAD

**Issue by honzajavorek** [Homebrew/homebrew-cask#101349]
I can see https://github.com/Homebrew/homebrew-cask/pull/85040 closed, because the software is discontinued. However, [this page](https://support.shinywhitebox.com/hc/en-us/articles/204161459-Installing-iShowU-Audio-Capture) on the maker's website is updated Feb 2021 and the software [is currently the recommended way](https://obsproject.com/forum/resources/os-x-capture-audio-with-ishowu-audio-capture.505/) to enable any audio recording on macOS when using [OBS](https://obsproject.com/), a very popular OSS software used for screen recording and streaming. It would be awesome if I didn't have to install it manually, I like to keep things managed by Homebrew exclusively.

I'm noob in preparing formulae, but perhaps if you give me green to prepare one for this software, I could try it based on the closed PR. Of course, if someone is more experienced in this, they would probably have it done in a much faster and correct manner.

**Comment by miccal** [comment]
Please go ahead and open a PR @honzajavorek.

**Comment by honzajavorek** [comment]
OK so investigated further and it seems it indeed [has been deprecated](https://support.shinywhitebox.com/hc/en-us/articles/360039968951) and replaced by "SWB Audio Capture", which doesn't have a separate download anymore. It's bundled with the other apps by the author, which are already available as casks.
