### ISSUE TITLE
delete .git folder taking lot of space

### ISSUE THREAD

**Issue by davidecampello** [Homebrew/homebrew-cask#102278]
Hi, I have a computer with few disk space and I noticed that this folder /opt/homebrew/Library/Taps/homebrew/homebrew-core/.git take about 450Mb and the same is for /opt/homebrew/Library/Taps/homebrew/homebrew-cask/.git.
Is it possible to delete this folders? Are they necessary for hombrew to work?
Thanks

**Comment by vitorgalvao** [comment]
Homebrew is distributed as git repos, and that’s what we use to update. Yes, those are necessary.

**Comment by davidecampello** [comment]
Ok, thank you!
