### ISSUE TITLE
Allow `--no-require-sha` and Brewfile `require_sha:false`.

### ISSUE THREAD

**Issue by ppo** [Homebrew/homebrew-cask#102602]
> Cross-issue on [`homebrew-bundle`](https://github.com/Homebrew/homebrew-bundle/issues/939)

### Provide a detailed description of the proposed feature

Allow to activate `require-sha` by default/globally via `HOMEBREW_CASK_OPTS="--require-sha"` and to deactivate when necessary using `--no-require-sha` or in a Brewfile `cask "name", args: { require_sha: false }`.

### What is the motivation for the feature?

I want to require all casks to have a checksum by default, globally.  
But as some formulae doesn't have one, I need a way to selectively deactivate it.

And of course I don't want to do the opposite; i.e. manually requiring only when available.

### Example use case

```
HOMEBREW_CASK_OPTS="--require-sha"
```

```
brew install --cask --no-require-sha font-roboto
```

Brewfile:
```
cask "font-roboto", args: { require_sha: false }
```

**Comment by jacobbednarz** [comment]
I'm 👎 on this proposal as verifying the integrity of packages is something that ensures that Homebrew is only installing packages that the end user is expecting and nothing malicious. 

Happy to hear other opinions if I've missed anything!

**Comment by ppo** [comment]
> I'm 👎 on this proposal as verifying the integrity of packages is something that ensures that Homebrew is only installing packages that the end user is expecting and nothing malicious. 

That's exactly why I want to activate it by default.  
Unfortunately some packages don't have it (e.g. fonts, Chrome) so you may not enable it globally. And it's a problem with bundle/Brewfile if you can't disable it per package.

**Comment by jacobbednarz** [comment]
I'm not sure I follow the issue then because formula that don't/can't have a sha256 for verification  already use `sha256 :no_check` (see [google-chrome](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/google-chrome.rb#L3)). This works in other parts of the Homebrew ecosystem too.

**Comment by jacobbednarz** [comment]
Bringing over my comment from the other thread but the homebrew-bundle README already has a reference to `require_sha: false` for `cask_args` which _should_ mean it's already there?

**Comment by vitorgalvao** [comment]
> Cross-issue on [`homebrew-bundle`](https://github.com/Homebrew/homebrew-bundle/issues/939)

Please don’t do that. Open one issue in one repo.

> I want to require all casks to have a checksum by default, globally.
> But as some formulae doesn't have one

Please let’s keep nomenclature consistent when discussing. Casks.

> verifying the integrity of packages is something that ensures that Homebrew is only installing packages that the end user is expecting and nothing malicious.

On casks that’s not exactly true. We even state specifically and often that users shouldn’t take a checksum as a security value. Casks download packaged directly from vendors and if upstream is compromised we have no way of knowing. In no way do we want the responsibility of saying a certain checksum is trustworthy.

> the homebrew-bundle README already has a reference to `require_sha: false`

The example I’m seeing is `require_sha: true`

As to the feature request itself, in general I’m not opposed to `--no-` options, but I also don’t think this feature is worth it. I could take it or leave it. If the PR for it were small (fast to review and without significantly complicating the codebase), I’d be fine with it, but I’m doubtful a maintainer will want to spend the time on it.

I’ll leave this open for now in case someone wants to tackle it (remember: small!) or express disagreement, but when the stale bot comes around, that’s it.

**Comment by ppo** [comment]
Isn't the `sha256 :no_check` supposed to mean that it must ignore/not fail with `--require-sha`?

But so… If there's no way to activate the "Require SHA" globally and disable it for exceptions, it means we have to explicitly specify it in each install command and in each cask line in the Brewfile… which doesn't feel right.  
That said, I may understand the "OK if small changes.
