### ISSUE TITLE
What happened to the XtraFinder cask?

### ISSUE THREAD

**Issue by mariobrostech** [Homebrew/homebrew-cask#102718]
Hi,

I was looking the other day for the XtraFinder cask on Homebrew since I remember it being there in years past and wanted to give it another try. However, I cannot find it either by `brew search xtrafinder` or by searching for it on [https://formulae.brew.sh](https://formulae.brew.sh).

I would like to know what has happened to the cask: has it been renamed due to naming guidelines, or has it been outright removed? If so, why?

Thanks in advance for your help!

**Comment by cho-m** [comment]
It was removed. See: https://github.com/Homebrew/homebrew-cask/pull/41890

The reason was that XtraFinder requires Apple's SIP to be disabled.
This is documented on their site: https://www.trankynam.com/xtrafinder/doc/index.html#line4
