### ISSUE TITLE
Craft URI invalid

### ISSUE THREAD

**Issue by NicolasReyrolle** [Homebrew/homebrew-cask#102785]
Hi,

The specified URI for Craft is invalid, this gives a 404.
I have been totally unable to find the new one from their website, so sorry I cannot propose a correction.

https://github.com/Homebrew/homebrew-cask/blob/4a1bc7d00d6296da36ec61922e366afbdc6e878f/Casks/craft.rb#L5

Regards,

**Comment by vitorgalvao** [comment]
Thank you for letting us know. Removing in https://github.com/Homebrew/homebrew-cask/pull/102789.
