### ISSUE TITLE
Add more debug output to `zap :delete` stanza

### ISSUE THREAD

**Issue by sebroeder** [Homebrew/homebrew-cask#10325]
While working on caskroom/homebrew-versions#879 I found that small errors (typos, incorrect `gsub` calls) in the `zap :delete` stanza where quite common but hard to find, leaving files behind that should be removed by `zap`.

Since `:delete` does not complain when a file that is supposed to be deleted does not exist, it would be really helpful when the `--debug` output could not only show the `rm` command it runs (as it already does) but also whether it actually deleted the files/folders or whether they were not even there in the first place (indicating an error in the formula in most cases).

This way it would be much easier for package maintainers to verify that the file/folder array given to the `zap :delete` stanza is actually correct (checking manually in the file system is time consuming).

**Comment by radeksimko** [comment]
It might be useful for `--debug` output, I agree. Labelling issue properly.

It's worth mentioning that `zap` is intended to be tool for removing optional things that are very often created by user while using the SW, not during the installation, therefore **in many cases things just won't exist and it does not mean there's something wrong**.

**Comment by vitorgalvao** [comment]
No objections here.
