### ISSUE TITLE
Homebrew ignoring --appdir='...'

### ISSUE THREAD

**Issue by p-sims** [Homebrew/homebrew-cask#103360]
Prehaps I'm understanding, but I've used the following in my bash profile to change application install directory:
`export HOMEBREW_CASK_OPTS="--appdir=/Applications/Downloaded/ --fontdir=/Library/Fonts"`

This shows up in brew config:
![Screenshot 2021-04-07 at 17 28 04](https://user-images.githubusercontent.com/64636731/113901474-c935d800-97c6-11eb-8081-cfba1fddeb32.png)

But when I come to update a cash for an app  homebrew seems the think my app path is /Users/<my user>/Applications/Downloaded/
![Screenshot 2021-04-07 at 17 16 42](https://user-images.githubusercontent.com/64636731/113901595-eb2f5a80-97c6-11eb-8f7e-72b958f5fb49.png)
 
No sure if this is a bug or something else . . .

**Comment by p-sims** [comment]
Strangled this doesn't seem to apply to all casks
![Screenshot 2021-04-07 at 20 11 00](https://user-images.githubusercontent.com/64636731/113921034-70256e80-97dd-11eb-9af2-c898ccbb3dd7.png)

**Comment by miccal** [comment]
This should be fixed by https://github.com/Homebrew/homebrew-cask/pull/103685.
