### ISSUE TITLE
qt-creator does not find existing brew installed qt versions

### ISSUE THREAD

**Issue by jayvdb** [Homebrew/homebrew-cask#103349]
### Provide a detailed description of the proposed feature

The qt-creator preferences shows which Qt versions it has found.  The list is empty when both qt and qt@5 are installed by brew.

Under QT versions in the preferences, clicking Add omits /usr , so it is not easy to add the brew installed Qt that way.

Also in the preferences is a button "Link with Qt".  There it is possible to enter path `/usr/local/Cellar/qt/6.0.2`, but that doesnt allow registering it.

A little further fiddling reveals it will register a Qt if the full path to the `qmake` is given. 

### What is the motivation for the feature?

qt-creator without a qt installation is usable, but not very functional, and it would be nice if users can get it to work reasonably well without knowing how to force it to find the various qmake

### Example use case

1. `brew install qt qt-creator`
2. Open app qt-creator
3. Open project

Expect qt-creator to be able to use qt tools.

**Comment by vitorgalvao** [comment]
We’ll need a PR for this. I’ve never used QT so I have no idea what would be needed here.
