### ISSUE TITLE
Docker Desktop for Apple Silicon RC 3

### ISSUE THREAD

**Issue by ManuelSchneid3r** [Homebrew/homebrew-cask#103448]
### Provide a detailed description of the proposed feature

Let the Docker Desktop Cask ship the Docker Desktop for Apple Silicon RC 3 for M1 based macs. Since Docker for amd64 simply does not work for M1 machines, the docker cask makes no sense there anyway and could be used to ship the RC:
https://docs.docker.com/docker-for-mac/apple-m1/

### What is the motivation for the feature?

Docker cask prints an error message and exits on M1 chips.

### Example use case

Well if you need Docker Desktop on an ARM machine

**Comment by vitorgalvao** [comment]
[From the README](https://github.com/Homebrew/homebrew-cask/#requests):

> Issues requesting new casks will be closed. If you want a cask added to the main repositories, [submit a pull request](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#adding-a-cask).

This is also explicit in [the issue templates](https://github.com/Homebrew/homebrew-cask/issues/new/choose), where the one clearly labeled `Cask Request` with the subtitle `For requesting new casks`, states the same thing.

Please do not ignore our templates or documentation.

**Comment by ManuelSchneid3r** [comment]
This is not a cask request. Shipping legacy docker on an M1 is plain nonsense. I just wanted to give the maintainers a hint on how  to 'fix' this 'bug'

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/103810
