### ISSUE TITLE
doc: define "cask" (n.)

### ISSUE THREAD

**Issue by adonovan** [Homebrew/homebrew-cask#103722]
Your documentation at README.md and USAGE.md uses sentences like these:

"Want to contribute a Cask?"
"Issues requesting new casks will be closed. If you want a cask added ..."
"All Homebrew Cask commands begin with brew, which works for both Casks and Formulae."

Yet I have no idea what a "cask" is. Is it homebrew jargon for a package? (I guess not, because homebrew-cask would then be a mysterious name for a GUI-app extension to homebrew.)

Could you please define this term before you use it? (Remember that most readers care to spend the least possible amount of time understanding their build system, and just want to get on with something else.)

**Comment by vitorgalvao** [comment]
[On the FAQ of the main repo](https://github.com/Homebrew/brew/blob/master/docs/FAQ.md), the first link is to [a glossary](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#homebrew-terminology).

At the root of this repository there’s a `Casks` directory. Everything here is about casks, those little ruby files with define how to install software.

> Is it homebrew jargon for a package? (I guess not, because homebrew-cask would then be a mysterious name for a GUI-app extension to homebrew.)

We’re aware the beer-themed terminology can be a bit confusing. Even the original author of Homebrew recognised it early on. Alas, some of those are hard to change now. Homebrew Cask started as a separate project, which is why we have both formulae and casks. Making everything less confusing is a work in progress.

> most readers care to spend the least possible amount of time understanding their build system, and just want to get on with something else.

Agreed, though it’s not clear why you’d care in this case. If you don’t know what a cask is, why would you want to contribute one? You don’t need to know what a cask is to use it. I’d say [the README is pretty clear on how they’re used](https://github.com/Homebrew/homebrew-cask#lets-try-it). Heck, you don’t even need to know what a cask is called to contribute one; we have tons of contributors who call them formulae, even when they are built differently.

**Comment by adonovan** [comment]
> At the root of this repository there’s a Casks directory. Everything here is about casks, those little ruby files with define how to install software.

So there is. Your "a little Ruby file which defines how to install software" is already a better definition than I had gleaned.


> We’re aware the beer-themed terminology can be a bit confusing.  ... Making everything less confusing is a work in progress.

Glad to hear it. I don't mind the beer theme, and the glossary (which I had found a different way) is helpful but seems to omit Casks as a noun. Adding one line there would help, perhaps something like:

"Cask (noun): a Ruby script that automates the installation of a GUI application, using the Cask extension to Homebrew"


> Agreed, though it’s not clear why you’d care in this case.

Fair enough. While my "most readers care..." claim is probably true, in this instance I am trying to form a minimal mental model of these concepts so that I am not just mindless copying commands I don't understand.

**Comment by vitorgalvao** [comment]
> Cask (noun): a Ruby script that automates the installation of a GUI application

That would be incomplete, though. They can [install pretty much anything](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/all_stanzas.md#at-least-one-artifact-stanza-is-also-required); they just can’t compile software (unlike formulae).

> using the Cask extension to Homebrew

Seems redundant and is possibly confusing. It makes it seems like you need to do something to start using casks.

> so that I am not just mindless copying commands I don't understand.

Like what? Yours isn’t a common question, so to address it would help to know the exact problem you’re facing.

**Comment by adonovan** [comment]
> Like what? Yours isn’t a common question, so to address it would help to know the exact problem you’re facing.

My question may be uncommon, but my problem is not: how to get oriented in a Mac development environment. (I know Linux well, but my new employer issues only Mac workstations, despite production running Linux, so I'm trying to map Mac-flavored concepts onto their Linux counterparts, or understand where there is no simple correspondence.)

I think you may underestimate just how clueless many of your users are initially, even though they may have great experience or capacity to learn. In any project, it rarely hurts to provide an overview of the model of your design in terms so simple they might seem embarrassing to you. Imagine if the documentation for git started with "it's a DAG of commits, where each commit is a tar file", instead of reference material and videos of workflows. It would have saved weeks of pain.

**Comment by vitorgalvao** [comment]
> My question may be uncommon, but my problem is not

I keep replying and asked you for more details. Hardly seems like I don’t want to improve the situation.

> In any project, it rarely hurts to provide an overview of the concepts of your design in terms so simple they might seem embarrassing to you.

I agree, though we have to strike a balance. We’re not going to teach you how to open a Terminal. That’s not an exaggeration; if we added every explanation everyone asks for, we’d be explaining what a shell is.

[The README explains what HBC is](https://github.com/Homebrew/homebrew-cask#homebrew-cask), [how to get started](https://github.com/Homebrew/homebrew-cask#lets-try-it), and [how to learn more](https://github.com/Homebrew/homebrew-cask#learn-more).

So again, you need to specify what exactly is your question. I can answer that, and then maybe you can submit some PRs to improve the documentation, which we can further discuss.
