### ISSUE TITLE
Upgrading openvpn-connect removes user data

### ISSUE THREAD

**Issue by treuherz** [Homebrew/homebrew-cask#103721]
Upgrading the [`openvpn-connect`](https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/openvpn-connect.rb) cask runs its Uninstaller package which, as far as I can tell, removes all existing user preferences, including all VPN profiles. This necessitates a lot of manual work on the part of the user to recreate their previous environment, after what you'd expect to be a non-destructive upgrade.

I've upgraded this package manually in the past, before I switched to managing it with Homebrew. Running the new version's installer package, _not_ running the uninstaller first, does _not_ delete existing VPNs. This seems like it would be the desired behaviour on a `brew upgrade`.

Output during the upgrade is below. It doesn't look like anything unusual is happening here, I think the problem is in the choice to run the uninstaller package as part of the upgrade, rather than anything not working as programmed.

```
==> Upgrading openvpn-connect
==> Downloading https://swupdate.openvpn.net/downloads/connect/openvpn-connect-3.2.7.3220_signed.dmg
######################################################################## 100.0%
==> Removing launchctl service org.openvpn.client
==> Removing launchctl service org.openvpn.helper
==> Running uninstall script /Applications/OpenVPN Connect/Uninstall OpenVPN Connect.app/Contents/Resources/remove.sh
==> Uninstalling packages; your password may be necessary:
org.openvpn.client.pkg
org.openvpn.client_framework.pkg
org.openvpn.client_launch.pkg
org.openvpn.client_uninstall.pkg
org.openvpn.helper_framework.pkg
org.openvpn.helper_launch.pkg
==> Running installer for openvpn-connect; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
installer: Package name is OpenVPN Connect
installer: Installing at base path /
installer: The install was successful.
==> Purging files for version 3.2.6,3136 of Cask openvpn-connect
🍺  openvpn-connect was successfully upgraded!
```

**Comment by vitorgalvao** [comment]
See https://github.com/Homebrew/homebrew-cask/pull/72782, https://github.com/Homebrew/homebrew-cask/issues/75251, https://github.com/Homebrew/homebrew-cask/issues/53078, and https://github.com/Homebrew/homebrew-cask/pull/56218.

This is a rare situation and we’re open to specific improvements, but we’re already aware of it.
