### ISSUE TITLE
Unexpected method 'license' called on Cask kdiff3

### ISSUE THREAD

**Issue by profwmw** [Homebrew/homebrew-cask#103832]
This warning has popped up on multiple occasions, even after resetting and upgrading.  It doesn't seem to have any real effect, but the message requests a bug report.

**Comment by miccal** [comment]
You currently installed version of `kdiff3` is from a very old version of the Cask file -- please run
```
brew uninstall --force kdiff3
```
then
```
rm -r "$(brew --prefix)/Caskroom/kdiff3"
```
then
```
brew install kdiff3
```
which should fix your issue.
