### ISSUE TITLE
Re-open previously running apps after they have been updated by Homebrew

### ISSUE THREAD

**Issue by mariobrostech** [Homebrew/homebrew-cask#104074]
### Provide a detailed description of the proposed feature

I would like to propose the ability for casks to automatically re-open if they were already running at the time of being updated via Homebrew. Apps that always run in the background, such as the window manager Rectangle, for instance, are automatically quit by Homebrew when they are being updated, but they aren't re-launched following the update. This makes for a sub-par user experience. The ability to do something along these lines seems possible since Homebrew automatically detects and closes any running apps before updating them, so it would likely be possible for Homebrew to also detect if the app was running prior to being updated to re-launch it accordingly.

### What is the motivation for the feature?

I use a script that runs on an automated schedule to update Homebrew and all of my associated formulae and casks. This generally goes smoothly, but when apps that have to constantly run in the background are updated, Homebrew stops these apps without restarting them following the update. This can be frustrating because it won't become evident that these apps have been terminated unless the user tries to invoke them and they fail to work. A good example of this would be the Rectangle window manager, like detailed in the previous section of this issue, but this could very well apply a number of always-running apps.

### Example use case

This is how Homebrew currently handles app updates:
- Homebrew quits any running apps when they are updated
- Homebrew deletes the existing app link from /Applications
- Homebrew downloads the updated app binary and re-links it into /Applications
- The app doesn't activate until the user manually initializes it, even if it had been open prior to being updated

My proposed solution would change the process to something like this:
- Homebrew quits any running apps when they are updated and logs any open apps will be updated to a temporary file
- Homebrew deletes the existing app link from /Applications
- Homebrew downloads the updated app binary and re-links it into /Applications
- Once this is done, Homebrew pulls from the list of previously running apps and re-opens them
- The user no longer has to worry about launching apps that have been updated by Homebrew if they had already been running prior to the update

**Comment by vitorgalvao** [comment]
> are automatically quit by Homebrew when they are being updated, but they aren't re-launched following the update.

That’s because an `upgrade` is an `uninstall` followed by an `install`.

So what you’re asking isn’t trivial. It would require specific `upgrade` functionality, which we don’t have. See https://github.com/Homebrew/homebrew-cask/issues/75251 and related issues.
