### ISSUE TITLE
Broken link in PR template

### ISSUE THREAD

**Issue by MichaelSp** [Homebrew/homebrew-cask#104194]
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

In the [PR Template](https://github.com/Homebrew/homebrew-cask/blob/master/.github/PULL_REQUEST_TEMPLATE.md) the links to stable versions and exceptions are not explaining anything about stable versions and exceptions.

This is relevant here: https://github.com/Homebrew/homebrew-cask/pull/104193

### Command that failed

not applicable

### Output of command with `--verbose --debug`

not applicable

### Output of `brew doctor --verbose`

not applicable

### Output of `brew tap`

not applicable

**Comment by cho-m** [comment]
Links to currently open PRs on this (for some reason, each PR decided to only fix half the issue even though change is on same line):
- https://github.com/Homebrew/homebrew-cask/pull/104174 (documented exception)
- https://github.com/Homebrew/homebrew-cask/pull/104198 (stable version)
