### ISSUE TITLE
Wrap ghidra into app bundle.

### ISSUE THREAD

**Issue by ZzEeKkAa** [Homebrew/homebrew-cask#104183]
### Provide a detailed description of the proposed feature

Ghidra is an java application and provides ghidraRun script, which simply runs:

```bash
#!/usr/bin/env bash

#----------------------------------------
# Ghidra launch
#----------------------------------------

# Maximum heap memory may be changed if default is inadequate. This will generally be up to 1/4 of 
# the physical memory available to the OS. Uncomment MAXMEM setting if non-default value is needed.
#MAXMEM=2G

# Resolve symbolic link if present and get the directory this script lives in.
# NOTE: "readlink -f" is best but works on Linux only, "readlink" will only work if your PWD
# contains the link you are calling (which is the best we can do on macOS), and the "echo" is the 
# fallback, which doesn't attempt to do anything with links.
SCRIPT_FILE="$(readlink -f "$0" 2>/dev/null || readlink "$0" 2>/dev/null || echo "$0")"
SCRIPT_DIR="${SCRIPT_FILE%/*}"

# Launch Ghidra
"${SCRIPT_DIR}"/support/launch.sh bg Ghidra "${MAXMEM}" "" ghidra.GhidraRun "$@"
```

I want to wrap this cask into app. Does `brew` have util to generate app from bash script? Is it ok to generate `.app` bundle with `plist` in `.rb` file?

Found gist that does what I'm talking about: https://gist.github.com/saagarjha/777909b257dbfa98649476b7f5af41bb

### What is the motivation for the feature?

Run application from Launchpad, not from console.

### Example use case

Application run.

**Comment by vitorgalvao** [comment]
> Does `brew` have util to generate app from bash script?

Nope. You’ll have to do it yourself or ask upstream.
