### ISSUE TITLE
Is livecheck broken with strategy sparkle?

### ISSUE THREAD

**Issue by Yann-R** [Homebrew/homebrew-cask#104100]
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

Hello,
While trying to write a new cask inspired from existing casks using  `livecheck` with `strategy :sparkle`, I just observed that they all are currently failing.

Just a few examples:
- brew livecheck --cask adium
- brew livecheck --cask fantastical
- brew livecheck --cask rectangle
- brew livecheck --cask skim
- brew livecheck --cask snapndrag
- brew livecheck --cask swish
- brew livecheck --cask texmacs
- brew livecheck --cask texshop
- brew livecheck --cask wireshark
- brew livecheck --cask xquartz
- etc.

I can't find any of them that ends without failing, either this cask is installed on my system or not.
All other existing casks I tested with other stategy stanza just work.
All the ones with sparkle as stategy produce:
```
Error: cannot load such file -- nokogiri
/opt/brew/Homebrew/Library/Homebrew/livecheck/strategy/sparkle.rb:58:in `require'
/opt/brew/Homebrew/Library/Homebrew/livecheck/strategy/sparkle.rb:58:in `item_from_content'
/opt/brew/Homebrew/Library/Homebrew/livecheck/strategy/sparkle.rb:114:in `find_versions'
/opt/brew/Homebrew/Library/Homebrew/livecheck/livecheck.rb:532:in `block in latest_version'
/opt/brew/Homebrew/Library/Homebrew/livecheck/livecheck.rb:479:in `each'
/opt/brew/Homebrew/Library/Homebrew/livecheck/livecheck.rb:479:in `each_with_index'
/opt/brew/Homebrew/Library/Homebrew/livecheck/livecheck.rb:479:in `latest_version'
/opt/brew/Homebrew/Library/Homebrew/livecheck/livecheck.rb:189:in `block in run_checks'
/opt/brew/Homebrew/Library/Homebrew/livecheck/livecheck.rb:142:in `map'
/opt/brew/Homebrew/Library/Homebrew/livecheck/livecheck.rb:142:in `with_index'
/opt/brew/Homebrew/Library/Homebrew/livecheck/livecheck.rb:142:in `run_checks'
/opt/brew/Homebrew/Library/Homebrew/dev-cmd/livecheck.rb:115:in `livecheck'
/opt/brew/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

### Command that failed

brew livecheck --cask xquartz

### Output of command with `--verbose --debug`

<details><summary>Click to expand</summary><pre><code>

git config --replace-all homebrew.devcmdrun true
#<Homebrew::CLI::Args named=["xquartz"], remaining=["xquartz"], d?=true, debug?=true, Display any debugging information.?=false, q?=false, quiet?=false, Make some output more quiet.?=false, v?=true, verbose?=true, Make some output more verbose.?=false, h?=false, help?=false, Show this message.?=false, full_name?=false, Print formulae/casks with fully_qualified names.?=false, tap=nil, Check formulae/casks within the given tap, specified as <user>`/`<repo>.=nil, all?=false, Check all available formulae/casks.?=false, installed?=false, Check formulae/casks that are currently installed.?=false, newer_only?=false, Show the latest version only if it's newer than the formula/cask.?=false, json?=false, Output information in JSON format.?=false, Suppress warnings, don't print a progress bar for JSON output.?=false, formula?=false, formulae?=false, Only check formulae.?=false, cask?=true, casks?=true, Only check casks.?=false>

Cask:             xquartz
Livecheckable?:   Yes

URL:              https://www.xquartz.org/releases/sparkle/release.xml
Strategies:       PageMatch, Sparkle
Strategy:         Sparkle
Error: cannot load such file -- nokogiri
/opt/brew/Homebrew/Library/Homebrew/livecheck/strategy/sparkle.rb:58:in `require'
/opt/brew/Homebrew/Library/Homebrew/livecheck/strategy/sparkle.rb:58:in `item_from_content'
/opt/brew/Homebrew/Library/Homebrew/livecheck/strategy/sparkle.rb:114:in `find_versions'
/opt/brew/Homebrew/Library/Homebrew/livecheck/livecheck.rb:532:in `block in latest_version'
/opt/brew/Homebrew/Library/Homebrew/livecheck/livecheck.rb:479:in `each'
/opt/brew/Homebrew/Library/Homebrew/livecheck/livecheck.rb:479:in `each_with_index'
/opt/brew/Homebrew/Library/Homebrew/livecheck/livecheck.rb:479:in `latest_version'
/opt/brew/Homebrew/Library/Homebrew/livecheck/livecheck.rb:189:in `block in run_checks'
/opt/brew/Homebrew/Library/Homebrew/livecheck/livecheck.rb:142:in `map'
/opt/brew/Homebrew/Library/Homebrew/livecheck/livecheck.rb:142:in `with_index'
/opt/brew/Homebrew/Library/Homebrew/livecheck/livecheck.rb:142:in `run_checks'
/opt/brew/Homebrew/Library/Homebrew/dev-cmd/livecheck.rb:115:in `livecheck'
/opt/brew/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'

</code></pre></details>

### Output of `brew doctor --verbose`

<details><summary>Click to expand</summary><pre><code>

==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
==> $LOAD_PATHS
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/warning-1.2.0/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tapioca-0.4.20/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/spoom-1.0.9/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thor-1.1.0/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-stub-0.2.0/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-cobertura-1.4.2/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-0.21.2/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov_json_formatter-0.1.2/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-html-0.12.3/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.5.0/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-sorbet-0.6.1/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-2.2.0/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rails-2.9.1/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.10.2/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-1.12.1/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unicode-display_width-2.0.0/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.11.0/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-ast-1.4.1/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-sorbet-1.8.0/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-0.5.6274/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-static-0.5.6274-universal-darwin-14/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.2/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-github-2.3.1/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-3.10.0/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-mocks-3.10.2/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-expectations-3.10.1/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-core-3.10.1/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-support-3.10.2/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.4/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/regexp_parser-2.1.1/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rdiscount-2.2.0.2/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/rdiscount-2.2.0.2
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rack-2.2.3/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/pry-0.14.0/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.6.0/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/patchelf-1.3.0/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parlour-6.0.0/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-0.5.6274/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.0.0/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parser-3.0.0.0/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel_tests-3.7.0/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel-1.20.1/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.1/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/method_source-1.0.0/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.8.0/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrick-1.7.0/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubyntlm-0.6.3/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.11.3-x86_64-darwin/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/racc-1.5.2/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/racc-1.5.2
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.5.0/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-4.0.1/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.3.1/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-data-3.2021.0225/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.3/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/hpricot-0.8.6
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/elftools-1.1.3/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.7.7/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/unf_ext-0.0.7.7
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.3.5/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.4.4/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.3/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/commander-4.5.2/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/highline-2.0.3/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/colorize-0.8.1/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/coderay-1.1.3/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/byebug-11.1.3/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/byebug-11.1.3
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bootsnap-1.7.3/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/bootsnap-1.7.3
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/msgpack-1.4.2/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/msgpack-1.4.2
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bindata-2.4.8/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ast-2.4.2/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/addressable-2.7.0/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/public_suffix-4.0.6/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.1.3.1/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.4.2/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-2.0.4/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/minitest-5.14.4/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.9/lib
/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby
/opt/brew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/site_ruby/2.6.0
/opt/brew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/site_ruby/2.6.0/x86_64-darwin14
/opt/brew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/site_ruby
/opt/brew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/vendor_ruby/2.6.0
/opt/brew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/vendor_ruby/2.6.0/x86_64-darwin14
/opt/brew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/vendor_ruby
/opt/brew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0
/opt/brew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/x86_64-darwin14
/opt/brew/Homebrew/Library/Homebrew
==> Homebrew Version
3.1.2-15-gba578f4
==> macOS
10.15.7
==> SIP
Enabled
==> Homebrew Cask Staging Location
/opt/brew/Caskroom
==> Homebrew Cask Taps:
/opt/brew/Homebrew/Library/Taps/homebrew/homebrew-cask (3892 casks)
/opt/brew/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (188 casks)
/opt/brew/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1721 casks)
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  godep

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  archivemount
  avfs
  colorsvn
  contacts
  csv-fix
  curlftpfs
  ext2fuse
  ext4fuse
  fuse-zip
  godep
  ifuse
  mp3fs
  ntfs-3g
  rdesktop
  sshfs
  xmount
  xtail

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/ublio.h

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  unison

Warning: Your Homebrew's prefix is not /usr/local.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/usr/local).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
unsupported configuration.

Warning: /usr/bin occurs before /opt/brew/bin in your PATH.
This means that system-provided programs will be used instead of those
provided by Homebrew. Consider setting your PATH so that
/opt/brew/bin occurs before /usr/bin. Here is a one-liner:
  echo 'setenv PATH /opt/brew/bin:$PATH' >> ~/.tcshrc

The following tools exist at both paths:
  cpan
  svn
  pre-grohtml
  groff
  neqn
  instmodsh
  db_upgrade
  perlivp
  pod2usage
  corelist
  db_hotbackup
  git-receive-pack
  libnetcfg
  tfmtodit
  grolbp
  python3
  troff
  mmroff
  encguess
  groffer
  db_printlog
  db_archive
  refer
  pip3
  pod2text
  nano
  pfbtops
  ptardiff
  grops
  grotty
  db_stat
  json_pp
  perl
  perlbug
  eqn
  db_load
  piconv
  ptargrep
  h2ph
  prove
  podchecker
  tbl
  rsync
  shasum
  git-upload-archive
  indxbib
  ptar
  soelim
  pl2pm
  addftinfo
  svnlook
  db_verify
  perlthanks
  post-grohtml
  hpftodit
  pic
  patch
  gdiffmk
  xsubpp
  perldoc
  grodvi
  lookbib
  afmtodit
  svnversion
  h2xs
  lkbib
  db_checkpoint
  pod2man
  enc2xs
  git-shell
  grn
  nroff
  db_deadlock
  git-upload-pack
  grolj4
  splain
  grog
  pod2html
  db_recover
  db_dump
  git
  zipdetails

</code></pre></details>

### Output of `brew tap`

<details><summary>Click to expand</summary><pre><code>

homebrew/bundle
homebrew/cask
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core

</code></pre></details>

**Comment by cho-m** [comment]
Have you tried running via Rosetta?
`arch -x86_64 brew livecheck --cask xquartz`

I think Homebrew uses x86_64 version of Nokogiri:
https://github.com/Homebrew/brew/blob/2b34ecfe18f7924619823dfe1e21540fcdace982/Library/Homebrew/vendor/bundle/bundler/setup.rb#L45

**Comment by Yann-R** [comment]
> Can you try fixing some of the brew doctor errors and clean up your PATH?

Apart from `brew link unison` (that I fixed just now), which one(s) are you aiming at?

Since, I agree to modify things (at least for test purposes) but, at first glance, all the rest that `brew doctor` suggests is interesting, but these are things I've chosen to be like that:

- my prefix is `/opt/brew` and not `/usr/local` that's true
- therefore I preferred to but /opt/brew/bin AFTER and not before /usr/bin in my PATH to have these additional software in second place
- I also preferred putting non-prefixed coreutils in my path since it's useful

So apart from having specifically `strategy :sparkle` not working with a non-standard brew prefix (not /usr/local) it seems odd.

> EDIT: actually, seems you are not using M1 since on 10.15. I see same error on M1.

Yes, intel and catalina.
So you see the same error that I signaled?... Not related with my personal `brew doctor`artifacts then?

> You may want to see if nokogiri.rb exists in the directory above.

Well done! It maybe be a good idea.
My system does have `nokogiri.rb`
- but not in the path you pasted (that doesn't exist on my system)
`/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.11.3-x86_64-darwin/lib`
- it is located in
`/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.10.10/lib`

Is it the reason of the failure?
Do I have to reinstall something that is now broken?

**Comment by cho-m** [comment]
> My system does have `nokogiri.rb`
> 
> * but not in the path you pasted (that doesn't exist on my system)
>   `/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.11.3-x86_64-darwin/lib`
> * it is located in
>   `/opt/brew/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.10.10/lib`

Homebrew uses Ruby Bundler to manage some of their dependencies.
In theory, it should have downloaded newer nokogiri when certain Homebrew commands are run.

For some reason, you currently have the dependency from older Homebrew (v2.7.2 or older)
- https://github.com/Homebrew/brew/blob/2.7.2/Library/Homebrew/Gemfile.lock#L52
   ```
       nokogiri (1.10.10)
   ```
- https://github.com/Homebrew/brew/blob/2.7.2/Library/Homebrew/vendor/bundle/bundler/setup.rb#L42
   ```
   $:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/nokogiri-1.10.10/lib"
   ```

Rather than current Homebrew:
- https://github.com/Homebrew/brew/blob/master/Library/Homebrew/Gemfile.lock#L57
   ```
       nokogiri (1.11.3)
   ```
- https://github.com/Homebrew/brew/blob/master/Library/Homebrew/vendor/bundle/bundler/setup.rb#L45
   ```
   $:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/nokogiri-1.11.3-x86_64-darwin/lib"
   ```

---

I think some commands like `brew audit|style` usually end up automatically installing missing Gems, so maybe try running one of those.

Essentially, you need to get Homebrew to use Bundler to download the currently expected vendor-gems.

**Comment by Yann-R** [comment]
> I think some commands like brew audit|style usually end up automatically installing missing Gems, so maybe try running one of those.

Perfect idea!
`brew audit xquartz.rb`
=> updates many gems

and then my initial problem is solved.
```
> brew livecheck xquartz
xquartz : 2.8.0 ==> 2.8.0
```

> Essentially, you need to get Homebrew to use Bundler to download the currently expected vendor-gems.

Yes. Have you any idea why my brew system did not also implied gems to be updated from updates to updates? (I use homebrew for  years, regularly updated)...
Thank you for your help, really! 👍

**Comment by miccal** [comment]
Fixed by https://github.com/Homebrew/brew/pull/11171.

**Comment by Yann-R** [comment]
@miccal Good news: you confirm that the fix you mentioned (addressing the issue when the first item in list is not the latest version) will also solve the kind of problem we decribed above:
- my ruby gems used by `brew livecheck` not automatically updated to latest versions 
- although I've been regularly used `brew update` for months and years...?
