### ISSUE TITLE
Upgrade tortoisehg to 5.7.1

### ISSUE THREAD

**Issue by rgoldberg** [Homebrew/homebrew-cask#104639]
### Provide a detailed description of the proposed feature

Upgrade tortoisehg to 5.7.1

### What is the motivation for the feature?

tortoisehg 5.7.1 is the current stable version

### Example use case

`brew install tortoisehg`

**Comment by SMillerDev** [comment]
https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask
