### ISSUE TITLE
Missing docs for :github_latest strategy

### ISSUE THREAD

**Issue by thatrobotdev** [Homebrew/homebrew-cask#104626]
Hello!
I've been noticing there are a lot of casks with a livecheck stanza that do this:
```ruby
livecheck do
    url :url
    strategy :github_latest
```

but I can't find any docs for this in the livecheck stanza docs: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/livecheck.md.

**Comment by cho-m** [comment]
Homebrew Cask docs probably need to be updated.
A related issue was #98231, which was for documenting `:git` strategy.

Homebrew's core rubydoc (https://rubydoc.brew.sh/Homebrew/Livecheck/Strategy.html) lists all available strategies.

Some strategies used in Casks that aren't in the docs for Cask repo include:
- [`:git`](https://rubydoc.brew.sh/Homebrew/Livecheck/Strategy/Git.html) - useful for matching on git tags. Default behavior for GitHub Repo URLs if no `livecheck` stanza.
- [`:github_latest`](https://rubydoc.brew.sh/Homebrew/Livecheck/Strategy/GithubLatest.html) - useful when GitHub repo redirects `https://github.com/<owner>/<repo>/releases/latest` to current stable release. Can help ignore pre-releases in `:git` strategy and regex capture more complicated download URL/filename paths.
- [`:electron_builder`](https://rubydoc.brew.sh/Homebrew/Livecheck/Strategy/ElectronBuilder.html) - very specific to electron-builder YAML appcasts.
- [`:extract_plist`](https://rubydoc.brew.sh/Homebrew/Livecheck/Strategy/ExtractPlist.html) - a last-ditch approach for unversioned URLs that requires downloading file.

**Comment by carlocab** [comment]
FYI, `:github_latest` should also only be used when really needed, as it involves an API call that is often rate-limited by GitHub.
