### ISSUE TITLE
Caffeine collecting analytics without user's consent

### ISSUE THREAD

**Issue by medeyusa** [Homebrew/homebrew-cask#104772]
Today I've noticed that caffeine (installed from homebrew) started collecting some analytics data. I'm certain it didn't in the past, so collecting data without user's consent or knowledge is unethical. I removed it immediately, I suggest issuing warning during an installation to inform users about such behaviour.

<img width="995" alt="Screenshot 2021-04-29 at 00 07 17" src="https://user-images.githubusercontent.com/81479208/116478762-e702d400-a87e-11eb-82e6-7475d035ccd3.png">

**Comment by miccal** [comment]
This is an issue for the developers of Caffeine, and does not have anything to do with `homebrew-cask` -- all the Cask file does is download and install the software the same way as you would do it manually.
