### ISSUE TITLE
Remove: wakeonlan cask

### ISSUE THREAD

**Issue by bdmorin** [Homebrew/homebrew-cask#104849]
The cask `wakeonlan` should be considered for removal.
```
❯ brew info wakeonlan --cask
wakeonlan: 1.0
https://www.readpixel.com/wakeonlan/
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/wakeonlan.rb
==> Name
WakeOnLan
==> Description
None
==> Artifacts
WakeOnLan/WakeOnLan.app (App)
==> Analytics
install: 1 (30 days), 33 (90 days), 233 (365 days)
```
The website is flagged as malware by google.

https://safebrowsing.google.com/safebrowsing/diagnostic?site=https%3A%2F%2Fwww.readpixel.com%2Fdownloads%2Ffiles%2FWakeOnLan1.0.zip

![image](https://user-images.githubusercontent.com/476219/116763987-13d0fb80-a9e5-11eb-8567-bd28d696cf0c.png)

Additionally, the developer and app appear to be abandoned.

I hope I opened this issue properly. 
Thanks.

**Comment by cho-m** [comment]
Sounds reasonable.

Definitely seems abandoned given that the Cask download file (based on `sha256`) has remained unchanged since introduction in 2014.

If you are familiar with git, you may want to go ahead and open PR to remove Cask.
Let me know if you aren't and I can create PR to delete cask.

**Comment by bdmorin** [comment]
Yeah, I can do that, wasn't sure if that was the protocol.
