### ISSUE TITLE
Policy for new download url of Autodesk Sketchbook.

### ISSUE THREAD

**Issue by bric3** [Homebrew/homebrew-cask#104962]
The sketchbook formula is outdated, because the website is down, the software is available on a new site.

```shell
$ brew install sketchbook
==> Downloading https://update.sketchbook.com/mac/SketchBook_v8.7.1_mac.dmg
Warning: Transient problem: timeout Will retry in 1 seconds. 3 retries left.
Warning: Transient problem: timeout Will retry in 2 seconds. 2 retries left.
Warning: Transient problem: timeout Will retry in 4 seconds. 1 retries left.
##O=#  #
curl: (6) Could not resolve host: update.sketchbook.com
Error: Download failed on Cask 'sketchbook' with message: Download failed: https://update.sketchbook.com/mac/SketchBook_v8.7.1_mac.dmg
```

When one goes to the Autodesk Sketchbook download site : https://www.autodesk.com/products/sketchbook/free-download, one can see the following link.

https://download.autodesk.com/us/support/files/sketchbook/sketchbook_2019/sketchbook_v8.7.1_mac.dmg

So editing the formula is easy and works. BUT as you can notice this URL has a `sketchbook_2019` path component, which I'm not sure would fit the acceptance criteria. I would like some guidance on how to proceed.

**Comment by SMillerDev** [comment]
If that is the place where the download is available I'm not sure what acceptance criteria that would break.

**Comment by cho-m** [comment]
If the year in URL is static, then you can just use the same version format `version "8.7.1"`.

If the year in URL is expected to be updated, then you can add the year to version format `version "8.7.1,2019"`
And change URL to use both parts: `url "https://download.autodesk.com/us/support/files/sketchbook/sketchbook_#{version.after_comma}/sketchbook_v#{version.before_comma}_mac.dmg"`

The `livecheck` is probably also broken and will probably fail CI audit test.

**Comment by bric3** [comment]
Hi thank you both. I will proceed as suggested.

**Comment by bric3** [comment]
Follow-up in https://github.com/Homebrew/homebrew-cask/pull/105067
