### ISSUE TITLE
Stats 2.5.12 crash on M1 Macbook Air

### ISSUE THREAD

**Issue by lanthean** [Homebrew/homebrew-cask#104961]
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

New version of Stats crashes on M1 version of MBA (Macbook Air).
After a minute or so after starting the app, it will crash.
I have SSD (R/W, F/U, usage %), RAM, CPU, Temp, Battery and network (U/D) enabled.
```sh
 ✔ lanthean@mba ➤ ~/mnt ➤ /Applications/Stats.app/Contents/MacOS/Stats                                  
Error call(READ_KEYINFO): (iokit/common) invalid argument
Error read(): (iokit/common) invalid argument
Error call(READ_KEYINFO): (iokit/common) invalid argument
Error read(): (iokit/common) invalid argument
2021-05-03 14:16:10.393 Stats[27147:7083104] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]'
*** First throw call stack:
(
        0   CoreFoundation                      0x000000018a8d3db8 __exceptionPreprocess + 240
        1   libobjc.A.dylib                     0x000000018a5fd0a8 objc_exception_throw + 60
        2   CoreFoundation                      0x000000018a99ebb4 -[__NSCFString characterAtIndex:].cold.1 + 0
        3   CoreFoundation                      0x000000018a9ac97c -[__NSPlaceholderDictionary initWithCapacity:].cold.1 + 0
        4   CoreFoundation                      0x000000018a7dca60 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 320
        5   CoreFoundation                      0x000000018a80e75c -[NSDictionary initWithDictionary:copyItems:] + 408
        6   CoreFoundation                      0x000000018a80e524 -[__NSPlaceholderDictionary initWithDictionary:copyItems:] + 172
        7   CoreText                            0x000000018be79678 _ZN11TAttributes9ApplyFontEPK14__CFDictionaryPK8__CTFontPK11TCharStream7CFRangePPKv + 252
        8   CoreText                            0x000000018be79430 _ZN11TAttributesC2EPK14__CFDictionaryPK11TCharStream7CFRange + 96
        9   CoreText                            0x000000018bdd4bc8 _ZN21TTypesetterAttrString10InitializeEPK20__CFAttributedString + 356
        10  CoreText                            0x000000018bdd48b8 _ZN21TTypesetterAttrStringC2EPK20__CFAttributedStringPK14__CFDictionary + 112
        11  CoreText                            0x000000018bdd4770 CTLineCreateWithAttributedString + 136
        12  UIFoundation                        0x000000018de060b4 -[NSCoreTypesetter _stringDrawingCoreTextEngineWithOriginalString:rect:padding:graphicsContext:forceClipping:attributes:stringDrawingOptions:drawingContext:stringDrawingInterface:] + 1808
        13  UIFoundation                        0x000000018dd4330c __NSStringDrawingEngine + 1964
        14  UIFoundation                        0x000000018dda78e0 -[NSAttributedString(NSExtendedStringDrawing) drawWithRect:options:context:] + 32
        15  ModuleKit                           0x00000001028248e8 block_destroy_helper.11 + 2344
        16  ModuleKit                           0x0000000102824468 block_destroy_helper.11 + 1192
        17  ModuleKit                           0x00000001028245a8 block_destroy_helper.11 + 1512
        18  AppKit                              0x000000018d1a6334 _NSViewDrawRect + 148
        19  AppKit                              0x000000018d8d7400 -[NSView _recursive:displayRectIgnoringOpacity:inContext:stopAtLayerBackedViews:] + 1312
        20  AppKit                              0x000000018d1a5ab4 -[NSView(NSLayerKitGlue) _drawViewBackingLayer:inContext:drawingHandler:] + 676
        21  QuartzCore                          0x0000000190b4b908 -[CALayer renderInContext:] + 1316
        22  QuartzCore                          0x0000000190b4d258 -[CALayer _renderSublayersInContext:] + 412
        23  QuartzCore                          0x0000000190b4b91c -[CALayer renderInContext:] + 1336
        24  QuartzCore                          0x0000000190b4d258 -[CALayer _renderSublayersInContext:] + 412
        25  QuartzCore                          0x0000000190b4b91c -[CALayer renderInContext:] + 1336
        26  AppKit                              0x000000018d8d6948 -[NSView _renderLayerInContext:] + 288
        27  AppKit                              0x000000018d8d7180 -[NSView _recursive:displayRectIgnoringOpacity:inContext:stopAtLayerBackedViews:] + 672
        28  AppKit                              0x000000018d326380 -[NSView displayRectIgnoringOpacity:inContext:] + 820
        29  AppKit                              0x000000018d325fe8 __62-[NSView cacheDisplayInRect:toBitmapImageRep:includeSubviews:]_block_invoke + 268
        30  AppKit                              0x000000018d325eb8 -[NSBitmapImageRep _captureDrawing:] + 80
        31  AppKit                              0x000000018d325e4c -[NSView cacheDisplayInRect:toBitmapImageRep:includeSubviews:] + 176
        32  AppKit                              0x000000018d7ad5a4 -[NSStatusItem _updateReplicant:] + 1380
        33  AppKit                              0x000000018d2e9d64 -[NSStatusItem _updateReplicants] + 220
        34  AppKit                              0x000000018d7adf50 -[NSStatusItem _updateReplicantsUnlessMenuIsTracking:] + 128
        35  Foundation                          0x000000018b619fe0 __NSFireDelayedPerform + 444
        36  CoreFoundation                      0x000000018a86fdb4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
        37  CoreFoundation                      0x000000018a86f9b0 __CFRunLoopDoTimer + 1076
        38  CoreFoundation                      0x000000018a86f438 __CFRunLoopDoTimers + 392
        39  CoreFoundation                      0x000000018a854644 __CFRunLoopRun + 1944
        40  CoreFoundation                      0x000000018a853734 CFRunLoopRunSpecific + 600
        41  HIToolbox                           0x0000000192751b84 RunCurrentEventLoopInMode + 292
        42  HIToolbox                           0x00000001927518f8 ReceiveNextEventCommon + 552
        43  HIToolbox                           0x00000001927516b8 _BlockUntilNextEventMatchingListInModeWithFilter + 72
        44  AppKit                              0x000000018d03d4ec _DPSNextEvent + 836
        45  AppKit                              0x000000018d03be8c -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1292
        46  AppKit                              0x000000018d02dd18 -[NSApplication run] + 596
        47  Stats                               0x000000010268fca8 Stats + 15528
        48  libdyld.dylib                       0x000000018a774420 start + 4
)
libc++abi: terminating with uncaught exception of type NSException
[1]    27147 abort      /Applications/Stats.app/Contents/MacOS/Stats
 ✘ lanthean@mba ➤ ~/mnt ➤ uname -a
Darwin mba 20.4.0 Darwin Kernel Version 20.4.0: Fri Mar  5 01:14:02 PST 2021; root:xnu-7195.101.1~3/RELEASE_ARM64_T8101 arm64
 ✔ lanthean@mba ➤ ~/mnt ➤
```

### Command that failed

/Applications/Stats.app/Contents/MacOS/Stats [--force (the same output)]

### Output of command with `--verbose --debug`

<details><summary>Click to expand</summary><pre><code>

 ✔ lanthean@mba ➤ ~/mnt ➤ /Applications/Stats.app/Contents/MacOS/Stats                                  
Error call(READ_KEYINFO): (iokit/common) invalid argument
Error read(): (iokit/common) invalid argument
Error call(READ_KEYINFO): (iokit/common) invalid argument
Error read(): (iokit/common) invalid argument
2021-05-03 14:16:10.393 Stats[27147:7083104] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]'
*** First throw call stack:
(
        0   CoreFoundation                      0x000000018a8d3db8 __exceptionPreprocess + 240
        1   libobjc.A.dylib                     0x000000018a5fd0a8 objc_exception_throw + 60
        2   CoreFoundation                      0x000000018a99ebb4 -[__NSCFString characterAtIndex:].cold.1 + 0
        3   CoreFoundation                      0x000000018a9ac97c -[__NSPlaceholderDictionary initWithCapacity:].cold.1 + 0
        4   CoreFoundation                      0x000000018a7dca60 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 320
        5   CoreFoundation                      0x000000018a80e75c -[NSDictionary initWithDictionary:copyItems:] + 408
        6   CoreFoundation                      0x000000018a80e524 -[__NSPlaceholderDictionary initWithDictionary:copyItems:] + 172
        7   CoreText                            0x000000018be79678 _ZN11TAttributes9ApplyFontEPK14__CFDictionaryPK8__CTFontPK11TCharStream7CFRangePPKv + 252
        8   CoreText                            0x000000018be79430 _ZN11TAttributesC2EPK14__CFDictionaryPK11TCharStream7CFRange + 96
        9   CoreText                            0x000000018bdd4bc8 _ZN21TTypesetterAttrString10InitializeEPK20__CFAttributedString + 356
        10  CoreText                            0x000000018bdd48b8 _ZN21TTypesetterAttrStringC2EPK20__CFAttributedStringPK14__CFDictionary + 112
        11  CoreText                            0x000000018bdd4770 CTLineCreateWithAttributedString + 136
        12  UIFoundation                        0x000000018de060b4 -[NSCoreTypesetter _stringDrawingCoreTextEngineWithOriginalString:rect:padding:graphicsContext:forceClipping:attributes:stringDrawingOptions:drawingContext:stringDrawingInterface:] + 1808
        13  UIFoundation                        0x000000018dd4330c __NSStringDrawingEngine + 1964
        14  UIFoundation                        0x000000018dda78e0 -[NSAttributedString(NSExtendedStringDrawing) drawWithRect:options:context:] + 32
        15  ModuleKit                           0x00000001028248e8 block_destroy_helper.11 + 2344
        16  ModuleKit                           0x0000000102824468 block_destroy_helper.11 + 1192
        17  ModuleKit                           0x00000001028245a8 block_destroy_helper.11 + 1512
        18  AppKit                              0x000000018d1a6334 _NSViewDrawRect + 148
        19  AppKit                              0x000000018d8d7400 -[NSView _recursive:displayRectIgnoringOpacity:inContext:stopAtLayerBackedViews:] + 1312
        20  AppKit                              0x000000018d1a5ab4 -[NSView(NSLayerKitGlue) _drawViewBackingLayer:inContext:drawingHandler:] + 676
        21  QuartzCore                          0x0000000190b4b908 -[CALayer renderInContext:] + 1316
        22  QuartzCore                          0x0000000190b4d258 -[CALayer _renderSublayersInContext:] + 412
        23  QuartzCore                          0x0000000190b4b91c -[CALayer renderInContext:] + 1336
        24  QuartzCore                          0x0000000190b4d258 -[CALayer _renderSublayersInContext:] + 412
        25  QuartzCore                          0x0000000190b4b91c -[CALayer renderInContext:] + 1336
        26  AppKit                              0x000000018d8d6948 -[NSView _renderLayerInContext:] + 288
        27  AppKit                              0x000000018d8d7180 -[NSView _recursive:displayRectIgnoringOpacity:inContext:stopAtLayerBackedViews:] + 672
        28  AppKit                              0x000000018d326380 -[NSView displayRectIgnoringOpacity:inContext:] + 820
        29  AppKit                              0x000000018d325fe8 __62-[NSView cacheDisplayInRect:toBitmapImageRep:includeSubviews:]_block_invoke + 268
        30  AppKit                              0x000000018d325eb8 -[NSBitmapImageRep _captureDrawing:] + 80
        31  AppKit                              0x000000018d325e4c -[NSView cacheDisplayInRect:toBitmapImageRep:includeSubviews:] + 176
        32  AppKit                              0x000000018d7ad5a4 -[NSStatusItem _updateReplicant:] + 1380
        33  AppKit                              0x000000018d2e9d64 -[NSStatusItem _updateReplicants] + 220
        34  AppKit                              0x000000018d7adf50 -[NSStatusItem _updateReplicantsUnlessMenuIsTracking:] + 128
        35  Foundation                          0x000000018b619fe0 __NSFireDelayedPerform + 444
        36  CoreFoundation                      0x000000018a86fdb4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
        37  CoreFoundation                      0x000000018a86f9b0 __CFRunLoopDoTimer + 1076
        38  CoreFoundation                      0x000000018a86f438 __CFRunLoopDoTimers + 392
        39  CoreFoundation                      0x000000018a854644 __CFRunLoopRun + 1944
        40  CoreFoundation                      0x000000018a853734 CFRunLoopRunSpecific + 600
        41  HIToolbox                           0x0000000192751b84 RunCurrentEventLoopInMode + 292
        42  HIToolbox                           0x00000001927518f8 ReceiveNextEventCommon + 552
        43  HIToolbox                           0x00000001927516b8 _BlockUntilNextEventMatchingListInModeWithFilter + 72
        44  AppKit                              0x000000018d03d4ec _DPSNextEvent + 836
        45  AppKit                              0x000000018d03be8c -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1292
        46  AppKit                              0x000000018d02dd18 -[NSApplication run] + 596
        47  Stats                               0x000000010268fca8 Stats + 15528
        48  libdyld.dylib                       0x000000018a774420 start + 4
)
libc++abi: terminating with uncaught exception of type NSException
[1]    27147 abort      /Applications/Stats.app/Contents/MacOS/Stats
 ✘ lanthean@mba ➤ ~/mnt ➤ uname -a
Darwin mba 20.4.0 Darwin Kernel Version 20.4.0: Fri Mar  5 01:14:02 PST 2021; root:xnu-7195.101.1~3/RELEASE_ARM64_T8101 arm64
 ✔ lanthean@mba ➤ ~/mnt ➤

</code></pre></details>

### Output of `brew doctor --verbose`

<details><summary>Click to expand</summary><pre><code>

 ✔ lanthean@mba ➤ ~ ➤ brew doctor --verbose
==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
==> $LOAD_PATHS
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/warning-1.2.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tapioca-0.4.21/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/spoom-1.0.9/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thor-1.1.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-stub-0.2.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-cobertura-1.4.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-0.21.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov_json_formatter-0.1.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-html-0.12.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.5.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-sorbet-0.6.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-2.3.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rails-2.9.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.11.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-1.13.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unicode-display_width-2.0.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.11.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-ast-1.4.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-sorbet-1.8.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-0.5.6274/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-static-0.5.6274-universal-darwin-14/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-github-2.3.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-3.10.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-mocks-3.10.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-expectations-3.10.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-core-3.10.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-support-3.10.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.5/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/regexp_parser-2.1.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rdiscount-2.2.0.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/rdiscount-2.2.0.2
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rack-2.2.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/pry-0.14.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.6.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/patchelf-1.3.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parlour-6.0.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-0.5.6274/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.0.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parser-3.0.1.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel_tests-3.7.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel-1.20.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/method_source-1.0.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.8.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrick-1.7.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubyntlm-0.6.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.11.3-x86_64-darwin/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/racc-1.5.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/racc-1.5.2
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.5.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-4.0.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.3.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-data-3.2021.0225/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/hpricot-0.8.6
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/elftools-1.1.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.7.7/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/unf_ext-0.0.7.7
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.3.5/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.4.4/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/commander-4.6.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/highline-2.0.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/colorize-0.8.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/coderay-1.1.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/byebug-11.1.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/byebug-11.1.3
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bootsnap-1.7.4/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/bootsnap-1.7.4
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/msgpack-1.4.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/msgpack-1.4.2
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bindata-2.4.8/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ast-2.4.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/addressable-2.7.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/public_suffix-4.0.6/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.1.3.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.4.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-2.0.4/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/minitest-5.14.4/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.9/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/arm64e-darwin20
/Library/Ruby/Site/2.6.0/universal-darwin20
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/arm64e-darwin20
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin20
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/arm64e-darwin20
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin20
/opt/homebrew/Library/Homebrew
==> Homebrew Version
3.1.5-18-g4f4fb49
==> macOS
11.3
==> SIP
Enabled
==> Homebrew Cask Staging Location
/opt/homebrew/Caskroom
==> Homebrew Cask Taps:
/opt/homebrew/Library/Taps/homebrew/homebrew-cask (3890 casks)
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: /usr/bin occurs before /opt/homebrew/bin in your PATH.
This means that system-provided programs will be used instead of those
provided by Homebrew. Consider setting your PATH so that
/opt/homebrew/bin occurs before /usr/bin. Here is a one-liner:
  echo 'export PATH="/opt/homebrew/bin:$PATH"' >> /Users/lanthean/.bash_profile

The following tools exist at both paths:
  git-receive-pack
  python3
  pip3
  bashbug
  git-upload-archive
  git-shell
  git-upload-pack
  git

</code></pre></details>

### Output of `brew tap`

<details><summary>Click to expand</summary><pre><code>
homebrew/cask
homebrew/core 
</code></pre></details>

**Comment by carlocab** [comment]
This looks like a problem with the software itself, and not with the cask. Do you not encounter the same problem if you install this software without using Homebrew?

**Comment by lanthean** [comment]
It did not occur to me, to make such distinction.

**Comment by lanthean** [comment]
Let me copy it to the Stats branch and close it here.
