### ISSUE TITLE
Installation of plover fails with 'It seems the App source it not there'-error

### ISSUE THREAD

**Issue by jottr** [Homebrew/homebrew-cask#104921]
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

Installation of `plover 3.1.1` fails with `Error: It seems the App source '/usr/local/Caskroom/plover/3.1.1/Plover.app' is not there.`

### Command that failed

brew install plover

### Output of command with `--verbose --debug`

<details><summary>Click to expand</summary><pre><code>

==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://github.com/openstenoproject/plover/releases/download/v3.1.1/plover-3.1.1-py2-mac.dmg
Already downloaded: /Users/jottr/Library/Caches/Homebrew/downloads/757e769f57a5e2cdc64045bf8d7e966774bdcb858a16a6d9ff0e95dc746385a0--plover-3.1.1-py2-mac.dmg
==> Checking quarantine support
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/jottr/Library/Caches/Homebrew/downloads/757e769f57a5e2cdc64045bf8d7e966774bdcb858a16a6d9ff0e95dc746385a0--plover-3.1.1-py2-mac.dmg
==> /Users/jottr/Library/Caches/Homebrew/downloads/757e769f57a5e2cdc64045bf8d7e966774bdcb858a16a6d9ff0e95dc746385a0--plover-3.1.1-py2-mac.dmg is quarantined
==> Verifying checksum for cask 'plover'
==> Installing Cask plover
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/jottr/Library/Caches/Homebrew/downloads/757e769f57a5e2cdc64045bf8d7e966774bdcb858a16a6d9ff0e95dc746385a0--plover-3.1.1-py2-mac.dmg
==> Verifying Gatekeeper status of /Users/jottr/Library/Caches/Homebrew/downloads/757e769f57a5e2cdc64045bf8d7e966774bdcb858a16a6d9ff0e95dc746385a0--plover-3.1.1-py2-mac.dmg
==> /Users/jottr/Library/Caches/Homebrew/downloads/757e769f57a5e2cdc64045bf8d7e966774bdcb858a16a6d9ff0e95dc746385a0--plover-3.1.1-py2-mac.dmg is quarantined
==> Propagating quarantine from /Users/jottr/Library/Caches/Homebrew/downloads/757e769f57a5e2cdc64045bf8d7e966774bdcb858a16a6d9ff0e95dc746385a0--plover-3.1.1-py2-mac.dmg to /usr/local/Caskroom/plover/3.1.1
==> Creating metadata directory: /usr/local/Caskroom/plover/.metadata/3.1.1/20210502153235.382
==> Creating metadata subdirectory: /usr/local/Caskroom/plover/.metadata/3.1.1/20210502153235.382/Casks
==> Installing artifacts
==> 2 artifacts defined
#<SortedSet: {#<Cask::Artifact::App:0x00007fe912343f70 @cask=#<Cask::Cask:0x00007fe912288bf8 @token="plover", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/plover.rb>, @tap=#<Tap:0x00007fe9121894c8 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @formula_renames={}, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fe912288b08@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/plover.rb:1>, @default_config=#<Cask::Config:0x00007fe9122785f0 @explicit={}, @env={}, @default={:languages=>["en-DE", "de-DE"], :appdir=>#<Pathname:/Applications>, :colorpickerdir=>#<Pathname:/Users/jottr/Library/ColorPickers>, :prefpanedir=>#<Pathname:/Users/jottr/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Users/jottr/Library/QuickLook>, :mdimporterdir=>#<Pathname:/Users/jottr/Library/Spotlight>, :dictionarydir=>#<Pathname:/Users/jottr/Library/Dictionaries>, :fontdir=>#<Pathname:/Users/jottr/Library/Fonts>, :servicedir=>#<Pathname:/Users/jottr/Library/Services>, :input_methoddir=>#<Pathname:/Users/jottr/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Users/jottr/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Users/jottr/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Users/jottr/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Users/jottr/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Users/jottr/Library/Screen Savers>}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/plover>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/plover/.metadata>, @config=#<Cask::Config:0x00007fe9123393e0 @explicit={}, @env={}, @default={:languages=>["en-DE", "de-DE"], :appdir=>#<Pathname:/Applications>, :colorpickerdir=>#<Pathname:/Users/jottr/Library/ColorPickers>, :prefpanedir=>#<Pathname:/Users/jottr/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Users/jottr/Library/QuickLook>, :mdimporterdir=>#<Pathname:/Users/jottr/Library/Spotlight>, :dictionarydir=>#<Pathname:/Users/jottr/Library/Dictionaries>, :fontdir=>#<Pathname:/Users/jottr/Library/Fonts>, :servicedir=>#<Pathname:/Users/jottr/Library/Services>, :input_methoddir=>#<Pathname:/Users/jottr/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Users/jottr/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Users/jottr/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Users/jottr/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Users/jottr/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Users/jottr/Library/Screen Savers>}>, @dsl=#<Cask::DSL:0x00007fe912339110 @cask=#<Cask::Cask:0x00007fe912288bf8 ...>, @token="plover", @version="3.1.1", @sha256=#<Checksum:0x00007fe912338df0 @hexdigest="c45c1c6cf797de62923d20e6e46aec0d946027b6b3cca4df2fc2db4e3183516b">, @url=#<URL::DSL:0x00007fe9123388a0 @uri=#<URI::HTTPS https://github.com/openstenoproject/plover/releases/download/v3.1.1/plover-3.1.1-py2-mac.dmg>, @verified="github.com/openstenoproject/plover/", @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @specs={:verified=>"github.com/openstenoproject/plover/", :user_agent=>:default}>, @name=["Plover"], @desc="Open-source stenotype engine", @homepage="https://www.openstenoproject.org/plover/", @livecheck=#<Livecheck:0x00007fe912338328 @formula_or_cask=#<Cask::DSL:0x00007fe912339110 ...>, @regex=nil, @skip=false, @skip_msg=nil, @strategy=:github_latest, @url=:url>, @livecheckable=true, @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/plover/3.1.1>, @language_eval=nil>>, @source_string="Plover.app", @target_string="", @source=#<Pathname:/usr/local/Caskroom/plover/3.1.1/Plover.app>, @target=#<Pathname:/Applications/Plover.app>>, #<Cask::Artifact::Zap:0x00007fe9123414f0 @cask=#<Cask::Cask:0x00007fe912288bf8 @token="plover", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/plover.rb>, @tap=#<Tap:0x00007fe9121894c8 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @formula_renames={}, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fe912288b08@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/plover.rb:1>, @default_config=#<Cask::Config:0x00007fe9122785f0 @explicit={}, @env={}, @default={:languages=>["en-DE", "de-DE"], :appdir=>#<Pathname:/Applications>, :colorpickerdir=>#<Pathname:/Users/jottr/Library/ColorPickers>, :prefpanedir=>#<Pathname:/Users/jottr/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Users/jottr/Library/QuickLook>, :mdimporterdir=>#<Pathname:/Users/jottr/Library/Spotlight>, :dictionarydir=>#<Pathname:/Users/jottr/Library/Dictionaries>, :fontdir=>#<Pathname:/Users/jottr/Library/Fonts>, :servicedir=>#<Pathname:/Users/jottr/Library/Services>, :input_methoddir=>#<Pathname:/Users/jottr/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Users/jottr/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Users/jottr/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Users/jottr/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Users/jottr/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Users/jottr/Library/Screen Savers>}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/plover>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/plover/.metadata>, @config=#<Cask::Config:0x00007fe9123393e0 @explicit={}, @env={}, @default={:languages=>["en-DE", "de-DE"], :appdir=>#<Pathname:/Applications>, :colorpickerdir=>#<Pathname:/Users/jottr/Library/ColorPickers>, :prefpanedir=>#<Pathname:/Users/jottr/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Users/jottr/Library/QuickLook>, :mdimporterdir=>#<Pathname:/Users/jottr/Library/Spotlight>, :dictionarydir=>#<Pathname:/Users/jottr/Library/Dictionaries>, :fontdir=>#<Pathname:/Users/jottr/Library/Fonts>, :servicedir=>#<Pathname:/Users/jottr/Library/Services>, :input_methoddir=>#<Pathname:/Users/jottr/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Users/jottr/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Users/jottr/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Users/jottr/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Users/jottr/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Users/jottr/Library/Screen Savers>}>, @dsl=#<Cask::DSL:0x00007fe912339110 @cask=#<Cask::Cask:0x00007fe912288bf8 ...>, @token="plover", @version="3.1.1", @sha256=#<Checksum:0x00007fe912338df0 @hexdigest="c45c1c6cf797de62923d20e6e46aec0d946027b6b3cca4df2fc2db4e3183516b">, @url=#<URL::DSL:0x00007fe9123388a0 @uri=#<URI::HTTPS https://github.com/openstenoproject/plover/releases/download/v3.1.1/plover-3.1.1-py2-mac.dmg>, @verified="github.com/openstenoproject/plover/", @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @specs={:verified=>"github.com/openstenoproject/plover/", :user_agent=>:default}>, @name=["Plover"], @desc="Open-source stenotype engine", @homepage="https://www.openstenoproject.org/plover/", @livecheck=#<Livecheck:0x00007fe912338328 @formula_or_cask=#<Cask::DSL:0x00007fe912339110 ...>, @regex=nil, @skip=false, @skip_msg=nil, @strategy=:github_latest, @url=:url>, @livecheckable=true, @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/plover/3.1.1>, @language_eval=nil>>, @directives={:trash=>"~/Library/Application Support/plover/", :signal=>[]}>}>
==> Installing artifact of class Cask::Artifact::App
==> Purging files for version 3.1.1 of Cask plover

</code></pre></details>

### Output of `brew doctor --verbose`

<details><summary>Click to expand</summary><pre><code>

==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
==> $LOAD_PATHS
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/warning-1.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tapioca-0.4.21/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/spoom-1.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thor-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-stub-0.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-cobertura-1.4.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-0.21.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov_json_formatter-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-html-0.12.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-sorbet-0.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-2.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rails-2.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.11.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-1.13.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unicode-display_width-2.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.11.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-ast-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-sorbet-1.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-0.5.6274/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-static-0.5.6274-universal-darwin-14/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-github-2.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-3.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-mocks-3.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-expectations-3.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-core-3.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-support-3.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/regexp_parser-2.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rdiscount-2.2.0.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/rdiscount-2.2.0.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rack-2.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/pry-0.14.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/patchelf-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parlour-6.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-0.5.6274/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parser-3.0.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel_tests-3.7.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel-1.20.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/method_source-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrick-1.7.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubyntlm-0.6.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.11.3-x86_64-darwin/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/racc-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/racc-1.5.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-4.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-data-3.2021.0225/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/elftools-1.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.7.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/unf_ext-0.0.7.7
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.3.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.4.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/commander-4.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/highline-2.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/colorize-0.8.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/coderay-1.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/byebug-11.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/byebug-11.1.3
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bootsnap-1.7.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/bootsnap-1.7.4
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/msgpack-1.4.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/msgpack-1.4.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bindata-2.4.8/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ast-2.4.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/addressable-2.7.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/public_suffix-4.0.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.1.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.4.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-2.0.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/minitest-5.14.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/site_ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/site_ruby/2.6.0/x86_64-darwin14
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/vendor_ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/vendor_ruby/2.6.0/x86_64-darwin14
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/x86_64-darwin14
/usr/local/Homebrew/Library/Homebrew
==> Homebrew Version
3.1.5-12-g4444b70
==> macOS
10.15.7
==> SIP
Enabled
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3894 casks)
/usr/local/Homebrew/Library/Taps/hashicorp/homebrew-tap (1 cask)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (187 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1724 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (177 casks)

</code></pre></details>

### Output of `brew tap`

<details><summary>Click to expand</summary><pre><code>

acrogenesis/macchanger
browsh-org/browsh
caarlos0/antibody
dart-lang/dart
denisidoro/tools
drgrib/tap
fabianishere/personal
hashicorp/tap
heroku/brew
homebrew/bundle
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/services
jesseduffield/lazygit
koekeishiya/formulae
laurent22/massren
moncho/dry
mopidy/mopidy
neovim/neovim
pebble/pebble-sdk
rigellute/tap
rockymadden/rockymadden
ryanfb/alicevision
sachaos/todoist
sass/sass
saulpw/vd
vitorgalvao/tiny-scripts
wata727/tflint
wtfutil/wtfutil
zegervdv/zathura

</code></pre></details>

**Comment by miccal** [comment]
[Our CI machines cannot reproduce this](https://github.com/Homebrew/homebrew-cask/pull/105307), and this also install fine for me locally. Please try installing again.

**Comment by SMillerDev** [comment]
Between a CI run and now 2 maintainers running this without issues locally, it's something in your configuration. I'd recommend checking virusscanners or similar software. Unless more users have this issue there is no reason to believe it's a brew issue.

**Comment by carlocab** [comment]
Can't reproduce this either:
```
❯ brew install plover
==> Downloading https://github.com/openstenoproject/plover/releases/download/v3.1.1/plover-3.1.1-py2-mac.dmg
Already downloaded: /Users/chisquared/Library/Caches/Homebrew/downloads/757e769f57a5e2cdc64045bf8d7e966774bdcb858a16a6d9ff0e95dc746385a0--plover-3.1.1-py2-mac.dmg
==> Installing Cask plover
==> Moving App 'Plover.app' to '/Applications/Plover.app'
🍺  plover was successfully installed!
```

> just because you can't reproduce the error, doesn't mean it that there is no error with the cask.

This might be true. However, given evidence so far, it is much, much more likely that the problem has more to do with your local configuration than with the cask.

Moreover, even if there were a problem with the cask, the fact that we're unable to reproduce it makes the problem non-actionable. Open issues should reflect actionable items.

Sorry.

**Comment by jottr** [comment]
The file properly downloads: 

```
Downloading https://github.com/openstenoproject/plover/releases/download/v3.1.1/plover-3.1.1-py2-mac.dmg
Already downloaded: /Users/jottr/Library/Caches/Homebrew/downloads/757e769f57a5e2cdc64045bf8d7e966774bdcb858a16a6d9ff0e95dc746385a0--plover-3.1.1-py2-mac.dmg
```

And matches the expected `sha256` sum:

```
 sha256sum /Users/jottr/Library/Caches/Homebrew/downloads/757e769f57a5e2cdc64045bf8d7e966774bdcb858a16a6d9ff0e95dc746385a0--plover-3.1.1-py2-mac.dmg
c45c1c6cf797de62923d20e6e46aec0d946027b6b3cca4df2fc2db4e3183516b  /Users/jottr/Library/Caches/Homebrew/downloads/757e769f57a5e2cdc64045bf8d7e966774bdcb858a16a6d9ff0e95dc746385a0--plover-3.1.1-py2-mac.dmg
```

I can manually install from that very `.dmg` without issue.

**Comment by carlocab** [comment]
What's the output of `brew config`?

**Comment by jottr** [comment]
```
$ brew config

HOMEBREW_VERSION: 3.1.5-101-gd3013fc
ORIGIN: https://github.com/Homebrew/brew
HEAD: d3013fcbc1c2424ae5deafd36d4f0bd79065984c
Last commit: 23 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fe47217500e2c2131751e5dec2bb32b3da77eff4
Core tap last commit: 45 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.Sp94AXR5FU/org.macosforge.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.0.0.32.29
Xcode: 12.4
XQuartz: 2.7.11 => /opt/X11
```
