### ISSUE TITLE
mysqlworkbench 8.0.24 problem on macOS Catalina 10.15.7

### ISSUE THREAD

**Issue by karololszacki** [Homebrew/homebrew-cask#105183]
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

Very similar to #91416 which was fixed by #91418.

Running `brew cask install mysqlworkbench` works, and the App is added to the Applications folder, however when trying to run it errors with:

```
You can’t use this version of the application “MySQLWorkbench” with this version of macOS. You have macOS 10.15.7. The application requires macOS 11.2 or later
```

I think mysqlworkbench.rb needs updating to add a new section to only install the latest version on macOS version 11.2 and higher and an older version on Catalina (but I don't know if 8.0.23 worked, or if 8.0.22 is needed).

**Comment by carlocab** [comment]
Thanks for the report. Please open a pull request for this; it should be very similar to #91418.

**Comment by karololszacki** [comment]
I downloaded 8.0.23 and installed manually, but now macOS complains that "Apple cannot verify if it doesn't contain malicious software" and asks me to upgrade it to new version...

**Comment by cho-m** [comment]
@karololszacki that is a common warning for unsigned apps.
See: https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/app_cant_be_opened.md
The warning message is different but reason is the same Gatekeeper protection.

As long as Oracle/MySql doesn't sign the apps with Apple Developer ID, the warning will show up.
Follow the steps to disable Gatekeeper and make sure it runs.
Then you can open a PR for this.
