### ISSUE TITLE
retroarch-metal-1.9.2 SHA mismatch

### ISSUE THREAD

**Issue by hermitmaster** [Homebrew/homebrew-cask#105417]
https://github.com/Homebrew/homebrew-cask/blob/b7ad5efd44bcdc067546f9044f965efbbc453cfb/Casks/retroarch-metal.rb#L3

```
Error: SHA256 mismatch
Expected: 73d2f50f61967b0720c10ea2c2080de696513ea0973ddd421d277b3e26390057
  Actual: d0b6b6a126b1649790c14da54802dcde4df42c711ab46ecffa5ce5d646b801a6
```

**Comment by carlocab** [comment]
https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md
