### ISSUE TITLE
Fix permissions when uninstalling vmware-fusion cask with zap stanza

### ISSUE THREAD

**Issue by mariobrostech** [Homebrew/homebrew-cask#105535]
Hi,

When uninstalling the VMware Fusion cask with a zap stanza, the vast majority of the files are unable to be deleted due to not prompting for the sudo password for permission to delete files from system directories. Is there any way this can be remedied so that the program can be completely uninstalled when utilizing the zap stanza?

Thank you in advance!

**Comment by carlocab** [comment]
Please use the issue template when opening issues here, thank you.

https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md#if-your-issue-was-closed-without-review

**Comment by mariobrostech** [comment]
Sorry about that! I have re-opened this issue with the proper issue template at #105537
