### ISSUE TITLE
Please upgrade StarUML

### ISSUE THREAD

**Issue by diguage** [Homebrew/homebrew-cask#105920]
### Provide a detailed description of the proposed feature

Please upgrade StarUML.

https://staruml.io/download

![image](https://user-images.githubusercontent.com/2121467/118465820-da162980-b734-11eb-99df-ce276de3725f.png)

![image](https://user-images.githubusercontent.com/2121467/118465936-f619cb00-b734-11eb-97b0-f055459b5d13.png)

### What is the motivation for the feature?

NO

### Example use case

NO

**Comment by SMillerDev** [comment]
https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask
