### ISSUE TITLE
Cask for Jetbrains Toolbox for Apple Silicon

### ISSUE THREAD

**Issue by eduardbosch** [Homebrew/homebrew-cask#106768]
### Provide a detailed description of the proposed feature

The current Jetbrains Toolbox cask installs the Intel version.
https://formulae.brew.sh/cask/jetbrains-toolbox#default

Can anyone add the Jetbrains Toolbox cask for the Apple Silicon?

https://www.jetbrains.com/toolbox-app/
![Toolbox App](https://user-images.githubusercontent.com/3925897/120662210-3beec700-c489-11eb-86aa-efff8ca9b4b7.png)

Many thanks ❤️

### What is the motivation for the feature?

Allow installing the Apple Silicon version for performance.

### Example use case

-

**Comment by cho-m** [comment]
Homebrew/cask already supports the Apple Silicon version. See:

https://github.com/Homebrew/homebrew-cask/blob/72f0ae47485758deacb2df31a5c63dd95e13b143/Casks/jetbrains-toolbox.rb#L4-L12

**Comment by eduardbosch** [comment]
Thanks @cho-m!

Sorry to open an issue for a request @SMillerDev, I'll take a look at the guide to create a new cask for the next time 🙂
