### ISSUE TITLE
How to fix the error "Cask 'sectionctl' is unreadable: wrong constant name #<Class:0x00000000034d64a0>"

### ISSUE THREAD

**Issue by AskAlice** [Homebrew/homebrew-cask#106833]
When I run 
```
brew install --build-bottle --verbose /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sectionctl.rb
```

it returns with exit 1 after successfully installing the binary, with the following errors/warnings

```
Error: Failed to load cask: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/Sectionctl.rb
Cask 'sectionctl' is unreadable: wrong constant name #<Class:0x00000000034d64a0>
Warning: Treating /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sectionctl.rb as a formula.
... build output ...
```

here is my formula
```rb
class Sectionctl < Formula
  version "1.11.1"
  desc "sectionctl Commandline Tools"
  homepage "https://github.com/section/sectionctl"
  url "https://github.com/section/sectionctl/archive/refs/tags/v#{version}.tar.gz"
  sha256 "5d3b47ea1b2641aa312e13a8bd282cb3aeb7caa540585e8f600dd621a3b1bfda"
  license "MIT"

  depends_on "go" => :build

  def install
    goos = `go env GOOS`.strip
    goarch = `go env GOARCH`.strip
    ENV["VERSION"] = "v#{version}"
    system "make", "build-release", "GOOS=#{goos}", "GOARCH=#{goarch}"
    bin.install "dist/sectionctl-v#{version}-#{goos}-#{goarch}/sectionctl"
    prefix.install "dist/sectionctl-v#{version}-#{goos}-#{goarch}/LICENSE"
    prefix.install "dist/sectionctl-v#{version}-#{goos}-#{goarch}/README.md"
  end

  test do
    system "#{bin}/sectionctl", "--help"
  end
end

```

What am I doing wrong?

**Comment by carlocab** [comment]
Don't pass a path to `brew install`. Instead, do `brew install --build-bottle --verbose sectionctl`.

**Comment by AskAlice** [comment]
@carlocab That would be possible if it weren't testing these in the CI for a tap 
https://github.com/section/homebrew-section/runs/2754442964

**Comment by carlocab** [comment]
I don't see why it's not possible. `brew install foo` should resolve to installing `$(brew --repo homebrew/core)/Formula/foo.rb` as long as this formula file exists.

**Comment by AskAlice** [comment]
@carlocab, thanks that's much better! set that up for section/homebrew-brews . does it bottle for arm64 on macos and linux?

**Comment by carlocab** [comment]
If you run it on ARM CI, yes. `brew` doesn't support cross-compilation. However, If `go` will cross-compile for you by just setting `GOOS` and `GOARCH`, you might be able to make it work, but `test-bot` will still assume the built bottle is for an Intel machine.

Anyway, it looks like your original problem is solved now, so I'm closing this.

**Comment by AskAlice** [comment]
thanks :)
