### ISSUE TITLE
Wolfram Engine cask can't be bumped

### ISSUE THREAD

**Issue by pthariensflame** [Homebrew/homebrew-cask#106909]
Version 12.3.0.0 of `wolfram-engine` is available, but upon trying to use `bump-cask-pr` it fails to download.  Manually altering the cask produces similar results.

It seems as if the new URL is of the form `https://files.wolframcdn.com/packages/Homebrew/12.3.0.0/WolframEngine_12.3.0_MAC.dmg?`*hash*`MAC_.dmg`, where *hash* is some hash that changes every download.  `https://account.wolfram.com/download/public/wolfram-engine/desktop/MAC` gets the correct download by redirection but doesn't encode the version number anymore.

What should be done?

**Comment by ConnorGray** [comment]
I've just uploaded our WE 12.3 dmg file to:

    https://files.wolframcdn.com/packages/Homebrew/12.3.0.0/WolframEngine_12.3.0_MAC.dmg

so @pthariensflame I believe it should be possible for you to proceed with running `bumb-cask-pr`.

I apologize for the delay in uploading this file. We're working to update our release process to ensure that these file stay in-sync.

Please let me know if this fixes the issue, and if there is any further action we can take.

**Comment by miccal** [comment]
@ConnorGray is there any chance you can add something like `https://files.wolframcdn.com/packages/Homebrew/latest.txt` which lists the version `12.3.0.0` so we can add a `livecheck`?

**Comment by cho-m** [comment]
Created #107383 to close this.

For now, we can livecheck headers on unversioned download URL; however, if Homebrew-specific download link is not updated at same time, then it can lead to similar issue as this where bump cask fails.
