### ISSUE TITLE
zoom: Failure while executing; `/usr/bin/kill -f //Applications/zoom.us.app` exited with 1.

### ISSUE THREAD

**Issue by berndkrannich** [Homebrew/homebrew-cask#107182]
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

Since 3a53ea8, I am getting the following error:

```
zoom: Failure while executing; `/usr/bin/kill -f //Applications/zoom.us.app` exited with 1.
```

and the upgrade fails. I believe this is due to the double `/` because running the above command with `/Applications` on the command line stops Zoom as intended.

### Command that failed

brew upgrade --cask zoom

### Output of command with `--verbose --debug`

<details><summary>Click to expand</summary><pre><code>

==> Upgrading 1 outdated package:
zoom 5.6.6.950 -> 5.6.7.1020
==> Started upgrade process for Cask zoom
==> Upgrading zoom

...

installer: The upgrade was successful.
Error: zoom: Failure while executing; `/usr/bin/pkill -f //Applications/zoom.us.app` exited with 1.
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:138:in `upgrade_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:215:in `upgrade_outdated_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:107:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'

</code></pre></details>

### Output of `brew doctor --verbose`

<details><summary>Click to expand</summary><pre><code>

==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
==> $LOAD_PATHS

...

==> Homebrew Version
3.1.12-13-gc9fdecc
==> macOS
11.4
==> SIP
Enabled
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3920 casks)
/usr/local/Homebrew/Library/Taps/sap/homebrew-sapmachine (26 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (192 casks)

</code></pre></details>

### Output of `brew tap`

<details><summary>Click to expand</summary><pre><code>

homebrew/cask
homebrew/cask-versions
homebrew/core
homebrew/services
mas-cli/tap

</code></pre></details>

**Comment by berndkrannich** [comment]
Probably, 7b37ec3 will let the upgrade succeed, albeit with an error message instead of fixing what I expect is the root cause (see above).

**Comment by cho-m** [comment]
One thing to note is that, by default, there should be no double-slash unless you pass it in as input.

Homebrew's default appdir is `/Applications` and that is what will be used in `zoom` cask.
For example, here is part of output if I `brew install --debug --verbose zoom`
```
==> Installing artifact of class Cask::Artifact::PostflightBlock
ps x
/usr/bin/pkill -f /Applications/zoom.us.app
```

---

Most likely, the extra slash should be something you added.
For example, using `--appdir //Applications` in install command or running a wrapper script/tool that does something similar.

---

Anyway, since `zoom` uses a package installer that ignores `--appdir` input and always installs to `/Applications`, we can fix the path.

**Comment by berndkrannich** [comment]
> Most likely, the extra slash should be something you added.

@cho-m: My bad, you are completely right. I indeed had `HOMEBREW_CASK_OPTS` wrongly configured with two slashes. Thank you very much for the hint!

I'm closing this issue unless you want me to re-open it based on your last sentence above.
