### ISSUE TITLE
Homebrew installation fails because it tries to install wrong version of cask

### ISSUE THREAD

**Issue by fasmat** [Homebrew/homebrew-cask#107101]
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

I have my own Tap of a few casks that fail to install for the last 2 days. It seems as if hombrew tries to install the wrong version (978.2j) instead of the version specified in the cask (981.3b). See here: https://github.com/fasmat/homebrew-trader-workstation/blob/main/Casks/trader-workstation.rb

### Command that failed

brew install --cask fasmat/trader-workstation/trader-workstation

### Output of command with `--verbose --debug`

<details><summary>Click to expand</summary><pre><code>

==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://download2.interactivebrokers.com/installers/tws/stable-standalone/tws-stable-standalone-macosx-x64.dmg
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.1.11-45-g33e71c9\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.7\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://download2.interactivebrokers.com/installers/tws/stable-standalone/tws-stable-standalone-macosx-x64.dmg
Already downloaded: /Users/mafa/Library/Caches/Homebrew/downloads/ecef478e8a2f6f113371ee5fa27304a1c097e5df8f8c33bbca343713f9b9f8eb--tws-stable-standalone-macosx-x64.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/mafa/Library/Caches/Homebrew/downloads/ecef478e8a2f6f113371ee5fa27304a1c097e5df8f8c33bbca343713f9b9f8eb--tws-stable-standalone-macosx-x64.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/mafa/Library/Caches/Homebrew/downloads/ecef478e8a2f6f113371ee5fa27304a1c097e5df8f8c33bbca343713f9b9f8eb--tws-stable-standalone-macosx-x64.dmg
==> /Users/mafa/Library/Caches/Homebrew/downloads/ecef478e8a2f6f113371ee5fa27304a1c097e5df8f8c33bbca343713f9b9f8eb--tws-stable-standalone-macosx-x64.dmg is quarantined
Warning: No checksum defined for cask 'trader-workstation', skipping verification.
hdiutil imageinfo -format /Users/mafa/Library/Caches/Homebrew/downloads/ecef478e8a2f6f113371ee5fa27304a1c097e5df8f8c33bbca343713f9b9f8eb--tws-stable-standalone-macosx-x64.dmg
==> Installing Cask trader-workstation
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/mafa/Library/Caches/Homebrew/downloads/ecef478e8a2f6f113371ee5fa27304a1c097e5df8f8c33bbca343713f9b9f8eb--tws-stable-standalone-macosx-x64.dmg
hdiutil attach -plist -nobrowse -readonly -mountrandom /private/tmp/d20210611-65073-12xr6ww /Users/mafa/Library/Caches/Homebrew/downloads/ecef478e8a2f6f113371ee5fa27304a1c097e5df8f8c33bbca343713f9b9f8eb--tws-stable-standalone-macosx-x64.dmg
find . -print0
mkbom -s -i /private/tmp/20210611-65073-aq0cxz.list -- /private/tmp/20210611-65073-a4k380.bom
ditto --bom /private/tmp/20210611-65073-a4k380.bom -- /private/tmp/d20210611-65073-12xr6ww/dmg.6T1kl7 /private/tmp/d20210611-65073-1lef23u
diskutil info -plist /private/tmp/d20210611-65073-12xr6ww/dmg.6T1kl7
diskutil eject /private/tmp/d20210611-65073-12xr6ww/dmg.6T1kl7
cp -pR /private/tmp/d20210611-65073-1lef23u/Trader\ Workstation\ 981\ Installer.app/. /usr/local/Caskroom/trader-workstation/978.2j/Trader\ Workstation\ 981\ Installer.app
chmod -Rf +w /private/tmp/d20210611-65073-1lef23u
==> Verifying Gatekeeper status of /Users/mafa/Library/Caches/Homebrew/downloads/ecef478e8a2f6f113371ee5fa27304a1c097e5df8f8c33bbca343713f9b9f8eb--tws-stable-standalone-macosx-x64.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/mafa/Library/Caches/Homebrew/downloads/ecef478e8a2f6f113371ee5fa27304a1c097e5df8f8c33bbca343713f9b9f8eb--tws-stable-standalone-macosx-x64.dmg
==> /Users/mafa/Library/Caches/Homebrew/downloads/ecef478e8a2f6f113371ee5fa27304a1c097e5df8f8c33bbca343713f9b9f8eb--tws-stable-standalone-macosx-x64.dmg is quarantined
==> Propagating quarantine from /Users/mafa/Library/Caches/Homebrew/downloads/ecef478e8a2f6f113371ee5fa27304a1c097e5df8f8c33bbca343713f9b9f8eb--tws-stable-standalone-macosx-x64.dmg to /usr/local/Caskroom/trader-workstation/978.2j
/usr/bin/xattr -p com.apple.quarantine /Users/mafa/Library/Caches/Homebrew/downloads/ecef478e8a2f6f113371ee5fa27304a1c097e5df8f8c33bbca343713f9b9f8eb--tws-stable-standalone-macosx-x64.dmg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;60c325c4\;Homebrew\\x20Cask\;D2F6D198-0541-4D45-8B29-4B3E4E39DEB5
==> Creating metadata directory: /usr/local/Caskroom/trader-workstation/.metadata/978.2j/20210611091018.093
==> Creating metadata subdirectory: /usr/local/Caskroom/trader-workstation/.metadata/978.2j/20210611091018.093/Casks
==> Installing artifacts
==> 2 artifacts defined
#<SortedSet: {#<Cask::Artifact::Uninstall:0x00007fed3c24a7a8 @cask=#<Cask::Cask:0x00007fed3c0dfc38 @token="trader-workstation", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/trader-workstation.rb>, @tap=#<Tap:0x00007fed580f03f0 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @formula_renames={}, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fed3c0df940@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/trader-workstation.rb:1>, @default_config=#<Cask::Config:0x00007fed5817bb08 @explicit={}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/trader-workstation>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/trader-workstation/.metadata>, @config=#<Cask::Config:0x00007fed3c240d98 @explicit={}>, @dsl=#<Cask::DSL:0x00007fed3c240af0 @cask=#<Cask::Cask:0x00007fed3c0dfc38 ...>, @token="trader-workstation", @version="978.2j", @sha256=:no_check, @url=#<URL::DSL:0x00007fed3c240488 @uri=#<URI::HTTPS https://download2.interactivebrokers.com/installers/tws/stable-standalone/tws-stable-standalone-macosx-x64.dmg>, @verified=nil, @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @specs={:user_agent=>:default}>, @name=["Trader Workstation"], @desc="Trading software", @homepage="https://www.interactivebrokers.com/", @staged_path=#<Pathname:/usr/local/Caskroom/trader-workstation/978.2j>, @artifacts=#<SortedSet: {...}>, @language_eval=nil>>, @directives={:quit=>"com.install4j.5889-6375-8446-2021.22", :script=>{:executable=>"/Users/mafa/Applications/Trader Workstation 978/Trader Workstation 978 Uninstaller.app/Contents/MacOS/JavaApplicationStub", :args=>["-q"]}, :signal=>[]}>, #<Cask::Artifact::Installer:0x00007fed3c24b2c0 @cask=#<Cask::Cask:0x00007fed3c0dfc38 @token="trader-workstation", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/trader-workstation.rb>, @tap=#<Tap:0x00007fed580f03f0 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @formula_renames={}, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fed3c0df940@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/trader-workstation.rb:1>, @default_config=#<Cask::Config:0x00007fed5817bb08 @explicit={}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/trader-workstation>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/trader-workstation/.metadata>, @config=#<Cask::Config:0x00007fed3c240d98 @explicit={}>, @dsl=#<Cask::DSL:0x00007fed3c240af0 @cask=#<Cask::Cask:0x00007fed3c0dfc38 ...>, @token="trader-workstation", @version="978.2j", @sha256=:no_check, @url=#<URL::DSL:0x00007fed3c240488 @uri=#<URI::HTTPS https://download2.interactivebrokers.com/installers/tws/stable-standalone/tws-stable-standalone-macosx-x64.dmg>, @verified=nil, @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @specs={:user_agent=>:default}>, @name=["Trader Workstation"], @desc="Trading software", @homepage="https://www.interactivebrokers.com/", @staged_path=#<Pathname:/usr/local/Caskroom/trader-workstation/978.2j>, @artifacts=#<SortedSet: {...}>, @language_eval=nil>>, @args={:must_succeed=>true, :sudo=>false, :args=>["-q"], :print_stdout=>true}, @path=#<Pathname:/usr/local/Caskroom/trader-workstation/978.2j/Trader Workstation 978 Installer.app/Contents/MacOS/JavaApplicationStub>>}>
==> Installing artifact of class Cask::Artifact::Installer
==> Running installer script '/usr/local/Caskroom/trader-workstation/978.2j/Trader Workstation 978 Installer.app/Contents/MacOS/JavaApplicationStub'
/usr/bin/env PATH=/usr/local/bin:/usr/local/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin /usr/local/Caskroom/trader-workstation/978.2j/Trader\ Workstation\ 978\ Installer.app/Contents/MacOS/JavaApplicationStub -q
env: /usr/local/Caskroom/trader-workstation/978.2j/Trader Workstation 978 Installer.app/Contents/MacOS/JavaApplicationStub: No such file or directory
==> Purging files for version 978.2j of Cask trader-workstation
Error: Failure while executing; `/usr/bin/env PATH=/usr/local/bin:/usr/local/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin /usr/local/Caskroom/trader-workstation/978.2j/Trader\ Workstation\ 978\ Installer.app/Contents/MacOS/JavaApplicationStub -q` exited with 127. Here's the output:
env: /usr/local/Caskroom/trader-workstation/978.2j/Trader Workstation 978 Installer.app/Contents/MacOS/JavaApplicationStub: No such file or directory

/usr/local/Homebrew/Library/Homebrew/system_command.rb:302:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:65:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:40:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:44:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/installer.rb:38:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:233:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:226:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:111:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:69:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:68:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:68:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:167:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'

</code></pre></details>

### Output of `brew doctor --verbose`

<details><summary>Click to expand</summary><pre><code>

==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
==> $LOAD_PATHS
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/warning-1.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tapioca-0.4.23/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/spoom-1.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thor-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-stub-0.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-cobertura-1.4.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-0.21.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov_json_formatter-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-html-0.12.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-sorbet-0.6.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rails-2.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-1.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unicode-display_width-2.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.11.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-ast-1.7.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-sorbet-1.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-0.5.6274/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-static-0.5.6274-universal-darwin-14/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-github-2.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-3.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-mocks-3.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-expectations-3.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-core-3.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-support-3.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/regexp_parser-2.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rdiscount-2.2.0.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/rdiscount-2.2.0.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rack-2.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/pry-0.14.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/patchelf-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parlour-6.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-0.5.6274/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parser-3.0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel_tests-3.7.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel-1.20.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/method_source-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.8.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrick-1.7.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubyntlm-0.6.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.11.7-x86_64-darwin/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/racc-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/racc-1.5.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.5.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-4.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-data-3.2021.0225/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/elftools-1.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.7.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/unf_ext-0.0.7.7
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.3.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.4.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/commander-4.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/highline-2.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/colorize-0.8.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/coderay-1.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/byebug-11.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/byebug-11.1.3
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bootsnap-1.7.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/bootsnap-1.7.5
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/msgpack-1.4.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/msgpack-1.4.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bindata-2.4.8/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ast-2.4.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/addressable-2.7.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/public_suffix-4.0.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.1.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.4.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-2.0.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/minitest-5.14.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.10/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/site_ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/site_ruby/2.6.0/x86_64-darwin14
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/vendor_ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/vendor_ruby/2.6.0/x86_64-darwin14
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/x86_64-darwin14
/usr/local/Homebrew/Library/Homebrew
==> Homebrew Version
3.1.11-45-g33e71c9
==> macOS
10.15.7
==> SIP
Enabled
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3920 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (192 casks)
/usr/local/Homebrew/Library/Taps/fasmat/homebrew-trader-workstation (3 casks)
Your system is ready to brew.

</code></pre></details>

### Output of `brew tap`

<details><summary>Click to expand</summary><pre><code>

fasmat/trader-workstation
homebrew/cask
homebrew/cask-versions
homebrew/core
homebrew/services

</code></pre></details>

**Comment by SMillerDev** [comment]
The issue template here is only for issues with homebrew-cask casks. You can try and start a conversation at https://github.com/Homebrew/discussions/discussions instead.
