### ISSUE TITLE
Why does the doc use --cask when you can install cask without it?

### ISSUE THREAD

**Issue by shinokada** [Homebrew/homebrew-cask#107145]
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

This is about the documentation.

According to the [Formulae page](https://formulae.brew.sh/), it suggests to use `--cask`.
For example, 

```
brew install --cask google-chrome
```

But I can install without using the `--cask` and the [homebrew-cask README](https://github.com/Homebrew/homebrew-cask) doesn't use `--cask` neither.

```
brew install alfred
```

But [Formulae page](https://formulae.brew.sh/cask/alfred#default) uses `--casek`:

```
brew install --cask alfred
```

I suggest to unify the information.

### Command that failed

n/a

### Output of command with `--verbose --debug`

<details><summary>Click to expand</summary><pre><code>

REPLACE THIS TEXT WITH THE OUTPUT

</code></pre></details>

### Output of `brew doctor --verbose`

<details><summary>Click to expand</summary><pre><code>

REPLACE THIS TEXT WITH THE OUTPUT

</code></pre></details>

### Output of `brew tap`

<details><summary>Click to expand</summary><pre><code>

REPLACE THIS TEXT WITH THE OUTPUT

</code></pre></details>

**Comment by miccal** [comment]
Occasionally the `--cask` flag is necessary if a Formula and a Cask share the same name, for example with `dotnet`.

If you think the documentation can be improved, please send through a PR, thanks.
