### ISSUE TITLE
bad CPU type in executable: jad

### ISSUE THREAD

**Issue by jemjensen** [Homebrew/homebrew-cask#107277]
The "jad" executable currently pushed by homebrew is compiled for i386 so does not run on modern macs. According to the jad.rb file, the latest file is f9327fe93f23096a6ad0eee56c52267595764acd7e7451343bc6799da91e373b--jad158g.mac.intel.zip with a signature of 8e9e4ea6c4177acce6d27325a036f10a72c170ed60e48c37c3483335319d07b9, as shown:

>cask "jad" do  
>   version "1.5.8g"  
>   sha256 "8e9e4ea6c4177acce6d27325a036f10a72c170ed60e48c37c3483335319d07b9"
>   url "https://varaneckas.com/jad/jad#{version.no_dots}.mac.intel.zip"  
>   name "Jad"  
>   desc "Java decompiler"
>   homepage "https://varaneckas.com/jad/"

Reinstalling the formula confirms this is the file being downloaded:

>% brew reinstall --cask jad
>==> Caveats
>Instructions on using jad are available in
>
>  /usr/local/Caskroom/jad/1.5.8g/Readme.txt
>
>==> Downloading https://varaneckas.com/jad/jad158g.mac.intel.zip
>Already downloaded: >/Users/username/Library/Caches/Homebrew/downloads/f9327fe93f23096a6ad0eee56c52267595764acd7e7451343bc6799da91e373b--jad158g.mac.intel.zip
>==> Uninstalling Cask jad
>==> Unlinking Binary '/usr/local/bin/jad'
>==> Unlinking Manpage '/usr/local/share/man/man1/jad.1'
>==> Purging files for version 1.5.8g of Cask jad
>==> Installing Cask jad
>==> Linking Binary 'jad' to '/usr/local/bin/jad'
>==> Linking Manpage 'jad.1' to '/usr/local/share/man/man1/jad.1'
>🍺  jad was successfully installed!

Performing a shasum confirms the signature:

>% shasum -a 256 f9327fe93f23096a6ad0eee56c52267595764acd7e7451343bc6799da91e373b--jad158g.mac.intel.zip
>8e9e4ea6c4177acce6d27325a036f10a72c170ed60e48c37c3483335319d07b9  f9327fe93f23096a6ad0eee56c52267595764acd7e7451343bc6799da91e373b--jad158g.mac.intel.zip

File of the binary contained within the file:

>% file jad
>jad: Mach-O executable i386

Attempt to run the executable on Big Sur:

>% uname -p
>i386
>% uname -m
>x86_64
>% ./jad
>zsh: bad CPU type in executable: ./jad

**Comment by cho-m** [comment]
The software appears to be discontinued/unmaintained and built only for 32-bit.
Even the copyright is only up to 2001.

There is nothing we can do to make the software actually run on 64-bit only systems (macOS 10.15+).

The only things we can do is prevent users from installing this by marking discontinued, adding a macOS version limit, and/or removing the Cask.
