### ISSUE TITLE
Add new custom AppCenterDownloadStrategy to support appcenter apps

### ISSUE THREAD

**Issue by JounQin** [Homebrew/homebrew-cask#107354]
### Provide a detailed description of the proposed feature

I asked before at https://github.com/Homebrew/homebrew-cask/pull/79549#issuecomment-735386385, but no more reply received, so I raise a new issue here to discuss it.

My proposal solution: https://github.com/homebrew-x/homebrew-x/blob/master/shared/appcenter_download_strategy.rb

### What is the motivation for the feature?

appcenter URLs are a pain to maintain and break all the time.

### Example use case

ClashX Pro, Timeless, ...

**Comment by SMillerDev** [comment]
Feature suggestions for homebrew should really be made as a pull request to the brew repo

**Comment by JounQin** [comment]
I'd like to PR, but I want to make sure you members agree to add such a custom download strategy for appcenter first.

**Comment by JounQin** [comment]
So, should I PR directly?

**Comment by carlocab** [comment]
Are there any casks in this repo that would make use of this strategy? How many?

**Comment by JounQin** [comment]
@carlocab 

https://github.com/Homebrew/homebrew-cask/pulls?q=appcenter

`ClashX Pro`, `Timeless` and others attempted to be added, but failed, so I can't tell how many casks will be affected. But if it is added, it will be useful.

**Comment by carlocab** [comment]
Since you already have your `AppCenterDownloadStrategy`, I guess it wouldn't hurt to open a PR for it -- I don't think it should be too much work. I don't know if there's enough to justify merging it, but we'll find out when you open your pull request.

**Comment by JounQin** [comment]
in progress
