### ISSUE TITLE
please re-release VLC 3.0.15 upgrade

### ISSUE THREAD

**Issue by Pd69bq** [Homebrew/homebrew-cask#107343]
![vlc_3 0 15](https://user-images.githubusercontent.com/5948524/122137924-4beaab80-ce78-11eb-93d1-77783fa7f90c.png)

as the title suggested, MSFT is providing upgrade on its winget package manager, which means #107255 is no longer true and macOS releases can be found at [download.videolan.org](https://download.videolan.org/vlc/3.0.15/macosx/)

**Comment by cho-m** [comment]
Closing as we don't use issues for update requests.

The proper procedure is to submit a PR if update is available.
See https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask for help
