### ISSUE TITLE
Why are apps by affinity not in cask when their beta versions are in cask-versions?

### ISSUE THREAD

**Issue by xeoneux** [Homebrew/homebrew-cask#107490]
### Provide a detailed description of the proposed feature

I see that beta version of Affinity Photo is available through cask-version whereas the main app is not available through homebrew-cask. Even though there's an offline installer available for the app. Is there any reason for that?

### What is the motivation for the feature?

To install apps by Affinity through homebrew. They provide a free trial as well.

### Example use case

A simple `brew install affinity-photo` is missing

**Comment by carlocab** [comment]
The likeliest explanation is that no one's taken the time to add them. If they meet the requirements, you're welcome to open a PR to add them. See https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md.

**Comment by xeoneux** [comment]
Thanks @carlocab that's what I figured since there's no open/closed PR ever that discusses Affinity products.
I'll try and create a PR for the same 😄

**Comment by cho-m** [comment]
Closing as I think the question was answered and #107491 has been merged
(if other Affinity software are wanted, then can just continue opening new PRs).
