### ISSUE TITLE
[CI] Add support for basic testing of ARM if-branch (e.g. `brew fetch`)

### ISSUE THREAD

**Issue by cho-m** [Homebrew/homebrew-cask#107586]
### Provide a detailed description of the proposed feature

This is to improve checks on `homebrew-cask` CI by adding some support for basic (non-install) tests for ARM branch.

For example, at minimum doing something like a `brew fetch` to check valid URL/SHA. Perhaps an equivalent of `brew audit --online` test for livecheck.

This may either require a flag in `brew` to  "fake" Hardware for certain commands, or a CI-specific test logic rather than directly running `brew` commands.

Potentially consider scoping out if possible to run simple tests for other macOS version branches too (e.g. Mojave and older, or Monterey beta, or ...). This would allow us to detect dead branches better.

### What is the motivation for the feature?

Since `homebrew-cask` don't have an ARM CI node, the CI doesn't seem to test the ARM branch. 

Given that ARM-specific download URLs are becoming common, this means Homebrew maintainers may need to manually confirm ARM branch.

Having a test in CI would help check correct url/sha/etc and reduce manual confirmation overhead.

### Example use case

I have seen some PRs that showed CI passing, but when I locally checked out PR, the `brew fetch` failed.

For example, in #107488 (corresponding commit to change ARM url https://github.com/Homebrew/homebrew-cask/pull/107488/commits/696bb78fa7398f84f1a58846e14d1dd0c670ee39)
- Run with incorrect ARM url https://github.com/Homebrew/homebrew-cask/actions/runs/958546506
- Run with correct ARM url https://github.com/Homebrew/homebrew-cask/actions/runs/958888936

**Comment by SMillerDev** [comment]
I wonder if, instead of faking the OS, it wouldn't be better for casks to implement a DSL similar to a formula bottle block to define what a specific url supports.

**Comment by yurikoles** [comment]
I like [ArchLinux' PKGBUILD approach](https://wiki.archlinux.org/title/PKGBUILD#source), which allows defining architecture-specific sources as `source_x86_64=`, and corresponding checksum `sha256sums_x86_64=`. We can apply it to HBC DSL as `url_x86_64` / `url_aarch64` and `sha256_x86_64` / `sha256_aarch64`.

**Comment by bevanjkay** [comment]
This was completed by https://github.com/Homebrew/homebrew-cask/pull/143743
