### ISSUE TITLE
[CI] Make `CiMatrix` respect `depends_on macos:` when choosing runners

### ISSUE THREAD

**Issue by Logicer16** [Homebrew/homebrew-cask#107570]
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

`depends_on macos:` specifies the versions of macOS that are supported for a cask. When `CiMatrix` determines the runners a cask should be tested on without considering whether the runner actually is a macOS version supported the cask, causing checks to fail on environments that the user can't install/run the cask on themselves, and that the developer hasn't designed the cask for. 

Required for Homebrew/homebrew-cask-versions#11231

### Command that failed

`brew ruby -- "$(brew --repository homebrew/cask)/cmd/lib/generate-matrix.rb" "https://api.github.com/repos/Homebrew/homebrew-cask-versions/pulls/11231"`

### Output of command with `--verbose --debug`

*Unchanged from standard output: (https://github.com/Homebrew/homebrew-cask-versions/pull/11231/checks?check_run_id=2882107148)*

<details><summary>Click to expand</summary><pre><code>[
  {
    "name": "syntax (ubuntu-latest)",
    "tap": "homebrew/cask-versions",
    "runner": "ubuntu-latest",
    "skip_audit": true
  },
  {
    "name": "test safari-technology-preview (macos-10.15)",
    "tap": "homebrew/cask-versions",
    "cask": {
      "token": "safari-technology-preview",
      "path": "./Casks/safari-technology-preview.rb"
    },
    "audit_args": [
      "--appcast",
      "--online"
    ],
    "skip_install": false,
    "runner": "macos-10.15"
  },
  {
    "name": "test safari-technology-preview (macos-11.0)",
    "tap": "homebrew/cask-versions",
    "cask": {
      "token": "safari-technology-preview",
      "path": "./Casks/safari-technology-preview.rb"
    },
    "audit_args": [
      "--appcast",
      "--online"
    ],
    "skip_install": false,
    "runner": "macos-11.0"
  }
]::set-output name=matrix::[{"name":"syntax (ubuntu-latest)","tap":"homebrew/cask-versions","runner":"ubuntu-latest","skip_audit":true},{"name":"test safari-technology-preview (macos-10.15)","tap":"homebrew/cask-versions","cask":{"token":"safari-technology-preview","path":"./Casks/safari-technology-preview.rb"},"audit_args":["--appcast","--online"],"skip_install":false,"runner":"macos-10.15"},{"name":"test safari-technology-preview (macos-11.0)","tap":"homebrew/cask-versions","cask":{"token":"safari-technology-preview","path":"./Casks/safari-technology-preview.rb"},"audit_args":["--appcast","--online"],"skip_install":false,"runner":"macos-11.0"}]
</code></pre></details>

### Output of `brew doctor --verbose`

N/A: CI environment

Example output: https://github.com/Homebrew/homebrew-cask-versions/pull/11231/checks?check_run_id=2882107148

### Output of `brew tap`

N/A: CI environment

Example output: https://github.com/Homebrew/homebrew-cask-versions/pull/11231/checks?check_run_id=2882107148

**Comment by carlocab** [comment]
I'm not sure I understand the issue here. Your [PR](https://github.com/Homebrew/homebrew-cask-versions/blob/b42803a30fec67c6631ec5ff0cc1bc48888134c9/Casks/safari-technology-preview.rb#L2-L8) has
```ruby
  if MacOS.version <= :big_sur
    version "126,071-57331-20210621-f40f3ff7-4076-4a0b-a86e-99ea6abbfb6a"
    sha256 "b9dabd73ff2e2069da43d436a911458dcee2eac1c25fa5c679a948f5f60c71ba"
  else
    version "126,001-66930-20210616-c91fc8a5-bfeb-47ec-80c2-0d54c6ebbcee"
    sha256 "d7547c77c709db6f551a5be1c60fcdff3b116579aa24038ebe2936003e8c3af4"
  end
```
which means that version `126,071-57331-20210621-f40f3ff7-4076-4a0b-a86e-99ea6abbfb6a` is run on both Catalina and Big Sur. That seems to be reflected accurately in the output of `generate-matrix.rb`. Could you elaborate on what the issue here is?

**Comment by Logicer16** [comment]
The PR also has 
```
depends_on macos: ">= :big_sur"
```
requiring that it be run on Big Sur or later. The latest version does not support running on Catalina nor does it provide a valid installer that can be run on Catalina, causing unintended behaviour if the install or livecheck where to proceed on Catalina.

**Comment by carlocab** [comment]
Ah, yes, I missed that. That makes sense. Could you open a PR for this?

**Comment by Logicer16** [comment]
> Could you open a PR for this?

I would ... if I knew what I was doing. I could try and figure it out when I have some time, otherwise its open to whoever wants it.

**Comment by carlocab** [comment]
Sure, that's fine. Feel free to give us a shout if you get stuck. Even a draft PR that doesn't quite work fully would be a great start.
