### ISSUE TITLE
"verified" URL instructions link leads to a 404

### ISSUE THREAD

**Issue by Kreeblah** [Homebrew/homebrew-cask#107626]
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

I'm trying to update the ghidra.rb cask, but they changed the download location to be on Github, even though their regular page is still on ghidra-sre.org.  So, brew audit tells me I need to visit https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#when-url-and-homepage-hostnames-differ-add-verified for instructions on adding a verified parameter to the url, but that leads to a 404.

### Command that failed

brew audit --cask ./ghidra.rb

### Output of command with `--verbose --debug`

<details><summary>Click to expand</summary><pre><code>

 - The URL's domain github.com does not match the homepage domain www.ghidra-sre.org, a 'verified' parameter has to be added to the 'url' stanza. See https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#when-url-and-homepage-hostnames-differ-add-verified

</code></pre></details>

### Output of `brew doctor --verbose`

<details><summary>Click to expand</summary><pre><code>

N/A

</code></pre></details>

### Output of `brew tap`

<details><summary>Click to expand</summary><pre><code>

N/A

</code></pre></details>

**Comment by cho-m** [comment]
The docs were recently moved to main site and some old references need to be updated.
New URL: https://docs.brew.sh/Cask-Cookbook#when-url-and-homepage-hostnames-differ-add-verified

I opened Homebrew/brew#11588 to fix some of these dead urls.
