### ISSUE TITLE
being specific in "postflight" would avoid failures

### ISSUE THREAD

**Issue by tgbauer** [Homebrew/homebrew-cask#107852]
Suggest modifying "postflight" to act on the specific files required by macfuse and chown run if they exist.  This will allow the install of macfuse to work while other (mostly security related) apps are installed that require files in /usr/local/lib/ or /usr/local/include/  have root as owner (and actively block the chown command).

with some security software installed,
brew install macfuse
is failing due to exit status of "1" from the chown command

https://github.com/Homebrew/homebrew-cask/blob/dffa5ab4edbde828b174143344f0eb8e5f66dddf/Casks/macfuse.rb#L23

**Comment by carlocab** [comment]
Already proposed in https://github.com/Homebrew/homebrew-cask/pull/103393. If you'd like to see this implemented, please open a pull request, but please make sure to address the comments in the linked PR if you do.
