### ISSUE TITLE
`brew outdated` command doesn't show me outdated cask (insomnia)

### ISSUE THREAD

**Issue by mxmlnglt** [Homebrew/homebrew-cask#108054]
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

Insomnia just got released to version 2021.4: https://insomnia.rest/changelog

Version was pushed into homebrew-cask: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/insomnia.rb

`brew outdated` doesn't show me Insomnia as outdated.

```
fr136389@L-C02C91ZYMD6P ~ % brew outdated
oniguruma (6.9.6) < 6.9.7.1
openjdk (14.0.1, 15.0.2) < 16.0.1
eclipse-java (4.19.0,2021-03:R) != 4.20.0,2021-06:R
```

```
fr136389@L-C02C91ZYMD6P ~ % brew list --cask --version
adoptopenjdk 16.0.1,9
adoptopenjdk11 11.0.11,9
adoptopenjdk8 8,292:b10
dbeaver-community 21.1.1
eclipse-java 4.19.0,2021-03:R
fork 2.7
gimp 2.10.22
insomnia 2021.3.0
visual-studio-code 1.55.2
zoom 5.7.1.499
```

I ran `brew update-reset && brew update` to no avail.

### Command that failed

brew outdated

### Output of command with `--verbose --debug`

<details><summary>Click to expand</summary><pre><code>

user@host ~ % brew outdated --verbose --debug
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/yq.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/maven.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/nvm.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openjdk.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gettext.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/oniguruma.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pcre2.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/jq.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/git.rb
oniguruma (6.9.6) < 6.9.7.1
openjdk (14.0.1, 15.0.2) < 16.0.1
eclipse-java (4.19.0,2021-03:R) != 4.20.0,2021-06:R

</code></pre></details>

### Output of `brew doctor --verbose`

<details><summary>Click to expand</summary><pre><code>

user@host ~ % brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
You should download the Command Line Tools for Xcode 12.5.

</code></pre></details>

### Output of `brew tap`

<details><summary>Click to expand</summary><pre><code>

user@host ~ % brew tap
adoptopenjdk/openjdk
homebrew/cask
homebrew/core

</code></pre></details>

**Comment by mxmlnglt** [comment]
PS: of course, I quit Insomnia before running the `brew` commands, and I've got the 'Automatic download/install of updates' option in Insomnia unchecked. And Insomnia still displays me the 2021.3 version.

**Comment by bevanjkay** [comment]
@mxmlnglt Because the insomnia cask has `auto_updates true` it will not show in the `brew outdated` command unless you pass the `--greedy` flag – `brew outdated --greedy`.

**Comment by SMillerDev** [comment]
In addition, this repo is only for casks you can install. Issues with brew output should be reported to https://github.com/Homebrew/brew
