### ISSUE TITLE
Request Maintainer for specific apps

### ISSUE THREAD

**Issue by dtantono** [Homebrew/homebrew-cask#108037]
Hi
I am just curious that how to request maintainers or apps even for beta or dev version to be available on homebrew. because I only find this one (https://docs.brew.sh/New-Maintainer-Checklist) Please advise. Thanks

**Comment by SMillerDev** [comment]
We don't have specific maintainers. All homebrew maintainers maintain all software. The only possible distinction is between cask, brew and core.

**Comment by dtantono** [comment]
noted and suppose I want to request a specific app to be available on homebrew. What is the correct procedure to do it?

**Comment by SMillerDev** [comment]
https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md

**Comment by SMillerDev** [comment]
Closing this since it's not really an issue. For next time https://github.com/Homebrew/discussions/discussions would be a better place for general questions

**Comment by dtantono** [comment]
it seems you misunderstood because Windows and Linux have some kind of protocols of how to request maintainers/somebody to make the specific apps available in the repository. But, it seems Homebrew does not have it and I will move forward with this discussion on that link (https://github.com/Homebrew/discussions/discussions). Thanks
