### ISSUE TITLE
Audacity 3.0 reported

### ISSUE THREAD

**Issue by hacfi** [Homebrew/homebrew-cask#108129]
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

According to https://appleinsider.com/articles/21/07/04/open-source-audacity-deemed-spyware-over-data-collection-changes Audacity 3.0 is sharing your personal data. We should consider downgrading to 2.2.2.

### Command that failed

-

### Output of command with `--verbose --debug`

-

### Output of `brew doctor --verbose`

-

### Output of `brew tap`

-

**Comment by SMillerDev** [comment]
Why would it need to be downgraded? Plenty of casks collect user data.

**Comment by izhakjakov** [comment]
Because this is a new "feature" and many people who are using it do not expect this.
Also there is no way to disable this new "feature".  😞

**Comment by bevanjkay** [comment]
@izhakjakov You can submit a PR for Audacity 2.x to https://github.com/homebrew/homebrew-cask-versions

**Comment by iBobik** [comment]
There is [AudMonkey](https://github.com/AudMonkey/AudMonkey) - OS fork with telemetry removed. [They just added macOS builds.](https://github.com/AudMonkey/AudMonkey/issues/32)

How about to add AudMonkey as a separated cask and add install warning to Audacity cask?
