### ISSUE TITLE
Upgrade OBS to arm64 (M1) compatible version

### ISSUE THREAD

**Issue by Niek** [Homebrew/homebrew-cask#108128]
### Provide a detailed description of the proposed feature

The current OBS cask is Intel-only. There is a script at https://github.com/carlosonunez/obs-installer-for-apple-silicon to build a M1 version of OBS.

### What is the motivation for the feature?

Faster encoding, lower CPU usage.

### Example use case

Anyone using OBS on a M1 mac.

**Comment by SMillerDev** [comment]
As long as there is no official ARM OBS build we can't provide an ARM cask version. If there is an official build, please make a pull request to add it to the cask.

**Comment by carlosonunez** [comment]
Agree with @SMillerDev . As much as I love my own solution, making this the official Cask for OBS is more optimistic than I'd like!
