### ISSUE TITLE
Error: SHA256

### ISSUE THREAD

**Issue by sohnyi** [Homebrew/homebrew-cask#108323]
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

Error: SHA256 mismatch

Expected: 9f4d7d484cd3ff70950c8b2741f604be5f66a972d8cf4b7118b3b18d6f1a6561

 Actual: 34842e0b6ca6ea720499de67253ae4f73cf8d36465f54b95909c4d3ee1bebc9a

### Command that failed

brew install --cask cleanmymac

### Output of command with `--verbose --debug`

<details><summary>Click to expand</summary><pre><code>

REPLACE THIS TEXT WITH THE OUTPUT

</code></pre></details>

### Output of `brew doctor --verbose`

<details><summary>Click to expand</summary><pre><code>

REPLACE THIS TEXT WITH THE OUTPUT

</code></pre></details>

### Output of `brew tap`

<details><summary>Click to expand</summary><pre><code>

REPLACE THIS TEXT WITH THE OUTPUT

</code></pre></details>

**Comment by carlocab** [comment]
> * [x]  I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

That seems to be untrue.

https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md
