### ISSUE TITLE
Replace a .app file instead of removing and adding it again when homebrew updates casks

### ISSUE THREAD

**Issue by simonerancati** [Homebrew/homebrew-cask#108399]
### Provide a detailed description of the proposed feature

Instead of removing and then adding the updated casks you should replace the old with the new ones without removing them

### What is the motivation for the feature?

I would like to have this feature because every time homebrew updates my casks the old ones get removed from the dock and from the folders in the launchpad

### Example use case

When homebrew updates an app the icon won't get removed from the dock and from folders in launchpad forcing the user to add it again

**Comment by SMillerDev** [comment]
See https://github.com/Homebrew/homebrew-cask/issues/102721

Your idea brings other issues than the current dock and launchpad problems though. What if a replacement fails? What if the download was incomplete? Currently you can still roll-back the update, with your solution you can't

**Comment by simonerancati** [comment]
You can still backup the old app before upgrading it and if something fails roll-back the update by replacing the app with the backed up one

**Comment by miccal** [comment]
This is being discussed in https://github.com/Homebrew/homebrew-cask/issues/102721.
