### ISSUE TITLE
Visual Studio Cask broken.

### ISSUE THREAD

**Issue by dm3ch** [Homebrew/homebrew-cask#108329]
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

Visual studio cask is broken.
Dmg source is unavailable.

### Command that failed

brew install visual-studio

### Output of command with `--verbose --debug`

<details><summary>Click to expand</summary><pre><code>

==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.2.1-70-g5659d74\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.7\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://dl.xamarin.com/VsMac/VisualStudioForMac-8.10.5.16.dmg
==> Downloading https://dl.xamarin.com/VsMac/VisualStudioForMac-8.10.5.16.dmg
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.2.1-70-g5659d74\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.7\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --head https://dl.xamarin.com/VsMac/VisualStudioForMac-8.10.5.16.dmg
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.2.1-70-g5659d74\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.7\)\ curl/7.64.1 --header Accept-Language:\ en --fail --retry 3 --location --remote-time --output /Users/dmitry.chepurovskiy/Library/Caches/Homebrew/downloads/1c2e09ffaff5638e90c91e7edc1713b3e39a6a735469175f566fa15de7d04731--VisualStudioForMac-8.10.5.16.dmg.incomplete https://dl.xamarin.com/VsMac/VisualStudioForMac-8.10.5.16.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
Warning: Transient problem: HTTP error Will retry in 1 seconds. 3 retries
Warning: left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
Warning: Transient problem: HTTP error Will retry in 2 seconds. 2 retries
Warning: left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
Warning: Transient problem: HTTP error Will retry in 4 seconds. 1 retries
Warning: left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (22) The requested URL returned error: 500 Internal Server Error
Error: Download failed on Cask 'visual-studio' with message: Download failed: https://dl.xamarin.com/VsMac/VisualStudioForMac-8.10.5.16.dmg
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:407:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:404:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:25:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:171:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:73:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:100:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:69:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:68:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:68:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:167:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'

</code></pre></details>

### Output of `brew doctor --verbose`

<details><summary>Click to expand</summary><pre><code>

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
You should download the Command Line Tools for Xcode 12.4.

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  git-profile-manager
  unrar

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker
  kubernetes-cli
  six
  helm

</code></pre></details>

### Output of `brew tap`

<details><summary>Click to expand</summary><pre><code>

aylei/tap
buildpacks/tap
datawire/blackbird
golangci/tap
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/services
ketchoop/tap
minio/stable
norwoodj/tap

</code></pre></details>

**Comment by LiranV** [comment]
I've encountered similar issue ("500 Internal Server Error" from https://dl.xamarin.com) while trying to install [xamarin-ios](https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/xamarin-ios.rb)

**Comment by kittywhiskers** [comment]
Looks like an issue with Xamarin's servers, not Homebrew. Can't download using `wget`
```
> $ wget https://dl.xamarin.com/VsMac/VisualStudioForMac-8.10.5.16.dmg          
--2021-07-11 21:01:49--  https://dl.xamarin.com/VsMac/VisualStudioForMac-8.10.5.16.dmg
Resolving dl.xamarin.com (dl.xamarin.com)... 13.85.77.179
Connecting to dl.xamarin.com (dl.xamarin.com)|13.85.77.179|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2021-07-11 21:01:54 ERROR 500: Internal Server Error.
```

**Comment by dm3ch** [comment]
> Looks like an issue with Xamarin's servers, not Homebrew. Can't download using `wget`
> 
> ```
> > $ wget https://dl.xamarin.com/VsMac/VisualStudioForMac-8.10.5.16.dmg          
> --2021-07-11 21:01:49--  https://dl.xamarin.com/VsMac/VisualStudioForMac-8.10.5.16.dmg
> Resolving dl.xamarin.com (dl.xamarin.com)... 13.85.77.179
> Connecting to dl.xamarin.com (dl.xamarin.com)|13.85.77.179|:443... connected.
> HTTP request sent, awaiting response... 500 Internal Server Error
> 2021-07-11 21:01:54 ERROR 500: Internal Server Error.
> ```

Yep, but when you installs VisualStudio for Mac via link from microsoft website, it downloads DMG from completely different address on https://visualstudio.microsoft.com/ domain. Maybe it would be better to make cask using that address?

**Comment by kittywhiskers** [comment]
Sounds like it.

I figured `VisualStudioForMac-8.10.5.16.dmg` from Xamarin is the full (offline) version because the disk image from  https://download.visualstudio.microsoft.com is `visualstudioformacinstaller-8.10.0.10.dmg` and there'd be a preference for offline install images over online images

**Comment by LiranV** [comment]
@dm3ch FYI
`https://dl.xamarin.com` seems to be working again and I was able to complete the installation
