### ISSUE TITLE
Require checksum. Cask installs with no checksum should fail.

### ISSUE THREAD

**Issue by christopinka-smarsh** [Homebrew/homebrew-cask#108412]
### Provide a detailed description of the proposed feature

Example: Running `brew install google-chrome` I get
> Warning: No checksum defined for cask 'google-chrome', skipping verification.

What's the point of allowing this? Checksum verification is a main reason for me using Homebrew.

### What is the motivation for the feature?

Checksums should be integral to cask installs.

### Example use case

Any cask lacking a checksum.

**Comment by SMillerDev** [comment]
> What's the point of allowing this? Checksum verification is a main reason for me using Homebrew.

Because we don't control the checksums of casks. And if upstream updates their download it'll break everything. Checksums only work well when the source isn't supposed to change, and we don't have that guarantee for casks.

**Comment by miccal** [comment]
If you do not like this behaviour, you can pass the  `−−require−sha` flag as explained in `man brew`.
