### ISSUE TITLE
Sublime Text cask conflicts with existing license

### ISSUE THREAD

**Issue by tobadia** [Homebrew/homebrew-cask#108488]
### Provide a detailed description of the proposed feature

Hello cask maintainers,

Alongside #106089 Sublime Text cask was updated to fetch the recently released Sublime Text v4. However that version overwrites the previous cask (v3).

This poses an issue because ST v3 paid licenses are not compatible with ST v4: users are prompted with the "UNREGISTERED" label. Upgrding/updating brew "forces" the user to update that Cask, hence invalidating the license.

Would it be feasible to "version" STv4 into a different cask ?

Thanks

### What is the motivation for the feature?

STv3 license is not compatible with STv4

### Example use case

Use STv3 with a paid license
Inadvertently upgrade to STv4
End up with an "UNREGISTERED" STv4

**Comment by bevanjkay** [comment]
@tobadia The `homebrew-cask` repository should always return the latest version of an application, even if licensing or breaking changes occur.

1. To retain Sublime Text 3 (and continue to receive any additional updates to this branch), a cask for version 3 can be submitted to [`homebrew-cask-version`](https://github.com/Homebrew/homebrew-cask-versions/) – see [sublime-text-2](https://github.com/Homebrew/homebrew-cask-versions/blob/4644b2656e655d36f42f4055fd000a12568aaea2/Casks/sublime-text2.rb) as an example.
2. As the Sublime Text cask has `auto_update true` specified, it would only be upgraded, or listed as outdated if you pass the `--greedy` flag to either command. As always it is recommended that you do your own research into version updates.
