### ISSUE TITLE
Dropzone

### ISSUE THREAD

**Issue by vraravam** [Homebrew/homebrew-cask#108516]
### Provide a detailed description of the proposed feature

Dropzone has been featured in multiple mac productivity app blogs. I see that it used to be present via homebrew, but was subsequently deleted in https://github.com/Homebrew/homebrew-cask/pull/76391 - im not sure why this was done though. There are quite a few apps that are released via the Mac App store - and which can be found in homebrew, so why was dropzone deleted? Just asking for clarity

### What is the motivation for the feature?

Continue to use homebrew to install all mac apps

### Example use case

brew install --cask dropzone

**Comment by bevanjkay** [comment]
@vraravam At the time the cask was removed from Homebrew [the app was no longer available ](http://web.archive.org/web/20200302005407/https://aptonic.com/blog/)to download directly and was therefore removed. You are welcome to submit a PR to see the cask re-added.
