### ISSUE TITLE
session-manager-plugin: macOS unable to verify developer/malware status; removes after each update

### ISSUE THREAD

**Issue by bleachbyte** [Homebrew/homebrew-cask#109290]
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

The AWS Session Manager plugin (https://formulae.brew.sh/cask/session-manager-plugin) will not run on macOS Catalina 10.15.7, [as it is stopped by Gatekeeper](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/app_cant_be_opened.md):
![Screen Shot 2021-07-29 at 1 04 41 PM](https://user-images.githubusercontent.com/54293972/127544181-a64440f0-3610-46e2-9017-fbcc4c615094.png)

This comes up _every time_ the plugin is updated, which is [frequent enough](https://github.com/Homebrew/homebrew-cask/pulls?q=session-manager-plugin+is%3Apr) that it becomes a bit tedious to reinstall with `--no-quarantine` any time it's updated.

This was originally raised in #90637 ; the solution offered was the above doc (although [that link is broken](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/the_app_cant_be_opened.md)). I'm raising this issue to ask:

1. Is/can there be a better/more elegant solution to this process?
2. Given the scope of this error/issue, is this something that can be addressed in Homebrew, or will it ultimately be up to AWS to update their plugin permissions?

### Command that failed

aws ssm start-session

### Output of command with `--verbose --debug`

<details><summary> aws ssm start-session --document-name AWS-StartInteractiveCommand --parameters command='sudo su - bleachbyte' --target [REDACTED-InstanceID] </summary><pre><code>

Command '['session-manager-plugin', '{"SessionId": "bleachbyte-0123456789abcdefg", "TokenValue": "[REDACTED]", "StreamUrl": "wss://ssmmessages.us-west-2.amazonaws.com/v1/data-channel/bleachbyte-0123456789abcdefg?role=publish_subscribe", "ResponseMetadata": {"RequestId": "[REDACTED]", "HTTPStatusCode": 200, "HTTPHeaders": {"server": "Server", "date": "Thu, 29 Jul 2021 17:59:34 GMT", "content-type": "application/x-amz-json-1.1", "content-length": "680", "connection": "keep-alive", "x-amzn-requestid": "[REDACTED]"}, "RetryAttempts": 0}}', 'us-west-2', 'StartSession', '', '{"Target": "[REDACTED]", "DocumentName": "AWS-StartInteractiveCommand", "Parameters": {"command": ["sudo su - bleachbyte"]}}', 'https://ssm.us-west-2.amazonaws.com']' died with <Signals.SIGKILL: 9>.

</code></pre></details>

<details><summary>brew reinstall --cask session-manager-plugin --verbose --debug</summary><pre><code>

$ brew reinstall --cask session-manager-plugin --verbose --debug
==> Cask::Installer#reinstall
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://session-manager-downloads.s3.amazonaws.com/plugin/1.2.234.0/mac/sessionmanager-bundle.zip
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.2.5-17-g689c1fd\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.7\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://session-manager-downloads.s3.amazonaws.com/plugin/1.2.234.0/mac/sessionmanager-bundle.zip
Already downloaded: /Users/bleachbyte/Library/Caches/Homebrew/downloads/ac45872cb4cfc1ade1e091a61176b819bf70cfa466cabeeafe02afefba4ff5ae--sessionmanager-bundle.zip
==> Checking quarantine support
/usr/bin/xattr -h
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/bleachbyte/Library/Caches/Homebrew/downloads/ac45872cb4cfc1ade1e091a61176b819bf70cfa466cabeeafe02afefba4ff5ae--sessionmanager-bundle.zip
/usr/bin/xattr -p com.apple.quarantine /Users/bleachbyte/Library/Caches/Homebrew/downloads/ac45872cb4cfc1ade1e091a61176b819bf70cfa466cabeeafe02afefba4ff5ae--sessionmanager-bundle.zip
==> /Users/bleachbyte/Library/Caches/Homebrew/downloads/ac45872cb4cfc1ade1e091a61176b819bf70cfa466cabeeafe02afefba4ff5ae--sessionmanager-bundle.zip is quarantined
==> Verifying checksum for cask 'session-manager-plugin'
hdiutil imageinfo -format /Users/bleachbyte/Library/Caches/Homebrew/downloads/ac45872cb4cfc1ade1e091a61176b819bf70cfa466cabeeafe02afefba4ff5ae--sessionmanager-bundle.zip
zipinfo -1 /Users/bleachbyte/Library/Caches/Homebrew/downloads/ac45872cb4cfc1ade1e091a61176b819bf70cfa466cabeeafe02afefba4ff5ae--sessionmanager-bundle.zip
==> Uninstalling Cask session-manager-plugin
==> Uninstalling artifacts
==> 1 artifact defined
#<SortedSet: {#<Cask::Artifact::Binary:0x00007f98618db1b0 @cask=#<Cask::Cask:0x00007f985eb31b10 @token="session-manager-plugin", @sourcefile_path=#<Pathname:/usr/local/Caskroom/session-manager-plugin/.metadata/1.2.234.0/20210729180854.354/Casks/session-manager-plugin.rb>, @tap=nil, @block=#<Proc:0x00007f985eb31a48@/usr/local/Caskroom/session-manager-plugin/.metadata/1.2.234.0/20210729180854.354/Casks/session-manager-plugin.rb:1>, @default_config=#<Cask::Config:0x00007f985eb31a20 @explicit={}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/session-manager-plugin>, @metadata_main_container_path=#<Pathname:/usr/local/Caskroom/session-manager-plugin/.metadata>, @config=#<Cask::Config:0x00007f985eb3ae40 @explicit={}, @default={:languages=>["en-US"], :appdir=>#<Pathname:/Applications>, :colorpickerdir=>#<Pathname:/Users/bleachbyte/Library/ColorPickers>, :prefpanedir=>#<Pathname:/Users/bleachbyte/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Users/bleachbyte/Library/QuickLook>, :mdimporterdir=>#<Pathname:/Users/bleachbyte/Library/Spotlight>, :dictionarydir=>#<Pathname:/Users/bleachbyte/Library/Dictionaries>, :fontdir=>#<Pathname:/Users/bleachbyte/Library/Fonts>, :servicedir=>#<Pathname:/Users/bleachbyte/Library/Services>, :input_methoddir=>#<Pathname:/Users/bleachbyte/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Users/bleachbyte/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Users/bleachbyte/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Users/bleachbyte/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Users/bleachbyte/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Users/bleachbyte/Library/Screen Savers>}, @env={}, @binarydir=#<Pathname:/usr/local/bin>>, @dsl=#<Cask::DSL:0x00007f985eb38848 @cask=#<Cask::Cask:0x00007f985eb31b10 ...>, @token="session-manager-plugin", @version="1.2.234.0", @sha256=#<Checksum:0x00007f985eb38578 @hexdigest="cb0da8b92c1e4ace7076ffacca3dbaeca683cb77220973e8438f38c5ca93ab14">, @url=#<URL::DSL:0x00007f98618dbe80 @uri=#<URI::HTTPS https://session-manager-downloads.s3.amazonaws.com/plugin/1.2.234.0/mac/sessionmanager-bundle.zip>, @verified="session-manager-downloads.s3.amazonaws.com/", @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @specs={:verified=>"session-manager-downloads.s3.amazonaws.com/", :user_agent=>:default}>, @name=["Session Manager Plugin for the AWS CLI"], @desc="Plugin for AWS CLI to start and end sessions that connect to managed instances", @homepage="https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html", @livecheck=#<Livecheck:0x00007f98618db688 @formula_or_cask=#<Cask::DSL:0x00007f985eb38848 ...>, @regex=/<td>\s*v?(\d+(?:\.\d+)+)\s*<\/td>/i, @skip=false, @skip_msg=nil, @strategy=nil, @url=:homepage>, @livecheckable=true, @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/session-manager-plugin/1.2.234.0>, @language_eval=nil>>, @source_string="sessionmanager-bundle/bin/session-manager-plugin", @target_string="", @source=#<Pathname:/usr/local/Caskroom/session-manager-plugin/1.2.234.0/sessionmanager-bundle/bin/session-manager-plugin>, @target=#<Pathname:/usr/local/bin/session-manager-plugin>>}>
==> Uninstalling artifact of class Cask::Artifact::Binary
==> Unlinking Binary '/usr/local/bin/session-manager-plugin'
==> Purging files for version 1.2.234.0 of Cask session-manager-plugin
==> Purging all staged versions of Cask session-manager-plugin
==> Installing Cask session-manager-plugin
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Zip for /Users/bleachbyte/Library/Caches/Homebrew/downloads/ac45872cb4cfc1ade1e091a61176b819bf70cfa466cabeeafe02afefba4ff5ae--sessionmanager-bundle.zip
zipinfo -1 /Users/bleachbyte/Library/Caches/Homebrew/downloads/ac45872cb4cfc1ade1e091a61176b819bf70cfa466cabeeafe02afefba4ff5ae--sessionmanager-bundle.zip
unzip -o /Users/bleachbyte/Library/Caches/Homebrew/downloads/ac45872cb4cfc1ade1e091a61176b819bf70cfa466cabeeafe02afefba4ff5ae--sessionmanager-bundle.zip -d /private/tmp/d20210729-70927-16jvfdo
cp -pR /private/tmp/d20210729-70927-16jvfdo/sessionmanager-bundle/. /usr/local/Caskroom/session-manager-plugin/1.2.234.0/sessionmanager-bundle
chmod -Rf +w /private/tmp/d20210729-70927-16jvfdo
==> Verifying Gatekeeper status of /Users/bleachbyte/Library/Caches/Homebrew/downloads/ac45872cb4cfc1ade1e091a61176b819bf70cfa466cabeeafe02afefba4ff5ae--sessionmanager-bundle.zip
/usr/bin/xattr -p com.apple.quarantine /Users/bleachbyte/Library/Caches/Homebrew/downloads/ac45872cb4cfc1ade1e091a61176b819bf70cfa466cabeeafe02afefba4ff5ae--sessionmanager-bundle.zip
==> /Users/bleachbyte/Library/Caches/Homebrew/downloads/ac45872cb4cfc1ade1e091a61176b819bf70cfa466cabeeafe02afefba4ff5ae--sessionmanager-bundle.zip is quarantined
==> Propagating quarantine from /Users/bleachbyte/Library/Caches/Homebrew/downloads/ac45872cb4cfc1ade1e091a61176b819bf70cfa466cabeeafe02afefba4ff5ae--sessionmanager-bundle.zip to /usr/local/Caskroom/session-manager-plugin/1.2.234.0
/usr/bin/xattr -p com.apple.quarantine /Users/bleachbyte/Library/Caches/Homebrew/downloads/ac45872cb4cfc1ade1e091a61176b819bf70cfa466cabeeafe02afefba4ff5ae--sessionmanager-bundle.zip
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;6101a111\;Homebrew\\x20Cask\;FE526EEE-6B66-45FA-A2AE-EB8367CC553A
==> Creating metadata directory: /usr/local/Caskroom/session-manager-plugin/.metadata/1.2.234.0/20210729182720.499
==> Creating metadata subdirectory: /usr/local/Caskroom/session-manager-plugin/.metadata/1.2.234.0/20210729182720.499/Casks
==> Installing artifacts
==> 1 artifact defined
#<SortedSet: {#<Cask::Artifact::Binary:0x00007f986195d228 @cask=#<Cask::Cask:0x00007f986189edc8 @token="session-manager-plugin", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/session-manager-plugin.rb>, @tap=#<Tap:0x00007f9862137728 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @formula_renames={}, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007f986189e738@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/session-manager-plugin.rb:1>, @default_config=#<Cask::Config:0x00007f985e0aef08 @explicit={}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/session-manager-plugin>, @metadata_main_container_path=#<Pathname:/usr/local/Caskroom/session-manager-plugin/.metadata>, @config=#<Cask::Config:0x00007f986195e588 @explicit={}, @binarydir=#<Pathname:/usr/local/bin>>, @dsl=#<Cask::DSL:0x00007f986195e358 @cask=#<Cask::Cask:0x00007f986189edc8 ...>, @token="session-manager-plugin", @version="1.2.234.0", @sha256=#<Checksum:0x00007f986195e0b0 @hexdigest="cb0da8b92c1e4ace7076ffacca3dbaeca683cb77220973e8438f38c5ca93ab14">, @url=#<URL::DSL:0x00007f986195db88 @uri=#<URI::HTTPS https://session-manager-downloads.s3.amazonaws.com/plugin/1.2.234.0/mac/sessionmanager-bundle.zip>, @verified="session-manager-downloads.s3.amazonaws.com/", @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @specs={:verified=>"session-manager-downloads.s3.amazonaws.com/", :user_agent=>:default}>, @name=["Session Manager Plugin for the AWS CLI"], @desc="Plugin for AWS CLI to start and end sessions that connect to managed instances", @homepage="https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html", @livecheck=#<Livecheck:0x00007f986195d570 @formula_or_cask=#<Cask::DSL:0x00007f986195e358 ...>, @regex=/<td>\s*v?(\d+(?:\.\d+)+)\s*<\/td>/i, @skip=false, @skip_msg=nil, @strategy=nil, @url=:homepage>, @livecheckable=true, @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/session-manager-plugin/1.2.234.0>, @language_eval=nil>>, @source_string="sessionmanager-bundle/bin/session-manager-plugin", @target_string="", @source=#<Pathname:/usr/local/Caskroom/session-manager-plugin/1.2.234.0/sessionmanager-bundle/bin/session-manager-plugin>, @target=#<Pathname:/usr/local/bin/session-manager-plugin>>}>
==> Installing artifact of class Cask::Artifact::Binary
==> Linking Binary 'session-manager-plugin' to '/usr/local/bin/session-manager-plugin'
/bin/ln -h -f -s -- /usr/local/Caskroom/session-manager-plugin/1.2.234.0/sessionmanager-bundle/bin/session-manager-plugin /usr/local/bin/session-manager-plugin
/usr/local/Homebrew/Library/Homebrew/shims/scm/git --version
🍺  session-manager-plugin was successfully installed!

</code></pre></details>

### Output of `brew doctor --verbose`

<details><summary>Click to expand</summary><pre><code>

==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
==> $LOAD_PATHS
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/warning-1.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tapioca-0.4.23/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/spoom-1.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thor-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-stub-0.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-cobertura-1.4.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-0.21.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov_json_formatter-0.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-html-0.12.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-sorbet-0.6.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rails-2.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-1.18.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unicode-display_width-2.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.11.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-ast-1.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec_junit_formatter-0.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-sorbet-1.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-0.5.6274/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-static-0.5.6274-universal-darwin-14/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-github-2.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-3.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-mocks-3.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-expectations-3.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-core-3.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-support-3.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/regexp_parser-2.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rdiscount-2.2.0.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/rdiscount-2.2.0.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rack-2.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/pry-0.14.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/patchelf-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parlour-6.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-0.5.6274/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parser-3.0.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel_tests-3.7.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel-1.20.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/method_source-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.8.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrick-1.7.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubyntlm-0.6.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.11.7-x86_64-darwin/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/racc-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/racc-1.5.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.5.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-4.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-data-3.2021.0704/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/elftools-1.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.7.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/unf_ext-0.0.7.7
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.4.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/did_you_mean-1.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/commander-4.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/highline-2.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/colorize-0.8.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/coderay-1.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/byebug-11.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/byebug-11.1.3
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bootsnap-1.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/bootsnap-1.7.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/msgpack-1.4.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/msgpack-1.4.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bindata-2.4.10/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ast-2.4.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/addressable-2.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/public_suffix-4.0.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.4.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-2.0.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/minitest-5.14.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.10/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/site_ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/site_ruby/2.6.0/x86_64-darwin14
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/vendor_ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/vendor_ruby/2.6.0/x86_64-darwin14
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/x86_64-darwin14
/usr/local/Homebrew/Library/Homebrew
==> Homebrew Version
3.2.5-17-g689c1fd
==> macOS
10.15.7
==> SIP
Enabled
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3958 casks)
/usr/local/Homebrew/Library/Taps/chef/homebrew-chef (4 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (195 casks)
Your system is ready to brew.

</code></pre></details>

### Output of `brew tap`

<details><summary>Click to expand</summary><pre><code>

chef/chef
cloudfoundry/tap
domt4/autoupdate
homebrew/bundle
homebrew/cask
homebrew/cask-versions
homebrew/core
homebrew/services
lucagrulla/tap
mikhailai/misc

</code></pre></details>

**Comment by miccal** [comment]
Unfortunately there is not way around this without using the `--no-quarantine` flag, as we are not able to remove the quarantine protection via Cask.

Another way is to set `HOMEBREW_CASK_OPTS="--no-quarantine"` as an [environment variable](https://docs.brew.sh/Manpage#environment).
