### ISSUE TITLE
Metasploit.rb cask broken after recent update to 6.0.55

### ISSUE THREAD

**Issue by christiaaneggink** [Homebrew/homebrew-cask#109333]
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

Installing the Metaspoit cask fails after recent update to 6.0.55:

```
==> Downloading https://osx.metasploit.com/metasploit-framework-6.0.54%2B2021071
##O#- #                                                                       
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'metasploit' with message: Download failed: https://osx.metasploit.com/metasploit-framework-6.0.54%2B20210718102925-1rapid7-1.pkg
c
```

### Command that failed

brew install --cask metasploit --force

### Output of command with `--verbose --debug`

<details><summary>Click to expand</summary><pre><code>

Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 102 formulae.
==> Deleted Formulae
giter8
==> Updated Casks
Updated 11 casks.

==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.2.5-19-gbdc3391\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.4\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://osx.metasploit.com/metasploit-framework-6.0.54\%2B20210718102925-1rapid7-1.pkg
==> Downloading https://osx.metasploit.com/metasploit-framework-6.0.54%2B20210718102925-1rapid7-1.pkg
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.2.5-19-gbdc3391\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.4\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --head https://osx.metasploit.com/metasploit-framework-6.0.54\%2B20210718102925-1rapid7-1.pkg
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.2.5-19-gbdc3391\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.4\)\ curl/7.64.1 --header Accept-Language:\ en --fail --retry 3 --location --remote-time --output /Users/christiaaneggink/Library/Caches/Homebrew/downloads/bcc73a5fce3c14c3dd25b74e237fe5513e69abcc74eff051946b918f68d224c8--metasploit-framework-6.0.54\+20210718102925-1rapid7-1.pkg.incomplete https://osx.metasploit.com/metasploit-framework-6.0.54\%2B20210718102925-1rapid7-1.pkg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'metasploit' with message: Download failed: https://osx.metasploit.com/metasploit-framework-6.0.54%2B20210718102925-1rapid7-1.pkg
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:410:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:407:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:25:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:171:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:73:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:100:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:69:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:68:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:68:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:167:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:131:in `<main>'

</code></pre></details>

### Output of `brew doctor --verbose`

<details><summary>Click to expand</summary><pre><code>

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libmcrypt.4.4.8.dylib
  /usr/local/lib/libmhash.2.0.1.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/mcrypt.h
  /usr/local/include/mhash.h
  /usr/local/include/mutils/mcrypt.h
  /usr/local/include/mutils/mglobal.h
  /usr/local/include/mutils/mhash.h
  /usr/local/include/mutils/mhash_config.h
  /usr/local/include/mutils/mincludes.h
  /usr/local/include/mutils/mtypes.h
  /usr/local/include/mutils/mutils.h

Warning: Unbrewed '.la' files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.la' files:
  /usr/local/lib/libmcrypt.la
  /usr/local/lib/libmhash.la

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libmhash.a

</code></pre></details>

### Output of `brew tap`

<details><summary>Click to expand</summary><pre><code>

homebrew/cask
homebrew/core
homebrew/services

</code></pre></details>

**Comment by bevanjkay** [comment]
It looks like the command is trying to download the previous version of the cask. 

What is the output of `brew info metasploit`?

**Comment by SMillerDev** [comment]
I think I merged an update after this was created, try running `brew update` and trying again.

**Comment by christiaaneggink** [comment]
Awesome, works like a charm now.
