### ISSUE TITLE
Cannot install zoom on ARM machine - incorrect brew prefix location

### ISSUE THREAD

**Issue by vraravam** [Homebrew/homebrew-cask#110152]
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

Trying to install zoom on a Mac M1 machine, I get the following error:
```bash
sudo: unable to run /usr/local/bin/ssh-askpass
```

This is wrong - since, on an ARM machine, the path should be `/opt/homebrew` as opposed to `/usr/local`

### Command that failed

brew install zoom

### Output of command with `--verbose --debug`

<details><summary>Click to expand</summary><pre><code>

REPLACE THIS TEXT WITH THE OUTPUT

</code></pre></details>

### Output of `brew doctor --verbose`

<details><summary>Click to expand</summary><pre><code>

REPLACE THIS TEXT WITH THE OUTPUT

</code></pre></details>

### Output of `brew tap`

<details><summary>Click to expand</summary><pre><code>

REPLACE THIS TEXT WITH THE OUTPUT

</code></pre></details>

**Comment by SMillerDev** [comment]
There is no code in the cask that runs that command so I think it's an issue with your dot files.
