### ISSUE TITLE
Iterm2 version higher than official version on the website

### ISSUE THREAD

**Issue by Moulick** [Homebrew/homebrew-cask#110506]
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).

### Description of issue

The version of iterm2 in homebrew-cask was upgraded to `3.4.9` via https://github.com/Homebrew/homebrew-cask/pull/110277 while the official _stable_ version on https://iterm2.com/downloads.html is still `3.4.8`

Is this ok ?

**Comment by Moulick** [comment]
It seems that 
https://raw.githubusercontent.com/gnachman/iterm2-website/master/source/appcasts/final_modern.xml and 
https://github.com/gnachman/iTerm2/releases/tag/v3.4.9 both exist but the website does not mention this release 
Also the https://iterm2.com/appcasts/full_changes.txt is missing the 3.4.9 release

**Comment by SMillerDev** [comment]
You can ask iTerm about this, it seems like they themselves aren't sure what the latest release is.

**Comment by Moulick** [comment]
Create a ticket on their gitlab repo https://gitlab.com/gnachman/iterm2/-/issues/9879

**Comment by bevanjkay** [comment]
@Moulick The iTerm2 website has now been updated with `3.4.9` being the latest version.
