### ISSUE TITLE
sha256 mismatch on install of older docker desktop version

### ISSUE THREAD

**Issue by haakandev** [Homebrew/homebrew-cask#111091]
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

I'm trying to install an older version of [docker desktop](https://formulae.brew.sh/cask/docker), specifically [version 3.3.3](https://github.com/Homebrew/homebrew-cask/blob/961b663cc4defff883089f33e0e2687bcfd8d934/Casks/docker.rb).

However I get a sha256 mismatch as seen in the logs. I tried to following the checksum does not match error docs, but not sure if they apply since I'm trying to install an older version on purpose, and the actual sha256 is not from the latest version anyway. As far as I can tell, if I manually update the sha256 in the cask file, the correct docker desktop version is installed.

I attempted to submit an automatic fix as well, but it failed to download the file:
<details><summary>Logs</summary><pre><code>

seermedical@SeerMedicals-Mac-mini test % brew bump-cask-pr --version "3.3.3,64133" docker         
Updating Homebrew...
==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 1 formula.

Warning: bump-cask-pr is a developer command, so
Homebrew's developer mode has been automatically turned on.
To turn developer mode off, run brew developer off

==> Installing 'bundler' gem
Fetching bundler-1.17.3.gem
Fetching gem metadata from https://rubygems.org/.........
Fetching zeitwerk 2.4.2
Fetching concurrent-ruby 1.1.9
Fetching minitest 5.14.4
Installing zeitwerk 2.4.2
Installing minitest 5.14.4
Installing concurrent-ruby 1.1.9
Fetching public_suffix 4.0.6
Installing public_suffix 4.0.6
Fetching ast 2.4.2
Installing ast 2.4.2
Fetching bindata 2.4.10
Installing bindata 2.4.10
Fetching msgpack 1.4.2
Installing msgpack 1.4.2 with native extensions
Using bundler 1.17.3
Fetching byebug 11.1.3
Installing byebug 11.1.3 with native extensions
Fetching connection_pool 2.2.5
Installing connection_pool 2.2.5
Fetching did_you_mean 1.5.0
Installing did_you_mean 1.5.0
Fetching diff-lcs 1.4.4
Installing diff-lcs 1.4.4
Fetching docile 1.4.0
Installing docile 1.4.0
Fetching unf_ext 0.0.7.7
Installing unf_ext 0.0.7.7 with native extensions
Fetching hpricot 0.8.6
Installing hpricot 0.8.6 with native extensions
Fetching mime-types-data 3.2021.0901
Installing mime-types-data 3.2021.0901
Fetching net-http-digest_auth 1.4.1
Installing net-http-digest_auth 1.4.1
Fetching mini_portile2 2.5.3
Installing mini_portile2 2.5.3
Fetching racc 1.5.2
Installing racc 1.5.2 with native extensions
Fetching rubyntlm 0.6.3
Installing rubyntlm 0.6.3
Fetching webrick 1.7.0
Installing webrick 1.7.0
Fetching webrobots 0.1.2
Installing webrobots 0.1.2
Fetching mustache 1.1.1
Installing mustache 1.1.1
Fetching parallel 1.20.1
Installing parallel 1.20.1
Fetching plist 3.6.0
Installing plist 3.6.0
Fetching rack 2.2.3
Installing rack 2.2.3
Fetching rainbow 3.0.0
Installing rainbow 3.0.0
Fetching rdiscount 2.2.0.2
Installing rdiscount 2.2.0.2 with native extensions
Fetching regexp_parser 2.1.1
Installing regexp_parser 2.1.1
Fetching rexml 3.2.5
Installing rexml 3.2.5
Fetching rspec-support 3.10.2
Installing rspec-support 3.10.2
Fetching ruby-progressbar 1.11.0
Installing ruby-progressbar 1.11.0
Fetching unicode-display_width 2.0.0
Installing unicode-display_width 2.0.0
Fetching ruby-macho 2.5.1
Installing ruby-macho 2.5.1
Fetching simplecov-html 0.12.3
Installing simplecov-html 0.12.3
Fetching simplecov_json_formatter 0.1.3
Installing simplecov_json_formatter 0.1.3
Fetching sorbet-runtime-stub 0.2.0
Installing sorbet-runtime-stub 0.2.0
Fetching warning 1.2.0
Installing warning 1.2.0
Fetching parser 3.0.2.0
Installing parser 3.0.2.0
Fetching addressable 2.8.0
Installing addressable 2.8.0
Fetching elftools 1.1.3
Installing elftools 1.1.3
Fetching i18n 1.8.10
Installing i18n 1.8.10
Fetching tzinfo 2.0.4
Installing tzinfo 2.0.4
Fetching net-http-persistent 4.0.1
Installing net-http-persistent 4.0.1
Fetching bootsnap 1.8.1
Installing bootsnap 1.8.1 with native extensions
Fetching mime-types 3.3.1
Installing mime-types 3.3.1
Fetching unf 0.1.4
Installing unf 0.1.4
Fetching parallel_tests 3.7.1
Installing parallel_tests 3.7.1
Fetching nokogiri 1.11.7 (x86_64-darwin)
Installing nokogiri 1.11.7 (x86_64-darwin)
Fetching rspec-core 3.10.1
Installing rspec-core 3.10.1
Fetching rspec-expectations 3.10.1
Installing rspec-expectations 3.10.1
Fetching rspec-mocks 3.10.2
Installing rspec-mocks 3.10.2
Fetching simplecov 0.21.2
Installing simplecov 0.21.2
Fetching rubocop-ast 1.11.0
Installing rubocop-ast 1.11.0
Fetching patchelf 1.3.0
Installing patchelf 1.3.0
Fetching activesupport 6.1.4.1
Installing activesupport 6.1.4.1
Fetching domain_name 0.5.20190701
Installing domain_name 0.5.20190701
Fetching rspec-github 2.3.1
Installing rspec-github 2.3.1
Fetching rspec-retry 0.6.2
Installing rspec-retry 0.6.2
Fetching rspec_junit_formatter 0.4.1
Installing rspec_junit_formatter 0.4.1
Fetching rspec-its 1.3.0
Installing rspec-its 1.3.0
Fetching rspec 3.10.0
Installing rspec 3.10.0
Fetching simplecov-cobertura 1.4.2
Installing simplecov-cobertura 1.4.2
Fetching rubocop 1.20.0
Installing rubocop 1.20.0
Fetching http-cookie 1.0.4
Installing http-cookie 1.0.4
Fetching rspec-wait 0.0.9
Installing rspec-wait 0.0.9
Fetching rubocop-performance 1.11.5
Installing rubocop-performance 1.11.5
Fetching rubocop-rails 2.11.3
Installing rubocop-rails 2.11.3
Fetching rubocop-rspec 2.4.0
Installing rubocop-rspec 2.4.0
Fetching rubocop-sorbet 0.6.2
Installing rubocop-sorbet 0.6.2
Fetching mechanize 2.8.1
Installing mechanize 2.8.1
Fetching ronn 0.7.3
Installing ronn 0.7.3
Bundle complete! 33 Gemfile dependencies, 72 gems now installed.
Bundled gems are installed into `../../../usr/local/Homebrew/Library/Homebrew/vendor/bundle`
==> Downloading https://desktop.docker.com/mac/main/amd64/64133/Docker.dmg
##O=#  #                                                                      
curl: (22) The requested URL returned error: 403 
Error: Failed to download resource "docker"
Download failed: https://desktop.docker.com/mac/main/amd64/64133/Docker.dmg

</code></pre></details>

### Command that failed

curl -O https://raw.githubusercontent.com/Homebrew/homebrew-cask/961b663cc4defff883089f33e0e2687bcfd8d934/Casks/docker.rb && brew install --cask --no-quarantine docker.rb

### Output of command with `--verbose --debug`

<details><summary>Click to expand</summary><pre><code>

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2456  100  2456    0     0   119k      0 --:--:-- --:--:-- --:--:--  119k
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /Users/seermedical/test/docker.rb
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/curl --disable --cookie-jar /dev/null --globoff --show-error --user-agent Homebrew/3.2.11-28-g5c60200\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.5.2\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://desktop.docker.com/mac/stable/amd64/64133/Docker.dmg
==> Downloading https://desktop.docker.com/mac/stable/amd64/64133/Docker.dmg
/usr/bin/curl --disable --cookie-jar /dev/null --globoff --show-error --user-agent Homebrew/3.2.11-28-g5c60200\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.5.2\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --head https://desktop.docker.com/mac/stable/amd64/64133/Docker.dmg
/usr/bin/curl --disable --cookie-jar /dev/null --globoff --show-error --user-agent Homebrew/3.2.11-28-g5c60200\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.5.2\)\ curl/7.64.1 --header Accept-Language:\ en --fail --retry 3 --location --remote-time --output /Users/seermedical/Library/Caches/Homebrew/downloads/2cc36211072280d8bce8a8aba0b9c65c40eb3bcddbcea07053f9627b483071db--Docker.dmg.incomplete https://desktop.docker.com/mac/stable/amd64/64133/Docker.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  576M  100  576M    0     0  42.6M      0  0:00:13  0:00:13 --:--:-- 45.3M
==> Checking quarantine support
/usr/bin/xattr -h
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/seermedical/Library/Caches/Homebrew/downloads/2cc36211072280d8bce8a8aba0b9c65c40eb3bcddbcea07053f9627b483071db--Docker.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/seermedical/Library/Caches/Homebrew/downloads/2cc36211072280d8bce8a8aba0b9c65c40eb3bcddbcea07053f9627b483071db--Docker.dmg
==> /Users/seermedical/Library/Caches/Homebrew/downloads/2cc36211072280d8bce8a8aba0b9c65c40eb3bcddbcea07053f9627b483071db--Docker.dmg is not quarantined
==> Verifying checksum for cask 'docker'
Error: SHA256 mismatch
Expected: f143645bfd38e1dc93a773b1eb4a7b1e12832ddce20fc49e7057937838e7bf45
  Actual: 3c164120fec236b4981aed2b820417d475c83cb0b297d456ee54dc366bff9d40
    File: /Users/seermedical/Library/Caches/Homebrew/downloads/2cc36211072280d8bce8a8aba0b9c65c40eb3bcddbcea07053f9627b483071db--Docker.dmg
To retry an incomplete download, remove the file above.
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:292:in `verify_checksum'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:68:in `verify_download_integrity'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:33:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:174:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:73:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:69:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:68:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:68:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:167:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:129:in `<main>'

</code></pre></details>

### Output of `brew doctor --verbose`

<details><summary>Click to expand</summary><pre><code>

Your system is ready to brew.

</code></pre></details>

### Output of `brew tap`

<details><summary>Click to expand</summary><pre><code>

homebrew/cask
homebrew/core

</code></pre></details>

**Comment by bevanjkay** [comment]
@haakandev The `homebrew-cask` repository only maintains the most recent versions of each cask.
The addition of docker version 3 to the [`homebrew-cask-versions`](https://github.com/Homebrew/homebrew-cask-versions/) repository would be considered if you create a PR to add it there. Otherwise consider including the version you are after  [in your own Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap).
