### ISSUE TITLE
Request name change of cask lynx to be lynx-whiteboard

### ISSUE THREAD

**Issue by PhilHannent** [Homebrew/homebrew-cask#111128]
### Provide a detailed description of the proposed feature

I'd like to request the cask I originally setup (lynx.rb) be renamed to be lynx-whiteboard. This would have less clash with the open source lynx web browser and make it clearer what the product is.

### What is the motivation for the feature?

End user clarity.

### Example use case

User's don't accidentally install a text web browser rather than Lynx Whiteboard.

**Comment by miccal** [comment]
Thank you @PhilHannent, but the current name `lynx` follows our strict [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference) as the `pkg` installs an `app` called `Lynx #{version.major}.app`.
