### ISSUE TITLE
rightzoom: checksum mismatch due to in-place update (same version number)

### ISSUE THREAD

**Issue by brevilo** [Homebrew/homebrew-cask#111540]
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

Apparently, RightZoom was updated in-place on [2021-09-17](https://www.blazingtools.com/mac/), so without changing it's version (probably [adding support](https://www.blazingtools.com/right_zoom_mac.html) for macOS 12):
```
Expected: 026b18288814a6c548fe18730b4959b8e968ffb2eef31517796e72f7b988242c
  Actual: 60ad9b6a54dc1191159dc4ac557d095a38780afec4f7d3067093da98037fe476
```
I would have used `bump-cask-pr` but I'm not sure how to version the Cask in such a case. We need a "homebrew-internal" version bump.

### Command that failed

`brew install rightzoom`

**Comment by bevanjkay** [comment]
#111541 Fixes this. FYI you can just use `bump-cask-pr` and use the current version.

**Comment by brevilo** [comment]
> FYI you can just use `bump-cask-pr` and use the current version.

Good to know. Thanks!
