### ISSUE TITLE
Deprecate homebrew-cask-versions and migrate casks to homebrew-cask

### ISSUE THREAD

**Issue by gdams** [Homebrew/homebrew-cask#112102]
### Provide a detailed description of the proposed feature

Now that we have enough automation in place, I propose that we deprecate [homebrew-cask-versions](https://github.com/Homebrew/homebrew-cask-versions) and either migrate or deprecate (on a case-by-case basis) the casks that are listed there.

CC @MikeMcQuaid @vitorgalvao 

### What is the motivation for the feature?

From a maintainers point of view, maintaining two repos is more work than just one. There are only a small number of casks listed at homebrew-cask-versions and by migrating them to this repo we improve the end-user experience (by not needing to tap cask-versions).

### Example use case

n/a

**Comment by bevanjkay** [comment]
I am generally in favour of doing this. We will need a way of handling the different versions (ie. beta, nightly, etc..) in the main cask repo. In the cases of legacy major versioned casks, we will need a syntax there as well. Not sure on the pros and cons of the `@#{version}` syntax from `homebrew-core`.

It is probably worth discussing merging `homebrew-cask-drivers` at the same time. I am not aware of any downsides of moving them into the main cask repo, other than there being a number of unpopular (niche) driver casks. Perhaps moving casks with a certain analytic figure could be the way to go?

**Comment by MikeMcQuaid** [comment]
> Not sure on the pros and cons of the `@#{version}` syntax from `homebrew-core`.

I think it'd be good to be consistent unless it's overly laborious in terms of code changes required.

**Comment by MikeMcQuaid** [comment]
> It is probably worth discussing merging `homebrew-cask-drivers` at the same time. I am not aware of any downsides of moving them into the main cask repo, other than there being a number of unpopular (niche) driver casks. Perhaps moving casks with a certain analytic figure could be the way to go?

Agreed. I'd love to see us get down to ideally a single `homebrew-cask` repo and have the others either archived or migrated out.

**Comment by gdams** [comment]
>In the cases of legacy major versioned casks, we will need a syntax there as well. Not sure on the pros and cons of the @#{version} syntax from homebrew-core.

Looking at most of the casks in cask-versions they either have a major version number (e.g `cask9.rb`) or use `cask-beta`, `cask-nightly` `cask-pre`, `cask-edge`, `cask-legacy`, `cask-dev`.

It would be good to agree on a standard for beta builds.

With legacy builds I feel the simplest way is to use the semver major approach (e.g `temurin8` or `temurin11`)

I would suggest that we begin by migrating all of the versioned casks (as they seem to be the simplest to carry over and then look back round for the remaining casks?

**Comment by bevanjkay** [comment]
> Looking at most of the casks in cask-versions they either have a major version number (e.g `cask9.rb`) or use `cask-beta`, `cask-nightly` `cask-pre`, `cask-edge`, `cask-legacy`, `cask-dev`.



> Looking at most of the casks in cask-versions they either have a major version number (e.g `cask9.rb`) or use `cask-beta`, `cask-nightly` `cask-pre`, `cask-edge`, `cask-legacy`, `cask-dev`.
> 
> It would be good to agree on a standard for beta builds.

I agree that standardised naming conventions are the best option. We will need to consider instances (there's only a couple) that have multiple variants available, `google-chrome-dev`, `google-chrome-canary` and `google-chrome-beta` for example.

> With legacy builds I feel the simplest way is to use the semver major approach (e.g temurin8 or temurin11)
This is currently how the casks are named, however it isn't consistent with `homebrew-core`.

**Comment by gdams** [comment]
>This is currently how the casks are named, however it isn't consistent with homebrew-core.

So let's say we decided to rename the versioned ones to (e.g `temurin@11`) to match homebrew-core. Would we be able to use the [tap_migrations.json](https://github.com/Homebrew/homebrew-cask-versions/blob/master/tap_migrations.json) to redirect users? I'm not sure how that works and whether it supports cask name changes or just migrations to homebrew-core?

**Comment by MikeMcQuaid** [comment]
I'm not sure what the cask support is like for renaming. It was implemented for formulae but not sure if it ever was for casks.

**Comment by gdams** [comment]
> I'm not sure what the cask support is like for renaming. It was implemented for formulae but not sure if it ever was for casks.

Yeah it looks like we'd need to add support for Aliases to homebrew-cask (which wouldn't be a bad thing to do TBF)

**Comment by bevanjkay** [comment]
@gdams Renaming is not currently supported for `cask` - so would be a blocking requirement. But has been definitely needed - see #111512 and the `zoom`/`zoomus` rename.

**Comment by MikeMcQuaid** [comment]
I'd rather see these merged before we block on renaming. With that in mind: I think we should just keep the existing names.

**Comment by gdams** [comment]
> I'd rather see these merged before we block on renaming. With that in mind: I think we should just keep the existing names.

I can take a look at adding support for Aliases? I've never looked at the actual CLI codebase in my life but this would make the migration 100 times easier

**Comment by MikeMcQuaid** [comment]
@gdams you're welcome to take a look. I'd suggest instead of aliases that you look at https://github.com/Homebrew/homebrew-core/blob/master/formula_renames.json and the relevant code that handles it (`brew migrate`, `Migrator`) to consider allowing it to support casks, too.

**Comment by MikeMcQuaid** [comment]
(note: renames add implicit aliases)

**Comment by vitorgalvao** [comment]
> I can take a look at adding support for Aliases?

Instead of aliases, we should get the equivalent to `formula_renames.json` for casks. [That’s a much needed feature](https://github.com/Homebrew/homebrew-cask/issues/112102#issuecomment-934347233).

> It would be good to agree on a standard for beta builds.

The standard is what upstream calls it. [That’s what allows the same software with multiple variants](https://github.com/Homebrew/homebrew-cask/issues/112102#issuecomment-934341920).

Regarding `homebrew-cask-drivers`, we should *not* just move the casks because it would create a mess—most aren’t popular and the naming scheme for that repo is different (it includes the vendor as a prefix). We should instead just move the really popular ones which have an app (i.e. not simply a kext or similar) and let the others go, ideally giving away the repo to someone in the community who feels like taking care of it.

**Comment by gdams** [comment]
@MikeMcQuaid / @vitorgalvao are either of you able to point me in the rough direction where such a code change might be made? I'm trying to locate where the existing `formula_renames.json` stuff is actually used

**Comment by MikeMcQuaid** [comment]
> Instead of aliases, we should get the equivalent to `formula_renames.json` for casks. [That’s a much needed feature](https://github.com/Homebrew/homebrew-cask/issues/112102#issuecomment-934347233).

👍🏻 and it brings aliases for free

> We should instead just move the really popular ones which have an app (i.e. not simply a kext or similar) and let the others go, ideally giving away the repo to someone in the community who feels like taking care of it.

👍🏻 



> @MikeMcQuaid / @vitorgalvao are either of you able to point me in the rough direction where such a code change might be made? I'm trying to locate where the existing `formula_renames.json` stuff is actually used

@gadams best bet is to ask in Slack, I'm snowed under personally.

**Comment by dr3mro** [comment]
Qt-Creator 6.0 released

**Comment by neutric** [comment]
@dr3mro Please don't litter unrelated issues, opening a new one is still free of charge. ;) Apart from that, Qt-Creator 6 is still in beta stage afaik.

**Comment by JounQin** [comment]
In homebrew-cask-versions, there are some casks not using official download links due to unstable appcenter links like [`clashx-pro`](https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/clashx-pro.rb#L5), will that be allowed when merging.

I have a proposal #107354 before to add a new [`AppCenterDownloadStrategy`](https://github.com/JounQin/brew/commit/d7fd241a5ff31c904c7275cb974cfa8ce0681887), but I personally not very familiar with ruby and testing with it.

Should these cases be considered?

**Comment by MikeMcQuaid** [comment]
@jounqin Can you elaborate what is meant by "unstable" here? Thanks!

**Comment by JounQin** [comment]
> @JounQin Can you elaborate what is meant by "unstable" here? Thanks!

@MikeMcQuaid Take https://github.com/Homebrew/homebrew-cask/pull/86109/files#diff-3613a5c84fb0ae218d5189a6432b5d06ba33680109ff8fd9fb0f4e7fd11bdc44R6 as example, its download url will be invalid after a few minutes.

**Comment by MikeMcQuaid** [comment]
@jounqin Yeh, that seems not great. A `AppCenterDownloadStrategy` sounds like a good fix 👍🏻

**Comment by vitorgalvao** [comment]
> In homebrew-cask-versions, there are some casks not using official download links due to unstable appcenter links like [`clashx-pro`](https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/clashx-pro.rb#L5)

If a `url` is in a cask, it’s either official or a mistake. [`mpv` is the one we know about](https://github.com/Homebrew/homebrew-cask/issues/86226) and are discussing how to fix.

If there are more, they need to be corrected; we don’t want non-official links. @miccal [You merged this one](https://github.com/Homebrew/homebrew-cask-versions/pull/10472), do you remember?

None of this precludes an `AppCenterDownloadStrategy` strategy. A few years ago there was a user who worked for Microsoft and said they’d talk with the team about it, but nothing ever came of it.

**Comment by miccal** [comment]
> If there are more, they need to be corrected; we don’t want non-official links. @miccal [You merged this one](https://github.com/Homebrew/homebrew-cask-versions/pull/10472), do you remember?

Yes I do remember, and I recall being suprosed that this one was "stable".

And it still is, it seems:
```
|-> brew livecheck clashx-pro
clashx-pro : 1.72.0.1 ==> 1.72.0.1
```
```
|-> brew fetch clashx-pro
==> Downloading https://appcenter.vercel.app/clashx/clashx-pro/1.72.0.1
==> Downloading from https://appcenter-filemanagement-distrib5ede6f06e.azureedge.net/a59d3822-d12f-417d-8aae-664b2cac83cd/ClashX.dmg?sv=2019-02-02&sr=c&sig=a%2Fojvc3ssxgSHb0mDVyzTKXjLijE0cKo1FgHH9q5EwM%3D&se=2021-11-23T19%3A10%3A40Z&sp=
######################################################################## 100.0%
Downloaded to: /Users/miccal/Library/Caches/Homebrew/downloads/dfd5849e2e33931fef2b41fc63786a6d0bd0b1bf65ae595c3bda0e41cc628b0b--ClashX.dmg
SHA256: 36751e6f18073c1dcd5924b632d7a135123b3a0f6fd6af17040a7fbc4abe0bc3
```

> None of this precludes an `AppCenterDownloadStrategy` strategy. A few years ago there was a user who worked for Microsoft and said they’d talk with the team about it, but nothing ever came of it.

I opened an issue with Microsoft at this user's request, but it was never answered and I closed it after a month or two.

**Comment by MikeMcQuaid** [comment]
IMO the scope here should expand to "migrate casks from all homebrew-cask-* repos into homebrew-cask"

**Comment by vitorgalvao** [comment]
[Reminder](https://github.com/Homebrew/homebrew-cask/issues/112102#issuecomment-934355004) that moving the drivers repo without a pre-selection could be messy (last paragraph).

The fonts repo is probably worth keeping separate: it has a ton of casks but they are not of interest to everyone and its repo management is mostly automatic.

**Comment by aspauldingcode** [comment]
Is this still open?
I have a feeling it should be closed.
Can a maintainer check?

**Comment by MikeMcQuaid** [comment]
https://github.com/homebrew/homebrew-cask-versions has not been archived so it should stay open.

**Comment by bevanjkay** [comment]
@Homebrew/cask We are hoping to move forward with the migration of `homebrew-cask-versions` to `homebrew-cask` ASAP.

The current step is to lock in a naming convention for consistency.

Proposing that we go with `name@(version|channel)`
Examples: `google-chrome@beta`, `1password@7`

The advantages are that it keeps the naming convention in line with `homebrew-core` and also clearly distinguishes a "version" as some casks already end in a number that is intrinsically part of the name (ie. `iterm2`).

**Comment by MikeMcQuaid** [comment]
> [Reminder](https://github.com/Homebrew/homebrew-cask/issues/112102#issuecomment-934355004) that moving the drivers repo without a pre-selection could be messy (last paragraph).

Just for context for anyone following along: drivers was migrated and archived 🎉

**Comment by michaelblyons** [comment]
Someone might want to change the documentation at https://docs.brew.sh/Acceptable-Casks#beta-unstable-development-nightly-or-legacy

**Comment by p-linnane** [comment]
It will be updated once the migration is complete.

**Comment by p-linnane** [comment]
Closing as this is now complete.

**Comment by MikeMcQuaid** [comment]
Great work here everyone!

What do we want to do with homebrew-cask-fonts?

**Comment by miccal** [comment]
> What do we want to do with homebrew-cask-fonts?

Move them all into a sharded directory called `fonts` and let https://github.com/Homebrew/homebrew-cask/issues/172816 know to pull updates from that folder only?

**Comment by p-linnane** [comment]
Fully agree with @miccal. It would be nice to get rid of the fonts repo and have everything in the main (only) repo.

**Comment by bevanjkay** [comment]
Yeah I think that seems reasonable, unless adding 2,200 files to a directory is going to cause issues. Note that many are "Google Fonts" which are seldom updated, as they are unversioned and updates are managed systematically.

**Comment by p-linnane** [comment]
> Yeah I think that seems reasonable, unless adding 2,200 files to a directory is going to cause issues. Note that many are "Google Fonts" which are seldom updated, as they are unversioned and are managed systematically. 

I figured we would create a `fonts` directory and shard it.

**Comment by razvanazamfirei** [comment]
> Yeah I think that seems reasonable, unless adding 2,200 files to a directory is going to cause issues

If we do this, I'd like to change the syntax check to be scoped to modified files only. Tap syntax checks are already taking too long.

**Comment by MikeMcQuaid** [comment]
> Yeah I think that seems reasonable, unless adding 2,200 files to a directory is going to cause issues.

It is. They will need to be sharded further inside that directory.

Also they'll need to be renamed to start with `font-` (if they aren't already) and move the existing `font*` casks in there, too, otherwise various bits of tooling/libraries will break down.

> If we do this, I'd like to change the syntax check to be scoped to modified files only.

We should not do this. I know it's frustrating for this to take a while but this sort of modification detection ends up inevitably failing and ending up with a broken `master`.

If they are taking too long: let's figure out how best to speed up these checks.

> Move them all into a sharded directory called `font` and let [Homebrew/homebrew-linux-fonts](https://github.com/Homebrew/homebrew-linux-fonts) know to pull updates from that folder only?

I don't think it's worth optimising too hard based on this tap.

**Comment by bevanjkay** [comment]
Yeah they all have tokens that start with `font-*`. But they aren't currently sharded further, so will need to include that in the migration.

**Comment by MikeMcQuaid** [comment]
> Yeah they all have tokens that start with `font-*`. But they aren't currently sharded further, so will need to include that in the migration.

Yup. This should probably be handed a bit like `lib` in homebrew-core:
- there should be both `f` and `font` (or `font-`) subdirectories
unlike homebrew-core:
- the `font`/`font-` subdirectory should probably also be sharded 

This will likely require work in Homebrew/brew; I don't think there's currently supported for another level of directories.

Another option would be to shard by `f`, `font-a`, `font-b`, etc. in the `Casks` root. This would (except for `brew create`) require no/fewer Homebrew/brew changes.

**Comment by vitorgalvao** [comment]
Don’t forget there is (was?) a bot which kept the Google Fonts up to date automatically. However small the change to the structure, that will need an update to the new locations.

**Comment by MikeMcQuaid** [comment]
> Don’t forget there is (was?) a bot which kept the Google Fonts up to date automatically. However small the change to the structure, that will need an update to the new locations.

How does this differ from other autobump/livecheck workflows? Ideally it should be part of the same thing.

**Comment by vitorgalvao** [comment]
Yes, I don’t mean it in the sense that it will be a problem, I mean it in the sense “whoever works on the transition, don’t forget this important part which may not be immediately obvious”.

**Comment by bevanjkay** [comment]
There's currently two automations that are managing casks in the `homebrew-cask-fonts` repository. One is inside of the repo, and one is external that updates the "nerd fonts" supplied from the `ryanoasis` repository. It's worth noting that the "nerd fonts" specifically are relatively popular with three in the top-100 casks (last 30d install).

The Google Fonts automation is currently setup as a python script that on a schedule checks the https://github.com/google/fonts repository and adds/removes fonts, as well as updates any that have had changes.

Both of these do a little bit more than our current tooling for autobump/livecheck, because they also check and update if there have been changes that need to be reflected as `font` artifacts. I don't think this is something that could be rolled out wider, because many `font-*` casks require user-intervention to select the most "correct" artifacts within the archives.
