### ISSUE TITLE
Allow (limited?) installation without requiring `sudo`

### ISSUE THREAD

**Issue by aaelony-catasys** [Homebrew/homebrew-cask#112131]
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

Would it be possible to allow `brew install --cask julia ` to successfully complete without requiring `sudo`?

I work at a company that only allows the `administrator` to have sudo, even on my corporate MacBook Pro.

Thanks

### Command that failed

brew install --cask julia 

### Output of command with `--verbose --debug`

\<username\> is not in the sudoers file.  This incident will be reported.
==> Purging files for version 1.6.3 of Cask julia
Error: Failure while executing; `/usr/bin/sudo -E -- /bin/mkdir -p /Applications` exited with 1. Here's the output:
\<username\> is not in the sudoers file.  This incident will be reported.

### Output of `brew doctor --verbose`

<details><summary>Click to expand</summary><pre><code>

not relevant

</code></pre></details>

### Output of `brew tap`

<details><summary>Click to expand</summary><pre><code>

brew tap                         
borkdude/brew
homebrew/cask
homebrew/core
homebrew/services
mongodb/brew

</code></pre></details>

**Comment by SMillerDev** [comment]
That's an OS restriction unfortunately. We're just running the installer upstream provides, which requires root access.

For Julia you could check out the formula though, maybe it'll work.

**Comment by aaelony-catasys** [comment]
Got it. Seems like this kind of thing might be a good idea in general though; i.e. some non-sudo requiring alternative.

**Comment by carlocab** [comment]
Try passing `--appdir=~/Applications` to install into your `HOME` directory.

This won't work for all casks, since some run an upstream-provided installer which will require `sudo`.

In case that doesn't work, try installing the `julia` formula. This also doesn't help with other casks, but it might at least help you get going with what you were trying to install right now.

**Comment by aaelony-catasys** [comment]
Wow!  Thank-you for that magic!

(base) Tue 5 ~ %  brew install --cask julia --appdir=~/Applications 
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 2 formulae.
==> Updated Casks
Updated 5 casks.

```
==> Downloading https://julialang-s3.julialang.org/bin/mac/x64/1.6/julia-1.6.3-mac64.dmg
Already downloaded: /Users/username/Library/Caches/Homebrew/downloads/831fb2967c13b01b821bc2f5d940406f5d5d8d0aa463b3de518a22b546567991--julia-1.6.3-mac64.dmg
==> Installing Cask julia
==> Moving App 'Julia-1.6.app' to '/Users/username/Applications/Julia-1.6.app'
==> Linking Binary 'julia' to '/usr/local/bin/julia'
🍺  julia was successfully installed!
```

**Comment by carlocab** [comment]
You might then be interested in setting `HOMEBREW_CASK_OPTS`. See `man brew` for details.

**Comment by aaelony-catasys** [comment]
Great that homebrew is so flexible.  Awesome, thank-you!
