### ISSUE TITLE
TeXstudio 4.0.1 drops macOS 10.15 support, need to filter

### ISSUE THREAD

**Issue by loikein** [Homebrew/homebrew-cask#112771]
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

System: 10.15.7 (19H1417)
Can confirm 4.0.0 works perfectly fine, release: https://github.com/texstudio-org/texstudio/releases/tag/4.0.0

Cask of concern: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/texstudio.rb
Similar issue on TeXstudio's repo: https://github.com/texstudio-org/texstudio/issues/1826
TeXstudio official website states "There is no release for macOS 10.x": https://www.texstudio.org/#appimage

Technically I can do a PR, but I'm too busy trying to write a .tex file (aha) at this exact moment so just throwing it out.

### Command that failed

brew install TeXstudio (the command itself runs fine, only the app doesn't open)

### Output of command with `--verbose --debug`

(the command itself runs fine)

### Output of `brew doctor --verbose`

(the command itself runs fine)

### Output of `brew tap`

(the command itself runs fine)

**Comment by neutric** [comment]
10.15 will be supported again with the next release, not sure when it will be released though.
