### ISSUE TITLE
Be able to install different versions of Temurin

### ISSUE THREAD

**Issue by bliu13** [Homebrew/homebrew-cask#113604]
### Provide a detailed description of the proposed feature

Provide any way for us to have the ability to install different versions of Temurin. Could be either through using @ or maybe just a completely separate package.

### What is the motivation for the feature?

I think it would be good to have the ability to install different versions of Temurin. Certain projects have a hard dependency for a specific version of JDK and we may not always be able to update it to the latest version.

### Example use case

brew install --cask temurin11

or 

brew install --cask temurin@11

**Comment by bliu13** [comment]
Ah! That was my problem. I was not aware that we needed to the tap command first. I was looking for documentation all over the place, but I was not able to find this. Thank you so much!

**Comment by natami** [comment]
Does not appear to work with temurin15,16 and 17 ?

**Comment by neutric** [comment]
> Does not appear to work with temurin15,16 and 17 ?

That's to be expected, given that there are no [cask definitions](https://github.com/Homebrew/homebrew-cask-versions/tree/master/Casks) for these in `cask-versions` tap. Default `temurin` is currently version 17, though.

**Comment by natami** [comment]
Will there be a 17 available, when 18 is released?

**Comment by SMillerDev** [comment]
Probably, since that will be an LTS version.
