### ISSUE TITLE
Disable Media Keys for MS Teams via Arguments

### ISSUE THREAD

**Issue by jazzschmidt** [Homebrew/homebrew-cask#114094]
### Provide a detailed description of the proposed feature

MS Teams hijacks the Mac media keys and while listening to music the play/pause button mostly does not pause the music but rather plays the ringing tone in Teams. There are several issues reported for this in Microsofts issue portal, but you know....

I was able to stop Teams from using the media keys by adding the `--disable-features=HardwareMediaKeyHandling` argument to the application, as described in a comment at [Teams and Media Keys (answers.microsoft.com)](https://answers.microsoft.com/en-us/msteams/forum/all/teams-and-media-keys/136320bb-7af0-4bdc-8743-56608ff576b2?page=2) and [Add hardware-media-key-handling disabling option (Github: Electron)](https://github.com/electron/electron/issues/21731).

To automatically use that argument, I wrapped the actual execution call in a bash script and replaced the executable file in Teams `Info.plist` with that script as described in [How do I pass command line arguments to Dock items? (Superuser/SO)](https://superuser.com/questions/271678/how-do-i-pass-command-line-arguments-to-dock-items).

### What is the motivation for the feature?

This issue especially affects Mac users, since the majority of us is actually used to the special keys instead of the function keys and MS is very unlikely to fix this issue. Who needs to pause the ringtone when being called - or play it after finishing a call?

### Example use case

Being less frustrated when using Teams all day.

**Comment by jazzschmidt** [comment]
Is it actually possible to include that modifications in the brew formula?

**Comment by SMillerDev** [comment]
It is not because we just run the Microsoft installer.
