### ISSUE TITLE
Move session-manager-plugin from cask to non-cask

### ISSUE THREAD

**Issue by nitrocode** [Homebrew/homebrew-cask#114319]
### Provide a detailed description of the proposed feature

If a cask is for graphical user interfaces, then why is this formula in this repo instead of in homebrew-core ?

#### References
* Current cask https://github.com/Homebrew/homebrew-cask/blob/master/Casks/session-manager-plugin.rb
* Original PR in homebrew-cask https://github.com/Homebrew/homebrew-cask/pull/72347
* Original PR in homebrew-core before moving to cask due to the closed source code https://github.com/Homebrew/homebrew-core/pull/46522#issuecomment-552981492
* Now open source https://github.com/aws/session-manager-plugin

### What is the motivation for the feature?

If it's moved to homebrew core instead of casks then homebrew on linux will be able to install the formula.

### Example use case

on linux
```
brew install session-manager-plugin
```

**Comment by carlocab** [comment]
This isn't really a feature request. Please open a pull request in homebrew-core if you'd like to see this as a formula instead.

This guide might help: https://docs.brew.sh/Adding-Software-to-Homebrew
