### ISSUE TITLE
Add media-center universal build

### ISSUE THREAD

**Issue by nrlquaker** [Homebrew/homebrew-cask#114454]
### Provide a detailed description of the proposed feature

There is a [build](https://yabb.jriver.com/interact/index.php/topic,131173.0.html) with M1 support for [media-center](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/media-center.rb).

Not sure how to add it as it has different version. Can someone update the cask or provide the example so I can update it myself?

### What is the motivation for the feature?

To use native build on M1.

### Example use case

To use native build on M1.

**Comment by SMillerDev** [comment]
If it's a universal app it can just replace the Intel version. If it is arm only you can do something like https://github.com/Homebrew/homebrew-cask/pull/110695/files

**Comment by nrlquaker** [comment]
@SMillerDev yes, its universal binary. Created PR. Thanks for the info.
