### ISSUE TITLE
Stanza to declare native Apple Silicon support, universal builds, etc

### ISSUE THREAD

**Issue by lwouis** [Homebrew/homebrew-cask#114669]
### Provide a detailed description of the proposed feature

Hi!

I'm the author of the `alt-tab` cask, and I recently moved from an Intel-only to a universal build, and was trying to find a way to flag the cask as such, but it seems that today there is no way to flag a cask as having a universal build containing both x64 and arm architectures. It seems that it could be a useful addition to homebrew, so people on Apple Silicon hardware can know if they will download an Intel app, an ARM app, or a universal app.

Do you have plans for that? It seems there is something of that nature in homebrew-core, but not for flasks maybe. Let me know what you think of the idea 👍

### What is the motivation for the feature?

Helping users know what they download. Maybe have different release channels for different architectures. Probably other features I'm not thinking of right now.

### Example use case

I recently moved from an Intel-only to a universal build, and was trying to find a way to flag the cask as such. This way my users on M1 macs know it's native vs virtualized. They know from which version it started being universal, etc.

**Comment by SMillerDev** [comment]
I think you're overestimating how many people care about this. If we have a universal binary, it works for ARM users. If we have an x86 binary it also works for ARM users. I don't think we really need to relay metadata like this because it'll work just fine either way.
