### ISSUE TITLE
Cask request for getstation

### ISSUE THREAD

**Issue by YentlFrickx** [Homebrew/homebrew-cask#114958]
### Provide a detailed description of the proposed feature

I see that in the past there was a cask for getstation (the messaging app), but since it has been removed, no idea why: https://github.com/Homebrew/homebrew-cask/blob/98ec959621bfca7af6ff3d53c5ff2af6e0bfcbbd/Casks/station.rb 

### What is the motivation for the feature?

There is no nice way to install station at the moment (would like to automate it)

### Example use case

As mentioned before, my use-case would be automated install (and easy install)

**Comment by neutric** [comment]
Removal was in https://github.com/Homebrew/homebrew-cask/pull/89215/ and reasons were stated. Issues requesting new casks (or reinstating old ones) will be closed, though, as noted [here](https://github.com/Homebrew/homebrew-cask#requests). Instead, [open a PR](https://github.com/Homebrew/homebrew-cask/blob/HEAD/CONTRIBUTING.md#adding-a-cask), please.
