### ISSUE TITLE
julia on 

### ISSUE THREAD

**Issue by dodoplus** [Homebrew/homebrew-cask#115193]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

On ARM64 MacOS, brew switched to the ARM64 version of Julia 1.7.
Unfortunately, this is still not supported (Tier 3).

### Command that failed

command hasn't failed

### Output of command with `--verbose --debug`

```shell
irrelevant
```

### Output of `brew doctor --verbose`

```shell
irrelevant
```

### Output of `brew tap`

```shell
irrelevant
```

**Comment by bevanjkay** [comment]
@dodoplus Thank you for the report - I can see as per the `1.7` post, that the ARM build is still experimental, despite being available on the downloads page. We will get this reverted.

**Comment by carlocab** [comment]
We usually try to install native versions of software -- even when this is experimental -- on ARM. This is at least partly because we have no guarantee that a user even has Rosetta installed on ARM. So I'm personally against reverting the change.

If a user wants the Intel version, they can use a `/usr/local` installation of Homebrew. (Or download the `.dmg` themselves/use their own tap, etc.)

**Comment by dodoplus** [comment]
> 
x86 binary was installed for Julia 1.6.4, so this seems like a breaking change.
ARM64 Julia is (unfortunately) still unusable. 
See
https://github.com/JuliaLang/julia/issues/36617

**Comment by carlocab** [comment]
> ARM64 Julia is (unfortunately) still unusable.

This sounds like an exaggeration, given

> The [Julia User & Developer Survey 2021](https://julialang.org/blog/2021/08/julia-user-developer-survey/) showed that 5% of Julia users were already running Julia on this platform before an official stable version for it was released!

I don't mind adding `caveats` to the Julia cask for ARM that point out is an experimental ARM version. We've done the same for formulae.
