### ISSUE TITLE
Update freac from 1.1.5 to 1.1.5a

### ISSUE THREAD

**Issue by jimmodo** [Homebrew/homebrew-cask#115811]
### Provide a detailed description of the proposed feature

The current posted version is 1.1.5, however, there is a known bug in freac on the latest Mac OS preventing it from functioning in 1.1.5 making the 1.1.5a hotfix release essential. Ideally, this could be auto-updated from the Latest release link and generated based on the version # substring for Mac OS since this software's individual version for each platform does not always exactly match the version indicated under   https://github.com/enzo1982/freac/releases/latest (in this case there was a platform-specific hotfix)

### What is the motivation for the feature?

The product fails to run in Mac OS 12.x

### Example use case

"brew upgrade freac" -> 1.1.5a is installed over the current version

**Comment by neutric** [comment]
[Context](https://github.com/enzo1982/freac/issues/248) for the hotfix release.
