### ISSUE TITLE
Github Desktop Verified URL - How was it determined?

### ISSUE THREAD

**Issue by seandenigris** [Homebrew/homebrew-cask#115904]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

Looking back the cask's history, it seems the URL was changed between 890ae85 and a93a721, but I don't see where or why that actually happened by looking at those commits. [The latter has the comment](https://github.com/Homebrew/homebrew-cask/blob/a93a7215a60e9162dc6ee37b5e9389438eaf102e/Casks/github.rb), `# githubusercontent.com was verified as official when first introduced to the cask`, but is that verification process described anywhere? AFAICT, `githubusercontent.com` URLs could be just about anything. I assume the `desktop` subdomain in `https://desktop.githubusercontent.com` is what makes this safe, but I'm not clear whether that's justified. 

Thanks

### Command that failed

n/a

### Output of command with `--verbose --debug`

```shell
n/a
```

### Output of `brew doctor --verbose`

```shell
n/a
```

### Output of `brew tap`

```shell
n/a
```

**Comment by neutric** [comment]
Did you see the [relevant section](https://docs.brew.sh/Cask-Cookbook#when-url-and-homepage-domains-differ-add-verified) in the Cask Cookbook?

**Comment by bevanjkay** [comment]
@seandenigris Regarding the verification process. A maintainer will check that the URL is owned / controlled and authorized by upstream before merging the changes.

**Comment by seandenigris** [comment]
> Did you see the [relevant section](https://docs.brew.sh/Cask-Cookbook#when-url-and-homepage-domains-differ-add-verified) in the Cask Cookbook?

Yes, I did. I guess I'm asking, not "what does verified mean?" but "where/when is the verification process memorialized so it can be audited by the community?"

> Assuming that the official homepage of the app https://desktop.github.com/ is not under control if a malicious actor, the current link associated with the Download button is https://central.github.com/deployments/desktop/desktop/latest/darwin, which, according to `curl -sLI` forwards to https://desktop.githubusercontent.com/github-desktop/releases/2.9.6-9196a1ae/GitHubDesktop-x64.zip.

Ah, thank you. I dl-ed from both and verified the shas matched, but I just couldn't figure out how the team "knew" the sources were the same. Was the above memorialized somewhere e.g. a commit message, merge comment, etc? Would that be a good general policy?

**Comment by neutric** [comment]
> Yes, I did. I guess I'm asking, not "what does verified mean?" but "where/when is the verification process memorialized so it can be audited by the community?"

The Cask Cookbook (as linked to in the previous comment) says
> _It is our responsibility as Homebrew Cask maintainers to verify both the url and homepage information when first added (or subsequently modified, apart from versioning)._

The fact that a change to `verified` got merged is the memorialization.

Hope I didn't misunderstand. Feel free to rephrase.

**Comment by seandenigris** [comment]
> The fact that a change to `verified` got merged is the memorialization.

I don't want to beat a dead horse, but since it's security related thanks for working through this with me, @neutric and @bevanjkay. 

It seems that the *fact* of the verification is memorialized by the merge, but I guess what I was hoping for was that the *process* of the verification would be included at that point. Something like what you wrote before:
> Assuming that the official homepage of the app https://desktop.github.com/ is not under control if a malicious actor, the current link associated with the Download button is https://central.github.com/deployments/desktop/desktop/latest/darwin, which, according to curl -sLI forwards to https://desktop.githubusercontent.com/github-desktop/releases/2.9.6-9196a1ae/GitHubDesktop-x64.zip.

Putting that in a comment or the merge commit or wherever would provide auditing and confidence because a naive user like myself could replicate the verification. As it is, unless I'm missing something, one just has to blindly trust the person who did the merge, which, while perhaps safe in this case, is not a justifiable security policy IMHO.

**Comment by SMillerDev** [comment]
https://docs.brew.sh/Cask-Cookbook#when-url-and-homepage-domains-differ-add-verified

> The parameter doesn’t mean you should trust the source blindly [...]

It's not a security policy as much as it is a simple check that something isn't outright malicious.

**Comment by seandenigris** [comment]
@SMillerDev I hear you, and that's just it: aren't users more likely to resort to blind trust when the verification process is not at hand to replicate?

**Comment by SMillerDev** [comment]
A lot of users already fail to follow the big report template. I doubt a lot would follow verification steps so I simply don't think it's worth the effort.

**Comment by seandenigris** [comment]
Okay thanks for the dialogue
