### ISSUE TITLE
Cask avg-anitivirus version inconsistency leads to persistent outdated state

### ISSUE THREAD

**Issue by jwhite007** [Homebrew/homebrew-cask#116058]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

```brew outdated``` always reports installed version of the cask avg-antivirus as "latest" which is never consistent with the version stated in the formula itself and what gets reported with ``brew info avg-antivirus``` leading to the cask for avg-antivirus to consistently be understood by brew to be in an outdated state. I thought that pinning the cask would be a short-term fix; however, pinning does not appear possible for casks.  In addition, it would be nice to have a way of reporting an issue on a particular cask or formula as this isn't an issue with any particular brew command.

### Command that failed

NA

### Output of command with `--verbose --debug`

```shell
outdated --verbose --debug and ```brew info avg-antivirus --verbose --debug``` outputs are irrelevant as the commands are working just fine.

```
$ brew outdated
avg-antivirus (latest) != 4.0,2.0
```
```
$ brew info avg-antivirus
avg-antivirus: 4.0,2.0
https://www.avg.com/us-en/avg-antivirus-for-mac
/usr/local/Caskroom/avg-antivirus/latest (2 files, 21.9MB)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/avg-antivirus.rb
==> Name
AVG Antivirus for Mac
==> Description
Antivirus software
==> Artifacts
AVG AntiVirus.pkg (Pkg)
==> Analytics
install: 68 (30 days), 161 (90 days), 466 (365 days)
```
```

### Output of `brew doctor --verbose`

```shell
NA
```

### Output of `brew tap`

```shell
$ brew tap
homebrew/bundle
homebrew/cask
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
teamookla/speedtest
```

**Comment by bevanjkay** [comment]
This is because in the past the cask was versioned as `latest`. Try running `brew upgrade avg-antivirus` and it should update.

**Comment by jwhite007** [comment]
@bevanjkay,

I actually had to uninstall and then install again before i got the version to be "4.0,2.0" instead of "latest."

**Comment by bevanjkay** [comment]
@jwhite007 Had you run `brew upgrade avg-antivirus` or `brew upgrade`? As the cask would not be automatically upgraded by running `brew outdated` (this only reports which casks have an outdated local version compared to the current version reported by Brew). Calling `brew info` reports the information that is current in the tap repository (in this case `homebrew-cask`), not the locally installed version.

**Comment by jwhite007** [comment]
@bevanjkay, I understand. Running ```brew upgrade avg-antivirus``` or ```brew upgrade``` was constantly upgrading avg-antivirus as brew always saw the installed as "latest" and not "4.0,20." or whatever. This is the problem I was having. It was ostensibly upgrading, but the version was always "latest." I had to actually uninstall and then reinstall to get brew to see the installed version as "4.0,2.0."

**Comment by jwhite007** [comment]
@bevanjkay, I do appreciate your attention to the matter, however. Thank you. Have a great holiday season.
