### ISSUE TITLE
metasploit 404

### ISSUE THREAD

**Issue by hamon-e** [Homebrew/homebrew-cask#116499]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

```
$> brew update                                                                                             
Already up-to-date.
```
```
$> brew install --cask metasploit                                                                          
==> Downloading https://osx.metasploit.com/metasploit-framework-6.1.20%2B20211213112930-1rapid7-1.x86_64.pkg
##O#- #
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'metasploit' with message: Download failed: https://osx.metasploit.com/metasploit-framework-6.1.20%2B20211213112930-1rapid7-1.x86_64.pkg
```
```
$> brew info metasploit                                                                                     
metasploit: 6.1.20,20211213112930
https://www.metasploit.com/
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/metasploit.rb
==> Name
Metasploit Framework
==> Description
Penetration testing framework
==> Artifacts
metasploit-framework-6.1.20+20211213112930-1rapid7-1.x86_64.pkg (Pkg)
/opt/metasploit-framework/bin/msfconsole (Binary)
/opt/metasploit-framework/bin/msfd (Binary)
/opt/metasploit-framework/bin/msfdb (Binary)
/opt/metasploit-framework/bin/msfelfscan (Binary)
/opt/metasploit-framework/bin/msfmachscan (Binary)
/opt/metasploit-framework/bin/msfrop (Binary)
/opt/metasploit-framework/bin/msfrpc (Binary)
/opt/metasploit-framework/bin/msfrpcd (Binary)
/opt/metasploit-framework/bin/msfvenom (Binary)
/opt/metasploit-framework/bin/msfpescan (Binary)
/opt/metasploit-framework/bin/msfbinscan (Binary)
==> Analytics
install: 403 (30 days), 1,507 (90 days), 5,505 (365 days)
```
cant install metasploit
seems to be broken each update

https://github.com/Homebrew/homebrew-cask/issues/109333
https://github.com/Homebrew/homebrew-cask/issues/100911
https://github.com/Homebrew/homebrew-cask/issues/100236

### Command that failed

brew install --cask metasploit 

### Output of command with `--verbose --debug`

```shell
see ^
```

### Output of `brew doctor --verbose`

```shell
see ^
```

### Output of `brew tap`

```shell
see ^
```

**Comment by neutric** [comment]
Help yourself (and us) in the future by submitting a fix:

```
%  brew livecheck metasploit
metasploit : 6.1.20,20211213112930 ==> 6.1.22,20211226112904
```
and then follow the instructions in [CONTRIBUTING.md](https://github.com/Homebrew/homebrew-cask/blob/HEAD/CONTRIBUTING.md#updating-a-cask) to update it. After initial setup, all that is needed then is
```
%  brew bump-cask-pr --version 6.1.22,20211226112904 metasploit
```

This creates a local branch `bump-metasploit-6.1.22` that you can check out and install from without waiting for the PR to be merged.
