### ISSUE TITLE
Fusion 360 is installed in the "Wrong Folder".

### ISSUE THREAD

**Issue by mattpackwood** [Homebrew/homebrew-cask#116597]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

I am not sure if this is the correct place for this but, when you install Fusion360 the app "end up" in `~/Applications` not `/Applications`

### Command that failed

brew install --cask autodesk-fusion360

### Output of command with `--verbose --debug`

```shell
No errors
```

### Output of `brew doctor --verbose`

```shell
No errors
```

### Output of `brew tap`

```shell
No errors
```

**Comment by neutric** [comment]
Why do you think `~/Applications` is the wrong folder? You can use this folder for Apps that should only be visible to the current user. Admittedly, it is rarely used, but that is what the Fusion 360 installer opted for. Or does it install in `/Applications` when you run the installer manually?

**Comment by mattpackwood** [comment]
Ah, so that is a Fusion 360 path...  Interesting!

The only other software I see in there is are Chrome apps (Chat and Keep), "everything else" ends up in /Applications (including all the software I install with Homebrew).

So: Question - is this better addressed to AutoDesk?

**Comment by neutric** [comment]
> So: Question - is this better addressed to AutoDesk?

Yes. Not sure to what end, though. Is the software not starting as expected?

**Comment by mattpackwood** [comment]
More the irritation factor of having to remember to open a completely different folder than the one that “all my other software” is installed into.

**Comment by neutric** [comment]
There are smoother ways to start an App than going to the Application folder. Tools like Alfred (available as cask) or the built-in Spotlight (press Command+Space on your keyboard, then type app name) come to mind.

**Comment by bevanjkay** [comment]
@mattpackwood If you create an Alias for the app in the other folder then it wouldn't matter which you open.
