### ISSUE TITLE
Re-open handbrake-cli PR

### ISSUE THREAD

**Issue by Simon-Tang** [Homebrew/homebrew-cask#116726]
### Provide a detailed description of the proposed feature

The pull request https://github.com/Homebrew/homebrew-cask/pull/109484 adds a separate `handbrake-cli` cask, since the current `handbrake` cask doesn't install HandbrakeCLI automatically. We should re-open and merge the PR.

### What is the motivation for the feature?

This [StackOverflow thread](https://apple.stackexchange.com/questions/85731/how-do-i-install-handbrake-cli#comment461916_188200) has some more detail - it appears that the CLI was extracted to a separate DMG file on the Handbrake website at some point in time. In my own testing, the HandbrakeCLI needed to be downloaded from https://handbrake.fr/downloads2.php instead.

### Example use case

```
brew install handbrake-cli
HandbrakeCLI -h
```

**Comment by reitermarkus** [comment]
As was asked in https://github.com/Homebrew/homebrew-cask/pull/109484#issuecomment-893219881, isn't this the same as the formula? You can already install that with `brew install handbrake`.

**Comment by Simon-Tang** [comment]
@reitermarkus negative, the HandbrakeCLI is nowhere to be found after `brew install handbrake` alone. This could have been the case in the past but as of 2021 this is not automatically included.

**Comment by reitermarkus** [comment]
Seems like there is an implicit conflict with the cask, so it isn't linked by default.

```
==> handbrake cask is installed, skipping link.
```

You can link it manually with `brew link handbrake`.

**Comment by Simon-Tang** [comment]
Interesting. I have to admit I'm not familiar with `brew install` vs `brew install --cask` yet, but I think you have the solution there.

```
brew install --cask handbrake
# HandbrakeCLI not available yet
brew link handbrake
# Didn't work
brew install handbrake
brew link handbrake
# Worked
HandbrakeCLI -h
```

I'd need to learn more about how `brew` works to submit some kind of fix or add something to the handbrake docs on brew.sh. Do you have any thoughts on we could prevent other users from running into the same issue?
