### ISSUE TITLE
Why do i have to update HomeBrew twice everytime out of which it produces error the first time.

### ISSUE THREAD

**Issue by VivekHalakatti** [Homebrew/homebrew-cask#116995]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

Why do I have to update homebrew twice every time out of  which it produces error the first time.
These are the two commands i use:-
When i use 'brew upgrade' it gives me this error.
<img width="580" alt="Screenshot 2022-01-05 at 11 26 31 PM" src="https://user-images.githubusercontent.com/65499521/148265578-45854b19-eb4c-4baf-a15f-13bce9c56d65.png">
 

When i use '/opt/homebrew/bin/brew upgrade'.
<img width="579" alt="Screenshot 2022-01-05 at 11 24 53 PM" src="https://user-images.githubusercontent.com/65499521/148265374-2507de86-7cc2-461e-b345-9dd3c158eab2.png">
e

### Command that failed

'brew upgrade' or '-x86_64 brew upgrade'

### Output of command with `--verbose --debug`

```shell
not runnning
```

### Output of `brew doctor --verbose`

```shell
Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  php
  python@3.9

Warning: Your Homebrew's prefix is not /opt/homebrew.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/opt/homebrew).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
unsupported configuration.


Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /usr/local/opt/php
  /usr/local/opt/php@8.0
```

### Output of `brew tap`

```shell
homebrew/bundle
homebrew/cask
homebrew/core
```

**Comment by SMillerDev** [comment]
You're running a Rosetta install of homebrew `/usr/local` from a non-rosetta shell. This breaks all assumptions homebrew has, only run `/usr/local/bin/brew` in Rosetta and `/opt/homebrew/bin/brew` in a native shell.

**Comment by VivekHalakatti** [comment]
> You're running a Rosetta install of homebrew `/usr/local` from a non-rosetta shell. This breaks all assumptions homebrew has, only run `/usr/local/bin/brew` in Rosetta and `/opt/homebrew/bin/brew` in a native shell.

How do i get rid of rosetta version?
