### ISSUE TITLE
Kill pesky background adobe-acrobat-pro processes like login 

### ISSUE THREAD

**Issue by alemens** [Homebrew/homebrew-cask#117134]
### Provide a detailed description of the proposed feature
Kill sign in 
![Screenshot 2022-01-09 at 07 16 49](https://user-images.githubusercontent.com/20490756/148671499-726f54c7-b190-44ce-9c55-3b7e58bf0407.jpg)

### What is the motivation for the feature?
Can’t use adobe-acrobat-pro without log in

### Example use case
Open and use adobe-acrobat-pro without login 

### Info  
```
$ brew info adobe-acrobat-pro 
adobe-acrobat-pro: 21.007.20099 (auto_updates)
https://acrobat.adobe.com/us/en/acrobat/pdf-reader.html
/usr/local/Caskroom/adobe-acrobat-pro/21.007.20099 (5 files, 984.0MB)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/adobe-acrobat-pro.rb
==> Name
Adobe Acrobat Pro DC
==> Description
View, create, manipulate, print and manage files in Portable Document Format
==> Artifacts
Acrobat DC/Acrobat DC Installer.pkg (Pkg)
==> Analytics
install: 125 (30 days), 446 (90 days), 1,573 (365 days)
```

**Comment by bevanjkay** [comment]
Adobe Acrobat Pro requires a subscription to Adobe, hence why the login form in displayed.
