### ISSUE TITLE
brew install --cask temurin Is not working in Ubuntu 20.04

### ISSUE THREAD

**Issue by rifatSDAS** [Homebrew/homebrew-cask#117147]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

brew install --cask temurin  command does not working in Ubuntu 20.04 in VirtualBox 6.1

Is there any possible way to install temurin in linuxbrew?

Some information:
Host OS: Debian-based Linux distributions Ubuntu version 20.04.1 64 bit
Guest OS: Virtual Debian-based Linux distributions Ubuntu version 20.04.3 64 bit
VirtualBox: 6.1.30

### Command that failed

brew install --cask temurin 

### Output of command with `--verbose --debug`

```shell
Error: Cask 'temurin' is unavailable: No Cask with this name exists.
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cask/cask_loader.rb:196:in `load'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cask/cask_loader.rb:205:in `load'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:142:in `load_formula_or_cask'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:59:in `block in to_formulae_and_casks'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:58:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:58:in `flat_map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:58:in `to_formulae_and_casks'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:167:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

### Output of `brew doctor --verbose`

```shell
Your system is ready to brew.
```

### Output of `brew tap`

```shell
homebrew/cask-versions
homebrew/core
```

**Comment by SMillerDev** [comment]
Casks do not work on Linux, I'm not sure how you even got it to try.
