### ISSUE TITLE
visual-paradigm false sha256

### ISSUE THREAD

**Issue by b3z** [Homebrew/homebrew-cask#117198]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

Somehow there is a wrong sha256.

```sh
brew install --cask visual-paradigm
==> Downloading https://www.visual-paradigm.com/downloads/vp16.3/20211201/Visual_Paradigm_16_3_20211
Already downloaded: /Users/luca/Library/Caches/Homebrew/downloads/dc1ddae08b05002cfd72da279ee3c34887bcdc7b3f4473dfad0b677aa0fc858e--Visual_Paradigm_16_3_20211237_OSX_WithJRE.dmg
Error: SHA256 mismatch
Expected: 1da56af37f40973382406aa0324d7f13188463fec024c79b94360db24d0159cf
  Actual: 598f244b50b264bbca1bd8da4635c5b558adac1fa791d95052213693e04be955
    File: /Users/luca/Library/Caches/Homebrew/downloads/dc1ddae08b05002cfd72da279ee3c34887bcdc7b3f4473dfad0b677aa0fc858e--Visual_Paradigm_16_3_20211237_OSX_WithJRE.dmg
To retry an incomplete download, remove the file above.
``

### Command that failed

brew install --cask visual-paradigm

### Output of command with `--verbose --debug`

```shell
-
```

### Output of `brew doctor --verbose`

```shell
-
```

### Output of `brew tap`

```shell
b3z/small
bios-marcel/cordless
dominikbraun/timetrace
homebrew/cask
homebrew/cask-versions
homebrew/core
homebrew/services
mongodb/brew
mvp/uhubctl
nrlquaker/createzap
romkatv/powerlevel10k
sargsyan/github-notifier
```

**Comment by b3z** [comment]
I am stupid.

**Comment by neutric** [comment]
> I am stupid.

Why? The version as per cask is doing a redirect to the current version which leads to the checksum mismatch. Bump to the current version is waiting for a merge.
