### ISSUE TITLE
Request: Egnyte Desktop App

### ISSUE THREAD

**Issue by mjsteinbaugh** [Homebrew/homebrew-cask#117571]
### Provide a detailed description of the proposed feature

I'd like to add support for Egnyte Desktop App, but need some help with the recipe.

See related:
https://helpdesk.egnyte.com/hc/en-us/articles/205237150-Desktop-App-Installers

### What is the motivation for the feature?

This application is commonly used by companies instead of Dropbox.

### Example use case

Corporate file syncing replacement for Dropbox.

**Comment by carlocab** [comment]
Note that we don't take requests for new casks as issues. See: https://github.com/Homebrew/homebrew-cask#requests

> I'd like to add support for Egnyte Desktop App, but need some help with the recipe.

Where have you gotten stuck? Please open a pull request with what you'e done so far and we'll help you finish it off.

**Comment by mjsteinbaugh** [comment]
Hi @carlocab sute thing I'll see if I can put a draft pull request together. Thanks
