### ISSUE TITLE
I have 2 version of brew one for rosetta and one for Arm. How do i get rid of rosetta version of brew?

### ISSUE THREAD

**Issue by VivekHalakatti** [Homebrew/homebrew-cask#117694]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

Whenever i just try "brew upgrade" in my terminal it throws me with an error
 "Cannot install in Homebrew on ARM processor in Intel default prefix (/usr/local)!
Please create a new installation in /opt/homebrew using one of the
"Alternative Installs" from:
  https://docs.brew.sh/Installation
You can migrate your previously installed formula list with:
  brew bundle dump
". 

I have to use complete "opt/homebrew/bin/brew upgrade" to upgrade or install anything i want to.
So how how do i get rid of rosetta version of brew so that i can have one working command for all brew installs and upgrades?

### Command that failed

brew upgrade/install

### Output of command with `--verbose --debug`

```shell
-
```

### Output of `brew doctor --verbose`

```shell
Your Homebrew's prefix is not /opt/homebrew.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/opt/homebrew).
```

### Output of `brew tap`

```shell
homebrew/bundle
homebrew/cask
homebrew/core
```

**Comment by miccal** [comment]
Please read the discussion here: https://github.com/Homebrew/discussions/discussions/417
