### ISSUE TITLE
Teamviewer cask uninstall should act differently in macOS Catalina

### ISSUE THREAD

**Issue by sataset** [Homebrew/homebrew-cask#118316]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

Teamviewer cask uninstallation should be blocked if done through homebrew CLI on macOS Catalina (and maybe other versions?) due to the [bug](https://hexout.wordpress.com/2019/10/23/cant-boot-after-uninstalling-teamviewer-on-mac-os-catalina/) which is actually listed on [cask info page](https://formulae.brew.sh/cask/teamviewer):

> WARNING: teamviewer has a bug in Catalina where it doesn't deal well with being uninstalled by other utilities.The recommended way to remove it is by running their uninstaller under:
> 
> Preferences → Advanced

This bug is critical as it makes macOS not load.

I needed to go through the recovery process, install teamnviewer back again and uninstall everything through TeamViewer uninstaller to make sure everything is done correctly. This however does not remove homebrew installed package entry.

### Command that failed

brew uninstall teamviewer

### Output of command with `--verbose --debug`

```shell
null
```

### Output of `brew doctor --verbose`

```shell
null
```

### Output of `brew tap`

```shell
null
```

**Comment by miccal** [comment]
Please see https://github.com/Homebrew/homebrew-cask/issues/76829

Besides the `caveat` message, there is nothing more we can really do here except for removing the Cask entirely.

**Comment by carlocab** [comment]
This bug is pretty bad, though. Can we make `brew uninstall teamviewer` do nothing on Catalina, at least?

**Comment by miccal** [comment]
@carlocab no -- the `install` and `uninstall` are linked. The only way to fix this would be no not allow this Cask be be installed on Catalina in the first place.

**Comment by carlocab** [comment]
I think that's reasonable given the risks of bricking someone's system. It seems recoverable if you have some experience with macOS, but I'm not comfortable relying on that.

**Comment by miccal** [comment]
True, but changing it now would cause an issue for any user on Catalina who has this currently installed via Cask.

I think this is one of those cases where we are damned if we do and dammed if we don't.

It would be _really_ nice if user's actually _read_ our `caveats` :)

**Comment by carlocab** [comment]
The cask specifies a bunch of things to uninstall, though:

https://github.com/Homebrew/homebrew-cask/blob/2047f211999e9e70d9aa058a94eac796370e58d4/Casks/teamviewer.rb#L34-L63

What happens if we wrap that whole block in `unless MacOS.version == :catalina`?

**Comment by miccal** [comment]
I did not know we could do that in Cask -- worth a try, though.

**Comment by sataset** [comment]
There are other casks that basically work "one-way" only (e.g. [windscribe](https://formulae.brew.sh/cask/windscribe)).

Maybe these kind of casks should not be added or some general rule should be applied for all casks? Because it basically breaks the way homebrew / package managers work.

P.S.: I am not really familiar with Ruby but looking at `.rb` script it seems possible to just remove links or make it dummy? After dummy uninstall it is possible to catch user's attraction to caveat message during uninstallation process as it will not delete the installed application.

P.P.S: I am not usually missing caveats but in that case I noticed it is hard to see due to:
- Caveat log message placement (update, caveat, download, install). Usually I am seeing warning messages after installation so it is hard to miss them.
- Terminal window height: as caveat log message is not printed in the end it requires user to scroll almost all the way up to the caveat message.

**Comment by carlocab** [comment]
The caveats should be printed at the end. If that's not happening for casks, that's a bug.

**Comment by sataset** [comment]
That is exactly what happened during the process that I have listed in the issue description (`brew install teamviewer` back, uninstall through GUI).

<details>
  <summary>Spoiler with screenshot</summary>
  
  ![image](https://user-images.githubusercontent.com/28687456/151543399-95906f50-f37a-4e70-899d-20d95ca1134a.png)
  
</details>

**Comment by sataset** [comment]
> What happens if we wrap that whole block in `unless MacOS.version == :catalina`?

@carlocab, I think it is preferrable to use application's integrated uninstaller when possible? Correct me if I am wrong.

**Comment by carlocab** [comment]
> That is exactly what happened during the process that I have listed in the issue description (`brew install teamviewer` back, uninstall through GUI).

That's a bug. Please report this at [Homebrew/brew](https://github.com/Homebrew/brew).

> @carlocab, I think it is preferrable to use application's integrated uninstaller when possible? Correct me if I am wrong.

You're not wrong. Please see #76829 and #24377.

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/118326
