### ISSUE TITLE
Homebrew environment variable to override default github cask repo

### ISSUE THREAD

**Issue by shaunwarman** [Homebrew/homebrew-cask#118453]
### Provide a detailed description of the proposed feature

Similar to:
```sh
HOMEBREW_BREW_GIT_REMOTE
HOMEBREW_CORE_GIT_REMOTE
```

A way to override default cask git remote of: https://github.com/Homebrew/homebrew-cask

For example,
```
HOMEBREW_CASK_GIT_REMOTE=<some_internal_git_remote>
```

### What is the motivation for the feature?

Often in corporate settings there is a proxy or internal github mirror with the obstacle that public github is blocked due to internet connectivity restrictions / firewalls.

### Example use case

```
HOMEBREW_CASK_GIT_REMOTE=<some_internal_git_remote>
```

**Comment by SMillerDev** [comment]
The cask repo isn't tapped by default so you can just tap your own mirror.

**Comment by Rylan12** [comment]
There's very little logic in Homebrew that handles homebrew/cask differently from any other tap that contains casks, so Sean's suggestion should be plenty.

The only thing I'd add is that there's a chance Homebrew might try to auto-tap homebrew/cask every once in a while. The easiest way to disable this, unfortunately, is to have homebrew/cask tapped (`brew tap homebrew/cask` if it's not already done) and simply run `brew untap homebrew/cask`.

You can check that it won't be auto-tapped in the future by running `cat $(brew --repository)/.git/config` and checking for a line under the `[homebrew]` category that says something like `untapped = "homebrew/cask"`. If that doesn't show up, you can add it manually by running `git -C $(brew --repository) config homebrew.untapped homebrew/cask`.

**Comment by shaunwarman** [comment]
Thanks folks, this helps!
