### ISSUE TITLE
Open Office/Libre Office both not working, Guessing due to homebrew. #2892

### ISSUE THREAD

**Issue by zoiii111** [Homebrew/homebrew-cask#118548]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

Mac 2021 (Big Sur):

Cannot open neither Open Office nor Libre Office. Both get killed immediately. Tried de- and reinstallation, did not work.
I (IT-newbie) stupidly installed homebrew and guess, this is causing problems. Uninstalling homebrew does not work:
My Input:
~ % /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"

Getting this:
mkdir: /tmp/uninstall.69122: Permission denied
Unable to create temp dir '/tmp/uninstall.69122'

Tried installing open Office from here:
~ % brew install --cask openoffice

Got me this:
Error: Permission denied @ rb_sysopen - /private/tmp/github_api_headers20220131-69606-e7h269

Grateful for any help :)

Thank u in advance!!!

### Command that failed

Uninstalling homebrew

### Output of command with `--verbose --debug`

```shell
zsh: command not found: --verbose
```

### Output of `brew doctor --verbose`

```shell
Your system is ready to brew.
```

### Output of `brew tap`

```shell
homebrew/cask
homebrew/core
```

**Comment by neutric** [comment]
See also: https://github.com/Homebrew/discussions/discussions/2892

**Comment by carlocab** [comment]
This is specific to your machine. In particular, you have very peculiar permissions for `/tmp`. You can fix this by fixing your permissions to `/tmp` or to set `HOMEBREW_TEMP` to a directory you have write permissions to. Both these fixes are described in the discussion post linked above.
