### ISSUE TITLE
Duplicati's stable version are the beta releases

### ISSUE THREAD

**Issue by pdelre** [Homebrew/homebrew-cask#118671]
> Okay, given that the homepage links to the beta, we can revert to the beta and use the homepage for the `livecheck` instead of GitHub releases. Feel free to open a PR for that.

_Originally posted by @reitermarkus in https://github.com/Homebrew/homebrew-cask/issues/97381#issuecomment-795961310_

Given that Duplicati's stable version is the beta releases (below), the `livecheck` should use the project's [homepage download page](https://www.duplicati.com/download) to determine the stable release instead of using GitHub Releases/Tags which the project does not delineate stability between `beta`, `experimental`, or `canary` releases. This project specific version scheme has caused confusing and churn in the `liveness` check as various releases are added and dropped (#117546 #109314 #97381).

> **Beta**: This is the most stable build and is recommended for most users. This allows you to test the new features we're working on. Ensure you test restoring data with this version prior to using it in production environments.
> **Experimental**: Specific builds for developers only. Not for use with important data.
> **Canary**: Individual builds for developers only. Not for use with important data.

[Downloading Duplicati](https://duplicati.readthedocs.io/en/latest/02-installation/#downloading-duplicati)

**Comment by carlocab** [comment]
Please open a PR, and also see: https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md#if-your-issue-was-closed-without-review
