### ISSUE TITLE
Missing SHA256 SUM for chromium

### ISSUE THREAD

**Issue by maximiliankolb** [Homebrew/homebrew-cask#120075]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

With https://github.com/Homebrew/homebrew-cask/commit/dcd9f8ab0feb3a44523efc360975e62b73fbe62b, the checksum for chromium has been removed. cc @robertleeblairjr & @miccal 

From the commit message, I don't understand why. Is there something I can do to make that happen again?

Reading https://github.com/Homebrew/homebrew-cask/pull/119418#discussion_r810514167, I must say that I totally disagree.

Can I simply revert the commit and then update chromium to top of that, providing a valid checksum that I checked locally for both architectures? Would you accept such a PR?

### Command that failed

-

### Output of command with `--verbose --debug`

```shell
==> Casks with 'auto_updates true' or 'version :latest' will not be upgraded; pass `--greedy` to upgrade them.
==> Upgrading 2 outdated packages:
chromium 966981 -> latest
==> Upgrading chromium
==> Downloading https://download-chromium.appspot.com/dl/Mac?type=snapshots
==> Downloading from https://commondatastorage.googleapis.com/chromium-browser-snapshots/Mac/978008/chrome-mac.zip
######################################################################## 100.0%
Warning: No checksum defined for cask 'chromium', skipping verification.
==> Backing App 'Chromium.app' up to '/usr/local/Caskroom/chromium/966981/chrome-mac/Chromium.app'
==> Removing App '/Applications/Chromium.app'
==> Unlinking Binary '/usr/local/bin/chromium'
==> Moving App 'Chromium.app' to '/Applications/Chromium.app'
==> Linking Binary 'chromium.wrapper.sh' to '/usr/local/bin/chromium'
==> Purging files for version 966981 of Cask chromium
🍺  chromium was successfully upgraded!
```

### Output of `brew doctor --verbose`

```shell
-
```

### Output of `brew tap`

```shell
-
```

**Comment by SMillerDev** [comment]
> From the commit message, I don't understand why. Is there something I can do to make that happen again?

Because the download link is now no longer versioned.

> Reading https://github.com/Homebrew/homebrew-cask/pull/119418#discussion_r810514167, I must say that I totally disagree.

That's fine, but since you're not putting in the work to maintain it that means less to me than a frequent contributors opinion.

> Can I simply revert the commit and then update chromium to top of that, providing a valid checksum that I checked locally for both architectures? Would you accept such a PR?

Not likely, the current approach seems to be the most reasonable.

**Comment by neutric** [comment]
@maximiliankolb You can always consider hosting this in [your own Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) where you get to make all the decisions.

**Comment by trss** [comment]
@SMillerDev I remember requesting a "chromium-stable" that provides stable releases alone as per https://chromiumdash.appspot.com/schedule instead of multiple updates per day/week. This is because I just use Chromium instead of Chrome on my Mac.

The purpose of this cask appears to be for developers and testers of Chromium, or so I guess. But since this is the closest to my use-case, I end up using this. Would be glad to switch to a "chromium-stable" whether it's added here or someone creates and maintains a Tap or I end up doing it (which I don't intend to at the moment).

**Comment by trss** [comment]
@miccal When looking for my request for "chromium-stable" in my comment above, I chanced upon https://github.com/Homebrew/homebrew-cask/issues/118263#issuecomment-1024801921 but couldn't reply there so asking you here.

> There is no "stable" version of Chromium, the developers instead release several snapshot builds per day and we generally update the Cask every week or two.

Is https://chromiumdash.appspot.com/releases?platform=Mac different than Chromium?

**Comment by neutric** [comment]
@trss I see mentions of Chrome Browser and Chrome OS, but not Chromium.

**Comment by trss** [comment]
Ah, makes sense. Thanks.

**Comment by trss** [comment]
@neutric I just looked deeper into that website and here's my understanding.

[Schedule](https://chromiumdash.appspot.com/schedule) - Mentions Chrome Browser and Chrome OS, but not Chromium.

[Releases](https://chromiumdash.appspot.com/releases?platform=Mac) - No mention of a specific name, I assumed this to be Chromium.

[Branches](https://chromiumdash.appspot.com/branches) - Mentions Chromium and appears to provide all necessary details like branch position.

I understand that https://github.com/chromium/chromium/tags is the most direct source and hence the most reliable. However, given it doesn't provide sufficient info, can http://chromiumdash.appspot.com be considered for making a "chromium-stable" happen?

Quoting from the homepage:
> Chromium Dash ties together multiple data sources in order to present a consolidated view of what's going on in Chromium and Chrome, plus related projects like V8, WebRTC & Skia. Log in using your Chromium account for a personalized view.

**Comment by carlocab** [comment]
> [Releases](https://chromiumdash.appspot.com/releases?platform=Mac) - No mention of a specific name, I assumed this to be Chromium.

This is under "Chrome Data" on the right, so I think this is for Chrome, not Chromium.

> I understand that https://github.com/chromium/chromium/tags is the most direct source and hence the most reliable. However, given it doesn't provide sufficient info, can http://chromiumdash.appspot.com be considered for making a "chromium-stable" happen?

Does this page identify a stable version of Chromium? If it does, then that's a start, but we also need to be able to parse this page using `livecheck`.

**Comment by trss** [comment]
Didn't notice the "Chromium Data" and "Chrome Data" headings, thanks for pointing out.

About stable version of Chromium, again going by my understanding, the milestones with light blue background appear to be stable branches. If we can make sure not more than one branch can be active at a time, we can leave out the active branch and go for the previous one (99 and 95 at the time of this writing respectively).

About being able to parse I have no idea. I don't think I have much more to add. I'm glad there is hope. I'll let the experts take this on.

**Comment by trss** [comment]
Didn't notice the "Chromium Data" and "Chrome Data" headings, thanks for pointing out.

About stable version of Chromium, again going by my understanding, the milestones with light blue background in [Branches](https://chromiumdash.appspot.com/branches) appear to be stable releases. If branches not listed under "Active Branches" will never be committed to, we can leave them out and go for the one before them. For e.g., at the time of this writing, 99 is the only active branch and 95 is the one before that.

About being able to parse the page I have no idea. I don't think I have much more to add. I'm glad there is hope. I'll let the experts take this on.
