### ISSUE TITLE
tools/emulator is deprecated

### ISSUE THREAD

**Issue by nicodn** [Homebrew/homebrew-cask#120172]
I didn't get a chance to reply in the original PR, but the reason I was removing that link is here: https://issuetracker.google.com/issues/66886035?pli=1

There are two `emulator` binaries, and linking the one in `tools` first breaks things. The correct emulator is in `emulator/emulator`.

I'm sure there's more info online beyond that old google issue, but you can see replies from @google reps mentioning that `tools/` is slowly being deprecated

> Why are you removing this? From what I can see, this binary still exists:
> 
> <img width="173" alt="Screen Shot 2021-09-28 at 09 28 49" src="https://user-images.githubusercontent.com/6127163/135007373-61f3da95-73b6-4f24-9644-8f54a0ea2116.png">
> 
> _Originally posted by @miccal in https://github.com/Homebrew/homebrew-cask/pull/111792#discussion_r717155165_

**Comment by carlocab** [comment]
Issues aren't really the place for continuing discussions from closed PRs. When something doesn't fit the issue template, that's a strong sign that opening an issue isn't appropriate.

If you'd like to continue this discussion, please use [the discussions page](https://github.com/Homebrew/discussions/discussions) or open a new PR.
