### ISSUE TITLE
adding `zap` option to `brew reinstall`

### ISSUE THREAD

**Issue by spinofdoom** [Homebrew/homebrew-cask#120310]
### Provide a detailed description of the proposed feature

Since `brew reinstall` itself has an uninstallation component, I propose utilizing `brew uninstall`'s [fantastic](https://github.com/nrlquaker/homebrew-createzap) `zap` option with `brew reinstall`, such that:

`brew reinstall --zap <cask>` uninstalls `<cask>` according to `<cask>`'s `zap` stanza, then re-installs `<cask>`. 

(Since the `--zap` flag is doubtless familiar among those for whom this feature would be advantageous, its usage should be very intuitive.)

### What is the motivation for the feature?

It seems like a symmetrical & intuitive adoption of the `zap` option from `uninstall` to `reinstall`. It makes achieving a true "fresh re-installation" of any given Cask an ever-so-slightly simpler and quicker proposition. 

### Example use case

Let's say you realize you got your preferences so wrong in `flux` that you just want to nuke the prefs files, etc. and start over. Or maybe another Cask seems possibly bugged and you want to make sure to uninstall all vestiges of it before re-installing for testing purposes. 

Whatever the case, you may find yourself wanting a Cask re-installed with the power of `zap`, i.e., uninstalling the Cask, and deleting any generated application-associated files, so that after reinstallation the filesystem is left looking more or less like it would if the Cask was installed for the very first time. To do so, I suggest the following possibility:

`brew reinstall --zap <cask>`

The command is at the very least shorter and more elegant than the current option for solving that problem
(` brew uninstall --zap <cask> && brew install --cask <cask> `). Depending on the implementation, it could turn out to be faster and more efficient as well.

Perhaps it's worth pursuing.

**Comment by SMillerDev** [comment]
This should be made as a pull request in https://github.com/Homebrew/brew, it doesn't really make sense to discuss this in a repo that only hosts the packages.

**Comment by spinofdoom** [comment]
I was debating back and forth. thank you, @SMillerDev.
