### ISSUE TITLE
Add FileZilla back

### ISSUE THREAD

**Issue by jlecordier** [Homebrew/homebrew-cask#120475]
### Provide a detailed description of the proposed feature

I've read FileZilla was removed from Homebrew 4 years ago because of a malware. But it seems like it is not an issue anymore, as the downloaded file from the official website is an archive containing the `.app` file.

### What is the motivation for the feature?

It could be great to have FileZilla back on Homebrew

### Example use case

`brew install filezilla`

**Comment by neutric** [comment]
I don't think you need to bother after https://github.com/Homebrew/homebrew-cask/pull/55583.

**Comment by neutric** [comment]
For reference: https://github.com/Homebrew/homebrew-cask/pull/55583
