### ISSUE TITLE
Battle for Wesnoth cask is currently using develop version

### ISSUE THREAD

**Issue by gggto** [Homebrew/homebrew-cask#120832]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

Battle for Wesnoth uses an *even is stable, odd is dev* versionning scheme. Currently, the last stable version is 1.16.2, while on homebrew it is 1.17.0, which I as just explained is the dev version.

To avoid this kind of errors in the future, the livecheck in <https://github.com/Homebrew/homebrew-cask/blob/master/Casks/the-battle-for-wesnoth.rb> could become something along the lines of `regex(href=.*?Wesnoth[._-]v?(\d+(?:\.\d*[02468])+(?:\.\d+)*[a-z]?)\.dmg/i`, which should have the expected behaviour.

### Command that failed

none

### Output of command with `--verbose --debug`

```shell
none
```

### Output of `brew doctor --verbose`

```shell
none
```

### Output of `brew tap`

```shell
none
```

**Comment by bevanjkay** [comment]
@gggto Please open a PR with your suggested change and we can discuss the implementation there.
