### ISSUE TITLE
scilab 6.1.1 - pointers to add arm64

### ISSUE THREAD

**Issue by adavidzh** [Homebrew/homebrew-cask#121079]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

I'm not sure how else to raise this in order to figure out how to add `arm64` to `scilab` given that there are binaries for `arm64` [upstream (at the bottom of the page)](https://www.utc.fr/~mottelet/scilab_for_macOS.html).

I found the [`depends_on-arch`](https://docs.brew.sh/Cask-Cookbook#depends_on-arch) stanza but no clear idea of how to proceed.

A pointer of cask that has both `arm64` and `x86_64` could get me on the path to making a PR. Thanks!

### Command that failed

n.a.

### Output of command with `--verbose --debug`

```shell
n.a.
```

### Output of `brew doctor --verbose`

```shell
n.a.
```

### Output of `brew tap`

```shell
n.a.
```

**Comment by adavidzh** [comment]
Would [the `brave-browser` cask](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/brave-browser.rb) `if Hardware::CPU.intel?`-`then`-`else` be a good example to follow?

**Comment by SMillerDev** [comment]
Yeah, every cask with `if Hardware::CPU.intel?` would be fine to copy from.

**Comment by carlocab** [comment]
Please don't use our issue tracker for questions. The right place is the [discussions page](https://github.com/Homebrew/discussions/discussions), which you will see a link to when you click the "New Issue" button on GitHub.

> Would [the `brave-browser` cask](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/brave-browser.rb) `if Hardware::CPU.intel?`-`then`-`else` be a good example to follow?

Yes.

**Comment by adavidzh** [comment]
> Please don't use our issue tracker for questions. The right place is the [discussions page](https://github.com/Homebrew/discussions/discussions), which you will see a link to when you click the "New Issue" button on GitHub.

Thanks for the pointers² @SMillerDev and @carlocab.
