### ISSUE TITLE
Cask leapp unavailable for Linux

### ISSUE THREAD

**Issue by carlosleoliveira** [Homebrew/homebrew-cask#121584]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

When I try to install leapp on Linux I get a error message:

`Error: Cask 'leapp' is unavailable: No Cask with this name exists.`

### Command that failed

brew install --cask leapp

### Output of command with `--verbose --debug`

```shell
Error: Cask 'leapp' is unavailable: No Cask with this name exists.
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cask/cask_loader.rb:196:in `load'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cask/cask_loader.rb:205:in `load'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:139:in `load_formula_or_cask'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:59:in `block in to_formulae_and_casks'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:58:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:58:in `flat_map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:58:in `to_formulae_and_casks'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:170:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

### Output of `brew doctor --verbose`

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /home/leo/.local/bin/ansible-config
```

### Output of `brew tap`

```shell
homebrew/bundle
homebrew/core
```

**Comment by bevanjkay** [comment]
@carlosleoliveira `homebrew-cask` is only available for MacOS.

**Comment by carlosleoliveira** [comment]
I don't know who's responsible for the Leapp in Homebrew, the page from it says that I can install on Linux too. That's why I opened the issue.
![image](https://user-images.githubusercontent.com/60003832/161861330-c90b75ca-7f46-429b-beb7-d89b2757b4e2.png)

**Comment by bevanjkay** [comment]
@carlosleoliveira No worries. You'll need to report this to Leapp - as we don't support Linux.
