### ISSUE TITLE
[CI] generate-matrix.rb fails with Unhandled `depends_on macos` argument

### ISSUE THREAD

**Issue by isen-ng** [Homebrew/homebrew-cask#123974]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

Out of a sudden, `generate-matrix.rb` started returning this error, even on valid casks:

```
Unhandled `depends_on macos` argument
```

See this PR:
https://github.com/isen-ng/homebrew-dotnet-sdk-versions/pull/212

See the output:
https://github.com/isen-ng/homebrew-dotnet-sdk-versions/runs/6482936334?check_suite_focus=true

### Command that failed

brew ruby --verbose --debug -- "$(brew --repository homebrew/cask)/cmd/lib/generate-matrix.rb" "https://api.github.com/repos/isen-ng/homebrew-dotnet-sdk-versions/pulls/212"

### Output of command with `--verbose --debug`

```shell
brew ruby --verbose --debug -- "$(brew --repository homebrew/cask)/cmd/lib/generate-matrix.rb" "https://api.github.com/repos/isen-ng/homebrew-dotnet-sdk-versions/pulls/212"
  shell: /usr/bin/bash -e {0}
  env:
    HOMEBREW_DEVELOPER: 1
    HOMEBREW_NO_AUTO_UPDATE: 1
    HOMEBREW_GITHUB_API_TOKEN: ***
Error: Unhandled `depends_on macos` argument
Error: Process completed with exit code 1.
```

### Output of `brew doctor --verbose`

```shell
Not applicable in CI run
```

### Output of `brew tap`

```shell
Not applicable in CI run
```

**Comment by miccal** [comment]
Replace `depends_on macos: "> :mojave"` with `depends_on macos: ">= :mojave" and that should fix the issue you are seeing.

**Comment by isen-ng** [comment]
It works!
Thank you very much
