### ISSUE TITLE
jEdit "requires Java 11 or later" and doesn't run

### ISSUE THREAD

**Issue by gwerbin-tive** [Homebrew/homebrew-cask#124810]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

I installed jEdit and OpenJDK with `brew install jedit openjdk`, but jEdit fails to start, with this error:

> This application requires that Java 11 or later be installed on your computer. Please download and install the latest version of Java from www.java.com and try again.

<img width="372" alt="Screen Shot 2022-06-03 at 11 17 33 AM" src="https://user-images.githubusercontent.com/106692585/171883003-4708d680-1acf-4155-8024-c8a29170bdf7.png">

I have already installed OpenJDK with Homebrew. Do I need to install some JRE version instead, e.g. from the Oracle website? I don't really understand the whole Java ecosystem or its versioning system(s).

### Command that failed

open /Applications/jEdit.app

### Output of command with `--verbose --debug`

```shell
N/A
```

### Output of `brew doctor --verbose`

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /opt/local/bin/pkg-config
  /opt/local/bin/icu-config
  /opt/local/bin/krb5-config
  /opt/local/bin/freetype-config
  /opt/local/bin/xslt-config
  /opt/local/bin/libpng16-config
  /opt/local/bin/libpng-config
  /opt/local/bin/netpbm-config
  /opt/local/bin/gpgrt-config
  /opt/local/bin/libusb-config
  /opt/local/bin/python3.10-config
  /opt/local/bin/xml2-config
  /opt/local/bin/python3.9-config
  /opt/local/bin/onig-config
  /opt/local/bin/ksba-config
  /opt/local/bin/libmcrypt-config
  /opt/local/bin/curl-config
  /opt/local/bin/npth-config
  /opt/local/bin/ncursesw6-config
  /opt/local/bin/libassuan-config
  /opt/local/bin/pcre2-config
  /opt/local/bin/uuid-config
  /opt/local/bin/gpg-error-config
  /opt/local/bin/pcre-config
  /opt/local/bin/ncurses6-config
  /opt/local/bin/libgcrypt-config
  /opt/local/bin/pth-config
  /opt/pkg/bin/ncurses6-config
```

### Output of `brew tap`

```shell
aws/tap
homebrew/cask
homebrew/core
```

**Comment by bevanjkay** [comment]
@gwerbin-tive I have created a PR to update `jedit` with a `caveat` stanza that will output the following on install;

```
==> Caveats
jedit requires Java 11+. You can install the latest version with:
  brew install --cask temurin
```
