### ISSUE TITLE
Installation of Docker is hanging

### ISSUE THREAD

**Issue by mjsteinbaugh** [Homebrew/homebrew-cask#125921]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

Weirdly, I'm seeing the installation of Docker 4.9.1,81317 complete but then fail to launch the daemon successfully on 2 Intel Macs. Installation of the DMG [directly from the Docker Desktop website](https://www.docker.com/products/docker-desktop/) works. I made sure to remove all Docker configuation files -- not sure how to debug this further.

### Command that failed

brew install --cask docker

### Output of command with `--verbose --debug`

```shell
NA -- installation completes, but program doesn't launch successfully after installation
```

### Output of `brew doctor --verbose`

```shell
NA
```

### Output of `brew tap`

```shell
NA
```

**Comment by miccal** [comment]
This is a very popular Cask and are not seeing anyone else with this issue:
```
==> Analytics
install: 26,366 (30 days), 80,504 (90 days), 273,394 (365 days)
```
Perhaps try `brew reinstall --force homebrew/cask/docker` and see if that helps.

**Comment by mjsteinbaugh** [comment]
Totally agree, which is weird on machines. I'll see if this persists with the next Docker Desktop release, and will reopen if I can reproduce.
