### ISSUE TITLE
Upgrading Firefox requires admin privileges

### ISSUE THREAD

**Issue by soylent** [Homebrew/homebrew-cask#127394]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

As an unprivileged user, install Firefox to ~/Applications:
```
brew install firefox --cask --appdir=~/Applications
```
But updating it requires admin privileges because it's trying to remove `/Library/Logs/DiagnosticReports/firefox_*`:
```
brew upgrade --cask firefox
[...]
==> Removing files:                                 
/Library/Logs/DiagnosticReports/firefox_*                                                               
Password:
```
Here's the relevant part of the formula:
https://github.com/Homebrew/homebrew-cask/blob/982779bc675eb62bbb38593442e80e829faf89bb/Casks/firefox.rb#L229-L230

### Command that failed

brew upgrade --cask firefox

### Output of command with `--verbose --debug`

```shell
N/A
```

### Output of `brew doctor --verbose`

```shell
N/A
```

### Output of `brew tap`

```shell
N/A
```

**Comment by carlocab** [comment]
Sorry, but we require all issues to provide the requested information, regardless of whether they're relevant or not.

We can reopen this when you provide the missing information.
