### ISSUE TITLE
Invalid MarkText metadata

### ISSUE THREAD

**Issue by fxha** [Homebrew/homebrew-cask#127992]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

The `marktext.app` domain of the MarkText package is no longer owned by the MarkText organization and must be removed or replaced by `github.com/marktext/marktext` due to security concerns. See https://github.com/marktext/marktext/issues/3348.

Source: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/mark-text.rb#L11

### Command that failed

.

### Output of command with `--verbose --debug`

```shell
.
```

### Output of `brew doctor --verbose`

```shell
.
```

### Output of `brew tap`

```shell
.
```

**Comment by SMillerDev** [comment]
Please make a pull to this extend.

**Comment by p-linnane** [comment]
#128000
