### ISSUE TITLE
Cask not found if tapping homebrew-cask in another tab

### ISSUE THREAD

**Issue by dorianmariefr** [Homebrew/homebrew-cask#131370]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

After installing homebrew, I tried to install Spotify and Cloudflare WARP.

Installing Spotify launched a tap on cask.

But installing Cloudflare WARP told me the cask was not found even though it exists https://formulae.brew.sh/cask/cloudflare-warp.

### Command that failed

brew install --cask cloudflare-warp

### Output of command with `--verbose --debug`

```shell
Error: Cask 'cloudflare-warp' is unavailable: No Cask with this name exists.
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:196:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:205:in `load'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:129:in `load_formula_or_cask'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:57:in `block in to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:56:in `each'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:56:in `flat_map'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:56:in `to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cmd/install.rb:178:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

### Output of `brew doctor --verbose`

```shell
Your system is ready to brew.
```

### Output of `brew tap`

```shell
homebrew/cask
homebrew/core
```

**Comment by SMillerDev** [comment]
Try the one checkbox you didn't do.

**Comment by dorianmariefr** [comment]
Isn’t this supposed to work without some debugging commands?

**Comment by SMillerDev** [comment]
Brew update isn't really for debugging.

**Comment by dorianmariefr** [comment]
If you don't want to fix, feel free to mark it as WONTFIX

**Comment by SMillerDev** [comment]
Not all verification steps were done
