### ISSUE TITLE
Casks not searchable in fresh install (M1 Pro Macbook Pro)

### ISSUE THREAD

**Issue by apotenza92** [Homebrew/homebrew-cask#131893]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

Fresh install of macOS Monterey and fresh install of homebrew using script. Common app casks are simply not searchable but they can be installed with a manual command of their name.

### Command that failed

brew info --cask alfred

### Output of command with `--verbose --debug`

```shell
brew info --cask --verbose --debug alfred
Error: Cask 'alfred' is unavailable: No Cask with this name exists.
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:196:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:205:in `load'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:129:in `load_formula_or_cask'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:85:in `block in to_formulae_and_casks_and_unavailable'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:84:in `map'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:84:in `to_formulae_and_casks_and_unavailable'
/opt/homebrew/Library/Homebrew/cmd/info.rb:162:in `print_info'
/opt/homebrew/Library/Homebrew/cmd/info.rb:125:in `info'
/opt/homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

### Output of `brew doctor --verbose`

```shell
Your system is ready to brew.
```

### Output of `brew tap`

```shell
homebrew/core
```

**Comment by p-linnane** [comment]
Looks like you only have `homebrew/core` tapped. Run `brew tap homebrew/cask` and then try again.

**Comment by apotenza92** [comment]
Thanks that worked. Not sure why that wasn't included as part of the default installation of homebrew? In my past experience I haven't had to do that manually.

**Comment by p-linnane** [comment]
Only `homebrew/core` is tapped at install time. I can't speak to your previous experiences but as long as I can remember `homebrew/cask` has been an additional step.
