### ISSUE TITLE
Unable to uninstall oversight

### ISSUE THREAD

**Issue by dchimeno** [Homebrew/homebrew-cask#134096]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.6.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 978a452ea7ccdff1ed7377f88add3ff0513ba2b7
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0d5969d58ae67007a5c878c512387bf7d406feed
Core tap last commit: 5 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.32.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.4-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4.1
Rosetta 2: false
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

brew uninstall oversight

### What happened (include all command output)?

Running uninstall script /opt/homebrew/Caskroom/oversight/2.0.1/OverSight Installer.app/Contents/MacOS/OverSight Installer
2022-10-23 17:44:45.408 defaults[42675:39981994]
Domain (com.objective-see.oversight) not found.
Defaults have not been changed.

OVERSIGHT ERROR: uninstall failed

Error: Failure while executing; `/usr/bin/sudo -E -- /opt/homebrew/Caskroom/oversight/2.0.1/OverSight\ Installer.app/Contents/MacOS/OverSight\ Installer -uninstall` exited with 255. Here's the output:
2022-10-23 17:44:45.408 defaults[42675:39981994]
Domain (com.objective-see.oversight) not found.
Defaults have not been changed.

OVERSIGHT ERROR: uninstall failed

### What did you expect to happen?

oversight uninstalled

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew uninstall oversight
```

**Comment by SMillerDev** [comment]
It seems the upstream installer is just broken. Not much Homebrew can do about it

**Comment by p-linnane** [comment]
Please [open an issue](https://github.com/objective-see/OverSight/issues) with Objective-See as this is not an issue with Homebrew.
