### ISSUE TITLE
dependabot creates PRs in forks

### ISSUE THREAD

**Issue by nrlquaker** [Homebrew/homebrew-cask#134172]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

dependabot creates PRs in forks like this `Bump peter-evans/create-or-update-comment from 2.0.0 to 2.1.0`.
Is it possible to limit dependabot to main repo only?

### Command that failed

none

### Output of command with `--verbose --debug`

```shell
not needed
```

### Output of `brew doctor --verbose`

```shell
not needed
```

### Output of `brew tap`

```shell
not needed
```

**Comment by SMillerDev** [comment]
It is not, and this issue should be filed with dependabot not Homebrew

**Comment by nrlquaker** [comment]
Thanks for the reply.
Seems like dependabot [issue](https://github.com/dependabot/dependabot-core/issues/2804).
> We're actively working on this and a permanent fix should land in the next couple of weeks. We'll share more around the time we''re ready to roll this out
