### ISSUE TITLE
Warning: Unexpected method 'arch' called on Cask pycharm-ce

### ISSUE THREAD

**Issue by MDGrey33** [Homebrew/homebrew-cask#134650]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

Uninstalling pycharm-ce fails
brew update --force
output
`fatal: '...' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Fetching /opt/homebrew failed!`

### Command that failed

brew uninstall --force --verbose pycharm-ce

### Output of command with `--verbose --debug`

```shell
Warning: Unexpected method 'arch' called on Cask pycharm-ce.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Error: Cask 'pycharm-ce' definition is invalid: invalid 'sha256' value: {:arm=>"6b87c85f6b5b3262904b34d0bbb6775d2654610685a8bca9977b147644b113ea", :intel=>"01eec651f6e8d92e1bfe5688aeb179ad5eb92e77ef77d102793d4848f8efc0d4"}
```

### Output of `brew doctor --verbose`

```shell
Warning: Unexpected method 'arch' called on Cask pycharm-ce.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Error: Cask 'pycharm-ce' definition is invalid: invalid 'sha256' value: {:arm=>"6b87c85f6b5b3262904b34d0bbb6775d2654610685a8bca9977b147644b113ea", :intel=>"01eec651f6e8d92e1bfe5688aeb179ad5eb92e77ef77d102793d4848f8efc0d4"}
```

### Output of `brew tap`

```shell
homebrew/bundle
homebrew/cask
homebrew/core
```

**Comment by SMillerDev** [comment]
What does `brew config` and `brew doctor` say

**Comment by MDGrey33** [comment]
brew config 
                    
HOMEBREW_VERSION: 3.4.0
ORIGIN: ...
HEAD: ffc76654da12fba7d34d078fd9bf681fef65921e
Last commit: 8 months ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fe9cbf1816a78ecb31e7b5db3f51fd391f24aad2
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.35.3 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-arm64
CLT: 14.0.0.0.1.1661618636
Xcode: N/A
Rosetta 2: false


brew doctor  same as brew doctor --verbose, stated in the original message

**Comment by SMillerDev** [comment]
You set the Homebrew git origin to something nonsensical so it hasn't updated in 8 months. Try running `brew update-reset` to get it back to its normal value.

**Comment by MDGrey33** [comment]
brew update -reset

[Output]
`brew update-reset                               
==> Fetching /opt/homebrew...
fatal: '...' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: '...' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

==> Resetting /opt/homebrew...
branch 'master' set up to track 'origin/master'.
Switched to and reset branch 'master'
Your branch is up to date with 'origin/master'.

==> Fetching /opt/homebrew/Library/Taps/homebrew/homebrew-bundle...

==> Resetting /opt/homebrew/Library/Taps/homebrew/homebrew-bundle...
branch 'master' set up to track 'origin/master'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.

==> Fetching /opt/homebrew/Library/Taps/homebrew/homebrew-cask...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 12 (delta 4), reused 8 (delta 4), pack-reused 0
Unpacking objects: 100% (12/12), 116.32 KiB | 1.00 MiB/s, done.
From https://github.com/Homebrew/homebrew-cask
   40c105bf1a..6cdbdda354  master     -> origin/master

==> Resetting /opt/homebrew/Library/Taps/homebrew/homebrew-cask...
branch 'master' set up to track 'origin/master'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.

==> Fetching /opt/homebrew/Library/Taps/homebrew/homebrew-core...
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 24 (delta 13), reused 18 (delta 9), pack-reused 0
Unpacking objects: 100% (24/24), 175.57 KiB | 1.06 MiB/s, done.
From https://github.com/Homebrew/homebrew-core
   fe9cbf1816a..af672d9ec0f  master     -> origin/master

==> Resetting /opt/homebrew/Library/Taps/homebrew/homebrew-core...
branch 'master' set up to track 'origin/master'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.
`


brew update      

[output]

`fatal: '...' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Fetching /opt/homebrew failed!`

**Comment by SMillerDev** [comment]
That's disappointing, thought that would reset the origin too. Try `git -C $(brew --repo) remote set-url origin https://github.com/Homebrew/brew.git`

**Comment by MDGrey33** [comment]
$ git -C $(brew --repo) remote set-url origin https://github.com/Homebrew/brew.git

$ brew doctor                                                                     
Warning: Unexpected method 'arch' called on Cask pycharm-ce.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Error: Cask 'pycharm-ce' definition is invalid: invalid 'sha256' value: {:arm=>"6b87c85f6b5b3262904b34d0bbb6775d2654610685a8bca9977b147644b113ea", :intel=>"01eec651f6e8d92e1bfe5688aeb179ad5eb92e77ef77d102793d4848f8efc0d4"}


$ brew --config                                                                   
HOMEBREW_VERSION: 3.4.0
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: ffc76654da12fba7d34d078fd9bf681fef65921e
Last commit: 8 months ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a99c43cbe3fe513282c9c08ab9881b2aa88e91e6
Core tap last commit: 10 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.35.3 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-arm64
CLT: 14.0.0.0.1.1661618636
Xcode: N/A
Rosetta 2: false

**Comment by MDGrey33** [comment]
Thank you, managed to get it to work using your advice.
$ cd /opt/homebrew/bin
$ ls -al | grep git

git -> ../Cellar/git/2.35.3/bin/git

$ cd ../Cellar/git/2.35.3/bin/
$ git -C $(brew --repo) remote set-url origin https://github.com/Homebrew/brew.git
$brew --config 
                                                                  
HOMEBREW_VERSION: 3.4.0
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: ffc76654da12fba7d34d078fd9bf681fef65921e
Last commit: 8 months ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a99c43cbe3fe513282c9c08ab9881b2aa88e91e6
Core tap last commit: 10 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.35.3 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-arm64
CLT: 14.0.0.0.1.1661618636
Xcode: N/A
Rosetta 2: false

$ brew update 

Updated 2 taps (homebrew/core and homebrew/cask).
==> Outdated Formulae
awscli         gettext        gpgme          libffi         libnghttp2     libuv          p11-kit        tree
bdw-gc         ghostscript    guile          libgpg-error   libpng         little-cms2    pcre2          unbound
cmake          git            icu4c          libidn         libpq          nettle         pinentry       webp
direnv         gnupg          imagemagick@6  libidn2        libtasn1       node@12        python@3.9     zsh
freetype       gnutls         krb5           libksba        libtiff        openjpeg       ruby-build
==> Outdated Casks
chirp                                                        vnc-viewer

You have 39 outdated formulae and 2 outdated casks installed.
You can upgrade them with brew upgrade
or list them with brew outdated.

$ brew doctor

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  node@12

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /opt/homebrew/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/opt/homebrew/sbin:$PATH"' >> ~/.zshrc

I will try to fix the issues highlighted by brew doctor now.
Much appreciate the help 🥇

**Comment by MDGrey33** [comment]
Brewing happily, Thank you :) 

$ brew update 

Already up-to-date.

$ brew upgrade
$ brew doctor 

Your system is ready to brew.

**Comment by R-touyama** [comment]
I had a similar problem.
This command cured it.

https://github.com/Homebrew/homebrew-cask/issues/134650#issuecomment-1296167211
