### ISSUE TITLE
Cask workflows: `set-output` deprecated

### ISSUE THREAD

**Issue by unitof** [Homebrew/homebrew-cask#135715]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

GitHub is [deprecating `::set-output`](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) in custom Actions runners.

I noticed in my last Cask PR there is now a [warning](https://github.com/Homebrew/homebrew-cask/actions/runs/3453749018/jobs/5764586082#step:4:60) each time we use that, which is often.

They will be fully disabled in May 2023.

I'm relatively novice with GH Workflows, but it seems what we have to do is convert the current

```
puts "::set-output name=was_installed::#{JSON.generate(was_installed)}"
```

syntax in all our `/.github/workflows/**` files with the new syntax:

```
echo "was_installed=#{JSON.generate(was_installed)}}" >> $GITHUB_OUTPUT
```

I'd be honored to take on this PR! But wanted to check before doing so, since this affects sensitive workflows.

### Command that failed

[assorted GH workflows]

### Output of command with `--verbose --debug`

```shell
n/a
```

### Output of `brew doctor --verbose`

```shell
n/a
```

### Output of `brew tap`

```shell
n/a
```

**Comment by SMillerDev** [comment]
A pull request would be great, thanks

**Comment by reitermarkus** [comment]
There is already one open here: https://github.com/Homebrew/homebrew-cask/pull/133344
