### ISSUE TITLE
Chromium cask broken (on Apple silicon)

### ISSUE THREAD

**Issue by neuhaus** [Homebrew/homebrew-cask#135991]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

I installed the chromium cask on Apple Silicon macOS 13.0.1 (_Darwin box 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64_) using homebrew 3.6.11.
There were no errors during installation. I also tried to reinstall it the next day.

When trying to launch chromium, i get:

_"Chromium" is damaged and cannot be opened. It is recommended to move the object into the trash bin._

Running "file" on the binary looks ok:

    $ file /Applications/Chromium.app/Contents/MacOS/Chromium
    /Applications/Chromium.app/Contents/MacOS/Chromium: Mach-O 64-bit executable arm64

What's wrong with the cask?

### Command that failed

chromium

### Output of command with `--verbose --debug`

```shell
n/a
```

### Output of `brew doctor --verbose`

```shell
n/a
```

### Output of `brew tap`

```shell
n/a
```

**Comment by neuhaus** [comment]
```
% brew list chromium
==> App
/Applications/Chromium.app (168 files, 252MB)
==> Binary
/opt/homebrew/bin/chromium -> /opt/homebrew/Caskroom/chromium/latest/chromium.wrapper.sh (73B)
==> Preflight Block
preflight (Preflight Block)

% brew info chromium
==> chromium: latest
https://www.chromium.org/Home
/opt/homebrew/Caskroom/chromium/latest (323B)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/chromium.rb
==> Name
Chromium
==> Description
Free and open-source web browser
==> Artifacts
chrome-mac/Chromium.app (App)
/opt/homebrew/Caskroom/chromium/latest/chromium.wrapper.sh -> chromium (Binary)
==> Analytics
install: 6,835 (30 days), 19,833 (90 days), 68,949 (365 days)
```

**Comment by SMillerDev** [comment]
https://docs.brew.sh/FAQ#why-cant-i-open-a-mac-app-from-an-unidentified-developer explains what to do, on ARM this reports as damaged.

**Comment by neuhaus** [comment]
Right-clicking open did not solve the problem. Are you sure it's not actually broken?
