### ISSUE TITLE
Show DMG agreements by default

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-cask#13593]
References https://github.com/caskroom/homebrew-cask/issues/720. Some preliminary work done (and abandoned) in https://github.com/caskroom/homebrew-cask/pull/8231.

How the system should work:
- Show DMG agreements by default.
  - This is a blocking operation (i.e. the user has to type `y` or `n` to agree or not, before continuing).
  - The license is redirected to `less`, for easy reading and so terminal output doesn’t get cluttered.
    - If they agree, the installation continues.
    - If they disagree, the installation of that particular package aborts and the rest (if any) continue.
- Have a `--blindly-accept-licenses`<sup>1</sup> flag that will auto-accept agreements for that command.
  - This also works if set in `HOMEBREW_CASK_OPTS`.
  - In this case, the license won’t even be printed to output, and the user won’t be warned.

---

<sup>1</sup> The use of “blindly”, [as suggested by @MattiSG](https://github.com/caskroom/homebrew-cask/issues/720#issuecomment-67355027), has power.

**Comment by jawshooah** [comment]
It's worth mentioning that implementation of this feature is blocked by #8231. There's nothing to stop us from picking up @claui's work and moving forward, though.

**Comment by vitorgalvao** [comment]
@claui has been absent from the project for a long time, and [hasn’t even replied on that issue](https://github.com/caskroom/homebrew-cask/pull/8231#issuecomment-124977532) so we should consider that dead, and just pick up whatever’s useful.

**Comment by Amorymeltzer** [comment]
Just popping in to reiterate [my previous comment](https://github.com/caskroom/homebrew-cask/issues/720#issuecomment-67335235).  A simple one-line message, whether the default or with another flag, telling the user what they blindly agreed to would be welcome.

**Comment by MattiSG** [comment]
:+1:

**Comment by reitermarkus** [comment]
@vitorgalvao, I think this is actually implemented, but only shown with `--verbose`.

**Comment by vitorgalvao** [comment]
@reitermarkus But that is that ever a blocking operation that the user has to agree to before continuing?

**Comment by reitermarkus** [comment]
No, it doesn't block. Honestly, I think we should just close this. Nobody has complained or shown any interest in this in 4 years.
