### ISSUE TITLE
chronycontrol wipes configuration on upgrade

### ISSUE THREAD

**Issue by miquecg** [Homebrew/homebrew-cask#136451]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

I'd like to request a change for ChronyControl cask so it does not wipe chrony daemon configuration on each upgrade, which lives in `/etc/chrony.d`.

As per [discussion](https://github.com/orgs/Homebrew/discussions/3968), one solution would be to move [this line](https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/chronycontrol.rb#L22) to `zap` stanza.

### Command that failed

brew upgrade

**Comment by SMillerDev** [comment]
Please make a pull request for this.

**Comment by miquecg** [comment]
Thanks!
