### ISSUE TITLE
Chromium cask doesn't work on M1

### ISSUE THREAD

**Issue by rickwubs** [Homebrew/homebrew-cask#136621]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

It says Chromium is broken and must be moved to the bin.

### Command that failed

none

### Output of command with `--verbose --debug`

```shell
.
```

### Output of `brew doctor --verbose`

```shell
.
```

### Output of `brew tap`

```shell
.
```

**Comment by SMillerDev** [comment]
Then this should be reported to Chromium. Not Homebrew.

**Comment by rickwubs** [comment]
Home brew makes the cask available, surely it’s up to home brew to make sure that what they make available works?

After all you show the cask on your website..

Met vriendelijke groet,

Rick Wubs

**Comment by SMillerDev** [comment]
Is it up to Google to fix the website it finds for you?

**Comment by rickwubs** [comment]
I’d say it is if that website is part of their GitHub.

https://github.com/Homebrew/homebrew-cask/blob/master/Casks/chromium.rb

Please note that it is possible to get chromium working, it’s just that if you install the cask it does not work.

**Comment by SMillerDev** [comment]
If you insist on not telling the developers of the software that you have an issue with their software there is nothing we can do for you here. Your insistence that Homebrew distributing it makes it Homebrew's responsibility will not change that.

**Comment by rickwubs** [comment]
I don’t have a problem with chromium, I have a running version of chromium as we speak. Because they provide build instructions on their GitHub, and those instructions do work.

Your cask does not.

But I understand it’s not appreciated to tell you this, so I won’t in the future. That’s fine.
