### ISSUE TITLE
SHA256 mismatch for Onyx

### ISSUE THREAD

**Issue by verboEse** [Homebrew/homebrew-cask#137032]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
~  $ brew doctor
Your system is ready to brew.
~  $ brew config
HOMEBREW_VERSION: 3.6.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 747829334b4bb3ab0d67a4c8bd9f4bf78c491c49
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ea6649075c3656f38f23ac40e3e1be9af07472ac
Core tap last commit: 18 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.84.0 => /usr/bin/curl
macOS: 13.0.1-arm64
CLT: 14.1.0.0.1.1666437224
Xcode: N/A
Rosetta 2: false
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

brew install onyx

### What happened (include all command output)?

~  $ brew install onyx
==> Downloading https://www.titanium-software.fr/download/13/OnyX.dmg
Already downloaded: /Users/myuser/Library/Caches/Homebrew/downloads/1e845f3072528cb592885d32deeb1bacc8929ddeb6bca2cfe191cc8a30d49d54--OnyX.dmg
Error: SHA256 mismatch
Expected: 40f3686fa4fa1b0d55636ce63d4f43f43cfd6b0f84af0e5ca8adfc0f35e15858
  Actual: 003a1beade5cb33ce5d8e20d14dae2aa1ac051f2f0dec6cc95ceefb1b3a51b60
    File: /Users/myuser/Library/Caches/Homebrew/downloads/1e845f3072528cb592885d32deeb1bacc8929ddeb6bca2cfe191cc8a30d49d54--OnyX.dmg
To retry an incomplete download, remove the file above.

### What did you expect to happen?

installation of Onyx

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Just trying to install Onyx with home-brew ¯\_(ツ)_/¯
```

**Comment by bevanjkay** [comment]
Please follow the instructions at https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match.
