### ISSUE TITLE
Upgrading git-credential-manager fails with error

### ISSUE THREAD

**Issue by shivahnshankar** [Homebrew/homebrew-cask#138328]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
> brew config
HOMEBREW_VERSION: 3.6.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: 740f9ddcc620d4812770a0f12854ddd79c643874
Last commit: 33 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 08e7183dcc78832ab3c5ba60ab199216b82001c2
Core tap last commit: 83 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.0 => /opt/homebrew/bin/git
Curl: 7.85.0 => /usr/bin/curl
macOS: 13.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false

> brew doctor
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

brew update and then brew upgrade

### What happened (include all command output)?

==> Upgrading git-credential-manager-core
==> Downloading https://github.com/GitCredentialManager/git-credential-manager/releases/download/v2.0.886/gcm-osx-arm64-2.0.886.pkg
Already downloaded: /Users/shivashankar/Library/Caches/Homebrew/downloads/f619fcb1774b0b07953ef69b3f0edc026f10d0702d309024537f1de77a3be2da--gcm-osx-arm64-2.0.886.pkg
==> Running uninstall script /opt/homebrew/share/gcm-core/uninstall.sh
==> Purging files for version 2.0.886 of Cask git-credential-manager-core
Error: microsoft/git/git-credential-manager-core: uninstall script /opt/homebrew/share/gcm-core/uninstall.sh does not exist.

### What did you expect to happen?

Upgrade installs latest version of git-credential-manager

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
i already had git-credential-manager installed.

brew update
brew upgrade
```

**Comment by miccal** [comment]
We do not have a Cask called `git-credential-manager-core`, so I assume you installed this from an external tap, which is where you will need to report this.
