### ISSUE TITLE
Postgres.app versions

### ISSUE THREAD

**Issue by spencermathews** [Homebrew/homebrew-cask#138741]
The cask for [Postgres.app](https://postgresapp.com/) (currently [postgres-unofficial.rb](https://github.com/Homebrew/homebrew-cask/commits/master/Casks/postgres-unofficial.rb)) contains an unwieldy 6 different versions of PostgreSQL. 

The reason for this seems historical. Prior to [v2.2](https://github.com/PostgresApp/PostgresApp/releases/tag/v2.2) releases included all supported versions of PostgreSQL. Starting with v2.2 the latest PostgreSQL began to also be released by itself, without the baggage of all the legacy releases. The Cask was updated in [b526331](https://github.com/Homebrew/homebrew-cask/commit/b52633190d94bbffd11cbef9168164db58c658a3) with the new naming scheme, but the multi-version release stayed.

The v2.2 release notes say that:

> If you just want PostgreSQL, get the smaller DMG. It includes everything you need to get started. If you need multiple versions of PostgreSQL for testing, get the big DMG.

And the current [Downloads](https://postgresapp.com/downloads.html) page lists the single-version DMG at the top as the "Latest Release".

All this is to say that Homebrew users expect the current version of software so it seems unnecessary (and beyond redundant) for the general use case to continue to prefer the multi-version DMG. The latter currently weighs in at 379 MB, compared to 93 MB for just the latest PostgreSQL version, and offers little to no value for most users.

So, the purpose of this issue is to request that the Cask be updated to using the latest single-version release instead of the behemoth multi-version release.

**Comment by bevanjkay** [comment]
You are welcome to open a PR to update the cask - https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md
