### ISSUE TITLE
Can uninstall the Clockify Cask

### ISSUE THREAD

**Issue by satikusala** [Homebrew/homebrew-cask#139849]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

I installed the clockify cask. I then tried to uninstall or remove it, e.g. brew uninstall --cask clockify, and I kept getting an error "Error: It seems there is already an App at */opt/homebrew/Caskroom/clockify/2.8.4,458/Clockify Desktop.app'". I tried different commands with the same result. whey would it not unintall?

### Command that failed

brew uninstall --cask clockify

### Output of command with `--verbose --debug`

```shell
n/a.
```

### Output of `brew doctor --verbose`

```shell
n/a.
```

### Output of `brew tap`

```shell
n/a.
```

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.
