### ISSUE TITLE
macupdater 3 requires Ventura, so don't install it on older macOS versions

### ISSUE THREAD

**Issue by xyzzy-plugh-plover** [Homebrew/homebrew-cask#140563]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

macupdater 3 requires Ventura, so it shouldn't be installed on older macOS versions.

### Command that failed

brew reinstall macupdater

### Output of command with `--verbose --debug`

```shell
brew doesn't give any errors, it just installs an app version that won't work on my version of macOS
```

### Output of `brew doctor` and `brew config`

```shell
brew doesn't give any errors, it just installs an app version that won't work on my version of macOS
```

### Output of `brew tap`

```shell
brew doesn't give any errors, it just installs an app version that won't work on my version of macOS
```

**Comment by xyzzy-plugh-plover** [comment]
Thanks. How can I downgrade macupdater to 2.x so I can still use it?

**Comment by miccal** [comment]
> Thanks. How can I downgrade macupdater to 2.x so I can still use it?

https://github.com/Homebrew/homebrew-cask/pull/140583
