### ISSUE TITLE
brew install unity: Unity Hub.app exits with no License File found. Doc fix needed

### ISSUE THREAD

**Issue by richtong** [Homebrew/homebrew-cask#140662]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

Brew install unity correctly downloads the Unity Hub, but when running Unity it immediate returns with a 'No License found' and the only option is to quit Unity Hub. It looks like the license file needs to manually installed so it looks like there should at least be a note to explain this on a Mac you have to generate Unity_id.ulf and put it into /Library/Applications Support/Unity or Unity Hub will just exit.

### Command that failed

brew install unity

### Output of command with `--verbose --debug`

```shell
The command complete correctly but if fails to note the need to install a license file as above or the Unity Hub will just exit
```

### Output of `brew doctor` and `brew config`

```shell
brew doctor


lease note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  mermaid-cli

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libndi.4.dylib

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  mermaid-cli

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libndi.4.dylib

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker
^C
❯ brew doctor &| pbcopy
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  mermaid-cli

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libndi.4.dylib

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker
```

brew config: 

```
HOMEBREW_VERSION: 3.6.20-278-gdc14558
ORIGIN: https://github.com/Homebrew/brew
HEAD: dc145587da1bef3382ce7d4526029df45b8328af
Last commit: 2 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c40b889407e06399750084a32a582ee17172968e
Core tap last commit: 82 minutes ago
Core tap branch: master
Core tap JSON: 06 Feb 18:23 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.7Shj2qxHpg/org.xquartz:0
HOMEBREW_EDITOR: /opt/homebrew/bin/nvim
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.1 => /opt/homebrew/bin/git
Curl: 7.85.0 => /usr/bin/curl
macOS: 13.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false
```
```


### Output of `brew tap`

```shell
adoptopenjdk/openjdk
discoteq/discoteq
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/core
osrf/simulation
px4/px4
robotsandpencils/made
ubuntu/microk8s
```

**Comment by miccal** [comment]
Note to self: https://support.unity.com/hc/en-us/articles/211438683-How-do-I-activate-my-license-

**Comment by miccal** [comment]
According to the link above, you should be able to activate the licence from within the `.app`?

**Comment by richtong** [comment]
Yes what happens with the brew install is that you never get to this instead, the app just exist prematurely with a "No License Found message", but when you download from there site, it correctly runs the start up so doesn't do this. If you do download the app from their site and run the set up, if you then do a brew install --greedy then it works correctly. (I wanted to use brew to make sure to get updates to the Unity Hub).

I haven't looked into it, but did a quick glance at the ruby script, could it be that it is using a batch installation mode for the installer so it is designed for CD/CI cases where the .ulg file is already there?

Sorry I'm not Unity install expert ;-)

Sent via Superhuman ( ***@***.*** )

**Comment by miccal** [comment]
Are you referring to [`unity`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/unity.rb) or [`unity-hub`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/unity-hub.rb) here?

**Comment by richtong** [comment]
Ah yes I see the problem, thank you Miccal, you need to install unity-hub to get the license, if you just install unity then it doesn't have the license that unity hub finds. I'm so stupid! Thanks this can be closed, although it is really confusing for the noob unity user.

Sent via Superhuman ( ***@***.*** )

**Comment by carlocab** [comment]
If you need to install `unity-hub` to get `unity` to work, shouldn't the `unity` cask do that automatically?

**Comment by richtong** [comment]
Well I’m not sure I think it’s a documentation thing. But it looks like unity hub is the central downloader and license manager. So you use it like npm to manage unity versions.

It looks like the unity cask is the latest version of unity and expects a license file to already be there.

A dumb user like me sees unity and tries to install it not realizing that unity-hub comes first. The unity documents always start with unity hub and only experienced users do direct downloads of the specific version they want. So the proper sequence is

1. Brew install unity-hub
2. Start it and get your license. Then you can install your unity engine from there

For people who are advanced then should

1. Get their license file and copy it into Library/Applications Support/Unity/license.ulf
2 brew install unity if and only if you want the latest version (a reasonably uncommon case as they update the engine very often)

Sent via Superhuman iOS ( ***@***.*** )
