### ISSUE TITLE
Unable to upgrade cask with `brew upgrade --cask` even after I change the content of specific casks

### ISSUE THREAD

**Issue by singularitti** [Homebrew/homebrew-cask#140870]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

In the past, I was able to bump a cask using `brew bump-cask-pr $cask --no-browse --version $version` (I still can do it now). And before the merging of my PR, I can install my bumped new version of the cask with a local branch `bump-xxx-version` using `brew upgrade --cask`. But recently, I found that even after I switched to the local branch. I still cannot upgrade that cask with the aforementioned command. What's worse, my local `homebrew-cask` repo will not be pulled automatically after I run the command. And even if my PR is closed and I pulled it manually, I still cannot install the latest version of cask, which I just made a PR for. I have to wait for some time before it can be upgraded. I do not know if it is a bug or desired feature of homebrew. But this behavior is confusing, and I wish it could be somehow fixed.

### Command that failed

brew upgrade --cask

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/3.6.21-67-g8cd497d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --fail --location --remote-time --output /Users/qz/Library/Caches/Homebrew/api/cask.json --time-cond /Users/qz/Library/Caches/Homebrew/api/cask.json --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/cask.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading 1password
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading 1password-cli
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading alfred
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading alt-tab
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading bartender
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading batteries
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading betterzip
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading cleanmymac-zh
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading cleanshot
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading dash
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading displaperture
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading dockmate
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading dropbox
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading eudic
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading fork
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading gitkraken
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading grammarly-desktop
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading iina
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading input-source-pro
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading iterm2
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading keysmith
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading lunar
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading metaimage
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading microsoft-edge
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading mission-control-plus
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading one-switch
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading openinterminal
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading paletro
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading pdf-expert
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading quit-all
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading suspicious-package
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading swish
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading telegram
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading tg-pro
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading transmit
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading typeface
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading typora
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading visual-studio-code
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading zoom
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.21-67-g8cd497d\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.2\)\ curl/7.86.0 --header Accept-Language:\ en --retry 3 --fail https://raw.githubusercontent.com/Homebrew/homebrew-cask/16ac7c941c841787e3b661ea9f040b2b87cebafb/Casks/zoom.rb
```

### Output of `brew doctor` and `brew config`

```shell
$ brew doctor
Your system is ready to brew.

$ brew config
HOMEBREW_VERSION: 3.6.21-67-g8cd497d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8cd497d37efa812fb65576c0e233bde923e78331
Last commit: 4 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2f66a74ab329e3f12d2978eb263dfad96b304140
Core tap last commit: 4 hours ago
Core tap branch: master
Core tap JSON: 10 Feb 23:20 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: code
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
$ brew tap
buo/cask-upgrade
homebrew/aliases
homebrew/bundle
homebrew/cask
homebrew/cask-fonts
homebrew/command-not-found
homebrew/core
```

**Comment by bevanjkay** [comment]
@singularitti This will be because `brew upgrade` is using the API instead of git to track the latest versions.
You can optionally set an env `HOMEBREW_NO_INSTALL_FROM_API=1`

**Comment by singularitti** [comment]
> @singularitti This will be because `brew upgrade` is using the API instead of git to track the latest versions. You can optionally set an env `HOMEBREW_NO_INSTALL_FROM_API=1`

Can I untap `homebrew-cask` then? It takes up a lot of space on my disk.

**Comment by bevanjkay** [comment]
If you would like your changes to be available to you immediately you will need to keep `homebrew-cask` tapped and use the `HOMEBREW_NO_INSTALL_FROM_API=1` environment variable.
If you have `BREW_DEVELOPER=1` set and would like to continue using developer commands (bumping casks etc..) you will need to keep `homebrew-cask` tapped.

**Comment by singularitti** [comment]
And that means if I use neither of the features, I could untap `homebrew-cask`, is that right? How about other homebrew taps? It seems that `homebrew-cask-font` still uses `git`?

**Comment by Rylan12** [comment]
The API install is currently available for `homebrew/cask` and `homebrew/core`, so things like `homebrew/cask-fonts` will still need to remain tapped locally. However, those repos are much smaller so hopefully they don't pose as much of an issue.

To answer your other question, yes it's safe to untap `homebrew/cask` and `homebrew/core`. You'll still be able to use Homebrew the same as before. The only exception is that certain developer commands require those to be tapped locally in order to make any sense. For example, if you want to run `brew edit` or `brew cat`, you'll need to have the files installed locally.

This also applies to `bump-formula-pr` and `bump-cask-pr`. Since those commands require the formula/cask source, you can't run them without the respective tap installed locally.

---

Is there still an issue here that you're looking to resolve or can this issue be closed?

**Comment by singularitti** [comment]
This issue can be closed, thank you!
