### ISSUE TITLE
citrix-workspace native Apple Silicon support

### ISSUE THREAD

**Issue by felker** [Homebrew/homebrew-cask#141499]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

A 2023-02-07 article from Citrix indicates that they now offer native support of M1/M2 Apple Silicon via a Universal Binary: https://docs.citrix.com/en-us/citrix-workspace-app-for-mac/apple-silicon.html

There are 2x versions for download here:
https://www.citrix.com/downloads/workspace-app/mac/workspace-app-for-mac-native-support-for-silicon-mac.html
including Version: 23.01.0.53 (2301) which matches the latest Intel build available in this Cask: https://www.citrix.com/downloads/workspace-app/mac/workspace-app-for-mac-latest.html

I would update `citrix-workspace.rb` myself, but I could not find a direct download URL counterpart to the Intel installer: https://downloadplugins.citrix.com/Mac/CitrixWorkspaceApp.dmg currently used in the formula. 

See this article https://support.citrix.com/article/CTX338523/is-there-a-direct-and-unattended-download-url-for-the-latest-citrix-workspace-app-version

Is there another way to get a direct download URL so the formula can be updated?

### Command that failed

brew install --cask citrix-workspace

### Output of command with `--verbose --debug`

```shell
N/A
```

### Output of `brew doctor` and `brew config`

```shell
❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.

❯ brew config
HOMEBREW_VERSION: 4.0.1-58-g82a36d2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 82a36d24fb96129fd0f398dbb5492a16a03244b7
Last commit: 17 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 452e1e125b45d68f8bf37852457bbe34a1e4debf
Core tap last commit: 8 hours ago
Core tap branch: master
Core tap JSON: 18 Feb 09:45 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.NZcDTqOOhE/org.xquartz:0
HOMEBREW_EDITOR: emacsclient -t --alternate-editor=
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 14.0.0 build 1400
Git: 2.39.2 => /opt/homebrew/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false
```

### Output of `brew tap`

```shell
❯ brew tap
github/gh
homebrew/bundle
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
sticklerm3/pourhouse
teamookla/speedtest
```

**Comment by miccal** [comment]
I am not sure what we can do without a `url` that accepts `curl` requests.

This is the only one I can find for now, which is awful:
```
|-> curl -sLI https://downloads.citrix.com/21623/CitrixWorkspaceApp.dmg?__gda__=exp=1676876631~acl=/*~hmac=3680dd20fc06bbe179885e4f95b7b2e4e1d056ef1c48137d1fbd4e4ec7f6dda0
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 415562656
ETag: "26b157aa58e69ff4bf221064d45aa364:1673438845.047497"
Last-Modified: Wed, 11 Jan 2023 11:56:29 GMT
Server: AkamaiNetStorage
Date: Mon, 20 Feb 2023 06:04:11 GMT
Connection: keep-alive
content-disposition: attachment; filename=CitrixWorkspaceApp.dmg
Content-Type: application/octet-stream
```

Also note that:
```
|-> curl -sLI https://downloads.citrix.com/21623/CitrixWorkspaceApp.dmg
HTTP/1.1 403 Forbidden
Server: AkamaiGHost
Mime-Version: 1.0
Content-Length: 176
Expires: Mon, 20 Feb 2023 06:04:34 GMT
Date: Mon, 20 Feb 2023 06:04:34 GMT
Connection: keep-alive
content-disposition: attachment; filename=CitrixWorkspaceApp.dmg
Content-Type: application/octet-stream
```

**Comment by christopinka** [comment]
this is my cmd line

```bash

% brew install citrix-workspace
==> Downloading https://downloadplugins.citrix.com/Mac/CitrixWorkspaceApp.dmg
######################################################################## 100.0%
Warning: No checksum defined for cask 'citrix-workspace', skipping verification.
==> Installing Cask citrix-workspace
==> Running installer for citrix-workspace; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
Password:
Sorry, try again.
Password:
installer: Package name is Citrix Workspace
installer: Installing at base path /
installer: The install was successful.
🍺  citrix-workspace was successfully installed!

```

a couple problems


1) no checksum? 
2) why is base path not /opt/homebrew?

**Comment by felker** [comment]
@miccal I actually get `HTTP/1.1 403 Forbidden` for both of those URLs. 
Inspecting the element for the download button gives me a functional URL: ```https://downloads.citrix.com/21623/CitrixWorkspaceApp.dmg?__gda__=exp=1676944463~acl=/*~hmac=ad92ed3dafc48e89233edeaac2bd2f0768c1190751912bef2baaf39b86e5a5d9
```
I am no webdev, but I suppose these types of URLs are only valid for a short time and/or a certain set of clients.

I am hoping to put in a ticket with Citrix soon to get a direct link.

**Comment by miccal** [comment]
> I am hoping to put in a ticket with Citrix soon to get a direct link. 

That would be great, thank you @felker.

**Comment by miccal** [comment]
> Installation prompts for Rosetta install required for printing?. If Rosetta is required can it be part of the formula? Is there a separate formula for native support? I'm on an M1 mac. thanks

No there is not currently a separate installer for arm -- that is why this issue was created.

**Comment by miccal** [comment]
> 1. no checksum?

No, since the `url` is not versioned.

> 2. why is base path not /opt/homebrew?

Read the output:
```
Package installers may write to any location; options such as `--appdir` are ignored.
```

**Comment by felker** [comment]
I was unable to open a support ticket, but I did post in their forums: https://discussions.citrix.com/topic/418270-need-direct-download-url-for-apple-siliconuniversal-2-binary/

If folks want to upvote the post in the hopes that it gets some attention from Citrix, that might be helpful.
