### ISSUE TITLE
No file found - failure to upgrade (multiple casks affected)

### ISSUE THREAD

**Issue by georgettica** [Homebrew/homebrew-cask#141436]
the issue happens also in `brew outdated`

```
brew uninstall gimp
Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/cc58401c0905753619a9fc12dc733518beb75b05/Casks/gimp.rb
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/api.rb:105:in `fetch_file_source'
/opt/homebrew/Library/Homebrew/api/cask.rb:20:in `fetch_source'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:236:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:376:in `load'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:129:in `load_formula_or_cask'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:57:in `block in to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:56:in `each'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:56:in `flat_map'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:56:in `to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:273:in `to_kegs_to_casks'
/opt/homebrew/Library/Homebrew/cmd/uninstall.rb:48:in `uninstall'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

**Comment by carlocab** [comment]
What is the output of `brew config` and `brew doctor`?

**Comment by nosnilmot** [comment]
This appears to be a github issue, https://github.com/Homebrew/homebrew-cask/blob/cc58401c0905753619a9fc12dc733518beb75b05/Casks/gimp.rb is returning 500 errors intermittently too.

**Comment by djerfy** [comment]
Same error with other pkg (proxyman, gpg-suite, wireshark, ...) (autoremove, upgrade, uninstall)

**Comment by effleurager** [comment]
Also affects `intellij-idea-ce`
```
Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/cc58401c0905753619a9fc12dc733518beb75b05/Casks/intellij-idea-ce.rb
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/api.rb:105:in `fetch_file_source'
/usr/local/Homebrew/Library/Homebrew/api/cask.rb:20:in `fetch_source'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:236:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:376:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:50:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:46:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:46:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:98:in `upgrade_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:226:in `upgrade_outdated_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:117:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

**Comment by kranack** [comment]
Same here for `klogg`

```
Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/cc58401c0905753619a9fc12dc733518beb75b05/Casks/klogg.rb
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/api.rb:105:in `fetch_file_source'
/usr/local/Homebrew/Library/Homebrew/api/cask.rb:20:in `fetch_source'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:236:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:376:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:50:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:46:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:46:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:98:in `upgrade_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:226:in `upgrade_outdated_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:117:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

**Comment by effleurager** [comment]
> https://raw.githubusercontent.com/Homebrew/homebrew-cask/cc58401c0905753619a9fc12dc733518beb75b05/Casks/intellij-idea-ce.rb

`brew config`
```
HOMEBREW_VERSION: 4.0.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6f195c1e6fd29a6574dbe94428ae4c3324863aa5
Last commit: 7 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c27f57133838d853c5114fbce01dd678ba6db0e2
Core tap last commit: 3 weeks ago
Core tap branch: master
Core tap JSON: 16 Feb 09:56 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vi
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 14.0.0 build 1400
Git: 2.39.2 => /usr/local/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
```

`brew doctor`
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have uncommitted modifications to Homebrew/homebrew-cask-fonts.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts && git stash -u && git clean -d -f

Uncommitted files:
   M Casks/font-fira-mono-nerd-font.rb
```

Interestingly enough, running `brew update-reset` causes brew to wait infinitely (or longer than 5 minutes without any CPU activity)

**Comment by adriweb** [comment]
Also affects `osxfuse`

**Comment by d-led** [comment]
currently getting lots of 404 errors on other formulae as well

**Comment by xmollv** [comment]
Yeah we're getting the same error with `cocoapods`. Maybe the recent 4.0.0 release of `brew` broke it?

**Comment by augusl** [comment]
`Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/cc58401c0905753619a9fc12dc733518beb75b05/Casks/ngrok.rb
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/api.rb:105:in `fetch_file_source'
/usr/local/Homebrew/Library/Homebrew/api/cask.rb:20:in `fetch_source'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:236:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:376:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:50:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:46:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:46:in `casks'
/usr/local/Homebrew/Library/Homebrew/cmd/outdated.rb:190:in `outdated_formulae_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/outdated.rb:84:in `outdated'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'`

**Comment by AlekSi** [comment]
There is a workaround, found at https://github.com/Homebrew/brew/issues/14542

```sh
export HOMEBREW_NO_INSTALL_FROM_API=1
```

**Comment by d-led** [comment]
> There is a workaround, found at [Homebrew/brew#14542](https://github.com/Homebrew/brew/issues/14542)
> 
> ```shell
> export HOMEBREW_NO_INSTALL_FROM_API=1
> ```
> 
> That _seems_ to be a direct result of 4.0.0 release: https://brew.sh/2023/02/16/homebrew-4.0.0/

thx

**Comment by randpop** [comment]
Same issue here since this morning. Seems to be only a problem with casks.
Could this be because of some changes in the 4.0 release?

Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/cc58401c0905753619a9fc12dc733518beb75b05/Casks/adobe-creative-cloud.rb
Please report this issue: https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/api.rb:105:in `fetch_file_source'
/usr/local/Homebrew/Library/Homebrew/api/cask.rb:20:in `fetch_source'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:236:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:376:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:50:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:46:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:46:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:98:in `upgrade_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:226:in `upgrade_outdated_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:117:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'

**Comment by solrevdev** [comment]
Thanks! this worked for me too 🙏🏼️
 
> There is a workaround, found at [Homebrew/brew#14542](https://github.com/Homebrew/brew/issues/14542)
> 
> ```shell
> export HOMEBREW_NO_INSTALL_FROM_API=1
> ```
> 
> That _seems_ to be a direct result of 4.0.0 release: https://brew.sh/2023/02/16/homebrew-4.0.0/ Weirdly, is says:
> 
> > […] the `HOMEBREW_INSTALL_FROM_API` variable has been removed and is a no-op
> > If you wish to opt-out of this behaviour change, you can `export HOMEBREW_NO_INSTALL_FROM_API=1`
> 
> I guess the first sentence is wrong because that workaround worked for me 🤷

**Comment by randpop** [comment]
> Same issue here since this morning. Seems to be only a problem with casks. Could this be because of some changes in the 4.0 release?
> 
> ```
> Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/cc58401c0905753619a9fc12dc733518beb75b05/Casks/adobe-creative-cloud.rb
> Please report this issue: https://docs.brew.sh/Troubleshooting
> /usr/local/Homebrew/Library/Homebrew/api.rb:105:in `fetch_file_source'
> /usr/local/Homebrew/Library/Homebrew/api/cask.rb:20:in `fetch_source'
> /usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:236:in `load'
> /usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:376:in `load'
> /usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:50:in `block in casks'
> /usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:46:in `map'
> /usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:46:in `casks'
> /usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:98:in `upgrade_casks'
> /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:226:in `upgrade_outdated_casks'
> /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:117:in `upgrade'
> /usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
> ```

Hmmm... I changed nothing and now it runs thru all the process like a charm.

**Comment by carlocab** [comment]
GitHub has pushed a mitigation on their side. Please let us know if you're still having this problem. You'll need to do `unset HOMEBREW_NO_INSTALL_FROM_API` to try to trigger it.

**Comment by SMillerDev** [comment]
```
Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/cc58401c0905753619a9fc12dc733518beb75b05/Casks/parallels.rb
```
Still have it here.

**Comment by thanosz** [comment]
Still have the problem
```
# brew upgrade
Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/cc58401c0905753619a9fc12dc733518beb75b05/Casks/firefox.rb
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/api.rb:105:in `fetch_file_source'
/opt/homebrew/Library/Homebrew/api/cask.rb:20:in `fetch_source'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:236:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:376:in `load'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:50:in `block in casks'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:46:in `map'
/opt/homebrew/Library/Homebrew/cask/caskroom.rb:46:in `casks'
/opt/homebrew/Library/Homebrew/cask/cmd/upgrade.rb:98:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:226:in `upgrade_outdated_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:117:in `upgrade'
```

**Comment by adriweb** [comment]
Problem disappeared for `osxfuse`, but now is on `meld`

**Comment by jj1bdx** [comment]
I've found keybase cask fails to download.

```
brew update && brew upgrade
Already up-to-date.
Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/cc58401c0905753619a9fc12dc733518beb75b05/Casks/keybase.rb
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/api.rb:105:in `fetch_file_source'
/usr/local/Homebrew/Library/Homebrew/api/cask.rb:20:in `fetch_source'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:236:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:376:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:50:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:46:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:46:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:98:in `upgrade_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:226:in `upgrade_outdated_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:117:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

**Comment by kunish** [comment]
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/17328586/219347654-64d8c2ef-5506-49ef-8343-025d6a46f527.png">

Still for tailscale

**Comment by augusl** [comment]
`
Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/cc58401c0905753619a9fc12dc733518beb75b05/Casks/wireshark.rb
`

**Comment by solrevdev** [comment]
Same error different cask for me 

```bash
▲ ~ unset HOMEBREW_NO_INSTALL_FROM_API;
brew update
brew upgrade
Already up-to-date.
==> Downloading https://formulae.brew.sh/api/formula.json

==> Downloading https://formulae.brew.sh/api/cask.json

Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/cc58401c0905753619a9fc12dc733518beb75b05/Casks/inkscape.rb
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/api.rb:105:in `fetch_file_source'
/usr/local/Homebrew/Library/Homebrew/api/cask.rb:20:in `fetch_source'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:236:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:376:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:50:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:46:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:46:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:98:in `upgrade_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:226:in `upgrade_outdated_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:117:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

**Comment by therealvio** [comment]
I too am also getting a similar error, with gimp:

```
>brew remove gimp
Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/cc58401c0905753619a9fc12dc733518beb75b05/Casks/gimp.rb
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/api.rb:105:in `fetch_file_source'
/opt/homebrew/Library/Homebrew/api/cask.rb:20:in `fetch_source'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:236:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:376:in `load'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:129:in `load_formula_or_cask'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:57:in `block in to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:56:in `each'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:56:in `flat_map'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:56:in `to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:273:in `to_kegs_to_casks'
/opt/homebrew/Library/Homebrew/cmd/uninstall.rb:48:in `uninstall'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

**Comment by andrewcrook** [comment]
@therealvio 

Yeah corrected, it is a workaround. I since updated my comment. 
I just wanted to get the post out there as a correction to carlocab’s post ASAP.

**Comment by MikeMcQuaid** [comment]
> Though this seems more like a workaround than a fix.

We're working on a real/better fix.

**Comment by gabrielwhite** [comment]
Seems to be fixed for me after running `brew update`

**Comment by solrevdev** [comment]
> Seems to be fixed for me after running `brew update`

Same here 

```bash
▲ ~ brew update
Already up-to-date.
▲ ~ brew upgrade
==> Downloading https://formulae.brew.sh/api/formula.json

==> Downloading https://formulae.brew.sh/api/cask.json

▲ ~ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  q
  sxiv
▲ ~
```

**Comment by randpop** [comment]
> Seems to be fixed for me after running `brew update`

Same here.
