### ISSUE TITLE
libreoffice 7.5 now requires at least macos 10.14

### ISSUE THREAD

**Issue by peterdd** [Homebrew/homebrew-cask#141997]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

The cask lets install libreoffice 7.5 on old mac with high sierra, but starting the program claims to need at least 10.14.

So for old macbooks with 10.13  it is needed to uninstall 7.5 and use the previous libreoffice.rb with 7.4.5 version.

https://wiki.documentfoundation.org/ReleaseNotes/7.5

It would be nice to be able to pin also casks as the list gets longer (virtualbox, vagrant, .., libreoffice)

### Command that failed

-

### Output of command with `--verbose --debug`

```shell
-
```

### Output of `brew doctor` and `brew config`

```shell
-
```

### Output of `brew tap`

```shell
-
```

**Comment by miccal** [comment]
Thank you for letting us know @peterdd.

You can install `libreofffice-still` from the `homebrew-cask-versions` repository -- that one works on MacOS 10.13.

https://github.com/Homebrew/homebrew-cask-versions/pull/16051
