### ISSUE TITLE
ghidra: no support for Apple Silicon in releases

### ISSUE THREAD

**Issue by lnchan** [Homebrew/homebrew-cask#142048]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

The official releases of Ghidra do not ship with any `aarch64-apple-darwin` binaries. Those binaries (the demangler, the decompile, Sleigh, and others) are vital parts of Ghidra's functionality. While Apple Silicon is said to be supported, there seems [to be no intention to ship releases for Apple Silicon as of now](https://github.com/NationalSecurityAgency/ghidra/issues/4652#issuecomment-1446758698).

Using Rosetta 2 is a solution, but considering native binaries for Apple Silicon could be built, it seems like a waste. Please note that, unless Rosetta 2 is installed, Ghidra is mostly useless in its current state on Apple Silicon; and macOS does not offer to install Rosetta 2 when those CLI binaries are launched. This only results in an error in Ghidra, from the operating system, explaining that the binary is not supported by this architecture.

Ghidra would be more fit as a formulae, considering the requirement to build such binaries on macOS for Apple Silicon.

### Command that failed

ghidraRun / internal binaries

### Output of command with `--verbose --debug`

```shell
N/A
```

### Output of `brew doctor` and `brew config`

```shell
helene ~> brew doctor
Your system is ready to brew.

helene ~> brew config
HOMEBREW_VERSION: 4.0.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4d0154fa7926e8a7b06e9b074dd45957e820407c
Last commit: 7 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 25be650e536c44d8294ad15be81243c14aeff69d
Core tap last commit: 11 days ago
Core tap branch: master
Core tap JSON: 27 Feb 19:16 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_UPDATE_REPORT_ALL_FORMULAE: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.1 => /opt/homebrew/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false
```

### Output of `brew tap`

```shell
helene ~> brew tap
homebrew/cask
homebrew/core
```

**Comment by miccal** [comment]
Thank you for letting us know @lnchan, I have opened a PR for the Cask indicating that Rosetta is required.

Please see https://github.com/Homebrew/homebrew-core/pull/37656 for reasons why this is a Cask and not a Formula.

**Comment by carlocab** [comment]
> Please see https://github.com/Homebrew/homebrew-core/pull/37656 for reasons why this is a Cask and not a Formula.

I think Homebrew/homebrew-core#37656 is outdated; Ghidra should now be fully open-source.

**Comment by miccal** [comment]
@lnchan please feel free to open a PR in `homebrew-core` to submit `ghidra` as a Formula.
