### ISSUE TITLE
cask Godot Mono 4.0  no more need mono dependency

### ISSUE THREAD

**Issue by eeoun** [Homebrew/homebrew-cask#142184]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

At This PR #142167 bump cask `godot mono`  to version 4.0 

But the 4.0 of godto mono actually need a new dependency  `dotnet 6.0` and no more need dependency `mono`.

will submit a PR later.

### Command that failed

brew install --cask  godot-mono

### Output of command with `--verbose --debug`

```shell
N/A
```

### Output of `brew doctor` and `brew config`

```shell
N/A
```

### Output of `brew tap`

```shell
N/A
```

**Comment by SMillerDev** [comment]
Already fixed
