### ISSUE TITLE
Cask brightness supports i386/ppc, unusable on modern Mac

### ISSUE THREAD

**Issue by zhangyoufu** [Homebrew/homebrew-cask#142206]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

I tried to install `brightness` from homebrew-cask. Found that this app is totally unusable. Its Mach-O executable contains PowerPC / i386 image. I was not able to get this application run on my Intel MacBook with macOS Ventura 13.2.1 (22D68).

```
% /Applications/Brightness.app/Contents/MacOS/Brightness
zsh: bad CPU type in executable: /Applications/Brightness.app/Contents/MacOS/Brightness
```

I think this cask should be removed from repo. Or at least leave a warning that it's obsolete.

### Command that failed

# not related

### Output of command with `--verbose --debug`

```shell
# not related
```

### Output of `brew doctor` and `brew config`

```shell
# not related
```

### Output of `brew tap`

```shell
# not related
```

**Comment by carlocab** [comment]
https://github.com/Homebrew/homebrew-cask/blob/575064b7880af525a713c4a4f9d8390ccc692967/doc/faq/closing_issues_without_review.md#if-your-issue-was-closed-without-review
