### ISSUE TITLE
brew install --cask does not follow the rb file

### ISSUE THREAD

**Issue by wshuail** [Homebrew/homebrew-cask#143149]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

I changed the parallels.rb file
`git checkout 6812a3672932eefb2e049cfc1eead66c72a2a49f parallels.rb`
so it was supposed to install the old version, but 
`brew install --cask parallels `
always trying to install the latest version...

### Command that failed

brew install --cask parallels

### Output of command with `--verbose --debug`

```shell
NA
```

### Output of `brew doctor` and `brew config`

```shell
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have uncommitted modifications to Homebrew/homebrew-cask.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask && git stash -u && git clean -d -f

Uncommitted files:
  M  Casks/parallels.rb

brew config

HOMEBREW_VERSION: 4.0.6-126-g1a72b86
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1a72b861c36701e386e5acb2604b36398c8b382f
Last commit: 10 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fd36a7664a20aa17f26c7cf3c5712ed0600c9c0b
Core tap last commit: 8 minutes ago
Core tap branch: master
Core tap JSON: 16 Mar 09:09 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit skylake
Clang: 14.0.0 build 1400
Git: 2.39.2 => /usr/local/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6.3-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
```

### Output of `brew tap`

```shell
homebrew/cask
homebrew/core
```

**Comment by carlocab** [comment]
Use `brew extract` to extract it into your own tap (which you can create with `brew tap-new`).

**Comment by SMillerDev** [comment]
No, Homebrew uses the API for installs since 4.0: https://brew.sh/2023/02/16/homebrew-4.0.0/
