### ISSUE TITLE
Opening ParaView from command line after brew install returns `qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""`

### ISSUE THREAD

**Issue by mgenet** [Homebrew/homebrew-cask#143475]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

After brew installing ParaView on MacOS, and trying to open it from the command line, I am getting the following error:
```
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```
Am I doing something wrong? Thank you in advance?

### Command that failed

paraview&

### Output of command with `--verbose --debug`

```shell
N/A
```

### Output of `brew doctor` and `brew config`

```shell
N/A
```

### Output of `brew tap`

```shell
N/A
```

**Comment by miccal** [comment]
Please post the output of `brew list | grep qt`.

**Comment by mgenet** [comment]
```
pyqt
***@***.***
qt
***@***.***
```

**Comment by miccal** [comment]
Since you have `qt` installed, I am not sure what else to suggest.

**Comment by miccal** [comment]
Ping @carlocab who may be able to suggest someone from `hoembrew-core` with more `qt` experience than myself.
