### ISSUE TITLE
google-cloud-sdk zsh autocompletion doesn't load automatically

### ISSUE THREAD

**Issue by hayatofujii** [Homebrew/homebrew-cask#143596]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`. -> not really applicable
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

For some reason, `google-cloud-sdk` zsh autocompletion is linked to `$(brew --prefix)/share/zsh/site-functions`, as shown in `brew info google-cloud-sdk`:

```
==> Artifacts
[snip for brevity]
google-cloud-sdk/completion.zsh.inc -> /opt/homebrew/share/zsh/site-functions/_google-cloud-sdk (Binary)
[snip for brevity]
```

Following the [instructions about shell completion](https://docs.brew.sh/Shell-Completion), logging out and relogin doesn't autocomplete `gcloud` commands.

I'm fully aware of the caveat, and, by doing that, makes gcloud autocompletion work (thou I prefer sourcing from `$(brew --prefix)/share/zsh/site-functions`):

```
==> Caveats
To add gcloud components to your PATH, add this to your profile:
[snip]
  for zsh users
    source "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc"
[snip]
```

In conclusion, what's the point of the `google-cloud-sdk/completion.zsh.inc` artifact?

### Command that failed

`gcloud <Tab>`

### Output of command with `--verbose --debug`

```shell
not applicable
```

### Output of `brew doctor` and `brew config`

```shell
$ brew doctor
Your system is ready to brew.

$ brew config
HOMEBREW_VERSION: 4.0.9-35-g65d858d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 65d858da123dda54784a7b374605b6eb1a699882
Last commit: 4 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9432bb87026504e5992adb68570c408aed3caef6
Core tap last commit: 19 minutes ago
Core tap branch: master
Core tap JSON: 22 Mar 23:25 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.40.0 => /opt/homebrew/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false
```

### Output of `brew tap`

```shell
$ brew tap
dart-lang/dart
homebrew/cask
homebrew/cask-versions
homebrew/core
homebrew/services
leoafarias/fvm
playcover/playcover
```

**Comment by hayatofujii** [comment]
Just realized that there are two scripts; one `path.zsh.inc` and `completion.zsh.inc`. I've source'd path.zsh.inc and the behavior stays the same.

**Comment by miccal** [comment]
Ping @lucaong.

**Comment by hayatofujii** [comment]
Hi @razvanazamfirei, thanks for the reply!

These are the first couple of lines in my `.zshrc` file:

```
# zsh
export CLICOLOR=1
PS1="[%n@%m %1~] %(!.#.$) "

# homebrew-installed completions
if type brew &>/dev/null
then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

  autoload -Uz compinit
  compinit
fi
```

**Comment by lucaong** [comment]
I do not have much to add to what @razvanazamfirei already correctly said.

I double-checked that completion works for `gcloud` when adding `$(brew --prefix)/share/zsh/site-functions` to `$fpath` (or `$FPATH`), and that works for me. I am sorry I cannot help much here.

**Comment by razvanazamfirei** [comment]
Hi @hayatofujii, 

I would suggest running `compaudit` (you may need to `set -x` before to have the output visible). Double-check that your `_i_files` contain `_google-cloud-sdk`. If it does, the completions are visible to `zsh`. You can also test if other brew installed completions are working (e.g. `fd` if installed) 
``` zsh
+compaudit:57> _i_wdirs=( )
+compaudit:58> _i_wfiles=( )
+compaudit:60> _i_files=( /opt/homebrew/share/zsh/site-functions/_asdf 
/opt/homebrew/share/zsh/site-functions/_atuin /opt/homebrew/share/zsh/site-functions/_google-cloud-sdk ... )
```
The one caveat is that the `zsh` completions for the cask look like they could use some improvement and may need to be sourced directly. I would also double-check that `python` is available.

As it doesn't seem like this is a `brew` issue, rather an issue with Google's provided completions, I'll close this for now. If there's an issue we can resolve, please let us know.

**Comment by takanuva15** [comment]
I am dealing with this issue too - after reading this thread, I added the following line to my `~/.zshrc` file and then ran `. ~/.zshrc` and the autocomplete started working:
```
source "$(brew --prefix)/share/google-cloud-sdk/completion.zsh.inc"
```

**Comment by razvanazamfirei** [comment]
@takanuva Thanks for confirming! 👍

**Comment by hayatofujii** [comment]
@razvanazamfirei  `_google_cloud_sdk` is in fact listed in `_i_files`. And, for some reason, `python` was not working on my system, only `python3`, but fixing that still didn't work out.

I figured something out: the completion script is missing the compdef line as [required by zsh](https://zsh.sourceforge.io/Doc/Release/Completion-System.html#Autoloaded-files). If someone adds `#compdef gcloud` as the first line on the script, autocompletion works.

**Comment by takanuva15** [comment]
@hayatofujii I was about to say to just raise a PR lol, but I realized the sdk is probably closed-source. Is there a gcloud-cli bug tracker we could post your fix to?

**Comment by hayatofujii** [comment]
@takanuva15 The SDK is Apache licensed. Think I'm going to PR it like [aur does it](https://aur.archlinux.org/cgit/aur.git/tree/0003-add-compdef-to-zsh-completion.patch?h=google-cloud-cli).
