### ISSUE TITLE
SHA56 Hash for TouchOSC Bridge changed

### ISSUE THREAD

**Issue by vale** [Homebrew/homebrew-cask#143887]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

SHA256 Hash for TouchOSC Bridge changed without changing the version number. Since the Hash on the developers [website](https://hexler.net/pub/touchosc/touchosc-bridge-1.7.3.152-macos.dmg.sha) matches with the output I get from brew for the actual hash, this should be updated in my opinion.

### Command that failed

brew install --cask touchosc-bridge

### Output of command with `--verbose --debug`

```shell
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading touchosc-bridge
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://hexler.net/pub/touchosc/touchosc-bridge-1.7.3.152-macos.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.10\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://hexler.net/pub/touchosc/touchosc-bridge-1.7.3.152-macos.dmg
Already downloaded: /Users/vale/Library/Caches/Homebrew/downloads/d6230bba3c2bc82d21289b2b60ec220291163fa0a76db714c354dd3a2f569853--touchosc-bridge-1.7.3.152-macos.dmg
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target x86_64-apple-macosx12 /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Unknown support status
==> Verifying checksum for cask 'touchosc-bridge'
Error: SHA256 mismatch
Expected: eb5b4f24488c0298933fbe1aff8d634cc15dab0083709eef55aa17e913e89f7a
  Actual: fcc6d30e0c2fff5031c6ca8fa731fff832e0f0bb39e370c961b35d0d291c725a
    File: /Users/vale/Library/Caches/Homebrew/downloads/d6230bba3c2bc82d21289b2b60ec220291163fa0a76db714c354dd3a2f569853--touchosc-bridge-1.7.3.152-macos.dmg
To retry an incomplete download, remove the file above.
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:292:in `verify_checksum'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:68:in `verify_download_integrity'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:33:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:176:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:71:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:102:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:109:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:108:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:108:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:188:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
This does not seem relevant for this issue.
```

### Output of `brew tap`

```shell
This does not seem relevant for this issue.
```

**Comment by vale** [comment]
The line that should be updated is:  https://github.com/Homebrew/homebrew-cask/blob/0a3f917313825bc1025fd3dc016924d20d9fcfae/Casks/touchosc-bridge.rb#L3

**Comment by SMillerDev** [comment]
So definitelty didn't follow:
> I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).

or
> I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

**Comment by vale** [comment]
So this is a wont fix even if the checksum did change for real?

You could read my message and check the website first before closing the issue and telling me I should have followed the instructions.
Yes it is a Checksum does not match error but it is not the kind described in the instructions. The issue is not with my download but rather with the vendor changing the download.

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/144220

**Comment by bevanjkay** [comment]
@vale The documentation asks that you try to [submit a fix](https://github.com/Homebrew/homebrew-cask/blob/HEAD/CONTRIBUTING.md#updating-a-cask) in these instances and detail where that you got stuck if you were unsuccessful.

**Comment by SMillerDev** [comment]
> The issue is not with my download but rather with the vendor changing the download.

As is described in the instructions 

> So this is a wont fix even if the checksum did change for real?

Not unless you follow the instructions and submit a fix
