### ISSUE TITLE
Mochi doesn't install arm binaries on M1/M2

### ISSUE THREAD

**Issue by t1u1** [Homebrew/homebrew-cask#145642]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

The `mochi` cask currently installs Intel binary on my M2 mini.

https://github.com/Homebrew/homebrew-cask/blob/master/Casks/mochi.rb

However, arm binaries are available:
https://mochi.cards/releases/Mochi-1.15.21-arm64.dmg

Source: https://twitter.com/MochiCardsApp/status/1647987221872476162

### Command that failed

NA

### Output of command with `--verbose --debug`

```shell
NA
```

### Output of `brew doctor` and `brew config`

```shell
NA
```

### Output of `brew tap`

```shell
NA
```

**Comment by SMillerDev** [comment]
Please make a pull request to resolve this.

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/145643
