### ISSUE TITLE
brew install app not compatible with M1

### ISSUE THREAD

**Issue by zirawell** [Homebrew/homebrew-cask#145913]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

I have tried install one-switch with the command `brew install --cask one-switch`.
It can only download the app for intel. But I can manually get the universal app for M1 from their official website.
The problem is reproducible across my two devices with M1 chip.

### Command that failed

brew install --cask one-switch

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading one-switch
==> Cask::Installer#install
Warning: Cask 'one-switch' is already installed.

To re-install one-switch, run:
  brew reinstall --cask one-switch
```

### Output of `brew doctor` and `brew config`

```shell
➜ brew doctor
Your system is ready to brew.
➜ brew config
HOMEBREW_VERSION: 4.0.15-61-g512d7c9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 512d7c961386649f169d9d495dee0ea736ba867a
Last commit: 3 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8fdf72686c9345f0586d1e7ab51a4269466002c3
Core tap last commit: 56 minutes ago
Core tap branch: master
Core tap JSON: 26 Apr 14:32 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
http_proxy: http://127.0.0.1:7890
https_proxy: http://127.0.0.1:7890
no_proxy: localhost,127.0.0.1,localaddress,.localdomain.com
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.3
Rosetta 2: false
```

### Output of `brew tap`

```shell
➜ brew tap
blacktop/tap
homebrew/bundle
homebrew/cask
homebrew/core
```

**Comment by SMillerDev** [comment]
> It can only download the app for intel. But I can manually get the universal app for M1 from their official website.
> The problem is reproducible across my two devices with M1 chip.

Please make a pull request for this, the issue template is for bugs, not feature requests.
