### ISSUE TITLE
Attempting to install new cask bookletcreator fails with an error and "Please report this issue"

### ISSUE THREAD

**Issue by jmonschke-splunk** [Homebrew/homebrew-cask#146287]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

 brew install bookletcreator
Error: private method `download_name' called for #<Cask::Download:0x00007f838e5b8da8>
Did you mean?  downloader
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:612:in `initialize'
/usr/local/Homebrew/Library/Homebrew/downloadable.rb:89:in `new'
/usr/local/Homebrew/Library/Homebrew/downloadable.rb:89:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/downloadable.rb:86:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:51:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:174:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:69:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:100:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:237:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:228:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:228:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'

### Command that failed

brew install bookletcreator

### Output of command with `--verbose --debug`

```shell
brew install bookletcreator --verbose --debug
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading bookletcreator
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.16-2-gcdc5463\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.3.1\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://www.bookletcreator.com/files/BookletCreator-2.0.5.dmg
Error: private method `download_name' called for #<Cask::Download:0x00007fe2f3dd1e08>
Did you mean?  downloader
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:612:in `initialize'
/usr/local/Homebrew/Library/Homebrew/downloadable.rb:89:in `new'
/usr/local/Homebrew/Library/Homebrew/downloadable.rb:89:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/downloadable.rb:86:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:51:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:174:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:69:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:100:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:237:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:228:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:228:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libDellMonitorSdkLib.dylib
======================================================
brew config
HOMEBREW_VERSION: 4.0.16-2-gcdc5463
ORIGIN: https://github.com/Homebrew/brew
HEAD: cdc54636ee201cfaf7fe1a0148aaf8c29ad65dad
Last commit: 2 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 551af78867cb6f8377687483f5ca3cda6199357d
Core tap last commit: 25 minutes ago
Core tap branch: master
Core tap JSON: 01 May 18:48 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_AUTOREMOVE: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.4isdDVahcU/org.xquartz:0
HOMEBREW_EDITOR: /usr/local/bin/nvim
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_NO_GOOGLE_ANALYTICS: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.40.0 => /usr/local/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-x86_64
CLT: N/A
Xcode: 14.3
```

### Output of `brew tap`

```shell
brew tap
homebrew/cask
homebrew/cask-fonts
homebrew/core
homebrew/services
splunk/tap
toolbox/tap
```

**Comment by Bo98** [comment]
I've fixed this error now. You may still get another error (the error was happening in code that only executed if the download fails), but it should be clearer what's going on this time.
