### ISSUE TITLE
install anaconda do need sudo unlike miniconda?

### ISSUE THREAD

**Issue by moongi-simon-hong** [Homebrew/homebrew-cask#146531]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

brew install --cask anaconda
-> need password for sudo
brew install --cask miniconda
-> need no password for sudo

as stated in brew documentation. 
using brew should not require sudo(https://docs.brew.sh/FAQ#why-does-homebrew-say-sudo-is-bad)

in miniconda.rb no sudo is needed 
`installer script: {
    executable: "Miniconda3-#{version}-MacOSX-#{arch}.sh",
    args:       ["-b", "-p", "#{caskroom_path}/base"],
  }`

but for anaconda.rb sudo is required
`installer script: {
    executable: "Anaconda3-#{version}-MacOSX-#{arch}.sh",
    args:       ["-b", "-p", "#{HOMEBREW_PREFIX}/anaconda3"],
    sudo:       true,
  }`

if sudo is not really needed, we could modify it.

### Command that failed

brew install --cask anaconda

### Output of command with `--verbose --debug`

```shell
-
```

### Output of `brew doctor` and `brew config`

```shell
-
```

### Output of `brew tap`

```shell
-
```

**Comment by razvanazamfirei** [comment]
Hi @moongi-simon-hong, 

Thank you for bringing this issue to our attention! The discussion you linked is mostly applicable to formulas. sudo is used infrequently in casks, but it's always a good idea to review whether its usage is actually required. 

If you download one of the command-line installers from [here](https://www.anaconda.com/download#downloads), are you able to install it without using sudo?

**Comment by moongi-simon-hong** [comment]
sorry for delayed response
1. for my installation, CLI installer work just fine. able to control where to install perfeclty.
2. for general discussion, I though most cask formula should not need sudo.
 - for m1 mac, /opt/homebrew is owned by user, no need for sudo
 - sudo is need for copying GUI app to /Applications folder
   - with variable set up HOMEBREW_CASK_OPTS: ["--appdir=~/Applications", "--fontdir=~/Library/Fonts"] 
   - cask does not need sudo unless package itself require it (this is what mentioned in orginal post)
 - (solution?) at least two brew installation of conda (miniconda and anaconda) should behave same. 
   - both should not require sudo (what i suggest)
   - both require sudo

**Comment by razvanazamfirei** [comment]
Thank you, @moongi-simon-hong. I submitted a PR removing sudo from anaconda.

**Comment by razvanazamfirei** [comment]
Removing sudo does not work on Intel since you need sudo to `mkdir /usr/local/anaconda3`
Looks like miniconda does not create that directory there which is why sudo is not necessary. This is a limitation of their installation process. If miniconda does not require sudo, we will not run the install script with it.
