### ISSUE TITLE
downgrade mysqlworkbench on monterey to 8.0.31, as 8.0.32 has a query bug

### ISSUE THREAD

**Issue by lishoujun** [Homebrew/homebrew-cask#146780]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

mysqlworkbench 8.0.32 [cant not query anything](https://stackoverflow.com/questions/75288854/mysql-workbench-8-0-32-ce-crashes-on-macos-monterey-12-6-3) and 8.0.33 not support monterey anymore. 
code position:
https://github.com/Homebrew/homebrew-cask/blob/master/Casks/mysqlworkbench.rb#L43
```
  on_monterey do
    version "8.0.32"
```
change to  
```
  on_monterey do
    version "8.0.31"
```

I would submit a pr myself, but I don't know how to test my forked-repo local.  sorry to disturb you.

Regards,
Barry (Shoujun Li)

### Command that failed

None

### Output of command with `--verbose --debug`

```shell
None
```

### Output of `brew doctor` and `brew config`

```shell
None
```

### Output of `brew tap`

```shell
None
```

**Comment by SMillerDev** [comment]
Did MySQL actually pull that release?

**Comment by lishoujun** [comment]
@SMillerDev  
Sorry my English is pool, I try to understand your comment.
- 8.0.31  work for macos monterey
- 8.0.32  have  a big big bug (I link this bug in issue description )
- 8.0.33 not work for macos monterey (I have a bug report to [mysql](https://bugs.mysql.com/bug.php?id=110944))

**Comment by SMillerDev** [comment]
Homebrew is not the team that decides the version. If a version exists and we can install it we will. Bugs are for the developers of the software to fix

**Comment by lishoujun** [comment]
@SMillerDev 
I got what you mean, and I will check what mysql side, hope they can repaire the issue.

In fact, I am a bit upset for not help other brew+mysqlworkbench+monterey users avoid this issue.  LOL
