### ISSUE TITLE
Extra file to trash for the cask `microsoft-word`

### ISSUE THREAD

**Issue by tlkahn** [Homebrew/homebrew-cask#147142]
### Verification

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

I found this plist file should be removed after I use brew remove to delete `microsoft-word`:

```
/Library/Preferences/com.microsoft.autoupdate2.plist
```

Should we added?

### Command that failed

brew remove --cask microsoft-word

### Output of command with `--verbose --debug`

```shell
N/A
```

### Output of `brew doctor` and `brew config`

```shell
N/A
```

### Output of `brew tap`

```shell
N/A
```

**Comment by miccal** [comment]
This is a file from `microsoft-auto-update`, which was installed as a dependency for `microsoft-word`. Run `brew uninstall --cask microsoft-auto-update` to remove it also.
