### ISSUE TITLE
brew upgrade --cask wechat error 

### ISSUE THREAD

**Issue by xkia** [Homebrew/homebrew-cask#147383]
### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
HOMEBREW_VERSION: 4.0.18
ORIGIN: https://github.com/Homebrew/brew
HEAD: b0dc84b117f54f6b18e0528b95477c54e409ebdd
Last commit: 5 days ago
Core tap JSON: 17 May 14:04 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.40.1 => /usr/local/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-x86_64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.3
```

### What were you trying to do (and why)?

update application 

### What happened (include all command output)?

Warning: No checksum defined for cask 'wechat', skipping verification.
Warning: It seems there is already an App at '/usr/local/Caskroom/wechat/3.8.0.17/WeChat.app'; overwriting.
。。。。
cp: /Applications/WeChat.app/Contents/Resources/appreader_play_btn.svg: No such file or directory
。。。。

Warning: No checksum defined for cask 'wechat', skipping verification.
Warning: It seems there is already an App at '/usr/local/Caskroom/wechat/3.8.0.17/WeChat.app'; overwriting.
 
backup origin WeChat.app error

### What did you expect to happen?

brew upgrade --cask wechat success
but now , You can only delete the application manually and then reinstall it.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew upgrade --cask wechat
```

**Comment by reitermarkus** [comment]
Can you post the output of `brew upgrade --cask wechat -vd`?

**Comment by xkia** [comment]
> Can you post the output of `brew upgrade --cask wechat -vd`?

https://github.com/Homebrew/brew/pull/15138  
Causing inability to update  cask applications properly on macos Version 13.4, such as wechat

**Comment by razvanazamfirei** [comment]
@xkia, thanks for flagging the issue. The output of `brew upgrade --cask wechat -vd` is still useful. It allows us to address the root of the problem not only for you, but also for other users.

**Comment by xkia** [comment]
The historical version has been deleted by me and I have reinstalled it, but there are similar exceptions. Is this information helpful？

✗  brew reinstall --cask wechat -vd                                                                                                                                                                                                                                                                                                                      ⏱ 17s at 10:19:49
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading wechat
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://dldir1.qq.com/weixin/mac/WeChatMac.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.19\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.4\)\ curl/7.88.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://dldir1.qq.com/weixin/mac/WeChatMac.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.19\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.4\)\ curl/7.88.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://dldir1.qq.com/weixin/mac/WeChatMac.dmg
Already downloaded: /Users/xkia/Library/Caches/Homebrew/downloads/661ef805a7adb62e317c3ecfc344a75977b26aef43ca4a63b3636e98049127d3--WeChatMac.dmg
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target x86_64-apple-macosx13 /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/xkia/Library/Caches/Homebrew/downloads/661ef805a7adb62e317c3ecfc344a75977b26aef43ca4a63b3636e98049127d3--WeChatMac.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/xkia/Library/Caches/Homebrew/downloads/661ef805a7adb62e317c3ecfc344a75977b26aef43ca4a63b3636e98049127d3--WeChatMac.dmg
==> /Users/xkia/Library/Caches/Homebrew/downloads/661ef805a7adb62e317c3ecfc344a75977b26aef43ca4a63b3636e98049127d3--WeChatMac.dmg is quarantined
Warning: No checksum defined for cask 'wechat', skipping verification.
/usr/bin/env hdiutil imageinfo -format /Users/xkia/Library/Caches/Homebrew/downloads/661ef805a7adb62e317c3ecfc344a75977b26aef43ca4a63b3636e98049127d3--WeChatMac.dmg
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromPathLoader): loading /usr/local/Caskroom/wechat/.metadata/3.8.0.18/20230524021949.794/Casks/wechat.json
==> Uninstalling Cask wechat
==> Uninstalling artifacts
==> 3 artifacts defined
#<Cask::ArtifactSet: {#<Cask::Artifact::Uninstall:0x00007f9637a6cb18 @cask=#<Cask wechat>, @dsl_args=[{:quit=>"com.tencent.xinWeChat"}], @directives={:quit=>"com.tencent.xinWeChat", :signal=>[]}>, #<Cask::Artifact::App:0x00007f9637a7c6f8 @cask=#<Cask wechat>, @dsl_args=["WeChat.app", {}], @source_string="WeChat.app", @target_string="">, #<Cask::Artifact::Zap:0x00007f9637aaf080 @cask=#<Cask wechat>, @dsl_args=[{:trash=>["~/Library/Application Scripts/$(TeamIdentifierPrefix)com.tencent.xinWeChat", "~/Library/Application Scripts/$(TeamIdentifierPrefix)com.tencent.xinWeChat.IPCHelper", "~/Library/Application Scripts/com.tencent.xinWeChat", "~/Library/Application Scripts/com.tencent.xinWeChat.MiniProgram", "~/Library/Application Scripts/com.tencent.xinWeChat.WeChatMacShare", "~/Library/Caches/com.tencent.xinWeChat", "~/Library/Containers/$(TeamIdentifierPrefix)com.tencent.xinWeChat.IPCHelper", "~/Library/Containers/com.tencent.xinWeChat", "~/Library/Containers/com.tencent.xinWeChat.MiniProgram", "~/Library/Containers/com.tencent.xinWeChat.WeChatMacShare", "~/Library/Cookies/com.tencent.xinWeChat.binarycookies", "~/Library/Group Containers/$(TeamIdentifierPrefix)com.tencent.xinWeChat", "~/Library/Preferences/com.tencent.xinWeChat.plist", "~/Library/Saved Application State/com.tencent.xinWeChat.savedState"]}], @directives={:trash=>["~/Library/Application Scripts/$(TeamIdentifierPrefix)com.tencent.xinWeChat", "~/Library/Application Scripts/$(TeamIdentifierPrefix)com.tencent.xinWeChat.IPCHelper", "~/Library/Application Scripts/com.tencent.xinWeChat", "~/Library/Application Scripts/com.tencent.xinWeChat.MiniProgram", "~/Library/Application Scripts/com.tencent.xinWeChat.WeChatMacShare", "~/Library/Caches/com.tencent.xinWeChat", "~/Library/Containers/$(TeamIdentifierPrefix)com.tencent.xinWeChat.IPCHelper", "~/Library/Containers/com.tencent.xinWeChat", "~/Library/Containers/com.tencent.xinWeChat.MiniProgram", "~/Library/Containers/com.tencent.xinWeChat.WeChatMacShare", "~/Library/Cookies/com.tencent.xinWeChat.binarycookies", "~/Library/Group Containers/$(TeamIdentifierPrefix)com.tencent.xinWeChat", "~/Library/Preferences/com.tencent.xinWeChat.plist", "~/Library/Saved Application State/com.tencent.xinWeChat.savedState"], :signal=>[]}>}>
==> Uninstalling artifact of class Cask::Artifact::Uninstall
/usr/bin/env osascript -l JavaScript -e \'use\ strict\'\;'
''
'ObjC.import\(\'stdlib\'\)'
''
'function\ run\(argv\)\ \{'
'\ \ try\ \{'
'\ \ \ \ var\ app\ =\ Application\(argv\[0\]\)'
'\ \ \ \ if\ \(app.running\(\)\)\ \{'
'\ \ \ \ \ \ \$.exit\(0\)'
'\ \ \ \ \}'
'\ \ \}\ catch\ \(err\)\ \{\ \}'
''
'\ \ \$.exit\(1\)'
'\}'
' com.tencent.xinWeChat
==> Post-uninstalling artifact of class Cask::Artifact::Uninstall
==> Uninstalling artifact of class Cask::Artifact::App
Warning: It seems there is already an App at '/usr/local/Caskroom/wechat/3.8.0.18/WeChat.app'; overwriting.
==> Removing App '/usr/local/Caskroom/wechat/3.8.0.18/WeChat.app'
==> Backing App 'WeChat.app' up to '/usr/local/Caskroom/wechat/3.8.0.18/WeChat.app'
/usr/bin/env /bin/cp -pR /Applications/WeChat.app /usr/local/Caskroom/wechat/3.8.0.18/WeChat.app
==> Removing App '/Applications/WeChat.app'
==> Purging files for version 3.8.0.18 of Cask wechat
==> Purging all staged versions of Cask wechat
==> Installing Cask wechat
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/xkia/Library/Caches/Homebrew/downloads/661ef805a7adb62e317c3ecfc344a75977b26aef43ca4a63b3636e98049127d3--WeChatMac.dmg
/usr/bin/env hdiutil attach -plist -nobrowse -readonly -mountrandom /private/tmp/d20230524-1850-1irxtja /Users/xkia/Library/Caches/Homebrew/downloads/661ef805a7adb62e317c3ecfc344a75977b26aef43ca4a63b3636e98049127d3--WeChatMac.dmg
/usr/bin/env find . -print0
/usr/bin/env mkbom -s -i /private/tmp/20230524-1850-1ho8m8e.list -- /private/tmp/20230524-1850-1ivdk6i.bom
/usr/bin/env ditto --bom /private/tmp/20230524-1850-1ivdk6i.bom -- /private/tmp/d20230524-1850-1irxtja/dmg.hisoMv /private/tmp/d20230524-1850-pz9jbd
/usr/bin/env diskutil info -plist /private/tmp/d20230524-1850-1irxtja/dmg.hisoMv
/usr/bin/env diskutil eject /private/tmp/d20230524-1850-1irxtja/dmg.hisoMv
/usr/bin/env cp -pR /private/tmp/d20230524-1850-pz9jbd/WeChat.app/. /usr/local/Caskroom/wechat/3.8.0.18/WeChat.app
/usr/bin/env cp -pR /private/tmp/d20230524-1850-pz9jbd/.CacheDeleteDiscardedCaches/. /usr/local/Caskroom/wechat/3.8.0.18/.CacheDeleteDiscardedCaches
==> Verifying Gatekeeper status of /Users/xkia/Library/Caches/Homebrew/downloads/661ef805a7adb62e317c3ecfc344a75977b26aef43ca4a63b3636e98049127d3--WeChatMac.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/xkia/Library/Caches/Homebrew/downloads/661ef805a7adb62e317c3ecfc344a75977b26aef43ca4a63b3636e98049127d3--WeChatMac.dmg
==> /Users/xkia/Library/Caches/Homebrew/downloads/661ef805a7adb62e317c3ecfc344a75977b26aef43ca4a63b3636e98049127d3--WeChatMac.dmg is quarantined
==> Propagating quarantine from /Users/xkia/Library/Caches/Homebrew/downloads/661ef805a7adb62e317c3ecfc344a75977b26aef43ca4a63b3636e98049127d3--WeChatMac.dmg to /usr/local/Caskroom/wechat/3.8.0.18
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/xkia/Library/Caches/Homebrew/downloads/661ef805a7adb62e317c3ecfc344a75977b26aef43ca4a63b3636e98049127d3--WeChatMac.dmg
/usr/bin/env /usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/env /usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0381\;646d72cd\;\;15B90109-5F48-40DB-B899-F008297D7685
==> Creating metadata directory: /usr/local/Caskroom/wechat/.metadata/3.8.0.18/20230524022245.486
==> Creating metadata subdirectory: /usr/local/Caskroom/wechat/.metadata/3.8.0.18/20230524022245.486/Casks
==> Installing artifacts
==> Installing artifact of class Cask::Artifact::App
==> Moving App 'WeChat.app' to '/Applications/WeChat.app'
/usr/bin/sudo -E -- /bin/cp -pR /usr/local/Caskroom/wechat/3.8.0.18/WeChat.app/Contents /Applications/WeChat.app
cp: /Applications/WeChat.app/Contents: Operation not permitted
cp: /usr/local/Caskroom/wechat/3.8.0.18/WeChat.app/Contents: unable to copy extended attributes to /Applications/WeChat.app/Contents: Operation not permitted
cp: /Applications/WeChat.app/Contents/_CodeSignature: No such file or directory
cp: /usr/local/Caskroom/wechat/3.8.0.18/WeChat.app/Contents/_CodeSignature: unable to copy extended attributes to /Applications/WeChat.app/Contents/_CodeSignature: No such file or directory
cp: /Applications/WeChat.app/Contents/_CodeSignature/CodeResources: No such file or directory
cp: utimensat: /Applications/WeChat.app/Contents/_CodeSignature: No such file or directory
cp: chown: /Applications/WeChat.app/Contents/_CodeSignature: No such file or directory
cp: chmod: /Applications/WeChat.app/Contents/_CodeSignature: No such file or directory
cp: chflags: /Applications/WeChat.app/Contents/_CodeSignature: No such file or directory
cp: /usr/local/Caskroom/wechat/3.8.0.18/WeChat.app/Contents/_CodeSignature: unable to copy ACL to /Applications/WeChat.app/Contents/_CodeSignature: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS: No such file or directory
cp: /usr/local/Caskroom/wechat/3.8.0.18/WeChat.app/Contents/MacOS: unable to copy extended attributes to /Applications/WeChat.app/Contents/MacOS: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChat: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app: No such file or directory
cp: /usr/local/Caskroom/wechat/3.8.0.18/WeChat.app/Contents/MacOS/WeChatAppEx.app: unable to copy extended attributes to /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents: No such file or directory
cp: /usr/local/Caskroom/wechat/3.8.0.18/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents: unable to copy extended attributes to /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/_CodeSignature: No such file or directory
cp: /usr/local/Caskroom/wechat/3.8.0.18/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/_CodeSignature: unable to copy extended attributes to /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/_CodeSignature: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/_CodeSignature/CodeResources: No such file or directory
cp: utimensat: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/_CodeSignature: No such file or directory
cp: chown: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/_CodeSignature: No such file or directory
cp: chmod: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/_CodeSignature: No such file or directory
cp: chflags: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/_CodeSignature: No such file or directory
cp: /usr/local/Caskroom/wechat/3.8.0.18/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/_CodeSignature: unable to copy ACL to /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/_CodeSignature: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/MacOS: No such file or directory
cp: /usr/local/Caskroom/wechat/3.8.0.18/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/MacOS: unable to copy extended attributes to /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/MacOS: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/MacOS/WeChatAppEx: No such file or directory
cp: utimensat: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/MacOS: No such file or directory
cp: chown: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/MacOS: No such file or directory
cp: chmod: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/MacOS: No such file or directory
cp: chflags: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/MacOS: No such file or directory
cp: /usr/local/Caskroom/wechat/3.8.0.18/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/MacOS: unable to copy ACL to /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/MacOS: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/Resources: No such file or directory
cp: /usr/local/Caskroom/wechat/3.8.0.18/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/Resources: unable to copy extended attributes to /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/Resources: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/Resources/zh-Hans.lproj: No such file or directory
cp: /usr/local/Caskroom/wechat/3.8.0.18/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/Resources/zh-Hans.lproj: unable to copy extended attributes to /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/Resources/zh-Hans.lproj: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/Resources/zh-Hans.lproj/InfoPlist.strings: No such file or directory
cp: utimensat: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/Resources/zh-Hans.lproj: No such file or directory
cp: chown: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/Resources/zh-Hans.lproj: No such file or directory
cp: chmod: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/Resources/zh-Hans.lproj: No such file or directory
cp: chflags: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/Resources/zh-Hans.lproj: No such file or directory
cp: /usr/local/Caskroom/wechat/3.8.0.18/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/Resources/zh-Hans.lproj: unable to copy ACL to /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/Resources/zh-Hans.lproj: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/Resources/en.lproj: No such file or directory
cp: /usr/local/Caskroom/wechat/3.8.0.18/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/Resources/en.lproj: unable to copy extended attributes to /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/Resources/en.lproj: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/Resources/en.lproj/InfoPlist.strings: No such file or directory
cp: utimensat: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/Resources/en.lproj: No such file or directory
cp: chown: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/Resources/en.lproj: No such file or directory
cp: chmod: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/Resources/en.lproj: No such file or directory
cp: chflags: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/Resources/en.lproj: No such file or directory
cp: /usr/local/Caskroom/wechat/3.8.0.18/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/Resources/en.lproj: unable to copy ACL to /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/Resources/en.lproj: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/Resources/Base.lproj: No such file or directory
cp: /usr/local/Caskroom/wechat/3.8.0.18/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/Resources/Base.lproj: unable to copy extended attributes to /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/Resources/Base.lproj: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/Resources/Base.lproj/InfoPlist.strings: No such file or directory
cp: utimensat: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/Resources/Base.lproj: No such file or directory
cp: chown: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/Resources/Base.lproj: No such file or directory
cp: chmod: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/Resources/Base.lproj: No such file or directory
cp: chflags: /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/Resources/Base.lproj: No such file or directory
...
...
cp: /usr/local/Caskroom/wechat/3.8.0.18/WeChat.app/Contents: unable to copy ACL to /Applications/WeChat.app/Contents: Operation not permitted
/usr/local/Homebrew/Library/Homebrew/system_command.rb:313:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:59:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:38:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/moved.rb:91:in `move'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/moved.rb:19:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:234:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:227:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:115:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/reinstall.rb:31:in `block in reinstall_casks'
/usr/local/Homebrew/Library/Homebrew/cask/reinstall.rb:22:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/reinstall.rb:22:in `reinstall_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:170:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'

**Comment by JBYoshi** [comment]
I have a hunch on what's going on. macOS Ventura added an extra "App Management" permission in System Settings. It means that one app can't modify the contents of another app bundle unless the first app has either App Management permissions or Full Disk Access permissions.

Steps to reproduce:
* Install a cask that contains an application.
* Open the application, to make sure macOS knows there's an app installed there.
* Go to System Settings and make sure both App Management and Full Disk Access are turned off for your terminal.
* Run `brew reinstall <cask name>`.

I'm working on some changes that will make Homebrew prompt for permission when you're doing an update; I expect to have a PR up by the end of the week. In the meantime, you can manually grant permissions for your terminal under Settings > Security and Privacy > App Management. You should then be able to fix any broken casks with `brew reinstall --force <cask name>`.

**Comment by getsueineko** [comment]
> 

I believe that the cause is diagnosed correctly. I enabled the permission for the terminal and after that I successfully updated one of the available cask. I'm monitoring further. Thank you
