### ISSUE TITLE
ownCloud doesn't install arm binaries on M1/M2

### ISSUE THREAD

**Issue by GRomR1** [Homebrew/homebrew-cask#147617]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

The [onwCloud](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/owncloud.rb) cask currently installs Intel binary on my macbook air on ARM M1 processor.

https://github.com/Homebrew/homebrew-cask/blob/master/Casks/owncloud.rb

However, arm binaries are available:
https://download.owncloud.com/desktop/ownCloud/stable/4.0/mac/

Source: https://github.com/owncloud/client/issues/8329

### Command that failed

-

### Output of command with `--verbose --debug`

```shell
-
```

### Output of `brew doctor` and `brew config`

```shell
-
```

### Output of `brew tap`

```shell
-
```

**Comment by SMillerDev** [comment]
Please make a pull request to adjust this.
