### ISSUE TITLE
Can't update any cask. Problems with permissions

### ISSUE THREAD

**Issue by getsueineko** [Homebrew/homebrew-cask#147789]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

I'm having trouble updating any cask. If I install cask, then there is no problem, the application is successfully installed in Application.
However, if I go through an update, then I get a permissions error. I reinstalled brew, it did not help, brew doctor says that there are no problems.
After that, the application contains a broken application, in fact it is an application folder in which there is nothing
After that, only by deleting this folder can I reinstall a cask again

### Command that failed

brew upgrade --greedy

### Output of command with `--verbose --debug`

```shell
==> Upgrading 1 outdated package: cvivaldi 6.0.2979.22 -> 6.0.2979.23
==> Upgrading vivaldi
Downloading https://downloads.vivaldi.com/stable-auto/Vivaldi.6.0.2979.23.universal.tar.xz
Ch
Backing App 'Vivaldi.app' up to '/opt/homebrew/Caskroom/vivaldi/6.0.2979.22/Vivaldi.app
Removing App '/Applications/Vivaldi.app
##### 100.0%
Ch Password:
Ct Moving App 'Vivaldi.app' to
"Applications/Vivaldi.app'
==> C| cp: /Applications/Vivaldi.app/Contents: Operation not permitted
ct cp: /opt/homebrew/Caskroom/vivaldi/6.0.2979.23/Vivaldi.app/Contents: unable to copy extended attributes to /Applications/Vivaldi.app/Contents: Operation not permitted
Ch cp: /Applications/Vivaldi.app/Contents/CodeResources: No such file or directory cp: /Applications/Vivaldi.app/Contents/_CodeSignature: No such file or directory
Ch cp: /opt/homebrew/Caskroom/vivaldi/6.0.2979.23/Vivaldi.app/Contents/_CodeSignature: unable to copy extended attributes to /Applications/Vivaldi.app/Contents/_CodeSignature: No Su
==> Cl ch file or directory
Ch cp: /Applications/Vivaldi.app/Contents/_CodeSignature/CodeResources: No such file or directory
Ci cp: utimensat: /Applications/Vivaldi.app/Contents/_CodeSignature: No such file or directory
Ci cp: chown: /Applications/Vivaldi.app/Contents/_CodeSignature: No such file or directory ==> CH cp: chmod: /Applications/Vivaldi.app/Contents/ _CodeSignature: No such file or directory

<cut>
```

### Output of `brew doctor` and `brew config`

```shell
brew doctor
Your system is ready to brew.

brew config
HOMEBREW_VERSION: 4.0.19-9-g8aaf99e
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8aaf99e1d70c5f50a828c34c3219ecfb17203ba0
Last commit: 33 hours ago
Core tap JSON: 24 May 08:25 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.40.1 => /opt/homebrew/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
brew tap
blacktop/tap
hudochenkov/sshpass
romkatv/powerlevel10k
```

**Comment by SMillerDev** [comment]
Could be related to https://github.com/Homebrew/brew/pull/15138 @JBYoshi

**Comment by razvanazamfirei** [comment]
Could you run the command with `--verbose --debug`?

**Comment by pigri** [comment]
@razvanazamfirei I have the same problem. Here is my debug log: https://pastebin.mozilla.org/bYLeNVmk

**Comment by razvanazamfirei** [comment]
Thank you @pigri! Could you provide the permissions for:
`/Applications/Setapp.app/`
`(brew --prefix)/bin/brew`
`(brew --caskroom)/setapp/3.26.0,45,1684230862/*`
You can use `/bin/ls -le`

**Comment by pigri** [comment]
Sure, here you are:

``` $(brew --prefix)/bin/brew
-rwxr-xr-x@ 1 davidpapp  staff  5076 May 24 14:52 /opt/homebrew/bin/brew
```

```
/Applications/Setapp.app/
total 0
drwxr-xr-x@ 11 davidpapp  staff  352 May 19 19:19 Contents
```

```
ls -le $(brew --caskroom)/setapp/
total 0
drwxr-xr-x@ 3 davidpapp  staff  96 May 24 16:13 3.26.1,46,1684517124
```

**Comment by JBYoshi** [comment]
I think this might have to do with the new "App Management" permissions in macOS Ventura. More info here: https://github.com/Homebrew/homebrew-cask/issues/147383#issuecomment-1562033383
