### ISSUE TITLE
EmacsClient outdated?

### ISSUE THREAD

**Issue by ryofurue** [Homebrew/homebrew-cask#149428]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

When I `open -a EmacsClient`, I get this error message:
    sh: /Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_9/emacsclient: No such file or directory

I have only `bin-x86_64-10_11`  and  `bin-x86_64-10_14` under `/applications/Emacs.app/Contents/MacOS/`, which came from `brew install emacs --cask`.

Before submitting this report I did:
    brew update-reset && brew update
    brew doctor # -> "Your system is ready to brew."
    brew reinstall emacs --cask
    brew reinstall emacsclient --cask --force

(Perhaps EmacsClient should be included in the Emacs cask?)

### Command that failed

open -a EmacsClient

### Output of command with `--verbose --debug`

```shell
Sorry I don't know which command I should use the verbose debug option with.
```

### Output of `brew doctor` and `brew config`

```shell
$ brew doctor
Your system is ready to brew.
$ brew config
HOMEBREW_VERSION: 4.0.23-12-ge986264
ORIGIN: https://github.com/Homebrew/brew
HEAD: e986264a3e5f4cb14cbc98efbc3c0e09aa363b9f
Last commit: 2 days ago
Core tap JSON: 19 Jun 03:49 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.VyrexvP9z9/org.xquartz:0
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
$
```

### Output of `brew tap`

```shell
<None>
```

**Comment by miccal** [comment]
Please post the output of `which -a emacs`, `which -a ctags`,  `which -a ebrowse`, `which -a emacsclient` and `which -a etags`.

**Comment by ryofurue** [comment]
```sh
~ $ which -a emacs
/Users/furue/bin/emacs
/opt/homebrew/bin/emacs
~ $ which -a ctags
/usr/bin/ctags
~ $ which -a ebrowse
/opt/homebrew/bin/ebrowse
~ $ which -a emacsclient
/opt/homebrew/bin/emacsclient
~ $ which -a etags
/opt/homebrew/bin/etags
~ $
```
Note that my `~/bin/emacs` is a shell script which is
```sh
#!/bin/sh
if ps -e | grep '[E]macs.app' > /dev/null; then
  if test -x /opt/homebrew/bin/brew; then
    brewtopdir="/opt/homebrew"
  elif test -x /usr/local/bin/brew; then
    brewtopdir="/usr/local"
  fi
  $brewtopdir/bin/emacsclient -n "$@"
else
    open -a "Emacs" --args --chdir "$PWD" "$@"
fi
```

**Comment by miccal** [comment]
So `emacsclient` is correctly installed as a binary, but it is _not_ an `.app`, hence why `open -a EmacsClient` does not work. 

What exactly do you expect to happen when you run `open -a EmacsClient`?

**Comment by ryofurue** [comment]
I sent you a wrong set of information! regarding "which -a emacs" etc.!  I'm sorry!  I'll send you a correct set of information soon.  (I submitted the original report from a Mac machine and posted the second message from another Mac machine!)

> So emacsclient is correctly installed as a binary, but it is not an .app, hence why open -a EmacsClient does not work.

The emacsclient cask installs `/Applications/EmacsClient.app`, which *is* an app and means that `open -a EmacsClient` *is meant to work.*

**Comment by ryofurue** [comment]
> Perhaps try running `open -a /Applications/EmacsClient.app`

The result is the same:
```
sh: /Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_9/emacsclient: No such file or directory
```
So, my guess is that the `EmacsClient.app` tries to invoke the binary `emacsclient` of `Emacs.app` but looks into a non-existent folder `bin-x86_64-10_9`.

Does the `EmacsClient.app` work on your mac?

**Comment by ryofurue** [comment]
I've just found the code:

    /Applications/EmacsClient.app/Contents/Resources/Scripts/main.scpt

You can `open` it and you'll see the source code:
```
on emacsclient(input)
	do shell script "/Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_9/emacsclient -n -c -a \"/Applications/Emacs.app/Contents/MacOS/Emacs\" '" & input & "'"
end emacsclient
```
So, this script (is it an AppleScript?) tries to call the non-existent executable.

**Comment by miccal** [comment]
That is an upstream issue with the `emacsclient` Cask, and unfortunately there is nothing we can do here.

**Comment by ryofurue** [comment]
> That is an upstream issue with the emacsclient Cask, and unfortunately there is nothing we can do here.

Thank you for your message.  This is the first time for me to report issues about a cask and I didn't know well how things work.  From your message, I take it that I should look at the upstream package.
