### ISSUE TITLE
Orion cannot be installed on macos Sonoma

### ISSUE THREAD

**Issue by cloud-on-prem** [Homebrew/homebrew-cask#150646]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

Orion cannot be installed on macos Sonoma probably because of a misconfigured line here:
https://github.com/Homebrew/homebrew-cask/blob/c387f2cbbbad7d8fb8ebb13d76bac237c8c28fb8/Casks/orion.rb#L62

Should this be instead?

```
depends_on macos: ">= :ventura"
```

### Command that failed

brew install orion --cask

### Output of command with `--verbose --debug`

```shell
==> Downloading https://browser.kagi.com/updates/13_0/124.3.zip
Already downloaded: /Users/xxxx/Library/Caches/Homebrew/downloads/f0cc55ef8b5ebd5c52346e057ed49db77f508c88be57c0abbf67c77fefcabefb--124.3.zip
Error: This cask does not run on macOS versions newer than Ventura.
```

### Output of `brew doctor` and `brew config`

```shell
Warnings about using Macos 14.


HOMEBREW_VERSION: 4.0.28
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2b4cfb033757b63ab0b128d01c58db76480956f9
Last commit: 3 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7fd87f2ab8f95b69c8bf06ec18a007bf133667ec
Core tap last commit: 5 months ago
Core tap branch: master
Core tap JSON: 09 Jul 03:09 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: hx
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.0-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1
Rosetta 2: false
```
```


### Output of `brew tap`

```shell
dracula/install
homebrew/bundle
homebrew/cask-versions
homebrew/core
miserlou/loop
teamookla/speedtest
```

**Comment by Bo98** [comment]
> Orion cannot be installed on macos Sonoma probably because of a misconfigured line here:
> 
> https://github.com/Homebrew/homebrew-cask/blob/c387f2cbbbad7d8fb8ebb13d76bac237c8c28fb8/Casks/orion.rb#L62
> 
> Should this be instead?
>
>     depends_on macos: ">= :ventura"

It's correct for that URL. We will need to add another block for `https://cdn.kagi.com/downloads/14_0/Orion.dmg`.

Technically the downloads for 13.0 and 14.0 produce the same file with the same sha256, but there's no guarantee this will remain the case.

**Comment by miccal** [comment]
This will be fixed once macOS Sonoma is officially released.
```
Warning: You are using macOS 14.
We do not provide support for this pre-release version.
```
