### ISSUE TITLE
Casks/google-cloud-sdk upgrade issue if previously manually upgraded

### ISSUE THREAD

**Issue by alexanderxc** [Homebrew/homebrew-cask#150906]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

This is not properly an upgrade issue but possibly an issue on how google-cloud-sdk is installed as a Cask. I apologize in advance if this report is incorrectly formulated but I could not find a better solution. 

The issue is as follows: 
- google-cloud-sdk installation happens without a glitch and the everything works fine
- It may happen that there is a delay in between google release its (very frequent) update and the time the update is included into homebrew/casks. 
- In that time, whenever `gcloud` commands is run, the CLI reports there is an update and users may decide to perform such update
- If that happens, the Cask is updated in `/opt/homebrew/share/google-cloud-sdk` but its homebrew manifest is not. Consequently, homebrew still thinks the cask is at the previous version
- Whenever homebrew is updated it will list the cask as outdated whereas the cask is already at the latest version. 

google-cloud-sdk version is shown in `VERSION` file of its root folder => this confirms the statement above.

It would be nice to avoid this behavior. Is there a way to make sure and update homebrew version references / manifest if the package itself gets manually updated (thus avoiding the need to reinstall the package)?

Thanks in advance for the support.

### Command that failed

brew upgrade --cask google-cloud-sdk

### Output of command with `--verbose --debug`

```shell
N/A
```

### Output of `brew doctor` and `brew config`

```shell
❯ brew doctor
Your system is ready to brew.

❯ brew config
HOMEBREW_VERSION: 4.0.28
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2b4cfb033757b63ab0b128d01c58db76480956f9
Last commit: 6 days ago
Core tap JSON: 12 Jul 16:38 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1
Rosetta 2: false
```

### Output of `brew tap`

```shell
❯ brew tap
homebrew/services
romkatv/powerlevel10k
```

**Comment by razvanazamfirei** [comment]
Hey @alexanderxc, thank you for opening this. It seems like you're experiencing a problem related to what's described [here](https://docs.brew.sh/FAQ#why-arent-some-apps-included-during-brew-upgrade). Unfortunately, implementing the functionality you described is not feasible and has been discussed many times before. 

However, there are 2 solutions here. The first one is to add `auto_updates true` to the cask.
The second one, which would make the most sense, is to disable the update function in `google-command-sdk`. I've only looked into it briefly, but happy to review any PRs.

**Comment by alexanderxc** [comment]
Hey @razvanazamfirei, thank you for the suggestion! 

I agree point 2, but I'm afraid that the autoupdate check cannot be disabled - in specific, it is not the end of the world as the package does not autoupdate but just asks you to update when a new version comes out. 

so we are really at a crossroad here, as both point 1 or "not do anything" would be imperfect but good enough solutions. 

To clarify, modifying the `auto_updates true` makes brew to save the program without version in the filesystem? 

If that's the case, it might be the better option as the cask is capable of updating itself by simply updating the files in `/opt/homebrew/share/google-cloud-sdk`. 

What would you suggest at this point? 

Non sequitur: is there a brew command that is capable of listing all installed tap/casks and their relative versions. `brew list -l` does not quite cut it.

Thank you!

**Comment by razvanazamfirei** [comment]
Hey @alexanderxc, 
`google-cloud-sdk/lib/googlecloudsdk/core/config.json` has the option to disable the updater, but it involves us modifying the cask before installing, which doesn't sound like a good idea the more I think about it. 

With `auto_updates true`, `brew` will not upgrade your cask unless you pass `--greedy` or have `HOMEBREW_UPGRADE_GREEDY` set. See [here](https://docs.brew.sh/Manpage#upgrade-options-outdated_formulaoutdated_cask-) for more details. You can then update the cask through its own mechanism and use brew only when you want; however, this does not keep track of the real version, just of the version brew installed. I think this makes most sense.

To answer your last question, `brew list --casks --versions` should do the trick. Some unofficial commands can also extend the [cask upgrade](https://github.com/buo/homebrew-cask-upgrade) functionality. This, of course, is not endorsed by Homebrew; just providing here for reference.
