### ISSUE TITLE
One Switch cask installed through brew doesn't have native Apple silicon support

### ISSUE THREAD

**Issue by Jerry23011** [Homebrew/homebrew-cask#151074]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

One Switch installed through Homebrew doesn't have native Apple silicon support, it seems that Homebrew is getting an Intel-only binary.

From checking the hash, the latest .app file (version 1.31,392) downloaded from the [official website](https://fireball.studio/oneswitch/download/) of One Switch (`0190093b6f82e856fe98168b139a3574cc06c4001bfbe77c45a21506434e3b6e`) is different from the one downloaded with the [cask file](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/one-switch.rb) (`3b4edd6aa9ffaf1cae73a2c3ac4216c462ffc316bfb1cb9ed50a4daf653d9a27`)

I also tested the two .app files with [Silicon](https://github.com/DigiDNA/Silicon). The one downloaded from Homebrew has no Apple silicon support while the one from the official website does.

It seems that this is the right download link: https://fireball.studio/api/release_manager/downloads/studio.fireball.OneSwitchOfficial.dmg

### Command that failed

`brew install --cask one-switch`

### Output of command with `--verbose --debug`

```shell
None
```

### Output of `brew doctor` and `brew config`

```shell
`Your system is ready to brew.`


HOMEBREW_VERSION: 4.0.28-20-g5b30de8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5b30de880d3c937b121dcc036582143dc4548b4f
Last commit: 5 days ago
Core tap JSON: 10 Jul 10:59 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1
Rosetta 2: false
```

### Output of `brew tap`

```shell
None
```

**Comment by krehel** [comment]
Thanks for this @Jerry23011.  It does look like the zip file link provided as part of `sparkle` is only providing an `x86_64` binary, but the `dmg` provides a universal.

**Comment by Jerry23011** [comment]
Thanks for replying, I'm wondering how this can be fixed

**Comment by Jerry23011** [comment]
Thank you, @krehel
