### ISSUE TITLE
Instead of just saying "you may need to install Switch", why not suggest how to"?

### ISSUE THREAD

**Issue by cjheath** [Homebrew/homebrew-cask#151156]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

[This warning on installation](https://github.com/Homebrew/homebrew-cask/blob/95234a41351e4bb875886d81ce5b401d04c5a881/Casks/gtkwave.rb#L26-L27) says:

"You may need to install Perl’s Switch module to run #{token}’s command line tool".

For users not familiar with Perl, it would be much friendlier to also suggest *how* to install it:

`cpan install Switch`

### Command that failed

brew install gtkwave

### Output of command with `--verbose --debug`

```shell
Not applicable
```

### Output of `brew doctor` and `brew config`

```shell
Not applicable
```

### Output of `brew tap`

```shell
smokris/getwindowid
```

**Comment by krehel** [comment]
The next line in the caveat provides a link to the instructions to do this.

```
    You may need to install Perl’s Switch module to run #{token}’s command line
    tool.

      https://ughe.github.io/2018/11/06/gtkwave-osx
```

**Comment by cjheath** [comment]
Those instructions told me what I needed to do, but manually copying files between package management subdirectories isn't something I'm willing (or should need) to do. I got it working using `sudo` instead.

Still much better to just put the hint in the warning message, than to redirect to a page that (a) might vanish any time and (b) has instructions that don't necessarily work to (c) do something that many users will fail at or be unwilling to do anyway.

**Comment by bevanjkay** [comment]
@cjheath If you have a suggestion for a better caveat that would be more helpful, you are welcome to[ submit a PR](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md) for the changes.

**Comment by cjheath** [comment]
Thanks. I made a suggesting in opening the issue. Seems like a fork and clone of the entire repo to add five words:

"for example, `cpan install Switch`"

is quite circuitous though? I thought GitHub had an online way of creating such small PRs but can't find that rn.

**Comment by SMillerDev** [comment]
https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files

**Comment by cjheath** [comment]
Added PR https://github.com/Homebrew/homebrew-cask/pull/151772

**Comment by krehel** [comment]
#151772 was merged, so believe this can be closed now.
