### ISSUE TITLE
Android Studio not listed in outdated casks

### ISSUE THREAD

**Issue by lethefrost** [Homebrew/homebrew-cask#151200]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

I noticed that my installed version of AS is `Electric Eel 2022.1.1 Patch 1` or `2022.1.1.20`, and the current latest release is `Flamingo 2022.2.1 Patch 2` or `2022.2.1.20`. The cask code [here](https://github.com/Homebrew/homebrew-cask/blob/1c580cb3332f6b54662349b3c16eada3fa6cbd5d/Casks/android-studio.rb) looks like it has been up-to-date with the official release since 2 months ago. 

However, it is never listed in the `brew outdated` command output in the many times I executed it including today. I even tried specifically using `brew outdated --cask android-studio` but no outputs are shown. All troubleshooting commands were executed before those trials.

Below is what it shows after `brew info android-studio`:

```sh
> brew info android-studio
==> android-studio: 2022.2.1.20 (auto_updates)
https://developer.android.com/studio/
/opt/homebrew/Caskroom/android-studio/2022.1.1.20 (18.2KB)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/android-studio.rb
==> Name
Android Studio
==> Description
Tools for building Android applications
==> Artifacts
Android Studio.app (App)
==> Analytics
install: 0 (30 days), 0 (90 days), 0 (365 days)
```

It is also abnormal and surprising to see the analytics are all 0s. They are also on the [formulae site](https://formulae.brew.sh/cask/android-studio). I'm not too sure if there's some issue with the cask that made no one could install/detect this updated package or the installation statistics couldn't be collected?

Though this update is not detectable by `brew outdated` command, if I specify the formula to `upgrade`, it will still manage to upgrade to `2022.2.1.20` with the following outputs:

```sh
> brew upgrade android-studio
==> Upgrading 1 outdated package:
android-studio 2022.1.1.20 -> 2022.2.1.20
==> Upgrading android-studio
==> Downloading https://redirector.gvt1.com/edgedl/android/studio/install/2022.2.1.20/android-studio-2022.2.1.20-mac_arm.dmg
==> Downloading from https://r2---sn-cxaaj5o5q5-tt1ed.gvt1.com/edgedl/android/studio/install/2022.2.1.20/android-studio-2022.2.1.20-mac_arm.
##################################################################################################################################### 100.0%
==> Backing App 'Android Studio.app' up to '/opt/homebrew/Caskroom/android-studio/2022.1.1.20/Android Studio.app'
==> Removing App '/Applications/Android Studio.app'
==> Moving App 'Android Studio.app' to '/Applications/Android Studio.app'
==> Purging files for version 2022.1.1.20 of Cask android-studio
🍺  android-studio was successfully upgraded!
```

Thanks for your time reading this!

### Command that failed

brew outdated

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading android-studio
```

### Output of `brew doctor` and `brew config`

```shell
Your system is ready to brew.
HOMEBREW_VERSION: 4.0.28-76-g128746f
ORIGIN: https://github.com/Homebrew/brew
HEAD: 128746f92ba93f57311cc0ddc078bb62063d7163
Last commit: 2 hours ago
Core tap JSON: 17 Jul 15:48 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.41.0 => /opt/homebrew/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1
Rosetta 2: false
```

### Output of `brew tap`

```shell
None
```

**Comment by bevanjkay** [comment]
@lethefrost `brew outdated` will not show casks that have `auto_updates true` set, as it is expected that the update would be handled by the application itself in the default case. You can pass flags to `brew outdated` to list additional casks. `brew outdated --greedy` will show all outdated casks, or `brew outdated --greedy-auto-updates` will include casks with `auto_updates true` but not those with `version :latest`.
