### ISSUE TITLE
Cask: Authy using incorrect`version`

### ISSUE THREAD

**Issue by typkrft** [Homebrew/homebrew-cask#151365]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

I believe that the Authy Cask Formula is tagged with the incorrect version. Currently the formula has `2.4.0` that should be `2.3.0` I believe. 

The official page link `https://electron.authy.com/download?channel=stable&arch=x64&platform=darwin&version=latest&product=authy` redirects to this URL `https://pkg.authy.com/authy/stable/2.3.0/darwin/x64/Authy%20Desktop-2.3.0.dmg` at the moment.

### Command that failed

brew install --cask authy

### Output of command with `--verbose --debug`

```shell
Error: Download failed on Cask 'authy' with message: Failure while executing; `/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.29\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4.1\)\ curl/7.88.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://pkg.authy.com/authy/stable/2.4.0/darwin/x64/Authy\%20Desktop-2.4.0.dmg` exited with 22. Here's the output:
curl: (22) The requested URL returned error: 403
HTTP/1.1 403 Forbidden
Date: Thu, 20 Jul 2023 06:18:13 GMT
Content-Type: application/xml
Transfer-Encoding: chunked
Connection: keep-alive
X-Cache: Error from cloudfront
Via: 1.1 c22de0e2f2b4d640c1ce19166b5e21e6.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: ATL56-C1
X-Amz-Cf-Id: pU4Eqai_rfHLiJ4E_sSylK4f-FGI7IFjfEC4H01uO-0GVJ_hiRHqwg==
CF-Cache-Status: MISS
X-Content-Type-Options: nosniff
Server: cloudflare
CF-RAY: 7e9915eadece06e6-ATL
```
```


### Output of `brew doctor` and `brew config`

```shell
NA
```

### Output of `brew tap`

```shell
NA
```

**Comment by bevanjkay** [comment]
@typkrft The release must have been pulled by upstream, as it would not have passed our CI tests if the download was broken at the time of upgrade. Will setup a fix now.

**Comment by typkrft** [comment]
I saw the recent push and assumed as much. You all are great. Cheers!
