### ISSUE TITLE
CONTRIBUTING.md references non-existent path "$(brew --repository)"/Library/Taps/homebrew/homebrew-cask

### ISSUE THREAD

**Issue by cjheath** [Homebrew/homebrew-cask#151771]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

In CONTRIBUTING.md line 33, it asks you to cd to "$(brew --repository)"/Library/Taps/homebrew/homebrew-cask

In my (MACOS) system with the home-brew repository under /opt/homebrew, no such directory exists, so I cannot complete the instructions in [Getting Set Up To Contribute](https://github.com/cjheath/homebrew-cask/blob/master/CONTRIBUTING.md#getting-set-up-to-contribute).

### Command that failed

cd

### Output of command with `--verbose --debug`

```shell
Not applicable to `cd`
```

### Output of `brew doctor` and `brew config`

```shell
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  libhid
  nzbget

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install ghc

Run `brew missing` for more details.

$ brew config
HOMEBREW_VERSION: 4.0.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9b60fcf7ac3f82fa589a64091376d0663262f8c6
Last commit: 4 months ago
Core tap JSON: 14 Apr 04:12 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /usr/bin/vi
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_INSTALL_UPGRADE: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.3
Rosetta 2: false
```

### Output of `brew tap`

```shell
# brew tap
smokris/getwindowid
```

**Comment by bevanjkay** [comment]
@cjheath The default behaviour is not that `homebrew-cask` is not tapped for non-developers. So there is no local git repository.
Can you try running `brew tap homebrew/cask` and if the commands then run we can update the documentation.

**Comment by cjheath** [comment]
The command runs after tapping homebrew-cask
