### ISSUE TITLE
FYI: Changes to Official Release builds of Sigil and PageEdit

### ISSUE THREAD

**Issue by kevinhendricks** [Homebrew/homebrew-cask#151960]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

See (https://www.mobileread.com/forums/showthread.php?t=355274)

Please alert the Sigil and PageEdit cask maintainers
that both Sigil and PageEdit for the upcoming release will move to Qt 6.5.2 from Qt5 and Python 3.11.3 for official releases.

The new macos deployment target is 11.0

A separate arm64 build will be included.

### What is the motivation for the feature?

To provide a downstream notice of upcoming changes.

### How will the feature be relevant to at least 90% of Homebrew users?

na

### What alternatives to the feature have been considered?

na

**Comment by reitermarkus** [comment]
Also, there doesn't seem to be a cask for PageEdit.

**Comment by kevinhendricks** [comment]
Thank you!

We package all dependencies inside for our releases but Homebrew does not typically do that.  We will try and keep our tree buildable with Qt 5.15.x but Qt6 latest will become official and requires a cmake switch -DUSE_QT6=1 to use the Qt6 based cmake files.

PageEdit is a standalone wysiwyg xhtml editor companion program for Sigil.  Perhaps only MacPorts includes it.  Sorry I did not check beforehand.

We are happy to answer and address any build questions caused by our move if they come up.  Biggest issue is probably using macos deployment target of 11.0 (up from 10.12- which leaves lots of older platforms behind) but that was necessitated by Qt6.
