### ISSUE TITLE
CyberArk EPM prevents installation or upgrading of many casks

### ISSUE THREAD

**Issue by eddyg** [Homebrew/homebrew-cask#152041]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

CyberArk Endpoint Privilege Manager, an unfortunately popular tool used to restrict Mac users from doing stuff, is preventing more and more casks from being installed or updated. (And after an update fails, the application is in an unusable state, and then has to be manually removed and re-installed.)

Eventually I determined that commenting out the CyberArk EPM PAM sudo module (configured in `/etc/pam.d/sudo`) allowed the install to work successfully (although I was prompted for my password _multiple_ times during the install process).

Temporarily disabling the CyberArk PAM `sudo` interference can be done using `sed`:

```
sudo sed -i .bak '/CyberArkEPMPAM(\.dylib)?$/ s/^/# /' /etc/pam.d/sudo
brew install --cask wireshark
sudo mv /etc/pam.d/sudo.bak /etc/pam.d/sudo
```

Do you have any way to work with CyberArk to improve this situation? Using `brew` to manage software is extremely convenient, and having more apps being unable to be upgraded or installed is becoming a hassle.

### Command that failed

brew upgrade --cask wireshark

### Output of command with `--verbose --debug`

```shell
❯ brew upgrade --cask wireshark

==> Upgrading 1 outdated package:
wireshark 4.0.4 -> 4.0.7
==> Upgrading wireshark
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/9e944ae828ccde27340413ff2ac4de603243f5e0/Casks/wireshark.rb
==> Downloading https://2.na.dl.wireshark.org/osx/Wireshark%204.0.7%20Arm%2064.dmg
...
==> Running installer for wireshark; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
Execution blocked: eddyg does not have Admin rights

==> Purging files for version 4.0.7 of Cask wireshark
==> Purging files for version 4.0.7 of Cask wireshark
Warning: Reverting upgrade for Cask wireshark
==> Running installer for wireshark; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
Execution blocked: eddyg does not have Admin rights

==> Purging files for version 4.0.4 of Cask wireshark
Error: wireshark: Failure while executing; `/usr/bin/sudo -u root -E LOGNAME=eddyg USER=eddyg USERNAME=eddyg -- /usr/sbin/installer -pkg /opt/homebrew/Caskroom/wireshark/4.0.4/Add\ Wireshark\ to\ the\ system\ path.pkg -target /` exited with 1.


(Note at this point, Wireshark is unusable. I needed to manually remove /Applications/Wireshark.app)
```

### Output of `brew doctor` and `brew config`

```shell
❯ brew doctor
Your system is ready to brew.

❯ brew config
HOMEBREW_VERSION: 4.1.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3db1acf3e38e270af4e1c3f214622bbfb18f830e
Last commit: 5 days ago
Core tap JSON: 31 Jul 11:40 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
❯ brew tap
homebrew/bundle
homebrew/cask-versions
homebrew/services
mistertea/et
```

**Comment by SMillerDev** [comment]
> Do you have any way to work with CyberArk to improve this situation? 
We do not, you as a user of their software can work with them though. 

Closing as it's not an issue with brew
