### ISSUE TITLE
Error: freecad: SHA256 mismatch - intel version

### ISSUE THREAD

**Issue by Cocoader** [Homebrew/homebrew-cask#152222]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

I think there is a wrong checksum for the intel version specified.
Downloading it from https://www.freecad.org and doing a shasum results in "b5c938fe1f3356a7571de6289c804316701459a224c498e7ad09589db31ee7ba" as well.

### Command that failed

brew upgrade

### Output of command with `--verbose --debug`

```shell
Error: freecad: SHA256 mismatch
Expected: 271a3785a0ca68fab94ef6a7397ca9ed39cafbdce5bea19755b835462d8bceb0
  Actual: b5c938fe1f3356a7571de6289c804316701459a224c498e7ad09589db31ee7ba
```

### Output of `brew doctor` and `brew config`

```shell
none
```

### Output of `brew tap`

```shell
none
```

**Comment by SMillerDev** [comment]
> I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

please check the link here when you report that you did this.

**Comment by byteszard** [comment]
I have the some problem
![image](https://github.com/Homebrew/homebrew-cask/assets/16896367/e3cd912d-0aab-4a70-995e-139766d949ce)

**Comment by krehel** [comment]
#152232 fixes this.

It is advised to check upstream to find out why the `sha256` may have changed.  Anyone can submit updates to a Cask to fix an issue such as this.
