### ISSUE TITLE
multipass cask not installing bash autocompletion

### ISSUE THREAD

**Issue by gnzsnz** [Homebrew/homebrew-cask#153333]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

multipass cask is not installing bash autocompletion.

bash autocaompletion is available in `/Library/Application Support/com.canonical.multipass/Resources/completions/bash/multipass` however it's not installed in `$(brew --prefix)/etc/bash_completion.d`

please note that bash completion is uninstalled

```
$ brew reinstall multipass
==> Downloading https://github.com/canonical/multipass/releases/download/v1.12.2/multipass-1.12.2+mac-Darwin.pkg
Already downloaded: /Users/gonzo/Library/Caches/Homebrew/downloads/170dcf5b513c1c99620f25102766f6eb852252e7a39b64781122fd2391bbd7c1--multipass-1.12.2+mac-Darwin.pkg
==> Uninstalling Cask multipass
==> Removing launchctl service com.canonical.multipassd
Password:
==> Uninstalling packages; your password may be necessary:
com.canonical.multipass.multipassd
com.canonical.multipass.multipass
com.canonical.multipass.multipass_gui
==> Removing files:
/Applications/Multipass.app
/Library/Application Support/com.canonical.multipass
/Library/Logs/Multipass
/usr/local/bin/multipass
/usr/local/etc/bash_completion.d/multipass
==> Purging files for version 1.12.2 of Cask multipass
==> Installing Cask multipass
==> Running installer for multipass; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
installer: Package name is multipass
installer: Installing at base path /
installer: The install was successful.
🍺  multipass was successfully installed!
```

### Command that failed

multipass

### Output of command with `--verbose --debug`

```shell
does not apply

the issue is multipass autocompletion

$multipass <tab> (nothing happens)
```

### Output of `brew doctor` and `brew config`

```shell
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.

####################################################################################
$ brew config
HOMEBREW_VERSION: 4.1.5-55-g3cd7290
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3cd72905ce3d36a84994cc6c6b9ebbdafff4e922
Last commit: 31 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ab200061798482dfc87a6c477f29dd76dd86c582
Core tap last commit: 13 hours ago
Core tap branch: master
Core tap JSON: 19 Aug 18:40 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /opt/homebrew/bin/code -w
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.41.0 => /opt/homebrew/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
$ brew tap
homebrew/cask
homebrew/core
```

**Comment by gnzsnz** [comment]
workaround

```
$ cd $(brew --preifx)/etc/bash_completion.d
$ ln -s "/Library/Application Support/com.canonical.multipass/Resources/completions/bash/multipass"
```

**Comment by krehel** [comment]
Hi @gnzsnz - thanks for reporting this.  This looks like an upstream issue which affects ARM processors due to Homebrew directories being `/opt/homebrew` on ARM and `/usr/local/` on Intel.

The `postinstall` script in the package looks at `/usr/local` to evaluate if Homebrew is installed, and then not linking `completion` if not found.  Which, it won't be on ARM since that is not the Homebrew install location.  (Code excerpt below)

```
### Set up symlink for bash competions
# If HomeBrew installed (only looking for default path)
if [ -d "${3}usr/local/etc/bash_completion.d" ]; then
    ln -fsv "${3}/Library/Application Support/com.canonical.multipass/Resources/completions/bash/multipass" \
            "${3}usr/local/etc/bash_completion.d/multipass"
    echo "Installed Bash completion file for HomeBrew"
else
    echo "HomeBrew is not installed"
fi
```

It's possible to force the link by using a `binary` stanza in the Cask, and I can certainly propose this as a workaround.  But ultimately I believe upstream should check if Homebrew is installed in `/opt/homebrew` for ARM.

**Comment by gnzsnz** [comment]
i have raised

https://github.com/canonical/multipass/issues/3199
