### ISSUE TITLE
Catalina required for Libreoffice while Libreoffice.org says Mojave is required.

### ISSUE THREAD

**Issue by cbertelli** [Homebrew/homebrew-cask#153526]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

libreoffice.org/download/download-libreoffice says that Libreoffice 7.6.3 requires Mojave while the Cask formula requires Catalina. What's true?

### Command that failed

brew upgrade libreoffice --cask

### Output of command with `--verbose --debug`

```shell
Not relevant, anyway:
==> Purging files for version 7.6.0 of Cask libreoffice
Error: libreoffice: This software does not run on macOS versions older than Catalina.
```

### Output of `brew doctor` and `brew config`

```shell
Not relevant
```

### Output of `brew tap`

```shell
Not relevant
```

**Comment by SMillerDev** [comment]
Homebrew only supports Big Sur and later so anything below that is inconsequential anyway.

**Comment by Bo98** [comment]
[LibreOffice 7.6 release notes](https://wiki.documentfoundation.org/ReleaseNotes/7.6) mention:

> LibreOffice 7.6 requires macOS 10.15 or newer to run.

The download page has just not been updated. I also checked the Info.plist in the download itself:

```xml
<key>LSMinimumSystemVersion</key>
<string>10.15.0</string>
```

`homebrew/cask-versions/libreoffice-still` is still available for Mojave for as long as that remains on 7.5.x.
