### ISSUE TITLE
kstars: SHA256 mismatch

### ISSUE THREAD

**Issue by cxwx** [Homebrew/homebrew-cask#154278]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

kstars: SHA256 mismatch
Expected: 9a2da9c8f9eb6da847ccfaa7ca1270d15a7ab14b1becf805f98600811d928a2c
  Actual: d3f83431e2ca723b0aee7d452324f8be70fa4fd125f6f1c05107a17a304ab930
  
  each time the kstars upgrade with homebrew, it cause diff sha256, is that secure problem?

### Command that failed

upgrade kstars

### Output of command with `--verbose --debug`

```shell
/
```

### Output of `brew doctor` and `brew config`

```shell
/
```

### Output of `brew tap`

```shell
/
```

**Comment by SMillerDev** [comment]
>  I made doubly sure this is not a checksum does not match error.

The checkboxes are there to actually perform, not just decorative

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/154412
