### ISSUE TITLE
wkhtmltopdf: failed execution of install leaves package in broken state

### ISSUE THREAD

**Issue by pimlottc** [Homebrew/homebrew-cask#154280]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

wkhtmltopdf runs an installation script requiring sudo on install.  If this script fails to run, the package is left in a broken state.  In this state, you can't run wkhtmltopdf, but you also can't uninstall it, or force install a new version.

Of course it's not surprising the command doesn't run when the installation script does not complete, but the system is left in a state where the normal steps to fix it don't work and it's not clear how to fix it.

### Command that failed

brew install wkhtmltopdf

### Output of command with `--verbose --debug`

```shell
Current output:

/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading wkhtmltopdf
Warning: Not upgrading wkhtmltopdf, the latest version is already installed
```

Initial run w/o `--verbose --debug` (package not previously installed
```
==> Downloading https://formulae.brew.sh/api/formula.jws.json

==> Downloading https://formulae.brew.sh/api/cask.jws.json

==> Downloading https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-2/wkhtmltox-0.12.6-2.macos-cocoa.pkg
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/131323182/d62ac780-a
############################################################################################################### 100.0%
==> Installing Cask wkhtmltopdf
==> Running installer for wkhtmltopdf; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
Password:
```
```


### Output of `brew doctor` and `brew config`

```shell
brew config
Your system is ready to brew.
```

```
HOMEBREW_VERSION: 4.1.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: d4444b563e24ac7c05a93121c464c02dfa04d44f
Last commit: 7 days ago
Core tap JSON: 03 Sep 19:34 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.39.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5-arm64
CLT: 14.3.0.22.14.1
Xcode: 14.3.1
Rosetta 2: false
```
```


### Output of `brew tap`

```shell
gbevin/tools
```
```

**Comment by pimlottc** [comment]
Of course it's not surprising the command doesn't run when the installation script does not complete, but the system is left in a state where the normal steps to fix it don't work and it's not clear how to fix it.

**Comment by SMillerDev** [comment]
How about `brew reinstall`?

**Comment by powru9-gobVok-nutguj** [comment]
[]()

**Comment by miccal** [comment]
Cannot reproduce: https://github.com/Homebrew/homebrew-cask/pull/157058
