### ISSUE TITLE
Logseq 0.9.16 revoked and hence unable to download (404)

### ISSUE THREAD

**Issue by blmhemu** [Homebrew/homebrew-cask#154597]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

Title ^ brew says 404 not found. See https://github.com/logseq/logseq/releases/tag/0.9.16

### Command that failed

brew upgrade --greedy

### Output of command with `--verbose --debug`

```shell
curl: (22) The requested URL returned error: 404
HTTP/2 404
server: GitHub.com
date: Thu, 07 Sep 2023 06:00:17 GMT
content-type: text/plain; charset=utf-8
vary: X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With
cache-control: no-cache
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 0
referrer-policy: no-referrer-when-downgrade
content-security-policy: default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'
content-length: 9
x-github-request-id: 8B23:60DC:C1E7A0:10C9A33:64F966F0
```

### Output of `brew doctor` and `brew config`

```shell
Not needed
```

### Output of `brew tap`

```shell
Not needed
```

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/154596
