### ISSUE TITLE
cask google-chrome current version is unstable

### ISSUE THREAD

**Issue by CHOICORE** [Homebrew/homebrew-cask#155134]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

Current version: [117.0.5938.62](https://dl.google.com/chrome/mac/universal/stable/GGRO/googlechrome.dmg)

I have encountered a problem where the browser unexpectedly crashes. This issue occurs when performing certain actions within the browser.

Steps to Reproduce:

Google Chrome Browser -> Settings -> Privacy and security -> Clear browsing data 

Enable the "Advanced > Password and Passkeys" > Clear data

After enabling the option, the browser crashes unexpectedly.

The issue is specific to enabling this particular option other settings changes do not result in a crash.

The problem persists across multiple attempts and system restarts.

Additional Information:
Downloading files from the Google homepage works fine without any issues.

### Command that failed

-

### Output of command with `--verbose --debug`

```shell
-
```

### Output of `brew doctor` and `brew config`

```shell
HOMEBREW_VERSION: 4.1.11-25-gc953076
ORIGIN: https://github.com/Homebrew/brew
HEAD: c9530766096e692d5031750a14b4d1d42f1dc655
Last commit: 11 hours ago
Core tap JSON: 14 Sep 00:03 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.2-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
homebrew/bundle
homebrew/services
```

**Comment by SMillerDev** [comment]
This should be reported to Google, not the tool that can install it.
