### ISSUE TITLE
Packet hash mismatch detected waterfox (version G6.0)

### ISSUE THREAD

**Issue by f3035** [Homebrew/homebrew-cask#155936]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

Packet hash mismatch detected waterfox (version G6.0)

### Command that failed

brew install --cask waterfox --verbose

### Output of command with `--verbose --debug`

```shell
==> Downloading https://formulae.brew.sh/api/cask.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1007k  100 1007k    0     0  2465k      0 --:--:-- --:--:-- --:--:-- 2487k
==> Downloading https://cdn1.waterfox.net/waterfox/releases/G6.0/Darwin_x86_64-aarch64/Waterfox%20G6.0.dmg
Already downloaded: /Users/rsy/Library/Caches/Homebrew/downloads/8b2ad40e80e9dcf2ab01d516bbce46877982db449754b894e8817b1384419a61--Waterfox G6.0.dmg
==> Verifying checksum for '8b2ad40e80e9dcf2ab01d516bbce46877982db449754b894e8817b1384419a61--Waterfox G6.0.dmg'
Error: SHA256 mismatch
Expected: d4b9f237e5568e21d2714e5fa7d1a762f48751bfd6a78ec25ffea48538f12893
  Actual: a34681e8a98325153208b7c093825cd3d2a8d0f00a32a3bcf89b53a22341d088
    File: /Users/rsy/Library/Caches/Homebrew/downloads/8b2ad40e80e9dcf2ab01d516bbce46877982db449754b894e8817b1384419a61--Waterfox G6.0.dmg
To retry an incomplete download, remove the file above.
```

### Output of `brew doctor` and `brew config`

```shell
brew doctor
Your system is ready to brew.
--------------------------------
brew config

HOMEBREW_VERSION: 4.1.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: aa2a77b1f1ac1539e69e186bad1d569100448987
Last commit: 6 days ago
Core tap JSON: 23 Sep 04:09 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.2-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
yurikoles/yurikoles
```

**Comment by SMillerDev** [comment]
So definitely this last checkbox then:
> I made doubly sure this is not a checksum does not match error.
