### ISSUE TITLE
tsh cask does not provide versions, but tsh is incompatible across major versions

### ISSUE THREAD

**Issue by coltonparsons-vgs** [Homebrew/homebrew-cask#156128]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

The cask [tsh](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/t/tsh.rb) does not provide separate versions for install (e.g. `tsh@14`, `tsh@13`, etc), but tsh is incompatible across major version changes.

From the [Teleport install guide](https://goteleport.com/docs/installation/):
> For best results, Teleport clients (`tsh`, `tctl`, `tbot`) should be the same major version as the cluster they are connecting to. Teleport servers are compatible with clients that are on the same major version or one major version older. Teleport servers do not support clients that are on a newer major version.

In my particular situation, we're using Teleport v13, and `brew upgrade` updates my local tsh from `13.3.8` to `14.0.0` which is not compatible.

### Command that failed

brew search tsh@13

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading tsh
==> Casks
tsh ✔
Use `brew desc` to list packages with a short description.
```

### Output of `brew doctor` and `brew config`

```shell
## brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  exa

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python-certifi

## brew-config
HOMEBREW_VERSION: 4.1.13-4-gf1d345a
ORIGIN: https://github.com/Homebrew/brew
HEAD: f1d345a60e2c02f7e5c1b7930601b1921432cfb6
Last commit: 10 hours ago
Core tap JSON: 25 Sep 22:04 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.2-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
flypenguin/okta-cli
homebrew/bundle
homebrew/cask-fonts
trufflesecurity/trufflehog
turbot/tap
```

**Comment by miccal** [comment]
We would consider a pull request to add a `tsh13` Cask to the `homebrew-cask-versions` repository.
