### ISSUE TITLE
Please Add 64Gram (Telegram Client) Cask

### ISSUE THREAD

**Issue by felipemeamaral** [Homebrew/homebrew-cask#156449]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

The 64Gram Telegram client (https://github.com/TDesktop-x64/tdesktop) is not available no Homebrew.
It is a Telegram client with a lot of features like:

- Show admin titles in member list
- Download/Upload Speed Boost
- Disable Premium Animations
- Auto/Manual Messages Translation
- Show chat restriction reason on profile page
- Ban members option in Recent Actions
- Show Chat ID
- Always show discuss button if channel has discussion group
- Mark All Chats As Read for "All Chats" Folder
- [Voice Chat Radio mode](https://t.me/tg_x64/238)
- [Auto unmute option](https://t.me/tg_x64/266)
- Voice chat bitrate option
- Hide "All chats" folder option
- Search Messages From User(Right click user pic or member list)
- Allow open link without warning
- [Hide messages from blocked user](https://t.me/tg_x64/519)
- Copy inline button callback data to Clipboard
- Expose all chat permissions setting
- Show bot privacy in member list and profile
- Show admin title in admin list
- Always Show Scheduled Button option
- Repeat user message to current group
- Recent Actions/Admins list button in top bar
- Show service message time
- Show message ID in tooltip/message box
- Gif Shared Media section
- Don't share my phone number when add someone to contacts
- Multiple accounts up to 100
- Support multiple chat forward
- Support Forward Message without quote
- Quick Forward to Saved Messages
- [Restore] Convert to Supergroup feature
- [Restore] upgraded to supergroup service message
- Create new supergroup
- [Restore] Discussion group button
- [Mention user via Create Link with tg://user?id=123456](https://t.me/tg_x64/156)
- User Bio clickable
- tg://openmessage and tg://user clickable
- Show user total sent messages when you're deleting a message
- Shortcut for Fast Forward/Copy messages (ALT+F/ALT+C)
- Always delete message option(Group/Person/Both)
- Show Phone Number option
- View Channel Button in Group Info widget
- Show online member count if supergroup member >= 200 and more accurate
- Disable Cloud Draft Sync To Local
- Show/Hide/View pinned message
- Pin to top (Windows only)
- Allow pin older message with notify
- Remove all proxies
- Hide 1 to 1 call panel window when press X(close window)
- Allow pin Voice Chat window to top
- Message time with seconds
- Ban button for Join Requests

### Command that failed

brew search 64gram

### Output of command with `--verbose --debug`

```shell
$ brew search 64gram --verbose --debug
Error: No formulae or casks found for "64gram".
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/extend/kernel.rb:83:in `exit'
/usr/local/Homebrew/Library/Homebrew/extend/kernel.rb:83:in `odie'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:150:in `print_results'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:86:in `search'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
$ brew doctor  
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  exa

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libndi.dylib

---

$ brew config 
HOMEBREW_VERSION: 4.1.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: a8519f78fb63f2f2266950bdd8141037da69f8bd
Last commit: 3 days ago
Core tap JSON: 27 Sep 20:33 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BAT_THEME: OneHalfDark
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 36
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 36-core 64-bit haswell
Clang: 15.0.0 build 1500
Git: 2.42.0 => /usr/local/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.2-x86_64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A
```

### Output of `brew tap`

```shell
$ brew tap            
beeftornado/rmtree
cyansalt/cask
homebrew/cask-fonts
homebrew/cask-versions
homebrew/services
oven-sh/bun
shopify/shopify
```

**Comment by krehel** [comment]
Hi @felipemeamaral 

Would you like to try to create this Cask?

https://docs.brew.sh/Cask-Cookbook

Thanks

**Comment by miccal** [comment]
* Issues requesting new casks will be closed. If you want a cask added to the main repositories, [submit a pull request](https://github.com/Homebrew/homebrew-cask/blob/HEAD/CONTRIBUTING.md#adding-a-cask).
