### ISSUE TITLE
SHA256 mismatch at package "textsniper"

### ISSUE THREAD

**Issue by Christoph-Beckmann** [Homebrew/homebrew-cask#156713]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config:

HOMEBREW_VERSION: 4.1.14-7-gb855a9e
ORIGIN: https://github.com/Homebrew/brew
HEAD: b855a9eae8b7daf5fa7fbe4acc111c57024c2307
Last commit: 2 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fb20a84310f2a7d72fbab5c16b55878fca8c5348
Core tap last commit: 40 minutes ago
Core tap branch: master
Core tap JSON: 02 Oct 17:43 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_AUTO_UPDATE_SECS: 259200
HOMEBREW_AUTOREMOVE: set
HOMEBREW_CASK_OPTS: ["--no-quarantine"]
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 60
HOMEBREW_DISPLAY_INSTALL_TIMES: set
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_GITHUB_API: set
HOMEBREW_NO_INSTALL_CLEANUP: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.42.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.2-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: 15.0
Rosetta 2: false

----------------------

brew doctor:

Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

For sure, I removed and tried to reinstall after removing the download. I also checked the checksum after downloading the build from the owner of this software and indeed the checksum is wrong.

### What happened (include all command output)?

==> Downloading https://s3.amazonaws.com/textsniper.app/TextSniper1.10.dmg
####################################################################################################################################################################### 100.0%
Error: SHA256 mismatch
Expected: ecf2f88225e818c2fb605821f03e76bc1731ce36a2fd7d9ba8e46ef3bcf7d5b2
  Actual: a6be6174b043250c946b6c6be2b5753871c78817e90c29d3e9d4871d5b7b3072
    File: /Users/christophbeckmann/Library/Caches/Homebrew/downloads/ceb94fcd7fdfbf19ed19c48c92236f24c19cccd53d2f1d3ffcd7288e266f9d2e--TextSniper1.10.dmg
To retry an incomplete download, remove the file above.

### What did you expect to happen?

Should actually be installed

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install textsniper
```

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/156723
