### ISSUE TITLE
Zenmap doesn't look in brew path to find its nmap executable

### ISSUE THREAD

**Issue by cbrunnkvist** [Homebrew/homebrew-cask#156974]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

Zenmap installed as cask seems to not come preconfigured to look for the required `nmap` program in the right place, despite pulling that formula in as a dependency. 

I appreciate that Apps launched via Finder/Dock are not affected by PATH or other environment variables that we set in our shells - but wouldn't it be expected to, if not modify the template for `~/.zenmap/zenmap.conf`, at least print some message to let the user know that it is "supposed" to fail and hint about possible workarounds?

### Command that failed

Launching `/Applications/Zenmap.app` via Finder/Docker, etc.

### Output of command with `--verbose --debug`

```shell
(not applicable)
```

### Output of `brew doctor` and `brew config`

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libwkhtmltox.0.12.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h
```

```
HOMEBREW_VERSION: 4.1.14-41-g8c91152
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8c91152eb66fbbbbb2e01bc3bad086f6ef0846c9
Last commit: 81 minutes ago
Core tap JSON: 05 Oct 16:03 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.2-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A
Rosetta 2: false
```
```


### Output of `brew tap`

```shell
coursier/formulas
homebrew/services
saulpw/vd
```
```

**Comment by SMillerDev** [comment]
Casks are installed as upstream distributes them. You should take this report to upstream so they can fix it properly

**Comment by razvanazamfirei** [comment]
@cbrunnkvist, thank you for opening this! We can potentially add a caveat that would show up during the installation process. Do you have a suggestion on what that could look like?

**Comment by krehel** [comment]
Thanks for reporting this @cbrunnkvist.

This looks to be an upstream issue at glance.  I took two machines that never had this software installed before to test.  

I had no issues on an Intel machine, Zenmap worked without any post configuration.

On an M1 machine, there's an error that `nmap` isn't in PATH, but seems to be because the Homebrew path is different on ARM and Intel.  Error below from Zenmap on the M1 -

![nmap](https://github.com/Homebrew/homebrew-cask/assets/39449589/bf09077f-69cf-4029-add2-5cd0dee270ba)

The PATH variable in the screenshot is definitely not my complete path, which includes `/opt/homebrew/bin` where the `nmap` binary is installed from Homebrew.

However....

On my M1 machine, this issue goes away if the Homebrew `nmap` isn't used, and instead the `nmap` shipped with Zenmap is.  That gets installed into `/usr/local/bin/nmap`

I suppose we could modify the install options for Zenmap to install `nmap` and don't use the Formula.

@SMillerDev - any thoughts?

**Comment by cbrunnkvist** [comment]
As you perhaps could tell, I am on an **M1** too and always had `brew --prefix` as `/opt/homebrew/`. And my error message dialog reads exactly identical.

> On my M1 machine, this issue goes away if the Homebrew nmap isn't used, and instead the nmap shipped with Zenmap is. That gets installed into /usr/local/bin/nmap

What do you mean exactly by "shipped with Zenmap"? As far as I can see, the cask dependency is just (? or maybe cask dependencies are different?) a formula dependency. Maybe I'm unaware of some Homebrew-Cask specificity, but here's my transcript uninstalling, verifying nothing in `/usr/local/bin/`, and reinstalling:  

```
conny@SEE20 ~ % brew uninstall zenmap nmap
Uninstalling /opt/homebrew/Cellar/nmap/7.94_1... (830 files, 26.9MB)
==> Uninstalling Cask zenmap
==> Uninstalling packages with sudo; the password may be necessary:
org.insecure.nmap.zenmap
==> Removing files:
/Applications/Zenmap.app
==> Purging files for version 7.94 of Cask zenmap
conny@SEE20 ~ % hash -r                   
conny@SEE20 ~ % nmap
zsh: command not found: nmap
conny@SEE20 ~ % ls -l /Applications/Zenmap*
zsh: no matches found: /Applications/Zenmap*
conny@SEE20 ~ % ls -l  /usr/local/bin/n*
lrwxr-xr-x  1 root  wheel  22 Oct  5 23:07 /usr/local/bin/nmap -> /opt/homebrew/bin/nmap ### THIS WAS JUST A TEMPORARY MANUAL WORKAROUND
conny@SEE20 ~ % sudo rm -f /usr/local/bin/nmap
conny@SEE20 ~ % ls -l  /usr/local/bin/n*    
zsh: no matches found: /usr/local/bin/n*
conny@SEE20 ~ % brew install zenmap
==> Downloading https://formulae.brew.sh/api/formula.jws.json
##################################################################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
##################################################################################################################### 100.0%
==> Downloading https://nmap.org/dist/nmap-7.94.dmg
Already downloaded: /Users/conny/Library/Caches/Homebrew/downloads/222d515e15530ebf3b53f22b3761e37753b0dd20a2388216fdd00e5b963af0b5--nmap-7.94.dmg
==> Installing dependencies: nmap
==> Downloading https://ghcr.io/v2/homebrew/core/nmap/manifests/7.94_1-2
##################################################################################################################### 100.0%
==> Fetching nmap
==> Downloading https://ghcr.io/v2/homebrew/core/nmap/blobs/sha256:aa642e107f9b1fb16d729c695610cc8aa6812d67c3509f3fb5d1edb1a
##################################################################################################################### 100.0%
==> Installing nmap
==> Pouring nmap--7.94_1.arm64_ventura.bottle.2.tar.gz
🍺  /opt/homebrew/Cellar/nmap/7.94_1: 830 files, 26.9MB
==> Installing Cask zenmap
[...]
```

The error / dialog remains the same as before, because nothing has changed: `which -a nmap ndiff`
still gives 
```
/opt/homebrew/bin/nmap 
/opt/homebrew/bin/ndiff
```
as expected.

**Comment by SMillerDev** [comment]
> What do you mean exactly by "shipped with Zenmap"

The tool ships it's own nmap binary if you let it

> Note that the auto-added user conf file specifies just unqualified executable names ([nmap docs](https://nmap.org/book/zenmap-files.html)):

But it doesn't use the system path though

> `sudo ln -vs $(which nmap ndiff) /usr/local/bin`

Homebrew won't install outside it's own prefix, and especially not into a prefix for x86 Homebrew

**Comment by cbrunnkvist** [comment]
Thanks, can confirm it "just works" now, no matter which order or combination of nmap/zenmap packages I install. 👍
