### ISSUE TITLE
Please rename owasp-zap cask to zap or zaproxy

### ISSUE THREAD

**Issue by psiinon** [Homebrew/homebrew-cask#157575]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

ZAP is no longer part of OWASP: https://www.zaproxy.org/blog/2023-08-01-zap-is-joining-the-software-security-project/
As a result we'd like the ZAP cask to be renamed from "owasp-zap" to either "zap" or "zaproxy".

### Command that failed

n/a

### Output of command with `--verbose --debug`

```shell
n/a
```

### Output of `brew doctor` and `brew config`

```shell
n/a
```

### Output of `brew tap`

```shell
n/a
```

**Comment by razvanazamfirei** [comment]
Hi @psiinon,

Thank you for letting us know! I opened a PR to rename the cask.
