### ISSUE TITLE
`temurin20` is missing for arm (M1 macs)

### ISSUE THREAD

**Issue by miridius** [Homebrew/homebrew-cask#157718]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

After #157495, it's no longer possible to install temurin JDK 20 on arm. temurin used to point to 20, and it was updated to point to 21, but there's no version of the cask that points to 20.

I suspect it's because https://api.adoptium.net/v3/info/release_versions?release_type=ga&page_size=100&architecture=arm doesn't list major version 20 (but https://api.adoptium.net/v3/info/release_versions?release_type=ga&page_size=100 does!)

### Command that failed

brew install --cask temurin20

### Output of command with `--verbose --debug`

```shell
Warning: Cask 'temurin20' is unavailable: No Cask with this name exists.
==> Searching for similarly named casks...
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading temurin
==> Casks
temurin ✔                         temurin11                         temurin17                         temurin18                         temurin19                         temurin21                         temurin8

To install temurin ✔, run:
  brew install --cask temurin ✔
```

### Output of `brew doctor` and `brew config`

```shell
❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libfdb_c.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/foundationdb/fdb_c.h
  /usr/local/include/foundationdb/fdb_c_internal.h
  /usr/local/include/foundationdb/fdb_c_options.g.h
  /usr/local/include/foundationdb/fdb_c_types.h

❯ brew config
HOMEBREW_VERSION: 4.1.15
ORIGIN: https://github.com/Homebrew/brew
HEAD: e57a87cfe9c15f192cd4fc6695a2b3b7acf0ddf7
Last commit: 7 days ago
Core tap JSON: 16 Oct 10:51 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: ["--no-quarantine"]
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.42.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.6-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
aws/tap
bazelbuild/tap
borkdude/brew
clojure/tools
homebrew/autoupdate
homebrew/cask-fonts
homebrew/cask-versions
```

**Comment by SMillerDev** [comment]
That's not a supported version anymore afaik

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask-versions/pull/18035
