### ISSUE TITLE
kicad-cli: failed to load shared library

### ISSUE THREAD

**Issue by xobs** [Homebrew/homebrew-cask#157716]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

When attempting to use `kicad-cli`, it errors out with "Failed to load shared library":

```
$ kicad-cli sch export python-bom -o pcb-evt1.csv pcb-evt1.kicad_sch
16:28:44: Error: Failed to load shared library '/opt/Contents/PlugIns/_eeschema.kiface': dlopen(/opt/Contents/PlugIns/_eeschema.kiface, 0x000A): tried: '/opt/Contents/PlugIns/_eeschema.kiface' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/Contents/PlugIns/_eeschema.kiface' (no such file), '/opt/Contents/PlugIns/_eeschema.kiface' (no such file)
16:28:44: Error: Failed to load kiface library '/opt/Contents/PlugIns/_eeschema.kiface'.
```

### Command that failed

kicad-cli sch export python-bom pcb-evt1.kicad_sch

### Output of command with `--verbose --debug`

```shell
$ kicad-cli --verbose --debug                                            (base) 
Unknown argument: --verbose
Usage: kicad-cli [-h] {fp,pcb,sch,sym,version}

Optional arguments:
  -v, --version	prints version information and exits 
  -h, --help   	shows help message and exits 

Subcommands:
  fp            
  pcb           
  sch           
  sym           
  version       
```
```


### Output of `brew doctor` and `brew config`

```shell
$ brew doctor                                                            (base) 
Your system is ready to brew.
$ brew config                                                            (base) 
HOMEBREW_VERSION: 4.1.15
ORIGIN: https://github.com/Homebrew/brew
HEAD: e57a87cfe9c15f192cd4fc6695a2b3b7acf0ddf7
Last commit: 7 days ago
Core tap JSON: 16 Oct 08:28 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.2rfmUi9UNZ/org.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.0-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A
Rosetta 2: false
$
```
```


### Output of `brew tap`

```shell
$ brew tap                                                               (base) 
filosottile/musl-cross
gcenx/wine
homebrew/cask-versions
riscv-software-src/riscv
$
```
```

**Comment by bevanjkay** [comment]
@xobs Does the same issue occur if you download and install `kicad` manually? At face value, this does not look like a Homebrew specific issue.

**Comment by xobs** [comment]
@bevanjkay it does work if I install `kicad` manually, by copying it to `/Applications/` (after renaming the existing install from Homebrew to `/Applications/KiCad-homebrew/`):

```text
$ /opt/homebrew/bin/kicad-cli sch export netlist Farpatch.kicad_sch
13:20:50: Error: Failed to load shared library '/opt/Contents/PlugIns/_eeschema.kiface': dlopen(/opt/Contents/PlugIns/_eeschema.kiface, 0x000A): tried: '/opt/Contents/PlugIns/_eeschema.kiface' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/Contents/PlugIns/_eeschema.kiface' (no such file), '/opt/Contents/PlugIns/_eeschema.kiface' (no such file)
13:20:50: Error: Failed to load kiface library '/opt/Contents/PlugIns/_eeschema.kiface'.

$ /Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli sch export netlist Farpatch.kicad_sch 
$

**Comment by krehel** [comment]
Not knowing anything in specific about `kicad` but this looks like it could be a hard-coded path for something in `kicad-cli` looking back for `../../Contents/Plugins` for files, but those files don't exist in `opt` where `kicad-cli` is installed.

**Comment by bevanjkay** [comment]
> Who is in a position to fix this issue?

As a `kicad` user, you are likely best positioned to try to fix this issue. It's unlikely than any `homebrew-cask` maintainers are users of `kicad`.

**Comment by xobs** [comment]
Who is the maintainer of that recipe? Or do recipies not have maintainers?

Is there a way to list "known issues" of a recipe so that other users can know of problems that have not been fixed? I worry that if I leave it here in "Issues" it'll get closed by @github-actions

**Comment by bevanjkay** [comment]
Individual casks do not have maintainers, anybody is welcome and encouraged to open PRs to fix issues that arise.

**Comment by krehel** [comment]
A workaround may be to simply stop putting linking the binaries for this Cask and instead advising to add `/Applications/KiCad/KiCad.app/Contents/MacOS` to $PATH.

Again, from my comment above, it seems that `kicad-cli` is just looking back a few directories for libraries as a relative path and not as an absolute path.
