### ISSUE TITLE
brew package "helix" causes segfault on macOS 14.x

### ISSUE THREAD

**Issue by spe888** [Homebrew/homebrew-cask#158071]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

The brew package "helix" is outdated and causes some major issues when using it. On my system macOS 14.0 causes a segfault (I didnt have this problem on macOS 13.x), other users experience this as well (e.g. https://github.com/helix-editor/helix/issues/8415).

### Command that failed

brew install helix

### Output of command with `--verbose --debug`

```shell
https://github.com/helix-editor/helix/issues/8415
```

### Output of `brew doctor` and `brew config`

```shell
brew doctor
Your system is ready to brew.

brew config
HOMEBREW_VERSION: 4.1.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: c0c8a4dd4dd19ec16deb429abd50cdf82ea33b27
Last commit: 5 days ago
Core tap JSON: 19 Oct 12:27 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_REPOSITORY: /opt/homebrew/Homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.0-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
homebrew/services
```

**Comment by bevanjkay** [comment]
@spe888 This issue should be raised in the [`homebrew-core`](https://github.com/homebrew/homebrew-core) repository.

**Comment by spe888** [comment]
@bevanjkay sry, I've reopened it on homebrew-core https://github.com/Homebrew/homebrew-core/issues/151893
