### ISSUE TITLE
Spotify app on Arm is unsigned

### ISSUE THREAD

**Issue by PythonCoderAS** [Homebrew/homebrew-cask#158113]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

The Spotify cask that is installed is unsigned because every time I try to launch it I get an unsigned app error.

### Command that failed

brew install --cask spotify

### Output of command with `--verbose --debug`

```shell
N/A
```

### Output of `brew doctor` and `brew config`

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  lua@5.1
```

```
HOMEBREW_VERSION: 4.1.16-11-g3480dda
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3480dda0c7297bc161b7726d026395efec0815bd
Last commit: 19 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3c1408e72eaa44545ead62fff22a0866a42033ae
Core tap last commit: 9 months ago
Core tap branch: master
Core tap JSON: 19 Oct 13:51 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
homebrew/cask
homebrew/cask-fonts
homebrew/core
homebrew/services
pythoncoderas/brew
pythoncoderas/temp-versions
wabarc/wayback
zmwangx/npm-noob
```

**Comment by SMillerDev** [comment]
Not sure what brew can do about that.

**Comment by PythonCoderAS** [comment]
It's not unsigned when I download via the official website.

**Comment by bevanjkay** [comment]
@PythonCoderAS The official website provides the installation via an installer, not directly to the app.
The installer package may remove the quarantine attribute rather than signing the application properly, but is not able to run unattended by Homebrew.
