### ISSUE TITLE
VirtualBox installed via homebrew cask ~10x slower than expected

### ISSUE THREAD

**Issue by GlenHenshaw** [Homebrew/homebrew-cask#159257]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

Using a MacBook Air (13-inch, 2017), macOS 12.7

VirtualBox installs via the cask, but while attempting to install Windows 10, its performance is terrible, approximately 10-20x slower than VirtualBox as installed via the installer on the Virtualbox home page.

Windows 10 installation process takes something longer than 3 hours (I had to let it run overnight), as compared to <1 hr with the direct install. Boot time is measured in tens of minutes, as opposed to <1 minute, etc.

Not sure how to go about debugging this, happy for suggestions.

On a potentially completely unrelated note, brew config reports that my machine has a "CPU: quad-core 64-bit broadwell". In fact I have a dual core system. I know that if you tell VirtualBox to use more cores than you physically have, performance takes a considerable hit. However, I verified in the VirtualBox settings for my VM that it was to use either 1 or 2 cores. I also adjusted the RAM it was allows up to 4G (my system has 8). Neither change made an appreciable difference.

### Command that failed

no command failed

### Output of command with `--verbose --debug`

```shell
NA
```

### Output of `brew doctor` and `brew config`

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The following directories are not writable by your user:
/usr/local/share/man/man8

You should change the ownership of these directories to your user.
  sudo chown -R glen /usr/local/share/man/man8

And make sure that your user has write permission.
  chmod u+w /usr/local/share/man/man8



glen@Glens-MacBook-Air ~ % brew config
HOMEBREW_VERSION: 4.1.18
ORIGIN: https://github.com/Homebrew/brew
HEAD: bf8991f0d777fe8e33105f0cd7bf1e5993eed60a
Last commit: 5 days ago
Core tap JSON: 31 Oct 23:15 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.MSN7WOj73N/org.xquartz:0
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 14.0.0 build 1400
Git: 2.42.0 => /usr/local/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 12.7-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
```

### Output of `brew tap`

```shell
glen@Glens-MacBook-Air ~ % brew tap
homebrew/cask-versions
```

**Comment by razvanazamfirei** [comment]
Hi @GlenHenshaw, 

Can you confirm the version of VirtualBox installed via Homebrew and the version you downloaded directly?
