### ISSUE TITLE
Replace GPXSee Cask by a Formula

### ISSUE THREAD

**Issue by tumic0** [Homebrew/homebrew-cask#159352]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

The GPXSee Cask installs a x86_64-only version of GPXSee as distributed by the project on its Sourceforge download page. This version apparently (I can't verify this myself) also works on the M1/M2/M3 arm Macs but with a significant performance penalty caused by the Rosetta emulation. As GPXSee is open-source, distributing GPXSee in homebrew using a Formula that will compile a native arm version seems as a much better choice for any recent Apple HW. Also note that there will be no "official" arm build of GPXSee as the project has no resources to do so and there is practically [zero user interest](https://github.com/sponsors/tumic0) to change that. 

There is already a [Macports package](https://github.com/macports/macports-ports/blob/master/gis/GPXSee/Portfile) of GPXSee that compiles fine on arm so I don't see any problem why the homebrew Formula should not work as well. The GPXSee project also builds every version using the latest versions of Qt (the only dependency) on Mac in it's [CI builds](https://github.com/tumic0/GPXSee/actions/workflows/osx.yml).

### Command that failed

brew install --cask gpxsee

### Output of command with `--verbose --debug`

```shell
N/A
```

### Output of `brew doctor` and `brew config`

```shell
N/A
```

### Output of `brew tap`

```shell
N/A
```

**Comment by SMillerDev** [comment]
Go for it, if you can make a formula for it we can then see what to do with the cask.

**Comment by tumic0** [comment]
Well, If I would be able to create/test an arm build, there would be an "official" arm build of GPXSee... But all I have is an ancient iMac 2009 with OS X 10.13 so I can't test an arm version nor an Qt6-based version (which should be probably preferred) on Mac. If no-one is willing to take care of the formula, then I'm ok with the current state where there is a statement on the GPXSee homepage saying: "don't use the homebrew version" and you may close the issue, but I still think homebrew can do better...

**Comment by SMillerDev** [comment]
Homebrew does as well as its community is willing to work for. You can always make a pull request for a formula with tests and see if it works.
