### ISSUE TITLE
Description printed when installing Mark-text brew cask isn't helpful.

### ISSUE THREAD

**Issue by keeely** [Homebrew/homebrew-cask#159554]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

The current text printed is:

```
    The Apple Silicon (arm) version of mark-text is not signed, and
    will display an error stating it is damaged and can't be opened.
```
See:
https://github.com/Homebrew/homebrew-cask/blob/master/Casks/m/mark-text.rb#L25

Install on arm is discussed in this mark-text issue:
https://github.com/marktext/marktext/issues/2983

And executing:
```
xattr -cr /Applications/MarkText.app
```
Appears to resolve the issue, but it isn't mentioned during the install.

Could we have either the solution or at least a link to the issue printed during install so users know what to do?

My suggestion:

```
    The Apple Silicon (arm) version of #{token} is not signed.  You may need to
    execute 'xattr -cr /Applications/MarkText.app' prior to running this on arm, see:
    https://github.com/marktext/marktext/issues/2983
```

### Command that failed

brew install --cask mark-text

### Output of command with `--verbose --debug`

```shell
==> Caveats
The Apple Silicon (arm) version of mark-text is not signed, and
will display an error stating it is damaged and can't be opened.

etc...
```

### Output of `brew doctor` and `brew config`

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  openssl@1.1

HOMEBREW_VERSION: 4.1.18
ORIGIN: https://github.com/Homebrew/brew
HEAD: bf8991f0d777fe8e33105f0cd7bf1e5993eed60a
Last commit: 9 days ago
Core tap JSON: 06 Nov 12:07 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.6.1-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
homebrew/bundle
homebrew/cask-versions
homebrew/services
mongodb/brew
```

**Comment by SMillerDev** [comment]
We will not recommend people to remove security features. The correct fix is for the user to file an issue with mark-text so they start correctly signing their software.

**Comment by keeely** [comment]
If you don't want a recommendation to remove a security feature simply remove that part, in other words:

```
    The Apple Silicon (arm) version of #{token} is not signed.  See:
    https://github.com/marktext/marktext/issues/2983 for details.
```

Then the user can decide what to do (including complain or fund the signing if they want to).

**Comment by arcataroger** [comment]
> I'll happily review a pull request to that extend

@SMillerDev, I made a PR for it: https://github.com/Homebrew/homebrew-cask/pull/160508/files

Thank you!
