### ISSUE TITLE
Openfortivpn seems broken since last update

### ISSUE THREAD

**Issue by foss4ever** [Homebrew/homebrew-cask#160222]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

Since last week I have been unable to use openfortivpn as it no longer manages connect to our FortiGate VPN gateway.

When starting a connection I do get to the 2FA prompt, and having authenticated in the FortiToken app, openfortivpn then halts at "Committed PPP store" - seemingly unble to bring up the vpn tunnel adapter / interface, ppp0.

After having waited a while, I then hit ctrl+c and this results in additional output as seen below the yellow line:

![image](https://github.com/Homebrew/homebrew-cask/assets/72194332/110c33b7-d9d3-4ed0-833d-b44ba52a39aa)

I tested the same VPN connection in the official FortiClient app for MacOS and that works just fine.

I then ended up downgrading openfortivpn to previous version 1.20.5 and that has resolved the issue, however I of course do hope I can get back on the latest version when the underlying problem introduced with version 1.21.0 has been taken care of.

My platform is MacOS, specifically Sonoma 14.1.1, and hardware-wise I'm on a Macbook Air M1 (2020).

Over at the openfortvpn Github issues, I was able to get in contact with one of the developers, and they provide the following solution (seems the problem comes down to MacOS using a legacy version of the point to point protocol daemon, pppd):

_Packagers should build openfortivpn with configure --enable-legacy-pppd, required for platforms still shipping pppd < 2.5.0._

Source: https://github.com/adrienverge/openfortivpn/issues/1165#issuecomment-1811316948

Now, I don't personally know how to get any changes made in homebrew packages, so I would ask if someone could help to implement this fix?

### Command that failed

openfortivpn -c <vpn_config>

### Output of command with `--verbose --debug`

```shell
n/a
```

### Output of `brew doctor` and `brew config`

```shell
n/a
```

### Output of `brew tap`

```shell
n/a
```

**Comment by krehel** [comment]
Closing as a duplicate.  This is in Homebrew/core anyway, and not a Cask.  

https://github.com/Homebrew/homebrew-core/issues/154319
