### ISSUE TITLE
The intel hash is mismatched for onlyoffice 7.5.1

### ISSUE THREAD

**Issue by elesto** [Homebrew/homebrew-cask#160900]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

The intel hash is mismatched for onlyoffice 7.5.1 and I cannot install it.

### Command that failed

brew install onlyoffice

### Output of command with `--verbose --debug`

```shell
==> Downloading https://github.com/ONLYOFFICE/DesktopEditors/releases/download/v7.5.1/ONLYOFFICE-x86_64.dmg
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/69867298/fa496e97
############################################################################################################ 100.0%
Error: SHA256 mismatch
Expected: 62b2cdf1b02e550f6f41407dfa07d325628b746eefec021e795ec3c189feefed
  Actual: daf7c8500801665eb5369900ff77e60d0e4c8cfc99e023d59dc8583a4f0d7c54
```

### Output of `brew doctor` and `brew config`

```shell
t
```

### Output of `brew tap`

```shell
t
```

**Comment by bevanjkay** [comment]
Please see the link to the documentation regarding checksum mismatch which you ticked that you "made doubly sure this is not a checksum error".
https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match

**Comment by elesto** [comment]
Well I searched their website and downloaded the official 7.5.1 dmg and the hash is indeed the same as which brew downloaded. The one in the cask code is wrong.

**Comment by bevanjkay** [comment]
Please try to submit a fix with the following command:
`brew bump-cask-pr --sha256 daf7c8500801665eb5369900ff77e60d0e4c8cfc99e023d59dc8583a4f0d7c54 onlyoffice`

**Comment by elesto** [comment]
Im getting 
`Error: Cask 'onlyoffice' is unavailable: No Cask with this name exists.`
This must be because its not installed

**Comment by elesto** [comment]
So in the future I should try bump-caks-pr for hash mismatches?
