### ISSUE TITLE
wireshark installs ChmodBPF.pkg

### ISSUE THREAD

**Issue by jsimonetti** [Homebrew/homebrew-cask#162189]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

The wireshark cask installs ChmodBPF.pkg
This appears to be an oversight, as there is a special cask wireshark- chmodbpf that does explicitly that only.

I would assume that the cask wireshark would skip that part and if you want to do capturing, you also install wireshark-chmodbpf.

### Command that failed

brew install --cask wireshark

### Output of command with `--verbose --debug`

```shell
not applicable
```

### Output of `brew doctor` and `brew config`

```shell
not applicable
```

### Output of `brew tap`

```shell
not applicable
```

**Comment by bevanjkay** [comment]
It is currently setup so that both `wireshark` and `wireshark-chmodbpf` cannot be installed at the same time.
The cask installs the entirety of the `wireshark` packages as provided by upstream.
It looks like the `wireshark-chmodbpf` package is provided separately for those who manage their `wireshark` installation outside of Homebrew, but would like to install the extra.

**Comment by jsimonetti** [comment]
Thank you for explaining. I wasn't aware that they are mutually exclusive.
I made some assumptions about its use that where incorrect.
