### ISSUE TITLE
garmin-basecamp missing

### ISSUE THREAD

**Issue by spencermathews** [Homebrew/homebrew-cask#162155]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

Please add back the garmin-basecamp Cask. It was left behind when homebrew-cask-drivers was deprecated.

### Command that failed

brew install garmin-basecamp

**Comment by bevanjkay** [comment]
@spencermathews Can you open a PR to add the cask here?
