### ISSUE TITLE
`depends_on :java`

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-cask#16383]
Builds on https://github.com/caskroom/homebrew-cask/issues/7993.

Interface for `depends_on :java`:
- Similar to [`depends_on :macos`](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#depends_on-macos) and [`depends_on :x11`](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#depends_on-macos). Valid examples:
  - `depends_on java: true` # any java version
  - `depends_on java: '8'` # exact version
  - `depends_on java: ['6', '7']` # any of array of versions
  - `depends_on java: '>= 6'` # equal to or greater than version

**Comment by adityadalal924** [comment]
Early implementation followup at https://github.com/caskroom/homebrew-cask/issues/16591

**Comment by adm745** [comment]
https://github.com/Homebrew/homebrew-cask/issues/16383#issue-124979701

**Comment by adm745** [comment]
#91518

**Comment by vitorgalvao** [comment]
@reitermarkus What about we scrap this, remove the `depends_on_java` `caveat` and start making those casks `depends_on formula: 'openjdk'`? Do you foresee major problems with that approach? Alternatively, seeing as we’re so integrated with HB, would it be viable to use whatever formulae use to check for java?

**Comment by reitermarkus** [comment]
`depends_on formula: 'openjdk'` does not install it globally, i.e. link it to `/Library/Java/JavaVirtualMachines` which most GUI apps probably depend on.

**Comment by CAMOBAP** [comment]
Is there a way to achieve `depends_on java: '>= 6'` behavior? Or the implementation still on the way?

**Comment by vitorgalvao** [comment]
> Is there a way to achieve `depends_on java: '>= 6'` behavior?

No.

> Or the implementation still on the way?

Also no. The feature is desirable, but no one is working on it. This has never evolved in six years. Either we get an outside contribution for it, or we abandon it.

**Comment by reitermarkus** [comment]
There is now an `openjdk` formula and `depends_on :java` in formulae is deprecated if not already removed.

**Comment by CAMOBAP** [comment]
@vitorgalvao @reitermarkus what if I will add `depends_on openjdk@8`, does it mean that my formula depends exactly on java 8, and will download java 8 even if java 11 available?

**Comment by reitermarkus** [comment]
Yes. You should always depend on the latest version unless an older version is actually necessary.

**Comment by MikeMcQuaid** [comment]
Closing this, as-of https://github.com/Homebrew/brew/pull/11290 being merged I think we're as good as we're going to get here and it's been open without progress for a long time.
