### ISSUE TITLE
Some of my paid apps are listed, can they be removed?

### ISSUE THREAD

**Issue by jordibruin** [Homebrew/homebrew-cask#163897]
### Verification

- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### Provide a detailed description of the proposed feature

My apps MacWhisper and MacGPT are listed even though they are paid. Can they be removed?

### What is the motivation for the feature?

My paid apps are offered for free 🙂 

### How will the feature be relevant to at least 90% of Homebrew users?

Yes

### What alternatives to the feature have been considered?

To remove my apps 🙂

**Comment by p-linnane** [comment]
Hello. I see MacWhisper has a free tier, so should not be an issue. MacGPT is paid only, so we will remove that. I believe it was assumed a paid license key was needed to use MacGPT when it was added. We have many other pieces of software that will install via Homebrew, but be useless without a license key. Our apologies for including that one. I'll submit a PR to remove MacGPT now.

**Comment by p-linnane** [comment]
@jordibruin MacGPT has been removed. I'd recommend you change the download link if you can, because it is still visible in the git history. I'd like to extend our apologies again and appreciate you raising the issue so we could address it.

**Comment by jordibruin** [comment]
Thanks @p-linnane for the quick action! Even though MacWhisper has a free tier, I want users to get access to it through my website so that I can contact them about updates and feedback. Hope you can also remove that one.

MacGPT used to have a free tier as well, which is probably why it was added, but I don't think that should allow someone to add it here without my permission. Can you point me to where I can read more about the process/policies about which apps can be added?

Thanks again for the swift action 🙂

**Comment by bevanjkay** [comment]
@jordibruin Anyone can submit an app to `homebrew-cask`. All we do is allow a headless install of an app/pkg using command line. We don't host any files, they are retrieved from a publicly accessible url (using curl) and then unpackaged. 

Our users (myself included) find it a much less tedious method to install/upgrade application as you don't have to navigate to the website, unpackage the download, run the installer, etc...

Your applications were very likely submitted by regular users of your software who manage other apps using Homebrew and wanted to do the same for yours.

**Comment by MikeMcQuaid** [comment]
> A side note would be that if you are serious about users requiring signup to download your apps, then using a different distribution method may be more suitable as the current does allow for direct downloading if the source is discovered. ie. require a token from a submitted form to authenticate the download.

Indeed. Removing the cask here still means anyone can copy-paste the existing cask and download this software unless you make changes on your end.
