### ISSUE TITLE
Check signatures with gnupg?

### ISSUE THREAD

**Issue by ioerror** [Homebrew/homebrew-cask#164]
The Tor Browser has signatures for each release:
https://www.torproject.org/dist/torbrowser/osx/TorBrowser-2.3.25-2-osx-i386-es-ES.zip
https://www.torproject.org/dist/torbrowser/osx/TorBrowser-2.3.25-2-osx-i386-es-ES.zip.asc

And we publish a set of keys that are likely to sign them:
https://www.torproject.org/docs/verifying-signatures.html

I'd like to add the proper keys to my Tor Browser formula and have the signatures checked at install time.

**Comment by hellais** [comment]
Here is some broken code I wrote a long time ago to add support for what I described in #22238. If there is interest in this I could pick it back up again: https://github.com/hellais/homebrew/tree/feature/package-signing.
