### ISSUE TITLE
muCommander 1.3.0 cannot be opened

### ISSUE THREAD

**Issue by nandi95** [Homebrew/homebrew-cask#164121]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

When you install the formula you get the error "muCommander is damaged and can't be opened"
This is related to: https://github.com/mucommander/mucommander/issues/999 and can be fixed by running
```sh
sudo xattr -cr /Applications/muCommander.app
```
Related file: https://github.com/Homebrew/homebrew-cask/blob/feae25707e5658cc26fc2ff35702211a040b4614/Casks/m/mucommander.rb

### Command that failed

brew install mucommander

### Output of command with `--verbose --debug`

```shell
not relevant
```

### Output of `brew doctor` and `brew config`

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  node@16
  openssl@1.1

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docutils
  php





HOMEBREW_VERSION: 4.2.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: b3751bca8c4a3c76107d5aa3b75b81db93cf4bb6
Last commit: 2 days ago
Core tap JSON: 10 Jan 01:44 UTC
Core cask tap JSON: 10 Jan 01:44 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.43.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.2.1-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.2
Rosetta 2: false
```

### Output of `brew tap`

```shell
homebrew/cask-versions
homebrew/services
mongodb/brew
shivammathur/extensions
shivammathur/php
```

**Comment by bevanjkay** [comment]
This is an intended MacOS security feature. The best way forward is to encourage the developer to sign the application (as is already being discussed in the issue that you linked).
