### ISSUE TITLE
Remarkable desktop app has moved to the Apple Store

### ISSUE THREAD

**Issue by nhamilakis** [Homebrew/homebrew-cask#164484]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

I tried installing the Remarkable app using and when i opened the app a notification informed me that this version of the app will be deprecated in the future as the app has migrated to the App store [App Store URL](https://apps.apple.com/us/app/remarkable-desktop/id1276493162).

I tried doing an update, and a clean-install. Then i saw that [On the source of the cask](https://github.com/Homebrew/homebrew-cask/blob/49884d9255bc731976b11a79589146691bec92db/Casks/r/remarkable.rb) the installation is still from the vendor site (remarkable.com), it should be migrated to use the app store instead.

### Command that failed

brew install --cask remarkable

### Output of command with `--verbose --debug`

```shell
Command works normally with old version
```

### Output of `brew doctor` and `brew config`

```shell
HOMEBREW_VERSION: 4.2.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: b3751bca8c4a3c76107d5aa3b75b81db93cf4bb6
Last commit: 8 days ago
Core tap JSON: 15 Jan 19:56 UTC
Core cask tap JSON: 15 Jan 19:52 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BROWSER: vivaldi
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /opt/homebrew/bin/code
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.43.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.2.1-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
brew tap
gromgit/fuse
homebrew/bundle
homebrew/services
```

**Comment by bevanjkay** [comment]
We are not able to install applications from the App Store, so we will need to deprecate `remarkable`, and add a caveat to use the App Store version instead.
