### ISSUE TITLE
rode-connect fails to install due to wrong version

### ISSUE THREAD

**Issue by felixthiele** [Homebrew/homebrew-cask#165108]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

The ["rode-connect" cask](https://github.com/Homebrew/homebrew-cask/blob/6c1ccf05fee04dd807f2efe6d971f1a5c489aba3/Casks/r/rode-connect.rb#L2) is currently labeled as version `1.3.31`. RODE has since released version `1.3.33`, but unfortunately, homebrew tries to install a pkg file with version 1.3.31 from the URL that does not exist. 

Since I cannot install rode-connect via homebrew, I cannot use `brew bump --open-pr rode-connect`. Can / should one manually bump the version in the cask? If yes, I can gladly submit a PR. 

### Command that failed

brew install rode-connect

### Output of command with `--verbose --debug`

```shell
Error: Could not find PKG source file 'RØDE Connect (1.3.31).pkg', found 'RØDE Connect (1.3.33).pkg' instead.
```

### Output of `brew doctor` and `brew config`

```shell
not relevant
```

### Output of `brew tap`

```shell
not relevant
```

**Comment by bevanjkay** [comment]
Unfortunately, in this case the `url` that RODE use to notify that there is a new version has not been updated for some time.
https://update.rode.com/rode-devices-manifest.json
