### ISSUE TITLE
"Stats.app" cannot be opened because the developer cannot be verified

### ISSUE THREAD

**Issue by X-dark** [Homebrew/homebrew-cask#165584]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

Each time Stats is upgraded by Brew, macOS is complaining about "developer cannot be verified". Uninstalling then reinstalling the app, fixes it (until the next upgrade).
cf https://github.com/exelban/stats/issues/1469 and https://github.com/exelban/stats/issues/1562

### Command that failed

Stats.app

### Output of command with `--verbose --debug`

```shell
N/A
```

### Output of `brew doctor` and `brew config`

```shell
❯ brew doctor
Your system is ready to brew.

❯ brew config
HOMEBREW_VERSION: 4.2.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: cfac516ee045d869be34598152e80a11ef2befe7
Last commit: 2 days ago
Core tap JSON: 30 Jan 15:01 UTC
Core cask tap JSON: 30 Jan 15:01 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: ["--appdir=~/Applications"]
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_UPGRADE_GREEDY: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.3-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
❯ brew tap
homebrew/cask-fonts
homebrew/services
michaelroosz/ssh
theseal/ssh-askpass
```

**Comment by vraravam** [comment]
I have the same problem with Stats while none of the other apps exhibit this behavior.
I have the following in my `Brewfile`:
`cask_args appdir: '/Applications', no_quarantine: true`

**Comment by SMillerDev** [comment]
What does `codesign -v <app location>` say?

**Comment by X-dark** [comment]
```
❯ codesign -v -v ~/Applications/Stats.app
/Users/E0376464/Applications/Stats.app: valid on disk
/Users/E0376464/Applications/Stats.app: satisfies its Designated Requirement
```

**Comment by vraravam** [comment]
pinging to remove staleness

**Comment by bevanjkay** [comment]
@vraravam @X-dark 
Can you confirm whether or not you have the "fan helper" installed?

**Comment by vraravam** [comment]
i dont think i have that installed @bevanjkay

**Comment by Moulick** [comment]
I have the fan helper installed. This issue happens to me mostly after I restart my machine. `Spotify` and `Stats` almost always give me `developer cannot be verified` popup on machine startup.

**Comment by bevanjkay** [comment]
It definitely seems to be to do with the login items getting stuck in a state where maybe they are attached to the old version somehow. I haven't been able to find a way to track and fix the issue yet.

**Comment by Moulick** [comment]
Any information that we can gather to help figure out the issue?

Just as an side note, if MacOS fails to launch spotify/stats due to this issue, and I click cancel to prevent starting the apps, MacOS repeatedly tries to launch the apps again and again throwing the error popup again and again. Only solution is found is running `sudo xattr -rd com.apple.quarantine /Applications/Spotify.app` and then it starts

**Comment by NKjoep** [comment]
Still happening, and for everyone landing here while searching for a solution, this is still valid:

```
sudo xattr -rd com.apple.quarantine /Applications/Stats.app
```

**Comment by vraravam** [comment]
> ```
> sudo xattr -rd com.apple.quarantine /Applications/Stats.app
> ```

I am able to run the above command without `sudo` (YMMV) to effect this change.

**Comment by muescha** [comment]
still happening with version 3.0.1:

`codesign -v /Applications/Stats.app` gives no output

ls -ali /Applications/Stats.app
Permissions Size User    Date Modified    Name
drwxr-xr-x@    - muescha 2026-06-07 20:49 Contents/

**Comment by unbeatable-101** [comment]
Having this issue with version 3.0.3 as well. `codesign -v /Applications/Stats.app` also gave no output
