### ISSUE TITLE
Can't start homebrew cask as a service

### ISSUE THREAD

**Issue by scottmessinger** [Homebrew/homebrew-cask#167899]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

In the old version of the [clickhouse formula](https://github.com/ClickHouse/homebrew-clickhouse/tree/2befce0f018ee79a9bdc2cca07a04f877b3ae6fe?tab=readme-ov-file#running-clickhouse-server), it could be started as a service:

```
brew services start clickhouse
```

However, in the new cask, it's not clear (or not possible?) to start it as a cask:

```
% brew services start clickhouse 
Error: No available formula with the name "clickhouse". Did you mean clickhouse-cpp?
```

If I try to add `--cask` to mirror the install syntax, it doesn't work either:
```
% brew services start --cask clickhouse 
Error: invalid option: --cask
```

Am I doing something wrong? Or, when the other version was deprecated, did it also lose functionality?

### Command that failed

brew services start clickhouse 

### Output of command with `--verbose --debug`

```shell
% brew services start clickhouse --verbose --debug
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading clickhouse
Error: No available formula with the name "clickhouse". Did you mean clickhouse-cpp?
/opt/homebrew/Library/Homebrew/formulary.rb:856:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:970:in `factory'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:113:in `services'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
% brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  graphite

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  node@16
  openssl@1.1

Warning: Some installed formulae are not readable:
  xeroapi/taps/xoauth: wrong number of arguments (given 1, expected 0)


% brew config
HOMEBREW_VERSION: 4.2.10-62-g2aa8040
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2aa80402655472df8c1d37d979aca7f3c6ce415f
Last commit: 4 hours ago
Core tap JSON: 29 Feb 14:59 UTC
Core cask tap JSON: 29 Feb 14:59 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.38.1 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.1.2-arm64
CLT: N/A
Xcode: 15.2
Rosetta 2: false
```

### Output of `brew tap`

```shell
% brew tap
envkey/envkey
heroku/brew
homebrew/services
mongodb/brew
nats-io/nats-tools
screenplaydev/tap
withgraphite/tap
xeroapi/taps
```

**Comment by SMillerDev** [comment]
Casks do not have a service definition, so they can't be ran as a service.

**Comment by cho-m** [comment]
> In the old version of the [clickhouse formula](https://github.com/ClickHouse/homebrew-clickhouse/tree/2befce0f018ee79a9bdc2cca07a04f877b3ae6fe?tab=readme-ov-file#running-clickhouse-server),

Also, that's for the 3rd party tap.

There may be a naming overlap now that there is a `clickhouse` Cask added on 2023-09-03 (https://github.com/Homebrew/homebrew-cask/commit/dafea3508d1316c75ca0d29b776db4630927a72f).

You may want to install it with the tap name prepended, e.g. https://github.com/ClickHouse/homebrew-clickhouse/tree/2befce0f018ee79a9bdc2cca07a04f877b3ae6fe?tab=readme-ov-file#quick-start-one-liner

Or the versioned name which doesn't conflict, e.g. `clickhouse@23.5`

**Comment by scottmessinger** [comment]
That's really helpful to know -- thanks for the quick updates! To deprecate a formula for a community supported one makes complete sense. However, I find it unexpected, confusing, and frankly, quite frustrating for a functional package to be deprecated for something less functional. 

I doubt there's anything that can be done, but just wanted to note that this change was quite odd and I hope other packages don't become casks, given this limitation.

Thanks again for the quite info. I really, really appreciate it!!!
