### ISSUE TITLE
Cask `latexdraw` needs `xattr` in recipe

### ISSUE THREAD

**Issue by jasonhemann** [Homebrew/homebrew-cask#167951]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

With the formula as written, MacOS at least Monterrey won't let you open the application. It needs ` xattr -c` on the application itself. This should be baked into the formula. 

### Command that failed

Nothing failed, per se

### Output of command with `--verbose --debug`

```shell
NA
```

### Output of `brew doctor` and `brew config`

```shell
NA
```

### Output of `brew tap`

```shell
NA
```

**Comment by bevanjkay** [comment]
Quarantine is a **security** feature that is built into MacOS that we go to great lengths to support.
We will never systematically remove a quarantine attribute from an application. The appropriate way forward is to ask upstream to codesign their software.
