### ISSUE TITLE
checksum for cask waterfox (G6.0.9) is wrong

### ISSUE THREAD

**Issue by kateyork** [Homebrew/homebrew-cask#168133]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

SHA256 checksum is wrong for waterfox.rb, so I get an error "SHA256 mismatch". The version 6.0.9 is the newest one in waterfox.rb, but it seems that the sha256 value in the waterfox.rb file is wrong.
```
Error: SHA256 mismatch
Expected: 3468876a2d0d6590279eb6ef854df3f64b2ff967c2d638bbf46e278cd4dcf6ad
  Actual: c0433a7e89546dee1df553165760ef050aa72baff46c3b0b215bc83c18e473b7
```
If I manually download and evaluate the checksum, I get the actual value:
c0433a7e89546dee1df553165760ef050aa72baff46c3b0b215bc83c18e473b7

So there must be a problem with the checksum stored in the waterfox.rb file.
https://github.com/Homebrew/homebrew-cask/blob/master/Casks/w/waterfox.rb

Thanks!

### Command that failed

brew install waterfox

### Output of command with `--verbose --debug`

```shell
I don't think that's necessary
```

### Output of `brew doctor` and `brew config`

```shell
no output
```

### Output of `brew tap`

```shell
homebrew/cask-fonts
homebrew/servicves
```

**Comment by bevanjkay** [comment]
Please try to open a PR to fix the issue. We do not keep checksum mismatch issues open unless an attempt has been made to rectify.

**Comment by kateyork** [comment]
alright thank you!
