### ISSUE TITLE
TeXstudio for Apple Silicon has been released.

### ISSUE THREAD

**Issue by KerasLyc** [Homebrew/homebrew-cask#168821]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

TeXstudio for Apple Silicon has been released. But now only the x86 version can be installed using the command "brew install texstudio".

### Command that failed

brew install texstudio

### Output of command with `--verbose --debug`

```shell
Not for the issue.
```

### Output of `brew doctor` and `brew config`

```shell
Not for the issue.
```

### Output of `brew tap`

```shell
Not for the issue.
```

**Comment by SMillerDev** [comment]
https://docs.brew.sh/Updating-Software-in-Homebrew
