### ISSUE TITLE
powershell caveats not reproducible

### ISSUE THREAD

**Issue by glensc** [Homebrew/homebrew-cask#170589]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

`brew install powershell` prints this caveat:

```
==> Caveats
To use Homebrew in PowerShell, set:
  Add-Content -Path $PROFILE.CurrentUserAllHosts -Value '$(/opt/homebrew/bin/brew shellenv) | Invoke-Expression'
```

this is not very self-explanatory, obviously, there's no `Add-Content` command in path, it should be fed to powershell somehow. after `brew ls powershell` (useless for pkg cask -- doesn't list files) and later `cat /Applications/PowerShell.app/Contents/MacOS/PowerShell.sh` figured I should feed it to `pwsh` program

```
$ pwsh
PowerShell 7.4.1
PS /Users/glen> Add-Content -Path $PROFILE.CurrentUserAllHosts -Value '$(/opt/homebrew/bin/brew shellenv) | Invoke-Expression'
Add-Content: Could not find a part of the path '/Users/glen/.config/powershell/profile.ps1'.
PS /Users/glen>
```

apparently, the caveat needs to include some `install -d ~/.config/powershell` first.

perhaps also use `pwsh -c` to the command so the command wouldn't need to be interactive?

note: I'm not powershell user, just installed it for the first time to run some script.

### Command that failed

pwsh

### Output of command with `--verbose --debug`

```shell
not relevant - feature request to documentation
```

### Output of `brew doctor` and `brew config`

```shell
not relevant - feature request to documentation
```

### Output of `brew tap`

```shell
not relevant - feature request to documentation
```

**Comment by razvanazamfirei** [comment]
I believe this should be in `homebrew/brew`.

**Comment by SMillerDev** [comment]
Why? The caveats come from the cask AFAIK
