### ISSUE TITLE
Cask for Evernote is not up to date

### ISSUE THREAD

**Issue by asmaier** [Homebrew/homebrew-cask#170676]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

The version available via brew is
```
$ brew info evernote
==> evernote: 10.65.2,20231027153932,c6b1b587de93d3065ffa3836221cd7723d2e4996 (auto_updates)
```
However this version is too old. When I start it it tells me "Client not supported. Please update". 

I believe this happens, because the latest version of Evernote is 10.83.4, see 

- https://evernote.com/release-notes

So I think the cask for Evernote should be updated to version 10.83.4 .

### Command that failed

brew upgrade evernote

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading evernote
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading evernote
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading evernote
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading evernote
Warning: Not upgrading evernote, the latest version is already installed
```

### Output of `brew doctor` and `brew config`

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  meld

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  python-platformdirs
  python-distlib
  python-filelock

HOMEBREW_VERSION: 4.2.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: bd1155be8f50998429a795c15a69c8fe75250510
Last commit: 3 days ago
Core tap JSON: 04 Apr 20:37 UTC
Core cask tap JSON: 04 Apr 20:37 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.43.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.3.1-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
homebrew/bundle
```

**Comment by krehel** [comment]
Thanks @asmaier - opened #170677 to address.

**Comment by amaier-ypog** [comment]
Thank you for the quick fix. The new version of evernote works fine now.

**Comment by asmaier** [comment]
Thank you for the quick fix. The new version of Evernote works fine now.
