### ISSUE TITLE
Alfred can't find any of the homebrew casks i installed, even with folder added

### ISSUE THREAD

**Issue by hrqmonteiro** [Homebrew/homebrew-cask#171393]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

Alfred don't find any of the brew casks installed

![Screenshot 2024-04-15 at 15 11 43](https://github.com/Homebrew/homebrew-cask/assets/17055027/5e6459eb-0b3a-484d-98be-44b31265c8f5)
![Screenshot 2024-04-15 at 15 11 49](https://github.com/Homebrew/homebrew-cask/assets/17055027/37c13f60-5f5f-4635-82f9-a01680966f6e)
![Screenshot 2024-04-15 at 15 11 56](https://github.com/Homebrew/homebrew-cask/assets/17055027/b0202fcc-19ea-4de8-ba1c-17b9d52036d6)
![Screenshot 2024-04-15 at 15 12 01](https://github.com/Homebrew/homebrew-cask/assets/17055027/b8c7de74-1f78-43f0-b9ba-358d38728296)
![Screenshot 2024-04-15 at 15 12 07](https://github.com/Homebrew/homebrew-cask/assets/17055027/8d267316-2a92-4b69-b8fb-c5132b2eb33d)

### Command that failed

none

### Output of command with `--verbose --debug`

```shell
none
```

### Output of `brew doctor` and `brew config`

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Settings.

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 15.1.


Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  handbrake
  emacs-plus@29
  dart-sdk
```

```
HOMEBREW_VERSION: 4.2.18
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9edabf02ce29e54d0b717baa757cff38ad0c0e25
Last commit: 22 hours ago
Core tap JSON: 15 Apr 18:08 UTC
Core cask tap JSON: 15 Apr 18:08 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 6
Homebrew Ruby: 3.1.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: hexa-core 64-bit kabylake
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 13.6.6-x86_64
CLT: 14.3.1.0.1.1683849156
Xcode: 15.2
```
```


### Output of `brew tap`

```shell
d12frosted/emacs-plus
homebrew/bundle
localsend/localsend
```
```

**Comment by vitorgalvao** [comment]
This is most likely an issue with the Spotlight database. See [Troubleshooting File Indexing Issues](https://www.alfredapp.com/help/troubleshooting/indexing/).

* Try typing `reload` in Alfred first (7. Reload the Applications cache).
* If that doesn’t work, reindex (5. Rebuild your Mac's metadata index).
* If that doesn’t work, start at the beginning (Built-in Troubleshooting) and move your way down.

**Comment by SMillerDev** [comment]
Either way it's not a brew issue
