### ISSUE TITLE
Missing steelseries-exactmouse-tool from Homebrew/homebrew-cask-drivers

### ISSUE THREAD

**Issue by LukasKnuth** [Homebrew/homebrew-cask#173168]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

The `steelseries-exactmouse-tool` used to be in https://github.com/Homebrew/homebrew-cask-drivers - I have it in my Brewfile.

On a freshly installed macOS with Brew installed, I can't install this cask anymore. The error I'm getting is:

```
Warning: Cask 'steelseries-exactmouse-tool' is unavailable: No Cask with this name exists.
===> Searching for similar named casks...
===> Casks
steelseries-engine

To install steelseries-engine, run:
  brew install --cask steelseries-engine
```

### Command that failed

brew install --cask steelseries-exactmouse-tool

### Output of command with `--verbose --debug`

```shell
N/A
```

### Output of `brew doctor` and `brew config`

```shell
testing@Testings-Virtual-Machine ~ % /opt/homebrew/bin/brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  openssl@1.1
  vault

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  numpy

Warning: /usr/bin occurs before /opt/homebrew/bin in your PATH.
This means that system-provided programs will be used instead of those
provided by Homebrew. Consider setting your PATH so that
/opt/homebrew/bin occurs before /usr/bin. Here is a one-liner:
  echo 'export PATH="/opt/homebrew/bin:$PATH"' >> ~/.zshrc

The following tools exist at both paths:
  bashbug
  corelist
  cpan
  enc2xs
  encguess
  ex
  git
  git-receive-pack
  git-shell
  git-upload-archive
  git-upload-pack
  h2ph
  h2xs
  instmodsh
  json_pp
  libnetcfg
  openssl
  perl
  perlbug
  perldoc
  perlivp
  perlthanks
  piconv
  pip3
  pl2pm
  pod2html
  pod2man
  pod2text
  pod2usage
  podchecker
  pp
  prove
  ptar
  ptardiff
  ptargrep
  python3
  rview
  rvim
  shasum
  splain
  streamzip
  tidy
  vi
  view
  vim
  vimdiff
  vimtutor
  xsubpp
  xxd
  zipdetails

Warning: Homebrew's "bin" was not found in your PATH.
Consider setting your PATH for example like so:
  echo 'export PATH="/opt/homebrew/bin:$PATH"' >> ~/.zshrc

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /opt/homebrew/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/opt/homebrew/sbin:$PATH"' >> ~/.zshrc
testing@Testings-Virtual-Machine ~ % /opt/homebrew/bin/brew config
HOMEBREW_VERSION: 4.2.21
ORIGIN: https://github.com/Homebrew/brew
HEAD: 82c2e743a5bcea725f9ca1429e3e21c3088ff904
Last commit: 2 days ago
Core tap JSON: 08 May 07:32 UTC
Core cask tap JSON: 08 May 07:32 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 2
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: dual-core 64-bit dunno
Clang: 15.0.0 build 1500
Git: 2.45.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
fluxcd/tap
hashicorp/tap
homebrew/bundle
homebrew/cask-fonts
homebrew/services
localsend/localsend
siderolabs/tap
```

**Comment by bevanjkay** [comment]
Casks that weren't considered popular were not migrated from `homebrew-cask-drivers` before it was archived.
Can you try to add the cask to the `hombrew-cask` repo? Here's the latest version of the caskfile for reference - https://github.com/reitermarkus/homebrew-cask-drivers/blob/10b3255948376b59cce603d0e738a1338a651c1c/Casks/steelseries-exactmouse-tool.rb

**Comment by bevanjkay** [comment]
Essentially yes, and then seeing if there are any subsequent CI failures. It would need to be put in the correct directory also, which is now `Casks/s/steelseries-exactmouse-tool.rb`
