### ISSUE TITLE
Incorporate `name` stanza into `brew cask search`

### ISSUE THREAD

**Issue by jawshooah** [Homebrew/homebrew-cask#17323]
I didn't realize we hadn't implemented this yet, since I could find no open issues documenting our intention to do so.

Note: this was previously brought up in #13952, and likely in earlier discussions as well.

**Comment by alexchandel** [comment]
Please yes. You would expect `brew cask search quicklook` to find everything that mentions QuickLook, and yet it misses `qlvideo` even though it has `name 'QuickLook Video'`.

**Comment by claui** [comment]
[I have implemented it](https://github.com/claui/homebrew-cask/commit/01824d0b1130ae72a8276ffedb2b96f100281b57) a while ago to get familiar with the core.

It just needs a rebase, a few tests, and a thorough review (in that order).

**Comment by gentlecat** [comment]
I've been looking into this today and got something basic working: https://github.com/Homebrew/brew/compare/master...gentlecat:name-search. Am I going in the right direction with this or should it be implemented differently? I'm very much new to the codebase (and the language), so I won't be surprised if something is completely wrong. :)

I'm also not quite sure what would be the best way to display results of the name search. I imagine it would be useful to show both *name* and *token* of a cask, and whether it's already installed. But I don't yet know how to modify `Formatter` cleanly to do this.

**Comment by claui** [comment]
@gentlecat I’m happy to see someone taking care of this task, and appreciate that a lot!

As I’ll be extra busy this week, I’d appreciate other maintainers to take a look at your work (and at your question). If no one does, I’ll get back to you by the end of the week, hopefully.

**Comment by commitay** [comment]
`brew cask search` has been replaced by `brew search`. Casks can be searched by name using `brew search --desc`.

```
$ brew search --desc jetbrains
==> Formulae

==> Casks
jetbrains-toolbox: JetBrains Toolbox
pycharm-edu: Jetbrains PyCharm Educational Edition, PyCharm Edu
phpstorm: JetBrains PhpStorm
rider: Jetbrains Rider
youtrack-workflow: JetBrains Youtrack Workflow Editor
mps: JetBrains MPS
pycharm-ce: Jetbrains PyCharm Community Edition, PyCharm CE
```
