### ISSUE TITLE
Make :signal available in Installer Stanza

### ISSUE THREAD

**Issue by winkelsdorf** [Homebrew/homebrew-cask#17399]
Hi,

follow up issue for the discussion from https://github.com/caskroom/homebrew-cask/issues/11366#issuecomment-173204691: 

I've implemented the Adobe Casks using preflight/postflight due to `Signal` and `staged_path` not being available in the Installer (and partly Uninstall) Stanza(s).

The latter, `staged_path` has already been implemented.

In order to ensure that Casks for products like Adobe work without difficulties, having `Signal` available in the Installer Stanza would be helpful. This reduces clutter in the Casks where Installer Stanza would have to be accompanied by `Preflight` for quitting known conflicting processes.

I would like to ask if it's possible to implement `:signal` to Installer:

``` console
Installer signal: [['KILL', 'SafariNotificationAgent']],
```

Cheers,
Frederik

**Comment by sirn** [comment]
I also want to add that `signal:` would also be helpful in case of upgrading application version for `version :latest` casks.

I recently found an app that simply crashed (that I have to manually `kill -9` it) if the app was upgraded without first shutting down everything including a background process it spawn (in my case was Arq, where it spawn Arq Agent.app in the background).

**Comment by vitorgalvao** [comment]
@sirn Not really relevant, because we don’t know yet how upgrading will be handled when it is implemented, but `signal:` will likely not be a part of it, it’ll be handled automatically.
