### ISSUE TITLE
Can't upgrade (or install) `twine`

### ISSUE THREAD

**Issue by zgracem** [Homebrew/homebrew-cask#176995]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

So I tried upgrading the [Twine](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/t/twine.rb) cask this morning and the operation stalled indefinitely: I had to `^C` it after 15 minutes. I tried uninstalling the cask, which seemed to work. But then I tried reinstalling it, which also resulted in Homebrew hanging until I hit `^C` about 10 minutes later. 

- `brew install --cask twine --force` didn't help.
- `brew update-reset && brew update` ran OK but didn't fix the problem.
- `brew install --cask twine --appdir=/Applications` (my default is `--appdir=~/Applications`) didn't help.
- `rm -rf /usr/local/Caskroom/twine` per [this comment](https://github.com/Homebrew/homebrew-cask/issues/164980#issuecomment-1902878575) didn't help.
- Deleting the downloaded disk image (`rm -f ~/Library/Caches/Homebrew/downloads/*--Twine-*.dmg`) didn't help.
- `ls -dl "$(brew --caskroom)"` reveals that I am the owner of the Caskroom directory.
- `brew install --cask twine --verbose --debug` (see below) seems to suggest a problem unmounting the installation disk image, but I don't know enough about macOS to troubleshoot any further.

Finally, for whatever it's worth, I had the same problem upgrading/reinstalling [Obsidian](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/o/obsidian.rb) last week, when I didn't have time to save the command output or open an issue. But that leads me to suspect this isn't a problem with Twine per se.

### Command that failed

brew upgrade --cask twine; brew install --cask twine

### Output of command with `--verbose --debug`

```shell
~ > brew install --cask twine --verbose --debug
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading twine
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.6\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://github.com/klembot/twinejs/releases/download/2.9.0/Twine-2.9.0-macos.dmg
==> Downloading https://github.com/klembot/twinejs/releases/download/2.9.0/Twine-2.9.0-macos.dmg
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/118545267/09e3b184-1e83-4987-93eb-d9f96b1f1b9b?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240617%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240617T153204Z&X-Amz-Expires=300&X-Amz-Signature=75b134c2e7e2a7c8fee30d494f615b470c1a49214116bb69ba123486d090f649&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=118545267&response-content-disposition=attachment%3B%20filename%3DTwine-2.9.0-macOS.dmg&response-content-type=application%2Foctet-stream
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.6\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --fail --retry 3 --remote-time --output /Users/zozo/Library/Caches/Homebrew/downloads/a89fa1765fbe9ff546233a0909531d049ea01ce4e34920bcce1895b26a5c9bb5--Twine-2.9.0-macOS.dmg.incomplete --location https://objects.githubusercontent.com/github-production-release-asset-2e65be/118545267/09e3b184-1e83-4987-93eb-d9f96b1f1b9b\?X-Amz-Algorithm=AWS4-HMAC-SHA256\&X-Amz-Credential=releaseassetproduction\%2F20240617\%2Fus-east-1\%2Fs3\%2Faws4_request\&X-Amz-Date=20240617T153204Z\&X-Amz-Expires=300\&X-Amz-Signature=75b134c2e7e2a7c8fee30d494f615b470c1a49214116bb69ba123486d090f649\&X-Amz-SignedHeaders=host\&actor_id=0\&key_id=0\&repo_id=118545267\&response-content-disposition=attachment\%3B\%20filename\%3DTwine-2.9.0-macOS.dmg\&response-content-type=application\%2Foctet-stream
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  183M  100  183M    0     0  43.1M      0  0:00:04  0:00:04 --:--:-- 43.1M
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /Library/Developer/CommandLineTools/usr/bin/swift -target x86_64-apple-macosx14 /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/zozo/Library/Caches/Homebrew/downloads/a89fa1765fbe9ff546233a0909531d049ea01ce4e34920bcce1895b26a5c9bb5--Twine-2.9.0-macOS.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/zozo/Library/Caches/Homebrew/downloads/a89fa1765fbe9ff546233a0909531d049ea01ce4e34920bcce1895b26a5c9bb5--Twine-2.9.0-macOS.dmg
==> /Users/zozo/Library/Caches/Homebrew/downloads/a89fa1765fbe9ff546233a0909531d049ea01ce4e34920bcce1895b26a5c9bb5--Twine-2.9.0-macOS.dmg is not quarantined
==> Quarantining /Users/zozo/Library/Caches/Homebrew/downloads/a89fa1765fbe9ff546233a0909531d049ea01ce4e34920bcce1895b26a5c9bb5--Twine-2.9.0-macOS.dmg
/usr/bin/env /Library/Developer/CommandLineTools/usr/bin/swift -target x86_64-apple-macosx14 /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/zozo/Library/Caches/Homebrew/downloads/a89fa1765fbe9ff546233a0909531d049ea01ce4e34920bcce1895b26a5c9bb5--Twine-2.9.0-macOS.dmg https://github.com/klembot/twinejs/releases/download/2.9.0/Twine-2.9.0-macos.dmg https://twinery.org/
==> Verifying checksum for 'a89fa1765fbe9ff546233a0909531d049ea01ce4e34920bcce1895b26a5c9bb5--Twine-2.9.0-macOS.dmg'
/usr/bin/env hdiutil imageinfo -format /Users/zozo/Library/Caches/Homebrew/downloads/a89fa1765fbe9ff546233a0909531d049ea01ce4e34920bcce1895b26a5c9bb5--Twine-2.9.0-macOS.dmg
==> Installing Cask twine
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/zozo/Library/Caches/Homebrew/downloads/a89fa1765fbe9ff546233a0909531d049ea01ce4e34920bcce1895b26a5c9bb5--Twine-2.9.0-macOS.dmg
/usr/bin/env hdiutil attach -plist -nobrowse -readonly -mountrandom /private/tmp/homebrew-dmg20240617-12987-54uy6m /Users/zozo/Library/Caches/Homebrew/downloads/a89fa1765fbe9ff546233a0909531d049ea01ce4e34920bcce1895b26a5c9bb5--Twine-2.9.0-macOS.dmg
/usr/bin/env find . -print0
/usr/bin/env mkbom -s -i /private/tmp/20240617-12987-o29o9u.list -- /private/tmp/20240617-12987-9filjh.bom
/usr/bin/env ditto --bom /private/tmp/20240617-12987-9filjh.bom -- /private/tmp/homebrew-dmg20240617-12987-54uy6m/dmg.RIEv20 /private/tmp/homebrew-unpack20240617-12987-kvm5y1
/usr/bin/env diskutil info -plist /private/tmp/homebrew-dmg20240617-12987-54uy6m/dmg.RIEv20
/usr/bin/env diskutil eject disk11s1

[...and then it hanged here for about 10 minutes, until I did a ^C...]

^C==> Purging files for version 2.9.0 of Cask twine
Error: Read-only file system @ apply2files - /private/tmp/homebrew-dmg20240617-12987-54uy6m/dmg.RIEv20/.DS_Store
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/fileutils.rb:2330:in `unlink'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/fileutils.rb:2330:in `block in remove_file'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/fileutils.rb:2335:in `platform_support'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/fileutils.rb:2329:in `remove_file'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/fileutils.rb:2318:in `remove'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/fileutils.rb:1452:in `block in remove_entry'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/fileutils.rb:2377:in `block (2 levels) in postorder_traverse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/fileutils.rb:2377:in `block (2 levels) in postorder_traverse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/fileutils.rb:2381:in `postorder_traverse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/fileutils.rb:2376:in `block in postorder_traverse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/fileutils.rb:2375:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/fileutils.rb:2375:in `postorder_traverse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/fileutils.rb:2376:in `block in postorder_traverse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/fileutils.rb:2375:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/fileutils.rb:2375:in `postorder_traverse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/fileutils.rb:1450:in `remove_entry'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/tmpdir.rb:107:in `ensure in mktmpdir'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/tmpdir.rb:107:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:192:in `mount'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:182:in `extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11430/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11430/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11430/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:114:in `extract'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11430/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11430/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11430/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:129:in `block in extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/lib/ruby/3.3.0/tmpdir.rb:99:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:126:in `extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11430/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11430/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11430/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:225:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:82:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:109:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:246:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:235:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:235:in `run'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11430/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11430/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11430/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/usr/local/Homebrew/Library/Homebrew/brew.rb:92:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
~ > brew doctor
Your system is ready to brew.
~ > brew config
HOMEBREW_VERSION: 4.3.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: e8430b25a1d1321f32e5093d62b57b5cb7cfb3c3
Last commit: 24 hours ago
Core tap HEAD: f5dfd971dcd0351165c33fc6252a958f0269cb38
Core tap last commit: 2 hours ago
Core tap JSON: 17 Jun 15:22 UTC
Core cask tap HEAD: f9e01727b8eb8ba7e18a14fdecacfc5ccde80abb
Core cask tap last commit: 2 hours ago
Core cask tap JSON: 17 Jun 15:22 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_API_AUTO_UPDATE_SECS: 1800
HOMEBREW_BAT: set
HOMEBREW_BAT_CONFIG_PATH: /Users/zozo/.config/bat/config_homebrew
HOMEBREW_BROWSER: /usr/bin/open
HOMEBREW_BUNDLE_USER_CACHE: /Users/zozo/Library/Caches/bundler
HOMEBREW_CASK_OPTS: ["--appdir=~/Applications"]
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 7
HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: 7
HOMEBREW_DISPLAY_INSTALL_TIMES: set
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_NO_AUTOREMOVE: set
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_SORBET_RUNTIME: set
HOMEBREW_UPDATE_TO_TAG: set
Homebrew Ruby: 3.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/bin/ruby
CPU: 16-core 64-bit cometlake
Clang: 15.0.0 build 1500
Git: 2.45.2 => /usr/local/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-x86_64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
```

### Output of `brew tap`

```shell
~ > brew tap
1password/tap
alhadis/troff
bramstein/webfonttools
dart-lang/dart
homebrew-ffmpeg/ffmpeg
homebrew/bundle
homebrew/cask
homebrew/command-not-found
homebrew/core
homebrew/services
homebrew/test-bot
nrlquaker/createzap
potatolabs/git-redate
sass/sass
yt-dlp/taps
zgracem/caveats
zgracem/formulae
```

**Comment by razvanazamfirei** [comment]
What is the output of `sudo -l diskutil eject`? Are you able to manually mount and unmount disk images?

**Comment by zgracem** [comment]
```
~ > sudo -l diskutil eject
Password:
diskutil eject
```

And using the Finder to open .dmg files (and then eject them) works as expected.

**Comment by bevanjkay** [comment]
I wonder if it is getting stuck on the command after the eject command.
If so, it may have been fixed by https://github.com/Homebrew/brew/pull/17526

**Comment by zgracem** [comment]
I updated Homebrew:

```
~ > brew config
HOMEBREW_VERSION: 4.3.6-13-gaefd4db
ORIGIN: https://github.com/Homebrew/brew
HEAD: aefd4db7d4711df1d3d71a942d7e192a04908fd7
Last commit: 22 minutes ago
Core tap HEAD: 5914c264ab0bb91a495ae3e52e1b58397c68f806
Core tap last commit: 10 minutes ago
Core tap JSON: 18 Jun 13:18 UTC
Core cask tap HEAD: c72094b904311f732c8275804bbac56b4ab78501
Core cask tap last commit: 4 minutes ago
Core cask tap JSON: 18 Jun 13:18 UTC
[...]
```

Unfortunately, my problem persists. `brew install --cask twine --verbose --debug` provides essentially the same output and hangs indefinitely at the same point.

**Comment by krehel** [comment]
Unhelpful probably, but couldn't replicate in a clean VM environment using either v4.3.3 or v4.3.6 of Homebrew.

Almost sounds like a resource being held open preventing eject, but can't think what it would be. Agree that it's probably not a `twine` issue as mentioned it occurred to another Cask.

Immediately stupid question - have you tried rebooting?
Have you tried another cask besides `twine` since it failed?

Wondering if somehow you are out of space in `/private/tmp`, as I had that happen to me on my Intel mini with 128gb storage and obviously caused all kinds of strange behavior.

**Comment by zgracem** [comment]
I've rebooted several times in the last 24 hours. I'm afraid it hasn't seemed to make a difference.

I don't know how to check the specific capacity of `/private/tmp`, but fwiw, my primary `Macintosh HD` volume has about 150 GB free.

Just now I tried (re)installing three casks: [`jordanbaird-ice`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/j/jordanbaird-ice.rb), [`streamlink-twitch-gui`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/s/streamlink-twitch-gui.rb), and [`chatterino`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/c/chatterino.rb). Ice and Streamlink installed without issue, but Chatterino failed in the same way as Twine and Obsidian did (hanging forever while `diskutil` is the active process).

Here's an ominous twist: after the failed Chatterino installation, I tried to run `diskutil list`, and that _also_ stalled indefinitely. Opening the Disk Utility GUI gets me this, also indefinitely:

<img width="916" alt="image" src="https://github.com/Homebrew/homebrew-cask/assets/1896569/4044183d-bc4f-4b79-a818-65674e7fff03">

Rebooting did not make either `diskutil` or Disk Utility.app work correctly. (Neither did unmounting all of my external drives, if that's useful info.) So now I'm concerned that I somehow damaged my system when I `^C`'d out of a previous disk operation...

**Comment by krehel** [comment]
BLUF: At this stage with the new information, I don't think this is specifically a Homebrew issue, but do think you should be wary of your disk.

More -

I wouldn't _think_ `^C` would damage anything, as you effectively either cancelled a disk eject of a read only filesystem (the dmg) or halted a file copy process - but neither of which would take the time duration you mentioned.  But, I have personally destroyed a target disk before in a much more severe fashion when working with a failing disk (story at bottom), but ⬇️ 

It's possible you have bad sectors on your disk, and you've hit a point where installing or mounting something is trying to use that disk portion in I/O ops, either read or write.  Having issues enumerating volumes could point to a broader issue, but that's not exactly a definitive diagnosis, but I'd at least say disk issues can't be ruled out.

Are you having any other issues outside of Homebrew with reading or writing data, running programs, etc?  

I am not trying to strike fear here, but (as I am 100% sure you know) you should have backups and be aware that if your disk is actually failing it can cause very wonky behavior.

Personal story: I was trying to file copy a 2013 MBP spinning HDD that was ticking and starting failure in target disk mode to a external disk attached to another MBP.  File copy hung partway through and froze, and corrupted the APFS volume when I `^C`'d it.  Disk Utility would hang and view the drive was ruined.  Only thing I could do was hook the drive up to my Linux machine with `apfs` tools on it and recover what files I could.

**Comment by zgracem** [comment]
> Are you having any other issues outside of Homebrew with reading or writing data, running programs, etc?

None that I've noticed. And about 11 years ago I had HDD issues that slowly progressed to catastrophic failure (which corrupted my backups too, ugh) so I'm familiar with at least some of the symptoms. And so far the only problems I'm seeing are these, and w/r/t Homebrew _Cask_ specifically; formula-based `brew` operations formulae all seem to work fine, as does everything else on my machine.

> I am not trying to strike fear here, but (as I am 100% sure you know) you should have backups and be aware that if your disk is actually failing it can cause very wonky behavior.

I appreciate the warning, and fortunately I have multiple verified backups of my data, if it comes to that.

**Comment by krehel** [comment]
Yeah, and I'm being transparent - I could be completely wrong and it is a Homebrew Cask issue, but I don't know what it would immediately be.  One of the other maintainers may have a better idea, and I'll continue to give it some thought.  

The fact it persists after reboots is the concerning part, since if you had situations with locked or open resources those would be cleared on restart.  The worst problems are "sometime" problems.

Have you gotten any of `twine`, `obsidian`, or `chatterino` installed via Homebrew?

**Comment by krehel** [comment]
Happy to help @zgracem - unfortunate circumstance but glad we got it potentially identified.  What you mentioned makes sense - and `diskutil` for all of its shortcomings does tell you _something_ is wrong - by not working. 🤷‍♂️ 

Best of luck in resolution of your issue.
