### ISSUE TITLE
Getting "Error: Unexpected method 'appcast' called on Cask adoptopenjdk11."

### ISSUE THREAD

**Issue by mpkeefe** [Homebrew/homebrew-cask#177124]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

I first noticed this error when running 
  brew install gh
but I'm also getting it when I run
  brew doctor

### Command that failed

brew install gh. Actually the command succeeds installing gh. But I get the error message

### Output of command with `--verbose --debug`

```shell
$ brew install gh --verbose --debug
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading gh
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading gh
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::NullLoader): loading gh
Warning: gh 2.51.0 is already installed and up-to-date.
To reinstall 2.51.0, run:
  brew reinstall gh
```

### Output of `brew doctor` and `brew config`

```shell
$ brew doctor
Error: Unexpected method 'appcast' called on Cask adoptopenjdk11.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Error: Unexpected method 'appcast' called on Cask adoptopenjdk11.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  openssl@1.1


 $ brew config
HOMEBREW_VERSION: 4.3.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: e8430b25a1d1321f32e5093d62b57b5cb7cfb3c3
Last commit: 2 days ago
Core tap JSON: 18 Jun 14:41 UTC
Core cask tap JSON: 18 Jun 14:41 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.3.3 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false
```

### Output of `brew tap`

```shell
$ brew tap
adoptopenjdk/openjdk
hashicorp/tap
homebrew/services
```

**Comment by krehel** [comment]
Reported many times.  Please see https://github.com/Homebrew/homebrew-cask/issues/173201
