### ISSUE TITLE
BetterAndBetter url changed

### ISSUE THREAD

**Issue by elliotl1l** [Homebrew/homebrew-cask#177208]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

I updated BetterAndBetter and failed, it shows `Error: betterandbetter: Download failed on Cask 'betterandbetter' with message: Download failed: https://cdn.better365.cn/BetterAndBetter/BetterAndBetter2.6.1Beta.dmg`.
I checked the website and noticed that the url has already changed to https://cdn.better365.cn/BetterAndBetter2.6.1_1Beta.dmg, I hope you can replace the url and fix this problem, thank you!

### Command that failed

brew upgrade betterandbetter

### Output of command with `--verbose --debug`

```shell
Error: betterandbetter: Download failed on Cask 'betterandbetter' with message: Download failed: https://cdn.better365.cn/BetterAndBetter/BetterAndBetter2.6.1Beta.dmg
/opt/homebrew/Library/Homebrew/download_strategy.rb:434:in `rescue in fetch'
/opt/homebrew/Library/Homebrew/download_strategy.rb:431:in `fetch'
/opt/homebrew/Library/Homebrew/downloadable.rb:86:in `fetch'
/opt/homebrew/Library/Homebrew/cask/download.rb:53:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:186:in `download'
/opt/homebrew/Library/Homebrew/cask/installer.rb:69:in `fetch'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:192:in `upgrade_cask'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:113:in `block in upgrade_casks'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:112:in `each'
/opt/homebrew/Library/Homebrew/cask/upgrade.rb:112:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:260:in `upgrade_outdated_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:138:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:92:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
Your system is ready to brew.

HOMEBREW_VERSION: 4.3.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: e8430b25a1d1321f32e5093d62b57b5cb7cfb3c3
Last commit: 3 days ago
Core tap JSON: 19 Jun 09:45 UTC
Core cask tap JSON: 19 Jun 09:45 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.3.3 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.45.2 => /opt/homebrew/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
bigwig-club/brew
khanhas/tap
lihaoyun6/tap
spicetify/tap
```

**Comment by SMillerDev** [comment]
https://docs.brew.sh/Updating-Software-in-Homebrew should help you with that, which is the quickest way to get this resolved.
