### ISSUE TITLE
darktable needs minimum macos 3.5, app fail on 12.7.5, pls add a depend_on...

### ISSUE THREAD

**Issue by wgoetz** [Homebrew/homebrew-cask#177676]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

darktable 4.8.0 forces minimum macos 13.5 as described here: 
https://github.com/darktable-org/darktable?tab=readme-ov-file#supported-platforms

On 12.7.5 the brew install darktable is ok due to not checking old macos version.
darktable appllication itself states incompatibility.

### Command that failed

the darktable app on 12.7.5 nok

### Output of command with `--verbose --debug`

```shell
n.a.
```

### Output of `brew doctor` and `brew config`

```shell
n.a.
```

### Output of `brew tap`

```shell
n.a.
```

**Comment by Rylan12** [comment]
Please feel free to open a Pull Request to make this change! You can find help on our docs page at https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request or https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md
