### ISSUE TITLE
Link for metashapepro is wrong

### ISSUE THREAD

**Issue by 0n3-70uch** [Homebrew/homebrew-cask#178158]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

Hello, the link to Agisoft Metashape Pro is outdated. Used link in `metashapepro.rb` (line 5):
`  url "http://download.agisoft.com/metashape-pro_#{version.dots_to_underscores}.dmg"`

Correct link:
https://s3-eu-west-1.amazonaws.com/download.agisoft.com/metashape-pro_2_1_2.dmg

And correct `metashapepro.rb` (line 5):
`  url "https://s3-eu-west-1.amazonaws.com/download.agisoft.com/metashape-pro_#{version.dots_to_underscores}.dmg"`

Have a nice day

### Command that failed

brew upgrade --cask --greedy --force metashapepro

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading metashapepro
==> Upgrading 1 outdated package:
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromPathLoader): loading /opt/homebrew/Caskroom/metashapepro/.metadata/2.1.1/20240323090302.977/Casks/metashapepro.json
metashapepro 2.1.1 -> 2.1.2
==> Started upgrade process for Cask metashapepro
==> Upgrading metashapepro
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.7-47-g09223c7\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head http://download.agisoft.com/metashape-pro_2_1_2.dmg
```

### Output of `brew doctor` and `brew config`

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  meld

Warning: You have the following deprecated, official taps tapped:
  Homebrew/homebrew-cask-versions
Untap them with `brew untap`.
```

### Output of `brew tap`

```shell
homebrew/cask-versions
```

**Comment by SMillerDev** [comment]
Where can we find that new link upstream?

**Comment by 0n3-70uch** [comment]
Hi you can fine it here: https://www.agisoft.com/downloads/installer/

**Comment by 0n3-70uch** [comment]
Thank you.
