### ISSUE TITLE
Wrong package downloaded for appcleaner : brew install --cask appcleaner

### ISSUE THREAD

**Issue by alexistrn** [Homebrew/homebrew-cask#178404]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

When we want to install appcleaner (cask : https://formulae.brew.sh/cask/appcleaner#default), **the app downloaded and installed is not the expected application**. It should be this one from FreeMacSoft, which is totally free : https://freemacsoft.net/appcleaner/ 
But we get another one from Nektony, which is not free and from an obscur developper : https://nektony.com/fr/mac-app-cleaner

The link to the website (not the package downloaded) of appcleaner on the homebrew page is good anyway : https://freemacsoft.net/appcleaner/

### Command that failed

brew install --cask appcleaner

### Output of command with `--verbose --debug`

```shell
Not applicable
```

### Output of `brew doctor` and `brew config`

```shell
Not applicable
```

### Output of `brew tap`

```shell
Not applicable
```

**Comment by bevanjkay** [comment]
It looks like you have mistyped when you ran `brew install --cask` and passed in the token `app-cleaner` instead of `appcleaner`.
