### ISSUE TITLE
imhex 1.35.4 macOS x86_64 can't be opened

### ISSUE THREAD

**Issue by rinkjames** [Homebrew/homebrew-cask#179158]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

Upon successful installation of imhex using `brew install imhex`, attempting to launch the app returns a message saying,

> "ImHex.app" can't be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information. Homebrew Cask downloaded this file today at 09:36.

I've ascertained that the `md5` hash of the file `imhex-1.35.4-macOS-x86_64.dmg` downloaded manually from [here](https://github.com/WerWolv/ImHex/releases) matches that of the similarly named file homebrew downloaded into `~/Library/Caches/Homebrew/downloads/`. The `md5` hash was `d01508fc749d87e9db5ca60abad6855b`. Despite identical hashes, launching the app installed using the former dmg appears to work without issue, but launching that installed using the latter file results in the above warning message. I don't know what's going on.

<img width="372" alt="Screenshot 2024-07-10 at 14 19 04" src="https://github.com/Homebrew/homebrew-cask/assets/13288151/d09c9ff0-1bd8-409d-94c7-e9b424666213">

### Command that failed

n/a: there was no command that failed

### Output of command with `--verbose --debug`

```shell
n/a: there was no command that failed
```

### Output of `brew doctor` and `brew config`

```shell
~
❯ brew doctor                                                                       14:53:47
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  python-packaging
~
❯ brew config                                                                       14:53:55
HOMEBREW_VERSION: 4.3.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1c98a33a376e5b35ebc801d0f7d6ba7b9eb118ac
Last commit: 3 days ago
Core tap JSON: 10 Jul 12:30 UTC
Core cask tap JSON: 10 Jul 12:30 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BAT_THEME: OneHalfDark
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.VC4q5G5ukJ/org.xquartz:0
HOMEBREW_EDITOR: code
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 15.0.0 build 1500
Git: 2.45.2 => /usr/local/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-x86_64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
~
❯                                                                                   14:53:59
```

### Output of `brew tap`

```shell
~
❯ brew tap                                                                          14:53:08
borgbackup/tap
homebrew/bundle
homebrew/services
~
❯                                                                                   14:53:12
```

**Comment by khipp** [comment]
When running the app for the first time, you can either go to `System Settings` > `Privacy & Security` and click `Open Anyway` or open the application through the right-click menu and confirm the dialog:
<img width="372" alt="image" src="https://github.com/Homebrew/homebrew-cask/assets/9824526/9f85daa7-f4b7-489a-9223-56236b0f69ba">

**Comment by rinkjames** [comment]
Ah, apologies that this was so straightforward. I’m not used to getting this message. I’ve seen the ‘unidentified developer’ message before. Wasn’t aware the solution to both is the same. Many thanks.
