### ISSUE TITLE
Error: Unexpected method 'appcast' called on Cask adoptopenjdk8.

### ISSUE THREAD

**Issue by GDGlab** [Homebrew/homebrew-cask#179283]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

as i entered command brew uninstall cocoapods, there is an error

### Command that failed

brew uninstall cocoapods

### Output of command with `--verbose --debug`

```shell
zsh: command not found: --verbose
```

### Output of `brew doctor` and `brew config`

```shell
brew doctor
Error: Unexpected method 'appcast' called on Cask adoptopenjdk8.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Error: Unexpected method 'appcast' called on Cask adoptopenjdk8.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
brew config
HOMEBREW_VERSION: 4.3.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1c98a33a376e5b35ebc801d0f7d6ba7b9eb118ac
Last commit: 3 days ago
Core tap JSON: 11 Jul 08:20 UTC
Core cask tap JSON: 11 Jul 08:27 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.3.3 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: N/A
Xcode: 15.4
Rosetta 2: false
dmitriy@MacBook-Air-Dmitriy ~ %
```

### Output of `brew tap`

```shell
adoptopenjdk/openjdk
```

**Comment by khipp** [comment]
Take a look at our pinned issue: https://github.com/Homebrew/homebrew-cask/issues/173201#issuecomment-2101662209.

**Comment by GDGlab** [comment]
> Take a look at our pinned issue: [#173201 (comment)](https://github.com/Homebrew/homebrew-cask/issues/173201#issuecomment-2101662209).

thx
