### ISSUE TITLE
gns3 sha256 is wrong - cannot update to 2.2.48

### ISSUE THREAD

**Issue by daftu** [Homebrew/homebrew-cask#179272]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

File Casks/g/gns3.rb contains bad sha256 signature which results in problems with updating/installing:
```
Error: gns3: SHA256 mismatch
Expected: 8b08977690ea9627f9b9a21102e0475cf9a8b5fcc419e7fe77caeb94f0e1a786
Actual: da20da1b9675950995cae776284a69e9b8a492837420306c2651ac3342e4bd57
```
As I've checked gns3 repository, "da20da1b9675950995cae776284a69e9b8a492837420306c2651ac3342e4bd57" is correct sha256 and should be changed in gns3.rb

### Command that failed

brew upgrade

### Output of command with `--verbose --debug`

```shell
==> Casks with 'auto_updates true' or 'version :latest' will not be upgraded; pass `--greedy` to upgrade them.
==> Upgrading 1 outdated package:
gns3 2.2.47 -> 2.2.48
==> Upgrading gns3
==> Downloading https://github.com/GNS3/gns3-gui/releases/download/v2.2.48/GNS3-2.2.48.dmg
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/13111393/8ed12a28-3d64-43
#################################################################################################################### 100.0%
==> Purging files for version 2.2.48 of Cask gns3
Error: gns3: SHA256 mismatch
Expected: 8b08977690ea9627f9b9a21102e0475cf9a8b5fcc419e7fe77caeb94f0e1a786
  Actual: da20da1b9675950995cae776284a69e9b8a492837420306c2651ac3342e4bd57
    File: /Users/username/Library/Caches/Homebrew/downloads/35f76db99c47fa3049e61153037c295ebdd32cfa6b47cf2e7d84f95ed8189a96--GNS3-2.2.48.dmg
To retry an incomplete download, remove the file above.
```

### Output of `brew doctor` and `brew config`

```shell
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  adoptopenjdk
  fing-cli
  openconnect-gui
  phantomjs
  robo-3t

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  stormssh
  maven@3.3

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  cowsay
  ecm
  maven@3.3
  openssl@1.1
  packer
  python@3.8

Warning: You have the following deprecated, official taps tapped:
  Homebrew/homebrew-cask-versions
  Homebrew/homebrew-cask-drivers
Untap them with `brew untap`.

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  md5sha1sum
```

### Output of `brew tap`

```shell
brew tap
hashicorp/tap
homebrew/bundle
homebrew/cask-drivers
homebrew/cask-versions
homebrew/services
isen-ng/dotnet-sdk-versions
platformsh/tap
spl/pdftk
yt-dlp/taps
```

**Comment by daftu** [comment]
Package maintainer provides sha256 on his github , and it is valid:
https://github.com/GNS3/gns3-gui/releases/download/v2.2.48/GNS3-2.2.48.dmg.sha256

**Comment by SMillerDev** [comment]
>  I made doubly sure this is not a checksum does not match / SHA256 mismatch error (do not open an issue before trying to open a PR to fix first).

So it's this one from the checklist?

**Comment by daftu** [comment]
> > I made doubly sure this is not a checksum does not match / SHA256 mismatch error (do not open an issue before trying to open a PR to fix first).
> 
> So it's this one from the checklist?

Sorry, it was.
