### ISSUE TITLE
`font-cantarell` uses old version of font that breaks in some use cases

### ISSUE THREAD

**Issue by qwertychouskie** [Homebrew/homebrew-cask#179369]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

The version of the Cantarell font installed by the `font-cantarell` cask is an old version that doesn't display right on some websites.  The latest version of the font can be found from https://cantarell.gnome.org/.

An excellent example of this breakage can be seen at https://extensions-next.gnome.org/

Bad version:
<img width="289" alt="image" src="https://github.com/user-attachments/assets/bbaf147a-a553-4ebd-a50e-fec18603758c">

Good version:
<img width="289" alt="image" src="https://github.com/user-attachments/assets/80cd865e-5bc6-4d88-80e4-8abfc4313945">

### Command that failed

brew install --cask font-cantarell

### Output of command with `--verbose --debug`

```shell
N/A
```

### Output of `brew doctor` and `brew config`

```shell
N/A
```

### Output of `brew tap`

```shell
N/A
```

**Comment by bevanjkay** [comment]
The version distributed here is what is made available through the Google Fonts distribution.
If this is outdated, then an issue should be filed in the upstream repository - https://github.com/google/fonts/

**Comment by qwertychouskie** [comment]
There's already an upstream issue open since 2015:

https://github.com/google/fonts/issues/112

Which due to Google Fonts' rules about updates not removing any styles, is blocked on this upstream issue to add italics:

https://gitlab.gnome.org/GNOME/cantarell-fonts/-/issues/44

I believe Homebrew should probably switch to the Gnome version of the font irrespective of Google Fonts' decision to wait on switching, since Gnome apps and websites are going to expect the Gnome-maintained version of Cantarell and the features it provides.

**Comment by bevanjkay** [comment]
Thanks for the explanation. Can you try to [open a PR](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#cask-related-pull-request) to complete the change?

**Comment by qwertychouskie** [comment]
> Thanks for the explanation. Can you try to [open a PR](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#cask-related-pull-request) to complete the change?

Done: https://github.com/Homebrew/homebrew-cask/pull/179384
