### ISSUE TITLE
Thunderbird change versioning to include "esr" string

### ISSUE THREAD

**Issue by schwedenmut** [Homebrew/homebrew-cask#179792]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

Ss stated in https://support.mozilla.org/de/kb/thunderbird-128-nebula-faq#w_why-is-thunderbird-128-labeled-as-128-0esr-when-previous-versions-were-not-called-esr the new versioning format will have an esr appended to it.

So to overcome this change and to be able to download the current official thunderbird version, I went ahead and slightly changed the livecheck regex from `/href=.*?thunderbird[._-]v?(\d+(?:\.\d+)+)[._-]SSL/i` to `/href=.*?thunderbird[._-]v?(\d+(?:\.\d+)+esr)[._-]SSL/i`. Also the version now needs to either include the esr with this regex.
Alternatively we could leave the esr outside the capturing group and programatically include it to the download URIs.

What do y'all think?
Kind regards

### Command that failed

brew livecheck thunderbird

### Output of command with `--verbose --debug`

```shell
➜  t git:(master) brew livecheck thunderbird --verbose --debug 
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4/bin/bundle clean
#<Homebrew::DevCmd::LivecheckCmd::Args named=["thunderbird"], remaining=["thunderbird"], d?=true, debug?=true, q?=false, quiet?=false, v?=true, verbose?=true, h?=false, help?=false, full_name?=false, tap=nil, eval_all?=false, installed?=false, newer_only?=false, json?=false, r?=false, resources?=false, formula?=false, formulae?=false, cask?=false, casks?=false, extract_plist?=false>
/Users/mschwede/.homebrew/livecheck_watchlist.txt
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading thunderbird
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromNameLoader): loading thunderbird

Cask:             thunderbird
Livecheckable?:   Yes

URL (homepage):   https://www.thunderbird.net/
Strategies:       PageMatch
Strategy:         PageMatch
Regex:            /href=.*?thunderbird[._-]v?(\d+(?:\.\d+)+)[._-]SSL/i
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.9-281-g9538f42\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.6.7\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 -V
URL (final):      https://www.thunderbird.net/en-US/

Matched Versions:
115.12.2 => #<Version:0x000000012b7bf788 @version="115.12.2", @detected_from_url=false>

thunderbird: 115.12.2 ==> 115.12.2
```

### Output of `brew doctor` and `brew config`

```shell
➜  t git:(master) brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  mitmproxy

Warning: You have the following deprecated, official taps tapped:
  Homebrew/homebrew-cask-versions
  Homebrew/homebrew-cask-fonts
  Homebrew/homebrew-cask-drivers
Untap them with `brew untap`.

➜  t git:(master) brew config
HOMEBREW_VERSION: 4.3.9-281-g9538f42
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9538f424b5e8c0c02d94426f71cbfb08a5f53314
Last commit: 2 hours ago
Core tap HEAD: 5d26950f060ecc6aaab71d88109646d0f59bac0b
Core tap last commit: 7 months ago
Core tap JSON: 16 Jul 17:07 UTC
Core cask tap HEAD: 8efab4086a82989d7eb82744a1a3e4a80e173f3f
Core cask tap last commit: 2 hours ago
Core cask tap JSON: 16 Jul 17:07 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 15.0.0 build 1500
Git: 2.45.2 => /usr/local/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 13.6.7-x86_64
CLT: 15.1.0.0.1.1700200546
Xcode: N/A
```

### Output of `brew tap`

```shell
➜  t git:(master) brew tap
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/services
minio/stable
vitorgalvao/tiny-scripts
```

**Comment by schwedenmut** [comment]
by the way, the "new" update channels are esr, release, beta and daily - possibly the time to do it like the firefox cask to split into thunderbird@esr, thunderbird@beta, thunderbird@nightly and thunderbird.

**Comment by samford** [comment]
> Yes, the main Thunderbird cask should follow the release channel. > The livecheck should check for `LATEST_THUNDERBIRD_VERSION` in https://product-details.mozilla.org/1.0/thunderbird_versions.json

Makes sense to me. I'll create a PR to implement your `livecheck` block suggestion.
