### ISSUE TITLE
if I don't keep shell open it is removed

### ISSUE THREAD

**Issue by silvrwolfboy** [Homebrew/homebrew-cask#181402]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

on Mac OS 15 Homebrew won't stay installed

### Command that failed

brew

### Output of command with `--verbose --debug`

```shell
not installed
```

### Output of `brew doctor` and `brew config`

```shell
it brewed till I closed the shell then poof
```

### Output of `brew tap`

```shell
same
```

**Comment by SMillerDev** [comment]
This has nothing to do with casks. Please create a discussion and ensure you followed all the instructions at the end of the install.
