### ISSUE TITLE
Github Desktop - update URL returning 404

### ISSUE THREAD

**Issue by FIying-Scotsman** [Homebrew/homebrew-cask#181406]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

The Github Desktop update URL has started returning a 404, preventing the cask from being updated. Confirmed in a browser.

> **The requested content does not exist.**
> HttpStatusCode: 404
> ErrorCode: WebContentNotFound
> RequestId : 47f1aea4-a01e-005e-6bd4-e45927000000
> TimeStamp : 2024-08-02T12:07:52.1496366Z

### Command that failed

brew upgrade $(brew outdated --cask --greedy --quiet)

### Output of command with `--verbose --debug`

```shell
==> Updating Homebrew...
Already up-to-date.
==> Upgrading 1 outdated package:
github 3.4.2-27793d93 -> 3.4.3-2170ce9b
==> Upgrading github
==> Downloading https://desktop.githubusercontent.com/github-desktop/releases/3.4.3-2170ce9b/GitHubDesktop-arm64.zip
curl: (56) The requested URL returned error: 404

==> Purging files for version 3.4.3-2170ce9b of Cask github
Error: github: Download failed on Cask 'github' with message: Download failed: https://desktop.githubusercontent.com/github-desktop/releases/3.4.3-2170ce9b/GitHubDesktop-arm64.zip
```

### Output of `brew doctor` and `brew config`

```shell
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  authy
```

### Output of `brew tap`

```shell
brew tap
italomandara/cxpatcher
```

**Comment by FIying-Scotsman** [comment]
I understand this is an easy fix, but opened for awareness. The download on the site is different to the releases URL above (which is still live if you don't provide a specific release) while serving the same file so I'm not sure what's going on.

**Comment by khipp** [comment]
Thank you for the report, @FIying-Scotsman. We have an open [pull request](https://github.com/Homebrew/homebrew-cask/pull/181392), that will solve the issue.
