### ISSUE TITLE
`utmctl` broken when using `--appdir`

### ISSUE THREAD

**Issue by lishaduck** [Homebrew/homebrew-cask#182568]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

I don't have admin right, just brew rights. Thus, I use `--appdir` to move apps to `~/Applications`, which mostly works fine. However, `utmctl` doesn't respect it. Given [the docs](https://docs.brew.sh/Common-Issues#cask---permission-denied), I figured it was acceptable to at least note it was broken.
I should note that this has always been true (for at least a year), but it didn't bother me enough to care until now.

### Command that failed

`utmctl list`

### Output of command with `--verbose --debug`

Flags n/a, output:

```shell
2024-08-15 20:28:29.203 utmctl[28511:15501686] Can't find app with file path /Applications/UTM.app
Error: Application not found.
```

### Output of `brew doctor` and `brew config`

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Xcode (15.3) is outdated.
Please update to Xcode 15.4 (or delete it).
Xcode can be updated from the App Store.
```
```shell
HOMEBREW_VERSION: 4.3.15-119-g21e3055
ORIGIN: https://github.com/Homebrew/brew
HEAD: 21e3055eb5d278bb4f8747f6d4bc443f92c9a12f
Last commit: 57 minutes ago
Core tap HEAD: fd694e77b99dcbfeb315c76e992ed1b1adc45e63
Core tap last commit: 54 minutes ago
Core tap JSON: 16 Aug 01:06 UTC
Core cask tap JSON: 16 Aug 01:07 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BAT: set
HOMEBREW_BROWSER: chrome
HOMEBREW_CASK_OPTS: ["--appdir=~/Applications"]
HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: 1
HOMEBREW_EDITOR: code
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.46.0 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 14.6.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.3
Rosetta 2: false
```

### Output of `brew tap`

```shell
homebrew/core
homebrew/services
martido/graph
withgraphite/tap
```

**Comment by lishaduck** [comment]
Oh, didn't see #12858.
It works, just not the cli. Could be given a caveat, I suppose?
I assume a patch wouldn't be terrible, but you don't patch casks, do you?

**Comment by khipp** [comment]
@lishaduck Unfortunately, this issue is beyond our control. We simply set a symlink to the `utmctl` binary (`utmctl -> ~/Applications/UTM.app/Contents/MacOS/utmctl` in this case).

The problem appears to be related to how their [symlink resolution logic](https://github.com/utmapp/UTM/blob/1e0e6b20621e9cfb63b71fb983995bb59bf34ea1/utmctl/UTMCtl.swift#L100) works, causing it to fall back to the default path. This issue should be reported upstream.

Running `utmctl` from the app's actual directory works as expected:
```console
$ cd ~/Applications/UTM.app/Contents/MacOS && ./utmctl list                                                                                                                                             (torch)
UUID                                 Status   Name
```

**Comment by lishaduck** [comment]
Oh, meant to close this, sorry :)
