### ISSUE TITLE
multipass: sudp/password prompt before warning

### ISSUE THREAD

**Issue by dotysan** [Homebrew/homebrew-cask#183228]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

When upgrading, the `Password:` prompt appears before the warning prompt:
```
==> Upgrading multipass
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/8bac6e653c4a426f76f949b812e753eba0dc987d/Casks/m/multipass.rb
==> Downloading https://github.com/canonical/multipass/releases/download/v1.14.0/multipass-1.14.0+mac-Darwin.pkg
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/114128199/f64dcf1b-87bc-4cae-8952-969fa965c9f2?X-Amz-Algorithm=AWS4-H
==> Removing launchctl service com.canonical.multipassd
Password:
==> Uninstalling packages with sudo; the password may be necessary:
com.canonical.multipass.multipassd
com.canonical.multipass.multipass
com.canonical.multipass.multipass_gui
==> Removing files:
/opt/homebrew/etc/bash_completion.d/multipass
/Applications/Multipass.app
/Library/Application Support/com.canonical.multipass
/Library/Logs/Multipass
/usr/local/bin/multipass
/usr/local/etc/bash_completion.d/multipass
==> Running installer for multipass with sudo; the password may be necessary.
installer: Package name is multipass
installer: Installing at base path /
installer: The install was successful.
==> Purging files for version 1.13.1 of Cask multipass
🍺  multipass was successfully upgraded!
```

### Command that failed

brew upgrade

### Output of command with `--verbose --debug`

```shell
The usual stuff. This was a one-shot error, as the upgrade succeeded.
```

### Output of `brew doctor` and `brew config`

```shell
The usual stuff. This was a one-shot error, as the upgrade succeeded.
```

### Output of `brew tap`

```shell
The usual stuff. This was a one-shot error, as the upgrade succeeded.
```

**Comment by khipp** [comment]
@dotysan, can you provide more information on the warning you are seeing?

Based on the provided log, the upgrade ran without issues. You are prompted for a password to remove services and files requiring elevated permissions while uninstalling the previous version of the cask.

**Comment by dotysan** [comment]
Sorry for not being clearer. The prompt "Running installer for multipass with sudo; the password may be necessary." didn't appear before the "Password:" prompt. But instead it came after, which is too late.

Maybe a minor nit.

**Comment by khipp** [comment]
Thank you for the explanation. This issue should then be raised in the main repository: https://github.com/Homebrew/brew.
