### ISSUE TITLE
`/opt/homebrew/bin/cursor: line 62: /Applications/Cursor.app/Contents/Resources/app/bin/../cursor: No such file or directory`

### ISSUE THREAD

**Issue by singularitti** [Homebrew/homebrew-cask#183427]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

When I tried to run `cursor .` in a working directory, I met the following error:

```
grep: /proc/version: No such file or directory
/opt/homebrew/bin/cursor: line 62: /Applications/Cursor.app/Contents/Resources/app/bin/../cursor: No such file or directory
```

This starts from [a recent PR](https://github.com/singularitti/homebrew-cask/blob/25e01e16144d88561a0ee73a6f8bd4c94a432783/Casks/c/cursor.rb#L29). However, this seems to be similar to the VSCode one. So I don't know why it is not working like `code`.

I have tried uninstalling and reinstalling `cursor` on different macOS systems, the same issue persists.

### Command that failed

cursor .

### Output of command with `--verbose --debug`

```shell
N/A
```

### Output of `brew doctor` and `brew config`

```shell
Your system is ready to brew.

HOMEBREW_VERSION: 4.3.17-149-g17e3bee
ORIGIN: https://github.com/Homebrew/brew
HEAD: 17e3bee3dadd9290270248e21f194e4a7000a0b7
Last commit: 6 hours ago
Core tap JSON: 25 Aug 23:11 UTC
Core cask tap HEAD: 7054d47f77b8c00e2d890389f0b48313b6765467
Core cask tap last commit: 44 minutes ago
Core cask tap JSON: 25 Aug 23:11 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: code
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby
CPU: 16-core 64-bit arm_palma
Clang: 15.0.0 build 1500
Git: 2.46.0 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 14.6.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
homebrew/cask
```

**Comment by daeho-ro** [comment]
It seems that the `cursor` binary` is somehow wrong.

```
if [ ! -L "$0" ]; then
	# if path is not a symlink, find relatively
	VSCODE_PATH="$(dirname "$0")/.."
else
	...
fi

ELECTRON="$VSCODE_PATH/cursor"
CLI="$VSCODE_PATH/resources/app/out/cli.js"
ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"
```

$(dirname "$0")/../cursor gives the wrong path and the command is not working. I think it is better to contact the upstream, not homebrew.

**Comment by singularitti** [comment]
Cool, thank you @daeho-ro!
