### ISSUE TITLE
vmware-fusion 13.6 install requirement is wrong!!!

### ISSUE THREAD

**Issue by logopk** [Homebrew/homebrew-cask#184472]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

Cask for vmware-fusion 13.6 installs on Big Sur and has a requirement macOS >=12. (Commit 836ad93)

However Fusion 13.6 requires Ventura macos >= 13

If you install this cask VMWare Fusion fails to start!

### Command that failed

brew upgrade vmware-fusion

### Output of command with `--verbose --debug`

```shell
n/a
```

### Output of `brew doctor` and `brew config`

```shell
n/a
```

### Output of `brew tap`

```shell
n/a
```

**Comment by khipp** [comment]
This has been addressed in #184467.
