### ISSUE TITLE
Unable to install from forked formula, configure failed to execute with no other error

### ISSUE THREAD

**Issue by voltagex** [Homebrew/homebrew-cask#184729]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

Please let me know if there's a better place to report this.

I am trying to install virt-viewer from https://github.com/voltagex-forks/homebrew-virt-manager which I forked from someone else.

I have updated the version and SHA256.

Other fields don't appear to allow file upload here and the output is 940k.

[virt-viewer-build.txt](https://github.com/user-attachments/files/16926092/virt-viewer-build.txt)

### Command that failed

./configure --disable-silent-rules --disable-update-mimedb --with-gtk-vnc --with-spice-gtk --prefix=/opt/homebrew/Cellar/virt-viewer/11.0

### Output of command with `--verbose --debug`

```shell
See attached file above
```

### Output of `brew doctor` and `brew config`

```shell
Your system is ready to brew.
HOMEBREW_VERSION: 4.3.19
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1f9bd2de89883ec9a59db3eab0f5475bce06d5bc
Last commit: 7 days ago
Core tap JSON: 09 Sep 05:53 UTC
Core cask tap JSON: 09 Sep 05:53 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.3.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby
CPU: octa-core 64-bit arm_ibiza
Clang: 15.0.0 build 1500
Git: 2.46.0 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 14.6.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false
```

### Output of `brew tap`

```shell
artginzburg/tap
homebrew/services
voltagex-forks/virt-manager
```

**Comment by daeho-ro** [comment]
Try https://github.com/jeffreywildman/homebrew-virt-manager.

**Comment by SMillerDev** [comment]
This is not about a cask or a homebrew formula so it should be reported to the tap owners
