### ISSUE TITLE
brew upgrade calibre hangs indefinitely

### ISSUE THREAD

**Issue by AleMaMi** [Homebrew/homebrew-cask#185761]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

When run `brew upgrade calibre`, it doesn't start downloading and hangs forever. If run with `--debug`, it is possible to see `curl` command at last line and no other activity.

If I try to directly download `calibre` package from URL, it is possible to download it without any issues.

### Command that failed

brew upgrade calibre

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading calibre
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading calibre
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading calibre
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading calibre
==> Upgrading 1 outdated package:
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromPathLoader): loading /opt/homebrew/Caskroom/calibre/.metadata/7.17.0/20240826052058.689/Casks/calibre.json
calibre 7.17.0 -> 7.18.0
==> Started upgrade process for Cask calibre
==> Upgrading calibre
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.23\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.0\)\ curl/8.7.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://download.calibre-ebook.com/7.18.0/calibre-7.18.0.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.3.23\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 15.0\)\ curl/8.7.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://download.calibre-ebook.com/7.18.0/calibre-7.18.0.dmg
```

### Output of `brew doctor` and `brew config`

```shell
Your system is ready to brew.

HOMEBREW_VERSION: 4.3.23
ORIGIN: https://github.com/Homebrew/brew
HEAD: 42c11a4dedf352229271593de831161071603c66
Last commit: 17 hours ago
Core tap JSON: 17 Sep 19:55 UTC
Core cask tap JSON: 17 Sep 19:55 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.3.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.0-arm64
CLT: 16.0.0.0.1.1724870825
Xcode: 16.0
Rosetta 2: false
```

### Output of `brew tap`

```shell
homebrew/bundle
railwaycat/emacsmacport
yonaskolb/xcodegen
```

**Comment by aphedges** [comment]
I was encountering this same problem, and it fortunately didn't hang forever. However, `brew upgrade --verbose --debug calibre` was stuck for ~15 minutes at the same `curl` command you reported. After the command finished, Calibre was downloaded and installed successfully.

I don't know what the solution is here. There might be something wrong with Calibre's distribution infrastructure that is causing the hang, or it might be a bug in Homebrew. At the very least, I feel that `brew` shouldn't hang for 15 minutes without any indication of work being done.

**Comment by bevanjkay** [comment]
This is an issue with Calibre's download servers, they can be patchy at times.
Downloading from the GitHub location is significantly faster. However, we can't use this for Homebrew, as old versions are removed when a new version becomes available.

See https://github.com/Homebrew/homebrew-cask/pull/183664 for information.
