### ISSUE TITLE
Thunderbird LATEST vs ESR

### ISSUE THREAD

**Issue by giacgbj** [Homebrew/homebrew-cask#187251]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

It seems that Thunderbird cask should follow ESR channel instead of LATEST or, at least, create different casks.
Launching the latest (131), Thunderbird shows the following warning:
<img width="874" alt="Screenshot 2024-10-02 at 14 29 23" src="https://github.com/user-attachments/assets/f238ba91-9cfe-4a80-85d0-190ebda1e137">

### Command that failed

-

### Output of command with `--verbose --debug`

```shell
-
```

### Output of `brew doctor` and `brew config`

```shell
-
```

### Output of `brew tap`

```shell
-
```

**Comment by Bo98** [comment]
Mozilla's communication on this has been very confusing. In the previous announcement they made it clear that monthly releases are not the same as betas: https://support.mozilla.org/en-US/kb/thunderbird-128-nebula-faq

We took data from https://product-details.mozilla.org/1.0/thunderbird_versions.json and `LATEST_THUNDERBIRD_VERSION` has historically _always_ been the latest stable version (https://web.archive.org/web/20240212012428/https://product-details.mozilla.org/1.0/thunderbird_versions.json). ESR is a very new entry.

Seems like they've suddenly changed the definition of what "latest" means to know mean a beta, breaking any scripts that use that API in the process.

Based on https://thunderbird.topicbox.com/groups/planning/T10766b2d0c60c029/product-details-update-for-monthly-releases, it seems like "latest" will be the correct thing to use soon, but not for v131 so we need to temporarily move to ESR and then move back when ready.

**Comment by sdellenb** [comment]
Unfortunately, starting Thunderbird after the upgrade to 131.0 made my profile incompatible with 128.2.3esr.
There's no path back without setting everything up from scratch (or backup).

**Comment by NicoHaase** [comment]
I fully understand that this is neither the fault nor the responsibility of Homebrew's team, but do you recommend any action for endusers to handle this situation? Do we need to migrate to another cask? Or do you plan to migrate the "existing" Thunderbird cask to a different kind of release once that is ready?

**Comment by Bo98** [comment]
> do you recommend any action for endusers to handle this situation? Do we need to migrate to another cask? Or do you plan to migrate the "existing" Thunderbird cask to a different kind of release once that is ready?

The monthly release channel will eventually become stable so we'll keep everyone on that branch until it does.

There is an ESR cask available too now but this is only those who really don't want the warning and are okay with a new profile.
