### ISSUE TITLE
Github issue template should not ask for full `--verbose --debug` output as that is too long for Github limits, making issue submission fail

### ISSUE THREAD

**Issue by corneliusroemer** [Homebrew/homebrew-cask#187349]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

I tried to submit an issue following the reproducible bug report template.

When I submitted, I got an error message: `Comment is too long (maximum is 65536 characters)`

Even when I shortened the longest comment, I could no longer submit, because of presumably a bug in Github issue templates.

So I had to recreate the issue from scratch.

The root cause (in addition to Github's bug of not allowing shortening and resubmitting) is that you ask for the failing command with `--verbose --debug`. The full verbose logs of `brew uninstall little-snitch --verbose --debug` are more then 225k characters, more than 3 times the character limit.

This results in a very very lengthy log that exceeds the issue limits. You should change the template to no longer require this output.

This is the issue where I noticed this problem: #187348 

### Command that failed

Submission of Github issue following template instructions

### Output of command with `--verbose --debug`

```shell
N/A
```

### Output of `brew doctor` and `brew config`

```shell
N/A
```

### Output of `brew tap`

```shell
N/A
```

**Comment by bevanjkay** [comment]
The verbose logs are required to gather the sufficient information to debug an issue correctly.
