### ISSUE TITLE
Subcommand nrfutil-settings not found

### ISSUE THREAD

**Issue by taile2007** [Homebrew/homebrew-cask#187772]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

I was trying to compile nRF52 code with MacOS using ARM gcc. At the end of the process, the error of command "settings" not found with nrfutil at https://formulae.brew.sh/cask/nrfutil. I'm using Python 3.9.6

### Command that failed

Yes

### Output of command with `--verbose --debug`

```shell
n/a
```

### Output of `brew doctor` and `brew config`

```shell
n/a
```

### Output of `brew tap`

```shell
n/a
```

**Comment by daeho-ro** [comment]
https://docs.nordicsemi.com/bundle/nrfutil/page/README.html#nrf-util-commands

I cannot find `settings` command for that.

**Comment by bevanjkay** [comment]
Please answer all questions in the issue template.

**Comment by taile2007** [comment]
Hi. Sorry for the late response! Please find the link mentioning about the use of settings to create bootloader settings.
https://docs.nordicsemi.com/bundle/nrfutil/page/guides-nrf5sdk/generating_bootloader_settings.html
Seems like this is only available for the nRF Util (version 6.1.0 and lower). Thanks
