### ISSUE TITLE
Implement methods for shim scripts

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-cask#18809]
@caskroom/maintainers This replaces https://github.com/caskroom/homebrew-cask/issues/9203. Everyone agrees shim scripts are desirable, so lets allow them.

On a first phase, if anyone submits a cask that employs a shim script (usually inside a `preflight` and using ruby methods to write to a file), we should (after determining it is indeed necessary and we have no other way to fix the problem) accept it and **add a comment mentioning it’s a shim** (this will allow us to find them easier to study/replace).

On a second phase (the point of this issue), we should implement something to make those easier to make. So, two points:
- Should we really implement something to make them easier, or should we just accept them in their usual rough form (has the advantage of not encouraging them, which is good since they should be used as a last resort)?
- Any suggestions for implementations/interface?

**Comment by adidalal** [comment]
https://github.com/caskroom/homebrew-cask/blob/master/Casks/minecraft-server.rb - add comment
https://github.com/caskroom/homebrew-cask/pull/15876 - needs new PR w/ comment
https://github.com/caskroom/homebrew-cask/pull/9101 - needs new PR w/ comment

**Comment by vitorgalvao** [comment]
#15876 doesn’t apply, because the shim isn’t necessary (the tool officially creates the necessary script).

**Comment by psibre** [comment]
@vitorgalvao thanks for the heads up and for quickly merging #18827 -- I'll see if I can contribute a test and shim script

**Comment by psibre** [comment]
A thought occurs: is it even possible to add some sort of test to ensure that the shim script works correctly? I'm thinking of something along the lines of the [`test` block](/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#add-a-test-to-the-formula) in homebrew formulas...

**Comment by vitorgalvao** [comment]
@psibre No, we don’t have anything like that. Shim scripts should be discouraged, though (and only used in specific situations). This is not really related to this issue at hand (this issue is about deciding on an interface for shim scripts), so I ask that you open a new issue for further questions (every caskroom mantainer is likely getting an email to each reply to this issue, so we should really stay on topic).

**Comment by adidalal** [comment]
What's the official comment for a shim script?

**Comment by vitorgalvao** [comment]
> What's the official comment for a shim script?

I guess `# shim script (https://github.com/caskroom/homebrew-cask/issues/18809)` is OK.
