### ISSUE TITLE
Google Drive 98.0 update broken (but installs directly from DMG just fine)

### ISSUE THREAD

**Issue by thomaswitt** [Homebrew/homebrew-cask#188594]
@bevanjkay The 98.0 upgrade for Google Dreivedoesn't work - always fails with (manual installation works fine):

```
==> Upgrading google-drive
==> Downloading https://dl.google.com/drive-file-stream/5-percent/GoogleDrive.dmg
Already downloaded: /Users/thomas/Library/Caches/Homebrew/downloads/84693b003c10517f01579bedcab912bc7c5fa5c3b18a8b838de123793c4f0fa7--GoogleDrive.dmg
Warning: No checksum defined for cask 'google-drive', skipping verification.
==> Removing launchctl service com.google.GoogleUpdater.wake.system
==> Uninstalling packages with sudo; the password may be necessary:
com.google.drivefs.arm64
com.google.drivefs.shortcuts
==> Running installer for google-drive with sudo; the password may be necessary.
installer: Package name is Google Drive
installer: Upgrading at base path /
installer: The upgrade failed.
==> Purging files for version 98.0 of Cask google-drive
==> Purging files for version 98.0 of Cask google-drive
Warning: Reverting upgrade for Cask google-drive
==> Running installer for google-drive with sudo; the password may be necessary.
installer: Package name is Google Drive
installer: Upgrading at base path /
installer: The upgrade was successful.
Error: google-drive: Failure while executing; `/usr/bin/sudo -u root -E LOGNAME=thomas USER=thomas USERNAME=thomas -- /usr/sbin/installer -pkg /opt/homebrew/Caskroom/google-drive/98.0/GoogleDrive.pkg -target /` exited with 1. Here's the output:
installer: Package name is Google Drive
installer: Upgrading at base path /
installer: The upgrade failed.
```

But when I open the DMG manually and run the installer with the same command directly from the DMG volume, it works fine:

```
thomas@MacStudio:~ $ open /Users/thomas/Library/Caches/Homebrew/downloads/84693b003c10517f01579bedcab912bc7c5fa5c3b18a8b838de123793c4f0fa7--GoogleDrive.dmg
thomas@MacStudio:~ $ /usr/bin/sudo -u root -E LOGNAME=thomas USER=thomas USERNAME=thomas -- /usr/sbin/installer -pkg /Volumes/Install\ Google\ Drive/GoogleDrive.pkg -target /
installer: Package name is Google Drive
installer: Upgrading at base path /
installer: The upgrade was successful.
```

_Originally posted by @thomaswitt in https://github.com/Homebrew/homebrew-cask/issues/187113#issuecomment-2413215830_

**Comment by Bo98** [comment]
Is there any further information in `/var/log/install.log`? Quite a few things get logged there so have to search around for it.

**Comment by bevanjkay** [comment]
I was unable to replicate this myself, Google Drive updated just fine.
Can you also provide the output of `brew config` and `brew doctor`

**Comment by thomaswitt** [comment]
@bevanjkay Thx for the hint regarding install.log - could have thought about this myself. It seemed the Google Updater was somehow corrupted. After deleting the LaunchDaemons and the Updater itself, it works fine. Sorry for the hassle and thanks for the tip.

**Comment by thomaswitt** [comment]
@bevanjkay Just FYI for whoever reads that, I keep constantly having trouble with that update. It always fails at

```
installer:%97.750000
installer: The upgrade failed.
```

Last time I could solve it via deleting LaunchDaemons, this time that doesn't do the job. Even uninstalling and re-installing fails. Manual install via opening the same DMG and double clicking the installer just works fine. Also command line via

`/usr/bin/sudo -u root -E LOGNAME=thomas USER=thomas USERNAME=thomas -- /usr/sbin/installer -pkg /Volumes/Install\ Google\ Drive/GoogleDrive.pkg -target /`

straight from the DMG works. But the install after the copy orgy via
`/usr/bin/sudo -u root -E LOGNAME=thomas USER=thomas USERNAME=thomas -- /usr/sbin/installer -pkg /opt/homebrew/Caskroom/google-drive/100.0/GoogleDrive.pkg -target /`

keeps on failing. I couldn't find out from the logs why it does that, but maybe it would be easier if the installer installs straight from the DMG.

So I stopped using the cask and installed Google Drive manually.

**Comment by bevanjkay** [comment]
Can you please provide the output of `brew config` and `brew doctor`?
It's usually required in the issue template, but opening an issue from a comment bypasses this.

**Comment by thomaswitt** [comment]
@bevanjkay 
```
~ $ brew config
HOMEBREW_VERSION: 4.4.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 254bf3fe9d8fa2e1b2fb55dbcf535b2d870180c4
Last commit: 5 days ago
Core tap JSON: 15 Nov 22:27 UTC
Core cask tap JSON: 15 Nov 22:27 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /opt/homebrew/bin/vim
HOMEBREW_MAKE_JOBS: 24
Homebrew Ruby: 3.3.6 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: 24-core 64-bit arm_blizzard_avalanche
Clang: 16.0.0 build 1600
Git: 2.47.0 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.1-arm64
CLT: 16.1.0.0.1.1729049160
Xcode: 16.1
Rosetta 2: false
~ $ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install python-lxml

Run `brew missing` for more details.
~ $
```
