### ISSUE TITLE
mysqlworkbench 8.0.40 is broken

### ISSUE THREAD

**Issue by christian-andersson** [Homebrew/homebrew-cask#190115]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

mysqlworkbench 8.0.40 is broken, they forgot to add the mysql_native_plugin meaning that anyone that uses ordinary username/password to login to database will not work.

see the following issue in mysql
https://bugs.mysql.com/bug.php?id=116377

Mysql has also removed 8.0.40 of the workbench from their download page

### Command that failed

no failed brew command

### Output of command with `--verbose --debug`

```shell
not needed
```

### Output of `brew doctor` and `brew config`

```shell
not needed
```

### Output of `brew tap`

```shell
not needed
```

**Comment by edufalcao** [comment]
They fixed the package and re-uploaded that with the same version number. I tried locally and it worked 
https://bugs.mysql.com/bug.php?id=116377.
