### ISSUE TITLE
Fix link at https://formulae.brew.sh/cask/cheatsheet

### ISSUE THREAD

**Issue by macau23** [Homebrew/homebrew-cask#191401]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

Bad link at https://formulae.brew.sh/cask/cheatsheet

is:
https://wwww.mediaatelier/de/GrandTotal/

should be:
https://www.mediaatelier.de/GrandTotal/

### Command that failed

see above

### Output of command with `--verbose --debug`

```shell
.
```

### Output of `brew doctor` and `brew config`

```shell
.
```

### Output of `brew tap`

```shell
.
```

**Comment by macau23** [comment]
Invalid. They screwed up the redirect.

**Comment by daeho-ro** [comment]
Yeap, there is nothing can do here.

```
curl -X HEAD -I https://www.mediaatelier.com/CheatSheet/
HTTP/2 301
set-cookie: PHPSESSID=1b5338627fcc3ddd1ad02c046ca1ab04; path=/; secure
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
location: https://wwww.mediaatelier/de/GrandTotal/
```

**Comment by daeho-ro** [comment]
I got the response,

>Hi Daeho
>
>CheatSheet has been discontinued 2 years ago.
>
>Please check out following alternatives:
>http://www.ergonis.com/products/keycue/
>https://sergii.tatarenkov.name/keyclu/support/

that is not I wanted but anyway they don't think to fix it.

**Comment by khipp** [comment]
Closing as per above.
