### ISSUE TITLE
All PR checks failing at `zizmor` step

### ISSUE THREAD

**Issue by unitof** [Homebrew/homebrew-cask#191585]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

Recently all PR Actions in this repo (homebrew/homebrew-cask) have begun failling, always on the step:

```
zizmor --format sarif . >results.sarif
  shell: /usr/bin/bash -xeuo pipefail {0}
  env:
    HOMEBREW_DEVELOPER: 1
    HOMEBREW_NO_AUTO_UPDATE: 1
    HOMEBREW_NO_ENV_HINTS: 1
    HOMEBREW_NO_INSTALL_FROM_API: 
    HOMEBREW_GITHUB_API_TOKEN: ***
+ zizmor --format sarif .
Error: Process completed with exit code 14.
```

or

```
Run actions/download-artifact@v4
Downloading single artifact
Error: Unable to download artifact(s): Artifact not found for name: results.sarif
        Please ensure that your artifact is not expired and the artifact was uploaded using a compatible version of toolkit/upload-artifact.
        For more information, visit the GitHub Artifacts FAQ: https://github.com/actions/toolkit/blob/main/packages/artifact/docs/faq.md
```

Examples:
* https://github.com/Homebrew/homebrew-cask/actions/runs/11772005269/job/32786760680
* https://github.com/Homebrew/homebrew-cask/actions/runs/11771865685/job/32786411588?pr=191582
* https://github.com/Homebrew/homebrew-cask/actions/runs/11770833917/job/32783841725?pr=191570
* https://github.com/Homebrew/homebrew-cask/actions/runs/11772865530/job/32788879344?pr=191584

### Command that failed

zizmor --format sarif . >results.sarif

### Output of command with `--verbose --debug`

```shell
n/a
```

### Output of `brew doctor` and `brew config`

```shell
n/a
```

### Output of `brew tap`

```shell
n/a
```

**Comment by bevanjkay** [comment]
Thanks @unitof - it's being looked into. Note that it is a non-blocking error because the job is not required in the CI suite, so the failures don't cause any particular trail-on effects for now.

**Comment by woodruffw** [comment]
https://github.com/Homebrew/brew/pull/18753 will fix this, once the workflow changes there propagate to the rest of the repos 🙂
