### ISSUE TITLE
`malwarebytes` cask isn't found for livecheck

### ISSUE THREAD

**Issue by huyz** [Homebrew/homebrew-cask#192336]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

There is a `malwarebytes` cask at: https://github.com/Homebrew/homebrew-cask/blob/defdf682219678f95cb852e976d5bf5b87c1f25d/Casks/m/malwarebytes.rb

Indeed I can `search`, `info`, and `install` just fine, as I've been using it for a few years.

But the brew CLI doesn't seem to find this cask for some reason for `livecheck` or `bump --open-pr`:
```
❯ brew livecheck --cask malwarebytes
Error: Cask 'malwarebytes' is unavailable: No Cask with this name exists.
❯ brew bump --open-pr malwarebytes
Error: No available formula with the name "malwarebytes".

❯ brew info --cask malwarebytes
==> malwarebytes: 5.7.1.1804 (auto_updates)
https://www.malwarebytes.com/mac/
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/m/malwarebytes.rb
==> Name
Malwarebytes for Mac
==> Description
Scan and remove malware, spyware, and viruses
==> Artifacts
Malwarebytes-Mac-5.7.1.1804.pkg (Pkg)
==> Caveats
malwarebytes requires a kernel extension to work.
If the installation fails, retry after you enable it in:
  System Settings → Privacy & Security

For more information, refer to vendor documentation or this Apple Technical Note:
  https://developer.apple.com/library/content/technotes/tn2459/_index.html

==> Analytics
install: 107 (30 days), 388 (90 days), 1,954 (365 days)
```

There actually isn't a need for an update as `5.7.1.1804` is indeed the latest at https://www.malwarebytes.com/mac-download and thus the cask definition has the latest version tag. But I still would expect the `livecheck` and `bump` commands to find the cask.

I did check the URL `https://data-cdn.mbamupdates.com/web/mb#{version.major}_mac/Malwarebytes-Mac-#{version}.pkg` and the livecheck URL https://downloads.malwarebytes.com/file/mb-mac and they work fine from my browser when I manually interpolate and navigate to them.

### Command that failed

brew livecheck --cask malwarebytes

### Output of command with `--verbose --debug`

```shell
Error: Cask 'malwarebytes' is unavailable: No Cask with this name exists.
```

### Output of `brew doctor` and `brew config`

```shell
❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  dozer
  graphiql
  kapitainsky-rclone-browser
  meld
  mysides
  pdf-images
  recipeui
  robo-3t
  shortcutdetective
  sourcetrail
  tenor
  ui-browser

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  dog
  openssl@1.1
  packer

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/Spyder.dylib
  /usr/local/lib/Spyder3.dylib
  /usr/local/lib/Spyder5.dylib
  /usr/local/lib/dccmtr.dylib
  /usr/local/lib/dcxmtr.dylib
  /usr/local/lib/libCIEHandler.dylib
  /usr/local/lib/libCalibrationHandler.dylib
  /usr/local/lib/libDeviceManager.dylib
  /usr/local/lib/libErrorHandler.dylib
  /usr/local/lib/libICMManager.dylib
  /usr/local/lib/libMCCAppManager.dylib
  /usr/local/lib/libMCCEngineWrapper.dylib
  /usr/local/lib/libMonitorDDCCISDK.dylib
  /usr/local/lib/libProtocolEngine.dylib
  /usr/local/lib/libmkusb.dylib
  /usr/local/lib/libusb-1.0.0.dylib

❯ brew config
HOMEBREW_VERSION: 4.4.5-50-gaf47c78
ORIGIN: https://github.com/Homebrew/brew
HEAD: af47c78dece2ff905a7cfec93695d950d26ad331
Last commit: 4 hours ago
Core tap JSON: 17 Nov 04:39 UTC
Core cask tap JSON: 17 Nov 04:39 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BROWSER: open
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.6 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.47.0 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 14.7.1-arm64
CLT: 16.1.0.0.1.1729049160
Xcode: 16.1
Rosetta 2: false
```

### Output of `brew tap`

```shell
acrogenesis/macchanger
ameshkov/tap
charmbracelet/tap
cormacrelf/tap
dart-lang/dart
grishka/grishka
homebrew/services
jakehilborn/jakehilborn
mongodb/brew
mvp/uhubctl
nextdns/tap
noahgorstein/tap
railwaycat/emacsmacport
saulpw/vd
teamookla/speedtest
textualize/homebrew
tuist/tuist
tylerbrock/saw
```

**Comment by daeho-ro** [comment]
I think... you are in developer mode and so have to tap for homebrew defaults?
```
brew tap homebrew/cask
brew tap homebrew/core
```
Not sure.

**Comment by huyz** [comment]
That's possible. I may have tried to edit casks definitions in the past.

```
brew tap homebrew/cask --force
```

did fix it for me.

I can't figure out how I can see if I'm in developer mode and how to revert that. Do you know?

**Comment by daeho-ro** [comment]
```
brew developer
```
to see the status, and 
```
brew developer off
```
to turn off.

**Comment by huyz** [comment]
Great, thanks. I guess that'll do it

**Comment by huyz** [comment]
Interestingly, running `brew livecheck` automatically turns on developer mode :)

**Comment by SMillerDev** [comment]
Yeah, it's a developer command. There's no real reason to run it except to "develop" updates
