### ISSUE TITLE
codesign openscad@snapshot

### ISSUE THREAD

**Issue by rob-miller** [Homebrew/homebrew-cask#192475]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

OpenSCAD is/are having problems with signing/authenticating their binaries for MacOS.  They seem to have sorted it for the released binary, but the fix doesn't get applied to their nightly builds.  As you will know from other Homebrew issue threads on codesigning apps, a solution as suggested for users in [this issue discussion](https://github.com/openscad/openscad/issues/880#issuecomment-2474781056) is:

`codesign --deep -f -s - /Applications/OpenSCAD.app`

Would it be possible to add this to the Homebrew cask code for openscad@snapshot ?

Mine is an Intel mac.  

### Command that failed

open -a OpenScad

### Output of command with `--verbose --debug`

```shell
The application /Applications/OpenSCAD.app cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x600003b28960 {Error Domain=NSPOSIXErrorDomain Code=162 "Unknown error: 162" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}
rob@ra~:0s> brew update openscad
```

### Output of `brew doctor` and `brew config`

```shell
adm1n@ra:18 09:46:39 ~ $ brew doctor
Your system is ready to brew.

adm1n@ra:18 10:02:05 ~ $ brew config
HOMEBREW_VERSION: 4.4.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: cc0b5d6d05d1f3af5b2f53e9fbb1e7bfa0c332ab
Last commit: 27 hours ago
Core tap JSON: 18 Nov 13:27 UTC
Core cask tap JSON: 18 Nov 13:36 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: ["--fontdir=/Library/Fonts"]
HOMEBREW_EDITOR: /usr/local/bin/mg
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 3.3.6 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 16.0.0 build 1600
Git: 2.47.0 => /usr/local/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.1-x86_64
CLT: 16.1.0.0.1.1729049160
Xcode: 16.1
```

### Output of `brew tap`

```shell
adm1n@ra:18 10:02:23 ~ $ brew tap
brewsci/bio
homebrew/services
ivandokov/contrib
jakehilborn/jakehilborn
adm1n@ra:18 10:02:43 ~ $
```

**Comment by SMillerDev** [comment]
> Would it be possible to add this to the Homebrew cask code for openscad@snapshot ?

No, Homebrew will not pretend that external unsigned binaries are actually signed.

**Comment by kintel** [comment]
Binaries under https://openscad.org/downloads.html#snapshots are now signed and notarized; we finally caved in and paid Apple the extortion fee.
