### ISSUE TITLE
chromium: Missing API keys, Chromium features are disabled

### ISSUE THREAD

**Issue by Neved4** [Homebrew/homebrew-cask#193814]
This is not a command issue, could be considered more of a bug in how Chromium is currently shipped. See Debian Bug report below.

### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

Currently, Chromium shipped via Homebrew lacks Google API keys, which disables certain features such as Safe Browsing, Geolocation, and Spelling Suggestions. See:

> _The key in question allows access to nine separate Google services including Spelling, Suggest, Translate, Geolocation, Safe Browsing, and so on. While some of those features could be considered optional, losing them would certainly degrade users' experience compared to Chrome browser users—or even Firefox users—in many cases. It's a little strange to see a feature added that requires a magic key in order to use it, but the restrictions on what can be done with the APIs and keys makes it all the more worrisome._

Debian also had this issue and seem to have fixed it [10 years ago][Debian Bug Tracker - #748867]. We could either reuse [Debian API keys] or get Google to assign a set of keys for the Homebrew project.

#### See also

[The Chromium Project - API Keys]  
[LWN.net - Chromium API keys on Debian]  
[Debian Bug Tracker - #748867]
[Debian API keys]

[The Chromium Project - API Keys]: https://www.chromium.org/developers/how-tos/api-keys/
[LWN.net - Chromium API keys on Debian]: https://lwn.net/Articles/570485/
[Debian Bug Tracker - #748867]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=748867
[Debian API keys]: https://salsa.debian.org/chromium-team/chromium/-/commit/ee87a9416a0c9e522b914f86a3127eb5893a4768

### Command that failed

N/A

### Output of command with `--verbose --debug`

```shell
N/A
```

### Output of `brew doctor` and `brew config`

```shell
N/A
```

### Output of `brew tap`

```shell
N/A
```

**Comment by SMillerDev** [comment]
That page from the chromium project is very specific. It mentions that anyone who did not accept the ToS for these keys is not allowed to use them. So I don't think Homebrew should go against that rule.

**Comment by Neved4** [comment]
Sounds good, it'd be much better to get Google to assign a set of keys for Homebrew.

**Comment by Neved4** [comment]
Closing based on the discussions in https://github.com/Homebrew/homebrew-cask/issues/193814#issuecomment-2509767471 and https://github.com/Homebrew/homebrew-cask/pull/193815#issuecomment-2510296355. Thx again!

**Comment by Neved4** [comment]
For anyone stumbling across this on macOS, here's a rundown:

1. With `launchctl setenv`, you can set the values for a current session.
2. To persist across reboots, you can use a `launchd` script.
3. The above will set the variables globally. Setting them on a per-app basis will ensure isolation from other processes. To do this, you can feed the values into `Info.plist` with `plutil`, but note it will not survive app upgrades.
4. You can also edit `Info.plist` manually with an editor, and add the values after `LSEnvironment`.

G'luck!
