### ISSUE TITLE
microsoft-office installer not compatible with macos < 13.0

### ISSUE THREAD

**Issue by guillaume-ferry** [Homebrew/homebrew-cask#194267]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

Since 16.91.24.111020, microsoft office installer (https://github.com/Homebrew/homebrew-cask/blob/2466cf94e1b40dce8b7eedcfeda56945801d5ac2/Casks/m/microsoft-office.rb#L5C8-L5C131) does'nt support macos <13.
Update needed : https://github.com/Homebrew/homebrew-cask/blob/2466cf94e1b40dce8b7eedcfeda56945801d5ac2/Casks/m/microsoft-office.rb#L27

### Command that failed

brew install microsoft-office

### Output of command with `--verbose --debug`

```shell
==> Downloading https://formulae.brew.sh/api/formula.jws.json
########################################################################################################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
########################################################################################################################################################### 100.0%
==> Downloading https://officecdnmac.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/Microsoft_365_and_Office_16.91.24111020_Installer.pkg
Already downloaded: /Users/homebrew//Library/Caches/Homebrew/downloads/cb88d71f416ad14ff2237313370d46de9d04792d1b9145021553ba9cd7841d24--Microsoft_365_and_Office_16.91.24111020_Installer.pkg
All dependencies satisfied.
==> Installing Cask microsoft-office
	==> Running installer for microsoft-office with sudo; the password may be necessary.
installer: Error - Ce logiciel requiert macOS version 13.0 ou une version supérieure.
==> Purging files for version 16.91.24111020 of Cask microsoft-office
Error: Failure while executing; `/usr/bin/sudo -u root -E LOGNAME=homebrew USER=homebrew USERNAME=homebrew -- /usr/sbin/installer -pkg /usr/local/Caskroom/microsoft-office/16.91.24111020/Microsoft_365_and_Office_16.91.24111020_Installer.pkg -target / -applyChoiceChangesXML /private/tmp/choices20241205-90585-w3lagj.xml` exited with 1. Here's the output:
installer: Error - Ce logiciel requiert macOS version 13.0 ou une version supérieure.
```

### Output of `brew doctor` and `brew config`

```shell
Warning: You are using macOS 12.

brew config
HOMEBREW_VERSION: 4.4.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2e780004c92f16a96036d3d43569c2924c4e54f5
Last commit: 3 days ago
Branch: stable
Core tap JSON: 05 Dec 14:10 UTC
Core cask tap JSON: 05 Dec 14:10 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.3.6 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: 10-core 64-bit westmere
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: true
```

### Output of `brew tap`

```shell
/
```

**Comment by krehel** [comment]
Please feel free to open a PR to address this @guillaume-ferry!
