### ISSUE TITLE
CoverLoad won't download

### ISSUE THREAD

**Issue by morning-paradigm** [Homebrew/homebrew-cask#194482]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

- I've been trying to run `brew upgrade --cask coverload` (with `--force`) too, but when I ran the command there's nothing, not even a curl error, the command will just run without any output until I Ctrl+C.
- I see it trying to connect once in Little Snitch when run, but there's not traffic for that connection.
- I can download the file from the vendor’s website just fine.
- I even tried running `ln -s ~/Library/Caches/Homebrew/downloads/71fe1ff60856b2f1f978006246fc3873824b5215b7a15b9abf51ad8799014321--coverload-2.4.2-802.zip ~/Library/Caches/Homebrew/Cask/coverload-2.4.2-802.zip` (I think I got the filenames right) to trick Homebrew into thinking it's already downloaded but nothing changed.
- No issues with any other cask or formula.

### Command that failed

brew upgrade --cask coverload

### Output of command with `--verbose --debug`

```shell
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.4.10\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 -V
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.4.10\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.5\)\ curl/8.6.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://s3-us-west-2.amazonaws.com/coverloadapp.com/Uploads/CoverLoad-2.4.2-802.zip
```

### Output of `brew doctor` and `brew config`

```shell
❱ brew doctor
Your system is ready to brew.

❱ brew config
HOMEBREW_VERSION: 4.4.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8c868ba70e526f1f00561470d58fcbaddb1b4e48
Last commit: 35 hours ago
Branch: stable
Core tap JSON: 07 Dec 06:54 UTC
Core cask tap JSON: 07 Dec 07:01 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.3.6 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
alienator88/cask
brewforge/extras
buo/cask-upgrade
complexlogic/tap
homebrew/services
```

**Comment by bevanjkay** [comment]
I am unable to replicate this issue, is it still present for you?

**Comment by morning-paradigm** [comment]
I tried switching to the Homebrew installed curl, it didn't help.
But I kept 'export HOMEBREW_FORCE_BREWED_CURL=1`.  
Days later it just randomly worked. Not sure if that was related to the curl installation or just a connectivity issue.
