### ISSUE TITLE
logitech-g-hub uninstaller does not remove system extensions

### ISSUE THREAD

**Issue by sebseager** [Homebrew/homebrew-cask#194572]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

In the `logitech-g-hub` cask, the zap stanza does not remove system extensions added during install. For me, these are located at `/Library/SystemExtensions/59AEB536-F83A-4F22-8045-C690E43D3352/com.logi.ghub.audiooverride.dext` and `/Library/SystemExtensions/74D1458E-1796-412A-A73C-4F52F916B31F/com.logi.ghub.hidfilter.dext`. It's possible `lghub_updater --uninstall` was supposed to remove these, but I think they should be dealt with when running `--zap` anyway.

The user can also manually remove them in System Settings > General > Login Items & Extensions, so could also just add a caveat to the formula?

### Command that failed

brew uninstall -f --zap logitech-g-hub

### Output of command with `--verbose --debug`

```shell
N/A
```

### Output of `brew doctor` and `brew config`

```shell
N/A
```

### Output of `brew tap`

```shell
N/A
```

**Comment by kevin-stuart** [comment]
Just a hint, I found this post to be helpful when trying to fix G Hub: https://old.reddit.com/r/LogitechG/comments/bluth5/uninstaller_for_g_hub_for_mac/ - the entire uninstall did not work for me at all via homebrew. Did that work for you? I had to run the uninstall via the file manually downloaded again.

**Comment by krehel** [comment]
I think we are discovering there are issues specifically on ARM with this uninstaller (it is an Intel only binary) as I cannot get it to run correctly by calling the uninstaller directly, completely outside of Homebrew.

We're working on seeing what can be done but right now looking like two options -

1. Make the Cask `installer: manual` and have the user do the install/uninstall themselves
2. Rewrite the uninstall block, not use the provided uninstaller, and remove components individually.  This is the current attempt, but the Logitech software is... painful to say the least.

**Comment by krehel** [comment]
We think this is currently resolved via https://github.com/Homebrew/homebrew-cask/pull/195559 as far as removal is concerned.  We've removed the uninstall script and are using Homebrew native DSL to do the uninstall.  Please update and if there are problems please let us know!

Thanks!
