### ISSUE TITLE
Brew Cask formula for Sage (SageMath) does not include ARM binaries

### ISSUE THREAD

**Issue by culler** [Homebrew/homebrew-cask#194559]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

I hope this is the right place to report that (as I just discovered) the formula for the Sage package only provides access to an x86_64 version of SageMath-10-X.app.  But arm64 versions are also available, and have been since the beginning of the Sage_macOS project.

Also, I would like to let you know that, starting with SageMath-10-4.app, pip packages for SageMath-X-Y.app are installed in the directory `~/Library/SageMath-X-Y` rather than in `~/.sage` although the latter directory is still created by Sage when it is run via the app.  This was done to avoid mixing user installed packages from different versions of the app.  (Different versions of Sage can use the same version of python, but require different versions of python packages.)

### Command that failed

brew install sage

### Output of command with `--verbose --debug`

```shell
N/A
```

### Output of `brew doctor` and `brew config`

```shell
N/A
```

### Output of `brew tap`

```shell
N/A
```

**Comment by daeho-ro** [comment]
Are you using brew? It seems that the cask `sage` has an arm version and so if you install from arm machine, it should be installed correct version automatically.

**Comment by culler** [comment]
Great!  I thought that was how it worked.  But when I looked at [the formula](https://formulae.brew.sh/cask/sage) I saw this (with no mention of arm64):
<img width="695" alt="image" src="https://github.com/user-attachments/assets/752a6018-a765-4548-83d5-1dd199757b85">

I guess this is a false alarm.  Sorry!
