### ISSUE TITLE
un-deprecate Meld

### ISSUE THREAD

**Issue by jonatan-ivanov** [Homebrew/homebrew-cask#194791]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

Meld is now deprecated since the MacOS project seems to be discontinued, see: [meld.rb](https://github.com/Homebrew/homebrew-cask/blob/ad4922b0767e3e400873aa428e8207f6d69df8ac/Casks/m/meld.rb).

There is another project to make Meld working on MacOS by @dehesselle available here: https://gitlab.com/dehesselle/meld_macos/-/releases

Is it possible to change the cask and use the new project/location of the MacOS build of Meld?

### Command that failed

N/A

### Output of command with `--verbose --debug`

```shell
N/A
```

### Output of `brew doctor` and `brew config`

```shell
N/A
```

### Output of `brew tap`

```shell
N/A
```

**Comment by SMillerDev** [comment]
I don't think we should switch out the source, but I'd be happy to review a new cask

**Comment by jonatan-ivanov** [comment]
What do you mean by a new cask? The name of the project is still Meld, should it be like `meld-something.rb`? If so, what do you recommend? Fwiw, as a user, meld would be the expected name to me.

**Comment by SMillerDev** [comment]
> The name of the project is still Meld, should it be like meld-something.rb?

There is a guide for this in the docs, but generally it would end up as something like `<new_author>-<package_name>`.

> Fwiw, as a user, meld would be the expected name to me.

Sure, but we can't have multiple packages with the same name. And it would be more harmful if we stopped `meld` from pointing to the source people have come to expect from it. When this becomes the source people expect we can probably rename it to meld
