### ISSUE TITLE
qwt - Qt6Qwt6 pkgconfig file has error

### ISSUE THREAD

**Issue by topher800** [Homebrew/homebrew-cask#196602]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

Sorry if this is in the wrong place, I couldn't find a straightforward answer in the docs of how to get to a maintainer.

/usr/local/opt/qwt/lib/pkgconfig//Qt6Qwt6.pc

lists requires from Qt5, these should be changed to Qt6:

  12   │ Requires: Qt5Widgets Qt5Concurrent Qt5PrintSupport Qt5Svg Qt5OpenGL

Those are correct for Qt5Qwt6

### Command that failed

brew install qwt

### Output of command with `--verbose --debug`

```shell
N/A
```

### Output of `brew doctor` and `brew config`

```shell
N/A
```

### Output of `brew tap`

```shell
N/A
```

**Comment by bevanjkay** [comment]
Hi @topher800 
The correct repo for this issue is [`homebrew-core`](https://github.com/homebrew/homebrew-core)
