### ISSUE TITLE
Bug report: `brew cask install` does not respect to pinned tap

### ISSUE THREAD

**Issue by cybertk** [Homebrew/homebrew-cask#22045]
(Already to run `brew update; brew cleanup; brew cask cleanup` before reporting my issue. It usually fixes things!)
### Description of issue

When a Cask (e.g. `nylas-n1.rb`) exists in both core tap **caskroom/cask** and user tap **cybertk/cask**, and user tap is pinned with `brew tap-pin cybertk/cask`. 

`brew cask install nylas-n1` will still install the cask of core tap **caskroom/cask**.

So the behavior I expect is to install the Cask in **cybertk/cask** tap, and it's just the purpose of `brew tap-pin` 

> Pin tap, prioritizing its formulae over core when formula names are supplied by the user. See also tap-unpin.
### Output of `brew tap`

```
$ brew tap
caskroom/cask
cybertk/cask
homebrew/core
homebrew/gui
homebrew/versions
```
### Output of `brew tap --list-pinned`

```
$ brew tap --list-pinned
cybertk/cask
```
### Output of `brew --version`

```
$ brew --version
Homebrew 0.9.9 (git revision cc0ca; last commit 2016-06-16)
Homebrew/homebrew-core (git revision db0a; last commit 2016-06-16)
```

**Comment by claui** [comment]
Thank you for your report.

As of today, Homebrew-Cask and Homebrew are different projects; likewise, a formula and a Cask are not the same thing. A rule that applies to formulae does not necessarily hold for Casks.

That said, I agree with you in terms of user expectation. It is reasonable for a user to pin a Cask tap and then expect `brew cask install` to behave like you suggested. While not exactly a bug, I feel this is a good candidate for an enhancement. :+1:

**Comment by vitorgalvao** [comment]
So much has changed since this was first opened, it definitely needs a recheck. Does this still happen, @cybertk?
