### ISSUE TITLE
Should cleanup command clear incomplete downloads?

### ISSUE THREAD

**Issue by carlosdagos** [Homebrew/homebrew-cask#23437]
I ran a cleanup command as two downloads were happening:

```
❯ brew cask cleanup
==> Removing cached downloads
/Users/carlos/Library/Caches/Homebrew/Cask/alfred--3.0.3_694.zip
/Users/carlos/Library/Caches/Homebrew/Cask/atom--1.9.2.zip
/Users/carlos/Library/Caches/Homebrew/Cask/dropbox--latest.incomplete
/Users/carlos/Library/Caches/Homebrew/Cask/spotify--latest.dmg.incomplete
==> This operation has freed approximately 135.4M of disk space.
```

You can see the `.incomplete` files being deleted. However once one of the downloads finished:

```
❯ brew cask install dropbox --force
==> Downloading https://www.dropbox.com/download?plat=mac&full=1
######################################################################## 100.0%
Error: Download failed on Cask 'dropbox' with message: No such file or directory -
(/Users/carlos/Library/Caches/Homebrew/Cask/dropbox--latest.incomplete,
/Users/carlos/Library/Caches/Homebrew/Cask/dropbox--latest)
```

**Comment by reitermarkus** [comment]
Files are now [locked during download](https://github.com/caskroom/homebrew-cask/pull/23492), but I'm leaving this open for now, as files should ideally be locked during the whole installation process.

**Comment by joh-klein** [comment]
What I would really like, would be a switch (i.e. `--incomplete`) to ignore incomplete downloads. Reason: I have a update script (something like: find all outdated cask, update those and after that do a cleanup) which, if there are large downloads, sometimes takes rather long and I have to stop it. But if I do, the `brew cask cleanup` removes all incomplete downloads and forces me to download them again the next time i start the script.

**Comment by reitermarkus** [comment]
@joh-klein, this issue is specific to your script, and hence should be handled in your script.

**Comment by vitorgalvao** [comment]
@reitermarkus Is this still worth pursuing?
