### ISSUE TITLE
Implement formula_renames.json

### ISSUE THREAD

**Issue by colindunn** [Homebrew/homebrew-cask#29716]
It was mentioned on #29677 by @adidalal that formula_renames.json should probably be implemented for times when a cask gets renamed.

This would be particularly applicable to the new cask outdated/upgrade feature #29301.

**Comment by colindunn** [comment]
Initial testing done on #29677 to get the ball rolling:

OK so I messed with it and can't get it to work.

Created a `formula_renames.json` file with just this:
```
{
  "chirp": "chirp-daily"
}
```

Reinstall:
```
> brew cask reinstall chirp
Error: undefined method `latest?' for nil:NilClass
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:36:in `clear_cache'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:14:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:101:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:62:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:15:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:6:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:6:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:111:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:150:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

Removed it and attempted to install by name:
```
> brew cask install chirp
Error: No available Cask for chirp. Did you mean one of:
caskroom/cask/chirp-daily
caskroom/cask/chirp-daily
Error: nothing to install
```

**Comment by adidalal** [comment]
I think this might be a homebrew core issue, or maybe just my initial assumption that HBC would support this out of the box was wrong.

@reitermarkus any thoughts?

**Comment by reitermarkus** [comment]
@adidalal, I'm not familiar with the code behind this, but I would also guess that your

> initial assumption that HBC would support this out of the box was wrong.

**Comment by commitay** [comment]
I meant to comment on this months ago and keep forgetting to.

I'm 👎  on the idea of `formula_renames`,  I think long term it will turn into a PITA to maintain. Improving `search` to use the `name` stanza would cover most cases where this is needed.

**Comment by vitorgalvao** [comment]
@commitay I agree `name` in `search` is more important.

However, doesn’t `formula_renames` do more? Like making the connection between the installed formula and its rename, so you don’t have issues `uninstall`ing?

I’m really asking, as I’m unsure.

**Comment by commitay** [comment]
My (possibly wrong) understanding of `formula_renames` is that it's a forced migration, i.e the original is completely removed and replaced by a new install.

**Comment by reitermarkus** [comment]
`formula_renames` migrates the Formula's prefix to the new name and allows installing Formulae with their old name as to not break installation scripts with the old name.

**Comment by wickles** [comment]
Is there any builtin function that would help determine which casks are migrated or removed?

In the meantime I got frustrated constantly finding out far later than ideal that my casks no longer exist. Here's a simple script to find migrated and removed casks.
```
brew-cask-migrated () {
    local installed=$(brew cask list -1)
    local casks=$(brew cask search)
    echo "$installed" | while read line; do
        if ! [[ $casks =~ (^|[[:space:]])$line($|[[:space:]]) ]]; then
            echo "$line"
        fi
    done
}
```
