### ISSUE TITLE
Show per-subcommand usage messages

### ISSUE THREAD

**Issue by raxod502** [Homebrew/homebrew-cask#41438]
### Description of feature/enhancement

Homebrew explains the usage of its subcommands when passed a `--help` flag. Cask does not provide (as far as I can tell) any way of determining what flags its subcommands take.

For consistency and ease of use, I think Cask should follow Homebrew and provide per-subcommand usage messages.

### Justification

Just before opening this issue, I was asked a question about `brew cask uninstall`, and I wondered if it took a `--force` flag like `brew uninstall`. The following ensued:

```
% brew cask help uninstall
% brew cask uninstall
% brew cask uninstall --help
% brew cask --help uninstall
% man brew-cask
```

This is four commands more than it should have taken to figure out what flags `brew cask uninstall` takes, in my opinion.

### Example use case

```
% brew cask uninstall --help
brew cask uninstall, rm, remove [--force] token [ token ... ]
    Uninstall the given Cask. With --force, uninstall even if the
    Cask does not appear to be present.
```

**Comment by reitermarkus** [comment]
> Cask does not provide (as far as I can tell) any way of determining what flags its subcommands take.

There is `man brew-cask`, but we'd accept a PR to add this functionality directly to `brew cask` commands.

**Comment by raxod502** [comment]
So will this be closed unless someone provides a pull request?

**Comment by vitorgalvao** [comment]
@raxod502 That’s the idea, yes. By having a bot detect and close down things nobody is interested in (enough to work on it) or that aren’t high priority enough for the maintainers to work on, we can focus the repo and find what really matters.

That doesn’t mean the issue can’t be revisited in the future, it just means that *right now* it isn’t worth keeping open.
