### ISSUE TITLE
The order of `language` blocks matters

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-cask#42755]
Title is a bit vague since the issue takes a few steps to properly explain.

In the [firefox cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/firefox.rb), we have:

```ruby
  language 'zh-TW' do
    sha256 '3f14be10147a050b551be5ee0d8f3de65a2f7518577ee4454e9b2575200b4271'
    'zh-TW'
  end

  language 'zh' do
    sha256 'e8cf292d80b7a04322880fb07b6e2f9ef171a0ff7715a7ff500397bc78962f1d'
    'zh-CN'
  end
```

Notice what happens when `fetch`ing each of those:

```
brew cask fetch firefox --language=zh
==> Downloading https://download-installer.cdn.mozilla.net/pub/firefox/releases/57.0.4/mac/zh-CN/Firefox%2057.0.4.dmg

brew cask fetch firefox --language=zh-TW
==> Downloading https://download-installer.cdn.mozilla.net/pub/firefox/releases/57.0.4/mac/zh-TW/Firefox%2057.0.4.dmg
```

They are bot correct. Now I’ll `brew cask edit firefox` and invert the order of those blocks, so they read:

```ruby
  language 'zh' do
    sha256 'e8cf292d80b7a04322880fb07b6e2f9ef171a0ff7715a7ff500397bc78962f1d'
    'zh-CN'
  end

  language 'zh-TW' do
    sha256 '3f14be10147a050b551be5ee0d8f3de65a2f7518577ee4454e9b2575200b4271'
    'zh-TW'
  end
```

Now let’s re`fetch`:

```
brew cask fetch firefox --language=zh
==> Downloading https://download-installer.cdn.mozilla.net/pub/firefox/releases/57.0.4/mac/zh-CN/Firefox%2057.0.4.dmg

brew cask fetch firefox --language=zh-TW
==> Downloading https://download-installer.cdn.mozilla.net/pub/firefox/releases/57.0.4/mac/zh-CN/Firefox%2057.0.4.dmg
```

Now they are both grabbing the `zh-CN` version, which is the one indicated by the `language 'zh' do`block. So it seems that **when there’s a language code *without* an hyphen, if it’s `language` block comes before those of the same language *with* an hyphen, it overpowers them on `install`**.

Noticed due to https://github.com/caskroom/homebrew-cask/issues/42752.

**Comment by commitay** [comment]
```
```
