### ISSUE TITLE
Return code of brew cask outdated remains

### ISSUE THREAD

**Issue by tyranron** [Homebrew/homebrew-cask#43226]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

##### What happened?

`brew cask outdated` does not respond with different return codes whether cask is outdated or not.
```bash
$ brew cask outdated minikube
minikube (0.24.1) != 0.25.0
$ brew cask outdated minikube || echo 1
minikube (0.24.1) != 0.25.0
$ brew cask outdated minikube && echo 1
minikube (0.24.1) != 0.25.0
1
$ brew cask reinstall minikube
==> Satisfying dependencies
All Formula dependencies satisfied.
==> Downloading https://storage.googleapis.com/minikube/releases/v0.25.0/minikub
######################################################################## 100.0%
...
==> Installing Cask minikube
==> Linking Binary 'minikube-darwin-amd64' to '/usr/local/bin/minikube'.
🍺  minikube was successfully installed!
$ brew cask outdated minikube || echo 1
$ brew cask outdated minikube && echo 1
1
```

##### What is expected to happen?

The similar behavior as with `brew outdated` command:
```bash
$ brew outdated wget
wget (1.18) < 1.19.4_1
$ brew outdated wget || echo 1
wget (1.18) < 1.19.4_1
1
$ brew outdated wget && echo 1
wget (1.18) < 1.19.4_1
$ brew upgrade wget
Updating Homebrew...
...
==> Upgrading 1 outdated package, with result:
wget 1.19.4_1
...
==> Pouring wget-1.19.4_1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/wget/1.19.4_1: 50 files, 3.7MB
$ brew outdated wget || echo 1
$ brew outdated wget && echo 1
1
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.5.2
caskroom/homebrew-cask (git revision f0503; last commit 2018-01-27)
==> macOS
10.12.6
==> SIP
Enabled
==> Java
9.0.1, 1.8.0_152, 1.7.0_60
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (7 files, 961MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3902 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (177 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by tyranron** [comment]
Temporary workaround is:
```bash
$ (brew cask outdated minikube | test -z) || echo 1
$ (brew cask outdated minikube | test -z) && echo 1
1
```

**Comment by reitermarkus** [comment]
I think it should be the other way around, right? `0` if it is outdated, otherwise `1`.

```bash
if brew cask outdated minikube; then
  brew cask upgrade minikube
fi
```

**Comment by tyranron** [comment]
@reitermarkus to be compatible with `brew outdated` it should be vice versa: `0` if is up-to-date, and `1` otherwise.

It seems a little bit illogical for me to, that `brew outdated` actually succeeds when package is up-to-date, not outdated. But I think it's better to be compatible with such upstream behavior to not confuse users like me 🙂

**Comment by vitorgalvao** [comment]
I’d even argue that an exit code should return the success of the *command*, not its contents. So a command that successfully tells you if there are or not outdated casks should always return `0`, no matter the actual response. A non-`0` exit code would only happen when the command itself failed to run.

But building software is a bunch of compromises and backwards compatibilities, so yes, we should return the same that `brew outdated` does.

**Comment by tyranron** [comment]
@vitorgalvao 

> A non-0 exit code would only happen when the command itself failed to run.

Can't agree with that. That's hardly depends on command's semantic and goal. Even more, such behavior makes such commands poorly suitable for automation.

However, both sides can be satisfied here with additional flag that switcher RC behavior.

**Comment by vitorgalvao** [comment]
@tyranron On the contrary, most guides on exit status state clearly that’s the appropriate behaviour. [Example](http://tldp.org/LDP/abs/html/exit-status.html):

> A successful command returns a 0, while an unsuccessful one returns a non-zero value that usually can be interpreted as an *error code*. Well-behaved UNIX commands, programs, and utilities return a 0 exit code upon successful completion, though there are some exceptions.

A `0` is a successful command execution and a non-`0` is a specific *error*.

Your own example above of using `&&` and `||` is inappropriate. You make no distinction between error codes so you have no way to differentiate between outdated formulae and a command error, *and those should be handled quite differently in your code*. To be that granular, you need to specify the *exact* error code. An error code of `1` is particularly poor in this situation, since that typically signifies a generic error. So if you want an error code to specify a specific successful condition, at the very least it should be non-`1`.

> However, both sides can be satisfied here with additional flag

That is absurd and unnecessary. There are no “sides to satisfy”. I stated clearly in my previous post that “**yes, we should return the same that `brew outdated` does**”. No one in this post is arguing for inconsistency.

**Comment by amyspark** [comment]
Does Cask have infrastructure in place to return exit codes? I've skimmed over the code and the usual `def run` does not have e.g. a `Homebrew.failed` to check.

**Comment by amyspark** [comment]
An example resolution is at https://github.com/Homebrew/brew/pull/5025.

**Comment by vitorgalvao** [comment]
Suggesting we reopen and merge https://github.com/Homebrew/brew/pull/5025 to close this.
