### ISSUE TITLE
Question: is brew-cask-completion still necessary

### ISSUE THREAD

**Issue by jasonkarns** [Homebrew/homebrew-cask#43813]
The [docs still state](https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md#tab-completion) that completion support should be installed via `brew install brew-cask-completion`.
> brew install brew-cask-completion 

However, with cask now part of homebrew core, it seems that brew cask's completion is provided OOTB by brew's completion script? (https://github.com/Homebrew/brew/blob/master/completions/bash/brew)

Is this correct or is brew-cask-completion still necessary? If brew-cask-completion is no longer necessary, I'd be happy to submit a PR to update the docs accordingly.

**Comment by MindTooth** [comment]
Added `brew cask` completion to fish-shell about a month ago too.

https://github.com/fish-shell/fish-shell/commit/fde647214d0cb8e9f3fcdcd7437fad47f57f7d32

**Comment by commitay** [comment]
> is brew-cask-completion still necessary?

For bash, no. For fish I think the completions are only available in `--HEAD`.

**Comment by MindTooth** [comment]
True.  I hope they release it soon.

**Comment by commitay** [comment]
PR updating the docs for bash and zsh. https://github.com/Homebrew/homebrew-cask/pull/48755

**Comment by MindTooth** [comment]
Updated completion for fish is released with the new [3.0.0](https://github.com/fish-shell/fish-shell/releases/tag/3.0.0) release.
