### ISSUE TITLE
Inconsistent CLI output when typed system user password is incorrect

### ISSUE THREAD

**Issue by walterdolce** [Homebrew/homebrew-cask#44835]
#### General troubleshooting steps

- N/A [ ] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- N/A [ ] I ran `brew update-reset && brew update` and retried my command.
- N/A [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

When the underlying logic taps into some system-level resources which require the administrator password, and the password is entered incorrectly, the output on the CLI is inconsistent. Please see below.

```
> brew cask upgrade
==> Upgrading 2 outdated packages, with result:
dotnet 2.0.6, dotnet-sdk 2.1.101
==> Satisfying dependencies
==> Downloading https://download.microsoft.com/download/8/D/A/8DA04DA7-565B-4372-BBCE-D44C7809A467/dotnet-runtime-2.0.6-osx-x64.pkg
######################################################################## 100.0%
==> Verifying checksum for Cask dotnet
==> Starting upgrade for Cask dotnet
==> Running uninstall process for dotnet; your password may be necessary
==> Uninstalling packages:
com.microsoft.dotnet.dev.2.1.4.component.osx.x64
Password:
Password:
==> Sorry, try again.
```

As you can see, there's the following at the end of the output:
```
Password:
Password:
==> Sorry, try again.
```
The first time, I entered the password incorrectly. The system correctly prompted for `Password:` again. But the `Sorry, try again` came through only after when I entered the password correctly and `brew cask upgrade` could continue to run. 

Hope that makes sense. Any question or anything I can do to help/fix this please let me know.

#### Output of `brew cask doctor`
N/A

**Comment by vitorgalvao** [comment]
Seems like https://github.com/caskroom/homebrew-cask/issues/7000 returned.
