### ISSUE TITLE
Dia.app: error “cannot open display” has returned. Regression?

### ISSUE THREAD

**Issue by claui** [Homebrew/homebrew-cask#46400]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [ ] None of the templates was appropriate for my issue, or I’m not sure.  
**(The appropriate template came up by default, and I’m using it right now)**
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

~#45650~ (**Edit:** #28511) has broken Dia for me. It aborts immediately on launch with status code 1 and the [error message _cannot open display_](https://navkirats.blogspot.de/2014/10/dia-diagram-mac-osx-yosemite-fix-i-use.html):

```
$ /Applications/Dia.app/Contents/Resources/bin/dia
22:28: execution error: „XQuartz“ hat einen Fehler erhalten: Das Programm läuft nicht. (-600)
Warning: AppleCollationOrder setting not found, using AppleLocale.
Setting Language: de.UTF8

(dia-bin:73320): Gtk-WARNING **: cannot open display: /private/tmp/com.apple.launchd.luAbLYqYkB/org.macosforge.xquartz:0
```

I can’t find any explanation or reason as to why the `Contents/Resources/bin/dia` script would “[n]o longer [need] to export the display”. Google suggests that the issue may indeed have vanished for most people but puzzling enough, for me the app still errors out consistently.

Setting `DISPLAY` to `:0` works around the issue as expected:

```
$ DISPLAY=':0' /Applications/Dia.app/Contents/Resources/bin/dia
```

How do we go about this? I’d be happy to maintain a private tap but I suspect other users (albeit very few) may have the same issue. Is it reasonable to re-insert the patch for everyone?

#### Command that failed

```
/Applications/Dia.app/Contents/Resources/bin/dia
```

#### Output of command with `--force --verbose --debug`

_(does not apply)_

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.6.2-33-g27ec9da
caskroom/homebrew-cask (git revision 85020; last commit 2018-04-26)
==> macOS
10.12.6
==> SIP
Enabled
==> Java
10.0.1, 1.8.0_172
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (48 files, 3.7GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3956 casks)
/usr/local/Homebrew/Library/Taps/bsiegel/homebrew-tap (1 cask)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (143 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1160 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (176 casks)
/usr/local/Homebrew/Library/Taps/claui/homebrew-cask-aged (9 casks)
/usr/local/Homebrew/Library/Taps/claui/homebrew-cask-games (2 casks)
/usr/local/Homebrew/Library/Taps/claui/homebrew-cask-test (3 casks)
/usr/local/Homebrew/Library/Taps/claui/homebrew-cask-unofficial (4 casks)
/usr/local/Homebrew/Library/Taps/claui/homebrew-cask-versions (3 casks)
/usr/local/Homebrew/Library/Taps/claui/homebrew-textmate (6 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
bsiegel/tap
caskroom/cask
caskroom/drivers
caskroom/fonts
caskroom/versions
claui/cask-aged
claui/cask-games
claui/cask-test
claui/cask-unofficial
claui/cask-versions
claui/cleanup-bin
claui/public
claui/services-bulk
claui/tap-git
claui/textmate
claui/unofficial
ethereum/ethereum
homebrew/core
homebrew/dev-tools
homebrew/dupes
homebrew/games
homebrew/gui
homebrew/science
homebrew/services
homebrew/x11
jaybrown/cn
mistertea/et
osx-cross/avr
rosaland/rosa
vitorgalvao/tiny-scripts
watsonbox/cmu-sphinx
```

Edit: fixed issue reference.

**Comment by vitorgalvao** [comment]
> Is it reasonable to re-insert the patch for everyone?

I’m fine with that.

But I’d also like for an issue to be opened with the developers about this, and a comment above the fix pointing to the online discussion.

**Comment by claui** [comment]
Still trying to figure out where to file that issue. Looks like the issue is in the build process/a build artifact, which is not part of the upstream project but handled separately, and overseen by an individual maintainer, who [passed away in 2014](https://mail.gnome.org/archives/dia-list/2014-November/msg00047.html). The latest binary release for Mac predates that. It’s not clear who even has access to the Mac build scripts as of today.

Not sure who to ask about the Mac release process as it seems pretty much abandoned.
