### ISSUE TITLE
'brew install borg' conflict with 'brew cask install borgbackup' (1 link: /usr/local/bin/borg)

### ISSUE THREAD

**Issue by dukechem** [Homebrew/homebrew-cask#47428]
The /usr/local/bin/borg link is used by 2 independent formula: "brew install borg" and "brew cask install borgbackup" 

brew info borg
Terminal based search engine for bash commands
https://github.com/ok-borg/borg

That is, formula 'brew cask install borgbackup' has 1 conflict with 'brew install borg': they both want to create a /usr/local/bin/borg symlink.

The borgbackup via ssh expects to find a binary named "borg" in the path, and /usr/local/bin/borg is the one and only symlink created by "brew cask install borgbackup".

I propose easy fix: that the borgbackup formula should warn of conflict and suggest "brew uninstall borg" or at least "brew unlink borg". 

Seems that any one with the expertise to use the ok-borg/borg should be able to manually create the their own appropriate links.

#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x ] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs).
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

The /usr/local/bin/borg link is used by 2 independent formula: brew install borg and brew cask install borgbackup

#### Command that failed

```
brew install borg

```

#### Output of command with `--force --verbose --debug`

```
bash-3.2$ brew install --force --verbose --debug borg
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/borg.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/go.rb
==> Downloading https://homebrew.bintray.com/bottles/borg-0.0.3.high_sierra.bottle.tar.gz
Already downloaded: /Users/ml266/Library/Caches/Homebrew/borg-0.0.3.high_sierra.bottle.tar.gz
==> Verifying borg-0.0.3.high_sierra.bottle.tar.gz checksum
==> Pouring borg-0.0.3.high_sierra.bottle.tar.gz
tar xzf /Users/ml266/Library/Caches/Homebrew/borg-0.0.3.high_sierra.bottle.tar.gz
==> Finishing up
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/borg
Target /usr/local/bin/borg
already exists. You may want to remove it:
  rm '/usr/local/bin/borg'
...
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.6.3-56-g5e77335
caskroom/homebrew-cask (git revision fda3b; last commit 2018-05-20)
==> macOS
10.13.4
==> SIP
Enabled
==> Java
1.8.0_131
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (3 files, 83MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3956 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (178 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
bash-3.2$ 

```

#### Output of `brew tap`

```
bash-3.2$ brew tap
caskroom/cask
caskroom/versions
homebrew/bundle
homebrew/core
mcs07/cheminformatics
samangh/tap
bash-3.2$ 
```

**Comment by reitermarkus** [comment]
We have `conflicts_with formula:`, but it isn't implemented yet. Closing in favour of https://github.com/Homebrew/homebrew-cask/issues/12822.
