### ISSUE TITLE
https://caskroom.github.io/ not resolving

### ISSUE THREAD

**Issue by brianmorton** [Homebrew/homebrew-cask#47598]
I suspect this has to do with the move from caskroom to homebrew :)

**Comment by reitermarkus** [comment]
The website it still in the old location, it is working for me.

**Comment by brianmorton** [comment]
![image](https://user-images.githubusercontent.com/1434096/40557085-d8aa5c3c-6003-11e8-95ea-5babeee6b61e.png)

**Comment by reitermarkus** [comment]
Have you tried on a different device?

**Comment by brianmorton** [comment]
You are 100% correct, for some reason this location is having DNS issues with that - sorry for the disturbance!
