### ISSUE TITLE
uninstall pkgutil: should audit / warn when package not found

### ISSUE THREAD

**Issue by joshka** [Homebrew/homebrew-cask#47915]
### Description of feature/enhancement

In `brew cask audit` / `install` / `uninstall` warn when the package listed in the uninstall clause is not found.

### Justification

I just created of a few casks at https://github.com/joshka/homebrew-audio where the package name format changed across the versions / casks I was creating. It would be nice to be notified of this early.

### Example use case

Current
```
$ cat Casks/d16-phoscyon.rb
cask 'd16-phoscyon' do
  version '1.6.0'
  sha256 '97b55bd946d219deb5133ab71e393a2407829c382534abbee1511e047adbcd8a'

  url "http://d16.pl/pub/install/Phoscyon%20-%20#{version}.dmg"
  name 'D16 Phoscyon'
  homepage 'http://d16.pl/phoscyon'

  pkg 'Phoscyon.pkg'

  uninstall pkgutil: 'com.d16group.pkg.phoscyon'
end

$ brew cask audit --download d16-phoscyon
==> Downloading http://d16.pl/pub/install/Phoscyon%20-%201.6.0.dmg
Already downloaded: /Users/joshka/Library/Caches/Homebrew/Cask/d16-phoscyon--1.6.0.dmg
==> Verifying checksum for Cask d16-phoscyon
audit for d16-phoscyon: passed

$ brew cask style d16-phoscyon
1 file inspected, no offenses detected

$ brew cask install d16-phoscyon
Updating Homebrew...
==> Satisfying dependencies
==> Downloading http://d16.pl/pub/install/Phoscyon%20-%201.6.0.dmg
Already downloaded: /Users/joshka/Library/Caches/Homebrew/Cask/d16-phoscyon--1.6.0.dmg
==> Verifying checksum for Cask d16-phoscyon
==> Installing Cask d16-phoscyon
==> Running installer for d16-phoscyon; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are i
==> installer: Package name is Phoscyon
==> installer: Installing at base path /
==> installer: The install was successful.
🍺  d16-phoscyon was successfully installed!

$ brew cask uninstall d16-phoscyon
==> Uninstalling Cask d16-phoscyon
==> Running uninstall process for d16-phoscyon; your password may be necessary
==> Uninstalling packages:
==> Purging files for version 1.6.0 of Cask d16-phoscyon
```

New messages:
```
==> installer: The install was successful.
Warning: package listed in the uninstall stanza is not installed. This may indicate that the Cask has a bug. Try running `/usr/local/Homebrew/Library/Taps/Homebrew/homebrew-cask/developer/bin/list_recent_pkg_ids` to get a list of the most recently installed packages and consider submitting a PR to fix this.

==> Uninstalling packages:
Warning: package 'com.d16group.pkg.phoscyon' does not exist, it may have been manually uninstalled or there may be an error in the Cask.
```

This is a quick sanity check that this seems like the right thing to do, before investing the time to actually do it.

**Comment by commitay** [comment]
We check for leftover pkgs and other things as part of the travis script.

https://github.com/Homebrew/homebrew-cask/blob/master/ci/travis/script.sh

**Comment by commitay** [comment]
I'm not sure how practical this would be as it would need be able to handle wildcard/regexp input.
https://github.com/Homebrew/homebrew-cask/blob/11d5b4e1674b2de8a5cc22969c9a856e9e7f4984/Casks/dotnet-sdk.rb#L13

Also, some casks have uninstall scripts that may also remove the PKGID so while displaying a warning or error would be correct it may not be desirable. We may not want to remove the pkgutil uninstall in case the uninstall script changes.

**Comment by joshka** [comment]
Thanks for the sanity check. I’ll hook up Travis CI in my tap to check for this instead of making this change.

**Comment by commitay** [comment]
No problem and thanks for the suggestion nonetheless!
