### ISSUE TITLE
proxy bad URI

### ISSUE THREAD

**Issue by riccardocorbella** [Homebrew/homebrew-cask#47919]
The command **brew cask search \<something\>** gives the following error:

> Error: bad URI(is not URI?): http://<proxy_username>:<proxy_password>@<proxy_ip>:<proxy_port>
> Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
> /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/uri/rfc3986_parser.rb:67:in `split'
> /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/uri/rfc3986_parser.rb:73:in `parse'
> /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/uri/common.rb:227:in `parse'
> /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/uri/generic.rb:1556:in `find_proxy'
> /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:195:in `block in open_loop'
> /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'
> /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:210:in `catch'
> /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'
> /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
> /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:717:in `open'
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions/Casks/gpg-suite-nightly.rb:7:in `block (2 levels) in load'
> /usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/url.rb:10:in `block in from'
> /usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl/stanza_proxy.rb:8:in `block in once'
> /usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl/stanza_proxy.rb:21:in `to_s'
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions/Casks/gpg-suite-nightly.rb:12:in `block in load'
> /usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:32:in `instance_eval'
> /usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:32:in `initialize'
> /usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:31:in `new'
> /usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:31:in `cask'
> /usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:67:in `cask'
> /usr/local/Homebrew/Library/Homebrew/compat/hbc/cask_loader.rb:15:in `cask'
> /usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:113:in `cask'
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions/Casks/gpg-suite-nightly.rb:1:in `load'
> /usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:57:in `instance_eval'
> /usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:57:in `load'
> /usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:16:in `block in each'
> /usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:15:in `each'
> /usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:15:in `each'
> /usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/search.rb:46:in `map'
> /usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/search.rb:46:in `search'
> /usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/search.rb:8:in `run'
> /usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
> /usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
> /usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
> /usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
> /usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
> /usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
