### ISSUE TITLE
audit: language sort order and duplicates

### ISSUE THREAD

**Issue by commitay** [Homebrew/homebrew-cask#47949]
We should enforce an order in which the languages occur and also check that only one of each language is present.

**Comment by commitay** [comment]
@vitorgalvao Now we're all in the same org the `core` label might be confusing for some people as it refers to https://github.com/Homebrew/brew not https://github.com/Homebrew/homebrew-core

**Comment by adidalal** [comment]
Shouldn't order not matter?
https://github.com/Homebrew/brew/pull/4224

**Comment by commitay** [comment]
Different things, the other issue/PR is to fix which language is selected when installing.

This is for audit to sort languages in order and check only one of each language block exists to avoid something like this:
```
  language 'en-GB' do
    sha256 'f71618820e92e7c25622c03b25b8d95d4f3195a8f1ddabba79871e1c9bc49243'
    'en-GB'
  end

  language 'de' do
    sha256 '634aa70168d70e32058c6263f156af229c4965642225763a30ec91609cf81dee'
    'de'
  end

  language 'cs' do
    sha256 '2d5af247fe9c77b6463304e2e11bc2a94c9fa29dcb041bdb4b74b9c21f31b653'
    'cs'
  end

  language 'en-GB' do
    sha256 'f71618820e92e7c25622c03b25b8d95d4f3195a8f1ddabba79871e1c9bc49243'
    'en-GB'
  end
```
