### ISSUE TITLE
Casks, Taps, and Versioning

### ISSUE THREAD

**Issue by adidalal** [Homebrew/homebrew-cask#47950]
Extracted from https://github.com/Homebrew/homebrew-cask/issues/41990 as it is something that can warrant further discussion, but was dragging the conversation off-thread. **Feel free to continue the discussion below.**

[How to Create and Maintain a Tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md)

Copying a few quotes below for context:

https://github.com/Homebrew/homebrew-cask/issues/41990#issuecomment-393484921 @joshka 
> On the versions part of this (and this may be something to cut off into another issue - please suggest we do so if this thread is not the right place for this). A particular use case that I'd like to be able to solve easily came up the other day in conversation. A music producer friend had an old track that he wrote using a specific version of a VST (a synthesizer) which he couldn't find again. It would have been nice to be able to say `brew cask install some-synth@1.2.3` as the right solution for this.

https://github.com/Homebrew/homebrew-cask/issues/41990#issuecomment-393504741 @vitorgalvao 
> @joshka We’re talking about a change in nomenclature, meaning the rules on what old versions to actually include are not likely to change that much. I’d be surprised if in the case of your friend there were even two people in the exact same situation. Keeping multiple versions of plugins is not something we’ll aim for.

https://github.com/Homebrew/homebrew-cask/issues/41990#issuecomment-393625892 @mwean 
> Yeah I agree. I've had to switch away from homebrew for many of my development dependencies (e.g. postgresql) because I need precise control of versions.

https://github.com/Homebrew/homebrew-cask/issues/41990#issuecomment-393737215 @joshka 
> @claui I created https://github.com/joshka/homebrew-audio last night as a response to and issue of putting all the VSTs that a manufacturer makes into homebrew-cask would blow out the count of casks in the core repo for little upside. In there there are a few examples of this problem on a v1 to v2 cask as well as many examples where I explicitly included every version of every plugin available from d16 in the git history (I scripted the repo creation, I’m not insane). This means a person who needs 1.0.0 when 1.1.0 is out installs from a github link, while a person requiring the latest v1 uses brew cask install foo, and a v2 user does brew cask install foo2. 3 ways to install depending on the version.
> When I’m near a computer I’ll raise a seperate issue to track this instead of continuing in this thread. 
> Mike,
> In the case of software upgrades, another thing that explicitly changes is that software versions may be paid upgrades. Just because a piece of software upgrades doesn’t mean it includes any security content. The two problems are not tied to each other.

**Comment by MikeMcQuaid** [comment]
> This means a person who needs 1.0.0 when 1.1.0 is out installs from a github link

@joshka This approach means you cannot fix any issues in 1.0.0's cask, FYI.

**Comment by claui** [comment]
@joshka If you’re really determined to offer all past versions, what would keep you from laying out your tap as follows?

```
Casks/d16-devastor2
Casks/d16-devastor2.1.3.rb
Casks/d16-devastor2.1.2.rb
Casks/d16-devastor2.1.1.rb
Casks/d16-devastor2.1.0.rb
Casks/d16-devastor2.0.1.rb
Casks/d16-devastor2.0.0.rb
Casks/d16-devastor1.4.0.rb
Casks/d16-devastor1.3.1.rb
Casks/d16-devastor1.3.0.rb
Casks/d16-devastor1.2.0.rb
Casks/d16-devastor1.0.0.rb
Casks/d16-sigmund.rb
Casks/d16-sigmund1.1.2.rb
Casks/d16-sigmund1.1.1.rb
Casks/d16-sigmund1.1.0.rb
Casks/d16-sigmund1.0.0.rb
```

Apart from that still being kind of a mess, would that at least help a bit in terms of unifying those “3 ways to install?”

**Comment by joshka** [comment]
The mess is avoidable. I proposed a while back that we use folders for related casks (editions / language versions / versions) instead of all in one folder.

**Comment by claui** [comment]
My point was whether the Git history is really needed in this case.

**Comment by joshka** [comment]
@claui
The git history was my laziness rather than a necessary part of the import. There was a download folder (http://d16.pl/pub/install/). It was easier to just include all and not worry about a dedupe on the import script.

I only own 2 of the D16 plugins, but my goal is to make this useful enough that it becomes the right way to install audio plugins. At times electronic musicians can be just as fussy as developers when it comes to wanting specific versions of software. This comes from a history of being burnt by upgrades by Apple, App makers, and plugin makers where the upgrades have prevented them finishing a track, using a piece of hardware to write music, or playing to an audience.

@MikeMcQuaid 
Yep, I know this wouldn't allow fixing the cask. In this case I went for the approach that was a compromise rather than a perfect match. If this became a problem there would be ways to get to a working version.

The plugin problem is just a specific example that I can think of off the top of my head. I'm not sure that it helps to go too deep on the singular example rather than broad to gather many use cases on this. With a single example, the solution tends to be overfitted to the problem. There's sure to be more examples that others have other than this.

**Comment by joshka** [comment]
Yep. I don’t disagree. And in fact there’s a perfect example of that problem for the D16 plugins. Earlier versions of the installers used a subtlety different package name and hence the uninstall stanza in the casks for those versions doesn’t correctly uninstall the package. I ‘fixed’ it by including the old package name in the current cask and acknowledge I’d deal with the downside of that if necessary.

From a versioning perspective, I see the following scenarios / use cases so far:
1. A user can install the current version of a cask and receive updates to that and new versions. E.g `brew cask install ableton-live`
2. A user can install a major version of a cask and receive updates only to that soecific major version. E.g. `brew cask install ableton-live@9`.
3. A current version can become a new old version easily. E.g `brew cask new-version ableton-live@9`
3. A developer can create a fix version cask of a specific point version to address issues such as cleanup of leftover files `brew cask new-version ableton-live@9.7.1`
4. The number of casks is large and storing this in the main repository Cask folder as a file per cask would be annoying. Use a folder / repo / change the cask DSL to support multiple versions in the one file.
5. Consistency with formula naming should be considered. Use @version if we can.
6. There may be side by side installation considerations - apps sometime tend towards being of contained and hence able to be installed with multiple versions (ableton-live 9/10 is the example, so is java).

**Comment by MikeMcQuaid** [comment]
> change the cask DSL to support multiple versions in the one file.

I think this makes things unnecessary complication (as well as increasing pressure on Homebrew or Cask maintainers to maintain these in the main taps).

**Comment by commitay** [comment]
> > The number of casks is large and storing this in the main repository Cask folder as a file per cask would be annoying. Use a folder / repo / change the cask DSL to support multiple versions in the one file.

> I think this makes things unnecessary complication (as well as increasing pressure on Homebrew or Cask maintainers to maintain these in the main taps).

Strongly agree with this.

**Comment by joshka** [comment]
> I think this makes things unnecessary complication (as well as increasing pressure on Homebrew or Cask maintainers to maintain these in the main taps).
I agree - I'm pointing this out as an approach worth excluding, not the *right solution*

**Comment by claui** [comment]
Speaking about making it easier for both users and maintainers, I see some potential in what @MikeMcQuaid [suggested above](https://github.com/Homebrew/homebrew-cask/issues/47950#issuecomment-394148791), and would advocate for a new subcommand that does exactly that.

A fitting name for this might be:

```
$ brew cask customize some-synth
```

or, even easier to remember:

```
$ brew cask tweak some-synth
```

Another benefit of such a subcommand would be that we could advertise it as another mandatory step in our issue templates:

- [x] I have looked into `brew cask tweak` and determined that I still wish to open an issue nonetheless.
