### ISSUE TITLE
brew cask upgrade does not seem to work

### ISSUE THREAD

**Issue by elgs** [Homebrew/homebrew-cask#48002]
```
~$ brew cask --version
Homebrew-Cask 1.6.6
Homebrew/homebrew-cask (git revision 1c78e; last commit 2018-06-01)
~$ 
~$ brew update
Already up-to-date.
~$ 
~$ brew cask outdated
~$ 
~$ brew cask info google-chrome
google-chrome: 67.0.3396.62
https://www.google.com/chrome/
/usr/local/Caskroom/google-chrome/66.0.3359.181 (2 files, 77.5KB)
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/google-chrome.rb
==> Name
Google Chrome
==> Artifacts
Google Chrome.app (App)
```

Above is the output when I was trying to upgrade `google-chrome`. It looks like I have Chrome version 66, but the server already has version 67. However, I was not able to upgrade it with `brew cask upgrade`. I'm wondering whether I have done anything wrong.

**Comment by commitay** [comment]
https://github.com/Homebrew/homebrew-cask/blob/master/USAGE.md#updatingupgrading-casks

> Many applications update themselves, so their Casks are ignored by `brew cask outdated` and `brew cask upgrade`. This behaviour can be overridden by adding `--greedy` to the command.

**Comment by elgs** [comment]
Thank you so much. It works. Who wants to upgrade each application if it could be done with a single command. `--greedy` should be the default.

**Comment by commitay** [comment]
> `--greedy` should be the default.

`man brew-cask`
> If −−greedy is given then also upgrade the Casks having auto_updates true or version :latest.

The reason it isn't the default is `brew cask upgrade --greedy` will upgrade everything with latest and `auto_updates` regardless of if it needs upgraded.

**Comment by elgs** [comment]
I'm surprised! That's not a problem if I have only a few cask package installed. It would be a problem if I have a dozen or two. 

Why cannot brew cask smart enough to upgrade ONLY those outdated?

**Comment by commitay** [comment]
We don't have a reliable way (that can be used for all casks) to find if an cask has already upgraded itself which is why we use `auto updates true` and exclude them from `upgrade`.

**Comment by elgs** [comment]
I'm confused now. Based on my understand about what you said. If I run `brew cask upgrade --greedy` a second time after the success of the first time, it should upgrade everything all over again. But I just tried and the second time didn't do anything. Did I understand something wrong? Thanks.

**Comment by elgs** [comment]
@commitay I think brew cask should not care about the situation applications upgrading themselves. If someone need applications to upgrade themselves, they should not install them with brew cask in the first place at all.

I think `brew cask upgrade` should just upgrade anything that are outdated, nothing more, nothing less.

**Comment by commitay** [comment]
`upgrade` behaviour was discussed extensively before it was implemented.

**Comment by elgs** [comment]
`--greedy` is causing `dropbox` to be installed every time. `brew cask upgrade` without `--greedy` won't upgrade Chrome or Firefox. It looks like there's no way for `brew cask` to upgrade Chrome and Firefox but leave Dropbox alone given only Chrome and Firefox are outdated in my computer.

**Comment by elgs** [comment]
> We don't have a reliable way (that can be used for all casks) to find if an cask has already upgraded itself which is why we use auto updates true and exclude them from upgrade.

I know it's too late to talk about the design now. But why not keep a local copy of the version info for each installed cask package. When running `brew cask upgrade`, it compare the local versions against the server versions and decided which packages need to be upgraded?

**Comment by elgs** [comment]
Aha! I think the real evil one is the `latest`!! `--greedy` to disregard `auto update true` is a good idea. `latest` should not be allowed at all. Now I fully understand how it works.

**Comment by elgs** [comment]
Can you please make `--greedy` to ignore `latest`? I think the package owners who mark their packages as `latest` probably don't want to upgrade their packages anymore. Thus `--greedy` will be really useful. To me, marking package version as `latest` is just insane.

**Comment by commitay** [comment]
> I think the package owners who mark their packages as `latest` probably don't want to upgrade their packages anymore.

This isn't what `:latest` means. 

> [all_stanzas.md](https://github.com/Homebrew/homebrew-cask/blob/0ddcd8fa6f264bf753e66efad7f737ac7cbc8fba/doc/cask_language_reference/all_stanzas.md#required-stanzas)
> `version`: give value of `:latest` if versioned downloads are not offered

**Comment by elgs** [comment]
Thanks for the explanation. That makes sense though I think it's a bad idea for unversioned packaged to be maintained in a package manager.

Would it be possible to make the semantics of `--greedy` to be more specific, like `--force-latest`, and `--force-auto-update`? This way, I would be able to use only `--force-auto-update` to upgrade all packages but not being bothered by those `latest` packages.

**Comment by vitorgalvao** [comment]
> If someone needs applications to upgrade themselves, they should not install them with brew cask in the first place.

This is an absurd statement.

We’ve existed for years. You’re making blanket statements as if they applied to everyone, when they apply _to you_.

> I think it's a bad idea for unversioned packages to be maintained in a package manager.

You’re welcome to contact the developers of casks that use `latest` and ask them to always provide versioned download links and/or public appcasts of their releases. We’d all appreciate that.

> Would it be possible to make the semantics of `--greedy` to be more specific, like `--force-latest`, and `--force-auto-update`?

No. Every single one of your questions was already answered elsewhere, and as @commitay explained before, `upgrade` behaviour was extensively discussed. If you want to expand on that discussion, I ask that you search for (it’s in this repo) and read the original first. Otherwise it’s a waste of time.

I also ask you stop making posts nervously one after another. This isn’t a chat app and it makes your questions harder to follow.

**Comment by vitorgalvao** [comment]
> I think it's a bad idea for unversioned packages to be maintained in a package manager.

You’re welcome to contact the developers of casks that use `latest` and ask them to always provide versioned download links and/or public appcasts of their releases. We’d all appreciate that.

> If someone needs applications to upgrade themselves, they should not install them with brew cask in the first place.

This is an absurd statement.

We’ve existed for years. You’re making blanket statements as if they applied to everyone, when they apply _to you_.

> Would it be possible to make the semantics of `--greedy` to be more specific, like `--force-latest`, and `--force-auto-update`?

No. Every single one of your questions was already answered elsewhere, and as @commitay explained before, `upgrade` behaviour was extensively discussed. If you want to expand on that discussion, I ask that you search for (it’s in this repo) and read the original first. Otherwise it’s a waste of time.

I also ask you stop making posts nervously one after another. This isn’t a chat app and it makes your questions harder to follow.

**Comment by elgs** [comment]
> You’re welcome to contact the developers of casks that use latest and ask them to always provide versioned download links and/or public appcasts of their releases. We’d all appreciate that.

Does your appreciating that mean you all also don't like the `latest`? Just saying, this is not the point. Your statement is absurd because you have to understand brew cask allowed the `latest` in the first place. I'm not blaming the package owners marking their package version as `latest`. What I was saying is allowing `latest` as version is a bad idea. I don't want to further argue about it. It sounds like a legacy design feature/bug. We just accept the existence of it.

> No. Every single one of your questions was already answered elsewhere, and as @commitay explained before, upgrade behaviour was extensively discussed. If you want to expand on that discussion, I ask that you search for (it’s in this repo) and read the original first. Otherwise it’s a waste of time.

Good arrogant tone! I like it!

> I also ask you stop making posts nervously one after another. This isn’t a chat app and it makes your questions harder to follow.

If you don't like what I'm saying, you can ignore it. If you don't like me, kick me out of your project. It's really up to you.
