### ISSUE TITLE
handshaker cask (TLS/SSL issues)

### ISSUE THREAD

**Issue by brianmorton** [Homebrew/homebrew-cask#48065]
The main website for this cask ( https://www.smartisan.com/apps/ ) loads ok, although it is marked as insecure because it mixes secure and insecure content.

The download link ( https://sf.smartisan.com/sf/release/download ) provides a different experience when you click on it, due to the deprecated/legacy cert authorities (to put it nicely).

![image](https://user-images.githubusercontent.com/1434096/40929240-054d8caa-67d9-11e8-9ba5-98e221a9b47e.png)

It has been like this for a while (~ 1 month), but I have been holding off on doing anything about it hoping they would just get a new cert.

Since this doesn't seem to be the case, should we remove the cask? Or are we ok trusting this cert?

**Comment by vitorgalvao** [comment]
The download URL in the cask is `http`, not `https`, so it downloads fine. I think we have an issue somewhere about `--require-sha` but for `https`.
