### ISSUE TITLE
`cask-repair` command

### ISSUE THREAD

**Issue by commitay** [Homebrew/homebrew-cask#48086]
A ruby version of `cask-repair` implemented as command has been mentioned a couple of times, opened this to discuss and see if its something we might want to do.

Benefits of the command approach:
- Always up to date.
- Could use `brew` [GitHub API utils](https://github.com/Homebrew/brew/blob/b088302e11c62fb5dff0a5c69815d94a46da97da/Library/Homebrew/utils/github.rb#L258-L270) rather than the `hub` formula.

Possible features that would (probably) be easier to implement in ruby:
- Checking for duplicate PRs.
- Support updates for language casks (`firefox`, etc.)

Couple of things that would need to be discussed:
- Where it would live. Adding it to the `brew` repo may not be the best option, another tap (similar to the `bundle` and `services` commands) or the `homebrew-cask` repo may work better.
- Whether it would be a `brew` command (e.g. `brew cask-repair`) or a `brew cask` command (e.g. `brew cask repair`)

**Comment by brianmorton** [comment]
I would be a fan of integrating it.

FWIW, my duplicate PR logic, while rudimentary by some standards, has worked well for me:
• search open PRs for cask name
• not found -> clear to submit PR
• found -> grep version strict match (if exact match found, flag as duplicate PR else clear to submit)

**Comment by commitay** [comment]
> we can’t just check the PR/branch name and be sure they’re duplicates. There are a few ways we could go about it (checking first for name and on conflict download and check for content)

The bump formula command with the GitHub API utils check the PR name/version and warns if there is a PR with the same already open but gives the option of submitting it anyway with `--force`. I think something similar would be sufficient as we only need it for duplicate version bumps and if the change is unrelated to the open PR it can be submitted anyway.

> I don’t think duplicate PRs are a big enough problem.

Yeah, it isn't really a problem, would mostly be so we don't have to close them manually. Might also be useful if we ever get a bot for submitting version bumps so it doesn't keep submitting the same PRs.

**Comment by MikeMcQuaid** [comment]
> A ruby version of cask-repair implemented as command

How is it currently implemented?

**Comment by vitorgalvao** [comment]
> https://github.com/vitorgalvao/tiny-scripts/blob/master/cask-repair

Compare that monstrosity to [the original, four years ago](https://github.com/vitorgalvao/tiny-scripts/commit/bf645e03edc2a432c27a2165c7ce18693d339b8f#diff-4a8d6dd423163721b17011afb643d0b7). Less than five times the size (and did so little). Not sure I should be proud or surprised it still manages to hold itself together and work effectively.

**Comment by MikeMcQuaid** [comment]
A command sounds better. I wonder what makes `brew cask-repair` worse than `brew cask repair`?

**Comment by reitermarkus** [comment]
> I wonder what makes `brew cask-repair` worse than `brew cask repair`?

The hyphen. All other commands are sub-commands of `brew cask`, so why should `repair` be an exception?

**Comment by MikeMcQuaid** [comment]
> All other commands are sub-commands of brew cask, so why should repair be an exception?

Adding (and fixing, currently) support for `brew cask` subcommands in the `PATH` adds additional complexity assuming the implementation doesn't differ otherwise.

Furthermore, `brew cask` is itself a subcommand of Homebrew so it feels strange to have additional custom subcommands of that with their own command naming scheme just to avoid a `-`.

**Comment by reitermarkus** [comment]
> Adding (and fixing, currently) support for `brew cask` subcommands in the `PATH` adds additional complexity assuming the implementation doesn't differ otherwise.

Implementing a cask-specific command as a `brew` sub-command adds far more complexity than having first-class support for `brew cask` sub-commands.

**Comment by core-code** [comment]
sorry to just chime in. just wanted to mention, from a user-perspective the single thing i would want changed about cask-repair (or a hypothetical "brew cask repair") is the ability to run multiple instances concurrently (which currently results in damaged merge requests). if you are updating 20 casks having to do it in a serial way slows things down considerably, especially with long downloads.

**Comment by brianmorton** [comment]
@core-code I am with you on that - a bit off topic for sure - but I have brought it up [previously](https://github.com/vitorgalvao/tiny-scripts/issues/133).

**Comment by reitermarkus** [comment]
@brianmorton, no, there hasn't been any progress on this.

**Comment by vitorgalvao** [comment]
I’m fine with letting this close. If this is ever going to be worked on (I’d say about now the chances are a bit over 50%) I’ll probably be the one to do it. And don’t worry, I won’t forget about this without an open issue, I’ve been considering it for longer than this has been open.

**Comment by brianmorton** [comment]
@vitorgalvao I also have an open issue (I believe) for my cask-automation project to port cask-repair into python, or port cask-automation into ruby so that I could integrate cask-repair functionality as it would be helpful when doing automated cask updates.
