### ISSUE TITLE
brew cask should support apaches dynamic mirror selection for package downloads

### ISSUE THREAD

**Issue by mvitz** [Homebrew/homebrew-cask#48204]
#### General troubleshooting steps

- [X] I have retried my command with `--force` and the issue is still present.
- [X] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs).
  - [X] None of the templates was appropriate for my issue, or I’m not sure.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

When installing `apache-directory-studio` it uses the US specific URI `http://www.us.apache.org/dist/directory/studio/#{version}/ApacheDirectoryStudio-#{version}-macosx.cocoa.x86_64.dmg`.

However this is not a good idea because some users may reside in europe and the download is very slow.

Besides that apache requires that all downloads should use the dynamic mirror chooser by using https://www.apache.org/dyn/closer.cgi but this requires logic on `brew cask`s side.

In `brew core` there is a special `CurlApacheMirrorDownloadStrategy` (see https://github.com/Homebrew/brew/blob/9fa79d20564aa24550c3cfa118f2aa6c28de3766/Library/Homebrew/download_strategy.rb#L412-L435) which `brew cask` should support as well.

**Comment by commitay** [comment]
Merging the separate brew and cask download strategies and removing duplicated code is something that is planned so when that happens we could likely support this but until that happens this isn't something we would want to add support for as it would only benefit one cask.

**Comment by commitay** [comment]
https://github.com/Homebrew/homebrew-cask/pull/51681
