### ISSUE TITLE
audit: new flags

### ISSUE THREAD

**Issue by commitay** [Homebrew/homebrew-cask#48267]
I've been thinking about trying to add or re-add some "online" checks to audit. One problem with running these checks as part of the default audit is that they are _slow_. This was an issue with the HTTPS check when it was briefly added, it made almost impossible to run audit over the whole repo.

I propose adding new flags (similar to the current formula audit) to allow for us to run these checks only when they are needed.

- `audit` = current audit checks
- `audit --online` = `audit` + checks that require network connectivity
  - `url`, `homepage` and `appcast` reachable and HTTP/HTTPS check
- `audit --download` = `audit --online` + checksum verification
  - check `url` and `sha256` for non-CI `MacOS.version`
- `audit --new` = `audit --online` + new cask checks
  - Current formula name conflict check
  - GitHub notability audit

This would allow us to run `audit` on the entire repo, use `audit --online` in scripts to check for dead URLs and `audit --download` would remain as the standard check on CI. New casks would run `audit --new --download`.

**Comment by vitorgalvao** [comment]
I’d rather `audit` (no flags) did the most work, with flags doing fewer. The rationale for that being simplicity for contributors. Instead of fighting with getting them to use the right flags, it’s easier to have them use no flags.

**Comment by commitay** [comment]
FWIW, I agree with trying to simplify these checks for contributors but I think changing the flags so that they are the opposite of how `audit` works for formulae and the current cask `audit` might not be an improvement and could cause some confusion as both `audit`s without flags only have offline checks similar to `style`.

**Comment by commitay** [comment]
Kind of related as this issue is basically an audit revamp: would it be practical to verify `url`s and `sha256`s for all macOS releases as part of `audit --download`, similar to how we check all language stanzas?

**Comment by vitorgalvao** [comment]
Agreed that consistency should take precedence. I also agree with checking all macOS releases. We have an environmental variable to fake macOS releases already, so this shouldn’t be a big burden to implement.
