### ISSUE TITLE
Need to remove 'brew cask update' or link to 'brew update'

### ISSUE THREAD

**Issue by FinalPhase** [Homebrew/homebrew-cask#48271]
Hi there,
Getting an error when running brew cask update, we might want to remove this option (making sure brew update also has this functionality already) or to link it to 'brew update' instead.

➜  ~ git:(master) ✗ brew cask update
Error: Calling `brew cask update` is disabled!
Use `brew update` instead.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
Or, even better, submit a PR to fix it!
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/utils.rb:113:in `odeprecated'
/usr/local/Homebrew/Library/Homebrew/utils.rb:121:in `odisabled'
/usr/local/Homebrew/Library/Homebrew/compat/hbc/cli/update.rb:8:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'

Thanks,
Idan

**Comment by commitay** [comment]
This is the expected behaviour, `brew cask update` has been deprecated and replaced by `brew update`.
