### ISSUE TITLE
Lastpass cask doesn't install lastpass app, but browser extension installer

### ISSUE THREAD

**Issue by SimJoSt** [Homebrew/homebrew-cask#48300]
When installing the lastpass cask, only the browser extension installer is downloaded/"installed". It's not the regular lastpass app, which would be put into the applications folder, which you can currently only get from the app store, you would expect.

I propose either adding the "real" lastpass app or switching it for the current app or making the name of the current app more descriptive and clear.

**Comment by vitorgalvao** [comment]
>  which you can currently only get from the app store

> I propose either adding the "real" lastpass app

Those things are incompatible. If it’s *only* available in the MAS, then we can’t add it here.

The current cask is named according to the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md), which is important to avoid duplicates. I’d be fine with removing the cask, though. [I have no strong feelings one way or the other](https://youtu.be/CxK_nA2iVXw).

**Comment by islanderman** [comment]
I agree with @SimJoSt's comment above.  This cask does not install the app as the expected behavior. When using lastpass as their Chrome plugin, most likely it's sync'ed with Google automatically.

**Comment by vitorgalvao** [comment]
Are you both fine with removing the cask?
