### ISSUE TITLE
Problem with install Scribus

### ISSUE THREAD

**Issue by Andreacouvert** [Homebrew/homebrew-cask#48324]
I tray to install Scribus and I have the below problem, please could some one help me? Thanks   
https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/utils.rb:113:in `odeprecated'
/usr/local/Homebrew/Library/Homebrew/utils.rb:121:in `odisabled'
/usr/local/Homebrew/Library/Homebrew/compat/hbc/cli/update.rb:8:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:94:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:128:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
Andreas-MacBook-Pro:~ andreacouvert$ brew update Scribus
Error: This command updates brew itself, and does not take formula names.
Use 'brew upgrade Scribus' instead.
Andreas-MacBook-Pro:~ andreacouvert$ brew upgrade Scribus
Error: No available formula with the name "scribus" 
Andreas-MacBook-Pro:~ andreacouvert$

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
