### ISSUE TITLE
Revive betterzipql

### ISSUE THREAD

**Issue by windware** [Homebrew/homebrew-cask#48467]
In this pull request, betterzipql has been removed as the feature has been integrated into its own standalone app but it still serves the purpose to have it just as a QuickLook plugin instead of installing an app to get the feature.

https://github.com/Homebrew/homebrew-cask/pull/41954

Download
https://macitbetter.com/downloads/

It says, it's a legacy version but confirmed it's working under macOS 10.13.5.

**Comment by vitorgalvao** [comment]
It’s a little missed cask, that being legacy will eventually stop to work and no one will notice. We prefer to keep those to a minimum.

If you want it as a cask, your best bet is making your own tap.
