### ISSUE TITLE
brew cask cleanup --dry-run

### ISSUE THREAD

**Issue by brianmorton** [Homebrew/homebrew-cask#48463]
`brew cleanup` has a `--dry-run` flag, `brew cask cleanup` does not.

is it possible to implement this or achieve this functionality another way?

**Comment by vitorgalvao** [comment]
We’re aiming for feature-parity with commands, so this is something we should implement. It’s low priority, though, so it’s more likely to happen with an external PR.

**Comment by brianmorton** [comment]
I'll see if I have some time to look into this.

**Comment by commitay** [comment]
Merging `brew cask cleanup` and `brew cleanup` is something @reitermarkus is going to be working on.

 https://github.com/Homebrew/homebrew-cask/issues/41990#issuecomment-389016701

**Comment by vitorgalvao** [comment]
Forgot about that. Only remembered `search`. Closing, then.
