### ISSUE TITLE
Move /doc contents to Homebrew/brew/docs

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/homebrew-cask#48659]
### Description of feature/enhancement

Move the contents of the `/doc` folder in this repository to https://github.com/Homebrew/brew/tree/master/docs.

### Justification

- Make Homebrew Cask documentation more discoverable to Homebrew users. 
- Get Homebrew Cask documentation included in https://docs.brew.sh
- Keep Homebrew Cask documentation with the core code rather than the casks code

**Comment by reitermarkus** [comment]
@wagnercolodette, feel free to start working on this.

**Comment by MikeMcQuaid** [comment]
@wagnercolodette Yes, that'd be great 👍

**Comment by jvanderen1** [comment]
Hello! While there are links that need to be updated and the README in https://github.com/Homebrew/brew/tree/master/docs, would it be just as simple as cutting the contents from `homebrew-cask/doc/` to a folder called `brew/docs/cask/`?

**Comment by MikeMcQuaid** [comment]
@jvanderen1 I think also all documents should be in a flat structure i.e. in the root of 
https://github.com/Homebrew/brew/tree/master/docs rather than subdirectories named `cask` or `development`

**Comment by EricFromCanada** [comment]
I'm on this, stalebot.
