### ISSUE TITLE
SHA256 error while installing Google Chrome

### ISSUE THREAD

**Issue by stefaniuk** [Homebrew/homebrew-cask#48940]
#### General troubleshooting steps

Install Google Chrome via `brew cask install` command.

#### Description of issue

Hash of the file doesn't match.

#### Command that failed

```
brew cask install google-chrome
```

#### Output of command

```
dast7 at macOS-246851 in ~ $ brew cask install google-chrome
==> Satisfying dependencies
==> Downloading https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
Already downloaded: /Users/dast7/Library/Caches/Homebrew/Cask/google-chrome--67.0.3396.87.dmg
==> Verifying checksum for Cask google-chrome
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'google-chrome' does not match.

Expected: c5e017f928aca26aa03c184e816af161ec72eaf8890b7ec4e58bd9b78d587ab6
Actual:   1804266f4c2777b983d450a3950e3a91e0b30a9d69a069b36b0ac97bbeacc2bc
File:     /Users/dast7/Library/Caches/Homebrew/Cask/google-chrome--67.0.3396.87.dmg

To retry an incomplete download, remove the file above.
```

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/48942
