### ISSUE TITLE
Broken caveats on cask break brew search and more stuff

### ISSUE THREAD

**Issue by stek29** [Homebrew/homebrew-cask#49049]
I have a small brew tap dedicated to iOS/macOS related tools at https://github.com/stek29/homebrew-idevice.

A cask in that tap (supraudit) has caveats which print LICENSE file from staged path:
https://github.com/stek29/homebrew-idevice/blob/6f89f0f4ba0093bdb583b39423d1c999dd99fdc3/Casks/supraudit.rb#L12-L21

I can see that file is still there when I download the tar manually:
```
❯ curl http://newosxbook.com/tools/supraudit.tar | tar -t
tmp/
tmp/LICENSE
tmp/CREDITS
tmp/praudit.c
usr/
usr/local/
usr/share/
usr/share/man/
usr/share/man/manj/
usr/share/man/manj/supraudit.j
usr/local/bin/
```

But that's not the main issue.

If you try to install that cask, installation would fail with `No such file or directory @ rb_sysopen - /usr/local/Caskroom/supraudit/latest/tmp/LICENSE` error.

And afaiu there's no way to fix that error without manually creating that file.

And it's not possible to uninstall that cask, `brew search` gets broken too, so is `brew cask info` and many more.

I will try to fix that issue on my side, however, I don't think that it's normal that broken caveats in one cask lead to it being stuck in semi-installed state while breaking not only cask, but brew as a whole.

It was originally reported at stek29/homebrew-idevice#2.

**Comment by stek29** [comment]
From what I understand, it has happened because `caveats` are now processed before installation, and `license` is the way to go now.

So, I have changed cask code to use `license` method with `file://` path, but imo there should be a better way to notify user about license which is only available in the archive with binaries themselves.

**Comment by stek29** [comment]
Also, you've probably want to do a git checkout in tap if you want to reproduce the issue.

**Comment by vitorgalvao** [comment]
Thank you for the report, but I see this as an issue with your cask, not HBC.

I’ll leave this open for a while in case another maintainer wants to take a look, but if none do, this’ll just be closed.

**Comment by stek29** [comment]
@vitorgalvao I agree that it's an issue with my cask, but I don't think that one cask should be able to break `brew search` completely.

I have fixed the issue with my cask already, but if you think that it's not HBC issue -- I'm ok with that too.

**Comment by vitorgalvao** [comment]
In what way does `search` break?

**Comment by stek29** [comment]
@victorpopkov it keeps loading, but then `No such file or directory` gets printed, and no results are shown (not even from brew itself)

**Comment by vitorgalvao** [comment]
Pinging @reitermarkus.

**Comment by reitermarkus** [comment]
I'd say this is a `wontfix`, because anything other than the official methods is unsupported, especially a cask's specification depending on something which is not created until after the installation.
