### ISSUE TITLE
cask-repair fails for eclipse-jee

### ISSUE THREAD

**Issue by joe776** [Homebrew/homebrew-cask#49048]
I tried to update the eclipse-jee cask to 4.8 Photon. From what I got form the existing formula, the correct way to specify the version should be `4.8.0,photon:R`. However, cask-repair simply ignores this provided version and downloads the old 4.7.3a, no matter if entered in the prompt or via `cask-repair -v "4.8.0,photon:R" eclipse-jee`. Editing the formula manually worked as expected.

**Comment by vitorgalvao** [comment]
`cask-repair` bug reports belong in https://github.com/vitorgalvao/tiny-scripts.

Can’t reproduce this at all. Please check if you’re on the latest `cask-repair` version.
