### ISSUE TITLE
wowza-streaming-engine

### ISSUE THREAD

**Issue by brianmorton** [Homebrew/homebrew-cask#49081]
Appcast has an update to `4.7.5.02` (currently `4.7.5`), however attempting to download it is challenging. You need a free account to access the downloads section, however after registering this is what I get:
![image](https://user-images.githubusercontent.com/1434096/42048672-c7df130a-7ab8-11e8-90ff-856e3f8c385b.png)

Seems to me this cask should maybe be removed as it shouldn't be downloaded without a valid license?

**Comment by brianmorton** [comment]
![giphy](https://user-images.githubusercontent.com/1434096/42394851-71f2307c-8110-11e8-8d8e-308f11325696.gif)

**Comment by vitorgalvao** [comment]
But do they not verify the license after it’s downloaded? That’d be a bit weird. If that’s the case, we should indeed remove the cask (do you know? If not, we should ping whoever submitted it).

But if it doesn’t work without a license even after downloading it, it should be fine to keep.

**Comment by brianmorton** [comment]
I do not know. I tried installing it, but the dmg just extracts a .app for the installer which IMMEDIATELY asks for sudo so I am unwilling to continue.
![image](https://user-images.githubusercontent.com/1434096/42403612-474f59f4-8137-11e8-859d-4333529458cc.png)

@mandrean initially introduced the cask.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/49937
