### ISSUE TITLE
Allow pinning casks

### ISSUE THREAD

**Issue by boobaa** [Homebrew/homebrew-cask#49127]
### Description of feature/enhancement

Just like `brew pin anyformula` prevents upgrading `anyformula`, `brew cask pin anycask` should prevent upgrading `anycask`.

### Justification

Somebody might want casks that don't auto-upgrade themselves not to be upgraded at all.

### Example use case

Some days ago I ran `brew update; brew update; brew cask update` and I was happy that `lilypond` has been upgraded after a long period of time. Today I had to realize this new version doesn't work with `frescobaldi`, so I had to `brew cask uninstall lilypond; brew cask install https://raw.githubusercontent.com/Homebrew/homebrew-cask/645dbb8228ec2f1f217ed1431e188687aac13ca5/Casks/lilypond.rb` to get back a working environment.

(I must admit this might be filed as a bug report stating that current version of `frescobaldi` doesn't work with current version of `lilypond`, but I couldn't find the reason.)

**Comment by vitorgalvao** [comment]
A huge chunk of casks auto-update and we can’t stop that. So `pin` would at best be inconsistent and not work in a lot of cases.

If you do a search you’ll see we’ve discussed this in the past, especially in the `upgrade` issues on `brew`’s repository.
