### ISSUE TITLE
 Checksum for Cask 'rar' does not match.

### ISSUE THREAD

**Issue by smancill** [Homebrew/homebrew-cask#49128]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

The sha256 from the latest rar tarball (5.6.0) is different to the sha256 in the formula.

#### Command that failed

```
$ brew cask upgrade rar
==> Upgrading 1 outdated package, with result:
rar 5.6.0
==> Caveats
Instructions on using rar and unrar are available in

  /usr/local/Caskroom/rar/5.6.0/rar/rar.txt

==> Satisfying dependencies
==> Downloading https://www.rarlab.com/rar/rarosx-5.6.0.tar.gz
######################################################################## 100.0%
==> Verifying checksum for Cask rar
==> Note: running "brew update" may fix sha256 checksum errors
==> Purging files for version 5.6.0 of Cask rar
Error: Checksum for Cask 'rar' does not match.

Expected: 381eb0c0645bfbd603e7e20a6a8cb34e484c6eeca161a1b3017cf93415448fde
Actual:   381ca05ca2701cf72148da49d36a4dda4e8e29cd0c3879f697b2861326277d5d
File:     /Users/smancill/Library/Caches/Homebrew/Cask/rar--5.6.0.tar.gz

To retry an incomplete download, remove the file above.
```

I checked downloading the file manually:

```
$ wget https://www.rarlab.com/rar/rarosx-5.6.0.tar.gz
--2018-06-29 16:22:03--  https://www.rarlab.com/rar/rarosx-5.6.0.tar.gz
Resolving www.rarlab.com (www.rarlab.com)... 5.135.104.98
Connecting to www.rarlab.com (www.rarlab.com)|5.135.104.98|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 579479 (566K) [application/x-gzip]
Saving to: ‘rarosx-5.6.0.tar.gz’

rarosx-5.6.0.tar.gz                                100%[==========================================>] 565.90K   116KB/s    in 4.9s

2018-06-29 16:22:09 (116 KB/s) - ‘rarosx-5.6.0.tar.gz’ saved [579479/579479]

$ gsha256sum rarosx-5.6.0.tar.gz
381ca05ca2701cf72148da49d36a4dda4e8e29cd0c3879f697b2861326277d5d  rarosx-5.6.0.tar.gz
```

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask#reporting-bugs

https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error
