### ISSUE TITLE
brew cask install <cask> requires password

### ISSUE THREAD

**Issue by zioval** [Homebrew/homebrew-cask#49159]
Hi,
I'd like to know why sometimes the command brew cask install <cask> requires a password.
I do understand that the installer itself may require a password but why if i try to install/uninstall the cask and install it back within 5 minutes or so, no password is required at the second installation..
And if i wait more than 5 minutes to reinstall it, the password will be asked again. I can see some caching mechanism in place. How does this cache work?
Is there a way to avoid the insertion of the password at all?

You can find the steps I followed below:

************ update-reset *********
LTTO0051:~ andrea.valenti$ brew update-reset .     
==> Fetching /usr/local/Homebrew...
remote: Counting objects: 181, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 181 (delta 141), reused 141 (delta 141), pack-reused 34
Receiving objects: 100% (181/181), 70.53 KiB | 5.42 MiB/s, done.
Resolving deltas: 100% (142/142), completed with 83 local objects.
From https://github.com/Homebrew/brew
   0d33aba0b..61a8c4d1f  master                                                  -> origin/master
 * [new branch]          dependabot/bundler/Library/Homebrew/test/rubocop-0.57.2 -> origin/dependabot/bundler/Library/Homebrew/test/rubocop-0.57.2

==> Resetting /usr/local/Homebrew...
Branch 'master' set up to track remote branch 'master' from 'origin'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.

==> Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask...
remote: Counting objects: 173, done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 173 (delta 128), reused 164 (delta 119), pack-reused 0
Receiving objects: 100% (173/173), 22.13 KiB | 5.53 MiB/s, done.
Resolving deltas: 100% (128/128), completed with 45 local objects.
From https://github.com/Homebrew/homebrew-cask
   8563bcb0a..d021d69b4  master     -> origin/master

==> Resetting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask...
Branch 'master' set up to track remote branch 'master' from 'origin'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.

==> Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
remote: Counting objects: 998, done.
remote: Compressing objects: 100% (288/288), done.
remote: Total 998 (delta 744), reused 962 (delta 708), pack-reused 0
Receiving objects: 100% (998/998), 145.15 KiB | 1.16 MiB/s, done.
Resolving deltas: 100% (744/744), completed with 125 local objects.
From https://github.com/Homebrew/homebrew-core
   2ff9c2ca..46d6b55f  master     -> origin/master

==> Resetting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
Branch 'master' set up to track remote branch 'master' from 'origin'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.

*********brew update*******************
LTTO0051:~ andrea.valenti$ brew update .      
Already up-to-date.

********* run install command (password will be required)********************
LTTO0051:~ andrea.valenti$ brew cask install adobe-acrobat-reader 
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
castxml

==> Satisfying dependencies
==> Downloading http://ardownload.adobe.com/pub/adobe/reader/mac/AcrobatDC/1801120040/AcroRdrDC_1801120040_MUI.dmg
Already downloaded: /Users/andrea.valenti/Library/Caches/Homebrew/Cask/adobe-acrobat-reader--18.011.20040.dmg
==> Verifying checksum for Cask adobe-acrobat-reader
==> Installing Cask adobe-acrobat-reader
==> Running installer for adobe-acrobat-reader; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:   *********** PASSWORD REQUIRED ********************
installer: Package name is Adobe Acrobat Reader DC (Continuous)
installer: Installing at base path /
installer: The install was successful.
🍺  adobe-acrobat-reader was successfully installed!

********** UNINSTALL IMMEDIATELY AFTER INSTALL *******************
LTTO0051:~ andrea.valenti$ brew cask uninstall adobe-acrobat-reader
==> Uninstalling Cask adobe-acrobat-reader .  
==> Running uninstall process for adobe-acrobat-reader; your password may be necessary
==> Removing launchctl service com.adobe.ARMDC.Communicator
==> Removing launchctl service com.adobe.ARMDC.SMJobBlessHelper
==> Removing launchctl service com.adobe.ARMDCHelper.cc24aef4a1b90ed56a725c38014c95072f92651fb65e1bf9c8e43c37a23d420d
==> Quitting application ID com.adobe.Reader
==> Quitting application ID com.adobe.AdobeRdrCEFHelper
==> Quitting application ID com.adobe.AdobeRdrCEF
==> Uninstalling packages:
com.adobe.acrobat.DC.reader.app.pkg.MUI
com.adobe.acrobat.DC.reader.browser.pkg.MUI
com.adobe.acrobat.DC.reader.appsupport.pkg.MUI
com.adobe.RdrServicesUpdater
com.adobe.armdc.app.pkg
==> Removing files:
/Applications/Adobe Acrobat Reader DC.app
==> Purging files for version 18.011.20040 of Cask adobe-acrobat-reader

*****INSTALL AGAIN IMMEDIATELY AFTER UNINSTALL (no password required)*******
LTTO0051:~ andrea.valenti$ brew cask install adobe-acrobat-reader .  
==> Satisfying dependencies
==> Downloading http://ardownload.adobe.com/pub/adobe/reader/mac/AcrobatDC/1801120040/AcroRdrDC_1801120040_MUI.dmg
Already downloaded: /Users/andrea.valenti/Library/Caches/Homebrew/Cask/adobe-acrobat-reader--18.011.20040.dmg
==> Verifying checksum for Cask adobe-acrobat-reader
==> Installing Cask adobe-acrobat-reader
==> Running installer for adobe-acrobat-reader; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
installer: Package name is Adobe Acrobat Reader DC (Continuous)    ****** NO PASSWORD ASKED****
installer: Installing at base path /
installer: The install was successful.
🍺  adobe-acrobat-reader was successfully installed!

***** UNINSTALL IMMEDIATELY AFTER INSTALL *******
LTTO0051:~ andrea.valenti$ brew cask uninstall adobe-acrobat-reader . 
==> Uninstalling Cask adobe-acrobat-reader
==> Running uninstall process for adobe-acrobat-reader; your password may be necessary
==> Removing launchctl service com.adobe.ARMDC.Communicator
==> Removing launchctl service com.adobe.ARMDC.SMJobBlessHelper
==> Removing launchctl service com.adobe.ARMDCHelper.cc24aef4a1b90ed56a725c38014c95072f92651fb65e1bf9c8e43c37a23d420d
==> Quitting application ID com.adobe.Reader
==> Quitting application ID com.adobe.AdobeRdrCEFHelper
==> Quitting application ID com.adobe.AdobeRdrCEF
==> Uninstalling packages:
com.adobe.acrobat.DC.reader.app.pkg.MUI
com.adobe.acrobat.DC.reader.browser.pkg.MUI
com.adobe.acrobat.DC.reader.appsupport.pkg.MUI
com.adobe.RdrServicesUpdater
com.adobe.armdc.app.pkg
==> Removing files:
/Applications/Adobe Acrobat Reader DC.app
==> Purging files for version 18.011.20040 of Cask adobe-acrobat-reader

****** WAIT MORE THAN 5 minutes and install AGAIN (password asked again)******
LTTO0051:~ andrea.valenti$ brew cask install adobe-acrobat-reader    
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
wandio

==> Satisfying dependencies
==> Downloading http://ardownload.adobe.com/pub/adobe/reader/mac/AcrobatDC/1801120040/AcroRdrDC_1801120040_MUI.dmg
Already downloaded: /Users/andrea.valenti/Library/Caches/Homebrew/Cask/adobe-acrobat-reader--18.011.20040.dmg
==> Verifying checksum for Cask adobe-acrobat-reader
==> Installing Cask adobe-acrobat-reader
==> Running installer for adobe-acrobat-reader; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:  *******PASSWORD REQUIRED AGAIN*******

**Comment by vitorgalvao** [comment]
1. Asking for a password is done via `sudo`, so if the time between asks is too short, check your `sudo` timeout.
2. When making a bug report *fill the template, like it tells you*.
3. Use [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks). Your issue is barely understandable as it is.
