### ISSUE TITLE
have travis check for appcasts (eg. find_appcast)

### ISSUE THREAD

**Issue by brianmorton** [Homebrew/homebrew-cask#49200]
### Description of feature/enhancement

When travis runs CI, have it check the cask for an appcast.

### Justification

Frequently there is a better appcast (devmate, etc) than the one listed in the cask... however as a contrib I am not going to install every cask just to run the `find_appcast` tool so I can check. Since travis has to unpack every cask anyway, why not have travis also check to see if there is an appcast available?

### Example use case

any cask submission/addition.

**Comment by commitay** [comment]
@brianmorton This is something I've been thinking about, it would be easier to implement as part of https://github.com/Homebrew/homebrew-cask/issues/48383. Closing in favour of that issue.
