### ISSUE TITLE
Unable to use brew commands

### ISSUE THREAD

**Issue by pavangadu** [Homebrew/homebrew-cask#49217]
Unable to use brew cask list command. This issue started once I did "brew upgrade".
MHYDIT1308849:~ pavan.kumar$ brew cask list
Error: Calling <<-EOS.undent is disabled!
Use <<~EOS instead.
/usr/local/homebrew/Library/Taps/now/homebrew-devtools/Casks/java8.rb:95:in `block in load'
Please report this to the now/devtools tap!
Or, even better, submit a PR to fix it!
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/homebrew/Library/Homebrew/utils.rb:113:in `odeprecated'
/usr/local/homebrew/Library/Homebrew/utils.rb:121:in `odisabled'
/usr/local/homebrew/Library/Homebrew/compat/extend/string.rb:4:in `undent'
/usr/local/homebrew/Library/Taps/now/homebrew-devtools/Casks/java8.rb:95:in `block in load'
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:35:in `instance_eval'
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:35:in `initialize'
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:31:in `new'
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:31:in `cask'
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:67:in `cask'
/usr/local/homebrew/Library/Homebrew/compat/hbc/cask_loader.rb:15:in `cask'
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:113:in `cask'
/usr/local/homebrew/Library/Taps/now/homebrew-devtools/Casks/java8.rb:1:in `load'
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:57:in `instance_eval'
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:57:in `load'
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/caskroom.rb:32:in `block in casks'
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/caskroom.rb:28:in `map'
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/caskroom.rb:28:in `casks'
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/cli/list.rb:40:in `list_installed'
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/cli/list.rb:14:in `run'
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:31:in `run'
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:93:in `run_command'
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:162:in `run'
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:127:in `run'
/usr/local/homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/homebrew/Library/Homebrew/brew.rb:99:in `<main>'

**Comment by commitay** [comment]
> Please report this to the now/devtools tap

or you can `brew untap now/devtools`
