### ISSUE TITLE
Snagit Cast is marked as "App Translocation"

### ISSUE THREAD

**Issue by PascalMinder** [Homebrew/homebrew-cask#49283]
So I installed Snagit 2018 over the Homebrew Cast command. Now the app works fine. But I use Little Snitch as my firewall.

As soon as I start the app Little Snitch reports that Snagit runs in "App Translocation" mode. Is there a way to fix this?

**Comment by eenick** [comment]
After installing SnagIt via Homebrew, I've always had trouble using the built-in Sparkle updater inside SnagIt. Installing Snagit from the .dmg doesn't seem to have this problem. 

I wonder if the App Translocation is whats causing this too.

**Comment by reitermarkus** [comment]
What's the output of `xattr -l '/Applications/Snagit 2018.app'`?

**Comment by eenick** [comment]
Results on download from Google Chrome and manually drag and drop in applications folder are
`com.apple.quarantine: 0041;5b5f37f5;Google\x20Chrome;71B188F2-B349-4360-811F-FC73A6791B9A`

**Comment by vitorgalvao** [comment]
> Results on download from Google Chrome and manually drag and drop in applications folder

HBC doesn’t set quarantine, so what’s the output of `xattr` on the app when installed via `brew cask`?

**Comment by GitTheHellOutaHere** [comment]
I don’t know if this is related, but I’ve had nothing but problems with recent versions of SnagIt (2018.2, 2018.1.1).

All of them open sandboxed (AppTranslocation).
I’ve done COMPLETE uninstall/reinstalls many times and even when I install earlier versions that used to work, they now open 'boxed as well.

I don’t use Homebrew, mine were installed from the dmg.

I’m about ready to reinstall 4.1.9 and give up on 2018 altogether.
I’ve wasted _hours_ on this BS!

**Comment by GitTheHellOutaHere** [comment]
**Ah-ha!**

I found a [website](https://support.mokastudio.com/support/solutions/articles/6000184826-macos-sierra-10-12-app-translocation-gatekeeper-path-randomization) with a helpful Terminal tip to remove the quarantine flag.

> To solve this issue, first ensure that _your app_ has the com.apple.quarantine extended attribute. 

>In a Terminal, do the following:
sudo xattr /Applications/_app name_.app

>You should get:
com.apple.quarantine

>Now remove this attribute:
sudo xattr -r -d com.apple.quarantine /Applications/_app name_.app

>You are now ready to go.

I tried it with Snagit and it FINALLY opened normally!

sudo xattr -r -d com.apple.quarantine /Applications/Snagit\ 2018.app

**Comment by reitermarkus** [comment]
I cannot reproduce this. There is no `com.apple.quarantine` for me when installing with `brew cask`.

**Comment by GitTheHellOutaHere** [comment]
Bummer.

I wasn’t sure since I don’t use it. I was hoping it would still help.
Can’t you install using the dmg?

Is there an advantage to installing with HB?
