### ISSUE TITLE
Gimp cannot be installed (fix included)

### ISSUE THREAD

**Issue by gbeine** [Homebrew/homebrew-cask#49387]
#### General troubleshooting steps

- [X] I have retried my command with `--force` and the issue is still present.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
  - [X] None of the templates was appropriate for my issue, or I’m not sure.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

```
gbeine:~ gbeine$ brew cask reinstall gimp
==> Satisfying dependencies
==> Downloading https://download.gimp.org/pub/gimp/v2.10/osx/gimp-2.10.4-x86_64.dmg
Already downloaded: /Users/gbeine/Library/Caches/Homebrew/Cask/gimp--2.10.4.dmg
==> Verifying checksum for Cask gimp
==> Installing Cask gimp
==> Purging files for version 2.10.4 of Cask gimp
Error: It seems the App source '/opt/homebrew/Caskroom/gimp/2.10.4/GIMP-2.10.app' is not there.
```

#### Command that failed

```
brew cask reinstall gimp
```

Fix it with:

```
gbeine:homebrew-cask gbeine$ git diff
diff --git a/Casks/gimp.rb b/Casks/gimp.rb
index 43401baa1..cf3925063 100644
--- a/Casks/gimp.rb
+++ b/Casks/gimp.rb
@@ -6,10 +6,10 @@ cask 'gimp' do
   name 'GIMP'
   homepage 'https://www.gimp.org/'
 
-  app "GIMP-#{version.major_minor}.app"
+  app "Gimp-#{version.major_minor}.app"
 
   postflight do
-    set_permissions "#{appdir}/GIMP.app/Contents/MacOS/GIMP", 'a+rx'
+    set_permissions "#{appdir}/Gimp.app/Contents/MacOS/gimp", 'a+rx'
   end
 
   zap trash: [
```

#### Output of command with `--force --verbose --debug`

```
{{replace this}}
```

#### Output of `brew cask doctor`

```
{{replace this}}
```

#### Output of `brew tap`

```
{{replace this}}
```

**Comment by commitay** [comment]
Can you submit a PR for this please?

**Comment by gbeine** [comment]
Sorry, no chance at the moment.
Maybe somebody else can do this.
