### ISSUE TITLE
Use discourse.brew.sh instead of the gitter.im chatroom

### ISSUE THREAD

**Issue by commitay** [Homebrew/homebrew-cask#49446]
Personally I don't really like the public [Gitter chatroom](https://gitter.im/Homebrew/homebrew-cask), it's hard to engage in or track long discussions as they aren't threaded.

https://discourse.brew.sh/ looks like it is a much nicer way of  engaging with the community. It also already has a reasonable amount of cask related traffic even although we don't mention it in any of the cask repos.

I propose that we remove the Gitter chatroom in favour of the Brew discourse forum.

cc @Homebrew/cask @MikeMcQuaid 
___
Somewhat related, the `#homebrew-cask` IRC is mentioned in the readme and also has a repo integration, is it still in use or can it be removed?

**Comment by claui** [comment]
👍 for removing the Gitter chat in favor of discourse.brew.sh.

No strong opinion on `#homebrew-cask` but I’ve always appreciated that there is a registration-free way for any user to quickly reach maintainers in case of emergency, e. g. upstream malware or other security issues.

**Comment by commitay** [comment]
> registration-free way for any user to quickly reach maintainers

Do any maintainers monitor `#homebrew-cask`?

**Comment by claui** [comment]
> Do any maintainers monitor `#homebrew-cask`?

Good question. I tried to set up a bouncer (`zrc` IIRC) last year so I can monitor the channel but gave up half way.

**Comment by MikeMcQuaid** [comment]
> I propose that we remove the Gitter chatroom in favour of the Brew discourse forum.

This seems sensible and reasonable to me 👍 

> Somewhat related, the #homebrew-cask IRC is mentioned in the readme and also has a repo integration, is it still in use or can it be removed?

If there's not some maintainers in most of the time I'd be 👍 to removing mentions of it.

**Comment by amyspark** [comment]
> Good question. I tried to set up a bouncer (zrc IIRC) last year so I can monitor the channel but gave up half way.

You may find a [Matrix account](https://matrix.org/blog/home/) useful for this purpose. (I'm using it for my GSoC project with Blender, and it works well.)

> I propose that we remove the Gitter chatroom in favour of the Brew discourse forum.
> Somewhat related, the #homebrew-cask IRC is mentioned in the readme and also has a repo integration, is it still in use or can it be removed?

I agree with swapping Gitter for Discourse, but would it be possible to keep the IRC chatroom? I don't feel Discourse is appropriate for quick/emergency matters.

**Comment by commitay** [comment]
> but would it be possible to keep the IRC chatroom? I don't feel Discourse is appropriate for quick/emergency matters.

I'd rather remove it unless we have several maintainers who can commit to monitoring it.

**Comment by MikeMcQuaid** [comment]
> I'd rather remove it unless we have several maintainers who can commit to monitoring it.

Agreed. It's not about deleting the channel but having it mentioned as an official communication mechanism.

**Comment by CryoRenegade** [comment]
How about we make an official Discord server for Homebrew also? We can then sort out problems in channels like (#general) or (#core-bugs).

**Comment by vitorgalvao** [comment]
> How about we make an official Discord server for Homebrew also?

I don’t think the solution is more chatrooms. From my experience with Gitter, chatrooms for open source seem like a bad idea. The same questions are asked over and over and conversations cannot be easily retrieved, leading to an endless cycle of repetition.

Chatrooms are a great idea for “hit and runners” that want to ask one question and leave, but frustrating for everyone else.

Dev-only chatrooms are another matter entirely. Those I think have value.

**Comment by CryoRenegade** [comment]
👍

**Comment by MikeMcQuaid** [comment]
> I don’t think the solution is more chatrooms. From my experience with Gitter, chatrooms for open source seem like a bad idea. The same questions are asked over and over and conversations cannot be easily retrieved, leading to an endless cycle of repetition.

I agree. This is why I am not (personally) in chatrooms for end-users: I do not want to have a continuous, unstructured requests for support.

**Comment by commitay** [comment]
This was done in https://github.com/Homebrew/homebrew-cask/pull/49489

I'll wait a couple of days before deleting the gitter room so people active there have a chance to see the notice that it is being deleted.

**Comment by commitay** [comment]
Gitter room has been deleted.

**Comment by CryoRenegade** [comment]
RIP Gitter. Long live Discourse!
