### ISSUE TITLE
Gimp 2.10 update leaves old app installed due to app rename

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew-cask#49486]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

After upgrading `gimp` to 2.10.4 the old app is still there, because new app has different spelling and version in name, so users now have two versions installed: `GIMP.app` (2.8.22) and `Gimp-2.10.app`.

**Comment by commitay** [comment]
Do did you upgrade?

**Comment by yurikoles** [comment]
yes

**Comment by commitay** [comment]
Sorry, how did you upgrade it? With `brew cask upgrade`?

**Comment by yurikoles** [comment]
Actually I did it with buo's extension, but I don't think that's the issue.

**Comment by commitay** [comment]
This shouldn't have been a problem is `brew cask upgrade` was used. Please post the full output of the command (as the template requested.)

**Comment by commitay** [comment]
Does the extension run `brew cask upgrade` or something else like `reinstall` or `install --force`?

**Comment by commitay** [comment]
It runs `install -force` which doesn't remove the previous version. This isn't a problem with cask.

**Comment by vitorgalvao** [comment]
> Actually I did it with buo's extension, but I don't think that's the issue.

That is very much an issue. It has been stated multiple times that we don’t support it. If you use an external tool, you do so at your own risk.

**Comment by vitorgalvao** [comment]
> Actually I did it with buo's extension, but I don't think that's the issue.

That is very much an issue. It has been stated multiple times that it doesn’t handle edge cases correctly and that we don’t support it, which is why it took so long for `upgrade` to be implemented — to be done right. If you use an external tool, you do so at your own risk.
