### ISSUE TITLE
Projectlibre checksum mismatch

### ISSUE THREAD

**Issue by robruma** [Homebrew/homebrew-cask#49488]
#### General troubleshooting steps

- [ ] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

$ brew cask install projectlibre
Updating Homebrew...
==> Satisfying dependencies
==> Downloading https://downloads.sourceforge.net/projectlibre/ProjectLibre/1.8/ProjectLibre-1.8.0.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask projectlibre
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'projectlibre' does not match.

Expected: c25bed132701c929afeb649ff208c5a75620e20f02f63eb7b10dae207635fe28
Actual:   0132bcf33b7e792ed0693888982b1163e5397c7820329188f0f916b2e0246ec7
File:     /Users/rruma/Library/Caches/Homebrew/Cask/projectlibre--1.8.0.dmg

#### Command that failed

```
brew cask install projectlibre
```

#### Output of command with `--force --verbose --debug`

```
I don't think so
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.6.12
Homebrew/homebrew-cask (git revision 87de68; last commit 2018-07-10)
==> macOS
10.13.5
==> SIP
Enabled
==> Java
10.0.1, 10, 9.0.4, 9.0.1, 1.8.0_144, 1.8.0_102, 1.8.0_31
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 91.6MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3994 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (185 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
Updating Homebrew...
buo/cask-upgrade
homebrew/boneyard
homebrew/bundle
homebrew/cask
homebrew/cask-versions
homebrew/completions
homebrew/core
homebrew/dupes
homebrew/services
```

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask#reporting-bugs → https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error

https://github.com/Homebrew/homebrew-cask/pull/47841
