### ISSUE TITLE
brew cask upgrade fails to use original appdir

### ISSUE THREAD

**Issue by ralphrmartin** [Homebrew/homebrew-cask#49543]
I like to organise my applications in different directories such as /Applications/Audio, so installed them using invocations such as
brew cask install --appdir=/Applications/Audio plex-mdeia-player

However, on issuing 
brew cask upgrade
I get
Error: It seems the App source '/Applications/Plex Media Player.app' is not there.
This can be overcome by issuing
brew cask reinstall  --appdir=/Applications/Audio plex-mdeia-player

From this, I infer that brew cask upgrade is not behaving properly - it needs to take into account the original appdir used when installing, and it is not doing so.

**Comment by commitay** [comment]
https://github.com/Homebrew/homebrew-cask/issues/40866
