### ISSUE TITLE
cask: nylas-mail-lives archived

### ISSUE THREAD

**Issue by brianmorton** [Homebrew/homebrew-cask#49694]
Their github repo has been updated with this note:
>Not Maintained & no longer secure: The current maintainers of this repo no longer have the ability to devote their time to maintaining this project. There are currently multiple vulnerable dependencies and it is highly recommended that you take a look at [Mailspring](https://getmailspring.com/). Mailspring is the spiritual successor of Nylas Mail, and is maintained by the original creator. You will find that Mailspring is very similar, and much more secure than Nylas Mail Lives. This project is now in Archive Mode.

Should the cask be removed in light of the security issues they say are present?

**Comment by vitorgalvao** [comment]
> Should the cask be removed in light of the security issues they say are present?

Definitely. Does this affect `nylas-mail` in any way?

**Comment by brianmorton** [comment]
I don't think so, but I am no expert on this.

**Comment by commitay** [comment]
`lives` is a fork of the original project which hasn't been updated for quite a while, if the fork has security issues I'd remove them both.

**Comment by brianmorton** [comment]
if we do a cask for their recommended replacement, mailspring, is it possible to just have the to `nylas` casks redirect or mention that they should install that instead?

**Comment by commitay** [comment]
No, we don't have support for this.

**Comment by commitay** [comment]
`nylas-mail` is still available for download with only a "discontinued" statement, I'll leave it alone for now but we will probably want to remove it at some point.
