### ISSUE TITLE
brew cask install --force $TOKEN

### ISSUE THREAD

**Issue by brianmorton** [Homebrew/homebrew-cask#49764]
[Came up](https://github.com/Homebrew/homebrew-cask/pull/49752#discussion_r203215448) while discussing a cask update, as I had the wrong impression of what the `--force` flag actually does.

I thought if there was a checksum mismatch on a cask install, that force would still let the cask be installed. This is not true.

But why can't it be true?

**Comment by brianmorton** [comment]
If I submit a PR to change this would that be acceptable?

**Comment by vitorgalvao** [comment]
It is acceptable to me that there is an option to bypass shasum mismatch errors. Be it an extra feature of `--force` or a new `--ignore-sha` option is something I don’t feel strongly about.

Ping @reitermarkus @commitay @claui.

**Comment by commitay** [comment]
If we're going to let users do this a separate `--ignore-sha` option would be better so it's absolutely clear to users what they are running. It should also probably be overridden by the `−−require−sha` option if it's set.

TBH, I don't really see the point in adding this now in light of https://github.com/Homebrew/homebrew-cask/issues/48862 as checksum mismatches won't be as much of an issue when it's implemented.

**Comment by brianmorton** [comment]
This can be closed now as it is obsolete I believe?

**Comment by claui** [comment]
@brianmorton 👍 for closing this, now that https://github.com/Homebrew/brew/pull/5371 has shipped.

**Comment by vitorgalvao** [comment]
Agreed.

**Comment by core-code** [comment]
i'm still very much interested in an option to force 'brew cask install' to go on even with SHA mismatches as this is important in a pipeline to find cask updates.

i do have scripts that work around the issue by patching the brew installation not to require the SHA to match beforehand and then unpatching brew later on. this is a ugly hack and i wish it wasn't necessary

**Comment by vitorgalvao** [comment]
@core-code I’d say a new issue is warranted at this point (half the commenters on this one are no longer regulars).

I’d still be fine with it being an `--ignore-sha` flag that’s overridden by `−−require−sha` if set.

> i do have scripts that work around the issue by patching the brew installation not to require the SHA to match beforehand and then unpatching brew later on.

My version of that in `cask-repair` is to modify the cask itself to use `sha256 :no_check`.

**Comment by core-code** [comment]
> @core-code I’d say a new issue is warranted at this point (half the commenters on this one are no longer regulars).

thanks, i am happy to create a new bug report

> My version of that in cask-repair is to modify the cask itself to use sha256 :no_check.

well, good idea didn't think about it. but the basic problem is the same ..... if something unepected occurs you are left with modified files that are under git control
