### ISSUE TITLE
Filebot 4.8.2 cask sha256 is stale

### ISSUE THREAD

**Issue by kogent** [Homebrew/homebrew-cask#49801]
looks like #49681 is not yet complete and the sha256 needs updating
```
Error: Checksum for Cask 'filebot' does not match.

Expected: 20cd5761bc51a213d31ab035f28831fb0e4d9097727a80e32f2d477fcccb0525
Actual:   1392977186771075a23ff9758fa5f4f3eb1229df0674a43ec7cb8b8a8b737777
File:     /Users/mcarey/Library/Caches/Homebrew/Cask/filebot--4.8.2.tar.xz

To retry an incomplete download, remove the file above.
```
The sha256 posted at the same source of the .tar.xz file shows the `Actual` hash is correct:
```bash
curl https://get.filebot.net/filebot/FileBot_4.8.2/FileBot_4.8.2.app.tar.xz.sha256
1392977186771075a23ff9758fa5f4f3eb1229df0674a43ec7cb8b8a8b737777
```

**Comment by commitay** [comment]
> looks like #49681 is not yet complete and the sha256 needs updating

The sha256 was updated, the file has been updated in-place after the PR was merged.

Ping @rednoah

**Comment by rednoah** [comment]
Yep, looks like the release packages have been updated with a minor revision. The new SHA-256 is `1392977186771075a23ff9758fa5f4f3eb1229df0674a43ec7cb8b8a8b737777`.

➔ https://github.com/filebot/website/blob/master/get.filebot.net/filebot/FileBot_4.8.2/FileBot_4.8.2.app.tar.xz.sha256

**Comment by rednoah** [comment]
Will submit a new PR.

**Comment by commitay** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-cask/pull/49803
