### ISSUE TITLE
Brew & cask upgrade script - brewup

### ISSUE THREAD

**Issue by ymolul** [Homebrew/homebrew-cask#49832]
### brewup - Brew & cask upgrade script

Hello,
I wrote a very basic shell script to update the installed brew and cask. 
I would like to share it with you, hoping it could become part of the project.
Thank you.

Ymolul

### The code

```
#!/bin/bash
brew update
brew upgrade
brew prune
brew cleanup

for c in $(brew cask list -1); do
    info=$(brew cask info $c)
    current_ver=$(echo "$info" | gcut -d$'\n' -f1 | gtr -d ' ' | gcut -d':' -f 2 | awk -F \( '{ print $1 }')
    installed_ver=$(echo "$info" | gcut -d$'\n' -f3 | gcut -d' ' -f 1 | rev | gcut -d'/' -f 1 | rev | gcut -d':' -f 1)
    if [ "$installed_ver" != "$current_ver" ]; then
        read -p  "$c installed version is '$installed_ver', but the current version is '$current_ver', do you want to upgrade $c ? [y/n] " answer
	if [ $answer = y ] ; then
        brew cask upgrade --force $c
    fi
fi
done
brew cask cleanup
brew doctor
```

### Setup instructions

Create a file in /usr/local/bin called "brewup"
`vi /usr/local/bin/brewup`

and insert the above code inside it

make it executable 
`chmod +x /usr/local/bin/brewup`

and launch the script...

That's all

**Comment by vitorgalvao** [comment]
Welcome @ymolul. Thank you for the enthusiasm, but we’re not interested in such a script. I suggest you publish a gist if you want to share it.
