### ISSUE TITLE
"Error: invalid option: --caskroom=/usr/local/Caskroom" on every cask command

### ISSUE THREAD

**Issue by dxu** [Homebrew/homebrew-cask#49868]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

On every single cask command listed, I get the error `Error: invalid option: --caskroom=/usr/local/Caskroom`

#### Command that failed

```
brew cask audit 
```

#### Output of command with `--force --verbose --debug`

```

bash-3.2$ brew cask audit --force --verbose --debug
Error: invalid option: --caskroom=/usr/local/Caskroom
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/options.rb:60:in `process_arguments'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:40:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:93:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:157:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:122:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:162:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:162:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:145:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:122:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```

#### Output of `brew cask doctor`

```
Error: invalid option: --caskroom=/usr/local/Caskroom
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/cask-fonts
homebrew/core
```

Some other information: 

I was setting up a new laptop, and cask installs were working fine. I was then trying to install [Adobe Source Code Pro](https://github.com/adobe-fonts/source-code-pro). I was able to successfully run `brew tap caskroom/fonts`, but it then it ran into this message when trying to install the cask. 

Screenshots:
<img width="1336" alt="screen shot 2018-07-19 at 8 02 07 pm" src="https://user-images.githubusercontent.com/718423/42976356-20f845c4-8b8f-11e8-988b-783bb3ca3acb.png">
<img width="1015" alt="screen shot 2018-07-19 at 8 02 16 pm" src="https://user-images.githubusercontent.com/718423/42976357-2345397c-8b8f-11e8-86f1-8746979175eb.png">

**Comment by commitay** [comment]
Output of `brew config`?

**Comment by dxu** [comment]
Thanks for the quick response!

```
bash-3.2$ brew config
HOMEBREW_VERSION: 1.7.0-53-g97e5493
ORIGIN: https://github.com/Homebrew/brew
HEAD: 97e549300cf520128284fd364f08613dc1af0202
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b47f6ebe254ebc978d569f7e2710608757c527c0
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: --appdir=/Applications --caskroom=/usr/local/Caskroom
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.1 build 902
Git: 2.13.5 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.4-x86_64
CLT: 9.3.0.0.1.1521514116
Xcode: N/A
XQuartz: N/A
```

**Comment by commitay** [comment]
> HOMEBREW_CASK_OPTS: --appdir=/Applications --caskroom=/usr/local/Caskroom

You have `--caskroom=/usr/local/Caskroom` set in you dotfiles.

**Comment by dxu** [comment]
Ah, my bad, my dotfiles are pretty out of date. Thanks for the quick turnaround and your help!
