### ISSUE TITLE
ATOM: fix "apm disable" command

### ISSUE THREAD

**Issue by JBallin** [Homebrew/homebrew-cask#49917]
```
$ apm disable linter
Disabled:
  linter
✓
$ apm list
linter@2.2.0
linter-eslint@8.4.1 (disabled)
```
**What should happen**
`apm list` should show `(disabled)` for `linter` but the command doesn't seem to work. `enable` works. `disable` worked previously with my non cask-installed version of Atom.

**What you tried**
`brew cask reinstall atom` didn't fix.

--

Atom version: 1.28.2

**Comment by commitay** [comment]
How is this a cask issue, shouldn't it be an issue for upstream?

**Comment by JBallin** [comment]
@commitay sorry for opening this, I'm going to investigate further as this seems to be specific to my machine. Thanks for taking a look!
