### ISSUE TITLE
Unable to install google-cloud-sdk using brew cask

### ISSUE THREAD

**Issue by shahamit2** [Homebrew/homebrew-cask#50036]
#### General troubleshooting steps

- [ ] I have retried my command with `--force` and the issue is still present.
- [ ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
  - [ ] None of the templates was appropriate for my issue, or I’m not sure.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

{{Unable to install google-cloud-sdk using brew cask on mac-os}}

#### Command that failed

```
{{brew cask install google-cloud-sdk --verbose --force}}
```

#### Output of command with `--force --verbose --debug`

```
{{shaham01-mac:~ shaham$ brew cask install google-cloud-sdk --verbose --force --debug
==> Loading Cask definitions
==> Translating 'google-cloud-sdk' into a valid Cask source
==> Testing source class Hbc::Source::URI
==> Testing source class Hbc::Source::PathSlashRequired
==> Testing source class Hbc::Source::TappedQualified
==> Testing source class Hbc::Source::UntappedQualified
==> Testing source class Hbc::Source::Tapped
==> Success! Using source class Hbc::Source::Tapped
==> Resolved Cask URI or file source to '/usr/local/homebrew/Library/Taps/caskroom/homebrew-cask/Casks/google-cloud-sdk.rb'
Error: /usr/local/homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:42: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:46: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '(' while loading 'google-cloud-sdk' from '/usr/local/homebrew/Library/Taps/caskroom/homebrew-cask/Casks/google-cloud-sdk.rb'
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:23:in `rescue in load'
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:19:in `load'
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:11:in `load_from_file'
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/source/path_base.rb:20:in `load'
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/source/tapped.rb:15:in `load'
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc.rb:58:in `load'
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:21:in `block in install_casks'
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `each'
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `install_casks'
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:112:in `run_command'
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `process'
/usr/local/homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:166:in `exit'
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:166:in `rescue in process'
/usr/local/homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:146:in `process'
/usr/local/homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/homebrew/Library/Homebrew/brew.rb:100:in `<main>'}}
```

#### Output of `brew cask doctor`

```
{{shaham01-mac:~ shaham$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.1.10-376-g0dfe85d-dirty
caskroom/homebrew-cask (git revision 7ac093; last commit 2018-07-25)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/homebrew/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (2 files, 3.3MB)
==> Homebrew-Cask Taps:
/usr/local/homebrew/Library/Taps/caskroom/homebrew-cask (3998 casks)
==> Contents of $LOAD_PATH
/usr/local/homebrew/Library/Homebrew/cask/lib
/usr/local/homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LC_CTYPE="UTF-8"
PATH="/Users/ashah/software:/usr/local/homebrew/bin:/Users/ashah/Personal/LA/packer:/Users/ashah/gocode/bin:/usr/local/opt/groovy/libexec:/usr/local/apache-cassandra-3.9:/usr/local/Cellar/gradle/3.3/bin:/Users/ashah/.rvm/gems/ruby-2.4.0/bin:/Users/ashah/.rvm/gems/ruby-2.4.0@global/bin:/Users/ashah/.rvm/rubies/ruby-2.4.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:~/.rvm/bin:/usr/local/homebrew/Library/Taps/homebrew/homebrew-core/cmd:/usr/local/homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/homebrew/Library/Homebrew/cask/cmd:/usr/local/homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"}}
```

#### Output of `brew tap`

```
{{shaham01-mac:~ shaham$ brew tap
caskroom/cask
homebrew/core
homebrew/dupes
homebrew/services}}
```

**Comment by shahamit2** [comment]
shaham01-mac:~ shaham$ brew config
HOMEBREW_VERSION: 1.1.10-376-g0dfe85d-dirty
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0dfe85df1376097ae966f6d710df716ad9a38ff2
Last commit: 1 year, 5 months ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 71838be7661e2d48da00acb9d684b0eebea6e61f
Core tap last commit: 18 hours ago
HOMEBREW_PREFIX: /usr/local/homebrew
HOMEBREW_REPOSITORY: /usr/local/homebrew
HOMEBREW_CELLAR: /usr/local/homebrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 9.0 build 900
Git: 2.10.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/homebrew/bin/python => /usr/local/homebrew/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/ashah/.rvm/rubies/ruby-2.4.0/bin/ruby => /Users/shaham/.rvm/rubies/ruby-2.4.0/bin/ruby
Java: 1.8.0_121, 1.8.0_111
macOS: 10.12.6-x86_64
Xcode: N/A
CLT: 9.2.0.0.1.1510905681
X11: N/A

@@@@@@@@@@@@@@@@@@@@@@@@@

shaham01-mac:~ shaham$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /usr/local/bin/gpg-error-config
  /usr/local/bin/ksba-config
  /usr/local/bin/libassuan-config
  /usr/local/bin/libgcrypt-config
  /usr/local/bin/libusb-config
  /usr/local/bin/pkg-config
  /usr/local/bin/pth-config
  /usr/local/bin/python-config
  /usr/local/bin/python2-config
  /usr/local/bin/python2.7-config
  /usr/local/bin/python3-config
  /usr/local/bin/python3.5-config
  /usr/local/bin/python3.5m-config
  /usr/local/bin/python3.6-config
  /usr/local/bin/python3.6m-config
  /usr/local/bin/uuid-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libsymsea.dylib
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  libffi
  openssl
  readline
  sqlite

Warning: Your Homebrew's prefix is not /usr/local.
You can install Homebrew anywhere you want but some bottles (binary packages)
can only be used with a /usr/local prefix and some formulae (packages)
may not build correctly with a non-/usr/local prefix.
Error: libpng: /usr/local/homebrew/Library/Taps/homebrew/homebrew-core/Formula/libpng.rb:38: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
        png_structp png_ptr;
                           ^
/usr/local/homebrew/Library/Taps/homebrew/homebrew-core/Formula/libpng.rb:40: syntax error, unexpected ',', expecting ')'
        png_destroy_write_struct(&png_ptr, (png_infopp)NULL);
                                          ^
/usr/local/homebrew/Library/Taps/homebrew/homebrew-core/Formula/libpng.rb:40: syntax error, unexpected tCONSTANT, expecting keyword_end
        png_destroy_write_struct(&png_ptr, (png_infopp)NULL);
                                                           ^
/usr/local/homebrew/Library/Taps/homebrew/homebrew-core/Formula/libpng.rb:42: syntax error, unexpected '}', expecting keyword_end

**Comment by commitay** [comment]
> HOMEBREW_VERSION: 1.1.10-376-g0dfe85d-dirty
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0dfe85d
Last commit: 1 year, 5 months ago

You have a very outdated Homebrew. Did you run `brew update-reset && brew update`?

**Comment by shahamit2** [comment]
thanks for help.
brew reset seems to be failing. It is not able to resolve delta while downloading from github.
Please see below.

shaham01-mac:~ shaham$ brew update-reset
==> Fetching /usr/local/homebrew...
error: Could not read 0a0c305111d4d6600164ca1179e09e68cc2cd18e
error: Could not read ae8627e0568e8f784fa1804cc82f8a5f6a867420
error: Could not read 0a0c305111d4d6600164ca1179e09e68cc2cd18e
error: Could not read ae8627e0568e8f784fa1804cc82f8a5f6a867420
remote: Counting objects: 24734, done.
remote: Compressing objects: 100% (6063/6063), done.
remote: Total 24734 (delta 18923), reused 23748 (delta 18018), pack-reused 0
Receiving objects: 100% (24734/24734), 4.19 MiB | 239.00 KiB/s, done.
Resolving deltas:  99% (18896/18923), completed with 553 local objects.
fatal: pack has 27 unresolved deltas
fatal: index-pack failed

==> Resetting /usr/local/homebrew...
error: unable to unlink old '.github/ISSUE_TEMPLATE.md': Permission denied
Branch master set up to track remote branch master from origin.
Reset branch 'master'
Your branch is up-to-date with 'origin/master'.

==> Fetching /usr/local/homebrew/Library/Taps/caskroom/homebrew-cask...

==> Resetting /usr/local/homebrew/Library/Taps/caskroom/homebrew-cask...
Branch master set up to track remote branch master from origin.
Reset branch 'master'
Your branch is up-to-date with 'origin/master'.

==> Fetching /usr/local/homebrew/Library/Taps/homebrew/homebrew-core...
remote: Counting objects: 72, done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 72 (delta 54), reused 69 (delta 51), pack-reused 0
Unpacking objects: 100% (72/72), done.
From https://github.com/Homebrew/homebrew-core
   71838be..026b7f7  master     -> origin/master

==> Resetting /usr/local/homebrew/Library/Taps/homebrew/homebrew-core...
Branch master set up to track remote branch master from origin.
Reset branch 'master'
Your branch is up-to-date with 'origin/master'.

==> Fetching /usr/local/homebrew/Library/Taps/homebrew/homebrew-dupes...

==> Resetting /usr/local/homebrew/Library/Taps/homebrew/homebrew-dupes...
Branch master set up to track remote branch master from origin.
Reset branch 'master'
Your branch is up-to-date with 'origin/master'.

==> Fetching /usr/local/homebrew/Library/Taps/homebrew/homebrew-services...

==> Resetting /usr/local/homebrew/Library/Taps/homebrew/homebrew-services...
Branch master set up to track remote branch master from origin.
Reset branch 'master'
Your branch is up-to-date with 'origin/master'.

**Comment by shahamit2** [comment]
I think this is issue with my macbook. I will fix it. Kindly advise if can proceed with closing this.
