### ISSUE TITLE
Error installing pandora

### ISSUE THREAD

**Issue by yipeecaiey** [Homebrew/homebrew-cask#50206]
#### General troubleshooting steps

- [Y] I have retried my command with `--force` and the issue is still present.
- [Y] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
  - [Y] None of the templates was appropriate for my issue, or I’m not sure.
- [Y] I ran `brew update-reset && brew update` and retried my command.
- [Y] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [Y] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Error while installing pandora.

#### Command that failed

```
brew cask install pandora
```

#### Output of command with `--force --verbose --debug`

```
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
All Cask dependencies satisfied.
==> Downloading
==> Downloading https://www.pandora.com/static/desktop_app/pandora_2_0_10.air
Already downloaded: /Users/yipeecaiey/Library/Caches/Homebrew/Cask/pandora--2.0.10.air
==> Downloaded to -> /Users/yipeecaiey/Library/Caches/Homebrew/Cask/pandora--2.0.10.air
==> Verifying download
==> Determining which verifications to run for Cask pandora
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask pandora
==> SHA256 checksums match
==> Installing Cask pandora
==> Hbc::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Air for /Users/yipeecaiey/Library/Caches/Homebrew/Cask/pandora--2.0.10.air
==> /Applications/Utilities/Adobe\ AIR\ Application\ Installer.app/Contents/MacOS/Adobe\ AIR\ Application\ Installer -silent -location /var/folders/q2/s2wvvbzd003f6n8h8yll48nw0000gn/T/d20180729-7050-qsf15h /Users/yipeecaiey/Library/Caches/Homebrew/Cask/pandora--2.0.10.air
==> Purging files for version 2.0.10 of Cask pandora
Error: Failure while executing; `/Applications/Utilities/Adobe\ AIR\ Application\ Installer.app/Contents/MacOS/Adobe\ AIR\ Application\ Installer -silent -location /var/folders/q2/s2wvvbzd003f6n8h8yll48nw0000gn/T/d20180729-7050-qsf15h /Users/yipeecaiey/Library/Caches/Homebrew/Cask/pandora--2.0.10.air` exited with 9. Here's the output:
failed due to bad configuration

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:107:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:51:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:23:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:16:in `system_command!'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/air.rb:16:in `extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:96:in `extract'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:103:in `block in extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:100:in `extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:172:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:67:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:88:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:93:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:159:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:124:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:170:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:170:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:147:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:124:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```

#### Output of `brew cask doctor`

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Applications/MAMP/Library/bin/curl-config
  /Applications/MAMP/Library/bin/freetype-config
  /Applications/MAMP/Library/bin/icu-config
  /Applications/MAMP/Library/bin/libmcrypt-config
  /Applications/MAMP/Library/bin/libpng-config
  /Applications/MAMP/Library/bin/libpng16-config
  /Applications/MAMP/Library/bin/Magick++-config
  /Applications/MAMP/Library/bin/Magick-config
  /Applications/MAMP/Library/bin/MagickCore-config
  /Applications/MAMP/Library/bin/MagickWand-config
  /Applications/MAMP/Library/bin/pcre-config
  /Applications/MAMP/Library/bin/pcre2-config
  /Applications/MAMP/Library/bin/pkg-config
  /Applications/MAMP/Library/bin/python-config
  /Applications/MAMP/Library/bin/python2-config
  /Applications/MAMP/Library/bin/python2.7-config
  /Applications/MAMP/Library/bin/sablot-config
  /Applications/MAMP/Library/bin/Wand-config
  /Applications/MAMP/Library/bin/x86_64-apple-darwin13.4.0-pkg-config
  /Applications/MAMP/Library/bin/xml2-config
  /Applications/MAMP/Library/bin/xslt-config
  /Applications/MAMP/Library/bin/yaz-config
  /Applications/MAMP/bin/php/php7.2.1/bin/php-config

```

#### Output of `brew tap`

```
homebrew/cask
homebrew/core
homebrew/services
```

**Comment by commitay** [comment]
Output of `brew cask doctor`?

**Comment by yipeecaiey** [comment]
==> *Homebrew-Cask Version*

Homebrew-Cask 1.7.1-41-g3c3b05d

Homebrew/homebrew-cask (git revision 26013; last commit 2018-07-29)

==> *macOS*

10.11.6

==> *SIP*

Enabled

==> *Java*

N/A

==> *Homebrew-Cask Install Location*

<NONE>

==> *Homebrew-Cask Staging Location*

/usr/local/Caskroom

==> *Homebrew-Cask Cached Downloads*

~/Library/Caches/Homebrew/Cask (10 files, 576.8MB)

==> *Homebrew-Cask Taps:*

/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4009 casks)

==> *Contents of $LOAD_PATH*

/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib

/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0

/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0

/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0

/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby

/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0

/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0

/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0

/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby

/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0

/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0

/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0

/usr/local/Homebrew/Library/Homebrew/cask/lib

/usr/local/Homebrew/Library/Homebrew

==> *Environment Variables*

LC_ALL="en_US.UTF-8"

PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"

SHELL="/bin/bash"

**Comment by commitay** [comment]
https://github.com/Homebrew/brew/pull/4567

Should be working now if you run `brew update`.

**Comment by vitorgalvao** [comment]
@yipeecaiey Please use `x` in checklists (no spaces inside the brackets) and [Github will make them clickable](https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments). Also, stick code in [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks).

**Comment by yipeecaiey** [comment]
thanks @commitay it worked perfectly this time!

@vitorgalvao I have updated as you requested.

Thanks!

**Comment by reitermarkus** [comment]
@commitay, I don't see how https://github.com/Homebrew/brew/pull/4567 relates to this. What was the problem here?
