### ISSUE TITLE
cask analytics

### ISSUE THREAD

**Issue by brianmorton** [Homebrew/homebrew-cask#50296]
https://formulae.brew.sh/analytics/install/30d/
(and developer-friendly sister, https://formulae.brew.sh/api/analytics/install/homebrew-core/30d.json)

These don't seem to take in analytics for casks. Is there something similar out there for casks?

I am working on automated updates (tailored to each cask, the way @vitorgalvao has suggested would be successful). To that end, it would be helpful to know which casks are very popular and which casks are not very popular.

Is such data available?

**Comment by vitorgalvao** [comment]
We don’t have analytics, but we do want them.

https://github.com/Homebrew/homebrew-cask/issues/47720

**Comment by brianmorton** [comment]
My bad, I definitely should have searched before opening this.
