### ISSUE TITLE
can not uninstall cask 'autofirma'

### ISSUE THREAD

**Issue by core-code** [Homebrew/homebrew-cask#50361]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [ ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
  - [ ] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Uninstalling Cask autofirma fails if the installer has been aborted and therefore the certificate is not installed

#### Command that failed

```
brew cask uninstall --force autofirma
```

#### Output of command with `--force --verbose --debug`

```
$ brew cask uninstall --force --verbose --debug autofirma
==> Uninstalling Cask autofirma
==> Uninstalling Cask autofirma
==> Un-installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x00007fb3ccd2e998>
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for autofirma; your password may be necessary
==> Uninstalling packages:
/usr/sbin/pkgutil --pkgs=es.gob.afirma
==> Removing files:
/Applications/AutoFirma.app
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --
==> Un-installing artifact of class Hbc::Artifact::PostflightBlock
/usr/bin/sudo -E -- /usr/bin/security delete-certificate -c AutoFirma\ ROOT
Unable to delete certificate matching "AutoFirma ROOT"Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/security delete-certificate -c AutoFirma\ ROOT` exited with 1. Here's the output:
Unable to delete certificate matching "AutoFirma ROOT"

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:101:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:46:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:23:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl/base.rb:14:in `system_command'
/usr/local/Caskroom/autofirma/.metadata/1.6.2/20180803115355.669/Casks/autofirma.rb:14:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:38:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:38:in `abstract_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:26:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:443:in `block in uninstall_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:440:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:393:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:169:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:169:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
Julians-MBP:~ julian$ 

```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.7.1-106-gd58607a
Homebrew/homebrew-cask (git revision 5508a; last commit 2018-08-03)
==> macOS
10.14
==> SIP
Disabled
==> Java
N/A
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (7 files, 371.5MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4014 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (191 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-eid (11 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1164 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (152 casks)
==> Contents of $LOAD_PATH
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
$ brew tap
homebrew/cask
homebrew/cask-drivers
homebrew/cask-eid
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
vitorgalvao/tiny-scripts

```

$ brew cask uninstall autofirma
==> Uninstalling Cask autofirma
==> Running uninstall process for autofirma; your password may be necessary
==> Uninstalling packages:
==> Removing files:
/Applications/AutoFirma.app
Unable to delete certificate matching "AutoFirma ROOT"
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/security delete-certificate -c AutoFirma\ ROOT` exited with 1. Here's the output:
Unable to delete certificate matching "AutoFirma ROOT"

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:97:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:46:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:21:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:25:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl/base.rb:14:in `system_command'
/usr/local/Caskroom/autofirma/.metadata/1.6.2/20180622074623.266/Casks/autofirma.rb:14:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:38:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:38:in `abstract_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:26:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:441:in `block in uninstall_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:438:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:391:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:93:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:157:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:122:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'

**Comment by commitay** [comment]
Please fill out the template.

**Comment by core-code** [comment]
i usually abort all installations when they prompt for a password since i don't want to pollute the system. however in this case some uninstallation fail, like this one. i am running 10.14 on this system, but i don't think this is a 10.14 issue.

**Comment by commitay** [comment]
If it wasn't installed it can just be deleted from `$(brew --prefix)/Caskroom/autofirma`

I'll update the cask so it doesn't fail during uninstall if the certificates don't exist.

**Comment by core-code** [comment]
> If it wasn't installed it can just be deleted from $(brew --prefix)/Caskroom/autofirma

ok thanks - can i be sure that nothing is ever installed at the point at which brew asks for a password and just doing the mentioned delete is always 'clean'?

> I'll update the cask so it doesn't fail during uninstall if the certificates don't exist.

thanks. btw, there seems to be an issue regarding uninstallation of casks with a login-item on mojave. is this known or should i submit a bug-report?

**Comment by commitay** [comment]
> can i be sure that nothing is ever installed at the point at which brew asks for a password and just doing the mentioned delete is always 'clean'?

Not always. In this case as its a pkg without a `preflight` it's fine to just delete. Also the uninstall is failing for the `uninstall_postflight` so anything that was installed should have been removed anyway.

```
  pkg "AutoFirma_#{version.dots_to_underscores}.pkg"

  # remove 'Autofirma ROOT' and '127.0.0.1' certificates from keychain (these were installed by pkg)
  uninstall_postflight do
    system_command '/usr/bin/security',
                   args: [
                           'delete-certificate',
                           '-c', 'AutoFirma ROOT'
                         ],
                   sudo: true

    system_command '/usr/bin/security',
                   args: [
                           'delete-certificate',
                           '-c', '127.0.0.1'
                         ],
                   sudo: true
  end

  uninstall pkgutil: 'es.gob.afirma',
            delete:  '/Applications/AutoFirma.app'
```

> there seems to be an issue regarding uninstallation of casks with a login-item on mojave. is this known or should i submit a bug-report?

No, it isn't known.  I'm not sure about the other maintainers but I don't even have a Mojave VM for testing yet. Feel free to submit a report and we can take a look but we probably won't do anything about it until Mojave hits GM.
