### ISSUE TITLE
Follow up for the `brew cask ci` command

### ISSUE THREAD

**Issue by commitay** [Homebrew/homebrew-cask#50405]
- Switch to using `brew pull` to avoid the need for commit range workarounds and syncing dirs.
- Try TravisBuddy again. (https://github.com/Homebrew/homebrew-cask/pull/45939)
- Post-install checks.
  - Check for appcasts. (Mentioned in https://github.com/Homebrew/homebrew-cask/issues/49200)
  - Check if a `pkg` installs an `app` to avoid open-source, cli-only casks. (new casks only)

**Comment by vitorgalvao** [comment]
> Check if a `pkg` installs an `app` to avoid open-source, cli-only casks. (new casks only)

We’ll need to refine that. A `pkg` can install nothing directly usable (driver) or a plugin (e.g. for QuickLook). Checking just for `app`s will not be enough. It may also be the case a `pkg` installs closed-source CLI.

**Comment by commitay** [comment]
It's intended to be a warning that it should be checked if it is acceptable cask or not, so we don't have to manually download and check if it has an app. I don't mean for it to be used by itself as grounds for refusing a cask.
