### ISSUE TITLE
[enhancement/feature request] - Homebrew/homebrew-cask - adding in vscode, others

### ISSUE THREAD

**Issue by tmm2018** [Homebrew/homebrew-cask#50467]
#### [enhancement/feature request] - Homebrew/homebrew-cask - adding in vscode, others

**IMHO, it would be nice to:**

- *sublime text*
- *adding in vscode*
- *atom (i think it's there already)*
- *xcode*
- *qt creator 5*
- *light table*

---

**on the basis of this assessment is the fact that:**
- *these are mostly free and/or opensource IDEs, or otherwise**
- *otherwise, IDEs that have an opensource license*
- *these are basically the most commonly used IDEs for mac*
- *the community would benefit extensively from having these tools available for macos*

**Comment by commitay** [comment]
Feel free to submit PRs.
