### ISSUE TITLE
brew style should force array square brackets on separate line

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew-cask#50531]
### Description of feature/enhancement

`brew cask style {cask_name}` should report and fix ruby array style.

### Justification

Maintainers do require square brackets to be on separate line, but rubocop doesn't report nor fix this.

### Example use case

302910a652ec7a1fa1dc161434e0a52448c45a3d

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/rubocop-cask/issues/64
