### ISSUE TITLE
igv_2_4.13: needs java 8

### ISSUE THREAD

**Issue by croth1** [Homebrew/homebrew-cask#50648]
I skipped filling the issue template because I felt that it did not apply - if I am mistaken, please let me know.

The igv cask sets the java version to '8+'

https://github.com/Homebrew/homebrew-cask/blob/4759257922e2508a8687a385f92aeefc64469aca/Casks/igv.rb#L12

But running with the standard java cask does not work.

![image](https://user-images.githubusercontent.com/15384900/43887977-9ffb6680-9bc0-11e8-9b23-b654ad198222.png)

Downgrading to the java8 cask solved the issue.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/50653/files
