### ISSUE TITLE
Appium 1.6.3 not available 

### ISSUE THREAD

**Issue by Trane9991** [Homebrew/homebrew-cask#50739]
Trying install appium I'm getting:
`curl: (22) The requested URL returned error: 404 Not Found\nError: Download failed on Cask 'appium' with message: Download failed: https://github.com/appium/appium-desktop/releases/download/v1.6.3/appium-desktop-1.6.3-mac.zip`

And I can see that download URL for appium 1.6.3 missing for releases page as well.
Maybe it worth downgrading back to 1.6.2?

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/50741
