### ISSUE TITLE
Outdated cask: presenter

### ISSUE THREAD

**Issue by thisgeek** [Homebrew/homebrew-cask#50895]
**Note**: The following report does not appear have a template. I've chosen to roughly follow the format of previous outdated cask tickets like #18176.

---

Outdated cask: [`presenter`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/presenter.rb).

**Info**

Version: 4.0.4
URL: https://support.ipevo.com/support/qa/IPEVO-Presenter

**Background**

> Please note that IPEVO Presenter is our legacy software that is no longer supported with updates or fixes. We have since released a new software “IPEVO Visualizer” for our document cameras that is more optimized.

\- _from <http://support.ipevo.com/support/qa/IPEVO-Presenter>_

**Comment by vitorgalvao** [comment]
How’s it outdated? `4.0.4` is the version we have.

**Comment by thisgeek** [comment]
Hm. Perhaps "outdated" isn't quite right. It's deprecated in favor of IPEVO Visualizer.

**Comment by vitorgalvao** [comment]
Removing in https://github.com/Homebrew/homebrew-cask/pull/50940.

A new submission will have to be done for the replacement.
