### ISSUE TITLE
Papyrus: application fails to start when java package is installed as provided by Homebrew

### ISSUE THREAD

**Issue by brokenthorn** [Homebrew/homebrew-cask#51011]
Due to architectural changes in Java 9+, which is provided by the `java` package (actually, at this time provides Java 10), Papyrus fails to start because of modules that are no longer loaded by default in newer versions of the JRE. Since most people probably have the `java` package installed and not the older `java8` package, the majority of people should be having this issue.

The fix I have been able to find is to edit the `papyrus.ini` file and add an additional line at the end: `--add-modules=java.se.ee`.

I've decided not to submit a PR to fix this since it's such a minor fix and truthfully, depends on whether `java` or `java8` is installed and I don't know Ruby to be able to provide a quick fix by altering the formula for `papyrus`.

**Comment by vitorgalvao** [comment]
Closing for lack of reply.

**Comment by brokenthorn** [comment]
Sorry for not replying. I didn't consider this being an upstream bug. I mean as long as the user installs the correct JRE (single or alongside another), the app should start. My opinion is that the user should not be forced to discover this fact, instead the package manager should either provide the compatible JRE as a dependency or, since in this case newer JREs work as long as some legacy flags are set, provide those flags for the app launcher.

**Comment by vitorgalvao** [comment]
> My opinion is that the user should not be forced to discover this fact

Agreed. And if the user manually installs the software from the official sources, as opposed from HBC, they’ll run into this exact problem. That’s why this is an upstream bug. It’s not the package manager introducing this problem. All we can add is a band-aid; they can fix it for good.

We’re no strangers to adding band-aids, but only after it’s clear upstream won’t fix an issue.
