### ISSUE TITLE
`upgrade --greedy` should not warn about `auto_updates` and `version :latest`

### ISSUE THREAD

**Issue by gtmgianni** [Homebrew/homebrew-cask#51019]
Even if you run `brew cask upgrade --greedy`, the following message is still displayed:

```
$ brew cask upgrade --greedy
==> Casks with `auto_updates` or `version :latest` will not be upgraded
```

**Comment by zdcthomas** [comment]
Hi there! I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!

**Comment by vitorgalvao** [comment]
@zdcthomas I don’t think anyone is working on this, no. You can go ahead. Thank you.
