### ISSUE TITLE
caskroom.io has been sublty hacked?

### ISSUE THREAD

**Issue by johnhamelink** [Homebrew/homebrew-cask#51050]
Hey guys,

I was installing brew cask on my new MacBook Pro, and I noticed on your website some really weird text.

<img width="1010" alt="screen shot 2018-08-20 at 19 11 30" src="https://user-images.githubusercontent.com/101739/44358418-e1894500-a4ac-11e8-8b06-ae6d111654f7.png">

My guess is that this is because someone's managed to edit the copy in order to improve some search rankings?

**Comment by vitorgalvao** [comment]
That hasn’t been our website for a good while. Someone grabbed the domain because we let it expire (on purpose). It was a mistake to do it so soon. We should have kept it for a while longer.

**Comment by johnhamelink** [comment]
That sucks, but at least it's not something overtly malicious!

**Comment by johnhamelink** [comment]
That sucks, but at least it's not something overtly malicious!
