### ISSUE TITLE
Out of service Website - http://caskroom.io/search/

### ISSUE THREAD

**Issue by jousmo** [Homebrew/homebrew-cask#51167]
http://caskroom.io/search/

<img width="763" alt="captura de pantalla 2018-08-22 a la s 18 14 27" src="https://user-images.githubusercontent.com/7170689/44495909-83d53400-a637-11e8-95c8-974e595fd708.png">

**Comment by reitermarkus** [comment]
`caskroom.io` hasn't been our website for a long time, and `caskroom.github.io` has been merged into https://brew.sh/.

**Comment by vitorgalvao** [comment]
Also, don’t use caskroom.io. We have no idea who bought it or what they plan to do with it. So far, we know they’re running ads.
