### ISSUE TITLE
halp w/ cctalk cask

### ISSUE THREAD

**Issue by brianmorton** [Homebrew/homebrew-cask#51211]
download page: https://www.cctalk.com/download/

previous (good) version and url:
https://n1other.hjfile.cn/wx/CCtalk/692/CCtalk.7.3.1-692.pkg

update (not working) version and url:
https://n1other.hjfile.cn/wx/CCtalk/707/CCtalk.7.3.2-707.dmg

The download page seems to use a script to redirect to the download and it will download if you click the button in a browser. However if I use wget on the new URL it fails. I'm sure this has come up before, but how would I try to tackle working this one out?

**Comment by vitorgalvao** [comment]
> However if I use wget on the new URL it fails.

Do you mean `curl`? Because that’s what we rely on, and sometimes one can download what the other can’t.

> how would I try to tackle working this one out?

By trying the [special parameters](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#additional-https-url-parameters).

**Comment by brianmorton** [comment]
Thanks for the help!

`curl` also failed.

This is my updated attempt at the cask file:
```
cask 'cctalk' do
  version '7.3.2,707'
  sha256 'e9e372308560f3438f56769cfc0918dfa725cc192a940fb7a307eb3c4f62ab58'

  # n1other.hjfile.cn was verified as official when first introduced to the cask
  url "https://n1other.hjfile.cn/wx/CCtalk/#{version.after_comma}/CCtalk.#{version.before_comma}-#{version.after_comma}.dmg",
      referer:    'https://www.cctalk.com/webapi/basic/v1.1/version/down?apptype=1&terminalType=8&versionType=103',
      user_agent: :fake,
      cookies:    {
                    'HJ_UID'       => '56338885-81d4-918c-4ffa-99741aee248d',
                    'HJ_SSID_54'   => 'cc93a6b2-c137-bba4-d2b0-8c7bb0a9b06b',
                    'HJ_SID'       => '74860d40-85bf-f39b-8dd7-c9fc28b302c3',
                    'HJ_CST'       => '0',
                    'HJ_CSTST_54'  => '0',
                    'HJ_CMATCH'    => '1',
                    'TRACKSITEMAP' => '54%2C',
                  }
  appcast 'http://f1.ct.hjfile.cn/api/AutoUpdate/newupdate/out/mac/cctalk/update/info.xml'
  name 'CCtalk'
  homepage 'https://www.cctalk.com/download/'

  depends_on macos: '>= :yosemite'

  pkg "CCtalk.#{version.before_comma}-#{version.after_comma}.pkg"

  uninstall pkgutil: 'com.hujiang.mac.cctalk'
end

```

and then I tried again:
```
$ brew cask audit --download ./cctalk.rb
==> Downloading https://n1other.hjfile.cn/wx/CCtalk/707/CCtalk.7.3.2-707.dmg

curl: (22) The requested URL returned error: 404 Not Found
audit for cctalk: failed
 - download not possible: Download failed on Cask 'cctalk' with message: Download failed: https://n1other.hjfile.cn/wx/CCtalk/707/CCtalk.7.3.2-707.dmg
Error: audit failed for casks: cctalk
```

I think I've done everything I can as described in the special params...

**Comment by brianmorton** [comment]
I think it may be because the cookies need to be send to the value I have as the referrer right now (`https://www.cctalk.com/webapi/basic/v1.1/version/down?apptype=1&terminalType=8&versionType=103`) but I'm not sure how to make that happen...

It seems if I was to make that URL the download URL it would probably give me the 302 to download the actual cask?

**Comment by brianmorton** [comment]
I now have it downloading by using the special params and the referral URL as the download URL... if I can't get this on track I will post further.

**Comment by brianmorton** [comment]
https://github.com/Homebrew/homebrew-cask/pull/51212
