### ISSUE TITLE
Gifox cask outdated

### ISSUE THREAD

**Issue by vemv** [Homebrew/homebrew-cask#51224]
![image](https://user-images.githubusercontent.com/1162994/44568271-5d69e280-a776-11e8-83af-1ab0f929000d.png)

`https://s3.eu-central-1.amazonaws.com/dstlalgzor/gifox/010601.03.dmg` simply doesn't exist anymore, the issue is simple.

Thanks - Victor

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/51225.

**Comment by brianmorton** [comment]
https://github.com/Homebrew/homebrew-cask/pull/51032
