### ISSUE TITLE
appserver cask: change in release model

### ISSUE THREAD

**Issue by brianmorton** [Homebrew/homebrew-cask#51299]
![image](https://user-images.githubusercontent.com/1434096/44671389-3f042100-a9da-11e8-9628-7d00101b75c1.png)

they are switching away from binary releases. what do?

drop the cask? leave the cask at it's last-released version?

**Comment by vitorgalvao** [comment]
> drop the cask?

Yes.

> leave the cask at it's last-released version?

[We purposefully don’t do that](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> Similarly (and trickier to spot), the app has moved to the Mac App Store but still provides old versions via direct download. We reject these in all official repos so users don’t get stuck using an old version, wrongly thinking they’re using the most up-to-date one (which, amongst other things, might be a security risk).

Not the same case, but the reasoning applies.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/51337
