### ISSUE TITLE
'joshaven-winbox' need to be updated for High Sierra fix.

### ISSUE THREAD

**Issue by Parahexen** [Homebrew/homebrew-cask#51614]
This cask referred to version 3.11 without High Sierra fix.

Thought it's beta stage indicated by the author, but this is for a really long time and we've fully tested it and work fine.

So maybe you are considering to alternate the cask to:
http://joshaven.com/Winbox4Mac_3.11_FixHS.dmg

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/51624
