### ISSUE TITLE
Reaper Cask has two apps, but they should be allowed to be installed independently

### ISSUE THREAD

**Issue by chillum** [Homebrew/homebrew-cask#51611]
The `reaper.dmg` indeed contains `REAPER64.app` and `ReaMote64.app` The problem is: one may want to install ReaMote, but not Reaper or install Reaper, but not ReaMote (in fact, they're designed to run on different machines).

What can we do to improve this? Split this to two packages? Use install options (how? did not find anything on this)?

**Comment by vitorgalvao** [comment]
> Use install options

We don’t support those.

> Split this to two packages

That would work, yes, though we probably won’t do that. In the cask’s years of existence, this has never been an issue. It’s not a feature desirable enough to be worth the extra cask to maintain.

If you really need this, I suggest making your own [tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md).
