### ISSUE TITLE
[feature request] adding some music software + vr stuff to the repo - actoolbox, junxion, rosa, et al

### ISSUE THREAD

**Issue by tem44** [Homebrew/homebrew-cask#51688]
## greetings

**i would kindly like to suggest the following music software to be added to your repos:**
- _http://www.actoolbox.net/_
- _http://steim.org/product/junxion/_
- _http://steim.org/product/rosa/_

**IMHO, adding this could extensively benefit the community**

**also, could be nice to add:**
- _https://unity3d.com/_
- _https://www.unrealengine.com/en-US/blog_

**looking forward**
_Cheers_

**Comment by tem44** [comment]
unity is already there

**Comment by vitorgalvao** [comment]
Some of those are already present.

Also, as stated in the [cask request template](https://github.com/Homebrew/homebrew-cask/issues/new?template=03_cask_request.md) visible [when you open a new issue](https://github.com/Homebrew/homebrew-cask/issues/new/choose) and [the README](https://github.com/Homebrew/homebrew-cask#requests), we don’t do cask requests.

Please do read the documentation we put right in front, or in the future your issues might be closed without a review. Thank you.

**Comment by vitorgalvao** [comment]
> IMHO, adding this could extensively benefit the community

I believe your heart is in the right place, but “I think this would be good” is not a valid justification. In addition, we have so many contributors and adding a cask is so easy, you can be sure that if no one is adding a piece of software, it’s because there’s either no interest from the vast majority of users or there’s something else that stops it from being included. That’s why we no longer do requests. If you want it, you have to do the legwork to add it (at which point we’ll review and help you improve the submission).

**Comment by tem44** [comment]
@vitorgalvao:
- _thank you so much for your precious feedback_

**we can only grow as opensource communities if:**
- _we learn from each other_
- _if we are open to have criticism from others_
- _if we are opened to give criticism in a positive way_
- _if we know how to listen, and how to be generous to each other_

**that part of the magic and beauty of opensource, which reasembles essential around:**
- _giving to the community in an open and generous way rather then taking away from it;_
- _with it, being able to develop skills that may sooner or later be important in a profession way or within other regards_

---

**regarding the justification to my feature request submission, i already updated my post above, but i paste down the entry above labeled as code via markdown. thank you so much**

> **in what regards to actoolbox, junxion and rosa, the main motivations for adding those are the following:**
> 
> - _these are software that have built a legacy within the scope of computer music_
> - _actoolbox was developed by a teacher and a very good friend of mine at the institute of sonology, one institution where i previously studied and to whom i owe a lot;_
> - _furthermore, it's free although not opensource ATM, it's LISP based, so a lot of the work developed into it in terms of integrating advanced math concepts such as chaos theory, music theory and other things, may be a good starting point for people to develop specific kind of work within the scope of computer music and algorithmic composition_
> - _furthermore, it integrates environments like MaxMSP/PureData, Csound and Supercollider, as well as Kyma, which are more then enough reasons to include this in the package (these are basically pieces of software used practically at any academic institution teaching computer music, ranging from high school levels, to phd students_
> - _furtermore, mr John Carmack is developing a scripting environment for Oculus Toolkit, facebook vr sdk, that will contain bindings to racket, a language from the scheme family that has plenty of similiraties with lisp, so the syntax is pretty identical to actoolbox, so with a bit of effort in terms of x86_64 disassembling, this may perfectly be a good tool to integrate into these kinds of programming environments_
> - _in what regards to JunXion and RoSa, they were both developed by another teacher and friend, namely frank balde, to who i owe also A LOT. mr frank balde is a senior developer at STEIM amsterdam, one of the most renowned institutions in the field of live electronic music, in europe, and probably, in the entire world. mr frank balde, was assistant of mr Michel Waisvisz, who is one of the key figures in computer music in the second of half of XXth century in europe_
> - _in the 80s he was already like using accelerometers and infrared sensors, and gyroscopes, with something called sensorlab, and early version of arduino, or a predeceasor (except that it was already available in the 80s and cost more then a car back then)_
> - _both the hands, on of the most advanced controllers for live electronic music ever built, Junxion, LiSa (the predeceasor of RoSa built for PPC architecture with code warrior UI framework) and RoSa were, and are still years light ahead of many commercial sofware applications in what regards to live sampling and_
> 
> **in what regards to unity, and unreal engine:**
> - _these excuse presentations being two of the most used engines by indie game developers, vr, ar, xr developers, installation artists and so around the world_
> - _unity and unity-hub are both in the repositories i guess_
> - _I wasn't able to check if unrealengine is already in the repositories but i guess no_
> - _another great software to install in the packages, is corona sdk, a game engine for low spec machines_
> 
> **among other tools, that i am not entirely sure that if they are in the hombrew cask repositories, are, at least:**
> - _blender_
> - _cinema 4d_
> - _autodesk software_
> - _zbrush_
> - _etc._

**Comment by tem44** [comment]
i kindly request the entry to be re-opened and to be reviewed by someone else, as well. thank you so much

**Comment by vitorgalvao** [comment]
> i kindly request the entry to be re-opened and to be reviewed by someone else, as well.

No. We (maintainers) already made the conscious choice to stop accepting cask requests, for the reasons I’ve outlined. **This is a documented rule**. No one will review it differently, *because we have already agreed*. Your reasons in no way overcome that. No software does. If you want the casks to be added, you need to submit them yourself (or ask someone else to do it).

Any contributor or maintainer is free to take you up on your request *as an individual*, but our official stance *as a project* is to not accept cask requests.

Further insistence will lead nowhere other than a waste of time for both of us. The rules have been explained to you, as well as their reasoning, so I expect you to respect them. Thank you.

**Comment by tem44** [comment]
i see your point. is there any video tutorial explaining how to add casks to homebrew. or otherwise documentation explaining how to do that? i've never done that myself, but am definitely willing to learn how to do so. perharps looking at the source code of this repo might be a good chance. thank you so much!!!

**Comment by tem44** [comment]
i'm now checking some formulas of casks. it's all like ruby based simple information for the package manager. i think i can handle that stuff. that's just getting the url adding some version data, adding checksum, and a few other things, so shall not hurt me within certain regard

**Comment by vitorgalvao** [comment]
Start with the [`adding_a_cask`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md) document. Move to [the language reference](https://github.com/Homebrew/homebrew-cask/tree/master/doc/cask_language_reference) to learn about each individual stanza in detail.
