### ISSUE TITLE
[enhancement] - homebrew/homebrew-cask - adding 4 formulas - wip - in a separate fork/branch

### ISSUE THREAD

**Issue by tem44** [Homebrew/homebrew-cask#51719]
#### [enhancement] - homebrew/homebrew-cask - adding 4 formulas - wip - in a separate fork/branch

- *_https://github.com/tem44/homebrew-cask/commit/00f0047b2959e435b687faba75ba4587f3b219dd_*

**feedback welcome (it's the first time i am preparing a pull request to homebrew cask, so i would like to have feedback)**

**Comment by vitorgalvao** [comment]
Please don’t open an issue if you’re opening a PR as well; open just the PR.

Also, please stop bolding everything, it makes your posts way harder to parse and read.
