### ISSUE TITLE
Re-add send-to-kindle

### ISSUE THREAD

**Issue by ericmarkmartin** [Homebrew/homebrew-cask#51733]
If I understand correctly from the issue threads namely #28191, then the reason this cask was dropped was because Amazon's installation process didn't support newer versions of macOS with SIP. I'm running High Sierra (10.13.6), which has SIP, and it seems fine now. I think this may have been part of an Amazon thing where they went and updated a bunch of these apps because I went through the same thing with kindle-previewer this past year (#43099).

As such, I was wondering if the cask could be added back in. I'm happy to make the PR myself, just let me know.

**Comment by vitorgalvao** [comment]
If it works, it works. You can go ahead with the PR.
