### ISSUE TITLE
Cache downloads

### ISSUE THREAD

**Issue by brandonkal** [Homebrew/homebrew-cask#51805]
### Description of feature/enhancement

I work in a bandwidth-limited location. Before using Homebrew cask, I would save downloaded dmg files to a network storage location to install software on all Macs on the network after download.

Is it possible to do this with Homebrew Cask?

### Justification

With slow download speeds, or locations with multiple Macs managed with Homebrew, using a cache would speed up the installation and update process of GUI applications. This would also be useful for managing large networks. Apple has this feature for App Store downloads with MacOS server and it would be great to have something similar for Homebrew downloads.

### Example use case

The user would have the option to specify where dmg files are downloaded. `brew cask install docker` would first check for the existance of Docker.dmg with the correct checksum in this cache folder (on a network folder in this example), if it exists, it would be used directly rather than fetching the 2GB file from the internet once again.

**Comment by vitorgalvao** [comment]
Downloads are cached by default to `~/Library/Caches/Homebrew`. If you directory is different, you can find it with `brew --cache`. To change the cache directory, use the environment variable `HOMEBREW_CACHE`. Check the `man` page: `man brew | less +'/HOMEBREW_CACHE'`.
