### ISSUE TITLE
Cannot use cask after update to mojave

### ISSUE THREAD

**Issue by rafilkmp3** [Homebrew/homebrew-cask#51860]
#### General troubleshooting steps

- [X] I have retried my command with `--force` and the issue is still present.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I cannot use the brew.  i can`t remove the puppet-agent and i am struck

#### Command that failed

```
┗ brew cask --force --verbose --debug uninstall puppet-agent


Warning: Cask 'puppet-agent' is unreadable: undefined method `major_minor' for nil:NilClass
Error: Cask 'puppet-agent' is unreadable: undefined method `major_minor' for nil:NilClass
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:52:in `rescue in casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:46:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:12:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of command with `--force --verbose --debug`

```
{{replace this}}
```

#### Output of `brew cask doctor`

```
┗ brew cask doctor
==> Homebrew Version
1.7.4-24-g375088c
==> macOS
10.14
==> SIP
Enabled
==> Java
10.0.2
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4050 casks)
/usr/local/Homebrew/Library/Taps/puppetlabs/homebrew-puppet (3 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (195 casks)
==> Contents of $LOAD_PATH
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
┏ ✔     ~/Down…oads/unomi-1.3.0-incubating 
```

#### Output of `brew tap`

```
buo/cask-upgrade
homebrew/bundle
homebrew/cask
homebrew/cask-versions
homebrew/core
puppetlabs/puppet
tsuru/tsuru
wata727/tflint
┏ ✔     ~/Down…oads/unomi-1.3.0-incubating                                                                                              7.38   6.13G 
┗
```

**Comment by CryoRenegade** [comment]
Is the cask made for Mojave? It could be a simple compatibility issue.

**Comment by vitorgalvao** [comment]
This is a bug with the [`puppet-agent`](https://github.com/puppetlabs/homebrew-puppet/blob/master/Casks/puppet-agent.rb) cask that is not part of the official repos. It’s a consequence of [this line](https://github.com/puppetlabs/homebrew-puppet/blob/master/Casks/puppet-agent.rb#L22). It tries to use the interpolated `version`, but `version` is unset because your there’s no case for `10.14`.

It needs to be fixed on their end. I’d submit a PR, but I’m unsure how they want to handle it (and since the casks are officially theirs, they’ll know). They don’t allow issues on that repo, and have [a specific ticketing system](https://tickets.puppetlabs.com/) that requires an account. You should inform them through there.

Feel free to link them back to this post in case further assistance is needed.

**Comment by vitorgalvao** [comment]
> buo/cask-upgrade

Not sure you’re aware (many users still are not) but we’ve finally added native support for `brew cask upgrade`.

**Comment by rafilkmp3** [comment]
@vitorgalvao but there is any way to me remove this package from my system? I prefer remove until fixed against live without cask

**Comment by rafilkmp3** [comment]
@vitorgalvao  i tried to put what you said but I am still having the same error.

```
 depends_on macos: '>= 10.10'
  url "https://downloads.puppet.com/mac/puppet5/10.13/x86_64/puppet-agent-5.6-1.osx10.13.dmg"
  pkg "puppet-agent-5.6-1-installer.pkg"

  name 'Puppet Agent'
```

**Comment by vitorgalvao** [comment]
@rafilkmp3 What’s that code block?

**Comment by rafilkmp3** [comment]
I removed the first "case statement without do a backup and this is now my file. and I still cant use the cask :(
 ```
cat /usr/local/Caskroom/puppet-agent/.metadata/5.5.6/20180827192947.184/Casks/puppet-agent.rb
 depends_on macos: '>= 10.10'
  url "https://downloads.puppet.com/mac/puppet5/10.13/x86_64/puppet-agent-5.6-1.osx10.13.dmg"
  pkg "puppet-agent-5.6-1-installer.pkg"

  name 'Puppet Agent'
  homepage "https://puppet.com/docs/puppet/10/about_agent.html"

  uninstall launchctl: [
                         'puppet',
                         'pxp-agent',
                         'mcollective',
                       ],
            pkgutil:   'com.puppetlabs.puppet-agent'

  zap trash: [
               '~/.puppetlabs',
               '/etc/puppetlabs',
             ]
end
```

**Comment by vitorgalvao** [comment]
> I removed the first "case statement

You were only supposed to change the `homepage` and leave everything else as was. That cask file is now broken. [Copy the original one](https://github.com/puppetlabs/homebrew-puppet/blob/master/Casks/puppet-agent.rb) to it and change *just* `homepage`. Anything works, you can even do `homepage 'https://example.com'`.

**Comment by vitorgalvao** [comment]
What’s the error you get now?

**Comment by rafilkmp3** [comment]
the same previous one. in any command
```
┗ brew  cask upgrade
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
svgo                                                                            wireguard-tools

Warning: Cask 'puppet-agent' is unreadable: undefined method `major_minor' for nil:NilClass
Error: Cask 'puppet-agent' is unreadable: undefined method `major_minor' for nil:NilClass
```

**Comment by vitorgalvao** [comment]
It may be trying to read the cask outside the `metadata`. To be safe, change all matching casks.

```bash
find "$(brew --prefix)" -name 'puppet-agent.rb'
```

**Comment by rafilkmp3** [comment]
I found another one here, and removed the 'major_minor'and i was able to remove the puppet thanks for this :)
```
find "$(brew --prefix)" -name 'puppet-agent.rb'
/usr/local/Homebrew/Library/Taps/puppetlabs/homebrew-puppet/Casks/puppet-agent.rb
/usr/local/Caskroom/puppet-agent/.metadata/5.5.6/20180827192947.184/Casks/puppet-agent.rb
```
