### ISSUE TITLE
Shouldn't the Duplicati cask depend on the mono brew Formula?

### ISSUE THREAD

**Issue by daften** [Homebrew/homebrew-cask#51884]
### Description of feature/enhancement

Now when duplicati is installed, you see a message that mono is required. Brew install mono fixes this off course, but shouldn't there be a simple depends_on in the cask?

### Justification

This would make the install a little more seamless and keep everything for Duplicati install nicely inside homebrew

### Example use case

/

I'm asking in an issue to be sure that this isn't done for a specific reason. If it is the way to go, I'll whip up a PR.

**Comment by vitorgalvao** [comment]
If it needs it, it needs it. No reason I recall on why it didn’t have it already (maybe it didn’t need it when it was first added?). You can go ahead with the PR.
