### ISSUE TITLE
Installing `obs` prompts for unknown password

### ISSUE THREAD

**Issue by alexreg** [Homebrew/homebrew-cask#52035]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I try to install the `obs` cask, but during the installation it prompts me for a password (like sudo would), but does not accept my usual account password. I have no idea what password it's asking for.

#### Command that failed

```
brew cask install obs
```

#### Output of command with `--force --verbose --debug`

```
$ brew cask install --force --verbose --debug obs
Updating Homebrew...
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://cdn-fastly.obsproject.com/downloads/obs-mac-22.0.3-installer.pkg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.4-58-gbde49f5\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --location --silent --head https://cdn-fastly.obsproject.com/downloads/obs-mac-22.0.3-installer.pkg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.4-58-gbde49f5\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --location --silent --head https://cdn-fastly.obsproject.com/downloads/obs-mac-22.0.3-installer.pkg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.4-58-gbde49f5\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --fail --location --remote-time --continue-at 0 --output /var/folders/sh/xb5grs3d247c0cxy_7s57_2r0000gk/T/brewdo.685tY82h/Library/Caches/Homebrew/downloads/c1a85c08882419958f9842ab729689fc2e67a29ccba12fd8c9f35adc4b289176--obs-mac-22.0.3-installer.pkg.incomplete https://cdn-fastly.obsproject.com/downloads/obs-mac-22.0.3-installer.pkg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  109M  100  109M    0     0  3944k      0  0:00:28  0:00:28 --:--:-- 3949k
==> Checking quarantine support
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /var/folders/sh/xb5grs3d247c0cxy_7s57_2r0000gk/T/brewdo.685tY82h/Library/Caches/Homebrew/downloads/c1a85c08882419958f9842ab729689fc2e67a29ccba12fd8c9f35adc4b289176--obs-mac-22.0.3-installer.pkg
/usr/bin/xattr -p com.apple.quarantine /var/folders/sh/xb5grs3d247c0cxy_7s57_2r0000gk/T/brewdo.685tY82h/Library/Caches/Homebrew/downloads/c1a85c08882419958f9842ab729689fc2e67a29ccba12fd8c9f35adc4b289176--obs-mac-22.0.3-installer.pkg
==> /var/folders/sh/xb5grs3d247c0cxy_7s57_2r0000gk/T/brewdo.685tY82h/Library/Caches/Homebrew/downloads/c1a85c08882419958f9842ab729689fc2e67a29ccba12fd8c9f35adc4b289176--obs-mac-22.0.3-installer.pkg is not quarantined
==> Quarantining /var/folders/sh/xb5grs3d247c0cxy_7s57_2r0000gk/T/brewdo.685tY82h/Library/Caches/Homebrew/downloads/c1a85c08882419958f9842ab729689fc2e67a29ccba12fd8c9f35adc4b289176--obs-mac-22.0.3-installer.pkg
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift /var/folders/sh/xb5grs3d247c0cxy_7s57_2r0000gk/T/brewdo.685tY82h/Library/Caches/Homebrew/downloads/c1a85c08882419958f9842ab729689fc2e67a29ccba12fd8c9f35adc4b289176--obs-mac-22.0.3-installer.pkg https://cdn-fastly.obsproject.com/downloads/obs-mac-22.0.3-installer.pkg https://obsproject.com/
==> Downloaded to -> /var/folders/sh/xb5grs3d247c0cxy_7s57_2r0000gk/T/brewdo.685tY82h/Library/Caches/Homebrew/downloads/c1a85c08882419958f9842ab729689fc2e67a29ccba12fd8c9f35adc4b289176--obs-mac-22.0.3-installer.pkg
==> Verifying SHA-256 checksum for Cask 'obs'.
==> Installing Cask obs
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Pkg for /var/folders/sh/xb5grs3d247c0cxy_7s57_2r0000gk/T/brewdo.685tY82h/Library/Caches/Homebrew/downloads/c1a85c08882419958f9842ab729689fc2e67a29ccba12fd8c9f35adc4b289176--obs-mac-22.0.3-installer.pkg
cp -p /var/folders/sh/xb5grs3d247c0cxy_7s57_2r0000gk/T/brewdo.685tY82h/Library/Caches/Homebrew/downloads/c1a85c08882419958f9842ab729689fc2e67a29ccba12fd8c9f35adc4b289176--obs-mac-22.0.3-installer.pkg /usr/local/Caskroom/obs/22.0.3/obs-mac-22.0.3-installer.pkg
==> Verifying Gatekeeper status of /var/folders/sh/xb5grs3d247c0cxy_7s57_2r0000gk/T/brewdo.685tY82h/Library/Caches/Homebrew/downloads/c1a85c08882419958f9842ab729689fc2e67a29ccba12fd8c9f35adc4b289176--obs-mac-22.0.3-installer.pkg
/usr/bin/xattr -p com.apple.quarantine /var/folders/sh/xb5grs3d247c0cxy_7s57_2r0000gk/T/brewdo.685tY82h/Library/Caches/Homebrew/downloads/c1a85c08882419958f9842ab729689fc2e67a29ccba12fd8c9f35adc4b289176--obs-mac-22.0.3-installer.pkg
==> /var/folders/sh/xb5grs3d247c0cxy_7s57_2r0000gk/T/brewdo.685tY82h/Library/Caches/Homebrew/downloads/c1a85c08882419958f9842ab729689fc2e67a29ccba12fd8c9f35adc4b289176--obs-mac-22.0.3-installer.pkg is quarantined
==> Propagating quarantine from /var/folders/sh/xb5grs3d247c0cxy_7s57_2r0000gk/T/brewdo.685tY82h/Library/Caches/Homebrew/downloads/c1a85c08882419958f9842ab729689fc2e67a29ccba12fd8c9f35adc4b289176--obs-mac-22.0.3-installer.pkg to /usr/local/Caskroom/obs/22.0.3
/usr/bin/xattr -p com.apple.quarantine /var/folders/sh/xb5grs3d247c0cxy_7s57_2r0000gk/T/brewdo.685tY82h/Library/Caches/Homebrew/downloads/c1a85c08882419958f9842ab729689fc2e67a29ccba12fd8c9f35adc4b289176--obs-mac-22.0.3-installer.pkg
/bin/chmod -R u\+w /usr/local/Caskroom/obs/22.0.3
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5b9d85c0\;Homebrew\\x20Cask\;8809422F-5EAE-4C44-BB59-EBC9F5CE7F02
==> Creating metadata directory /usr/local/Caskroom/obs/.metadata/22.0.3/20180915222053.462.
==> Creating metadata subdirectory /usr/local/Caskroom/obs/.metadata/22.0.3/20180915222053.462/Casks.
==> Installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x000000010185c990>
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for obs; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
/usr/bin/sudo -E -- env LOGNAME=_homebrew USER=_homebrew USERNAME=_homebrew /usr/sbin/installer -pkg /usr/local/Caskroom/obs/22.0.3/obs-mac-22.0.3-installer.pkg -target / -verboseR
Password:
Sorry, try again.
Password:
Sorry, try again.
Password:
sudo: 3 incorrect password attempts
==> Purging files for version 22.0.3 of Cask obs
Error: Failure while executing; `/usr/bin/sudo -E -- env LOGNAME=_homebrew USER=_homebrew USERNAME=_homebrew /usr/sbin/installer -pkg /usr/local/Caskroom/obs/22.0.3/obs-mac-22.0.3-installer.pkg -target / -verboseR` exited with 1. Here's the output:
Sorry, try again.
Sorry, try again.
sudo: 3 incorrect password attempts


Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:101:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:46:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:23:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:58:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:64:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:50:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:31:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:207:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:199:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:96:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
1.7.4-58-gbde49f5
==> macOS
10.13.6
==> SIP
Disabled
==> Java
1.8.0_60
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4050 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/bin/false"
```

#### Output of `brew tap`

```
alexreg/utilities
beeftornado/rmtree
burntsushi/ripgrep
heroku/brew
homebrew/boneyard
homebrew/bundle
homebrew/cask
homebrew/completions
homebrew/core
homebrew/dupes
homebrew/fuse
homebrew/games
homebrew/science
homebrew/services
homebrew/tex
homebrew/versions
homebrew/x11
theseal/ssh-askpass
```

**Comment by reitermarkus** [comment]
I cannot reproduce this.

Your cache is `/var/folders/sh/xb5grs3d247c0cxy_7s57_2r0000gk/T/brewdo.685tY82h/Library/Caches/Homebrew` and your user is `_homebrew`. How are you running Homebrew exactly?

**Comment by alexreg** [comment]
@reitermarkus Using [brewdo](https://github.com/zigg/brewdo). Works just fine with normal brew (not brew cask). I've just noticed a similar issue as this one occurs for some other casks (but not all).

**Comment by reitermarkus** [comment]
Given that `brewdo` is unmaintained and this isn't reproducible you'll have to figure this out yourself.

**Comment by alexreg** [comment]
@reitermarkus No, it's not unmaintained. I help maintain it myself. Anyway I find your reply very unhelpful. Why not put some effort into fixing cask, when it's clearly a shortcoming of your software?

**Comment by reitermarkus** [comment]
> No, it's not unmaintained.

The ReadMe says 

> This project is unmaintained and unsupported, and likely has issues.

> Anyway I find your reply very unhelpful.

I can't help you if I can't reproduce the issue.

> Why not put some effort into fixing cask, when it's clearly a shortcoming of your software?

We don't work for you, so we don't owe you anything. You're free to send a PR to fixing this issue.

**Comment by vitorgalvao** [comment]
@alexreg I’m confident the logic @reitermarkus applied is the same I would, so allow me to interject. First, consider the case from out point of view. We get literally dozens of *daily* issues/PRs, for something we’re doing for free with no reward (or expectation of one).

This makes it so we have to triage problems quickly and decide which ones to pursue at any given time. That’s why the issue template even demands you certify you’re aware your issue may be closed without review if you don’t fill it — when a user cuts corners and decides to save themselves a few minutes, they’re wasting hours of our time in a needless back-and-forth to get all the information. Similarly, if a user is rude without provocation, they’re draining out mental fortitude to keep contributing. I’ll make clear *none of these was the case with you, they’re examples of other situations*.

But here’s another example. When an issue can’t be reliably reproduced by a maintainer (especially if tried on a clean VM), then the issue is most likely to lie within the user’s personal configuration. So that means that to help that user, a maintainer is no longer *maintaining the software*, but instead *providing free tech support*, which is not the goal of open-source. Furthermore, if the user has a configuration so specific that it’s unlikely many others have it, dedicating maintainer time to it may mean hours or even days of completely wasted maintainer time, as none of it was spent meaningfully improving the software: whatever workaround devised for that user’s particular problem would only help a tiny subset of users.

For a user to get maintainer help with such a specific case, at the very least it’s their duty to investigate to the point where they can figure out the exact state that reproduces the problem, so further probing can take place. But do understand that even then a maintainer has no obligation to help, it only makes them likelier to.

> But you didn't even make a serious effort to (e.g. trying with brewdo)

Because, as explained, it’s essentially defunct software. It hasn’t had commits in years and says right in the README that it’s unmaintained. Abandoned software only loses users, which means time spent hacking around it will only bring diminishing returns.

> As a maintainer though, I would expect more interest in getting the software to work for more people, however, rather than the clichéd "doesn't work for me" attitude.

What this all means is that spending time on your specific problem would not in practice make the software work for more people. Rather, it would take away from working on other more pressing problems that would in fact accomplish that.

As for the time I spent writing this reply, I find it worth it because now I have a well written response I can link to in similar cases.

I hope the explanation was acceptable to you, and has elucidated the inner workings of the project.

**Comment by alexreg** [comment]
@vitorgalvao Thank you for your clarification. And yes, though it may seem like a rather long reply, you've set out your points fairly, and as you say, much of it can be reused easily in other situations.

In this case I would have appreciated if @reitermarkus had said outright something like "running brew not as the current user" is not officially supported. (I know it's never been supported to run it as the super user, but that's a slightly different matter.) Anyway, I'm sorry if I came off antagonistic, @reitermarkus. Hopefully I can by myself get brewdo working again with cask, and get a PR accepted here too as part of that, if the situation demands it. I'll try to remember to report back here if I do!

**Comment by vitorgalvao** [comment]
> In this case I would have appreciated if @reitermarkus had said outright something like "running brew not as the current user" is not officially supported.

That’s good to know in hindsight. For reasonable users, like you seem to be, there’s usually one good argument that makes our point across. The problem is we don’t know which one it is (or if the user is reasonable)!

Also note the situation could be entirely reversed. You could have gotten a more rushed explanation from me an insightful one from @reitermarkus. It just so happens he was the first to reply and was probably doing a ton of things at the same time. When I’m reviewing a bunch of issues/PRs in a row, sometimes my replies can seem curt.
