### ISSUE TITLE
invalid option: --caskroom=/usr/local/Caskroom

### ISSUE THREAD

**Issue by busyfree** [Homebrew/homebrew-cask#52091]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue
run brew cask command occur an error,invalid option: --caskroom=/usr/local/Caskroom

below is versions of system and applications

```
OS
macOS High Sierra 10.13.6

ruby
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

brew 
Homebrew 1.7.4
Homebrew/homebrew-core (git revision 29c4cf; last commit 2018-09-17)
Homebrew/homebrew-cask (git revision 020b; last commit 2018-09-17)
```

#### Command that failed

```
brew cask doctor
```

#### Output of command with `--force --verbose --debug`

```
Error: invalid option: --caskroom=/usr/local/Caskroom
/usr/local/Homebrew/Library/Homebrew/cask/cmd/options.rb:60:in `process_arguments'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:41:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/doctor.rb:10:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of `brew cask doctor`

```
Error: invalid option: --caskroom=/usr/local/Caskroom
```

#### Output of `brew tap`

```
Updating Homebrew...
heroku/brew
homebrew/cask
homebrew/core
homebrew/dupes
homebrew/php
homebrew/services
homebrew/versions
loadimpact/k6
vapor/tap
```

**Comment by reitermarkus** [comment]
Do you have `HOMEBREW_CASK_OPTS` set?

**Comment by busyfree** [comment]
> Do you have `HOMEBREW_CASK_OPTS` set?

Yes
export HOMEBREW_CASK_OPTS="--appdir=/Applications --caskroom=/usr/local/Caskroom"

**Comment by reitermarkus** [comment]
You'll have to remove the `--caskroom` option from `HOMEBREW_CASK_OPTS`.
