### ISSUE TITLE
You have some kind of spam on caskroom.io - has it been hacked? (screenshot attached)

### ISSUE THREAD

**Issue by george43g** [Homebrew/homebrew-cask#52119]
So I went on google to try to find the cask search webpage I always use

I found caskroom.io ("brew cask search")

I've attached a screenshot of what I found on the site, and furthermore, the search isn't working/loading at all.

<img width="1313" alt="screen shot 2018-09-18 at 12 48 49 pm" src="https://user-images.githubusercontent.com/11027390/45661793-66b25900-bb42-11e8-8731-6dbdde151cea.png">

EDIT: forgot to mention, the issue is specifically a link (in broken english) to a website that sells instagram followers... (under Android & iOS)

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/issues/51050
https://github.com/Homebrew/homebrew-cask/issues/51928
https://github.com/Homebrew/homebrew-cask/issues/51167
