### ISSUE TITLE
Vitalsource Bookshelf versions

### ISSUE THREAD

**Issue by joelstudler** [Homebrew/homebrew-cask#52137]
Please update the bookshelf cask to install the newest version on macOS 10.10+

https://github.com/Homebrew/homebrew-cask/blob/master/Casks/vitalsource-bookshelf.rb
https://support.vitalsource.com/hc/en-us/articles/201344733-Bookshelf-Download-Page

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/52150
