### ISSUE TITLE
Was your website hacked? There is ad spam in the middle of it.

### ISSUE THREAD

**Issue by nathancarter** [Homebrew/homebrew-cask#52164]
In the middle of otherwise technical content on [caskroom.io](http://caskroom.io) is the following content linking to a site that wants to sell you more Instagram followers.  I'm assuming this was not intentional, and that you would want to remove it.

<img width="974" alt="screen shot 2018-09-18 at 9 44 18 pm" src="https://user-images.githubusercontent.com/1316622/45715449-34c5e480-bb8c-11e8-8951-e1bf361b64e2.png">

**Comment by vitorgalvao** [comment]
#51050
#51928
#51167
#52119
