### ISSUE TITLE
Update openemu

### ISSUE THREAD

**Issue by xhaythemx** [Homebrew/homebrew-cask#52218]
Update openemu

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/52224

**Comment by vitorgalvao** [comment]
@xhaythemx Next time, please make a more complete bug report. At the very least give us the new version and the download URL.

Better yet, submitting a PR yourself is literally [one command away](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).
