### ISSUE TITLE
Error: Calling the `license` stanza is disabled! There is no replacement.

### ISSUE THREAD

**Issue by brileyd** [Homebrew/homebrew-cask#52252]
#### General troubleshooting steps

- [X] I have retried my command with `--force` and the issue is still present.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

{{
I attempted to search for pgp and gpg and I get the following error: 
myMBP~ - [09/20/18 11:57:57]:brew search gpg
Error: Calling the `license` stanza is disabled! There is no replacement.
Please report this to the goldcaddy77/firefox tap:
  /usr/local/Homebrew/Library/Taps/goldcaddy77/homebrew-firefox/Casks/firefox-48.rb:9

I did update command line tools yesterday, so that may be a factor.

I know the version of Firefox referred to in the error is out of date, but I use it only for testing and I really need to keep that version.  Is it possible to ignore this error and skip it?
}}

#### Command that failed

```
{{
brew search gpg
brew search pgp
brew cask list
}}
```

#### Output of command with `--force --verbose --debug`

```
{{
myMBP~ - [09/20/18 12:00:04]:brew search gpg --force --verbose --debug
Error: invalid option: --force
/usr/local/Homebrew/Library/Homebrew/cli_parser.rb:82:in `parse'
/usr/local/Homebrew/Library/Homebrew/cli_parser.rb:9:in `parse'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:45:in `search'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
}}
```

#### Output of `brew cask doctor`

```
{{
myMBP~ - [09/20/18 12:02:34]:brew cask doctor
==> Homebrew Version
1.7.5-51-g8125aba
==> macOS
10.13.6
==> SIP
Enabled
==> Java
1.8.0_152, 1.7.0_79, 1.6.0_65-b14-468
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4041 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1175 casks)
/usr/local/Homebrew/Library/Taps/goldcaddy77/homebrew-firefox (16 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
}}
```

#### Output of `brew tap`

```
{{
MBP~ - [09/20/18 12:03:47]:brew tap
goldcaddy77/firefox
homebrew/cask
homebrew/cask-fonts
homebrew/core
homebrew/dupes
homebrew/python
}}
```

**Comment by alebcay** [comment]
You should use [this fork of `homebrew-firefox` instead](https://github.com/asmod3us/homebrew-firefox), which seems to have the offending `license` stanzas removed and thus this error won't occur.

**Comment by brileyd** [comment]
That resolved my issue.  Thanks!
