### ISSUE TITLE
Failed to exexute `brew cask install imazing`, the download url is invalid 

### ISSUE THREAD

**Issue by gnillor** [Homebrew/homebrew-cask#52298]
Hi,
I have tried to run `brew cask install imazing`, but get the following error:
```
==> Caveats
Performing a zap on this cask removes files pertaining to both imazing
and imazing-mini, so it should not be done if you only want to uninstall one of them.

==> Satisfying dependencies
==> Downloading https://dl.devmate.com/com.DigiDNA.iMazing2Mac/9517/1537292305/iMazing2forMac-9517.dmg

curl: (22) The requested URL returned error: 404 
Error: Download failed on Cask 'imazing' with message: Download failed: https://dl.devmate.com/com.DigiDNA.iMazing2Mac/9517/1537292305/iMazing2forMac-9517.dmg
```

When I open the download url with Chrome, then got the below information:
```
404 Not Found
Code: NoSuchKey
Message: The specified key does not exist.
Key: com.DigiDNA.iMazing2Mac/9517/1537292305/iMazing2forMac-9517.dmg
RequestId: 97BA0449B3ED64D0
HostId: dX5nGOneJz/YuaF9arl0sTV4NH2kwGEzQPdC+4RLB2Neai7930n7zATh6mi9rFNhohazvOIjjxY=
```

Do you have any idea to fix this error? thanks!

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
