### ISSUE TITLE
unofficial fork used for eloston-chromium.rb

### ISSUE THREAD

**Issue by vemv** [Homebrew/homebrew-cask#52351]
https://github.com/Homebrew/homebrew-cask/blob/793890ef88e77f197e7d4f504e51402960923b2b/Casks/eloston-chromium.rb says something which is literally false:

> github.com/tectiv3/ungoogled-chromium-binaries was verified as official when first introduced to the cask

* tectiv3/ungoogled-chromium-binaries is not official, ungoogled-software/ungoogled-chromium-binaries is.
* the `when _first_ introduced to the cask` bit is also false. There have been three sources throughout the history of the cask.

I'm not very interested in this Cask (the official source is also 'unofficial' in a way: anyone can send binaries), but a general trend I sadly see in homebrew-cask is that the 'official check' appears to be an ambiguous concept.

I'd appreciate a clarification on the topic; and more generally perhaps users + contributors will benefit from a FAQ explaining it well.

Thanks - Victor

**Comment by commitay** [comment]
> https://github.com/Homebrew/homebrew-cask/blob/793890ef88e77f197e7d4f504e51402960923b2b/Casks/eloston-chromium.rb says something which is literally false:

`ungoogled-software/ungoogled-chromium-binaries` points to `tectiv3/ungoogled-chromium-binaries`

> when _first_ introduced to the cask

This is correct, the `url` was verified as official when it was first introduced to the cask. i.e. if the `url` changes, it will be verified again before it is merged.
