### ISSUE TITLE
Documentation: sha256 manpage link taken down

### ISSUE THREAD

**Issue by numbermaniac** [Homebrew/homebrew-cask#52482]
#### Description of issue

At [Updating the SHA256](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256), it says "If the Cask is an .app that is codesigned...". The word "codesigned" links to https://developer.apple.com/library/archive/documentation/Darwin/Reference/ManPages/man1/codesign.1.html, but this URL does not exist.

It appears the manpage section of their site [has been taken down](https://apple.stackexchange.com/questions/239484/does-apple-provide-a-web-site-with-content-of-man-pages-for-the-command-line-c#comment424789_239485).

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/52500
