### ISSUE TITLE
Ability to install Xquartz with Xinerama addon

### ISSUE THREAD

**Issue by npyl** [Homebrew/homebrew-cask#52503]
### Description of feature/enhancement

Add the ability to install Xinerama addon during Xquartz installation

### Justification

I am developing a port of conky for macOS and realised that Homebrew-Cask provides a really convenient way to install Xquartz (you don't have to go to website, download, open installer package, ... so on...).  Problem is, conky has the ability to use Xinerama addon for multiple displays support and homebrew's xquartz doesn't have it.

### Example use case

A `--with-xinerama` option seems to me like an ideal solution:
`brew cask install xquartz --with-xinerama`

Thank you

**Comment by vitorgalvao** [comment]
> A `--with-xinerama` option seems to me like an ideal solution

We don’t support install flags, so this is not an option.

If you find a way to do it, you should consider hosting your own [tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md). This isn’t a feature many users would want, so we won’t support it officially.
