### ISSUE TITLE
gisto checksum mismatch

### ISSUE THREAD

**Issue by y0y0z** [Homebrew/homebrew-cask#52587]
this what happens when i try to install gisto
```bash
$ brew update
$ brew cask install gisto
...
==> Verifying SHA-256 checksum for Cask 'gisto'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'gisto' does not match.

Expected: 1435b12c75777a97ddd3e28577fcd54247015326954e6aebb1befb72f2e5f66c
Actual:   e3def1a5950b3c34db6393e8e78316445311f00079e073fc875876b21f5e1a0b
File:     /Users/geek/Library/Caches/Homebrew/downloads/a9d4e5c96fbe18c0290b1317b52d49034ecaf334042e1d171efd4d5013b09e11--Gisto-1.10.5.dmg
```

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
