### ISSUE TITLE
paragon-extfs dl link incorrect

### ISSUE THREAD

**Issue by chrismartintx** [Homebrew/homebrew-cask#52779]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

New version of application due to Mojave release.  Link + ${verNo} no longer naming convention used by vendor.

http://dl.paragon-software.com/demo/trial_extfs.dmg
updated link

#### Command that failed

```
url "http://dl.paragon-software.com/demo/trial_extfs#{version}.dmg"
```

#### Output of command with `--force --verbose --debug`

```
{{replace this}}
```

#### Output of `brew cask doctor`

```
{{replace this}}
```

#### Output of `brew tap`

```
{{replace this}}
```

**Comment by reitermarkus** [comment]
Please [send a pull request updating the link](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#how-to-contribute).
