### ISSUE TITLE
Make a homebrew/cask-java tap?

### ISSUE THREAD

**Issue by commitay** [Homebrew/homebrew-cask#52875]
Current casks:

- `java`: OpenJDK 11
- `adoptopenjdk` JDK 11
- `oracle-jdk`: OracleJDK 11
- `zulu`: ZuluJDK 10
- `java8`: OracleJDK 8 (versions)
- `java10`: OracleJDK 10 (versions)
- `zulu7`: ZuluJDK 7 (versions)
- `zulu8`: ZuluJDK 8 (versions)
- `zulu9`: ZuluJDK 9 (versions)

Related cask: `java-jdk-javadoc`

Open PRs:
- `sapmachine-jdk` JDK 11
- `adoptopenjdk9 ` JDK 9 (versions)

Forthcoming PRs:
- `adoptopenjdk` 8/10 (versions)

Dumping these all in one tap would make them easier to manage (naming/avoiding duplicates, postflight consistency/avoiding install conflicts, etc.) I'm expecting more variants now that building JDKs is a thing.

**Comment by commitay** [comment]
Forgot that we don't have tap migrations, doing this will break to many installs. Closing.

**Comment by commitay** [comment]
Reopening as it might be worthwhile to implement `tap_migrations` so we can make a Java tap.

**Comment by vitorgalvao** [comment]
I’m neutral on this one. I don’t think an extra tap is warranted, but I’m also not the one that typically manages the `java` casks, so I may not be considering the difficulty.

> I really don't get how having more taps makes them easier to manage

It makes it easier to detect what’s abandoned and what’s managed.

I think I’ve mentioned this before, but I like the idea of directories inside the tap. If that were possible, we could get the benefit of organisation without the disadvantage of extra taps.

**Comment by commitay** [comment]
As all of them are basically hacks using `postflights` to install files, they could all have conflicts in `/Library/Java/JavaVirtualMachines` that need to be checked.

Keeping the postflights consistent, e.g. moving rather than symlinking and `plist` modifications.

Consistent naming for casks provided by different upstreams and multiple versions provided by the same upstream.

Having them all in one place would make it much easier.

> I like the idea of directories inside the tap

This could work but it wouldn't allow for rules that are tap specific, it would mean adding more rules to this tap.

**Comment by vitorgalvao** [comment]
> This could work but it wouldn't allow for rules that are tap specific, it would mean adding more rules to this tap.

Yes, I don’t mean to replace taps entirely, but as an intermediary step (e.g. qlplugins, audioplugins, the java casks).

**Comment by commitay** [comment]
> qlplugins, audioplugins

Stuff like this doesn't really have any other issues, the java casks have lots of problems that are specific to them.

**Comment by commitay** [comment]
I've kind of changed my mind on this as:

`brew cask install homebrew/cask-java/java`

is ugly and I think moving only some of the java casks to the tap is pointless.

Closing again, sorry of the noise.

**Comment by gdams** [comment]
@commitay I'd be happy to work with you to try and work out a way to standardize the Java casks and find a suitable solution? Feel free to reach out to be via email or twitter if you're interested in having a chat!

**Comment by bric3** [comment]
Agreed the way that homebrew currently handle java version, or currently do no handle is a pain for developers. Some need multiple versions of java at a time. Currently this is impossible to do properly with homebrew only at this time. 

This is both confusing and frustrating user experience. A solution that is fine too could be to just not use homebrew to handle java versions, but that should be advertised like pointing to https://github.com/sdkman.
