### ISSUE TITLE
dotnet package and dotnet-sdk conflict when upgrading

### ISSUE THREAD

**Issue by portalmafia** [Homebrew/homebrew-cask#53044]
### Justification
I think dotnet package is unnecessary because it causes conflicts with dotnet-sdk, so it's impossible to upgrade the SDK package with both packages installed, brew always complain about conflict when upgrading. The dotnet-sdk must says that it cames with dotnet RUN Time too, if my logic is correct.

### Example use case

``` brew cask install dotnet-sdk```

* Would be enough to install both dotnet-sdk and client run-time , since only installing dotnet-sdk it cames with the command embebed"dotnet".
* A better information about the package telling that it cames with runtime + sdk if my assumption is correct about the Run Time package (its only a command with all that featurse).

### Conclusion

 ``` brew cask install dotnet-sdk```
* Cames with dotnet command, so I really don't need the dotnet package right? 
* So at least the information should be upgraded about it.

**Comment by remi-debette** [comment]
Same issue.
Could we have a clear explanation on what are the steps required not to get 
`Error: Cask 'dotnet-sdk' conflicts with 'dotnet'.`

(Whether it means installing only one of the two or not)

Thank you

**Comment by ansonhoyt** [comment]
Just wanted to add, this is a new problem. I've had these dotnet packages installed for maybe a year, and have done many successful `brew cask upgrade` runs. Only ran into this error recently (last couple of weeks?).

```
$ brew cask upgrade
==> Casks with `auto_updates` or `version :latest` will not be upgraded
==> Upgrading 1 outdated package:
dotnet-sdk 2.1.402 -> 2.1.403
==> Purging files for version 2.1.403 of Cask dotnet-sdk
Error: Cask 'dotnet-sdk' conflicts with 'dotnet'.
```

**Comment by ansonhoyt** [comment]
Looks like it breaks since https://github.com/Homebrew/homebrew-cask/pull/52524. This added `conflicts-with` to `dotnet` and `dotnet-sdk` casks. @yurikoles responded with an (light) explanation on the pull request.

**Comment by reitermarkus** [comment]
The solution is to uninstall one of the two, as explained in https://github.com/Homebrew/homebrew-cask/pull/52524.
