### ISSUE TITLE
Java cask names: java vs. oracle-jdk

### ISSUE THREAD

**Issue by Det87** [Homebrew/homebrew-cask#53062]
Since the 'java' cask was apparently [changed](https://github.com/Homebrew/homebrew-cask/commit/c02425d0577eda56db18350cf58855bc396512e7) to OpenJDK, and there's no "JRE" anymore, should the _oracle-jdk_ be renamed to _oracle-java_ or something?

**Comment by commitay** [comment]
`oracle-jdk` is what upstream refers to it as.

https://blogs.oracle.com/java-platform-group/oracle-jdk-releases-for-java-11-and-later

**Comment by commitay** [comment]
The `java` casks are used internally by Homebrew and point to the default versions that can fufill the Java requirement, `java` for 9+ and `java8` for 1.8.
