### ISSUE TITLE
brew cask upgrade -> header line does not match file name

### ISSUE THREAD

**Issue by WeirdCircumstances** [Homebrew/homebrew-cask#53079]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command. (Found another bug doing this)
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Doing an cask upgrade results in  
`Error: Cask 'anaconda2' definition is invalid: Token '{:v1_1=>"anaconda2"}' in header line does not match the file name.` 

I can not uninstall, reinstall or rename it. Upgrading results every time in this error. 

#### Command that failed

```
brew cask upgrade
```

#### Output of command with `--force --verbose --debug`

```
Error: Cask 'anaconda2' definition is invalid: Token '{:v1_1=>"anaconda2"}' in header line does not match the file name.
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:74:in `cask'
/usr/local/Homebrew/Library/Homebrew/compat/cask/cask_loader.rb:15:in `cask'
/usr/local/Caskroom/anaconda2/.metadata/2.4.0/20151123205125.794/Casks/anaconda2.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:60:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:60:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:180:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:36:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:32:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:32:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of `brew cask doctor`

```
brew cask doctor
==> Homebrew Version
1.7.6-143-gc6acab6
==> macOS
10.14
==> SIP
Enabled
==> Java
10.0.2
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4032 casks)
/usr/local/Homebrew/Library/Taps/phinze/homebrew-cask (4032 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (204 casks)
/usr/local/Homebrew/Library/Taps/cpbotha/homebrew-marmaduke-chromium (2 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
cpbotha/marmaduke-chromium
gapple/services
homebrew/cask
homebrew/cask-versions
homebrew/core
homebrew/dupes
homebrew/fuse
homebrew/games
homebrew/python
homebrew/science
homebrew/versions
hukl/tap
josegonzalez/php
phinze/cask
```

**Comment by reitermarkus** [comment]
Which tap is the `anaconda2` cask from? Report this there or untap it, since this cask is very outdated.

**Comment by WeirdCircumstances** [comment]
Ok, tried `brew cask install anaconda2 --force`, same result:
`$ brew cask install anaconda2 --force
Error: Cask 'anaconda2' definition is invalid: Token '{:v1_1=>"anaconda2"}' in header line does not match the file name.`

I removed all deprecated taps (tried upgrade afterwards as well):
`brew tap
Updating Homebrew...
homebrew/cask
homebrew/core
hukl/tap
josegonzalez/php`

Afterwards still:
`brew cask upgrade --force --verbose --debug
Updating Homebrew...
Error: Cask 'anaconda2' definition is invalid: Token '{:v1_1=>"anaconda2"}' in header line does not match the file name.
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:74:in `cask'
/usr/local/Homebrew/Library/Homebrew/compat/cask/cask_loader.rb:15:in `cask'
/usr/local/Caskroom/anaconda2/.metadata/2.4.0/20151123205125.794/Casks/anaconda2.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:60:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:60:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:36:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:30:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:30:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:16:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:49:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:15:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'`

**Comment by WeirdCircumstances** [comment]
Started all over (uninstalled brew, reinstalled brew). Now it works. I think I cleaned everything a bit :)

Thanks!
