### ISSUE TITLE
muzzle 1.5 sha256 hash incorrect

### ISSUE THREAD

**Issue by kogent** [Homebrew/homebrew-cask#53081]
### Description of issue

PR #52980 updated muzzle to 1.5 but set the hash to a value that is different than the file that was downloaded.  If the hash on muzzleapp.com is correct then this needs to be `e76e5f5358e8749e7fe2294fee3717ac7327e79eff227430bf3d8f601684a0e6`

### Command that failed

```
brew cask install muzzle
```

### General troubleshooting steps

```bash
brew update && brew cask install muzzle
```

```
==> Satisfying dependencies
==> Downloading https://muzzleapp.com/binaries/muzzle.zip
Already downloaded: /Users/mcarey/Library/Caches/Homebrew/downloads/5774807681fd299cec397fd730c1ca61e2818da8104c84a57b54c349aad13922--muzzle.zip
==> Verifying SHA-256 checksum for Cask 'muzzle'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'muzzle' does not match.

Expected: 2f3c3c839787408d5b991651b5ba25323a12904b4d155e8074f68e7afea3f845
Actual:   e76e5f5358e8749e7fe2294fee3717ac7327e79eff227430bf3d8f601684a0e6
File:     /Users/mcarey/Library/Caches/Homebrew/downloads/5774807681fd299cec397fd730c1ca61e2818da8104c84a57b54c349aad13922--muzzle.zip

To retry an incomplete download, remove the file above.
```

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
