### ISSUE TITLE
Approving VirtualBox kext on Mac OS 10.13 High Sierra

### ISSUE THREAD

**Issue by bval** [Homebrew/homebrew-cask#53147]
Opening and then immediately closing this issue to document for folks having trouble approving the VirtualBox kexts in Mac OS 10.13 High Sierra that if you use any other apps or kexts that intercept mouse input, that other app or kext could cause OS X to ignore your clicking on Allow in System Preferences. You can read more about the issue and potential workarounds in tekezo/Karabiner-Elements#1017.

Tagging #39369 for anyone following those instructions but still not able to load those kexts.

**Comment by nicksloan** [comment]
You should also try using the tab key to select the button and pressing space to accept. That worked for me.
