### ISSUE TITLE
onyx sha256 is wrong

### ISSUE THREAD

**Issue by blacktop** [Homebrew/homebrew-cask#53593]
```
==> Upgrading onyx to 3.5.1
==> Satisfying dependencies
==> Downloading https://www.titanium-software.fr/download/1014/OnyX.dmg
Already downloaded: /Users/blacktop/Library/Caches/Homebrew/downloads/d56f2558efa98db9bd6498d928c165a0b5606c0b42d952b08902ba33705ca379--OnyX.dmg
==> Verifying SHA-256 checksum for Cask 'onyx'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'onyx' does not match.

Expected: 60e4f56fb2e5457aca1aa1d2a9be95502a310b0de75112e91b7c89bf4a2be829
Actual:   ce58fafd9fa25a91f0b7aeb54e6e0b35073c4f2ed9aa1c2e8ce169c7b413d3dc
```

**Comment by gjherbiet** [comment]
It looks like it hasn't been updated from OnyX 3.4.9 hash.
Hashed are published on Onyx download page: https://www.titanium-software.fr/en/onyx.html

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
