### ISSUE TITLE
unidentified developer - ONLY through brew cask

### ISSUE THREAD

**Issue by lantrix** [Homebrew/homebrew-cask#53741]
#### Description of issue

The app works perfectly, and this isn't a cask or feature request.
I searched the other issues and they don't seem to discuss this.

I find it strange that when I download `4.0.6` of gitkraken from their site the app is signed by the developer, and tells me as such.

When I download the SAME app via cask it gives me the known "[The app can’t be opened because it is from an unidentified developer](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/the_app_cant_be_opened.md)"

**Comment by wpiekutowski** [comment]
I'm experiencing a related problem with multiple apps. Whenever I open such an app (not only the first time), I'm getting a progress bar saying "Verifying..." and then a dialog:
![screenshot 2018-10-19 at 20 42 33](https://user-images.githubusercontent.com/612/47238714-544a6a00-d3e3-11e8-80e2-498491ae05d6.png)

Casks affected:
* atom
* firefox
* spectacle
* transmission
* vlc
* google-chrome

Not all casks are affected. It works fine (no dialog, only on the first launch) for:
* veracrypt
* virtualbox

Here's my environment
```
$ brew cask doctor
==> Homebrew Version
1.7.7
==> macOS
10.14
==> SIP
Enabled
==> Java
N/A
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4039 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (203 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
HOMEBREW_CASK_OPTS="--require-sha"
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by vitorgalvao** [comment]
> The app works perfectly, and this isn't a cask or feature request.

No, it’s a bug. Please fill that template.

@wpiekutowski You case is [working as expected](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/the_app_cant_be_opened.md).

**Comment by wpiekutowski** [comment]
Thank you for a quick reply. I'm aware of this FAQ entry, however on 10.14 I see this dialog **every time** I open mentioned apps with:
- right click -> Open -> Open
- double left click
- `open /Applications/Spectacle.app`
- via Spotlight

This doesn't happen if an app is downloaded by user manually and "installed" by moving to /Applications.

Additional observation: My user account doesn't have admin privs ("Standard" account). I have a separate admin user. When I use homebrew, I first `su - admin` and then run various `brew` commands. I'm mentioning this because the only difference I've spotted so far is the ownership of an application directory. When installed with homebrew, it's owned by admin. When installed manually, I get an admin authentication propmpt when moving the app to /Application and after a succesful authentication ownership is set to my standard user. 

Let me know if I should open a new issue about this.

**Comment by lantrix** [comment]
Raised as a proper bug report #54072

**Comment by wpiekutowski** [comment]
Thank you
