### ISSUE TITLE
Casks/jdownloader.rb symlink instead of app / Spotlight problem

### ISSUE THREAD

**Issue by ulab** [Homebrew/homebrew-cask#54117]
### Description of feature/enhancement

After installing the jdownloader cask I noticed that I can not find and open it using Spotlight. Reading through issues I learned that it was a problem with symlinking apps, but other casks worked fine.

Main difference seems to be that other cask are moved to /Applications, but jdownloader is not.

I have no experience with writing Casks, but it seems jdownloader is missing the "app" stanza?

### Justification

Using Spotlight is rather convenient.

### Example use case

`cmd` + `space` `jdownloader` => nothing :-(

**Comment by alagos** [comment]
Same story here. The way I use to run jd2 is going to finder -> applications -> jd2, but it would be way quicker to run it with spotlight.

**Comment by vitorgalvao** [comment]
[Try this](https://github.com/Homebrew/homebrew-cask/pull/54628/files). Does it work?

**Comment by alagos** [comment]
@vitorgalvao I've just tried installing with 
```
$ brew cask uninstall https://raw.githubusercontent.com/Homebrew/homebrew-cask/a0fbb0a7bd1a596e1f2103a1ed2a2f1711422c08/Casks/jdownloader.rb
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/a0fbb0a7bd1a596e1f2103a1ed2a2f1711422c08/Casks/jdownloader.rb.
######################################################################## 100.0%
==> Caveats
jdownloader requires Java 8. You can install it with

  brew cask install homebrew/cask-versions/java8

==> Satisfying dependencies
==> Downloading http://installer.jdownloader.org/clean/JD2Setup.dmg
######################################################################## 100.0%
==> No SHA-256 checksum defined for Cask 'jdownloader', skipping verification.
==> Installing Cask jdownloader
🍺  jdownloader was successfully installed!
```
and it works in spotlight. But if I try to uninstall it with:
```
brew cask uninstall https://raw.githubusercontent.com/Homebrew/homebrew-cask/a0fbb0a7bd1a596e1f2103a1ed2a2f1711422c08/Casks/jdownloader.rb
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-cask/a0fbb0a7bd1a596e1f2103a1ed2a2f1711422c08/Casks/jdownloader.rb.
######################################################################## 100.0%
==> Uninstalling Cask jdownloader
==> Running uninstall process for jdownloader; your password may be necessary
==> Removing files:
/Applications/JDownloader2.app
==> Purging files for version latest of Cask jdownloader
```
Is not removing the app, as it was installed in `/Applications/JDownloader 2.0`, not `/Applications/JDownloader2.app`

**Comment by vitorgalvao** [comment]
@alagos What about [now](https://raw.githubusercontent.com/Homebrew/homebrew-cask/79c2322030b0334b8413c2d811cc724e948e2a0d/Casks/jdownloader.rb)?
