### ISSUE TITLE
Checksum for Cask 'p4v' does not match

### ISSUE THREAD

**Issue by hsuttong** [Homebrew/homebrew-cask#54156]
$ brew cask install p4v
==> Satisfying dependencies
==> Downloading https://cdist2.perforce.com/perforce/r18.3/bin.macosx1013x86_64/P4V.dmg
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'p4v'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'p4v' does not match.

Expected: ff1d378906e22b13d7227fc4b3def17b1ebe957025cefe65e0f2737d1e57a493
Actual:   ea6dd0739d068c9a140c8802ad366aae9c27687d44f225e0cae180373eddca28
File:     /Users/hsuttong/Library/Caches/Homebrew/downloads/427b8d3b6886451661bdfc50a1558d525460c2ec40b720a7e0c17b2c7f90615a--P4V.dmg

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/54168
