### ISSUE TITLE
MacID should NOT have been removed

### ISSUE THREAD

**Issue by NicholasTD07** [Homebrew/homebrew-cask#54232]
This PR removed MacID. https://github.com/Homebrew/homebrew-cask/pull/47203

The reason was MacID was renamed to Unlox and we have a cask for Unlox. However, it's not the exact case. Unlox is more like MacID V2 and the developer explained why in his [FAQ](https://unlox.it/faqs/) and also a blog.

For people who bought the MacID iOS app, they could upgrade to Unlox, but with a cost. Plus, Unlox is not compatible with MacID. For people who like me, I am happy with MacID so I still want to use MacID on my mac and my phone.

Could you please revert the PR and bring back MacID as a cask itself? Thanks.

**Comment by vitorgalvao** [comment]
> please submit macid to https://github.com/Homebrew/homebrew-cask-versions

Please don’t.

> Could you please revert the PR and bring back MacID as a cask itself?

We’re not going to do that, I’m afraid. It’s been removed six months ago and this is the first time there has been any complaint, from which we can surmise it isn’t a popular cask. If you want it as a cask, you may wish to consider hosting your own [tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md).

**Comment by peterjc-123** [comment]
Ow nice page
