### ISSUE TITLE
cask-repair hangs at "Is everything correct? ([y]es / [n]o / [e]dit)"

### ISSUE THREAD

**Issue by vitahlin** [Homebrew/homebrew-cask#54265]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I want to update cask by script but it hang at "Is everything correct? ([y]es / [n]o / [e]dit)", whatever I input  it repeats again.

Full content : 
```c
cask-repair wiznote
Updating taps… Already up-to-date.
-----------------------------------------------------------------------------------------------------
cask 'wiznote' do
  version '2.6.1,2018-08-20'
  sha256 'd6e01cd6063f1aa0c13e6721d5243a08ce91671e2ab5324ba735f2b00ed0da2f'

  url "https://get.wiz.cn/wiznote-macos-#{version.after_comma}.dmg"
  name 'WizNote'
  homepage 'https://www.wiz.cn/wiznote-mac.html'

  app 'WizNote.app'
end
-----------------------------------------------------------------------------------------------------
Type the new version (or leave blank to use current one, or use `s` to skip)
> 2.6.4,2018-10-30
==> Downloading external files for Cask wiznote
==> Downloading https://get.wiz.cn/wiznote-macos-2018-10-30.dmg
######################################################################## 100.0%
==> No SHA-256 checksum defined for Cask 'wiznote', skipping verification.
==> Success! Downloaded to -> /Users/vitah/Library/Caches/Homebrew/downloads/dd7c10e2949b00fa9a161ae6
diff --git a/Casks/wiznote.rb b/Casks/wiznote.rb
index 812899c50..9862e5a52 100644
--- a/Casks/wiznote.rb
+++ b/Casks/wiznote.rb
@@ -1,6 +1,6 @@
 cask 'wiznote' do
-  version '2.6.1,2018-08-20'
-  sha256 'd6e01cd6063f1aa0c13e6721d5243a08ce91671e2ab5324ba735f2b00ed0da2f'
+  version '2.6.4,2018-10-30'
+  sha256 'd4e25658664897875b0d43e45d1bbf3950b594f216e3d43e26c97e26875ea67e'

   url "https://get.wiz.cn/wiznote-macos-#{version.after_comma}.dmg"
   name 'WizNote'
-----------------------------------------------------------------------------------------------------
• ==> Installing or updating 'rubocop-cask' gem
Building native extensions.  This could take a while...
-----------------------------------------------------------------------------------------------------
Is everything correct? ([y]es / [n]o / [e]dit) y
diff --git a/Casks/wiznote.rb b/Casks/wiznote.rb
index 812899c50..9862e5a52 100644
--- a/Casks/wiznote.rb
+++ b/Casks/wiznote.rb
@@ -1,6 +1,6 @@
 cask 'wiznote' do
-  version '2.6.1,2018-08-20'
-  sha256 'd6e01cd6063f1aa0c13e6721d5243a08ce91671e2ab5324ba735f2b00ed0da2f'
+  version '2.6.4,2018-10-30'
+  sha256 'd4e25658664897875b0d43e45d1bbf3950b594f216e3d43e26c97e26875ea67e'

   url "https://get.wiz.cn/wiznote-macos-#{version.after_comma}.dmg"
   name 'WizNote'
-----------------------------------------------------------------------------------------------------
• ==> Installing or updating 'rubocop-cask' gem
Building native extensions.  This could take a while...
• ==> Installing or updating 'rubocop-cask' gem
Building native extensions.  This could take a while...
-----------------------------------------------------------------------------------------------------
Is everything correct? ([y]es / [n]o / [e]dit) y
diff --git a/Casks/wiznote.rb b/Casks/wiznote.rb
index 812899c50..9862e5a52 100644
--- a/Casks/wiznote.rb
+++ b/Casks/wiznote.rb
@@ -1,6 +1,6 @@
 cask 'wiznote' do
-  version '2.6.1,2018-08-20'
-  sha256 'd6e01cd6063f1aa0c13e6721d5243a08ce91671e2ab5324ba735f2b00ed0da2f'
+  version '2.6.4,2018-10-30'
+  sha256 'd4e25658664897875b0d43e45d1bbf3950b594f216e3d43e26c97e26875ea67e'

   url "https://get.wiz.cn/wiznote-macos-#{version.after_comma}.dmg"
   name 'WizNote'
-----------------------------------------------------------------------------------------------------
• ==> Installing or updating 'rubocop-cask' gem
Building native extensions.  This could take a while...
• ==> Installing or updating 'rubocop-cask' gem
Building native extensions.  This could take a while...
• ==> Installing or updating 'rubocop-cask' gem
Building native extensions.  This could take a while...
-----------------------------------------------------------------------------------------------------
Is everything correct? ([y]es / [n]o / [e]dit)
```

#### Command that failed

```
cask-repair wiznote
```

**Comment by vitorgalvao** [comment]
It’s failing trying to run the `style` command. See https://github.com/Homebrew/homebrew-cask/issues/52775.

**Comment by jsatk** [comment]
Why is this closed? This is still a an issue.

**Comment by vitorgalvao** [comment]
> Why is this closed?

The reason is literally in the post above yours.

> This is still an issue.

Not with `cask-repair`.

**Comment by vitorgalvao** [comment]
> Why is this closed?

The reason is literally in the post above yours.

> This is still an issue.

And it’s being tracked elsewhere.

**Comment by jsatk** [comment]
@vitorgalvao the majority of people using `cask-repair` are simply running into this issue. It is not clear that it's related to `style`.

**Comment by jsatk** [comment]
Also this issue is about `cask-repair`. You then link to the other issue. And in that issue thread you reprimand folks for bringing up `cask-repair`. 
https://github.com/Homebrew/homebrew-cask/issues/52775#issuecomment-431342262

**Comment by vitorgalvao** [comment]
> And in that issue thread you reprimand folks for bringing up `cask-repair`

Because it was irrelevant information, and not addressing the problem. If I provided the tires to your car and you complain to me that the car isn’t running, if I point out that the problem is that the motor exploded I expect you to understand continuing to discuss the tires is wasted time, because it isn’t getting us closer to a resolution to the problem.

If there’s anything `cask-repair` is failing at here, is at not clearly communicating where the real issue is. I could indeed make that clearer, and maybe even bypass the problem by not running `style` in those situations, but `cask-repair` is already a huge mess<sup>1</sup> and I don’t want to complicate it, especially since this issue should fixed at the source and is high priority.

---

1. And I’ll be the first one to admit that, I’m not trying to irrationally defend `cask-repair`, I agree it has *huge* problems. This is just not one of them.

**Comment by jsatk** [comment]
Thanks for the reply.

The metaphor you give makes sense. It just wasn't clear to me (and others) how `brew cask style` was related to `cask-repair` never allowing us answer "Is everything correct?" when attempting to update outdated casks. I'd never heard of `brew cask style` before recently.

1. I'm an amateur rubyist and would be willing to attempt to fix this problem provided it's not already being worked on. Do you know if it's being actively fixed by someone else?
2. I'd love to make `cask-repair` better. As you said, it has problems. Is there a list of known issues with it specifically? I'd be willing to help fix.

**Comment by vitorgalvao** [comment]
> Do you know if it's being actively fixed by someone else?

If it is, it’s probably @reitermarkus, but I’m not sure it’s being worked on right now.

As for `cask-repair`, its issues are that it grew far beyond its original scope, and the code is a bit of a mess. One that that could be improved, for example, would be to get rid of `hub` as a dependency and use the API directly.

But it’s written in bash and follows my particular style, and I expect it to be followed. I’ve accepted many contributions to `cask-repair`, but if you submit large changes that don’t follow the current style, they’re unlikely to be merged. At this point, keeping it consistent is more important, so it doesn’t completely break. Alternatively, see https://github.com/Homebrew/homebrew-cask/issues/48086.
