### ISSUE TITLE
Skype For Business pkg 404 error

### ISSUE THREAD

**Issue by Jarli01** [Homebrew/homebrew-cask#54315]
#### General troubleshooting steps

- [X] I have retried my command with `--force` and the issue is still present.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Receiving a 404 error while attempting to install SfB.

https://download.microsoft.com/download/D/0/5D055DA17-4257-89A1-78E7BBE3833F/SkypeForBusinessInstaller-16.22.0.175.pkg

#### Command that failed

```
brew cask install skype-for-business
```

#### Output of command with `--force --verbose --debug`

```
Error: Download failed on Cask 'skype-for-business' with message: Download Failed: https://download.microsoft.com/download/D/0/5/D055DA17-4257-89A1-78E7BBE3833F/SkypeForBusinessInstaller-16.22.0.175.pkg

```

#### Output of `brew cask doctor`

```
Version 1.8.1-4

No issues reported
```

#### Output of `brew tap`

```
updated 1 tap homebrew/core
```

**Comment by Jarli01** [comment]
Updated pkg is here: https://download.microsoft.com/download/D/0/5/D055DA17-C7B8-4257-89A1-78E7BBE3833F/SkypeForBusinessInstaller-16.22.0.178.pkg

**Comment by Jarli01** [comment]
I'll post a edit to the cask in a minute.

**Comment by Jarli01** [comment]
https://github.com/Homebrew/homebrew-cask/compare/master...Jarli01:patch-1

**Comment by vitorgalvao** [comment]
Welcome @Jarli01. When posting a bug report in the future, please include the information we ask for, not a distillation.

For example, the `brew tap` output makes no sense. If you only had `homebrew/core`, you wouldn’t be able to install casks. Also, with the `doctor` command we’re not looking for errors, we’re looking for the exact configuration so we can identify common issues.
