### ISSUE TITLE
No history on deletion of mysimbl.rb

### ISSUE THREAD

**Issue by victorlin** [Homebrew/homebrew-cask#55281]
I am trying to install [`mySIMBL`](https://github.com/w0lfschild/mySIMBL). `brew search mysimbl` shows the last reference as a merged PR: [Update mysimbl to 0.5.3](https://github.com/Homebrew/homebrew-cask/pull/40481). However, the file `Casks/mysimbl.rb` does not exist in `master`.

Places I've looked:

- `git log --full-history -- Casks/mysimbl.rb` (yields no results)
- all issues and PRs on GitHub queried for "mysimbl"

Is there something I am missing here? I am curious how/why the cask was deleted.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/41917
https://github.com/Homebrew/homebrew-cask/pull/41890
https://github.com/sscotth/homebrew-sip
