### ISSUE TITLE
Do we need drop MTMR in this case?

### ISSUE THREAD

**Issue by idoo** [Homebrew/homebrew-cask#55289]
I asked an author to publish an app to the Github, (it was "normal" release process before) but looks like currently it's not distributed with public ling, only by a private server

https://github.com/Toxblh/MTMR/issues/128#issuecomment-440982258

**Comment by vitorgalvao** [comment]
Yes, if they’re not going to be making the latest version publicly available, we should drop it. Thank you for bringing this to our attention.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/55295
