### ISSUE TITLE
Warn that the app is running on upgrade

### ISSUE THREAD

**Issue by MacDada** [Homebrew/homebrew-cask#55430]
I've just learnt about the "greedy" upgrades (which existence and purpose should really be communicated better), and then I had another WTF ;)

While upgrading Chrome, the browser started to behave strangely. It's extensions would turn off, some pages wouldn't open (blank "loading" window).

I guess, I should close an app before attempting to upgrade it.

So there it is: apps that are running should not be upgraded. HBC should warn that in order for them to upgrade, they need to be turned off. Maybe there should be a flag to force the upgrade for ppl who want to risk upgrade while running the app.

**Comment by vitorgalvao** [comment]
This option make sense only after https://github.com/Homebrew/homebrew-cask/issues/16339. And since that one will likely not be done anytime soon, closing this. We can discuss it again after (if) the other ever gets done.
