### ISSUE TITLE
Remove (or archive) webpquicklook Cask

### ISSUE THREAD

**Issue by hanxue** [Homebrew/homebrew-cask#55444]
### Remove (or archive) webpquicklook Cask

The `webpquicklook` Cask has not been updated since October 2014, and the owner has updated the project description with **[DEPRECATED]**

![image](https://user-images.githubusercontent.com/760008/49062663-e4d06180-f24f-11e8-97bd-36692c7c9591.png)

### Justification

The `emin-webpquicklook` does exactly the same job and is still actively maintained. 

I can submit a PR to remove if the maintainers are OK with the proposed removal.

**Comment by vitorgalvao** [comment]
Please do. Remove `webpquicklook` and rename `emin-webpquicklook` to be `webpquicklook`. It’s more popular anyway.

**Comment by ran-dall** [comment]
@hanxue @vitorgalvao I made a PR to try to close this issue.
