### ISSUE TITLE
Telegram-4.7.1-147606 checksum failed

### ISSUE THREAD

**Issue by peterbourgon** [Homebrew/homebrew-cask#55752]
```
$ brew cask install telegram
==> Satisfying dependencies
==> Downloading https://osx.telegram.org/updates/Telegram-4.7.1-147606.app.zip
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'telegram'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'telegram' does not match.

Expected: d8803d4544745f5282b7e5b093820c5112db96efa39a9674528ec20523518e41
Actual:   4dbb50401a78fcb621f417da717586fcae910af70b1dd9e8018525ec468714f7
File:     /Users/peter/Library/Caches/Homebrew/downloads/247382fafe8b8fa2fabd75407b0ad974498aa60c8d1e4ff01d25dbed8efb4a90--Telegram-4.7.1-147606.app.zip

To retry an incomplete download, remove the file above.
```

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
