### ISSUE TITLE
filezilla no longer available?

### ISSUE THREAD

**Issue by phlinhng** [Homebrew/homebrew-cask#55880]
Today I tried to install ``filezilla`` by ``brew cask install filezilla``.
Then a message show up saying ``Error: Cask 'filezilla' is unavailable: No Cask with this name exists.``

After that I tried ``brew search file`` and ``brew search filezilla``, and ``filezilla`` didn't appear.
So is it true that filezilla is no longer available on cask?

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/55583
