### ISSUE TITLE
unable to install `sage`

### ISSUE THREAD

**Issue by evandrix** [Homebrew/homebrew-cask#56174]
```
$ brew cask install sage
==> Satisfying dependencies
==> Downloading http://mirrors.mit.edu/sage/osx/intel/sage-8.1-OSX_10.12.6-x86_64.app.dmg

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'sage' with message: Download failed: http://mirrors.mit.edu/sage/osx/intel/sage-8.1-OSX_10.12.6-x86_64.app.dmg
```

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
