### ISSUE TITLE
libreoffice 6.1.4 checksum changed

### ISSUE THREAD

**Issue by leonklingele** [Homebrew/homebrew-cask#56523]
```txt
==> Verifying SHA-256 checksum for Cask 'libreoffice'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
==> Purging files for version 6.1.4 of Cask libreoffice
Error: Checksum for Cask 'libreoffice' does not match.

Expected: 075c69bfb6672cf922f28f626ae183177671c08829c76aa1355e7fecce4fd0f7
Actual:   9cc44d1f75355a571a940db52f80f19e8c1eb3c5d18a46ff7925ce4202ae0398
```

New checksum matches the official one from https://download.documentfoundation.org/libreoffice/stable/6.1.4/mac/x86_64/LibreOffice_6.1.4_MacOS_x86-64.dmg.mirrorlist

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

**Comment by steiny2k** [comment]
please re-open. I get the same issue. Can't install libreoffice as the checksum in the repo is wrong.

**Comment by vitorgalvao** [comment]
Not reopening. My reason is pretty clear. Open an issue and follow the instructions, and you won’t even need to open an issue, because we teach you how to fix this.

In fact, there’s already someone with a PR open for this.
