### ISSUE TITLE
Error: Checksum for Cask 'elmedia-player' does not match and how to update it?

### ISSUE THREAD

**Issue by zizhenc** [Homebrew/homebrew-cask#56590]
Dear all,

I am new to git and GitHub and brew cask. I love the brew cask and try to install all gui apps using it. Now the problem is the Checksum for Cask 'elmedia-player' does not match. The one in cask is version 7.0 and now the download link provides version 7.1.
Hope anyone could update this. I tried update the cask by myself using 'cask-repair' but failed. I got errors like: "git@github.com: permission denied (publickey). fatal: could not read from remote repository."

Then I don't understand how to fix this. Hope suggestions.

Sincerely,
Zizhen Chen

**Comment by vitorgalvao** [comment]
Welcome, @zizhenc 

As explained in the template you deleted:

> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

So I’m going to close. If you open a new issue and follow the template, we teach you how to fix this error.
