### ISSUE TITLE
Installing atom incredibly slow

### ISSUE THREAD

**Issue by ismay** [Homebrew/homebrew-cask#56606]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Atom's own update command has been broken for a while now (see https://github.com/atom/atom/issues/16385). A temporary solution to this problem is to uninstall and reinstall atom through brew. However, the download for atom through homebrew (from https://github-production-release-asset-2e65be.s3.amazonaws) is incredibly slow. All other homebrew installs (casks as well as cli tools) download at a normal speed, but atom does not. I've tried updating on my home network and at work, with different machines, and at both networks it takes about half a day to a day to finish the install.

#### Command that failed

```
brew cask uninstall atom && brew cask install atom
```

**Comment by vitorgalvao** [comment]
Next time, please follow *all* the template.

This is not something we can fix, we don’t have control over other people’s server speeds.

**Comment by ismay** [comment]
> Next time, please follow all the template.

👍

> This is not something we can fix, we don’t have control over other people’s server speeds.

You can choose which url the script points to though. But it was just a heads up, do with it what you want.
