### ISSUE TITLE
gcc-arm-embedded 8-2018-q4-major broken gdb

### ISSUE THREAD

**Issue by troian** [Homebrew/homebrew-cask#56706]
#### General troubleshooting steps
gcc-arm-embedded in release 8-2018-q4-major has broken gdb

[bugreport](https://bugs.launchpad.net/gcc-arm-embedded/+bug/1809919)

Does it make sense to revert to previous release?

**Comment by vitorgalvao** [comment]
The bug report was just opened. It makes senses to wait for their response first.

**Comment by troian** [comment]
On of main tools is broken and it will simply confuse people

**Comment by reitermarkus** [comment]
We can revisit this if it gets reported by anyone else.
