### ISSUE TITLE
Consider using Azure Pipelines instead of Travis CI

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/homebrew-cask#56815]
### Description of feature/enhancement

Homebrew has migrated to using Azure Pipelines instead of Travis CI. Homebrew Cask should consider doing the same.

### Justification

The Azure Pipelines free macOS workers are much more performant than the Travis CI ones.

### Example use case

PRs are built with Azure Pipelines rather than Travis CI.

**Comment by vitorgalvao** [comment]
Fine by me.

**Comment by shikhar-scs** [comment]
@MikeMcQuaid I guess this lies along the lines of https://github.com/Homebrew/brew/pull/5457/files. If agreed upon, may I take this up ?

**Comment by reitermarkus** [comment]
@shikhar-scs, go for it. 👍

**Comment by shikhar-scs** [comment]
@reitermarkus I'd started with the work on `azure-pipelines`. I wrote the [azure-pipelines file](https://github.com/Homebrew/homebrew-cask/compare/master...shikhar-scs:azure-pipelines?expand=1#diff-fec826feae04e51c0d94076385408bdc) , taking help from the travis.yml file in the directory and then ran a build on the pipelines portal on azure devops. Here's where I'm getting stuck 
<img width="716" alt="screenshot 2019-01-07 at 9 38 09 am" src="https://user-images.githubusercontent.com/25258877/50748643-73c59600-1260-11e9-8e63-a72700c09431.png">

The complete log file is here : [6.txt](https://github.com/Homebrew/homebrew-cask/files/2731382/6.txt)

 Could you take a look please ? Also, is this the correct way ?

**Comment by vitorgalvao** [comment]
@shikhar-scs You’re getting that error because the `brew cask ci` command is [expecting a `CI` environment key](https://github.com/Homebrew/homebrew-cask/blob/7c37f9032d986c3dc3f984a61ff1e183fe9b61bb/cmd/brewcask-ci.rb#L14).

**Comment by reitermarkus** [comment]
Yes, you'll need to adjust [`brewcask-ci.rb`](https://github.com/Homebrew/homebrew-cask/blob/master/cmd/brewcask-ci.rb), which is currently pretty specific to Travis.

Also, please open a PR sooner rather than later, since it's much easier to review that way.

**Comment by shikhar-scs** [comment]
Thanks @reitermarkus & @vitorgalvao . I'll include a sample key as of now and debug further.

Also, is there a way I could test my changes locally? OR do i need to push my changes again & again :(

**Comment by reitermarkus** [comment]
You can set the `CI` variable locally for testing, or comment it out while testing.

**Comment by RDIL** [comment]
+1 for idea

**Comment by vitorgalvao** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-cask/pull/57156
