### ISSUE TITLE
Support for --full-name option when listing casks

### ISSUE THREAD

**Issue by cdalvaro** [Homebrew/homebrew-cask#56837]
### Description of feature

Add support for `--full-name` option when listing casks in order to identify the source of the cask formula.

### Justification

This is a feature that already has the `brew list` command.

```sh
brew list --help
Usage: brew list, ls [options] [-1] [-l] [-t] [-r]

List all installed formulae.

        --full-name                  Print formulae with fully-qualified names.
                                     If --full-name is not passed, other
                                     options (i.e. -1, -l, -t and -r)
                                     are passed to ls which produces the
                                     actual output.
```

When using `brew list --full-name`, the listed packages that have been installed from a different tap rather than `homebrew/core` appears with its corresponding tap concatenated at the beginning of the formula.

| `brew list` | `brew list --full-name` |
|:-----------|:-----------------------|
|ack|ack|
|bash|bash|
|boost|boost|
|cask|cask|
|cmake|cmake|
|cppzmq|cdalvaro/tap/cppzmq|
|zeromq|zeromq|

By adding support for `brew cask list --full-name` it can be useful for identifying cask packages that have been installed from different sources rather than `caskroom/cask`.

### Example use case

| `brew cask list` | `brew cask list --full-name` |
|:----------------|:-----------------------------|
|1password|1password|
|daisydisk|daisydisk|
|font-hack-nerd-font|homebrew/cask-fonts/font-hack-nerd-font|
|iterm2|iterm2|

**Comment by cdalvaro** [comment]
It would be great too, to replicate the behavior of `brew info --json=v1 --installed` with `cask`

**Comment by core-code** [comment]
personally i would have expected this option to print the full name from the cask name stanza, and not the "source"

**Comment by cdalvaro** [comment]
Some news here ...?

**Comment by vitorgalvao** [comment]
> Some news here ...?

This is incredibly low priority, so unless you wish to work on the PR yourself, it’s unlikely to get done any time soon.
