### ISSUE TITLE
Use `xattr -r -d com.apple.quarantine /Applications/x.app` on all installations

### ISSUE THREAD

**Issue by NightMachinary** [Homebrew/homebrew-cask#56876]
### Description of feature/enhancement

Some apps installed via Brew Cask (e.g., skim) show an irritating warning when first opened about the app being downloaded from the internet.nning `xattr -r -d com.apple.quarantine /Applications/x.app` on it solves the problem. So brew should just run this on all cask installations.

See also this question (not mine): https://apple.stackexchange.com/questions/337320/how-to-get-rid-of-application-downloaded-from-the-internet-message-when-instal

**Comment by vitorgalvao** [comment]
What you call “an irritating warning” we (and Apple) call “an important security feature”. We won’t remove quarantining — *we’re the ones adding it on purpose*.

You’re free to use the `--no-quarantine` flag to avoid this. And you do so at your own risk.
