### ISSUE TITLE
Split up microsoft-office cask into latest and 2016

### ISSUE THREAD

**Issue by ismay** [Homebrew/homebrew-cask#56898]
### Description of feature/enhancement

Split up microsoft-office cask into latest and 2016.

### Justification

Currently there's only the latest version and the 2011 version. But users with a license for the 2016 version cannot use the latest cask version, as the 2016 license is only compatible with versions up until 16.16 (current cask version is '16.20.18120801')

### Example use case

A user with a license for microsoft office 2016 wants to install a version compatible with that license. Would be nice if that's available under microsoft-office-2016

**Comment by vitorgalvao** [comment]
This is not a feature request, but a cask request. As explained in the templates, we don’t do cask requests.

If you want the cask, you’ll have to submit it.
