### ISSUE TITLE
Cask kerio-connect changed from client to server

### ISSUE THREAD

**Issue by ahousseini** [Homebrew/homebrew-cask#57078]
First commit was for the client: https://github.com/Homebrew/homebrew-cask/pull/45123

@core-code changed it later to the server: https://github.com/Homebrew/homebrew-cask/pull/52056

Should I make a new pull request for the client? E.g. `kerio-connect-client` or should we go back to the client and make a new cask `kerio-connect-server`?

**Comment by core-code** [comment]
sorry, it was not obvious to me that there were separate things.

**Comment by core-code** [comment]
i think having both, would at least reduce the confusion regarding this and maybe prevent such a mistake happening again,

**Comment by vitorgalvao** [comment]
Yes, let’s add both.
