### ISSUE TITLE
Error while installing ideviceinstaller - fatal error: 'cstddef' file not found

### ISSUE THREAD

**Issue by pgovind08** [Homebrew/homebrew-cask#57126]
iOS - 10.13.6
XCODE - 10.1

brew install --HEAD  ideviceinstaller
Updating Homebrew...
==> Cloning https://git.sukimashita.com/ideviceinstaller.git
Updating /Users/padma.govindaiah/Library/Caches/Homebrew/ideviceinstaller--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at f14def7 Remove length check on device UDID argument to support newer devices
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/ideviceinstaller/HEAD-f14def7_4
==> make install
Last 15 lines from /Users/padma.govindaiah/Library/Logs/Homebrew/ideviceinstaller/03.make:
2019-01-07 15:33:56 +0530

make
install

Making install in src
  CC       ideviceinstaller-ideviceinstaller.o
In file included from ideviceinstaller.c:31:
In file included from /usr/local/include/string.h:25:
/usr/local/Cellar/libplist/2.0.0_1/include/plist/Node.h:26:10: fatal error: 'cstddef' file not found
#include <cstddef>
         ^~~~~~~~~
1 error generated.
make[1]: *** [ideviceinstaller-ideviceinstaller.o] Error 1
make: *** [install-recursive] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting

I did go through the troubleshooting steps and did "brew update" twice.

$brew update
Fast-forwarded master to origin/master.
Updated 1 tap (homebrew/core).
==> Updated Formulae
boost
localadmins-MacBook-Pro:plist xxx.xxx$ brew update
Already up-to-date.

I tried the brew doctor, and got a list of header files which are not needed.. I did not put them specifically, might have got added during libimobile, autoconf, pkg-conf installation.

$brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/Array.h
  /usr/local/include/Boolean.h
  /usr/local/include/Data.h
  /usr/local/include/Date.h
  /usr/local/include/Dictionary.h
  /usr/local/include/Integer.h
  /usr/local/include/Key.h
  /usr/local/include/Node.h
  /usr/local/include/Real.h
  /usr/local/include/String.h
  /usr/local/include/Structure.h
  /usr/local/include/Uid.h
  /usr/local/include/afc.h
  /usr/local/include/android-ifaddrs.h
  /usr/local/include/ares.h
  /usr/local/include/ares_build.h
  /usr/local/include/ares_rules.h
  /usr/local/include/ares_version.h
  /usr/local/include/base.h
  /usr/local/include/bcj.h
  /usr/local/include/big_endian.h
  /usr/local/include/binary_log_types.h
  /usr/local/include/block.h
  /usr/local/include/byte_order_generic.h
  /usr/local/include/byte_order_generic_x86.h
  /usr/local/include/check.h
  /usr/local/include/container.h
  /usr/local/include/debugserver.h
  /usr/local/include/decimal.h
  /usr/local/include/delta.h
  /usr/local/include/diagnostics_relay.h
  /usr/local/include/errmsg.h
  /usr/local/include/file_relay.h
  /usr/local/include/filter.h
  /usr/local/include/hardware.h
  /usr/local/include/heartbeat.h
  /usr/local/include/house_arrest.h
  /usr/local/include/index.h
  /usr/local/include/index_hash.h
  /usr/local/include/installation_proxy.h
  /usr/local/include/keycache.h
  /usr/local/include/libimobiledevice.h
  /usr/local/include/libplatform/libplatform.h
  /usr/local/include/libusb.h
  /usr/local/include/little_endian.h
  /usr/local/include/lockdown.h
  /usr/local/include/lt_dlloader.h
  /usr/local/include/lt_error.h
  /usr/local/include/lt_system.h
  /usr/local/include/lzma12.h
  /usr/local/include/m_ctype.h
  /usr/local/include/m_string.h
  /usr/local/include/misagent.h
  /usr/local/include/mobile_image_mounter.h
  /usr/local/include/mobileactivation.h
  /usr/local/include/mobilebackup.h
  /usr/local/include/mobilebackup2.h
  /usr/local/include/mobilesync.h
  /usr/local/include/my_alloc.h
  /usr/local/include/my_byteorder.h
  /usr/local/include/my_command.h
  /usr/local/include/my_compiler.h
  /usr/local/include/my_config.h
  /usr/local/include/my_dbug.h
  /usr/local/include/my_dir.h
  /usr/local/include/my_getopt.h
  /usr/local/include/my_global.h
  /usr/local/include/my_list.h
  /usr/local/include/my_sys.h
  /usr/local/include/my_thread.h
  /usr/local/include/my_thread_local.h
  /usr/local/include/my_xml.h
  /usr/local/include/mysql.h
  /usr/local/include/mysql/client_authentication.h
  /usr/local/include/mysql/client_plugin.h
  /usr/local/include/mysql/com_data.h
  /usr/local/include/mysql/get_password.h
  /usr/local/include/mysql/group_replication_priv.h
  /usr/local/include/mysql/innodb_priv.h
  /usr/local/include/mysql/mysql_lex_string.h
  /usr/local/include/mysql/plugin.h
  /usr/local/include/mysql/plugin_audit.h
  /usr/local/include/mysql/plugin_auth.h
  /usr/local/include/mysql/plugin_auth_common.h
  /usr/local/include/mysql/plugin_ftparser.h
  /usr/local/include/mysql/plugin_group_replication.h
  /usr/local/include/mysql/plugin_keyring.h
  /usr/local/include/mysql/plugin_trace.h
  /usr/local/include/mysql/plugin_validate_password.h
  /usr/local/include/mysql/psi/mysql_file.h
  /usr/local/include/mysql/psi/mysql_idle.h
  /usr/local/include/mysql/psi/mysql_mdl.h
  /usr/local/include/mysql/psi/mysql_memory.h
  /usr/local/include/mysql/psi/mysql_ps.h
  /usr/local/include/mysql/psi/mysql_socket.h
  /usr/local/include/mysql/psi/mysql_sp.h
  /usr/local/include/mysql/psi/mysql_stage.h
  /usr/local/include/mysql/psi/mysql_statement.h
  /usr/local/include/mysql/psi/mysql_table.h
  /usr/local/include/mysql/psi/mysql_thread.h
  /usr/local/include/mysql/psi/mysql_transaction.h
  /usr/local/include/mysql/psi/psi.h
  /usr/local/include/mysql/psi/psi_base.h
  /usr/local/include/mysql/psi/psi_memory.h
  /usr/local/include/mysql/service_command.h
  /usr/local/include/mysql/service_locking.h
  /usr/local/include/mysql/service_my_plugin_log.h
  /usr/local/include/mysql/service_my_snprintf.h
  /usr/local/include/mysql/service_mysql_alloc.h
  /usr/local/include/mysql/service_mysql_keyring.h
  /usr/local/include/mysql/service_mysql_password_policy.h
  /usr/local/include/mysql/service_mysql_string.h
  /usr/local/include/mysql/service_parser.h
  /usr/local/include/mysql/service_rpl_transaction_ctx.h
  /usr/local/include/mysql/service_rpl_transaction_write_set.h
  /usr/local/include/mysql/service_rules_table.h
  /usr/local/include/mysql/service_security_context.h
  /usr/local/include/mysql/service_srv_session.h
  /usr/local/include/mysql/service_srv_session_info.h
  /usr/local/include/mysql/service_ssl_wrapper.h
  /usr/local/include/mysql/service_thd_alloc.h
  /usr/local/include/mysql/service_thd_engine_lock.h
  /usr/local/include/mysql/service_thd_wait.h
  /usr/local/include/mysql/service_thread_scheduler.h
  /usr/local/include/mysql/services.h
  /usr/local/include/mysql/thread_pool_priv.h
  /usr/local/include/mysql/thread_type.h
  /usr/local/include/mysql_com.h
  /usr/local/include/mysql_com_server.h
  /usr/local/include/mysql_embed.h
  /usr/local/include/mysql_time.h
  /usr/local/include/mysql_version.h
  /usr/local/include/mysqld_ername.h
  /usr/local/include/mysqld_error.h
  /usr/local/include/nameser.h
  /usr/local/include/node_buffer.h
  /usr/local/include/node_object_wrap.h
  /usr/local/include/node_version.h
  /usr/local/include/notification_proxy.h
  /usr/local/include/openssl/aes.h
  /usr/local/include/openssl/archs/BSD-x86/opensslconf.h
  /usr/local/include/openssl/archs/BSD-x86_64/opensslconf.h
  /usr/local/include/openssl/archs/VC-WIN32/opensslconf.h
  /usr/local/include/openssl/archs/VC-WIN64A/opensslconf.h
  /usr/local/include/openssl/archs/aix-gcc/opensslconf.h
  /usr/local/include/openssl/archs/aix64-gcc/opensslconf.h
  /usr/local/include/openssl/archs/darwin-i386-cc/opensslconf.h
  /usr/local/include/openssl/archs/darwin64-x86_64-cc/opensslconf.h
  /usr/local/include/openssl/archs/linux-aarch64/opensslconf.h
  /usr/local/include/openssl/archs/linux-armv4/opensslconf.h
  /usr/local/include/openssl/archs/linux-elf/opensslconf.h
  /usr/local/include/openssl/archs/linux-ppc/opensslconf.h
  /usr/local/include/openssl/archs/linux-ppc64/opensslconf.h
  /usr/local/include/openssl/archs/linux-x32/opensslconf.h
  /usr/local/include/openssl/archs/linux-x86_64/opensslconf.h
  /usr/local/include/openssl/archs/linux32-s390x/opensslconf.h
  /usr/local/include/openssl/archs/linux64-s390x/opensslconf.h
  /usr/local/include/openssl/archs/solaris-x86-gcc/opensslconf.h
  /usr/local/include/openssl/archs/solaris64-x86_64-gcc/opensslconf.h
  /usr/local/include/openssl/asn1.h
  /usr/local/include/openssl/asn1_mac.h
  /usr/local/include/openssl/asn1t.h
  /usr/local/include/openssl/bio.h
  /usr/local/include/openssl/blowfish.h
  /usr/local/include/openssl/bn.h
  /usr/local/include/openssl/buffer.h
  /usr/local/include/openssl/camellia.h
  /usr/local/include/openssl/cast.h
  /usr/local/include/openssl/cmac.h
  /usr/local/include/openssl/cms.h
  /usr/local/include/openssl/comp.h
  /usr/local/include/openssl/conf.h
  /usr/local/include/openssl/conf_api.h
  /usr/local/include/openssl/crypto.h
  /usr/local/include/openssl/des.h
  /usr/local/include/openssl/des_old.h
  /usr/local/include/openssl/dh.h
  /usr/local/include/openssl/dsa.h
  /usr/local/include/openssl/dso.h
  /usr/local/include/openssl/dtls1.h
  /usr/local/include/openssl/e_os2.h
  /usr/local/include/openssl/ebcdic.h
  /usr/local/include/openssl/ec.h
  /usr/local/include/openssl/ecdh.h
  /usr/local/include/openssl/ecdsa.h
  /usr/local/include/openssl/engine.h
  /usr/local/include/openssl/err.h
  /usr/local/include/openssl/evp.h
  /usr/local/include/openssl/hmac.h
  /usr/local/include/openssl/idea.h
  /usr/local/include/openssl/krb5_asn.h
  /usr/local/include/openssl/kssl.h
  /usr/local/include/openssl/lhash.h
  /usr/local/include/openssl/md4.h
  /usr/local/include/openssl/md5.h
  /usr/local/include/openssl/mdc2.h
  /usr/local/include/openssl/modes.h
  /usr/local/include/openssl/obj_mac.h
  /usr/local/include/openssl/objects.h
  /usr/local/include/openssl/ocsp.h
  /usr/local/include/openssl/opensslconf.h
  /usr/local/include/openssl/opensslv.h
  /usr/local/include/openssl/ossl_typ.h
  /usr/local/include/openssl/pem.h
  /usr/local/include/openssl/pem2.h
  /usr/local/include/openssl/pkcs12.h
  /usr/local/include/openssl/pkcs7.h
  /usr/local/include/openssl/pqueue.h
  /usr/local/include/openssl/rand.h
  /usr/local/include/openssl/rc2.h
  /usr/local/include/openssl/rc4.h
  /usr/local/include/openssl/ripemd.h
  /usr/local/include/openssl/rsa.h
  /usr/local/include/openssl/safestack.h
  /usr/local/include/openssl/seed.h
  /usr/local/include/openssl/sha.h
  /usr/local/include/openssl/srp.h
  /usr/local/include/openssl/srtp.h
  /usr/local/include/openssl/ssl.h
  /usr/local/include/openssl/ssl2.h
  /usr/local/include/openssl/ssl23.h
  /usr/local/include/openssl/ssl3.h
  /usr/local/include/openssl/stack.h
  /usr/local/include/openssl/symhacks.h
  /usr/local/include/openssl/tls1.h
  /usr/local/include/openssl/ts.h
  /usr/local/include/openssl/txt_db.h
  /usr/local/include/openssl/ui.h
  /usr/local/include/openssl/ui_compat.h
  /usr/local/include/openssl/whrlpool.h
  /usr/local/include/openssl/x509.h
  /usr/local/include/openssl/x509_vfy.h
  /usr/local/include/openssl/x509v3.h
  /usr/local/include/plist++.h
  /usr/local/include/plist.h
  /usr/local/include/plugin.h
  /usr/local/include/plugin_audit.h
  /usr/local/include/plugin_ftparser.h
  /usr/local/include/plugin_group_replication.h
  /usr/local/include/plugin_keyring.h
  /usr/local/include/plugin_validate_password.h
  /usr/local/include/property_list_service.h
  /usr/local/include/pthread-barrier.h
  /usr/local/include/pthread-fixes.h
  /usr/local/include/restore.h
  /usr/local/include/sbservices.h
  /usr/local/include/screenshotr.h
  /usr/local/include/service.h
  /usr/local/include/sql_common.h
  /usr/local/include/sql_state.h
  /usr/local/include/sslopt-case.h
  /usr/local/include/sslopt-longopts.h
  /usr/local/include/sslopt-vars.h
  /usr/local/include/stdint-msvc2008.h
  /usr/local/include/stream_flags.h
  /usr/local/include/syslog_relay.h
  /usr/local/include/thr_cond.h
  /usr/local/include/thr_mutex.h
  /usr/local/include/thr_rwlock.h
  /usr/local/include/tree.h
  /usr/local/include/typelib.h
  /usr/local/include/uv-aix.h
  /usr/local/include/uv-bsd.h
  /usr/local/include/uv-darwin.h
  /usr/local/include/uv-errno.h
  /usr/local/include/uv-linux.h
  /usr/local/include/uv-sunos.h
  /usr/local/include/uv-threadpool.h
  /usr/local/include/uv-unix.h
  /usr/local/include/uv-version.h
  /usr/local/include/uv-win.h
  /usr/local/include/uv.h
  /usr/local/include/v8-debug.h
  /usr/local/include/v8-experimental.h
  /usr/local/include/v8-platform.h
  /usr/local/include/v8-profiler.h
  /usr/local/include/v8-testing.h
  /usr/local/include/v8-util.h
  /usr/local/include/v8-version.h
  /usr/local/include/v8.h
  /usr/local/include/v8config.h
  /usr/local/include/version.h
  /usr/local/include/vli.h
  /usr/local/include/webinspector.h
  /usr/local/include/zconf.h
  /usr/local/include/zlib.h

I tried uninstalling ideviceinstaller, but got an error for that as well.

$brew uninstall ideviceinstaller
Error: No such keg: /usr/local/Cellar/ideviceinstaller

Did a info for ideviceinstaller:
$brew info ideviceinstaller
ideviceinstaller: stable 1.1.0 (bottled), HEAD
Cross-platform library for communicating with iOS devices
https://www.libimobiledevice.org/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/ideviceinstaller.rb
==> Dependencies
Build: pkg-config ✔
Required: libimobiledevice ✔, libzip ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 21,945 (30 days), 54,282 (90 days), 156,631 (365 days)
install_on_request: 21,876 (30 days), 54,067 (90 days), 154,745 (365 days)
build_error: 0 (30 days)

I am stuck here and unable to proceed further.. i have been searching from past 2 days to overcome this error, but nothing seems to be working.

I am trying to run my app on the simulator, but stuck with the installations and errors.
Any help is really appreciated.

Thanks much.

**Comment by vitorgalvao** [comment]
Next time, please fill the template (as it tells you to) or I’ll close the issue without review (as the template warns).

You have the wrong repo. You want https://github.com/Homebrew/homebrew-core. And I warn you tht if you don’t follow their template (and correctly format your error, with [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks), they’re going to close it without review.
