### ISSUE TITLE
List of some casks that are should have auto_updates set to true

### ISSUE THREAD

**Issue by Zialus** [Homebrew/homebrew-cask#57391]
The following casks can auto-update, but don't have the option set to true

```
bbedit
path-finder
sublime-text-dev
yate
```

**Comment by tusharjoshi** [comment]
I have raised pull requests for these casks

[bbedit](https://github.com/Homebrew/homebrew-cask/pull/57393)
[path-finder](https://github.com/Homebrew/homebrew-cask/pull/57394)
[yate](https://github.com/Homebrew/homebrew-cask/pull/57395)

The `sublime-text-dev` cask is from `homebrew-casks-versions` repository and not from this repository, hence had to raise PR there
[sublime-text-dev](https://github.com/Homebrew/homebrew-cask-versions/pull/6839)

**Comment by vitorgalvao** [comment]
Thank you, @tusharjoshi.
