### ISSUE TITLE
definition is invalid: invalid 'depends_on macos' value: ":tiger"

### ISSUE THREAD

**Issue by Gowa2017** [Homebrew/homebrew-cask#57507]
Today I can't use `brew search`。

Error message is  Cask 'appcleaner' definition is invalid: invalid 'depends_on macos' value: ":tiger"

I modify the appcleaner.rb, change :tiger to  :mojave。 But， other *.rb file get the same error。

I have no idea what to do .

**Comment by vitorgalvao** [comment]
> But maybe it would be better to fill a new issue, filling the full template with necessary information.

Yes, please. Open a new issue @Gowa2017, and follow the instructions.

You likely won’t even need to finish open the issue, as your problem should be fixed by the commands in the template.
