### ISSUE TITLE
tinymediamanager: java8 required?

### ISSUE THREAD

**Issue by spl** [Homebrew/homebrew-cask#57762]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I installed `java` and `tinymediamanager` with:

```sh
$ brew cask install java
$ brew cask install tinymediamanager
```

because the caveat for `tinymediamanager` says:

```
==> Caveats
tinymediamanager requires Java 7+. You can install the latest version with

  brew cask install java
```

However, upon opening `tinyMediaManager.app`, it tells me that Java is not installed. On a whim, I decided to install `java8` from `homebrew/cask-versions`:

```
$ brew cask install java8
```

After that, opening `tinyMediaManager.app` was successful.

Is this a problem with the `java` formula/JRE/JDK, or is this a problem with `tinymediamanager` or other Java-based casks?

**Comment by reitermarkus** [comment]
It probably only works with older Java versions, i.e. 7 and 8. You can change the caveat to `depends_on_java '8'`.

**Comment by spl** [comment]
The [tinyMediaManager release notes for 2.9.14](http://www.tinymediamanager.org/blog/version-2-9-14/) do claim to have “Java 9 / 10 / 11 compatibility.”

I don't suppose it could be something different about the `java` (11) and `java8` formulae/packages, could it?

**Comment by reitermarkus** [comment]
You could try installing Java 11 manually to see if the cask is the problem.

**Comment by spl** [comment]
This appears to be a `tinymediamanager` issue that will be fixed in the next release. See https://github.com/tinyMediaManager/tinyMediaManager/issues/445
