### ISSUE TITLE
did cleanup go away?

### ISSUE THREAD

**Issue by brianmorton** [Homebrew/homebrew-cask#57875]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Tried running `brew cask cleanup` and was given the help page. `man brew-cask` says cleanup is still around though...

does the man page need updating (it was legitimately removed) or has this been broken somewhere along the line?

#### Command that failed

```
brew cask cleanup
brew cask cleanup --outdated
```

example output:

```
$ brew cask cleanup
Homebrew Cask provides a friendly CLI workflow for the administration
of macOS applications distributed as binaries.

Commands:

    audit      verifies installability of Casks
    cat        dump raw source of the given Cask to the standard output
    create     creates the given Cask and opens it in an editor
    doctor     checks for configuration issues
    edit       edits the given Cask
    fetch      downloads remote application files to local cache
    home       opens the homepage of the given Cask
    info       displays information about the given Cask
    install    installs the given Cask
    list       with no args, lists installed Casks; given installed Casks, lists staged files
    outdated   list the outdated installed Casks
    reinstall  reinstalls the given Cask
    style      checks Cask style using RuboCop
    uninstall  uninstalls the given Cask
    upgrade    upgrades all outdated casks
    zap        zaps all files associated with the given Cask

See also "man brew-cask"
Error: help does not take arguments.
```

#### Output of command with `--force --verbose --debug`

won't run, so it won't run with these flags either

#### Output of `brew cask doctor`

nothing important

#### Output of `brew tap`

```
brianmorton/cask-automation
eugenmayer/dockersync
heroku/brew
homebrew/bundle
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/dupes
homebrew/formula-analytics
homebrew/services
vitorgalvao/tiny-scripts
```

**Comment by vitorgalvao** [comment]
Yes, [it has been removed](https://github.com/Homebrew/brew/issues/4660). The `man` page needs updating.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/brew/pull/5601
