### ISSUE TITLE
Try to update "processing" cask and get errors

### ISSUE THREAD

**Issue by zizhenc** [Homebrew/homebrew-cask#57878]
#### General troubleshooting steps

- [ * ] I have retried my command with `--force` and the issue is still present.
- [ * ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ * ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [ * ] I ran `brew update-reset && brew update` and retried my command.
- [ * ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ * ] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [ * ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

The 'processing' software updated but brew cask still outdated, I was trying to use 'cask-repair' to update that, entered the new version number 3.5.2 and checked the download url everything is correct, but in the end when I try to submit the update, it shows the following errors:
Is everything correct? ([y]es / [n]o / [e]dit) y
Submitting…
There were errors while pushing:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Please fix the errors and try again. If the issue persists, open a bug report on the repo for this script (https://github.com/vitorgalvao/tiny-scripts).

I doubt it should be some authentic keys problem which I don't really understand.

#### Command that failed

```
cask-repair processing
```

#### Output of command with `--force --verbose --debug`

```
{{replace this}}
```

#### Output of `brew cask doctor`

```
{{replace this}}
```

#### Output of `brew tap`

```
{{replace this}}
```

**Comment by vitorgalvao** [comment]
> If the issue persists, open a bug report on the repo for this script (https://github.com/vitorgalvao/tiny-scripts).

It tells you right there the correct repo to report this. [But don’t](https://github.com/vitorgalvao/tiny-scripts/issues/160), as the problem is in your setup.

Also, [processing has already been updated](https://github.com/Homebrew/homebrew-cask/pull/57845).

**Comment by zizhenc** [comment]
Okay, now it is updated.
