### ISSUE TITLE
Add blacklist with reasons

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-cask#58040]
There are some casks we don’t want resubmitted, such as `audacity` (difficulty to maintain), or `pharo` (developers want to maintain their own casks), `adobe-*` (we don’t want to maintain them). As the list grows, remembering everything will become harder. Suggestion:

1. Keep a `blacklist.txt` on the repo, with one line per cask, of the style `cask-name: reason for blacklist` (e.g. `pharo: Developers maintain their own tap at https://github.com/pharo-project/homebrew-pharo`).
2. Travis (Azure Pipelines) checks `blacklist.txt` for matching cask names (the token reference should ensure they match). If a name matches, it fails CI with the message.

**Comment by core-code** [comment]
note regarding audacity: we have a caskfile here http://www.corecode.io/macupdater/casks/audacity.rb

**Comment by vitorgalvao** [comment]
> note regarding audacity: we have a caskfile here http://www.corecode.io/macupdater/casks/audacity.rb

You should run `audit` and `style` on it. The former will fail (and so will `install`) due to `depends_on macos: '>= :snow_leopard'` (removed support for pre-Mavericks). The latter will fail due to the empty line between `url` and `name`.

**Comment by core-code** [comment]
thanks all fixed 👍

**Comment by reitermarkus** [comment]
I'd suggest making this part of `brew cask audit`, similar to how formulae are blacklisted.

**Comment by alecclarke** [comment]
👋Could I take this one on?

**Comment by vitorgalvao** [comment]
> 👋Could I take this one on?

Yes, I’ve just assigned you to the issue. Thank you for taking it on. If at any time before completion you decide you no longer have the availability, please let us know, so we can unassign you. If that happens, don’t feel pressured as there will be no hard feelings, we all know sometimes life gets in the way.
