### ISSUE TITLE
Fix casks with `depends_on` that reference pre-Mavericks

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-cask#58046]
If you get an error of the type `Error: Cask 'hex-fiend-beta' definition is invalid: invalid 'depends_on macos' value: ":lion"`, where `hex-fiend-beta` can be any cask name, and `:lion` any macOS release name, run the following command:

```bash
/usr/bin/find "$(brew --prefix)/Caskroom/"*'/.metadata' -type f -name '*.rb' -print0 | /usr/bin/xargs -0 /usr/bin/perl -i -pe 's/depends_on macos: \[.*?\]//gsm;s/depends_on macos: .*//g'
```

This will remove all `depends_on macos` references of *installed* casks (where it doesn’t matter anymore anyway).

We should deal with these cases better in the future.

**Comment by glhrmv** [comment]
I was trying to uninstall the `keka` cask and I couldn't because of this error message. Thank you.

**Comment by ran-dall** [comment]
@vitorgalvao I remember that we had a conversation with @core-code about trying 'us' trying to support as many releases of `macOS` as possible. I now see what you were saying about the high maintenance overhead...

Maybe we should have it a **harder** requirement of **only supporting the last two releases of `macOS.`** _I know it doesn't fix the issue, but it would mitigate it a bit by not having as many tags._ 🏷

We should consider that we're talking [~31% of users; which are on something different from the last two releases of `macOS`](http://gs.statcounter.com/macos-version-market-share/desktop/worldwide).

**Comment by vitorgalvao** [comment]
@rand-all This specific lack of support for pre-Maverick is now enforced in the core, with the release of Homebrew 2.0.0 (today!).

**Comment by ran-dall** [comment]
@vitorgalvao Yea I saw about an hour after I wrote that...haha! 👍

**Comment by reitermarkus** [comment]
I think we can safely remove `depends_on: '>= :mavericks'`.

**Comment by ran-dall** [comment]
@reitermarkus 🧞‍♂️It shall be done, then...

**Comment by brianmorton** [comment]
https://github.com/Homebrew/homebrew-cask/pull/58460

**Comment by brianmorton** [comment]
https://github.com/Homebrew/homebrew-cask/pull/58507

**Comment by felker** [comment]
By the way, if you have edited your `PATH` environment variable so that GNU `sed` is the default, @vitorgalvao's command won't work as written:
```
sed: can't read /depends_on macos:/d: No such file or directory
```

Be sure to use BSD `sed`, e.g.:
```shell
find "$(brew --prefix)/Caskroom/"*'/.metadata' -type f -name '*.rb' -print0 | xargs -0 /usr/bin/sed -i '' '/depends_on macos:/d'
```

**Comment by vitorgalvao** [comment]
Thank you @felker. Added `/usr/bin/` to the other tools as well, just in case.

**Comment by brianmorton** [comment]
Is there something that can be done from the HBC side to prevent folks having to deal with this?

**Comment by vitorgalvao** [comment]
> Is there something that can be done from the HBC side to prevent folks having to deal with this?

Old casks (i.e. the ones in `.metadata`) are the cause of issues like this. We can:

1. Fallback to the current cask when the stored one gives an error.
2. Instead of storing the cask at the moment of install, generate a `bash` file with the uninstall commands.

There’s an issue I’m not finding where we spitballed more ideas. It’s not https://github.com/Homebrew/homebrew-cask/issues/49716, though that one also has some of them.

**Comment by brianmorton** [comment]
If I sub a PR to brew that would check if the metadata file exists and update it to work with the current release without causing issues, is that something that would be desired?

**Comment by vitorgalvao** [comment]
> check if the metadata file exists and update it to work with the current release

The problem isn’t metadata files not existing; it’s that they exist but are old (i.e. use deprecated features). Replacing them with the current release outright would defeat the purpose — we want those old instructions, which is why we keep the files.

I see option 2 as more desirable, because that would decouple the uninstall (and zap) instructions from cask functionality, meaning they’ll be resilient to DSL changes.

Even so, before making a PR it would be desirable to open an issue to discuss the exact solution.

**Comment by brianmorton** [comment]
My proposal is basically just to run the sed pipe you provided on the metadata file (for installed casks only, yea?) on `brew update` so that people don't have to run it manually. I was only interested in doing it if it was a quick fix, I don't really want to open an issue and get into a big thing about how to fix this... I guess I'm not THAT altruistic ;)

**Comment by vitorgalvao** [comment]
@brianmorton Ah, yes, my suggestion was about fixing it for every future case. I don’t think a fix for this particular one is necessary. The issue seems to be doing its job — people are finding it OK and not opening too many issues about it.

**Comment by bernstein82** [comment]
really wish this would get a proper fix...

**Comment by vitorgalvao** [comment]
I’d like to thank everyone so far for their civility and the positive response to this hack/fix. Even the emoji reactions on the top post have been way more than what I expected, and all positive which is a welcome surprise. Just goes to show how respectful the Homebrew community is, that even though this might’ve inconvenienced you, you accept the fix and carry on.

Thank you for helping us maintain Homebrew (Cask) and being a positive community.

**Comment by mxr576** [comment]
The suggested command breaks Onyx, because it defines dependencies in an array.

`Error: Cask 'onyx' is unreadable: /usr/local/Caskroom/onyx/.metadata/3.5.6/20190115061551.579/Casks/onyx.rb:30: syntax error, unexpected ',', expecting keyword_end`

**Comment by haykam821** [comment]
I've dealt with this before in #57996. The old versions were referenced incorrectly (`mountain_lion` instead of `:mountain_lion`). Perhaps we should have a script that checks if a cask's version references are outside of [symbolic names or version strings](https://github.com/Homebrew/homebrew-cask/blob/0d830e951d85c5d14d414aaa4bfcc633d2735e6e/doc/cask_language_reference/readme.md#version-comparisons).

**Comment by vitorgalvao** [comment]
> Perhaps we should have a script that checks if a cask's version references are outside of [symbolic names or version strings](https://github.com/Homebrew/homebrew-cask/blob/0d830e951d85c5d14d414aaa4bfcc633d2735e6e/doc/cask_language_reference/readme.md#version-comparisons).

No need for a script, that should be part of `audit`, as it was invalid code.

**Comment by zubrakadzo** [comment]
Hi, run "brew cask uninstall vlc" and get "Error: Cask 'vlc' definition is invalid: invalid 'depends_on macos' value: ":lion""

**Comment by vitorgalvao** [comment]
@zubrakadzo Run the line in the top post.

**Comment by zubrakadzo** [comment]
> @zubrakadzo Run the line in the top post.

> brew cask uninstall vlc
> ==> Uninstalling Cask vlc
> ==> Backing App 'VLC.app' up to '/usr/local/Caskroom/vlc/3.0.4/VLC.app'.
> ==> Removing App '/Applications/VLC.app'.
> ==> Unlinking Binary '/usr/local/bin/vlc'.
> ==> Purging files for version 3.0.4 of Cask vlc

Thank you very much for your help.

**Comment by metayan** [comment]
A solution to the `invalid 'depends_on macos' value:` issue is to keep the definitions of the old OS versions in `Library/Homebrew/os/mac/version.rb`. This way the
```depends_on macos: '>= :<some-old-system>'```
in the `.metadata` files will work fine, and there will be no need to modify them.

In other words, to just revert the changes to `Library/Homebrew/os/mac/version.rb` in 
https://github.com/Homebrew/brew/pull/5599/commits/1aa8ad09e212cd9cd2f3ae55f899ed4ef03ae4d0

**Comment by vitorgalvao** [comment]
Updated the top one-liner to cover multi-lines cases enclosed by `[]`. If you find any other cases that fail, please let me know.

**Comment by vrillusions** [comment]
I just ran in to this and almost instinctively I ran `brew doctor` in case something was messed up with local install.  Perhaps this is something that could be added to it?

**Comment by oncletom** [comment]
Thanks 👍 I've been able to run `brew cask reinstall spotify` after typing the first command.

**Comment by cypher004** [comment]
Hi,
I'm getting the following when trying to install upgrade vlc:
Error: Cask 'vlc' definition is invalid: invalid 'depends_on macos' value: ":lion"

It seemed relevent to the thread. So thought I'd post.

Cheers,
Vivek

**Comment by vitorgalvao** [comment]
@cypher004 The solution is in the top post. Please read before posting.

There haven’t been any meaningful comments in this issue for a while, so I’ll lock it.
