### ISSUE TITLE
Outdated cask: displaycal

### ISSUE THREAD

**Issue by compuguy** [Homebrew/homebrew-cask#58117]
Outdated cask: [displaycal](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/displaycal.rb)

Info:

- version: 3.7.1.4
- appcast url: https://sourceforge.net/projects/dispcalgui/rss?path=/release.

**Comment by vitorgalvao** [comment]
Note to whoever wants to update: software changed to use a `pkg`.

See https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/pkg.md and https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md.

**Comment by compuguy** [comment]
Since displaycal has a autoupdater, the cask probably should have the auto_updates line added to it The installer also does a couple things differently from the previous dmg. The folders within the DisplayCAL folder are symlinked (Reference and Tests) instead of being in the DisplayCAL folder.

**Comment by brianmorton** [comment]
@compuguy I think @vitorgalvao is suggesting this would be a great first issue for you to submit a PR for and fix yourself if you feel you're up to it. It is not terribly complicated and he has linked the relevant references above.

**Comment by rpaulucci3** [comment]
I just submitted a PR for this. Please read the attached notes, as I was not able to figure out what @compuguy meant by the symlinks.
