### ISSUE TITLE
Outdated Cask: Private Internet Access

### ISSUE THREAD

**Issue by mcgi5sr2** [Homebrew/homebrew-cask#58190]
https://github.com/Homebrew/homebrew-cask/blob/2822d939ce4c3eefdf2bfc8e7c6bd41261ac0a6c/Casks/private-internet-access.rb

points to the legacy client,  the new client is Qt based and a vast improvement. Currently at version 1.0.1 could the cask be updated please?

**Comment by brianmorton** [comment]
Rank | Cask | Downloads | %
-- | -- | -- | --
384 | private-internet-access | 189 | 0.03%


from https://formulae.brew.sh/analytics/cask-install/30d/

**Comment by vitorgalvao** [comment]
@brianmorton Good point, no more guessing this!

**Comment by brianmorton** [comment]
https://github.com/Homebrew/homebrew-cask/pull/58338

**Comment by vitorgalvao** [comment]
Thank you!
