### ISSUE TITLE
Cask Analytics: Floor (min) to be official?

### ISSUE THREAD

**Issue by brianmorton** [Homebrew/homebrew-cask#58273]
Now that cask analytics are [live and public](https://formulae.brew.sh/analytics/cask-install/30d/), I will be attempting to automate updates of some of the top casks.

More to the point, is there a floor beneath which we will be removing casks from this tap? eg less than 50 installs on the 365 day chart or something?

EDIT: I should also note that the analytics only started being gathered a few months ago, so the 365d (at this point) is really not much more than the 90d numbers

**Comment by vitorgalvao** [comment]
> More to the point, is there a floor beneath which we will be removing casks from this tap? eg less than 50 installs on the 365 day chart or something?

No, not for now. Current strategy should be that if a cask is behaving, it stays, and if it misbehaves we’ll see how popular it is and remove if not popular.
