### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by liamdawson** [Homebrew/homebrew-cask#58327]
### Description of feature/enhancement

(Opt-in?) support for installing casks to Linux installations.

Could be done in a number of ways, including having a default `platforms` attribute for Cask definitions, and allowing the list to be extended. (Other options would include determining platform eligibility by commands, such as supporting casks that only use `font`)

### Justification

So Homebrew 2.0 officially supports Linux, which is 🎊🎉. There are a number of casks where the underlying "thing" is suitable for both destinations, either by nature of having binaries built for both platforms (even non-GUI applications like `aws-vault`), or not actually having binary components (font casks).

Starting with opt-in would help work out how to appropriately make things available on both platforms, and recognises that not every cask will work on all platforms.

### Example use case

```diff
cask 'font-alegreya-sans' do
  version '2.008'
  sha256 'ff8d1290eae47df0d1f710083690aa7f46508acfb2f1d6bce04b1355ac56dbab'
+ platforms %i(macos linux)

  url "https://github.com/huertatipografica/Alegreya-Sans/archive/v#{version}.zip"
  appcast 'https://github.com/huertatipografica/Alegreya-Sans/releases.atom'
  name 'Alegreya-Sans'
  homepage 'https://github.com/huertatipografica/Alegreya-Sans'

  font "Alegreya-Sans-#{version}/fonts/otf/AlegreyaSans-Black.otf"
end
```

**Comment by ran-dall** [comment]
It's a great idea, but, I don't know if the scope of HBC would _specifically_ fit. I would support it either way but I'm thinking it would be a better fit as a side project without obfuscating HBC. JMO 🗳

**Comment by vitorgalvao** [comment]
We’ve talked about this before, and we don’t really wish to support linux officially. It’s too far removed from the goals, and the work would be non-trivial.

Our focus are apps. When you suggest we add linux support for casks that are not apps (like fonts), what you are suggesting is that we add support for a new operating system so *only* the less used/wanted casks work on that OS.

That doesn’t make sense in terms of maintainer time. But if you want to start your own project that uses the fonts repo as a reference for getting fonts on Linux, you’re welcome to it.
