### ISSUE TITLE
Error: Cask 'textwrangler' definition is invalid: invalid 'depends_on macos' value: ":snow_leopard"

### ISSUE THREAD

**Issue by danny-su** [Homebrew/homebrew-cask#58366]
Error: Cask 'textwrangler' definition is invalid: invalid 'depends_on macos' value: ":snow_leopard"

**Comment by brianmorton** [comment]
https://github.com/Homebrew/homebrew-cask/issues/58046

**Comment by vitorgalvao** [comment]
@danny-su Please search issues before opening a new one. This one is right at the top and pinned.

Also, please don’t skip the template (*it asks you directly*).

Thank you @brianmortom and @ran-dall for providing the answers.
