### ISSUE TITLE
More insight into what happens when sudo access is given on install

### ISSUE THREAD

**Issue by brianmorton** [Homebrew/homebrew-cask#58512]
### Description of feature/enhancement

more info when giving my password (sudo)

### Justification

i don't like giving installers sudo access

### Example use case
```
$ brew cask install adobe-acrobat-reader
Updating Homebrew...
==> Auto-updated Homebrew!
==> Satisfying dependencies
==> Downloading http://ardownload.adobe.com/pub/adobe/reader/mac/AcrobatDC/1901020069/AcroRdrDC_1901020069_MUI.dmg
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'adobe-acrobat-reader'.
==> Installing Cask adobe-acrobat-reader
==> Running installer for adobe-acrobat-reader; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:
installer: Package name is Adobe Acrobat Reader DC (Continuous)
installer: Installing at base path /
installer: The install was successful.
🍺  adobe-acrobat-reader was successfully installed!
```

It's crazy to me to have to give sudo access to adobe for READER. Is there any way to know what the package installer is doing with these privs?

**Comment by reitermarkus** [comment]
Calling `installer` from the Terminal does exactly the same as running the installer manually. We have no control over what it does, as is implied by the message “Package installers may write to any location”.

**Comment by brianmorton** [comment]
Is there no way to track or output what has been done?

**Comment by reitermarkus** [comment]
There is a `-dumplog` option, which duplicates `/var/log/install.log` to `stdout`, but the output isn't that useful.
