### ISSUE TITLE
'brew cask outdated' shows "Warning: Unexpected method 'gpg' called on Cask torbrowser"

### ISSUE THREAD

**Issue by viamin** [Homebrew/homebrew-cask#58567]
#### General troubleshooting steps

- [x] I have retried my command with `--force`. (**invalid option 'force'**)
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem. (**similar:** https://github.com/Homebrew/homebrew-cask/issues/58495)
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

running `brew cask outdated` shows the message: "Warning: Unexpected method 'gpg' called on Cask torbrowser."

#### Command that failed

```
brew cask outdated
```

#### Output of command with `--verbose --debug`

```
Warning: Unexpected method 'gpg' called on Cask torbrowser.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
==> Checking update info of Cask gpg-suite
==> Checking update info of Cask torbrowser
(and all the rest of my casks)
```

#### Output of `brew cask doctor`

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/bart/.pyenv/shims/python3.6m-config
  /Users/bart/.pyenv/shims/python-config
  /Users/bart/.pyenv/shims/python3-config
  /Users/bart/.pyenv/shims/python3.6-config
  /Users/bart/.pyenv/shims/pre-commit-validate-config

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  qt@5.5
  imagemagick
```

#### Output of `brew tap`

```
eugenmayer/dockersync
heroku/brew
homebrew/bundle
homebrew/cask
homebrew/core
homebrew/services
raggi/ale
thoughtbot/formulae
```

**Comment by viamin** [comment]
Actually this looks like the same fix as https://github.com/Homebrew/homebrew-cask/issues/58495
cask "torbrowser" has been renamed to "tor-browser"

**Comment by viamin** [comment]
It seems like there should be a better experience for this though

**Comment by cryptCEE** [comment]
this worked for me:
`rm -rf "$(brew --prefix)/Caskroom/torbrowser" && brew cask install tor-browser`

**Comment by vitorgalvao** [comment]
> It seems like there should be a better experience for this though

https://github.com/Homebrew/homebrew-cask/issues/29716
