### ISSUE TITLE
Cask `megacmd-app` does not link all binaries

### ISSUE THREAD

**Issue by pcr910303** [Homebrew/homebrew-cask#58651]
Cask `megacmd-app` has a lots of binaries (in it's `/Applications/MEGAcmd.app/Contents/MacOS/` folder) to turn on the server (`MEGAcmdLoader`) or the interactive shell (`MEGAcmdShell`), and to interact to the megacmd server (`mega-ls`, `mega-cd`, `mega-cp`, `mega-find`, etc...) but the current cask only links the binary `MEGAcmdLoader`. This binary is no use if there are no binaries to interact(`mega-ls`, `mega-cp`, `mega-cd`, etc...). I can just hardcode the binary lists to the cask, but it might be better to find all binaries in the directory and linking. (and I don't know how to do that :-( )

**Comment by vitorgalvao** [comment]
> I can just hardcode the binary lists to the cask

Please do. It’s the method we use for other casks.

**Comment by pcr910303** [comment]
@vitorgalvao Will try to make a PR in a week..... I’m pretty busy these days :-(
