### ISSUE TITLE
Try to Update folx but pull request not merged

### ISSUE THREAD

**Issue by zizhenc** [Homebrew/homebrew-cask#58828]
#### General troubleshooting steps

- [ * ] I have retried my command with `--force`.
- [ * ] I ran `brew update-reset && brew update` and retried my command.
- [ * ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ * ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ * ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.
- [ * ] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [ * ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

{{I use cask-repair submitted an Update folx to 5.7.13779 #58785, but the pull request not merged. (It shows merge is blocked. I don't understand the reason. The point is the app 'folx' is still the old version in the cask, I tried to update that and submitted it successfully, why not merging that?)}}

#### Command that failed

```
{{replace this}}
```

#### Output of command with `--force --verbose --debug`

```
{{replace this}}
```

#### Output of `brew cask doctor`

```
{{replace this}}
```

#### Output of `brew tap`

```
{{replace this}}
```

**Comment by zizhenc** [comment]
I even tried several times, now I have two pull requests opened, one is #58888, the other is #58785. Both of them shows "merging is blocked"
Now you cannot use brew cask to install folx since it is outdated and sum check failed.

**Comment by reitermarkus** [comment]
A maintainer has to review the PR first and then merge it.
