### ISSUE TITLE
Delete Homebrew/homebrew-cask-eid

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-cask#59021]
https://github.com/Homebrew/homebrew-cask-eid was well-intentioned, but it might be best if we delete it. It has few casks, they get few updates, when they do many times it requires more than a simple bump, and analytics shows too few downloads (the most popular one had 25 downloads in the last 90 days, and more than half had less than 7).

Leaving this open for a bit for disagreements.

**Comment by reitermarkus** [comment]
I'm not a fan of having multiple taps to begin with, so no objections from me..

**Comment by ricardojoaoreis** [comment]
Will the casks be migrated to the main tap or will it a case by case thing?

**Comment by vitorgalvao** [comment]
@ricardojoaoreis As hinted in the top post, they will be deleted. They’re more trouble than they are worth.

From you name, I’m guessing you may be interested in the `eid-pt` cask. That was the one that inspired it all, but not even I use it. Every time I needed it, it was already outdated.

If you want to save them, I recommend keeping your own tap.

**Comment by victorpopkov** [comment]
Fully agree. More taps = more headache.

**Comment by reitermarkus** [comment]
@vitorgalvao, I think we should probably delete the casks before archiving the repo.
