### ISSUE TITLE
Add cask Icns Composer

### ISSUE THREAD

**Issue by sayomelu** [Homebrew/homebrew-cask#59125]
A great useful icon composer for `.icns` file

https://github.com/raphaelhanneken/icnscomposer

**Comment by vitorgalvao** [comment]
The [cask request issue template](https://github.com/Homebrew/homebrew-cask/issues/new?template=03_cask_request.md) is clear that we don’t accept requests.

Even if we did, we wouldn’t add that cask on account of [not being notable enough](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> The Cask is too obscure (for example, a self-submitted app from a GitHub repository that is [not notable enough](https://github.com/Homebrew/homebrew-cask/pull/28103) (under 50 stars)).
