### ISSUE TITLE
1Password not installed as a Hardened Runtime

### ISSUE THREAD

**Issue by tstm** [Homebrew/homebrew-cask#59254]
#### General troubleshooting steps

- [ not applicable ] I have retried my command with `--force`.
- [ x ] I ran `brew update-reset && brew update` and retried my command.
- [ not applicable ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ x ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ not applicable ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.
- [ x ] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [ x ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

When installing 1Password as a Cask, it will not be installed as a [Hardened Runtime](https://developer.apple.com/documentation/security/hardened_runtime_entitlements). If the Hardened Runtime is not enabled, the memory of 1Password can be easily read using a debugger and due to some other ongoing issues with 1Password, the vault password can be read even if the 1Password vault is locked. 

If the regular installation package from the 1Password website is used, the Hardened Runtime is enabled by default. This difference makes the Cask version horribly insecure compared to the website-installed version.

**Comment by reitermarkus** [comment]
So how do you enable the Hardened Runtime?

**Comment by tstm** [comment]
These are the steps according to Apple: https://help.apple.com/xcode/mac/current/#/devf87a2ac8f

Why the Hardened Runtime is not working through extracting the zip file instead of using the PKG Installer, I don't know.

**Comment by cameronyule** [comment]
@tstm out of curiosity why did you close this issue?

**Comment by tstm** [comment]
@cameronyule Sorry about the abrupt closing, I was looking into reproducing this issue in a VM and wrote the results here: https://discussions.agilebits.com/discussion/comment/494106/#Comment_494106

So, this is mostly due to a couple of things: If you are running an OS before Mojave, the Hardened Runtime mode is not supported. Also, the Hardened Runtime is enabled only in 7.2+ versions of 1Password, as it requires app notarization from Apple.

If you have an old version of the app or are running an old version of the OS, or if SIP is not enabled on your OS, your passwords will be readable from memory by any user-level process. Even if 1Password is locked - at least for some minutes after locking.

Anyway, the new versions installed by Homebrew are fine, I checked.
