### ISSUE TITLE
macOS always ask if I am sure to want to open the software

### ISSUE THREAD

**Issue by LoHub** [Homebrew/homebrew-cask#59378]
Hello,
I have a little trouble with software which I installed with brew cask. Each time I want to launch one, macOS tell me that the software was downloaded from internet and if I am sure to want to launch it.
I understand why it ask that the first time but I don't understand why it ask that for each launch whereas other softwares which wasn't install with homebrew from internet trigger this mechanism just for the first launch.

Thank you

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/the_app_cant_be_opened.md

**Comment by LoHub** [comment]
Thank you for your quick answer, unfortunately my problem is not a problem with unidentified developer.
The message wich I receive is describe on https://support.apple.com/en-us/HT202491 in the "Open a developer-signed or notarized app" section. Apple explain that this message should be displayed just one time to the first launch and should never appear after.

**Comment by vitorgalvao** [comment]
This is not a widespread issue, so it must be a problem with your setup. Also, since you didn’t fill the template (as it requested), we can’t debug your issue.
