### ISSUE TITLE
LibreOffice is seen as damaged due to quarantining

### ISSUE THREAD

**Issue by wickles** [Homebrew/homebrew-cask#59384]
This issue was locked but I am still having the same problem with libreoffice 6.2.0. Issue is described thoroughly in that thread. The accepted resolution that it was closed for was not helpful for me though, since I do not use the language pack. 

https://github.com/Homebrew/homebrew-cask/issues/52758

**Comment by vitorgalvao** [comment]
Issue isn’t widespread (and the cask is popular), so it will be assumed to be an issue with your setup.

Please don’t skip the issue template.

Pinging @amyspark just in case, but still closing.
