### ISSUE TITLE
Kicad is out of date

### ISSUE THREAD

**Issue by stiff** [Homebrew/homebrew-cask#59383]
http://kicad-pcb.org says 5.0.2 was released in December 2018, but in https://github.com/Homebrew/homebrew-cask/blob/master/Casks/kicad.rb it's still 5.0.1. If it's the only change required I can do PR for that :)

**Comment by vitorgalvao** [comment]
![image](https://user-images.githubusercontent.com/1699443/53290315-24004700-379a-11e9-8fd7-7a3892e47b45.png)

**Comment by stiff** [comment]
Oops, I completely missed that, sorry.

**Comment by ibutra** [comment]
These issues seem to be removed now. At least I can't find that info on the given page anymore.
