### ISSUE TITLE
Error: Checksum for Cask 'navicat-premium' does not match

### ISSUE THREAD

**Issue by hill-mickey** [Homebrew/homebrew-cask#59491]
$ brew cask install navicat-premium
==> Satisfying dependencies
==> Downloading http://download.navicat.com/download/navicat121_premium_en.dmg
Already downloaded: /Users/lixiang/Library/Caches/Homebrew/downloads/f3fac28b9a3310032a6c1c4dbc606af76abdcb664ef150ee9c70e9334c046be6--navicat121_premium_en.dmg
==> Verifying SHA-256 checksum for Cask 'navicat-premium'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'navicat-premium' does not match.

Expected: 04bb0dcad6e0157aa7f0e60ff35d4f758affcdc374fd0f3b16bdb782afdf0631
Actual:   6950014d505249842999ca0923a6452065f38ec0b4252997fc7d5d5ec7b46efd
File:     /Users/lixiang/Library/Caches/Homebrew/downloads/f3fac28b9a3310032a6c1c4dbc606af76abdcb664ef150ee9c70e9334c046be6--navicat121_premium_en.dmg

To retry an incomplete download, remove the file above. If the issue persists, visit:

  https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
