### ISSUE TITLE
android-sdk cask references old and outdated emulator binary

### ISSUE THREAD

**Issue by plastiv** [Homebrew/homebrew-cask#59635]
### Issue:
Linking `tools/emulator` and `tools/emulator-check` for `android-sdk` cask is incorrect and adding them back at https://github.com/Homebrew/homebrew-cask/pull/55209 was a mistake, I think. It hides the correct `emulator/emulator` and `emulator/emulator-check` binaries.

https://github.com/Homebrew/homebrew-cask/blob/3889a6f201c28d9e5ff5a6b06821fefc51cc45b7/Casks/android-sdk.rb#L19-L20

### Longer explanation of the issue:

https://github.com/Homebrew/homebrew-cask/pull/55209 PR description contains reference to the removed code and it was correctly located at the `emulator` folder before. So it is a regression. 

https://github.com/Homebrew/homebrew-cask/commit/1ae79fbc57984925de2ff6688086bd9ac19f76f2#diff-5bc3ae1974612e8c0ea8c1c8f722087eL32
https://github.com/Homebrew/homebrew-cask/commit/1ae79fbc57984925de2ff6688086bd9ac19f76f2#diff-5bc3ae1974612e8c0ea8c1c8f722087eL33

`tools/emulator` is kept for compatibility with Android Studio 2.2 which was released ~mid 2017 and is long being not relevant. Everyone has to use `emulator/emulator` instead:
* https://issuetracker.google.com/issues/66886035
* https://developer.android.com/studio/run/emulator-commandline#starting
* Run `tools/emulator -verbose` vs `emulator/emulator -verbose` to ensure outdated version

But we can't just rename it, because downloaded zip `https://dl.google.com/android/repository/sdk-tools-darwin-4333796.zip` doesn't contains `emulator` folder. It has to be downloaded with `sdkmanager "emulator"` first. So I would suggest to remove `tools/emulator` `tools/emulator-version` and update help text with next description:

```
      You may want to install android sdk packages via the sdkmanager command:

            sdkmanager "tools" "platform-tools" "emulator" "build-tools;28.0.3" "platforms;android-28" "system-images;android-28;google_apis;x86_64" 
    
```

**Comment by vitorgalvao** [comment]
@plastiv Please submit a PR.

Does this affect https://github.com/Homebrew/homebrew-cask/issues/58883 in any way?

**Comment by vitorgalvao** [comment]
Closing for lack of reply.
