### ISSUE TITLE
Tunnelblick Version Incorrectly Reported as a Development Version

### ISSUE THREAD

**Issue by robertleeblairjr** [Homebrew/homebrew-cask#59672]
#### General troubleshooting steps

- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

{{replace this}}

#### Command that failed

```
{{replace this}}
```

#### Output of command with `--force --verbose --debug`

```
{{replace this}}
```

#### Output of `brew cask doctor`

```
{{replace this}}
```

#### Output of `brew tap`

```
{{replace this}}
```
<img width="682" alt="screen shot 2019-03-01 at 8 54 01 am" src="https://user-images.githubusercontent.com/12276457/53645936-a2784100-3bff-11e9-847c-e76d47d3c60d.png">

Contributor incorrectly listed the Tunnelblick version for the stable, release with the development, beta version scheme.

**Comment by vitorgalvao** [comment]
Already reverting.

**Comment by robertleeblairjr** [comment]
Thanks. It was committed.
