### ISSUE TITLE
visual-studio and mono-mdk versions do not match

### ISSUE THREAD

**Issue by CoskunSunali** [Homebrew/homebrew-cask#59740]
#### Description of issue

`visual-studio` cask depends on `mono` which install mono version 5.18 automatically, however, Visual Studio 2017 doesn't support mono version 5.18 and requires 5.16.

**Comment by vitorgalvao** [comment]
Is that something we expect to be fixed by upstream soon?

**Comment by CoskunSunali** [comment]
I don’t think so. They are fully focused on the VS for Mac 2019 release now. 

https://developercommunity.visualstudio.com/content/problem/446329/mono-518-update-for-visual-studio-for-mac.html

VS for Mac 2019 requires a minimum of mono v5.8 as far as I know.

**Comment by vitorgalvao** [comment]
> They are fully focused on the VS for Mac 2019 release now.

And when is that supposed to come out?

**Comment by CoskunSunali** [comment]
3rd or 4th quarter of 2019 but I might be wrong.

The problem is, 2017 licensees won't be able to use 2019 right away because it will require a new license. You can safely assume many people will continue to use 2017 for a while even if 2019 is released.

Using 2017 currently causes a circular download issue. Cask updates install mono 5.18, VS Mac auto updates install mono 5.16.

Not a deal breaker but it is there and I wanted to report so you are aware.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/issues/60110
