### ISSUE TITLE
Question: Appcast URL (SourceForge)

### ISSUE THREAD

**Issue by YBHwang** [Homebrew/homebrew-cask#59837]
In this document [Homebrew Cask Guide for Appcast](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md)

> Sourceforge projects follow the form https://sourceforge.net/projects/{{project_name}}/rss. A more specific page can be used as needed, pointing to a specific directory structure: https://sourceforge.net/projects/{{project_name}}/rss?path=/{{path_here}}. (Example: seashore.rb)

**Can I use **Appcast** URL to https://sourceforge.net/mirror/{{project_name}}/activity/feed ?**

**Comment by reitermarkus** [comment]
Closing this, since we can discuss this more easily here: 
https://github.com/Homebrew/homebrew-cask/pull/59838#pullrequestreview-211062003
