### ISSUE TITLE
doc: Update Gatekeeper warning

### ISSUE THREAD

**Issue by bobsut** [Homebrew/homebrew-cask#59914]
### Update Gatekeeper warning

Update the example Gatekeeper popup warning, and the string by which a searching user might find this doc

### Justification

When a user searches the doc for the string they see in the Gatekeeper popup warning, they should be able to find the string they see. They shouldn't be required to infer that the string they see in their warning means the same as the string Apple used in earlier versions of macOS.

### Example use case

The Gatekeeper popup formerly said **_The app_ can’t be opened because it is from an unidentified developer.**
The Gatekeeper popup now says **_The app_ is an app downloaded from the Internet. Are you sure you want to open it?**

The remedial action remains the same, although this PR clarifies that either a right-click or a control-click (whichever UI action is familiar to the user) will accomplish the needful.

### Related PR

This is addressed in PR GH-59915.

**Comment by vitorgalvao** [comment]
Welcome.

This is not a new message. Both messages always existed, they’re shown in different situations.

Please don’t open an issue if you’re going to submit a PR. Just open the latter.
