### ISSUE TITLE
Correct visual-studio and mono-mdk versions

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-cask#60110]
Refs #59740.

What needs to be done is find the `5.16` cask version of [`mono-mdk`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/mono-mdk.rb), add it to [caskroom/versions](https://github.com/Homebrew/homebrew-cask-versions), and [change the `visual-studio` dependency](https://github.com/Homebrew/homebrew-cask/blob/9db9fc36fa76afb28d30fc037ba8937521a8a01e/Casks/visual-studio.rb#L11).

**Comment by CoskunSunali** [comment]
One additional thing if it matters. The 'visual-studio' package is not marked with `auto-updates` attribute but it auto updates.

**Comment by rpaulucci3** [comment]
Self-assigning this :)

https://github.com/Homebrew/homebrew-cask/pull/60928

https://github.com/Homebrew/homebrew-cask-versions/pull/7145
