### ISSUE TITLE
heimdall-suite cask install fails, unofficial updated version available

### ISSUE THREAD

**Issue by nighto** [Homebrew/homebrew-cask#60255]
Following #55922 which has been closed thus I cannot comment on: As stated on https://github.com/Benjamin-Dobell/Heimdall/issues/446, there's an "unofficial" 1.4.1 version on [heimdall's bitbucket Downloads page](https://bitbucket.org/benjamin_dobell/heimdall/downloads/Heimdall-1.4.1-Unofficial-Signed.dmg).

I downloaded and installed it manually and it worked on Mojave 10.14.3. So the cask could be updated to use this version.

**Comment by vitorgalvao** [comment]
> Following #55922 which has been closed thus I cannot comment on

It’s the locking that prevents it, not the closing.

> there's an "unofficial" 1.4.1 version on [heimdall's bitbucket Downloads page](https://bitbucket.org/benjamin_dobell/heimdall/downloads/Heimdall-1.4.1-Unofficial-Signed.dmg).

We’re not going to link to an “unofficial” version that appeared on bitbucket but the author doesn’t link to. You’ll need to ask them to link to this version officially for us to add it.

**Comment by nighto** [comment]
Ok, so would it be possible to temporarily unlist `heimdall-suite` cask? Therefore users wouldn't waste time trying to install it since we know it will fail.

**Comment by vitorgalvao** [comment]
> Ok, so would it be possible to temporarily unlist `heimdall-suite` cask? Therefore users wouldn't waste time trying to install it since we know it will fail.

The cask isn’t popular, so that isn’t an issue:

```
heimdall-suite (added 832 days ago)
30 days: 14 (#1864)
90 days: 50 (#1674)
365 days: 100 (#1747)
```

if you’re going to ask the author, there’s no point to remove it if we’re going to add it back again.

**Comment by nighto** [comment]
Sure. Apparently heimdall's dev [moved the project from GitHub to GitLab](https://github.com/Benjamin-Dobell/Heimdall), and there's an [issue opened about it already](https://gitlab.com/BenjaminDobell/Heimdall/issues/487) (notice users mention the cask failing).

I added a comment mentioning repo owner to add the dmg as official, if they ever reply I'll update here.

In the mean time, do you think it would be ok to have a "cask fork" `heimdall-suite-unofficial` or something like that?

Thanks for your attention.

**Comment by vitorgalvao** [comment]
> In the mean time, do you think it would be ok to have a "cask fork" `heimdall-suite-unofficial` or something like that?

I’d rather not. Like I said, this isn’t popular, and it’d just fragment the users. I’d rather have this well fixed.

> Thanks for your attention.

Thank you for taking the time to explain the problem and link to your sources!
