### ISSUE TITLE
Error message when running brew cask install & app was already installed via some other means could be clearer

### ISSUE THREAD

**Issue by chrish42** [Homebrew/homebrew-cask#60284]
I was working on a setup script that I would just run from time to time and every software I use on my Macs would be installed afterwards. For this to works, each command has to work fine (i.e. not produce an error or bad side-effects) if it's run a second time or more. Everything was working fine for most of the casks I was installing (Warning: so-and-so already installed), except for the iterm2 one, where I was getting "Error: /Applications/iTerm2.app already exists. Not overwriting"

It certainly wasn't clear to me initially what the (correct) root cause of this was, as  non-expert with Homebrew. What there a bug with the formula? This was the only cask that installed to /Applications... is there something different with that? Etc.

It took a little while and help from @Moisan to figure out that I had initially installed iTerm2 via the installer on their website (and not the cask) on that computer. Most of that time would have been saved if only Homebrew had been clearer about that. For example:

`Error: /Applications/iTerm2 already exists, but was not installed by Homebrew initially. Not overwriting with version from cask iterm2.`

Bonus points for pointing to the solutions in addition to that, maybe something like:

`(Either uninstall the app before running brew cask install, or use the --force option to the cask install command.)`

Thanks!

**Comment by vitorgalvao** [comment]
> Error: /Applications/iTerm2 already exists, but was not installed by Homebrew initially. Not overwriting with version from cask iterm2.

That might not be true. And that message feels too verbose.

The exact messaging we output now is `Error: It seems there is already an App at '{{location}}'.`. That seems clear enough to me and most people don’t have trouble with that messaging, so I don’t think it’s worth changing.

**Comment by chrish42** [comment]
That message was just a proposal, it can be tweaked. The point was: homebrew knows if the cask was installed and is being updated, or if it thinks it's installing it for the first time. Communicating that fact clearly in the error would have been useful. Anyways, I won't be bothering to report usability issues in the future. Thanks.

**Comment by vitorgalvao** [comment]
> That message was just a proposal, it can be tweaked.

Yes, naturally.

> Communicating that fact clearly in the error would have been useful.

The point is I feel the current message is clear. If we got other reports of other users being confused by it, I’d have the opposite opinion. But one confused user doesn’t mean the message is bad; it means one user was confused.

> Anyways, I won't be bothering to report usability issues in the future.

I don’t think *one* disagreement about what constitutes a usability issue (your argument is that this is one, mine that it isn’t) should stop you from reporting other things you feel are wrong, but that is your choice and we can’t force you.
