### ISSUE TITLE
Add support for caching servers such as Artifactory

### ISSUE THREAD

**Issue by Endareth** [Homebrew/homebrew-cask#60326]
### Description of feature/enhancement

Add the ability to specify a 3rd party caching/mirror server to use.

### Justification

While core homebrew supports use of Artifactory (and presumably others) via the HOMEBREW_BOTTLE_DOMAIN environment variable, this isn't supported for casks. Adding equivalent functionality would provide speed and reliability to installing casks.

### Example use case

For any significantly sized development team, installing/upgrading casks can take a fair amount of time and bandwidth. Having the ability to cache the casks would speed up the download side of things considerably.
In addition, if the original source of a cask becomes temporarily unavailable due to network issues (regardless of whether that's at source or local), having a local cache/mirror would allow the cask to still be retrieved.

**Comment by jonchang** [comment]
Does `HOMEBREW_ARTIFACT_DOMAIN` work for your use case?

**Comment by Endareth** [comment]
Not with the a generic repo in artifactory (the way that normal formulas/bottles do). There might be a way to configure a repo to rewrite the request in a way that is able to download the cask, but I haven't had the time to experiment with that at the moment.
