### ISSUE TITLE
brew cask upgrade error

### ISSUE THREAD

**Issue by junsionzhang** [Homebrew/homebrew-cask#60410]
when running brew cask upgrade ,the error as follows:
Error: Cask 'weibox' definition is invalid: invalid 'depends_on macos' value: ":mountain_lion"

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Please don’t ignore the template, and please search before posting. [The solution](https://github.com/Homebrew/homebrew-cask/issues/58046) is literally pinned in the issues page.
