### ISSUE TITLE
ForkLift URL needs updated

### ISSUE THREAD

**Issue by NickRiddell** [Homebrew/homebrew-cask#60535]
When trying to run the following command I get a 404: 

brew cask install https://raw.githubusercontent.com/caskroom/homebrew-cask/0bc4d90f01add4fe5efaccc7ece9bcb34b393751/Casks/forklift.rb

This may be due to the URLs being http as opposed to https. I am trying to install ForkLift2.6.6

**Comment by NickRiddell** [comment]
Would it be possible to update the 2.6.6 file?

**Comment by vitorgalvao** [comment]
> Would it be possible to update the 2.6.6 file?

No. What you’re using to install is a specific git revision which is both unchangeable and an unsupported method. You may wish to consider hosting your own [tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md) and fixing it there.
