### ISSUE TITLE
Updating multilingual casks

### ISSUE THREAD

**Issue by core-code** [Homebrew/homebrew-cask#60617]
Updating multilingual casks is a pain since cask-repair doesn't work. Here is a script that should help - to generate the caskfile for the recent tor-browser update use it like this:

`update_multilingual_cask.py /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/tor-browser.rb 8.0.7
`

script source:
```

#!/usr/bin/python
# -*- coding: UTF-8 -*-
import sys, urllib2, hashlib

def getsha(url, version, language):
	url = url.replace("#{version}", version)
	url = url.replace("#{language}", language)
	response = urllib2.urlopen(url)
	download = response.read()
	if len(download) < 100000:
		raise Exception('it seems the download failed')	
	m = hashlib.sha256()
	m.update(download)
	return m.hexdigest()

if (len(sys.argv)) is not 3 or "-h" in sys.argv or "--help" in sys.argv:
    print "usage: " + sys.argv[0] + " <cask.rb> <new-version>"
    print "for example: " + sys.argv[0] + " /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/firefox.rb 66.0"
    sys.exit(1)

fe = open(sys.argv[1])
cask = fe.read()

url = cask.split("  url \"")[1].split("\"")[0]
version = sys.argv[2]

for line in cask.split("\n"):
	if line.startswith("  version '"):
		print "  version '" + version + "'"
	elif line.startswith("    sha256 '"):
		language = cask.split(line)[1].split("'")[1].split("'")[0]
		print "    sha256 '" + getsha(url, version, language) + "'"
	else:
		print line

```

code should be considered public domain, please add or use however you see fit.

**Comment by vitorgalvao** [comment]
Would it be too hard to add a `usage` to the script that would be called:

1. If the script is called with no arguments.
2. If the script is called with `-h` or `--help`.

If that could be done, we could add this to the scripts dir in this repo, and I’d point `cask-repair` to it on `language` casks.

**Comment by core-code** [comment]
usage is already given in the „noargs“ case, i can add the other one tomorrow

**Comment by core-code** [comment]
updated it for -h and --help

**Comment by core-code** [comment]
should i do any further changes?

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/61084
