### ISSUE TITLE
Homebrew cask instructed me to report this message

### ISSUE THREAD

**Issue by izaakm** [Homebrew/homebrew-cask#60674]
```
$ brew cask outdated
Warning: Unexpected method 'license' called on Cask google-drive.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Warning: Unexpected method 'license' called on Cask handbrakecli.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Warning: Unexpected method 'license' called on Cask plex-home-theater.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
```

#### General troubleshooting steps

- [na] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

{{replace this}}

#### Command that failed

```
{{replace this}}
```

#### Output of command with `--force --verbose --debug`

```
{{replace this}}
```

#### Output of `brew cask doctor`

```
{{replace this}}
```

#### Output of `brew tap`

```
{{replace this}}
```

**Comment by cixtor** [comment]
None of these programs are in the repository:

```
$ cask cat google-drive
  Error: Cask 'google-drive' is unavailable
  No Cask with this name exists.

$ cask cat handbrakecli
  Error: Cask 'handbrakecli' is unavailable
  No Cask with this name exists.

$ cask cat plex-home-theater
  Error: Cask 'plex-home-theater' is unavailable
  No Cask with this name exists.
```

Please update the issue to include all the information that we are asking you to include. For example, you forgot to include the output of `brew tap` so I have no idea what Taps you have installed. Do you see all those `{{replace this}}`? Please follow the instructions and update your issue to add the missing details.

**Comment by vitorgalvao** [comment]
> Please update the issue to include all the information that we are asking you to include

Welcome @cixtor, and thank you for trying to help other Homebrew Cask users. But please avoid using “we” when doing so can make the user think you’re part of the maintainers team. We’ve had problems in the past with users doing so, as they often give wrong information. For example, in this case your commands just spell `cask`, and not `brew cask`, which is not helpful. Furthermore, in this particular case I actually don’t need the extra information.

@izaakm Those are old casks we no longer carry. Do:

```
brew cask uninstall --force google-drive handbrakecli plex-home-theater
rm -rf "$(brew --prefix)/Caskroom/{google-drive,handbrakecli,plex-home-theater}
brew install handbrakecli
```

For the `google-drive` and `plex-home-theater` alternatives, do a `brew search`.

**Comment by izaakm** [comment]
@vitorgalvao will do, thanks. The instructions you provided are helpful. Is it possible to give users a more specific message in these cases? Eg, 'cask is deprecated'.
