### ISSUE TITLE
Custom cask alias support

### ISSUE THREAD

**Issue by nrlquaker** [Homebrew/homebrew-cask#61148]
### Description of feature/enhancement

Custom cask alias support like in [homebrew](https://github.com/Homebrew/homebrew-aliases). 

### Justification

Its possible in homebrew. I think it would be nice to have it in cask as well. Maybe its possible to use aliases set up by `homebrew-aliases`. Not sure maybe its already discussed. But I haven't found any mentioning of it. 

### Example use case
```
brew cask alias out='outdated'
brew cask out
```

**Comment by vitorgalvao** [comment]
That which you linked is an external command. To add support for casks, you’ll need to discuss it with them.
