### ISSUE TITLE
Unable to help updating cask 'r-app', shows no such cask in official repo

### ISSUE THREAD

**Issue by zizhenc** [Homebrew/homebrew-cask#61306]
#### General troubleshooting steps

- [ * ] I have retried my command with `--force`.
- [ * ] I ran `brew update-reset && brew update` and retried my command.
- [ * ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ * ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ * ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.
- [ * ] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [ * ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I am dealing with the cask 'r-app' (NOT the 'r' in brew). I used brew cask installed 'r-app' before. Then R official released r-app 3.5.3 on 3/11/2019, but until now the brew cask still hasn't update the cask version.

{{I just tried helping contibution of updating the cask version 'r-app' using 'cask-repair r-app' but it shows an error: "No such cask was found in any official repo (r-app)." This is impossible, I even can use brew cask info to get information of cask 'r-app'}}

#### Command that failed

```
{{cask-repair r-app}}
```

#### Output of command with `--force --verbose --debug`

```
{{cask-repair: unrecognized option: --force
Try `cask-repair --help` for more information.}}
```

#### Output of `brew cask doctor`

```
{{replace this}}
```

#### Output of `brew tap`

```
{{replace this}}
```

**Comment by vitorgalvao** [comment]
`brew cask uninstall --force r-app; brew cask install r`.

Next time, please fill the template, and remove the `{{` and `}}`.
