### ISSUE TITLE
Website Domain Expired

### ISSUE THREAD

**Issue by AdrianTP** [Homebrew/homebrew-cask#61347]
#### General troubleshooting steps

None of these are relevant to this issue

#### Description of issue

The website http://caskroom.io leads to a page talking about buying Instagram followers. I cannot find any contact information for Homebrew or Caskroom devs, so I came here.

The last Archive.Org backup copy is from 10 January 2019 (https://web.archive.org/web/20190110103338/http://caskroom.io/)

Here's the whois record, showing that it expired on 1 April

```Domain Name: CASKROOM.IO
Registry Domain ID: D503300000086816624-LRMS
Registrar WHOIS Server: whois.names.plus
Registrar URL: https://www.NAMES.plus
Updated Date: 2018-05-31T20:31:01Z
Creation Date: 2018-04-01T10:07:47Z
Registry Expiry Date: 2019-04-01T10:07:47Z
Registrar Registration Expiration Date:
Registrar: www.NAMES.plus
Registrar IANA ID: 700750
Registrar Abuse Contact Email: hello@names.plus
Registrar Abuse Contact Phone: +1.8669962198
Reseller:
Domain Status: ok https://icann.org/epp#ok
Registrant Organization: humbly LLC
Registrant State/Province: PA
Registrant Country: US
Name Server: MASTER.HOSTSILA.COM
Name Server: SLAVE.HOSTSILA.NET
DNSSEC: unsigned

The Registrar of Record identified in this output may have an RDDS service that can be queried for additional information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.
```

#### Command that failed

http://caskroom.io

#### Output of command with `--force --verbose --debug`

This is not relevant to this issue

#### Output of `brew cask doctor`

This is not relevant to this issue

#### Output of `brew tap`

This is not relevant to this issue

**Comment by vitorgalvao** [comment]
#52164
#52119
#51928
#51167
#51050
#53375
#55440
#57676
