### ISSUE TITLE
Not able to update eclipse-jee using "brew cask upgrade eclips-jee"

### ISSUE THREAD

**Issue by sukanth** [Homebrew/homebrew-cask#61455]
#### General troubleshooting steps

- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

i am trying to upgrade the cask command eclipse-jee and it fails with the following error

Error: Cask 'eclipse-jee' definition is invalid: invalid 'depends_on macos' value: ":leopard"

#### Command that failed

```
brew cask upgrade eclipse-jee
```

#### Output of command with `--force --verbose --debug`

```
➜  ~ brew cask upgrade eclipse-jee --force --verbose --debug
==> Upgrading 1 outdated package:
Error: Cask 'eclipse-jee' definition is invalid: invalid 'depends_on macos' value: ":leopard"
/usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:211:in `rescue in depends_on'
/usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:208:in `depends_on'
/usr/local/Caskroom/eclipse-jee/.metadata/4.10.0,2018-12:R/20181220064828.239/Casks/eclipse-jee.rb:9:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:48:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:48:in `config='
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:39:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:33:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:33:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:73:in `cask'
/usr/local/Caskroom/eclipse-jee/.metadata/4.10.0,2018-12:R/20181220064828.239/Casks/eclipse-jee.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:60:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:60:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:176:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:38:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:34:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:90:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:161:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:161:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:144:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

#### Output of `brew cask doctor`

```
➜  ~ brew cask doctor
==> Homebrew Version
2.1.0-4-g9a4fc66
==> macOS
10.14.4
==> SIP
Enabled
==> Java
1.8.0_191, 1.7.0_80
==> Gatekeeper support
```

#### Output of `brew tap`

```
➜  ~ brew tap
caskroom/cask
homebrew/cask
homebrew/cask-versions
homebrew/core
```

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/issues/58046

**Comment by sukanth** [comment]
I am still getting this error .. any help is appreciated.
![image](https://user-images.githubusercontent.com/8810504/55731658-30ee9800-59e0-11e9-82d1-0ed35d633a30.png)

**Comment by vitorgalvao** [comment]
@sukanth Read [the linked issue](https://github.com/Homebrew/homebrew-cask/issues/61455#issuecomment-480516004). The solution is in the first post.

**Comment by vitorgalvao** [comment]
Also, do `brew untap caskroom/cask`.

**Comment by sukanth** [comment]
@vitorgalvao  Thank you very much .. it worked
