### ISSUE TITLE
vulkan-sdk cask

### ISSUE THREAD

**Issue by apenngrace** [Homebrew/homebrew-cask#61639]
Last August @vitorgalvao and I discussed in [this thread](https://github.com/Homebrew/homebrew-cask/issues/51330#event-1958163894) a cask for the vulkan-sdk.  In your message, you said: 

> @apenngrace I’m sympathetic to your case, but I doubt this is used by enough people to warrant the trouble (would have to check the analytics).

Regarding user interest, I have had pretty consistent daily traffic for my cask (even though it is a private tap).  Would you re-consider allowing this cask to be part of the homebrew-cask repo again?  

As we discussed months ago, there is currently no build from source option for this project... even though it is theoretically possible.  In the meantime, there is duplicate formulae appearing such as `vulkan-headers` that only installs headers whereas my cask installs all assets in a functional manner that can be tested on the command line with the `vulkaninfo` command after installation.

**Comment by vitorgalvao** [comment]
> Would you re-consider allowing this cask to be part of the homebrew-cask repo again?

Your stats do indeed show demand for it:

```
30 days: #753 | vulkan-sdk | 68
90 days: #1023 | vulkan-sdk | 128
365 days: #1030 | vulkan-sdk | 330
```

But the rest of the [quoted post](https://github.com/Homebrew/homebrew-cask/issues/51330#issuecomment-427667839) did not change:

> There won’t be a “for the time being”. If it’s readded it’ll be here indefinitely, and when it can be removed you/other users of this will likely no longer care/remember to remove the cask, leaving it as an extra thing for maintainers to care for for little gain. You haven’t solved any of my worries of the previous comment.

That said, I was indeed willing to reconsider (by the way, thank you for asking!) until I saw [the current cask](https://github.com/apenngrace/homebrew-vulkan/blob/master/Casks/vulkan-sdk.rb). It’s really well organised (kudos) but it’s also incredibly different from every other cask in the main repos and full of workarounds, which mean maintenance burden. Right now you seem like the most qualified person to care for that cask, and it seems to be going well.

However, I will leave this issue open and add a `awaiting maintainer feedback` label until the bot auto-closes (about a month from now), in case another maintainer feels differently.

And again, thank you for asking and the good work maintaining the cask.

**Comment by apenngrace** [comment]
I appreciate your response.  I figured I’d ask to allow for the vulkan-sdk to be more discoverable with just an easy`brew search` command rather than having to find my cask other ways.

Let me know if there is anything I can do to restructure the code to your standards.  Although, the part of the code I'm not sure how I would change is the part rewriting JSON to fix file paths.

**Comment by apenngrace** [comment]
> Your stats do indeed show demand for it:
> 
> ```
> 30 days: #753 | vulkan-sdk | 68
> 90 days: #1023 | vulkan-sdk | 128
> 365 days: #1030 | vulkan-sdk | 330
> ```

By the way, is there a way for me to be able to access those stats?

**Comment by vitorgalvao** [comment]
> By the way, is there a way for me to be able to access those stats?

Yes. All [stats are public](https://formulae.brew.sh/analytics/).
