### ISSUE TITLE
Error: Cask 'itsycal' definition is invalid: invalid 'depends_on macos' value: ":mountain_lion"

### ISSUE THREAD

**Issue by gbstan** [Homebrew/homebrew-cask#61781]
brew cask upgrade triggers the following error on itsycal:

Error: Cask 'itsycal' definition is invalid: invalid 'depends_on macos' value: ":mountain_lion"

**Comment by gbstan** [comment]
Fixed with the command that was recommended in the thread on this type of error, i.e.
/usr/bin/find "$(brew --prefix)/Caskroom/"*'/.metadata' -type f -name '*.rb' -print0 | /usr/bin/xargs -0 /usr/bin/perl -i -0pe 's/depends_on macos: \[.*?\]//gsm;s/depends_on macos: .*//g'

This can be closed

**Comment by mzimann** [comment]
Commenting out the `depends_on` line in the file `/usr/local/Caskroom/itsycal/.metadata/0.11.13/20181119101014.417/Casks/itsycal.rb` and then running `brew cask upgrade` fixed it for me.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/issues/58046.

Also:

> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
