### ISSUE TITLE
NetBeans casks are all pointing to massively outdated versions

### ISSUE THREAD

**Issue by StoppingBuck** [Homebrew/homebrew-cask#61796]
#### Description of issue

NetBeans casks are pointing to obsolete, pre-Apache versions of NetBeans.

There seems to be 6 current NetBeans casks:
* netbeans.rb
* netbeans-html.rb
* netbeans-cpp.rb
* netbeans-php.rb
* netbeans-java-se.rb
* netbeans-java-ee.rb

All six of these are currently pointing to NetBeans 8.2, which was released back in 2016 and has loooooooong since been deprecated, as NetBeans has been handed from Oracle to the [Apache Incubator](http://incubator.apache.org/).

As of April 11th 2019, the current NetBeans version is [NetBeans 11](https://netbeans.apache.org/download/nb110/nb110.html).

It's worth noting that NetBeans is currently in the 'incubating' stage - meaning Apache is working on making it a fully-fledged Apache Project. However, I don't think that should be considered as a 'beta' stage in the traditional sense -- and regardless, the casks should be updated since 8.2 doesn't even support newer versions of Java, meaning that if you install both `java` and `netbeans` through Homebrew, NetBeans is gonna go tits up when you try to use it (made that mistake myself, and it took a good long time before realizing I was running 2016-era NetBeans!)

**Comment by vitorgalvao** [comment]
Care to submit the updates?

**Comment by core-code** [comment]
AFAIK there are no pre-compiled Mac binaries of NetBeans 10 or 11.

**Comment by ran-dall** [comment]
> Experimental installers for Apache NetBeans 11.0 are available [here](https://github.com/rtaneja1/incubator-netbeans/tree/installer-bin-11vc4/nbbuild/installer/binaries), however note these have not been validated by Apache yet, which is scheduled for the next release, based on work done in [PR-1052](https://github.com/apache/incubator-netbeans/pull/1052).

**Comment by vitorgalvao** [comment]
Let’s revisit next release, then. These have tons of users, somebody is bound to submit updates for them.
