### ISSUE TITLE
android-sdk cask installs to strange directory configuration

### ISSUE THREAD

**Issue by tedneward** [Homebrew/homebrew-cask#61993]
When installing `brew cask install android-sdk`, the result is strange to me; there's a "tools" directory in /usr/local/share/android-sdk, but it contains a subdirectory matched to the version number of the cask, and then the rest of the Android SDK is installed to a different location. Can you give me an idea of what location I'm supposed to provide to tools like Android Studio for the location of the SDK? (Many of them, like Visual Studio for Mac, seem to like to reverse the link and end up linking to /usr/local/Caskroom/android-sdk, and that doesn't seem to be correct either.) It feels like there's a slight mismatch about where the tools are going and where the rest of the SDK is going; I don't know if this is behavior "as intended" or not.

Homebrew checks out (brew doctor is happy).

**Comment by vitorgalvao** [comment]
Do `brew cask cat android-sdk`. The places it affects should be clear. If they’re not, please ask on our discourse that not a bug tracker, since your question is Android-dev related, not Hmebrew Cask-related.

**Comment by tedneward** [comment]
And what if the places it affects are not correct? In particular, as I've already commented, the version appears in the file path?

Never mind. It's just easier to manage the install by hand once and not bother with brew for this one.

Ted Neward
Sent from my iPhone


On Apr 16, 2019, at 15:01, V?tor Galv?o <notifications@github.com<mailto:notifications@github.com>> wrote:


Do brew cask cat android-sdk. The places it affects should be clear. If they're not, please ask on our discourse that not a bug tracker, since your question is Android-dev related, not Hmebrew Cask-related.

-

**Comment by vitorgalvao** [comment]
> And what if the places it affects are not correct?

Then you should submit a PR to fix those. None of the HBC maintainers are Android developers so we don’t know the best places for this to install. But this cask is popular and everyone else seems happy with it as it is.

> Never mind. It's just easier to manage the install by hand once and not bother with brew for this one.

If you’re going to have that attitude, then I’d prefer if you didn’t comment or open issues at all. That attitude isn’t productive and wastes our time. This project does mot exist for you and we’re not here to make you favours.

You didn’t even follow the rules explicit in the template and other places, that clearly state your issue may be closed without review if you don’t follow said template, so you already got a freebie.
