### ISSUE TITLE
[Feature request] New retired command and an upgrade path

### ISSUE THREAD

**Issue by dmlemos** [Homebrew/homebrew-cask#62017]
#### Description of feature/enhancement

Today I found out that I ended up with a retired cask `torbrowser`. Looking at it, the cask was retired in favour of a name change.

The error produced is similar to other issues already reported:
```
Warning: Unexpected method 'gpg' called on Cask torbrowser.
```

This happens with any command that deals with interpreting the cask file (my guess):
```sh
brew cask list
brew cask oudated
brew cask zap
```

Too frequently these errors happen and I wanted to suggest something that could help better tackle this particular situation.
I'd like to propose a new command `retired` to show the casks that are currently installed that are no longer supported. With a resemblance to to the `outdated` command.

Additionally, afaik the `tap-migrations` does not have support for an _upgrade path_. It's when a new cask of the same program is introduced, but with a different name, and in result deprecating the old one (with or without the old formula being removed). It can happen for various reasons, usually due to OS incpompatibilies/architecture differences. The point is that the user would have a way to know the _upgrade_path_ and move to the new formula without hassle. This could come in the form of a new stanza `update_path`, containing the list of the old formulas that this new formula is the upgrade to.

#### Justification

When casks are retired, sometimes it is due to program being deprecated, but other times it could be a name change for some reason, migration to a different cask, or a new version of the cask that is a significantly different to justify a new cask.

Nevertheless the user with the old formula is left with:
* Old cask is removed from brew
* _Core_ brew commands start showing errors that are not related with `brew` itself
* User has no idea that the cask was deprecated
* User has no way of checking for _upgrade_path_

Given the value of the `outdated` feature, I see the value for this in the same way.

#### Example use case

In this example, and let's assume this is true, the cask for `torbrowser` got deprecated in favour of `tor-browser`.
After the update or `brew cask list`, it should notify to the user that there are retired casks, which can be viewed and reported with `brew retired`.

Additionally if `_upgrade_path` is specified, `brew` could prompt the user interactively to move to the new formula, removing traces of the old one.

**Comment by vitorgalvao** [comment]
`tap-migrations` is definitely the best tool to tackle this, in part because there’s already some code written for it, in the non-Cask part.

Before we can even consider anything else, `tap-migrations` needs to be implemented.

**Comment by dmlemos** [comment]
Wouldn't mind sharing or pointing to where we can follow development of `tap-migrations`?

**Comment by vitorgalvao** [comment]
> Would you mind sharing or pointing to where we can follow development of `tap-migrations`?

There is none. We want the feature (there may be an open issue, but even if there is not, it is something we know we need) but no one is working on it as of now. It’s wide open.

**Comment by dmlemos** [comment]
Ok. It is great to know that there is a demand for it. I hope my proposal incites someone to develop it 🎈
