### ISSUE TITLE
Rewrite "Checksum does not match" page

### ISSUE THREAD

**Issue by philliplongman** [Homebrew/homebrew-cask#62026]
I just started to file a bug about a cask that won't upgrade. It turns out the issue is that Logitech hasn't bothered to produce a version of Logitech Unifying that officially supports Mojave, even six months after it's release. So it looks like Homebrew is behaving as expected when it won't install.

Having gone through the troubleshooting checklist, I really think someone should re-write [this page](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) from the point of view of a user with _a lot_ less knowledge. Even having figured out that `shasum` is a shell command, I still don't know what "`Actual` shasum line" means. And it's not until page three of Google results for "appcast" that I found a page relating to the Sparkle framework (which I was familiar with, but others may not be).

I realize you're trying to filter out unnecessary issues, but I think you may be forcing people to figure out a little too much here, and you're very insistent that they do this step.

**Comment by vitorgalvao** [comment]
> Even having figured out that `shasum` is a shell command, I still don't know what "`Actual` shasum line" means.

Example of an error message:

```
Error: Checksum for Cask 'magicavoxel' does not match.

Expected: a7c09a0178d4fd8b6484eae479b2b8f2daf60b8a0b39ba418981846906924e49
Actual:   d7c09a0178d4fd8b6484eae479b2b8f2daf60b8a0b39ba418981846906924e49
File:     /Users/username/Library/Caches/Homebrew/downloads/0050eb411cfaffaccecbbf861a33827b9b4108a715341f3af8cd944d6a6f8ea5--MagicaVoxel-0.99.3-alpha-macos.zip
```

There’s an `Actual:   d7c09a0178d4fd8b6484eae479b2b8f2daf60b8a0b39ba418981846906924e49` line. Under that is a `File:` line.

> And it's not until page three of Google results for "appcast" that I found a page relating to the Sparkle framework (which I was familiar with, but others may not be).

You don’t need to know what an appcast is, or search online. You needed only to run the suggested command.

I’ve simplified the instructions to the easiest ones: https://github.com/Homebrew/homebrew-cask/pull/62073/files.
