### ISSUE TITLE
Unable to download Racket installer

### ISSUE THREAD

**Issue by vky** [Homebrew/homebrew-cask#62029]
#### General troubleshooting steps

- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

When attempting to install Racket, the download fails with the current url in the formula:

https://mirror.racket-lang.org/installers/7.2/racket-7.2-x86_64-macosx.dmg

Attempting to manually download this file from the [source website](https://download.racket-lang.org/racket-7-2-x86_64-macosx-dmg.html) directly for that link also fails.

I updated the url in the formula to another mirror that's available on the website, and that succeeds. I used the url https://plt.eecs.northwestern.edu/racket-mirror/7.2/racket-7.2-x86_64-macosx.dmg.

#### Command that failed

```
brew cask install racket
```

**Comment by vitorgalvao** [comment]
Since that link is still on the page, we have no reason to believe this is not temporary.
