### ISSUE TITLE
Continue upgrading other casks when one cask fails

### ISSUE THREAD

**Issue by philliplongman** [Homebrew/homebrew-cask#62028]
### Description of feature/enhancement

When upgrading multiple casks, if a cask fails to upgrade, don't stop the upgrade task. Keep upgrading the others and display the error at the end.

### Justification

I had a cask that wouldn't upgrade for months, but it wasn't a bug. Logitech just has not released a version of the software that officially supports Mojave. Because this cask brought the upgrade task to a halt, I had to upgrade around it, explicitly entering in all the other cask names. It was annoying.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/brew/issues/5203
