### ISSUE TITLE
Please update the javadoc cask every time java  is updated

### ISSUE THREAD

**Issue by bondolo** [Homebrew/homebrew-cask#62195]
### Description of feature/enhancement

Whenever the java cask is updated please update the javadoc cask. I have previously submitted independent updates to javadoc but it is just silly to not do both at the same time.

### Justification

javadoc is always released at the same time as java releases. For anyone doing development it is essential to have javadoc. Given how javadoc is installed by homebrew it is advantageous to install both at the same time. 

### Example use case

n/a

**Comment by vitorgalvao** [comment]
Updates are submitted by users. We have several [“families” that ideally should be updated at the same time](https://github.com/Homebrew/homebrew-cask/blob/9cfc0d054661ff95817fe3483dc05c150684fa72/developer/bin/update_cask_family#L4) but we have no control over what users submit.
