### ISSUE TITLE
New strategy for `.metadata`

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-cask#62223]
When we install a cask, we keep a copy of it at that moment in a `.metadata` directory. This method causes problems when we remove a feature from the core, as the old casks throw errors when read back. An example of widespread breakage due to this method is https://github.com/Homebrew/homebrew-cask/issues/58046.

https://github.com/Homebrew/brew/pull/4730#issuecomment-415322677 suggests a few alternative to the current method. The first one is the most viable: when reading a cask in `.metadata`, if it gives an error, ignore it and read the current cask.

**Comment by reitermarkus** [comment]
> The only thing we need from the cask copy is the uninstall logic.

Actually, we need everything. In case an upgrade fails, we should still be able to reinstall the old version.

**Comment by vitorgalvao** [comment]
> Actually, we need everything. In case an upgrade fails, we should still be able to reinstall the old version.

Edited the top post to only reference the first option.

**Comment by vitorgalvao** [comment]
I’ve been thinking a bit more about this. The top post include another suggestion:

> The only thing we need from the cask copy is the uninstall logic. When installing, instead of keeping a copy of the cask, create an uninstall bash script. We already run system commands via ruby to perform the uninstallation anyway, so might as well save those commands.

That was removed due to the point that [we need everything, in the case of an upgrade fail](https://github.com/Homebrew/homebrew-cask/issues/62223#issuecomment-485206817). But how often does that happen? We could just as well do both. We always uninstall from the shell script, and only reference the `.metadata` cask if an upgrade fails. At which point, if that fails we’re back where we started, but in the way we’ve already got rid of most errors by offloading uninstall to script.

**Comment by MikeMcQuaid** [comment]
> [Homebrew/brew#4730 (comment)](https://github.com/Homebrew/brew/pull/4730#issuecomment-415322677) suggests a few alternative to the current method. The first one is the most viable: when reading a cask in `.metadata`, if it gives an error, ignore it and read the current cask.

I think we should do this. We're getting more and more reports of this and the status-quo is pretty untenable and undesirable. Any objections?

**Comment by vitorgalvao** [comment]
> I think we should do this. We're getting more and more reports of this and the status-quo is pretty untenable and undesirable. Any objections?

None whatsoever. We should also think about what to do if the failing cask no longer exists. My suggestion would be to inform the user they’ll need to uninstall it manually, `cat` the cask, and remove its directory from the Caskroom (so it no longer shows as installed).

**Comment by cpcallen** [comment]
Pending resolution, might it be worth retitling this issue so that people looking for bugs related to ``Error: Cask '…' is unreadable: undefined method `undent'`` can find it more easily?

**Comment by vitorgalvao** [comment]
> Pending resolution, might it be worth retitling this issue so that people looking for bugs related to `` Error: Cask '…' is unreadable: undefined method `undent' `` can find it more easily?

That’s *a* prevalent issue arising from this, but far from the only one. `Unexpected method 'license' called on Cask` is another one.

**Comment by cpcallen** [comment]
> That’s _a_ prevalent issue arising from this, but far from the only one.

Sure, I understand.  The more the merrier.

**Comment by MikeMcQuaid** [comment]
Have looked into this and found it non-trivial. I would suggest @reitermarkus would be the best fit for this, if willing.

A starter to reproduce is editing the metadata file e.g. `/usr/local/Caskroom/meetingbar/.metadata/2.0/20201125113824.338/Casks/meetingbar.rb` to add `.undent` onto a random string and then try to `brew uninstall meetingbar` (or any other command that operates on it).

**Comment by MikeMcQuaid** [comment]
May be worth making this `help wanted` on Homebrew/brew for visibility.

**Comment by Kobold** [comment]
Currently stuck on this. Another vote for whatever can be done! My `brew doctor` output:

```
❯ brew doctor --verbose --debug
Warning: Unexpected method 'license' called on Cask gpgtools.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Warning: Unexpected method 'gpg' called on Cask gpgtools.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Warning: Unexpected method 'license' called on Cask java.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Error: Cask 'java' is unreadable: undefined method `undent' for #<String:0x00007f95b3014f50>
/usr/local/Caskroom/java/.metadata/1.8.0_102-b14/20160929221813.341/Casks/java.rb:70:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:61:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:61:in `config='
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:48:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:43:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:43:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:87:in `cask'
/usr/local/Caskroom/java/.metadata/1.8.0_102-b14/20160929221813.341/Casks/java.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:72:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:72:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:45:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:39:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:39:in `casks'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:51:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

**Comment by vitorgalvao** [comment]
@Kobold `rm -rf "$(brew --caskroom)/"{java,gpgtools}`. You have very old installations of casks that no longer exist. This is not the issue to ask for help, though. For the next problem, please open a new issue or search as this has been repeated several times.

**Comment by Kobold** [comment]
Thank you for the help @vitorgalvao! I wasn't seeking help though, there are 5 or 8 closed issues repeating my issue — what I was running into seemed like an instance of the problem this ticket aims at addressing, and just wanted to bump the thread reiterating @MikeMcQuaid from October:

> We're getting more and more reports of this and the status-quo is pretty untenable and undesirable.

**Comment by vitorgalvao** [comment]
Thank you, but we don’t need votes or bumps on this, we’re all in agreement this is a problem and want it fixed.

Right now we need a PR.

**Comment by MikeMcQuaid** [comment]
Finally opened a fix for this in https://github.com/Homebrew/brew/pull/13289
