### ISSUE TITLE
How install java8 using brew cask

### ISSUE THREAD

**Issue by mxavierx** [Homebrew/homebrew-cask#62350]
#### General troubleshooting steps

- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Not able to install java8.

#### Command that failed

```
brew cask install java8
brew cask install caskroom/versions/java8
```

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask-versions/issues/7253

**Comment by mxavierx** [comment]
Thnx!
