### ISSUE TITLE
Merge menumeters and yujitach-menumeters

### ISSUE THREAD

**Issue by sbliven** [Homebrew/homebrew-cask#62412]
### Description of feature/enhancement

There are currently two recipes providing the MenuMeters app:
- [menumeters](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/menumeters.rb) provides version 1.8.1 from ragingmenace.com and works up to yosemite
- [yujitach-menumeters](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/yujitach-menumeters.rb) provides 1.9.3 through 1.9.7 and works on el-capitan and newer.

These packages provide the same software, but the current version is much harder to find and install due to the prefix. I propose that they be merged into a single 'menumeters' recipe, where the download location is selected based on the OS version.

### Justification

The original ragingmenace branch has been defunct since 2015, while the yujitach fork continues to be maintained and regularly released. They provide the same software and are mutually incompatible due to the non-overlapping OS restrictions. 

### Example use case

I would expect the following to work on a modern system:
```
brew cask install menumeters
```

**Comment by vitorgalvao** [comment]
Agreed. https://github.com/Homebrew/homebrew-cask/pull/62422.
