### ISSUE TITLE
textricator cask sets invalid classpath, fails to start

### ISSUE THREAD

**Issue by gkertai** [Homebrew/homebrew-cask#62500]
## Description of issue

`brew cask install textricator` installs the application just fine, but the symlinked bootstrap file `/usr/local/bin/textricator` fails to run with the error message: *Could not find or load main class io.mfj.textricator.cli.TextricatorCli*

If you launch it from the original install location `/usr/local/Caskroom/textricator/9.0.44/textricator-9.0.44/textricator` it runs.

## Cause

The bootstrap file sets the Java class path based on its own directory…
```
#!/usr/bin/env bash
java -cp "$(dirname $0)/lib/*" ${JAVA_OPTS} io.mfj.textricator.cli.TextricatorCli "$@"
```

…which for the symlinked file will point to `/usr/local/bin/lib/*`. It should be pointing to `/usr/local/Caskroom/textricator/9.0.44/textricator-9.0.44/textricator/lib/*` instead.

## Workaround

Until the cask is fixed, you can set an alias for the installed bootstrap file:

```bash
alias textricator=$(readlink $(which textricator))
```

**Comment by vitorgalvao** [comment]
This might be solved with a [shim script](https://github.com/Homebrew/homebrew-cask/search?q=shim+script).

PRs welcome. If the cask continues broken by the time the cleanup bot arrives at this issue, we’ll remove the cask instead. It’s not popular, hence not worth the trouble.

```
textricator (added 275 days ago)
30 days: 2 (#4294)
90 days: 2 (#5408)
365 days: 9 (#4924)
```

**Comment by gkertai** [comment]
Thanks for the tip! Added PR with shim script, app runs fine now. Homebrew is awesome!
