### ISSUE TITLE
qbittorrent: codesign in postinstall?

### ISSUE THREAD

**Issue by holymonson** [Homebrew/homebrew-cask#62523]
qbittorrent is an unsigned app so macOS's Firewall will attempt to block it everytime. It's quite annoying. See https://github.com/qbittorrent/qBittorrent/issues/3885 .

Codesigning the app can fix this issus (https://github.com/qbittorrent/qBittorrent/issues/3885#issuecomment-210352723). But I'm not sure if it's allow codesign in postinstall section in cask script.

If it's not allow, would you please add the how-to in caveats?

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/the_app_cant_be_opened.md

**Comment by vitorgalvao** [comment]
You’re free to do it yourself to your installation, we’re not going to auto-circumvent macOS security features and put users at risk.
