### ISSUE TITLE
Virtualbox download endpoint seems moved to download.oracle.com

### ISSUE THREAD

**Issue by SleepyDeb** [Homebrew/homebrew-cask#62537]
Virtualbox download endpoint seems moved from:
[https://download.virtualbox.org/virtualbox/](https://download.virtualbox.org/virtualbox/)
to:
[https://download.oracle.com/virtualbox/](https://download.oracle.com/virtualbox/)

Envolved files
Casks/virtualbox.rb
Casks/virtualbox-extension-pack.rb

Best regards

**Comment by mbigras** [comment]
This is what the error looks like:

```
brew install virtualbox
Error: No available formula with the name "virtualbox"
Found a cask named "virtualbox" instead.
Maxs-MacBook-Pro-2:laptop max$ brew cask install virtualbox
==> Caveats
To install and/or use virtualbox you may need to enable its kernel extension in:
  System Preferences → Security & Privacy → General
For more information refer to vendor documentation or this Apple Technical Note:
  https://developer.apple.com/library/content/technotes/tn2459/_index.html

==> Satisfying dependencies
==> Downloading https://download.virtualbox.org/virtualbox/6.0.6/VirtualBox-6.0.6-130049-OSX.dmg

curl: (51) SSL: no alternative certificate subject name matches target host name 'download.virtualbox.org'
Error: Download failed on Cask 'virtualbox' with message: Download failed: https://download.virtualbox.org/virtualbox/6.0.6/VirtualBox-6.0.6-130049-OSX.dmg
```

**Comment by Blaisorblade** [comment]
Same here. OTOH, downloading the files by hand from https://www.oracle.com/technetwork/server-storage/virtualbox/downloads/index.html has been failing for the past few hours, so this bug is likely blocked on upstream.

**Comment by vitorgalvao** [comment]
We need upstream to change the download link in the downloads page. Someone please contact them.

**Comment by mbigras** [comment]
Looks like there is a ticket open:
https://www.virtualbox.org/ticket/18610

**Comment by deepio** [comment]
https://forums.virtualbox.org/viewtopic.php?f=1&t=92880&hilit=download
https://github.com/Homebrew/homebrew-cask/pull/62509

Obviously a certificate was issued for the site incorrectly by accident.
@vitorgalvao they (site-moderator socratis on virtualbox's forum) suggest using http with virtualbox or https with oracle.com for now until it is resolved.

**Comment by tomtastic** [comment]
Forum link says it's due to be fixed tomorrow...

**Comment by Blaisorblade** [comment]
Thanks for the link! For now, one can install the pkgs by hand, or still use Cask by editing the formulas; I just replaced https by http in the `url "..."` lines, in
`/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/virtualbox-extension-pack.rb` and
`/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/virtualbox.rb`, and cask install then worked.

**Comment by deepio** [comment]
It's fixed, I just tried the link and it works. Someone from the Homebrew team can close the issue now.
