### ISSUE TITLE
Can we add CocoaPacketAnalyzer back in?

### ISSUE THREAD

**Issue by zengxs** [Homebrew/homebrew-cask#62546]
I noticed that the cask had been removed because it had been provided by the Mac App Store. (#45602)

However, the App Store version lacks a key feature, capture packets.
And the version download from the official website have it. 

Download link: <http://www.tastycocoabytes.com/_downloads/CPA_151.dmg>

Screenshot of official website version:
![screenshot1](https://i.imgur.com/wxPcZk3.png)

Screenshot of Mac App Store version:
![screenshot2](https://i.imgur.com/iqYsHK7.png)

**Comment by reitermarkus** [comment]
Feel free too re-add it.

**Comment by vitorgalvao** [comment]
As stated by the template, we don’t take requests. But as @reitermarkus mentioned, if *you* want to readd it, please do.
