### ISSUE TITLE
A review of `binary`-only casks

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-cask#62715]
This is a continuation of https://github.com/Homebrew/brew/pull/5724/files#r256898140.

In that thread, to advance the goal of lessening the confusion users have between `brew` and `brew cask`, the following rule was suggested:

> “if [you] want the CLI, `brew`, if you want the GUI, `brew cask` but it would also bring the CLI that typically comes in the package”

And

> To push the point further, maybe CLI-only casks (closed-source) should be removed as well.

For that second point it was suggested we look at the analytics, which is what this issue is about. The rule for inclusion was casks that include `binary` but not `pkg`, `app`, or `suite`. Some of these are open-source but can’t be built (or would be too complex) as formulae.

They are ordered by number of downloads in the last 365 days. Of the casks in the table, only 2 are not in the main repo: [nordic-nrf5x-command-line-tools](https://github.com/Homebrew/homebrew-cask-drivers/blob/master/Casks/nordic-nrf5x-command-line-tools.rb) and [chromedriver-beta](https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/chromedriver-beta.rb).

It’s clear from these results we can’t remove `binary`-only casks without upsetting thousands of users, so that’s a no-go for the time being. However, we should continue to think of ways to make the `brew`/`brew cask` divide clearer.

| cask | 30d | 90d | 365d |
|------|:---:|:---:|:----:|
| [minikube](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/minikube.rb) | 13,958 | 43,475 | 107,029 |
| [android-platform-tools](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/android-platform-tools.rb) | 13,251 | 36,055 | 94,566 |
| [chromedriver](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/chromedriver.rb) | 8,499 | 24,223 | 63,225 |
| [android-sdk](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/android-sdk.rb) | 5,061 | 16,072 | 44,099 |
| [google-cloud-sdk](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/google-cloud-sdk.rb) | 3,893 | 11,199 | 28,305 |
| [ngrok](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/ngrok.rb) | 3,279 | 10,082 | 26,369 |
| [phantomjs](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/phantomjs.rb) | 2,476 | 7,803 | 18,933 |
| [minishift](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/minishift.rb) | 1,520 | 4,690 | 11,801 |
| [aws-vault](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/aws-vault.rb) | 1,021 | 3,094 | 7,515 |
| [jet](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/jet.rb) | 374 | 1,160 | 3,234 |
| [1password-cli](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/1password-cli.rb) | 271 | 938 | 2,587 |
| [cscreen](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/cscreen.rb) | 221 | 674 | 1,745 |
| [rar](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/rar.rb) | 324 | 754 | 1,733 |
| [kindlegen](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/kindlegen.rb) | 206 | 615 | 1,601 |
| [oclint](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/oclint.rb) | 386 | 1,161 | 1,442 |
| [borgbackup](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/borgbackup.rb) | 124 | 462 | 1,287 |
| [fly](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/fly.rb) | 104 | 343 | 883 |
| [jad](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/jad.rb) | 88 | 213 | 565 |
| [dynamodb-local](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/dynamodb-local.rb) | 77 | 220 | 553 |
| [dwarf-fortress](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/dwarf-fortress.rb) | 69 | 206 | 468 |
| [perforce](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/perforce.rb) | 62 | 177 | 464 |
| [consul-cli](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/consul-cli.rb) | 45 | 116 | 312 |
| [browserstacklocal](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/browserstacklocal.rb) | 32 | 113 | 306 |
| [corelocationcli](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/corelocationcli.rb) | 30 | 107 | 290 |
| [lunchy](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/lunchy.rb) | 36 | 97 | 252 |
| [nordic-nrf5x-command-line-tools](https://github.com/Homebrew/homebrew-cask-drivers/blob/master/Casks/nordic-nrf5x-command-line-tools.rb) | 38 | 108 | 243 |
| [grads](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/grads.rb) | 24 | 69 | 232 |
| [ghidra](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/ghidra.rb) | 154 | 155 | 155 |
| [sauce-connect](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/sauce-connect.rb) | 23 | 58 | 145 |
| [gmvault](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/gmvault.rb) | 20 | 52 | 123 |
| [steamcmd](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/steamcmd.rb) | 10 | 47 | 116 |
| [jtool](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/jtool.rb) | 21 | 46 | 115 |
| [eventstore](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/eventstore.rb) | 24 | 75 | 97 |
| [minecraft-server](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/minecraft-server.rb) | 10 | 42 | 88 |
| [operadriver](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/operadriver.rb) | 8 | 21 | 85 |
| [dusty](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/dusty.rb) | 5 | 17 | 81 |
| [sublercli](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/sublercli.rb) | 8 | 30 | 76 |
| [red](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/red.rb) | 5 | 13 | 74 |
| [hab](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/hab.rb) | 2 | 8 | 52 |
| [rq](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/rq.rb) | 11 | 17 | 50 |
| [mars](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/mars.rb) | 8 | 22 | 49 |
| [joker](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/joker.rb) | 5 | 15 | 48 |
| [logisim-evolution](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/logisim-evolution.rb) | 3 | 21 | 46 |
| [wercker-cli](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/wercker-cli.rb) | 5 | 12 | 43 |
| [adobe-air-sdk](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/adobe-air-sdk.rb) | 5 | 18 | 42 |
| [manuskript](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/manuskript.rb) | 6 | 17 | 41 |
| [crystax-ndk](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/crystax-ndk.rb) | 6 | 13 | 40 |
| [gogs](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/gogs.rb) | 2 | 3 | 40 |
| [livetail](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/livetail.rb) | 4 | 6 | 37 |
| [chromedriver-beta](https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/chromedriver-beta.rb) | 35 | 35 | 35 |
| [spatial](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/spatial.rb) | 1 | 7 | 33 |
| [simplistic](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/simplistic.rb) | 2 | 8 | 31 |
| [jsl](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/jsl.rb) | 1 | 6 | 31 |
| [parse](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/parse.rb) | 6 | 12 | 30 |
| [activitywatch](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/activitywatch.rb) | 15 | 28 | 28 |
| [subgit](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/subgit.rb) | 2 | 8 | 23 |
| [cmucl](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/cmucl.rb) | 3 | 6 | 22 |
| [procexp](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/procexp.rb) | 1 | 3 | 17 |
| [happygrep](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/happygrep.rb) | 2 | 5 | 15 |
| [mcrcon](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/mcrcon.rb) | 7 | 11 | 15 |
| [textricator](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/textricator.rb) | 6 | 7 | 14 |
| [streamtools](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/streamtools.rb) | 2 | 9 | 14 |
| [filemon](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/filemon.rb) | 2 | 6 | 14 |
| [hashbackup](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/hashbackup.rb) | 4 | 9 | 14 |
| [hfsleuth](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/hfsleuth.rb) | 3 | 4 | 13 |

**Comment by vitorgalvao** [comment]
cc @MikeMcQuaid

**Comment by wolverian** [comment]
[aws-vault](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/aws-vault.rb) upstream [has said](https://github.com/Homebrew/homebrew-core/pull/3385#issuecomment-236302100) that they prefer casks. I don't know why. One possible reason is signing the binaries.

It would be nice to fix this cask (or formula) to include the upstream shell completion scripts. I couldn't figure out how to add them to the cask, so I added a formula for aws-vault in [my tap](https://github.com/wolverian/homebrew-taps/blob/master/Formula/aws-vault.rb), which includes the completion scripts. I didn't create a PR to homebrew-core since I'm uncertain if it would be accepted.

Ping @lox @mtibben.

**Comment by vitorgalvao** [comment]
> [aws-vault](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/aws-vault.rb) upstream [has said](https://github.com/Homebrew/homebrew-core/pull/3385#issuecomment-236302100) that they prefer casks. I don't know why. One possible reason is signing the binaries.

While upstream input is valuable, a single vendor’s opinion makes no difference. We’re looking for something that can be applied in a consistent manner.

> I didn't create a PR to homebrew-core since I'm uncertain if it would be accepted.

Nothing bad will happen if it isn’t accepted, so I don’t understand your reason to not submit a PR. If the work is done either way, submit it. If it’s accepted, your contribution will affect a lot of people; if it’s not, you’ll learn something about our process and we’ll get further knowledge of the software.

I’ll reinforce the goal of this issue:

> However, we should continue to think of ways to make the `brew`/`brew cask` divide clearer.

Answering that question is what replies should focus on.

**Comment by MikeMcQuaid** [comment]
My hot take:

- if it's a CLI and can be a (not ridiculously complicated) built-from-source formula: it should be one (rather than a cask)
- if it's a GUI or cannot be built from source: it should be a cask
- if it's usefully available as either/both: it should have both a formula and a cask we should have a consistent suffix for casks in this situation e.g. `-app`, `.app`, `-gui`, `-cask` or similar.

Reasons insufficient for something being a cask:

- upstream prefers to distribute a binary for any reason that isn't "this is a closed source application"

Reasons insufficient for something being a formula:

- upstream distributes a GUI but it's not consistently kept up to date
- "I prefer things from source"

**Comment by wolverian** [comment]
Thank you, @vitorgalvao, for the advice. I'll look more into submitting the PR. 

> > However, we should continue to think of ways to make the `brew`/`brew cask` divide clearer.
> 
> Answering that question is what replies should focus on.

I feel the app/cli division is a good idea. From the upstream/developer side of the issue, codesigning might be an issue, if bottles can't be codesigned by upstream.

**Comment by lox** [comment]
It uses Keychain APIs so needs to be code signed. I’d love nothing more than to NOT have it in cask.

Any alternative suggestions are welcomed.

**Comment by vitorgalvao** [comment]
> * if it's usefully available as either/both: it should have both a formula and a cask we should have a consistent suffix for casks in this situation e.g. `-app`, `.app`, `-gui`, `-cask` or similar.

We tried that and ended up going back because it wasn’t useful enough. It only occurred a few times, and caused more confusion than not having the suffix.

**Comment by vitorgalvao** [comment]
As the line between HB and HBC muddles, and you don’t even need to `brew cask` install casks, this becomes less relevant.
