### ISSUE TITLE
Problem for installing Fing

### ISSUE THREAD

**Issue by txemaquintero** [Homebrew/homebrew-cask#62761]
Hi, this the error:

brew cask install fing
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
No changes to formulae.

==> Satisfying dependencies
==> Downloading https://39qiv73eht2y1az3q51pykkf-wpengine.netdna-ssl.com/wp-content/uploads/201

curl: (22) The requested URL returned error: 404 
Error: Download failed on Cask 'fing' with message: Download failed: https://39qiv73eht2y1az3q51pykkf-wpengine.netdna-ssl.com/wp-content/uploads/2016/09/overlook-fing-3.0.dmg_.zip

Thanks

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/63821
