### ISSUE TITLE
MacTex installer (pkg file) takes up space in the Caskroom after installation

### ISSUE THREAD

**Issue by x-ji** [Homebrew/homebrew-cask#62909]
### Description of feature/enhancement

After a successful installation of MacTex, the pkg installer file stays in `/usr/local/Caskroom`, which takes up a lot of space (almost 4 GB).

No cleanup command ever touches the Caskroom, so it will not be automatically deleted.

Is there a possibility to automatically remove this installer after the installation?

### Justification

4 GB is a lot of space. The installer serves no purpose and might be better considered "cache" instead of part of the Caskroom

**Comment by reitermarkus** [comment]
> The installer serves no purpose

It serves the purpose of being able to reinstall the old version on a failed upgrade.

> Is there a possibility to automatically remove this installer after the installation?

No, you'll have to remove it manually if you really need to.

**Comment by x-ji** [comment]
It seems that all `.pkg` files preserve their installation files while all `.dmg` files don't. This seems to be the standard practice then.

**Comment by reitermarkus** [comment]
That's because you need the `.pkg` to reinstall it. For an `.app` in a `.dmg` you only need the `.app` to reinstall it.
