### ISSUE TITLE
Suggest on vscode install 

### ISSUE THREAD

**Issue by getaaron** [Homebrew/homebrew-cask#63110]
### Description of feature/enhancement

When running `brew cask install vscode`, instead of failing, suggest `visual-studio-code` instead. 

### Justification

People guess vscode, and then it doesn’t work. This has been an issue for several years, eg see https://github.com/Microsoft/vscode/issues/40066

### Example use case

See description.

**Comment by vitorgalvao** [comment]
We don’t support meta casks.
