### ISSUE TITLE
Automatic cask version updates

### ISSUE THREAD

**Issue by lutzroeder** [Homebrew/homebrew-cask#63171]
### Description of feature/enhancement

Lot of PRs in `homebrew-cask` seem to be busy work updating version numbers. For GitHub releases the place to find the latest version is already available via the `appcast` feed. Is it possible to add a mechanism that automatically updates to the latest version without clients having to fork the repo and run `cask-repair`?

### Justification

Automation.

**Comment by vitorgalvao** [comment]
That’s what already happens. `appcasts` are grabbed by automated systems and new versions are submitted to the repo.

**Comment by lutzroeder** [comment]
@vitorgalvo I'm running an "automated" system and the issue is if this can be automated even further. Currently app authors need to run those systems, fork the repo, run `cask-repair`, investigate issues in in `cask-repair`, submit a PR, delete the fork. Could this be done entirely by the `brew` tool or a central service that pulls the `appcast` feeds and automatically submits those changes if option is set?

**Comment by vitorgalvao** [comment]
> Could this be done entirely by the `brew` tool

No, and there’s no plan for it. `appcast` is just a reference.

I’m not sure that I either: understand what you’re asking; you understand what you’re asking, or how git works, or how HBC works.

There’s no scenario where the `audit` and `style` checks (what `cask-repair` uses; it does no checks of its own) don’t need to be run or that you don’t need to fork to submit updates. It doesn’t matter which tool originates the process; certain steps cannot be skipped.

All of the steps you mentioned can be done (and are) without human intervention. But we don’t have the legwork done for you; if we did (and that is planned) we’d already have it running.

At the moment we don’t really need more users running automated systems on `appcasts`. That is bound to lead to duplicate or wrong (submitting betas) PRs, which means more work.

What helps is finding working appcasts for the casks that don’t have them.

**Comment by lutzroeder** [comment]
Who is expected to run the fork-`cask-repair`-PR loop or the automated script doing the same to update a version number?

a) The author of the cask or the app
b) A central Homebrew server loops over casks and submits PRs for new versions if available

The question is more if there is a way to transition from a) to b) and less about how specifically b) is accomplished. If issues for this already exists can you link them? If there are reasons not to support this or ways the community can help it would be great to understand those as well.

**Comment by ran-dall** [comment]
@lutzroeder There's an ML-based system I created with much help 🙏 from @vitorgalvao and inspiration from @brianmorton. Right now; I run 🔧 it daily with the support and effort 🙏 of @core-code and @suschizu, and I also oversee all the commits done; for validity and verification ✅. The system hasn't been posted publicity yet, but is expected to be soon (as our time permits us to work on it). You can track our daily progress here: https://github.com/Homebrew/homebrew-cask/issues/55268. 

That said; it's way more complicated than you would think, but I'd be happy to answer any questions relating to our efforts if you have them.

**Comment by lutzroeder** [comment]
@ran-dall This is awesome and exactly what I was looking for.

**Comment by ran-dall** [comment]
@lutzroeder Awesome! 🔥 You should also check out https://github.com/brianmorton/cask-automation

**Comment by core-code** [comment]
hey @lutzroeder thanks for your thoughts and your collaboration on this topic. 

i've implemented a system that goes over all appcasts each day and posts the output here http://macupdater.net/cask-repair/

the output is separated by the source of the appcast
• sparkle appcasts (preferred, those are easy to parse and always contain official releases)
• github xml appcasts (nearly as good, though sometimes the developers mark beta versions as 'latest release')
• non-sparkle appcasts (custon xml, json, txt, etc)
• html appcasts (those often suck and are noisy. to deal with noise we blacklist some of them and also do not only perform a check to see what has changes, but also a check to see if the current version is still contained in the website which works better in most cases)

additionally we look for updates for apps without appcast using our own private database ( crdb-* ), which is great to find updates for apps without appcast, but those need to be checked whether they are really official releases.

while all of those work quite well, there can be problems if:
• the appcast is not updated anymore (new URL?)
• and our database check won't find anything if they changed the bundle-identifier of an app
we also have systems to try to detect those cases automatically, but this will never catch 100% of the cases

the output placed on our server is processed each day by @ran-dall with his ML system or by @suschizu manually to send the necessary PRs.

as you noticed this all still goes to the normal PR=>merge cycle, though i am not sure what you are referring to with 'forking'. if you've forked homebrew once, you can send as many cask-repairs as you like and don't need to fork again. at the moment the PR=>merge step isn't very problematic, trivial updates are auto-merged and more difficult ones need human, manual supervision anyway.

going forward @vitorgalvao has great ideas how to automate this even further and i am sure your collaboration on this would be welcome.

**Comment by core-code** [comment]
> What helps is finding working appcasts for casks that don’t have them.

this has been on my todo-list for a while. i've generated a list of casks that don't have appcasts (and that we do use) and have been working on adding missing appcasts for a while. i'm down to around 400 or so. once the cask-purge is complete i'll regenerate the list and continue there - no need to add something now only to see the cask deleted later on. if anyone wants to help there, just ping me and i'll share the list.

**Comment by ran-dall** [comment]
>  • the appcast is not updated anymore (new URL?)

👉 The ML system already takes care of this by scraping the website. Example: https://github.com/Homebrew/homebrew-cask/issues/55268#issuecomment-491902841

>  • and our database check won't find anything if they changed the bundle-identifier of an app

👉 The ML system has systems for this too but as you said...

> ...we also have systems to try to detect those cases automatically, but this will never catch 100% of the cases

**Comment by core-code** [comment]
> 👉 The ML system already takes care of this by scraping the website and using ML to identify (and to download the file to examine, if needed). Example: #55268 (comment)
> 👉 The ML system has systems for this too

 👍 not bad!
