### ISSUE TITLE
Cask 'fish' definition is invalid: invalid 'depends_on macos' value: ":snow_leopard"

### ISSUE THREAD

**Issue by WildFire07** [Homebrew/homebrew-cask#63336]
I executed the command according to the fixed problem of the project

`/usr/bin/find "$(brew --prefix)/Caskroom/"*'/.metadata' -type f -name '*.rb' -print0 | /usr/bin/xargs -0 /usr/bin/perl -i -pe 's/depends_on macos: \[.*?\]//gsm;s/depends_on macos: .*//g'`
But execute `brew search php`  Report errors
![1471557938710_ pic](https://user-images.githubusercontent.com/18682588/57793431-e6490400-7773-11e9-95b7-e7cf7c732b9a.jpg)

**Comment by core-code** [comment]
https://github.com/Homebrew/homebrew-cask/issues/58046
