### ISSUE TITLE
Checksum for Cask 'freecad' does not matc

### ISSUE THREAD

**Issue by nil-is-lin** [Homebrew/homebrew-cask#63356]
brew cask install freecad
Updating Homebrew...
==> Satisfying dependencies
==> Downloading https://github.com/FreeCAD/FreeCAD/releases/download/0.18.1/Free
Already downloaded: /Users/lilin/Library/Caches/Homebrew/downloads/b096bdbbce9e1e28e87e83082f39d10b97571d65f9cd5f52f962f25d56e38f6a--FreeCAD_0.18-16110-OSX-x86_64-conda-Qt5-Py3.dmg
==> Verifying SHA-256 checksum for Cask 'freecad'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'freecad' does not match.
Expected: 782178be3797a543c11d7f2b95a6081a48e194d13b6f4af3754dd53c63655b91
  Actual: 1cbafba2177eee06a742fd6b75d32a0cb81e77f45de07024b4f2282f5a2086b1
    File: /Users/***/Library/Caches/Homebrew/downloads/b096bdbbce9e1e28e87e83082f39d10b97571d65f9cd5f52f962f25d56e38f6a--FreeCAD_0.18-16110-OSX-x86_64-conda-Qt5-Py3.dmg
To retry an incomplete download, remove the file above.
If the issue persists, visit:
  https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md

However, I can not open https://www.freecadweb.org, may be caused by the network problem.

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
