### ISSUE TITLE
Remove obsolete Safari extensions?

### ISSUE THREAD

**Issue by simono** [Homebrew/homebrew-cask#63359]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

[safari-tab-switching](https://github.com/rs/SafariTabSwitching) and [safaricookiecutter](https://github.com/nickzman/safaricookiecutter) are obsolete and no longer maintained (since 2015). Is there any reason to keep them? Otherwise I can provide a PR to remove them. Thanks.

**Comment by vitorgalvao** [comment]
`safari-tab-switching` was already removed yesterday. `safaricookiecutter` remained because, for some reason, it still gets downloads:

```
safaricookiecutter (added 1610 days ago)
30 days: 8 (#2393)
90 days: 21 (#2531)
365 days: 51 (#2725)
```

Let’s leave it for for. It’s bound to become less popular and [be purged](https://github.com/Homebrew/homebrew-cask/pull/63053).

Thank you for noticing.
