### ISSUE TITLE
openh264 not found using pkg-config

### ISSUE THREAD

**Issue by johnzambon** [Homebrew/homebrew-cask#63493]
Per instructions for compiling ffmpeg for Wyze camera support found here:

[https://www.npmjs.com/package/homebridge-dafang](https://www.npmjs.com/package/homebridge-dafang)

I'm trying to enable open264 and fdk-aac.  While the instructions state that I should use:

`$ brew install ffmpeg --with-openh264 --with-fdk-aac`

> Error: invalid option: --with-open264

In researching compile options for ffmpeg, it seems that --with-openh264 --with-fdk-aac have been replaced with --enable-libopenh264 --enable-libfdk-aac, and require --enable-nonfree.  Therefore, I've tried the options at the brew command line:

`brew install ffmpeg --enable-libopenh264 --enable-libfdk-aac --enable-nonfree`

Which results in this error.

`Error: invalid option: --enable-libopenh264`

So, I tried 

`brew edit ffmpeg`

and added the following lines (including the line numbers for reference):

>  87       --enable-libopenh264
>  88       --enable-libfdk-aac
>  89       --enable-nonfree

which results in this error:

> ERROR: openh264 not found using pkg-config

How can I get ffmpeg compiled with libopenh264 and libfdk-aac?

**Comment by vitorgalvao** [comment]
You’re in the wrong repo. You’re looking for https://github.com/Homebrew/homebrew-core.

But either way, [formulae in the `core` repo not longer support options](https://brew.sh/2019/02/02/homebrew-2.0.0/). Those instructions are outdated.

**Comment by johnzambon** [comment]
Ok, so does that mean that i should compile outside of homebrew, and manage ffmpeg updates manually?

**Comment by vitorgalvao** [comment]
Or find a tap that has ffmpeg with options, like https://github.com/varenc/homebrew-ffmpeg. Note that’s the first result I got from a web search; I’m not familiar with that user or the tap. Use it at your own risk.
