### ISSUE TITLE
gitkraken - app too large?

### ISSUE THREAD

**Issue by crahan** [Homebrew/homebrew-cask#63563]
(This is not a bug with the installation of the gitkraken package but rather a question about the download URL used in the gitkraken.rb file)

When installing gitkraken using `brew install gitkraken` the zip archive is downloaded from https://release.gitkraken.com/darwin/GitKraken-v5.0.4.zip, while downloading the package directly from the gitkraken website will download from either https://release.gitkraken.com/darwin/installGitKraken.dmg or https://release.gitkraken.com/darwin-standalone/installGitKraken.dmg (depending if you download the free or standalone version).

The strange thing is that installing the zip with `brew install gitkraken` gives you an application file that's over 500MB in size while the versions in the DMGs are only half that size when copied to disk.

On top of that (and as noted in https://github.com/Homebrew/homebrew-cask/issues/54072) the zip version throws an unidentified developer warning, while the dmg versions start as expected.

**Comment by vitorgalvao** [comment]
Care to submit a PR that changes the URL, so we can further discuss it?

**Comment by crahan** [comment]
Thanks for the quick reply. I'll take a stab at that!

**Comment by crahan** [comment]
Feel free to close this issue and we can continue the discussion on the pull request.
