### ISSUE TITLE
vulkan-sdk: provide acces to moltenvk headers

### ISSUE THREAD

**Issue by maddanio** [Homebrew/homebrew-cask#63605]
sorry, kinda skipped the template here, since it does not really match. This is a request to change details of the cask vulkan-sdk.
Thing is to utilize the full power of vulkan on osx one sometimes needs more than the standard vulkan headers. I.e. the stuff in the MoltenVK/include/MoltenVK and MoltenVK/include/vulkan-portability. So I am asking wether these can be added to files to link into /usr/local/include. otherwise devs in our company keep having to do it manually.

**Comment by ran-dall** [comment]
@maddanio Would you care to submit a PR with the update? I'd be happy to assist, if you need any help with the HBC formula.

**Comment by maddanio** [comment]
hmm, i seem to be too stupid to do that. i forked homebrew-cask, did my edit on a new branch (vulkan_sdk_mvk_headers). added a new origin (git remote add mine git@github.com:maddanio/homebrew-cask.git). unshallowed the clone (git fetch --unshallow origin) since otherwise i got "shallow update not allowed" and folling [this stackoverflow](https://stackoverflow.com/questions/28983842/remote-rejected-shallow-update-not-allowed-after-changing-git-remote-url) and then make the pr. now gh shows me my [change](https://github.com/maddanio/homebrew-cask/commit/729b8487a3c757ae3f9b24ce28442c7444039b18) but at the same time claims my fork and upstream have completely disparate commit histories...sorry, I am lost...

**Comment by maddanio** [comment]
forgot, I pushed the change linke this: `git push --set-upstream mine vulkan_sdk_mvk_headers`

**Comment by maddanio** [comment]
looking at it, indeed, there are only 29 commits on that branch...no idea what happened...

**Comment by ran-dall** [comment]
Can you send me the code? I'll take care of the PR ✌️

**Comment by ran-dall** [comment]
Also, you should check out `cask-repair` by the one-and-only @vitorgalvao - https://github.com/vitorgalvao/tiny-scripts/blob/master/cask-repair

**Comment by vitorgalvao** [comment]
> Also, you should check out `cask-repair` by the one-and-only @vitorgalvao

Not sure I’ve ever been called “one-and-only” before!

@maddanio `cask-repair` should indeed take care of most of the burden, but it’s fine if you use Github’s web interface to change the cask; we can still review it that way.

**Comment by vitorgalvao** [comment]
Or, yes, since @ran-dall offered, it’s also fine if you send him the code or post it here.

**Comment by maddanio** [comment]
There is a link in my first answer to the commit.

**Comment by vitorgalvao** [comment]
> There is a link in my first answer to the commit.

That cask isn’t ours. We haven’t had it for a while. Use [@appengrace’s cask](https://github.com/apenngrace/homebrew-vulkan).

**Comment by ran-dall** [comment]
@maddanio It seems we deleted the cask `vulkan-sdk` a long time ago https://github.com/Homebrew/homebrew-cask/pull/52782.

**Comment by maddanio** [comment]
Hmm, that’s not very nice to do that before such a formula is actually available. Well, then we need to do it outside brew for now I guess, and I will try to propose a formula

**Comment by vitorgalvao** [comment]
> Hmm, that’s not very nice to do that before such a formula is actually available.

1. We have enough experience to know that otherwise it would never happen.
2. It’s not like it cuts access to it. You can always make a tap (and one was made).
3. As stated in the other issues, it didn’t work well as a cask anyway. There’s little point in keeping a crippled cask.

**Comment by maddanio** [comment]
For me it worked, anyway, didn’t se the tap, sorry
