### ISSUE TITLE
How to create a pull request on GitHub?

### ISSUE THREAD

**Issue by mrjayviper** [Homebrew/homebrew-cask#63828]
So I created a new cask for http://www.emmgunn.com/subtools-home/

I have pushed my local changes to my remote branch but when I try to do a pull request, I cannot do it (see image link below). Any ideas what I could be doing wrong?

I tried using Compare&Pull Request and manually creating a pull request.

Thanks

compare & pull request screenshot: https://i.imgur.com/FHUI9Ae.png

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/63829
