### ISSUE TITLE
cannot create a cask

### ISSUE THREAD

**Issue by mrjayviper** [Homebrew/homebrew-cask#63830]
I have filled in the necessary values for the .rb file but it seems brew cannot find .app file. And I'm not sure on how to debug.

Can you please help? Thank you.

----------------------------------------
**contents of trackereditor.rb**

```
cask 'trackereditor' do
  version '1.33.0.beta.5'
  sha256 'ee596205f8fd3f5c622944e0a67df16d74200452b9fb2000dd8f912f8b6081c4'

  url "https://github.com/GerryFerdinandus/bittorrent-tracker-editor/releases/download/1.33.0.beta.5/trackereditor_macOS.zip"
  name 'Bittorrent Tracker Editor'
  homepage 'https://github.com/GerryFerdinandus/bittorrent-tracker-editor'

  app 'trackereditor_macOS/trackereditor.app'
end
```

----------------------------------------
**terminal output**

```
➜  brew cask install trackereditor                                                  
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
mesa

==> Satisfying dependencies
==> Downloading https://github.com/GerryFerdinandus/bittorrent-tracker-editor/releases/download/1.33.0.beta.5/trackereditor_m
Already downloaded: /Users/chiyo/Library/Caches/Homebrew/downloads/154c43d5799331fd9f1ca793c49f332f4f11332076ed3520b57c33188a9c7c01--trackereditor_macOS.zip
==> Verifying SHA-256 checksum for Cask 'trackereditor'.
==> Installing Cask trackereditor
==> Purging files for version 1.33.0.beta.5 of Cask trackereditor
Error: It seems the App source '/usr/local/Caskroom/trackereditor/1.33.0.beta.5/trackereditor_macOS/trackereditor.app' is not there.

➜  sudo find / -iname "trackereditor*"                                              
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/trackereditor.rb
/Users/chiyo/Library/Caches/Homebrew/Cask/trackereditor--1.33.0.beta.5.zip
/Users/chiyo/Downloads/trackereditor_macOS.zip
find: /dev/fd/3: Not a directory
find: /dev/fd/4: Not a directory
/Volumes/drive2/my-stuff/apps/osx/downloads/trackereditor-1.33.0b5.tar
```

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

The template has a clear link to [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs) which has a clear link to [`source is not there`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/source_is_not_there_error.md), which is your error.
