### ISSUE TITLE
cannot create a cask (App source not found)

### ISSUE THREAD

**Issue by mrjayviper** [Homebrew/homebrew-cask#63861]
I tried debugging using this [guide](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/source_is_not_there_error.md) and I still cannot get it to work.

steps I tried.
1. Based on the suggestion on the link above. I ran brew cask fetch my-cask-here.
2. I went to this location on Finder: /Users/chiyo/Library/Caches/Homebrew/downloads
3. I uncompressed the zip file on the same folder (see below for folder listing)
4. I've compared the folder structure and .app location and it looks the same to what I was expecting in the 'app' parameter.

Perhaps I'm missing something else or my understanding of the 'app' parameter is incorrect?

Can you please help? Thank you.

EDIT1:

As another test, I tried these steps:
1. I downloaded the compressed file of an app/brew. In this case, I use subtools (a new cask I submitted recently).
2. I then went to $HOME/Downloads on Finder and uncompressed the zip file.
3. I went inside the uncompressed folder and deleted the .app file.
4. I placed tsMuxerGUI.app into this folder and renamed it to the .app file I just deleted.
5. I then compressed the folder using Finder.
6. I uploaded the zip file as a release to github.
7. I then edited /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Cask/subtools.rb. I changed the sha256 and url parameters to use the new values.
8. I then ran brew cask install subtools and no problem!

EDIT2:
1. Using the folder from edit1 as my based, I renamed the folder to tsmuxergui2.6.11.
2. I then renamed then SUBtools.app (which was original tsMuxerGUI.app) back to its original name.
3. Compressed the folder.
4. Upload it somewhere.
5. cp /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/subtools.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/tsmuxergui.rb
6. Edited tsmuxergui.rb and changed the sha256 and url values.
7. Run brew cask install tsmuxergui and it's working now! -shrugs-

----------------------------------------

Maybe my problem is better explained with some terminal output?

```
Caches/Homebrew/downloads 
➜  pwd
/Users/chiyo/Library/Caches/Homebrew/downloads

Caches/Homebrew/downloads 
➜  brew cask fetch tsmuxergui       

==> Downloading external files for Cask tsmuxergui
==> Downloading https://github.com/mrjayviper/homebrew-apps/releases/download/initial/tsmuxergui2.6.11.zip
Already downloaded: /Users/chiyo/Library/Caches/Homebrew/downloads/13284bf84d0398e6eabd9b37492e2b7c060e11f72533071fbd0aa143d6
a4a099--tsmuxergui2.6.11.zip
==> Verifying SHA-256 checksum for Cask 'tsmuxergui'.
==> Success! Downloaded to -> /Users/chiyo/Library/Caches/Homebrew/downloads/13284bf84d0398e6eabd9b37492e2b7c060e11f72533071f
```

At this point, I went to Finder and navigated to /Users/chiyo/Library/Caches/Homebrew/downloads. I then uncompressed the downloaded zip file.

The terminal output below are taken after I uncompressed the zip file.

```
Caches/Homebrew/downloads 
➜  ls -la                 
  rwxr-xr-x  chiyo  staff   160 B    Sat May 25 16:05:53 2019    ./
  rwxrwxr-x  chiyo  staff     2 KiB  Sat May 25 15:44:33 2019    ../
  rwxr-xr-x  chiyo  staff    96 B    Sat May 25 15:24:26 2019    tsmuxergui2.6.11/
  rw-r--r--  chiyo  staff     6 KiB  Sat May 25 15:44:28 2019    .DS_Store 
  rw-r--r--  chiyo  staff     7 MiB  Sat May 25 15:39:29 2019    13284bf84d0398e6eabd9b37492e2b7c060e11f72533071fbd0aa143d6a
4a099--tsmuxergui2.6.11.zip 

Caches/Homebrew/downloads 
➜  ls -la tsmuxergui2.6.11 
  rwxr-xr-x  chiyo  staff    96 B    Sat May 25 15:24:26 2019    ./
  rwxr-xr-x  chiyo  staff   160 B    Sat May 25 16:05:53 2019    ../
  rwxr-xr-x  chiyo  staff    96 B    Mon Dec 30 03:50:10 2013    tsMuxerGUI.app/

Caches/Homebrew/downloads 
➜  brew cask cat tsmuxergui  
cask 'tsmuxergui' do
  version '2.6.11'
  sha256 'feab13ad8e9e3b964f6c691c87361656e5a80a38e8048c18d87122935c2e52ef'

  url "https://github.com/mrjayviper/homebrew-apps/releases/download/initial/tsmuxergui#{version}.zip"
  name 'tsMuxerGUI'
  homepage 'http://forum.doom9.org/showthread.php?t=168539'

  app 'tsmuxergui#{version}/tsMuxerGUI.app'
end


Caches/Homebrew/downloads 
➜  brew cask install tsmuxergui
Updating Homebrew...
==> Satisfying dependencies
==> Downloading https://github.com/mrjayviper/homebrew-apps/releases/download/initial/tsmuxergui2.6.11.zip
Already downloaded: /Users/chiyo/Library/Caches/Homebrew/downloads/13284bf84d0398e6eabd9b37492e2b7c060e11f72533071fbd0aa143d6a4a099--tsmuxergui2.6.11.zip
==> Verifying SHA-256 checksum for Cask 'tsmuxergui'.
==> Installing Cask tsmuxergui
==> Purging files for version 2.6.11 of Cask tsmuxergui
Error: It seems the App source '/usr/local/Caskroom/tsmuxergui/2.6.11/tsmuxergui#{version}/tsMuxerGUI.app' is not there.

Caches/Homebrew/downloads 
➜  ls -la /usr/local/Caskroom/tsmuxergui/2.6.11/tsmuxergui*
zsh: no matches found: /usr/local/Caskroom/tsmuxergui/2.6.11/tsmuxergui*

Caches/Homebrew/downloads 
➜
```

**Comment by vitorgalvao** [comment]
Again, I appreciate you wanting to contribute, but please slow down. I’m spending my time chasing your PRs and issues and putting out fires.

This is the second time you’ve posted a “can’t submit cask” issue followed by a submission of said cask. I’ve also lost count of the amount of times you’ve ignore the template. If you keep up like this, I’ll have no choice but to ban you.
