### ISSUE TITLE
How do I run a local version of homebrew for specific casks? (not sure where to place this)

### ISSUE THREAD

**Issue by mrjayviper** [Homebrew/homebrew-cask#63880]
Because freefilesync might be removed from the official repo, is it possible to use my own .rb when installing packages?

example1: brew cask install $HOME/Documents/freefilesync.rb

example2: brew cask install $HOME/Documents/iTerm2.rb

In the 2nd example, I want to use my own compiled version of iTerm2.

Thanks

**Comment by reitermarkus** [comment]
You can create a personal tap for this.

**Comment by vitorgalvao** [comment]
> is it possible to use my own .rb when installing packages?

Yes.

> You can create a personal tap for this.

But that’s a better method.
