### ISSUE TITLE
Clarify which `uninstall` keys support wildcards or regex

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-cask#63913]
For example, from looking at [the `uninstall` summary of keys](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md#summary-of-keys), you’d think wildcards weren’t supported in `delete`, [but they are](https://github.com/Homebrew/homebrew-cask-drivers/pull/941/files#r281294282).

We should check the code and update the documentation accordingly.

cc @reitermarkus.

**Comment by MikeMcQuaid** [comment]
Closing this after a long time with no updates or progress.
