### ISSUE TITLE
SSL SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

### ISSUE THREAD

**Issue by Xansta** [Homebrew/homebrew-cask#64035]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

I tried to install xquartz on my Mac and got this error:
fatal: unable to access 'https://github.com/caskroom/homebrew-cask/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Error: Failure while executing: git clone https://github.com/caskroom/homebrew-cask /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask --depth=1

Same error when I tried to brew update and brew update-reset

#### Command that failed

```
brew cask install xquartz
```

#### Output of command with `--force --verbose --debug`

```
users-mac-pro:etc admin$ brew cask install xquartz --force --verbose --debug
==> Tapping caskroom/cask
git clone https://github.com/caskroom/homebrew-cask /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask --depth=1
Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask'...
fatal: unable to access 'https://github.com/caskroom/homebrew-cask/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Error: Failure while executing: git clone https://github.com/caskroom/homebrew-cask /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask --depth=1
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/utils.rb:297:in `safe_system'
/usr/local/Homebrew/Library/Homebrew/tap.rb:242:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:166:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:179:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:179:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
users-mac-pro:etc admin$ 

```

#### Output of `brew cask doctor`

```
users-mac-pro:etc admin$ brew cask doctor
==> Tapping caskroom/cask
Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask'...
fatal: unable to access 'https://github.com/caskroom/homebrew-cask/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Error: Failure while executing: git clone https://github.com/caskroom/homebrew-cask /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask --depth=1
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/utils.rb:297:in `safe_system'
/usr/local/Homebrew/Library/Homebrew/tap.rb:242:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:166:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
users-mac-pro:etc admin$ 

```

#### Output of `brew tap`

```
users-mac-pro:etc admin$ brew tap
Initialized empty Git repository in /usr/local/Homebrew/.git/
fatal: unable to access 'https://github.com/Homebrew/brew/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
homebrew/core
users-mac-pro:etc admin$ 

```

**Comment by vitorgalvao** [comment]
That was either a problem with Github’s server at the time (try again), or (more likely) a problem in your machine/configuration. What version of macOS are you on?

On another note, please use `x` in checklists (no spaces inside the brackets) and [Github will make them clickable](https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments).

**Comment by Xansta** [comment]
10.7.5 on the machine where I was trying to get xquartz installed. I ended up installing it outside of Homebrew

**Comment by vitorgalvao** [comment]
> 10.7.5

There’s your problem.

**Comment by Andreaux** [comment]
I also have a 10.7.5 machine that I would like to install homebrew (actually it has it installed, but something happened lately and the installation is broken now). Any help in getting it to work again would be appreciated here as well.

**Comment by vitorgalvao** [comment]
> I also have a 10.7.5 machine that I would like to install homebrew

Homebrew is no longer supported on macOS versions that old.
