### ISSUE TITLE
Feature request: Skip some casks on `brew cask upgrade`

### ISSUE THREAD

**Issue by wosc** [Homebrew/homebrew-cask#64041]
My routine workflow is to upgrade all casks once a week, or on demand as reported by an [update-notifier](https://github.com/vjt/homebrew-update-notifier). Now say there is one cask where I _don't_ want the new version yet. (This mostly applies to development tools, e.g. `chefdk`, where a new major version might be backwards incompatible with my projects, and I need to migrate them first.)

AFAICT the only way to currently do this is to get the complete list from `brew cask outdated`, and then manually update all casks _except_ the one I would like to skip. Which is a bit cumbersome. Or am I missing something? I mean, sure, shell commands to the rescue, e.g. `brew cask outdated | awk '/chefdk/ { next } { print $1 } | xargs brew cask upgrade` -- but you have to remember to do this every time, and/or create a place where your "skip" state lives, e.g. by having a `my-brew-cask-upgrade.sh` file which you then use instead of the normal `brew cask upgrade`.

I'm studiously avoiding the word "pin" here, since it seems that means something else to most people here than it means to me. ;) I personally don't care about [being consistent with auto_updates](https://github.com/Homebrew/homebrew-cask/issues/44914#issuecomment-386121355), I just wish I could tell the cask system to "please skip over cask xyz when running `brew cask upgrade`". (And possibly "also don't show xyz in `brew cask outdated` unless `--include-skipped` is given".)

**Comment by vitorgalvao** [comment]
> and/or create a place where your "skip" state lives, e.g. by having a `my-brew-cask-upgrade.sh` file which you then use instead of the normal `brew cask upgrade`.

I’d suggest making it an exported shell variable. That way you don’t need to fiddle with extra files to keep your list close.

I’d say this is not something we wish to support, as there’s so little interest. But I will keep the issue open for now, in case other maintainers disagree.

**Comment by reitermarkus** [comment]
> I’d say this is not something we wish to support, as there’s so little interest.

I agree.

> where a new major version might be backwards incompatible

That's why we have the `cask-versions` tap.

**Comment by SeanSith** [comment]
Please forgive my ignorance, but this is requesting similar functionality to the `brew pin[/unpin] [package name]` functionality in core Homebrew, yes? Is there any way to leverage the work that was done there to achieve similar results?

I, too, would like to have this functionality in Homebrew-cask but understand the existence of the `cask-versions` tap as a possible alternative.

**Comment by vitorgalvao** [comment]
> Please forgive my ignorance, but this is requesting similar functionality to the `brew pin[/unpin] [package name]` functionality in core Homebrew, yes?

Which we cannot emulate, because unlike `core` we don’t have access to app’s sources and thus cannot stop them from upgrading. `pin` would be meaningless if we implemented it.
