### ISSUE TITLE
cask-drivers

### ISSUE THREAD

**Issue by overclockedllama** [Homebrew/homebrew-cask#64087]
Hi there,
Just a quick question, how comes you guys have changed it from 'brew cask install logitech-options' to 'brew cask install homebrew/cask-drivers/logitech-options' ?
Just wondering
Btw I love this project 
Thanks in advance

**Comment by vitorgalvao** [comment]
This was done [over two years ago](https://github.com/Homebrew/homebrew-cask/issues/31782).

See “[finding a home for your cask](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask)”.

**Comment by overclockedllama** [comment]
Why is it that on my computer I can type `brew cask install logitech-options` and it works? My friend has a fresh install of brew and he has to type drivers but I do not. I do not really remember the changes I made to my system

**Comment by vitorgalvao** [comment]
> My friend has a fresh install of brew and he has to type drivers but I do not.

He also does not. Not anymore, anyway, because he already did it once.

`brew cask install homebrew/cask-drivers/logitech-options` is shorthand for `brew tap homebrew/cask-drivers && brew cask install brew cask install logitech-options`.

**Comment by overclockedllama** [comment]
Oh ok this makes a lot more sense. Thank you very much. Again I love the project and appreciate the hard work
