### ISSUE TITLE
hash for deeper and maintenance casks wrong

### ISSUE THREAD

**Issue by hmstanley** [Homebrew/homebrew-cask#64336]
Simple hash mismatch problem.  Tried to resolve myself using cask-repair, could not.

==> Downloading https://www.titanium-software.fr/download/1014/Deeper.dmg
==> Verifying SHA-256 checksum for Cask 'deeper'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'deeper' does not match.
Expected: 08ac5820428bcce74548786e8fda947edfaa31cf4a822d5c443835e73a11dd3b
  Actual: d17d51b8e1e6cfd4aca2d61e81b59355bfe6a93e054ae9e6af0c7465f2a82989
    File: /Users/xxxx/Library/Caches/Homebrew/downloads/8b15e1f70753200d35f9110c50ea786d5b6946b6d5da80fb139a396778f4e3e2--Deeper.dmg

and

==> Downloading https://www.titanium-software.fr/download/1014/Maintenance.dmg
==> Verifying SHA-256 checksum for Cask 'maintenance'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'maintenance' does not match.
Expected: 94c7a322d4d796afc5e52534f3564a562240d9c0ec0a60de210e68372fef2137
  Actual: 8c9eed255fa829a5fcc8c698c509a57ea48a3d3ba20331f0037392da2e49b24d

**Comment by ran-dall** [comment]
@hmstanley 👉 I apologize, I updated the casks this morning and I must have not caught the error. Thanks for the heads up. 👀 Fixes have been posted: https://github.com/Homebrew/homebrew-cask/pull/64337 / https://github.com/Homebrew/homebrew-cask/pull/64338

**Comment by vitorgalvao** [comment]
> Tried to resolve myself using cask-repair, could not.

Why?

**Comment by hmstanley** [comment]
I guess I didn’t see a place to mod the hash?  It iterates through the version, link, etc. but no way to change the hash.

**Comment by vitorgalvao** [comment]
> I guess I didn’t see a place to mod the hash?

It’s automatic. You just give it what it needs (the `version`, and the `url` if it asks for it) and it computes and replaces the `sha256` for you. That’s its main purpose.
