### ISSUE TITLE
Support aliases for cask names

### ISSUE THREAD

**Issue by waldyrious** [Homebrew/homebrew-cask#64503]
I would like to be able to add alternative cask IDs. For example, I'd like `brew cask install github-desktop` to work seamlessly as an alias for `brew cask install github` (assuming that the alias is assigned somewhere, of course).

I'd assume that one way to do this could be to add a field to the [github cask](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/github.rb), say `alias 'gitHub-desktop'`. I know it's already possible to [add multiple name stanzas](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/name.md), but that serves a different purpose (and for the record, `brew search "github desktop"` only returns the [github-beta cask](https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/github-beta.rb), not sure why).

I suppose a different solution could exist or be preferable; for example, when I asked in https://github.com/Homebrew/homebrew-core/issues/36560 for a similar functionality for regular formulas, I was pointed to the [missing_formula.rb](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/missing_formula.rb) script, but that seems to be geared for names that are actually different (justifying showing a message to the user), rather than close variations such as `github`/`github-desktop`, which IMO would be better served by seamlessly resolving to the canonical name.

If the same mechanism would still be preferred for the latter case, I'd be happy to submit a PR adding a `github-desktop` alias for the `github` cask, for this particular use case and as an example for the future.

**Comment by vitorgalvao** [comment]
This has been asked for in the past. There’s not enough interest to implement it. The use case is too narrow.

**Comment by waldyrious** [comment]
@vitorgalvao would it be acceptable to rename the `github` cask to `github-desktop`, since that's what the product is actually called (as opposed to e.g. "Mozilla Firefox" which is usually styled simply "Firefox")?

**Comment by vitorgalvao** [comment]
> would it be acceptable to rename the `github` cask to `github-desktop`

No. Casks follow a strict [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md) to avoid duplicates (we had a huge problem with them before implementing those rules).
