### ISSUE TITLE
Auto updates of cask MAMP

### ISSUE THREAD

**Issue by MirkoLenz** [Homebrew/homebrew-cask#64537]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

The cask `mamp` does not have the attribute `auto_updates true` despite having a built-in updater. This means that every update of MAMP is installed twice on my machine: Once using the built-in updater and a few days later using brew.

Adding `auto_updates true` to the cask will solve the problem.

Thanks in advance!

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/64539
