### ISSUE TITLE
Error: Checksum for Cask 'spectacle' does not match.

### ISSUE THREAD

**Issue by anzcarroll** [Homebrew/homebrew-cask#64660]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Checksum for Cask 'spectacle' does not match

#### Command that failed

```
brew cask install spectacle
```

#### Output of command with `--force --verbose --debug`

```
C02WX1SDHTD6MBP:~ axc5401$ brew cask install spectacle --force
==> Satisfying dependencies
==> Downloading https://spectacle.s3.amazonaws.com/downloads/Spectacle+1.2.zip
Already downloaded: /Users/axc5401/Library/Caches/Homebrew/downloads/b121fce845422e8d6002e6968285593312527586ff85399b56362b64b1c4e107--Spectacle 1.2.zip
==> Verifying SHA-256 checksum for Cask 'spectacle'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'spectacle' does not match.
Expected: 766d5bf3b404ec567110a25de1d221290bc829302283b28ed0fbe73b9557f30c
  Actual: 295c6069a75dd198cf738e79dd4dcac651829a61ff7832f73d41b04421d8e00a
    File: /Users/axc5401/Library/Caches/Homebrew/downloads/b121fce845422e8d6002e6968285593312527586ff85399b56362b64b1c4e107--Spectacle 1.2.zip
To retry an incomplete download, remove the file above.
If the issue persists, visit:
  https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md
```

#### Output of `brew cask doctor`

```
C02WX1SDHTD6MBP:~ axc5401$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The following directories do not exist:
/usr/local/sbin

You should create these directories and change their ownership to your account.
  sudo mkdir -p /usr/local/sbin
  sudo chown -R $(whoami) /usr/local/sbin

Warning: Xcode alone is not sufficient on Mojave.
Install the Command Line Tools:
  xcode-select --install

C02WX1SDHTD6MBP:~ axc5401$ sudo mkdir -p /usr/local/sbin
Password:
C02WX1SDHTD6MBP:~ axc5401$ sudo chown -R $(whoami) /usr/local/sbin
C02WX1SDHTD6MBP:~ axc5401$ brew cask reinstall spectacle
==> Satisfying dependencies
==> Downloading https://spectacle.s3.amazonaws.com/downloads/Spectacle+1.2.zip
Already downloaded: /Users/axc5401/Library/Caches/Homebrew/downloads/b121fce845422e8d6002e6968285593312527586ff85399b56362b64b1c4e107--Spectacle 1.2.zip
==> Verifying SHA-256 checksum for Cask 'spectacle'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'spectacle' does not match.
Expected: 766d5bf3b404ec567110a25de1d221290bc829302283b28ed0fbe73b9557f30c
  Actual: 295c6069a75dd198cf738e79dd4dcac651829a61ff7832f73d41b04421d8e00a
    File: /Users/axc5401/Library/Caches/Homebrew/downloads/b121fce845422e8d6002e6968285593312527586ff85399b56362b64b1c4e107--Spectacle 1.2.zip
To retry an incomplete download, remove the file above.
```

#### Output of `brew tap`

```
C02WX1SDHTD6MBP:~ axc5401$ brew tap
homebrew/cask
homebrew/core
pivotal/tap
```

**Comment by anzcarroll** [comment]
So I fixed this by `brew cask edit spetacle`
then replacing the hash with the Actual 
that ^^ hasn't been listed as a resolution in any other issues I had searched to resolve this, nor is it described here https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md 

Please update those instructions for this issue

**Comment by reitermarkus** [comment]
> nor is it described here https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md

It provides a link where fixing this is described.

> Help us by [submitting a fix](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).
