### ISSUE TITLE
homebrew/cask/welly is deprecated by homebrew/cask/clyang-welly

### ISSUE THREAD

**Issue by julyclyde** [Homebrew/homebrew-cask#64935]
#### Description of issue

{{homebrew/cask/welly is deprecated by homebrew/cask/clyang-welly}}

homebrew/cask/welly is providing a version 2.7 of Welly.app, which is stored on code.google.com . homebrew/cask/clyang-welly should be used instead.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/64943
