### ISSUE TITLE
openboardview cask's download link is incorrect

### ISSUE THREAD

**Issue by amingilani** [Homebrew/homebrew-cask#64947]
Hi there,

This is a simple one. The cask links to the wrong download file:

```
$ brew cask install openboardview
==> Satisfying dependencies
==> Downloading https://github.com/inflex/OpenBoardView/releases/download/R7.3/O

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'openboardview' with message: Download failed: https://github.com/inflex/OpenBoardView/releases/download/R7.3/OpenBoardView-R7.3-Darwin.dmg
```

Upon visiting [openboardview.org](https://openboardview.org/), we find that the download link is in fact:

```
https://github.com/OpenBoardView/OpenBoardView/releases/download/R7.3/OpenBoardView-R7.3-Darwin.dmg
```

@inflex is the [leading contributor](https://github.com/OpenBoardView/OpenBoardView/graphs/contributors) to the OpenBoardView project, so this is probably just a mistake.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/64948
