### ISSUE TITLE
Incorrect signature in yandexradio

### ISSUE THREAD

**Issue by mfilippov** [Homebrew/homebrew-cask#65007]
I installed yandexradio but I can't launch app. I see message:
```
 com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x100000af.Yandex.Radio[78551]): removing service since it exited with consistent failure - OS_REASON_CODESIGNING | When validating /Applications/Yandex.Radio.app/Contents/MacOS/Yandex.Radio:
com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x100000af.Yandex.Radio[78551]): Binary is improperly signed.
```

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
