### ISSUE TITLE
WPS Office App Language (Chinese)

### ISSUE THREAD

**Issue by robertleeblairjr** [Homebrew/homebrew-cask#65078]
I thought it best to just open an issue concerning the WPS Office cask since the default language distribution is Chinese and it's required to have a login before using the app. The distributions for Windows, Linux, iOS, and Android are distributed with English language defaults for installation. The WPS Office app can be used on macOS with the system default language after the user sets up the app with a login. But, this login is in Chinese and the requirements can be difficult for English users. I wanted to consider this a caveat for this cask but it doesn't exactly meet the requirements established in the caveats.md stanza. If it does meet the requirements per se, then I'll or someone else can submit a pull with the added caveat of this cask being a Chinese language distribution. However, moderators may choose to remove the cask because of not meeting language distribution requirements. I've attached a screenshot of the UI which is still not entirely supporting the system default language, mine being English, after installation and login.

<img width="1512" alt="Screen Shot 2019-06-20 at 8 11 03 AM" src="https://user-images.githubusercontent.com/12276457/59851812-24b57e00-9333-11e9-9728-5df9dcca7d97.png">

**Comment by vitorgalvao** [comment]
Thank you for your concern. This falls under the “[not a discoverability service](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/not_a_discoverability_service.md)” notion:

> users are expected to have reasonable knowledge about the apps they’re installing through us before doing so.

You’re not supposed to to use Homebrew Cask as “hey, I wonder what this app does” but as “I want this app that I’m familiar with”, so this login language subject is something users should be familiar with, or complain upstream.

**Comment by robertleeblairjr** [comment]
> Thank you for your concern. This falls under the “[not a discoverability service](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/not_a_discoverability_service.md)” notion:
> 
> > users are expected to have reasonable knowledge about the apps they’re installing through us before doing so.
> 
> You’re not supposed to to use Homebrew Cask as “hey, I wonder what this app does” but as “I want this app that I’m familiar with”, so this login language subject is something users should be familiar with, or complain upstream.

Thanks for the link and clarification. I was unaware if there were any language distribution/installation requirements. IE, some projects only allow or require specific languages to be included, hosted, etc. I'll know this now if I come across another app with similar language exclusions by the authors.
