### ISSUE TITLE
tla-plus-toolbox cask incompatible with java cask

### ISSUE THREAD

**Issue by hmijail** [Homebrew/homebrew-cask#65251]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Cask `tla-plus-toolbox` installs v1.5.7, which only works with Java 8. Installing brew's java cask seems to break it (it's a known problem that TLA 1.5.7 won't work with Java 11+ [1]), and even jenv doesn't help.

So it would be good to mark the TLA cask as incompatible with the java cask (is that possible?), or at least add a note to it.

For completeness, there already is a `tla-plus-toolbox-nightly` cask in homebrew-cask-versions. 

[1] https://github.com/tlaplus/tlaplus/releases/tag/v1.5.7

#### Command that failed

```
N/A
```

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/65259
