### ISSUE TITLE
Consider replacing android-ndk cask

### ISSUE THREAD

**Issue by rcombs** [Homebrew/homebrew-cask#65250]
This is a follow-up on #58883, which led to the android-ndk cask being removed in #59874. The new recommended solution is apparently to install the Java SDK, and then use it to install the NDK. The documentation on this isn't clear, and it requires using a Java tool from the CLI, setting up `JAVA_HOME` (apparently? Right now I'm getting errors that are apparently related to that), and a fair few other steps just to fetch the package. It's a lot less turn-key than `brew cask install android-ndk`, which is kind of the point of casks.

_Most_ users who install the NDK will also want the Java SDK, but I'm not one of them; I work on native code that happens to run on Android, but not the Java wrapper apps that use it. The old NDK cask served my use-case well, and the new one doesn't.

The NDK doesn't really depend on the SDK in any substantial way; the NDK is for native C/C++ development and largely consists of headers, compilers, shared libs, and native build tools. I don't know any particular reason not to allow it to be installed independently of the more Java-focused SDK.

For now, I ran `git revert a6562a5185c5aefee9b68ea8cd89c58089314405`, `brew cask install android-ndk`, and now things are back to working for me. The cask is a version behind, but it's fine for what I need at the moment, and it was easier than trying to figure out the upstream install process.

**Comment by vitorgalvao** [comment]
I’ve unlocked https://github.com/Homebrew/homebrew-cask/issues/58883. Please make your points there, so this can be discussed amongst Android developers. Looks like none of the HBC maintainers uses those casks, so we’re unsure on what’s the best course of action.
