### ISSUE TITLE
What is the difference between `wine` and `cask/wine-stable`?

### ISSUE THREAD

**Issue by gaochenyi** [Homebrew/homebrew-cask#65309]
There are `wine` and `cask/wine-stable`. They both seem to be the stable branch of wine and have the same version number. What is the difference?

**Comment by vitorgalvao** [comment]
I think @yurikoles is the one that pushed for the `wine` casks. He may be able to explain in detail.

**Comment by yurikoles** [comment]
The main difference is that `wine` formula is built from source and `wine-stable` is official binary pkg from WineHQ.

**Comment by yurikoles** [comment]
But `wine` can't be build on Mojave and higher due to lack of 32 bit dev libs. And can't run on Catalina and higher because Apple had deprecated 32 bit apps.

**Comment by vitorgalvao** [comment]
I though there were bigger differences. In that case, I see no point in having the cask. It should be just the formula.
