### ISSUE TITLE
intel-power-gadget CAN NOT use on 10.14.5

### ISSUE THREAD

**Issue by out0fmemory** [Homebrew/homebrew-cask#65528]
#### General troubleshooting steps

- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

This new version CAN NOT use on 10.14.5, because this version can not load intel driver, and the old version works(even the cert is out of date, old version can install manually)

**Comment by vitorgalvao** [comment]
That’s not an HBC problem. Only thing we can do is prevent it from being installed on Mojave.
