### ISSUE TITLE
Is it possible to tell homebrew to use a specific tap when installing a cask?

### ISSUE THREAD

**Issue by mrjayviper** [Homebrew/homebrew-cask#65547]
I want to use a specific tap when installing a cask. The cask is available in the built-in cask but I want to use a 3rd party one.

How can I do it?

Thanks

**Comment by vitorgalvao** [comment]
I’ll ask that you stop using the issue tracker for generic questions about functionality. That’s what [Discourse and IRC](https://github.com/Homebrew/brew#community) are for.

**Comment by vitorgalvao** [comment]
I ask that you stop using the issue tracker for generic questions about functionality. That’s what [Discourse and IRC](https://github.com/Homebrew/brew#community) are for.
