### ISSUE TITLE
getting this error on my personal tap

### ISSUE THREAD

**Issue by mrjayviper** [Homebrew/homebrew-cask#65548]
I am using a custom_download_strategy.rb on my tap. Any ideas on how to fix?

Thanks

------------------
contents of my-cask-here.rb
```
require_relative "../custom_download_strategy.rb"

cask 'my-cask-here' do
  version '2.4'
  sha256 '9fa3758363c9a70687b65f7bb7522e3e515cd63380ebb031aaaa18844fb344ab'

  url "https://github.com/my-cask-here/releases/download/apps/my-cask-here-#{version}.zip", :using => CustomGitHubPrivateRepositoryReleaseDownloadStrategy
  name 'my cask here'
  homepage 'http://www.my-cask-here.com'

  app "my-cask-here-#{version}/my-cask-here.app"
end
```

this is the error I'm getting when I want to reinstall the cask
`Cask 'my-cask-here' is unreadable: cannot load such file -- /usr/local/Caskroom/my-cask-here/.metadata/2.4/20190527075825.026/custom_download_strategy.rb`

**Comment by vitorgalvao** [comment]
The message tells you what is going on. It can’t load the file because it’s doing so from the `.metadata` directory. Try using a full path.

Either way, we don’t support what you’re trying to do, in casks.
