### ISSUE TITLE
sqlectron: Accept --appdir flag

### ISSUE THREAD

**Issue by mcandre** [Homebrew/homebrew-cask#65616]
### Description of feature/enhancement

The sqlectron cask should accept the conventional `--appdir` flag.

### Justification

`--appdir` customization allows users to install applications outside of `/Applications`, such as in `$HOME/Applications`. This is often useful for multi-user environments and restricted mac environments.

### Example use case

Multi-user environments and restricted mac environments.

**Comment by vitorgalvao** [comment]
This is not a feature request; it’s a bug report (it should work).

Open it as that, and follow the commands in the template.
