### ISSUE TITLE
Website to search for casks

### ISSUE THREAD

**Issue by muuvmuuv** [Homebrew/homebrew-cask#65659]
### Description of feature/enhancement

Maybe I have missed some link but I can not find a reference where to search for casks. Would be great to see/have a website where I can search for casks or a command to do so.

### Example use case

At the moment I am preparing my Mac for a full reinstallation of macOS in autumn with macOS Catalina and trying to replace manual installation processes with automation. Therefore, I was searching for a way to install apps and found casks but no way to search for applications.

**Comment by muuvmuuv** [comment]
Okay I found that https://formulae.brew.sh/cask/ is the thing I wanted but the search should be optimized. If I type in _1Password_ I can not see the cask just some other results. Generally I would optimize the website to not load every cask and rather implement a lazyload component to load on scroll like https://itnext.io/infinite-component-scrolling-with-react-lazy-and-intersectionobserver-7774c03b08f2

**Comment by vitorgalvao** [comment]
> or a command to do so.

`brew search` outputs both formulae and casks. `brew search --casks` will output all casks.

**Comment by muuvmuuv** [comment]
Thanks, this wasn't really clear. I expected something like `brew cask search xxx`.
