### ISSUE TITLE
not really a feature request: What's the difference between brew tap myusername/mytap && brew cask install myapp VS brew cask install myusername/myrepo/myapp

### ISSUE THREAD

**Issue by mrjayviper** [Homebrew/homebrew-cask#65652]
as above.

Why do I need to tap a repo when I can just install an app provided by a tap directly.

Thanks!

**Comment by vitorgalvao** [comment]
> when I can just install an app provided by a tap directly.

You can’t. That command is shorthand for tapping and installing. Tapping still happens.

But I’ve asked you before to not use the issue tracker for general questions. Use the discourse or IRC, or even better, read the documentation.
