### ISSUE TITLE
docker-toolbox should be renamed or aliased to docker-desktop

### ISSUE THREAD

**Issue by muuvmuuv** [Homebrew/homebrew-cask#65662]
The link is also redirecting to: https://www.docker.com/products/docker-desktop

And I think the version should be updated or a new fomulae should be created for the desktop version. On https://formulae.brew.sh/cask/docker-toolbox it still shows 18.x.

**Comment by vitorgalvao** [comment]
Thank you for the report. None of those solutions work because:

1. We don’t support cask aliases.
2. Cask tokens can’t end in `-desktop`.

But if it is now a different thing, it should be fixed.

**Comment by muuvmuuv** [comment]
Oh, what is the reason that it cannot have `-desktop` at the end? I mean because it is the name of it can we make an exception here?

Yes, it is a different thing. The `-desktop` version does not come with Kitematic and is now a full application with advanced settings and Kubernetes support.

Here is a link: https://docs.docker.com/toolbox/toolbox_install_windows/

**Comment by vitorgalvao** [comment]
> Oh, what is the reason that it cannot have `-desktop` at the end?

Because `desktop` is just noise. Homebrew Cask only works on macOS; every application is “Desktop”. Same as “App”. See the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).

> Here is a link: https://docs.docker.com/toolbox/toolbox_install_windows/

That’s Windows.

**Comment by muuvmuuv** [comment]
I know, but same for mac. On the left is a navigation. Just copied the wrong url: https://docs.docker.com/toolbox/toolbox_install_mac/

**Comment by muuvmuuv** [comment]
Okay it seems that docker-toolbox is the old installer and docker is the right way to go. So maybe remove docker-toolbox because it is not longer used?

**Comment by vitorgalvao** [comment]
> So maybe remove docker-toolbox because it is not longer used?

I’ll need a source for that claim.

```
docker-toolbox (added 1167 days ago)
30 days: 390 (#259)
90 days: 1,327 (#225)
365 days: 5,905 (#206)
```

**Comment by muuvmuuv** [comment]
Was not sure; here is a comment from Docker:

> Legacy desktop solution. Docker Toolbox is for older Mac and Windows systems that do not meet the requirements of Docker Desktop for Mac and Docker Desktop for Windows. We recommend updating to the newer applications, if possible.

https://docs.docker.com/toolbox/overview/

Okay, _" Docker Toolbox is for older Mac and Windows"_. I'll close this then. At the end it was a misunderstood of mine which cask installs what.
