### ISSUE TITLE
Getting homebrew casks data plugged in to Repology

### ISSUE THREAD

**Issue by luzpaz** [Homebrew/homebrew-cask#65978]
Repology is becoming a powerful service to understand what's available in the package ecosystem. Currently both [Homebrew and Linuxbrew](https://repology.org/repositories/statistics) are available and are going strong. We are missing Homebrew-casks though. 

**TLDR**
This is where casks stalled:  
https://github.com/repology/repology/issues/310#issuecomment-499703252
> https://formulae.brew.sh/api/cask.json is close but it lacks usable package names, like ones in the left column of https://formulae.brew.sh/cask  

There is partial alpha support but it's not enabled:  
https://github.com/repology/repology/commit/ba1781ffac7316975f6cf5bda037175a9919efe6

Here is where the thread has played out or has had relevance:  
https://github.com/repology/repology/issues/310  
https://github.com/Homebrew/brew/issues/4291  
https://github.com/Homebrew/brew/pull/4410  
https://github.com/Homebrew/brew.sh/pull/228  
https://github.com/Homebrew/brew/pull/4620  
https://github.com/Homebrew/homebrew-formula-analytics/pull/59  
https://github.com/Homebrew/formulae.brew.sh/pull/93    
https://github.com/Homebrew/homebrew-cask/pull/59521

**Comment by vitorgalvao** [comment]
Fine by me.

Pinging @reitermarkus @MikeMcQuaid @alexbostock.
