### ISSUE TITLE
Can't install old versions

### ISSUE THREAD

**Issue by mcint** [Homebrew/homebrew-cask#66035]
### Description of feature/enhancement

Allow specification of the version to be installed.

### Justification

I've upgrade a cask application only to find that its new behavior conflicts with another application. I'd like to specify a version to be installed so I can:
1. keep using my previous workflow, and
2. "bisect" the issue and let the maintainer know at what version the issue was introduced.

### Example use case

See previous.

**Comment by vitorgalvao** [comment]
You can only specify versions via specific casks ([homebrew/cask-versions](https://github.com/Homebrew/homebrew-cask-versions)). Due to the nature of a large portion of software installed by casks being auto updated, your requests is unfeasible.
