### ISSUE TITLE
command line version of PDF-images 

### ISSUE THREAD

**Issue by ryofurue** [Homebrew/homebrew-cask#66211]
### Description of feature/enhancement

I thought it would be nice if the command-line version of PDF-images is available in /usr/local/bin.  ( /Applications/PDF-Images.app/Contents/MacOS/pdfimages is the one. )

### Justification

I think it's a common command-line tool for Linux users.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/commit/de6e1f8c2d91e106a4a612a29277246481fcd2a4
