### ISSUE TITLE
Provide a way to delete cask installers

### ISSUE THREAD

**Issue by ptmkenny** [Homebrew/homebrew-cask#66242]
# A detailed description of the proposed feature

Add a command to delete cask installers (all installers in the Caskroom directory).

# The motivation for the feature

brew cleanup can clean up the cache, but cask installers are not considered part of the cache.  If you install MacTeX, it leaves a 4 GB installer behind.

Apple still sells laptops with just 128 GB of space, so it would be nice to have a way to have a command to delete the installers.

# How the feature would be relevant to at least 90% of Homebrew users

Most Mac users are on laptops where space disk space is at a premium. Installers can always be re-downloaded if necessary, so there's no reason to keep them around when space is limited.

# What alternatives to the feature have been considered

Going into the Caskroom directory and deleting installers manually.

**Comment by vitorgalvao** [comment]
This has already been discussed a few times.

We need to keep everything because some things are required for uninstallation. The installers are required or reinstallation, in case of a problem with an upgrade.

I’d be open to an option to delete `pkg` installers, but unless you’re offering to implement it yourself, it’s unlikely to get done.

**Comment by ptmkenny** [comment]
Ok, unfortunately I'm not much of a developer, so I'll just a snippet to delete them manually:

`find /usr/local/caskroom -type f -name "*.pkg" -delete`

**Comment by vitorgalvao** [comment]
`find "$(brew --prefix)/Caskroom" -type f -name '*.pkg' -delete` is better.

**Comment by ptmkenny** [comment]
Thanks, that’s helpful!

2019年7月15日(月) 21:39 Vítor Galvão <notifications@github.com>:

**Comment by reitermarkus** [comment]
We won't add this. As already mentioned, this would break upgrade functionality.
