### ISSUE TITLE
Homebrew Cask needs a iOS app for contributors on-the-go

### ISSUE THREAD

**Issue by core-code** [Homebrew/homebrew-cask#66601]
here you go, a rudimentary HomeBrew Cask App for contributors on-the-go called HBCA:

https://github.com/core-code/MiscApps/tree/master/HBCA

features
1.) it allows you to find out the name of any cask via a live search bar that works in realtime, in contrast to 'brew search' which takes exactly 7.3 eternities
2.) for any given cask, it allows you to quickly look at the caskfile, e.g. to learn about the latest version of this app in HBC. if will first display the version of the last "fetch", and then replace with the live version as soon as it is downloaded
3.) for any cask, you can quickly open a pull request in the webinterface
4.) for any cask, you can also calculate the checksum of a new version by entering the new version number. it will downloading the new file, a bit similarly to cask-repair to calculate the checksum. after it has finished downloading you can copy either the SHA256 or the whole updated caskfile including the new versionnumber => to submit as a PR via feature #3
5.) if you do have a server which can host CGI files, you can copy a short CGI file on your server and define the server URL before compiling the app. this will allow you to calculate checksums of updates on your server, instead of downloading updates locally to your iOS device. obviously, this can safe time and bandwidth

if interested, download the sources and give it a go ;) to compile, you need
• a recent Xcode version 
• and will also need to place a copy of our CoreLib ( https://github.com/core-code/CoreLib ) next to the HBCA folder. 
• i am not sure if a paying Apple Developer membership is needed these days to install self compiled apps on your iOS device. 
• you'll need to create a file "HBCA.xcconfig" in the HBCA folder containing 
`"DEVELOPMENT_TEAM = <yourappledeveloperteamid>"`

**Comment by core-code** [comment]
cc https://github.com/Homebrew/homebrew-cask/pull/66502#issuecomment-513909128 and @vitorgalvao : sadly no cool icon, just re-used the 🍻emoji. you wouldn't want to see my programmer's art ;p

**Comment by reitermarkus** [comment]
Doesn't compile for me, here's what I did:

```sh
git clone https://github.com/core-code/MiscApps
cd MiscApps
git clone https://github.com/core-code/CoreLib
cd HBCA
echo 'DEVELOPMENT_TEAM = XXXXXXXXXX' > HBCA.xcconfig
```

Then opened in Xcode and tried running:

```
CoreLib.m:99: Property 'fileIsSymlink' not found on object of type 'NSURL *'
```

**Comment by core-code** [comment]
thanks for the "bug report". i'll invesigate shortly

**Comment by core-code** [comment]
i was able to reproduce, and i believe, fix it. 

cd CoreLib;git pull;cd ..

should fix it

**Comment by core-code** [comment]
just FYI: i've added a notarised Mac binary now (its much faster than 'brew search'), and fixed support for iPhone X. also, the project now has a proper readme on the web with download links and screenshot ;-)
