### ISSUE TITLE
Move kindlegen to Core

### ISSUE THREAD

**Issue by davidlday** [Homebrew/homebrew-cask#66725]
If I understand the purpose of the cask extension correctly, it's targeted at the _"management of GUI macOS applications such as Atom and Google Chrome."_

KindleGen, however, is a command line tool also available for Linux (and Windows, but that's irrelevant here). I am considering submitting a PR to homebrew-core for KindleGen that would cover both Mac and Linux, but figured I should see if there's a specific reason it's not there already. Is there a reason not to move KindleGen to core and make it work for Linux as well? I'm not set on the idea of moving it to core, but there's no good installer for KindleGen on Linux and this felt like the best place to start.

**Comment by reitermarkus** [comment]
Is it open-source and can it be built from source?

**Comment by davidlday** [comment]
Good questions - unfortunately no to both. If that means it can't go in core, any suggestions on another suitable tap for it? Maybe linuxbrew/homebrew-extras?

**Comment by reitermarkus** [comment]
> unfortunately no to both

Then it has to stay a cask.

> Maybe linuxbrew/homebrew-extras?

https://github.com/Linuxbrew/homebrew-extra has been archived since you asked this. Your best bet it probably to create your own tap.
