### ISSUE TITLE
Inkscape: Accept --appdir for selecting installation directory

### ISSUE THREAD

**Issue by mcandre** [Homebrew/homebrew-cask#66732]
### Description of feature/enhancement

Add the conventional `--appdir <directory>` flag to the Inkscape cask formula, so that this application can be installed in custom directories.

### Justification

Restricted environments often prohibit the user from installing applications in the main `/Applications` directory.

### Example use case

Corporate Inkscape usage.

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

**Comment by vitorgalvao** [comment]
There’s no reason why that cask wouldn’t be respecting that rule.

**Comment by vitorgalvao** [comment]
Works fine for me. The issue is in your setup. This is a bug report, not a feature request; you used the wrong template.

**Comment by mcandre** [comment]
Hi @vitorgalvao, could you please post the full command you are using to install the Inkscape cask to a custom directory path? Perhaps I am placing the `--appdir` flag in the wrong part of the brew cask command.

**Comment by vitorgalvao** [comment]
```
brew cask uninstall --appdir=/some/path inkscape
```

**Comment by mcandre** [comment]
That's the uninstall command.
