### ISSUE TITLE
Repo inaccesible

### ISSUE THREAD

**Issue by raistlin2912** [Homebrew/homebrew-cask#66893]
Repo can't clone. URL https://github.com/Homebrew/homebrew-cask.git return HTTP 301

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

**Comment by Blaisorblade** [comment]
Now the repo is accessible but very slow; it seems a problem on GitHub's side. I've found https://discourse.brew.sh/t/different-git-in-use/5374 and asked GitHub on https://twitter.com/Blaisorblade/status/1155835681383559168.

**Comment by unitof** [comment]
`cask` recently has been _very_ slow to fetch `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask`, sporadically and for some users. Often takes 5 minutes or longer to `fetch`, and apparently times out for some users.

It's sporadic though—sometimes it fetches immediately.

`brew update -v` will show if and where it's hanging for you. In my case it also hangs on `brew update-reset`, when it gets to

```
==> Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask...
```
