### ISSUE TITLE
Update process takes long

### ISSUE THREAD

**Issue by relikd** [Homebrew/homebrew-cask#66914]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

When running `brew update` the whole process takes a lot of time. Even with a 100Mbit+ internet connection the consol freezes for 5-10 minutes on the following command:

```
Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask
```

#### Output of `brew tap`

```
homebrew/bundle
homebrew/cask
homebrew/cask-versions
homebrew/core
```

**Comment by nikoladev** [comment]
I had this same issue and just now I fixed it by running the following:

```bash
brew untap homebrew/homebrew-cask
brew tap homebrew/homebrew-cask
```

Afterwards `brew update` ran fine again.

The solution was inspired by what @winterflags said in [this comment](https://github.com/Homebrew/homebrew-cask/issues/50586#issuecomment-411798289)

**Comment by vitorgalvao** [comment]
Github has been having issues. There are other closed issues on this.

**Comment by h3adache** [comment]
@vitorgalvao for some reason it's only on this repo.
I try other repos on github and none have issues.
Any ideas?

**Comment by reitermarkus** [comment]
> Any ideas?

No, please contact GitHub Support.

**Comment by relikd** [comment]
I can imagine this being a problem because of the sheer size of the repo (and especially the large history of commits)

**Comment by reitermarkus** [comment]
`homebrew-core` has even more commits, and it's not having problems.

**Comment by relikd** [comment]
btw. `brew untap` showed 140 Mb deleted, and `brew tap` created just 4 Mb. Not sure where all the excess data is coming from. Piled up over the years …

**Comment by jlindsey** [comment]
It might be degraded performance on github's side still (I first noticed this slowdown right after the recent outage a few days ago). If I go in to `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask` and change the git remote url from the https endpoint to ssh, it is still slow but no longer hangs.
