### ISSUE TITLE
Manage multiple copies of the same application & renaming

### ISSUE THREAD

**Issue by madsem** [Homebrew/homebrew-cask#67011]
### Ability to manage multiple copies of the  application & renaming

I'd love to be able to manage multiple Chrome/Firefox etc. copies via Cask.
After reading the man page, this doesn't seem possible at this time. But the base requirements for such a feature already seem to exist by passing `--app-dir` on `install` & `uninstall`.

What I'm talking about in reference:
http://www.justin-credible.net/2016/01/05/running-a-second-instance-of-chrome-for-development/

### Justification

This is something that really many developers need, and also do. Especially when it comes to running multiple independent browser instances. So why not manage those installs also via Cask?

### Example use case

For example, running a second Chrome instance for development. To make it easy to bind it to hotkeys via tools like Hammerspoon it should be possible to actually download a second Chrome binary and rename it to, for example "Google Chrome Dev.app".

Maybe something along the lines of
`brew cask install google-chrome --name "Google Chrome Dev"`

Now you can create an applauncher, and/or bind it to hotkeys using a tool like karabiner-elements / hammerspoon etc.

```applescript
set chrome to "\"/Applications/Google Chrome Dev.app/Contents/MacOS/Google Chrome\""
set userdatadir to "\"$HOME/Library/Application Support/Google/Chrome Dev\""
do shell script chrome & " --restore-last-session --no-default-browser-check --no-pings --disable-reading-from-canvas --disable-webgl --disable-sync --no-first-run --no-referrers --user-data-dir=" & userdatadir & " > /dev/null 2>&1 &"
```

You could now repeat this process for other copies you might need which are always launched with specific switches.

This is a practice often used with Firefox & Chrome in particular, but might also be useful for other types of software.

PS: The renaming part would then also make it possible to automate this process in your dotfiles, assign custom icons to not just launchers but the app copy itself for easy identification and so forth.

**Comment by vitorgalvao** [comment]
Too much added complexity for something too few people will use on too few casks. This already has solutions. Not only you don’t need a second Chrome instance (having a script that calls the one you have is a better solution), web browsers have tons of versions (dev, stable, nightly, canary) already present in Homebrew Cask.
