### ISSUE TITLE
add reason to codeblocks removal PR: #52733

### ISSUE THREAD

**Issue by glensc** [Homebrew/homebrew-cask#67526]
@vitorgalvao: not cool if the cask is just removed and PR doesn't even include reason and the PR conversation is locked so can't even ask: https://github.com/Homebrew/homebrew-cask/pull/52733

preferred if that reason is included in original PR.

**Comment by reitermarkus** [comment]
You can see in the PR that it was referenced in https://github.com/Homebrew/homebrew-cask/issues/52731. If that issue is resolved now, feel free to resubmit the cask.

**Comment by glensc** [comment]
@vitorgalvao could edit the PR and include info to body not leave some template there.

**Comment by vitorgalvao** [comment]
> @vitorgalvao could edit the PR and include info to body not leave some template there.

Or you could read the page and see the linked references, just like @reitermarkus did. That’s what they’re there for!

You’ve got your answer. I don’t see what editing the PR message would do other than consuming even more of my *volunteered* time, which I regret I must now do to address your posts.

I’ll admit I’m trying but failing to not find an smidge of an entitlement tone in your messages in this issue. You’re not being mindful of the time it takes to deal with the barrage of issues we get *daily*, and are only thinking of your personal convenience. I’d appreciate if you’d respect our time.

You were mistaken in your original post (PR did have a reason; locking was done by a bot; and *clearly you can still ask*). It happens, that’s fine, you could have left it at that. I fail to see what continuing to post asking for information you already have accomplishes.

**Comment by glensc** [comment]
locked issues can't be commented

![image](https://user-images.githubusercontent.com/199095/63092467-8593b800-bf6a-11e9-9132-7d44a24118e3.png)

**Comment by vitorgalvao** [comment]
> locked issues can't be commented

I know how locked issues work. But you asked by making a new issue, so clearly you *can* and did ask, and locking wasn’t an impediment. **That’s the correct approach**, but the tone could’ve been better.

Either way the issue is solved, so let’s please leave it at that.
