### ISSUE TITLE
Lifesize released a new app - how to handle this transition?

### ISSUE THREAD

**Issue by raoulbhatia** [Homebrew/homebrew-cask#67548]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

`lifesize` cask is actually installing "Lifesize Cloud.app" (version 10.3.7-235).  There is a new app called "Lifesize.app" (version 2.210.2454).  Both Apps can be installed in parallel.

What is the best approach to handle this situation and to get the new `Lifesize.app` into the repository?  (I know the basics of adding a new cask so this is not an issue)

#### Command that failed

```
n/a
```

#### Output of command with `--force --verbose --debug`

```
n/a
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.1.10
==> macOS
10.14.6
==> SIP
Enabled
==> Java
N/A
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3548 casks)
==> Contents of $LOAD_PATH
[...]
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/core
vitorgalvao/tiny-scripts
```

**Comment by reitermarkus** [comment]
Rename `lifesize` to `lifesize-cloud` and add Lifesize as `lifesize`.

**Comment by vitorgalvao** [comment]
Closing as solved (answered). Now we just need the PR.
