### ISSUE TITLE
kdiff3 moved to github

### ISSUE THREAD

**Issue by chintan9** [Homebrew/homebrew-cask#67716]
#### Description of feature/enhancement
Kdiff3  has new repo. However it does not have dmg file. 😞 

https://github.com/KDE/kdiff3

https://www.phoronix.com/scan.php?page=news_item&px=KDiff3-Restored-And-Joins-KDE

#### Justification
It is new version of kdiff3. 

#### Example use case

**Comment by vitorgalvao** [comment]
> Kdiff3 has new repo. However it does not have dmg file. 😞

There’s nothing we can do, then.

https://github.com/Homebrew/homebrew-cask/pull/67726
