### ISSUE TITLE
Make rmdir: recursive?

### ISSUE THREAD

**Issue by danielbayley** [Homebrew/homebrew-cask#67806]
### Description of feature/enhancement

Make [`uninstall`/`zap`] `rmdir:` recursive, so that it will remove a tree of empty directories that exist under the given path… this should probably also include any `.DS_Store` files under this revised definition of _empty_.

### Justification

This would simplify [`uninstall`/`zap`] `rmdir:` in Casks in [the many] cases where an App leaves behind a tree of empty directories.

### Example use case

~~~ rb
zap rmdir: '~/Library/Application Support/Vendor'
~~~
instead of:
~~~ rb
zap rmdir: [
             '~/Library/Application Support/Vendor/Empty Folder',
             '~/Library/Application Support/Vendor',
           ]
~~~

**Comment by reitermarkus** [comment]
Do we not already support globbing for `rmdir`?

**Comment by reitermarkus** [comment]
Indeed we do:

```ruby
zap rmdir: '~/Library/Application Support/Vendor{,/Empty Folder}'
```

**Comment by danielbayley** [comment]
Ah yes brace expansion does work, but it can get tricky to work out for a tree of nested empty folders beyond one or two… and also this doesn't work if there are any `.DS_Store` files. Surely it would be easier for maintenance if `rmdir` ignored them, and worked recursively from the given single path…?

**Comment by reitermarkus** [comment]
> this doesn't work if there are any `.DS_Store` files

It does:

https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/artifact/abstract_uninstall.rb#L348

**Comment by danielbayley** [comment]
> It does:

Interesting… `rmdir:` often seems to fail; I always assumed it was because of `.DS_Store` files. Still, it would be nice if it was recursive, to save figuring out the exact brace expansion for any/all subfolders… Also @reitermarkus what do you think of handling folder `Icon?`s in the same way as `.DS_Store` files? As these can also prevent `rmdir` from working… Maybe something like:

~~~ rb
if (os_file = Dir[resolved_path.join "{.DS_Store,Icon?}"]).any?
  command.run!("/bin/rm", args: ["-f", "--", os_file], sudo: true, print_stderr: false)
end
~~~

**Comment by reitermarkus** [comment]
> what do you think of handling folder `Icon?`

I don't think we should treat it the same as `.DS_Store`; icons need a deliberate action to be generated in the first place, so they should also require the same for removing it.

**Comment by danielbayley** [comment]
> I don't think we should treat it the same as `.DS_Store`; icons need a deliberate action to be generated in the first place, so they should also require the same for removing it.

Fair enough. I still think `rmdir:` should work recursively on empty folders though… save using brace expansion.

**Comment by vitorgalvao** [comment]
I’m going to close this as low priority and little interest (where’s the bot that used to do that)?

@reitermarkus Please reopen if you disagree.
