### ISSUE TITLE
"brew cleanup -s" does not work when specifying cask by URL instead of name

### ISSUE THREAD

**Issue by core-code** [Homebrew/homebrew-cask#68182]
Homebrew Cask has a feature where you can install a Cask by URL, instead of name. 
For example you can run this to install audacity:

`brew cask install https://www.corecode.io/macupdater/casks/audacity.rb`

However, there seems to be a problem related to the 'cleanup' of the files downloaded in this way - they aren't deleted even when specifying 'brew cleanup -s'

Steps to reproduce
1.) run 'brew cleanup -s'
2.) double-check that '/Users/YOURUSERNAME/Library/Caches/Homebrew/Cask' is empty
3.) run 'brew cask fetch https://www.corecode.io/macupdater/casks/audacity.rb'
4.) run 'brew cleanup -s'
5.) now your '~/Library/Caches/Homebrew/Cask' folder should be empty again
6.) observe that there are two files 'audacity.rb' and 'audacity--2.3.2.dmg' in your cache folder that have not been properly removed by 'brew cleanup -s'

**Comment by vitorgalvao** [comment]
I can reproduce, but this seems to happen only on non-Homebrew casks.

```console
$ brew cask fetch https://www.corecode.io/macupdater/casks/audacity.rb https://raw.githubusercontent.com/Homebrew/homebrew-cask/master/Casks/alfred.rb
# Downloads happen

$ ls "${HOME}/Library/Caches/Homebrew/Cask"
alfred--4.0.3_1092.dmg
alfred.rb
audacity--2.3.2.dmg
audacity.rb

$ brew cleanup -s
Removing: /Users/vitor/Library/Caches/Homebrew/Cask/alfred--4.0.3_1092.dmg... (3MB)

$ ls "${HOME}/Library/Caches/Homebrew/Cask"
alfred.rb
audacity--2.3.2.dmg
audacity.rb
```

**Comment by core-code** [comment]
thats weird. its also noteworthy that the ".rb" file remains in the cache

**Comment by amyspark** [comment]
A bit of tracing tells me both Casks are considered as "non-stale". `audacity` does not exist in homebrew-cask, and `alfred` triggers this line: https://github.com/Homebrew/brew/blob/6c2b9ffdc1c1d606581cf011fd08d70264e72f7f/Library/Homebrew/cleanup.rb#L106

Both Casks are removed with `--prune=all`, anyway.

**Comment by core-code** [comment]
i can confirm that '--prune=all' makes both the download as well as the .rb file go away

**Comment by core-code** [comment]
i'd be fine with closing this, i can just use '--prune=all' FWIW
