### ISSUE TITLE
minikube uninstall command didn't uninstall kubenetest-cli

### ISSUE THREAD

**Issue by skvijay007** [Homebrew/homebrew-cask#68298]
#### General troubleshooting steps

- [y] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [y] I have retried my command with `--force`.
- [y] I ran `brew update-reset && brew update` and retried my command.
- [y] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [y] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [y] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

To help us debug your issue please explain:

What you were trying to do (and why)
I was writing script file to install all the necessary tools include minikube.
What happened (include command output)
When installed minikube it installed kubectl/kubernetest-cli in both paths '/usr/local/bin' and '/usr/local/Cellar'. After wards when tried to uninstall minikube using 'brew cask uninstall minikube', it just uninstalled minikube but not kubectl or kubernetest-cli. 

What you expected to happen
When uninstalled minikube, it should have removed kubernetes-cli from both paths "usr/loca/bin and usr/local/Cellar". 

Step-by-step reproduction instructions (by running brew install commands)
brew cask install minikube
ls /usr/local/bin - # You will find minikube and kubectl
ls /usr/local/Cellar - # You will find minikube and kubernetes-cli

brew cask uninstall minikube
ls /usr/local/bin - #You will not find minikube but kubectl is still there
ls /usr/local/Cellar - #You will not find minikube but kubernetes-cli is still there

#### Command that failed

```
{{replace this}}
```

#### Output of command with `--force --verbose --debug`

```
{{replace this}}
```

#### Output of `brew cask doctor`

```
{{replace this}}
```

#### Output of `brew tap`

```
{{replace this}}
```

**Comment by vitorgalvao** [comment]
We don’t auto-uninstall dependencies.

Next time, please fill the template.
