### ISSUE TITLE
Cask request: Sonos #37551

### ISSUE THREAD

**Issue by RobertClarke** [Homebrew/homebrew-cask#68378]
### Description of feature/enhancement

The Sonos app is miscategorized as a driver. Sonos for OSX is a fully-fledged app and should be included in the normal cask repo. A user should be able to run brew cask install Sonos without tapping homebrew/cask-drivers.

Currently located at https://github.com/Homebrew/homebrew-cask-drivers/blob/master/Casks/sonos.rb

### Justification

N/A

### Example use case

N/A

**Comment by vitorgalvao** [comment]
Our definition of driver may be broader than expected, but [it is well defined](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask):

> Software to make a hardware peripheral recognisable and usable by the system. If the software is useless without the peripheral, it’s considered a driver.
