### ISSUE TITLE
fix metadata on update

### ISSUE THREAD

**Issue by MoritzFago** [Homebrew/homebrew-cask#68525]
#### General troubleshooting steps

not applicable

#### Description of issue

Update metadata for installed cask on update for problems like: #58046

It's a terrible user-experience, that if you try to remove or reinstall some cask like the popular wireshark cask, you are met with a non descriptive error message and have to google for a solution, this should be done automatically, if a breaking change is implemented.

**Comment by vitorgalvao** [comment]
Yes, we’re aware. That problem is more complex than that. We’re still discussing solutions.
