### ISSUE TITLE
Make `genymotion` cask depend explicitly on `virtualbox` v 6.0.4

### ISSUE THREAD

**Issue by emanueleDiVizio** [Homebrew/homebrew-cask#68536]
### Description of feature/enhancement

`genymotion` cask would be better off in depending explicitly on `virtualbox` version 6.0.4. This is because, as stated in [Genymotion FAQs ](genymotion.com/help/desktop/faq/#compatible-virtualbox-versions).

> Several versions of VirtualBox are known to cause issues in Genymotion.
For Genymotion to run properly, make sure you have the right version of VirtualBox installed:
Windows: 6.0.4
macOS: 6.0.4
Linux: make sure VirtualBox is installed on your system. If not, install the version of VirtualBox provided by your distribution. Please note that VirtualBox versions prior to 5.2.22 may not work well with Genymotion.

### Justification

Genymotion cask is currently depending on the latest version of `virtualbox`. This causes the emulator to behave weirdly and very slowly, as Genymotion depends on a very particular version of VB (`6.0.4`) to behave correctly.

### Example use case

Anyone installing VirtualBox through Cask will have to manually uninstall `virtualbox` and reinstall `virtualbox` version `6.0.4`. In order to prevent so, it would be nice to depend explicitly on `virtualbox -v 6.0.4`.

**Comment by vitorgalvao** [comment]
That’s quite a bit of work. That would mean someone would have to be on top of `genymotion`’s requirements, always update the `depends_on` with the version, add the specific versions of `virtualbox` to [homebrew/cask-versions](https://github.com/Homebrew/homebrew-cask-versions) *and* remove the previous one.

Unless someone wants to take that job, it won’t happen. And it needs to be someone who has the available time for the commitment and doesn’t leave the other maintainers hanging if they decide to leave.

**Comment by emanueleDiVizio** [comment]
I hear you @vitorgalvao, thanks for your input! 
I agree with you; this looks like quite a bit of work.

 Do you reckon it'd be a good idea to echo a note in the script just pointing out that the preferred `virtualbox` version is `6.0.4` on mac? I reckon that would be enough to inform people at least.

**Comment by vitorgalvao** [comment]
> Do you reckon it'd be a good idea to echo a note in the script just pointing out that the preferred `virtualbox` version is `6.0.4` on OSX?

No, because that would also need constant updating. But I would consider a [`caveat`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/caveats.md) informing users `genymotion` requires specific `virtualbox` versions which might be different from the one installed via HBC, if there’s a webpage we can link to that has up-to-date information on which `genymotion` version requires which `virtualbox` version.

**Comment by emanueleDiVizio** [comment]
Alright, that suits me, we do have a link for it ([Genymotion FAQs ](genymotion.com/help/desktop/faq/#compatible-virtualbox-versions)). I can look into it
