### ISSUE TITLE
VirtualBox cask: installer fails

### ISSUE THREAD

**Issue by findurance** [Homebrew/homebrew-cask#68658]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

VirtualBox cask installer fails

#### Command that failed

brew cask install virtualbox virtualbox-extension-pack

#### Output of command with `--force --verbose --debug`

==> Cask::Installer#install
==> Printing caveats
==> Caveats
To install and/or use virtualbox you may need to enable its kernel extension in:
  System Preferences → Security & Privacy → General
For more information refer to vendor documentation or this Apple Technical Note:
  https://developer.apple.com/library/content/technotes/tn2459/_index.html

==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://download.virtualbox.org/virtualbox/6.0.12/VirtualBox-6.0.12-133076-OSX.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/2.1.11-26-g9a03431\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.54.0 --location --silent --head --request GET https://download.virtualbox.org/virtualbox/6.0.12/VirtualBox-6.0.12-133076-OSX.dmg
Already downloaded: /Users/lassi/Library/Caches/Homebrew/downloads/7dbbf6515aed00af07539cb1a2518d47806b99674d0261272edb986beb595f85--VirtualBox-6.0.12-133076-OSX.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/lassi/Library/Caches/Homebrew/downloads/7dbbf6515aed00af07539cb1a2518d47806b99674d0261272edb986beb595f85--VirtualBox-6.0.12-133076-OSX.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/lassi/Library/Caches/Homebrew/downloads/7dbbf6515aed00af07539cb1a2518d47806b99674d0261272edb986beb595f85--VirtualBox-6.0.12-133076-OSX.dmg
==> /Users/lassi/Library/Caches/Homebrew/downloads/7dbbf6515aed00af07539cb1a2518d47806b99674d0261272edb986beb595f85--VirtualBox-6.0.12-133076-OSX.dmg is quarantined
==> Downloaded to -> /Users/lassi/Library/Caches/Homebrew/downloads/7dbbf6515aed00af07539cb1a2518d47806b99674d0261272edb986beb595f85--VirtualBox-6.0.12-133076-OSX.dmg
==> Verifying SHA-256 checksum for Cask 'virtualbox'.
==> Installing Cask virtualbox
==> Cask::Installer#stage
hdiutil imageinfo /Users/lassi/Library/Caches/Homebrew/downloads/7dbbf6515aed00af07539cb1a2518d47806b99674d0261272edb986beb595f85--VirtualBox-6.0.12-133076-OSX.dmg
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/lassi/Library/Caches/Homebrew/downloads/7dbbf6515aed00af07539cb1a2518d47806b99674d0261272edb986beb595f85--VirtualBox-6.0.12-133076-OSX.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/c1/m_f2hl714jng_p6c1xqt37r00000gn/T/d20190905-22809-1a3r0bk /Users/lassi/Library/Caches/Homebrew/downloads/7dbbf6515aed00af07539cb1a2518d47806b99674d0261272edb986beb595f85--VirtualBox-6.0.12-133076-OSX.dmg
find . -print0
mkbom -s -i /var/folders/c1/m_f2hl714jng_p6c1xqt37r00000gn/T/20190905-22809-gg8qq1.list -- /var/folders/c1/m_f2hl714jng_p6c1xqt37r00000gn/T/20190905-22809-u5ph8w.bom
ditto --bom /var/folders/c1/m_f2hl714jng_p6c1xqt37r00000gn/T/20190905-22809-u5ph8w.bom -- /private/var/folders/c1/m_f2hl714jng_p6c1xqt37r00000gn/T/d20190905-22809-1a3r0bk/dmg.w6QmP9 /var/folders/c1/m_f2hl714jng_p6c1xqt37r00000gn/T/d20190905-22809-p0s9w0
diskutil eject /private/var/folders/c1/m_f2hl714jng_p6c1xqt37r00000gn/T/d20190905-22809-1a3r0bk/dmg.w6QmP9
cp -pR /var/folders/c1/m_f2hl714jng_p6c1xqt37r00000gn/T/d20190905-22809-p0s9w0/VirtualBox.pkg /usr/local/Caskroom/virtualbox/6.0.12,133076/VirtualBox.pkg
cp -pR /var/folders/c1/m_f2hl714jng_p6c1xqt37r00000gn/T/d20190905-22809-p0s9w0/VirtualBox_Uninstall.tool /usr/local/Caskroom/virtualbox/6.0.12,133076/VirtualBox_Uninstall.tool
cp -pR /var/folders/c1/m_f2hl714jng_p6c1xqt37r00000gn/T/d20190905-22809-p0s9w0/UserManual.pdf /usr/local/Caskroom/virtualbox/6.0.12,133076/UserManual.pdf
chmod -Rf +w /var/folders/c1/m_f2hl714jng_p6c1xqt37r00000gn/T/d20190905-22809-p0s9w0
==> Verifying Gatekeeper status of /Users/lassi/Library/Caches/Homebrew/downloads/7dbbf6515aed00af07539cb1a2518d47806b99674d0261272edb986beb595f85--VirtualBox-6.0.12-133076-OSX.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/lassi/Library/Caches/Homebrew/downloads/7dbbf6515aed00af07539cb1a2518d47806b99674d0261272edb986beb595f85--VirtualBox-6.0.12-133076-OSX.dmg
==> /Users/lassi/Library/Caches/Homebrew/downloads/7dbbf6515aed00af07539cb1a2518d47806b99674d0261272edb986beb595f85--VirtualBox-6.0.12-133076-OSX.dmg is quarantined
==> Propagating quarantine from /Users/lassi/Library/Caches/Homebrew/downloads/7dbbf6515aed00af07539cb1a2518d47806b99674d0261272edb986beb595f85--VirtualBox-6.0.12-133076-OSX.dmg to /usr/local/Caskroom/virtualbox/6.0.12,133076
/usr/bin/xattr -p com.apple.quarantine /Users/lassi/Library/Caches/Homebrew/downloads/7dbbf6515aed00af07539cb1a2518d47806b99674d0261272edb986beb595f85--VirtualBox-6.0.12-133076-OSX.dmg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5d70c91f\;Homebrew\\x20Cask\;D88F3F70-5BAD-490A-BB7F-023BA91C9A92
==> Creating metadata directory /usr/local/Caskroom/virtualbox/.metadata/6.0.12,133076/20190905090014.321.
==> Creating metadata subdirectory /usr/local/Caskroom/virtualbox/.metadata/6.0.12,133076/20190905090014.321/Casks.
==> Installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x00007fcf379f8518>
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for virtualbox; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
/usr/bin/sudo -E -- env LOGNAME=lassi USER=lassi USERNAME=lassi /usr/sbin/installer -pkg /usr/local/Caskroom/virtualbox/6.0.12,133076/VirtualBox.pkg -target / -verboseR
installer: Package name is Oracle VM VirtualBox
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Oracle VM VirtualBox…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%9.857540
installer:PHASE:Writing files…
installer:%25.475077
installer:PHASE:Writing files…
installer:%49.769023
installer:PHASE:Writing files…
installer:%86.611429
installer:PHASE:Running package scripts…
installer:%87.488225
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
==> Purging files for version 6.0.12,133076 of Cask virtualbox
Error: Failure while executing; `/usr/bin/sudo -E -- env LOGNAME=lassi USER=lassi USERNAME=lassi /usr/sbin/installer -pkg /usr/local/Caskroom/virtualbox/6.0.12,133076/VirtualBox.pkg -target / -verboseR` exited with 1. Here's the output:
installer: Package name is Oracle VM VirtualBox
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Oracle VM VirtualBox…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%9.857540
installer:PHASE:Writing files…
installer:%25.475077
installer:PHASE:Writing files…
installer:%49.769023
installer:PHASE:Writing files…
installer:%86.611429
installer:PHASE:Running package scripts…
installer:%87.488225
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:111:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:52:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:59:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:65:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:52:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:34:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:214:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:205:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:103:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:23:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'

#### Output of `brew cask doctor`

==> Homebrew Version
2.1.11-26-g9a03431
==> macOS
10.14.6
==> SIP
Enabled
==> Java
N/A
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3524 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-cobertura-1.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.35.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-performance-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-0.74.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unicode-display_width-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-retry-0.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-3.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-mocks-3.8.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-expectations-3.8.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-core-3.8.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-support-3.8.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parser-2.6.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parallel_tests-2.29.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parallel-1.17.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mustache-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/nokogiri-1.10.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/nokogiri-1.10.3
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/net-http-persistent-3.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mime-types-3.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mime-types-data-3.2019.0331/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.3
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unf_ext-0.0.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/unf_ext-0.0.7.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/coveralls-0.8.23/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/thor-0.20.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/tins-1.21.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/docile-1.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/json-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/json-2.2.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/backports-3.15.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/activesupport-5.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/i18n-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.1.5/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/bash"

#### Output of `brew tap`

homebrew/cask
homebrew/core

**Comment by vitorgalvao** [comment]
> To install and/or use virtualbox you may need to enable its kernel extension in:
System Preferences → Security & Privacy → General

Did you do this? Because there are tons of issues of this exact same complaint, and they all failed to follow those instructions.

Also, please don’t remove the backticks from the template. Put your code *inside* them. As it is, your issue is hard to read.

**Comment by findurance** [comment]
If you have a ton of duplicate, I think this really shows as a usability issue: the error message is followed by a rather extensive list of Ruby script errors, hiding the actual error message from the user, and in at least two ways:
1. The install is not aborted at the error, but it continiues with additional output
2. The additional output after the suggested fix gives the impression that the change is not needed.

So, will this issue get along with one of those duplicate issues? If so, it would be good to make note of that issue in this bug report.

**Comment by vitorgalvao** [comment]
> the error message is followed by a rather extensive list of Ruby script errors

Because you ran it with specific flags geared towards outputting more information for debugging.

> If you have a ton of duplicate, I think this really shows as a usability issue

We have several issues for that problem, yes, but nowhere near the amount of installations this cask has, over ten thousand a month!

```
virtualbox (added 2489 days ago)
30 days: 10,091 (#11)
90 days: 32,572 (#11)
365 days: 142,347 (#10)
```

If 10000 users handle it fine and 3 don’t, the problem isn’t the message but those 3 not reading it even when posting, or not searching before opening new issues. There’s only so much we can do in the way of information.

**Comment by findurance** [comment]
> Because you ran it with specific flags geared towards outputting more information for debugging.

Well, it showed quite extensive output even without the debug flags.. Like so:


brew cask install virtualbox virtualbox-extension-pack
==> Caveats
To install and/or use virtualbox you may need to enable its kernel extension in:
  System Preferences → Security & Privacy → General
For more information refer to vendor documentation or this Apple Technical Note:
  https://developer.apple.com/library/content/technotes/tn2459/_index.html

==> Satisfying dependencies
==> Downloading https://download.virtualbox.org/virtualbox/6.0.12/VirtualBox-6.0.12-133076-OSX.dmg
Already downloaded: /Users/lassi/Library/Caches/Homebrew/downloads/7dbbf6515aed00af07539cb1a2518d47806b99674d0261272edb986beb595f85--VirtualBox-6.0.12-133076-OSX.dmg
==> Verifying SHA-256 checksum for Cask 'virtualbox'.
==> Installing Cask virtualbox
==> Running installer for virtualbox; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
installer: Package name is Oracle VM VirtualBox
installer: Installing at base path /
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
==> Purging files for version 6.0.12,133076 of Cask virtualbox
Error: Failure while executing; `/usr/bin/sudo -E -- env LOGNAME=lassi USER=lassi USERNAME=lassi /usr/sbin/installer -pkg /usr/local/Caskroom/virtualbox/6.0.12,133076/VirtualBox.pkg -target /` exited with 1. Here's the output:
installer: Package name is Oracle VM VirtualBox
installer: Installing at base path /
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:111:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:52:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:59:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:65:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:52:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:34:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:214:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:205:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:103:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:23:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'

**Comment by findurance** [comment]
So, just how is a user supposed to tell from that, whether a message actually tells it is a problem or not.

It would be far more clearer, if:
a) Brew would quit after the first error, and not flood the console with other a bit useless output
b) Brew would show the actual error as the **final** message, even if it flooded with the nonsense.

**Comment by vitorgalvao** [comment]
After you run the install command, right at the top is the information, with a helpful `==> Caveats`. Yes, you “may” need to do it because you may have already done it in a previous version.

**The vast majority of people don’t have the problem you just experienced**. The ones that do get pointed to the message, realise the mistake and carry on.

This is not important. You didn’t read the instructions, it happens, let it go. You’re not doing yourself any favours by being antagonistic on this front.
