### ISSUE TITLE
Houdahspot wrong URL

### ISSUE THREAD

**Issue by aukaheng** [Homebrew/homebrew-cask#69103]
The URL in the [json](https://formulae.brew.sh/api/cask/houdahspot.json) file should be
https://www.houdah.com/houdahSpot/updates/cast5_assets/HoudahSpot5.0.8.zip
instead of
https://www.houdah.com/HoudahSpot5.0.8.zip

**Comment by vitorgalvao** [comment]
It’s [the cask itself](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/houdahspot.rb) that needs the fix. Care to submit the PR?
