### ISSUE TITLE
squirrelsql is not working and requires extra steps/info

### ISSUE THREAD

**Issue by maephisto666** [Homebrew/homebrew-cask#69409]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Not sure if this is the proper place to notify about this issue. In short terms, after installing SQuirreL using the original installer (e.g. `squirrel-sql-#{version}-MACOSX-install.jar`) the installation is fine but the program does not start. 

The reason is related strictly to SQuirreL and it is described here [Launching Squirrel SQL client on Mac OS](https://stackoverflow.com/questions/46370597/launching-squirrel-sql-client-on-mac-os): simply put, the starting shell script is wrong and needs some manual adjustments. 

Is this thing "addressable" by the cask installer 
- either making some changes directly to the shell script for SQuirreL
- or showing extra info after the installation and asking the user to do the change manually

?

What is the general recommendation in this case?

#### Command that failed

No command failed.

**Comment by vitorgalvao** [comment]
> The reason is related strictly to SQuirreL

Then it needs to be reported to and fixed by them.

> What is the general recommendation in this case?

We install things; if the installation script is broken they need to fix it, we shouldn’t be duct taping it.
