### ISSUE TITLE
Visual Studio 8.3.0.1805 requires preview version 6.4.0 of Mono MDK

### ISSUE THREAD

**Issue by tzinmein** [Homebrew/homebrew-cask#69591]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

I used cask-repair to create a pull request for the current stable version of Visual Studio, did not realise that it requires a Mono MDK version (6.4.0) that's currently in preview as I had the MDK preview installed manually.

I'll like to know what's the best way forward for a situation like this so I can try to correct this.

#### Command that failed

```
NA
```

#### Output of command with `--force --verbose --debug`

```
NA
```

#### Output of `brew cask doctor`

```
NA
```

#### Output of `brew tap`

```
homebrew/bundle
homebrew/cask
homebrew/cask-drivers
homebrew/cask-eid
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/services
jesseduffield/lazydocker
mas-cli/tap
vitorgalvao/tiny-scripts
```

**Comment by vitorgalvao** [comment]
What’s the prediction on how long for that version to become the stable download?

**Comment by tzinmein** [comment]
I don't have that information offhand. I'll try to look for it.

**Comment by tzinmein** [comment]
Mono stable has been updated to 6.4.0
