### ISSUE TITLE
Detecting Electron appcasts

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-cask#69749]
_Originally posted by @core-code in https://github.com/Homebrew/homebrew-cask/pull/69611#issuecomment-534687317_

i think i can add something to our current knowhow about finding appcasts for apps ( https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md )

many electron based apps contain a file in `Contents/Resources/app-update.yml `

this file contains the configuration how the app should be updates, i.e. the appcast information we are interested in

**example provider generic (http)**
```
provider: generic
url: 'https://desktop-release.notion-static.com/'
channel: latest
```

this means there will be a an appcast at URL+"latest-mac.yml"

**example provider s3**

```
provider: s3
bucket: timeular-desktop-packages
path: mac/production
```
this means there will be a an appcast at BUCKETNAME + ".s3.amazonaws.com/mac/production/latest-mac.yml"

other possible providers are "github" where the app is configured to use the github atom feed (which we can use too) or "bitbucket" which i haven't seen in practice yet

**Comment by vitorgalvao** [comment]
@amyspark I’m reopening because in addition to the script, we need to document the manual method in https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md.

**Comment by core-code** [comment]
@vitorgalvao completely unrelated to this issue, but i just wanted to let you know that i am unable to reach you by e-mail. your domain/mailserver seems to refuse connections.

**Comment by vitorgalvao** [comment]
Closed by https://github.com/Homebrew/homebrew-cask/pull/83549.
