### ISSUE TITLE
cask drops files/symlinks when installing app

### ISSUE THREAD

**Issue by jconley** [Homebrew/homebrew-cask#69742]
qgis 3.8.3
macOS 10.14.6

opening QGIS3.8.app errors with "QGIS 3.8 is damaged and can't be opened."

i manually downloaded QGIS3.8 from their website. shasum matches cask cached version.
i ran a diff on the two .app locations, and found all `__pycache__` folders appear to be missing.
also there are 2 `Frameworks` symlinks missing:
```
Contents/Frameworks/Python.framework/Versions/3.7/Frameworks
Contents/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/Frameworks
```
there are other Frameworks symlinks preserved in the app, but the missing ones happen to be `../../..` while the preserved ones looks like `../Frameworks`

as part of build testing, might consider running `spctl` on apps that are signed to catch issues like this.
```
$ spctl -a /Applications/QGIS3.8.app
/Applications/QGIS3.8.app: a sealed resource is missing or invalid
```

also noticed blender cask does some u+w manipulation with the `__pycache__` folder.

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

Please open a new issue and fill the information requested in addition to your findings.
