### ISSUE TITLE
no keyboard support

### ISSUE THREAD

**Issue by unculcated** [Homebrew/homebrew-cask#69756]
Just had a broken mpv, had to uninstall under cask, now keyboard functions don't work.

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

Also, this is not related to HBC. We only move the app, we don’t build it or modify it. You’ll need to ask upstream.

**Comment by unculcated** [comment]
false alarm
