### ISSUE TITLE
mysqlworkbench

### ISSUE THREAD

**Issue by ctrlaltca** [Homebrew/homebrew-cask#69926]
#### General troubleshooting steps

- [y] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [y] I have retried my command with `--force`.
- [y] I ran `brew update-reset && brew update` and retried my command.
- [y] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [y] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [y] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

The formula "mysqlworkbench" installs fine, but the installed application doesn't run anymore on High Sierra; it requires Mojave 10.14.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/69931
