### ISSUE TITLE
Suppress `Error: help does not take arguments.` when `help` is displayed due to invalid syntax

### ISSUE THREAD

**Issue by unitof** [Homebrew/homebrew-cask#69937]
### Description of feature/enhancement

`brew cask` automatically displays usage as returned by `brew cask help` when any invalid syntax is used in a command. However, any invalid command or argument is then passed as an argument to `brew cask help`, resulting in the unhelpful and somewhat misleading `Error: help does not take arguments.` when a developer very unlikely did not intend to run `brew cask help` at all.

### Justification

Syntax errors are common, especially among new users, when using a CLI app such as `brew cask`. Obviously, this is why we fall back to displaying usage when an invalid command is run. But when a user did not explicitly intend to run `brew cask help`, the error message `help does not take arguments` is unlikely to pertain to what they were trying to do, and is misleading. They meant to run another command and made a syntax error—they didn't intend to run `help` with an invalid argument.

Furthermore, were `help` to ever allow an argument in a future version, a user could inadvertently end up passing an argument for an invalid or mistyped command they had intended to run to `help`, leading to even more confusion.

### Example use case

`brew cask search fontstand`
`brew cask --help -g`
`brew cask help help`
`brew cask instlal firefox`

All result in:
```
Homebrew Cask provides a friendly CLI workflow for the administration
of macOS applications distributed as binaries.

Commands:

    --cache    display the file used to cache the Cask
    audit      verifies installability of Casks
    cat        dump raw source of the given Cask to the standard output
    create     creates the given Cask and opens it in an editor
    doctor     checks for configuration issues
    edit       edits the given Cask
    fetch      downloads remote application files to local cache
    home       opens the homepage of the given Cask
    info       displays information about the given Cask
    install    installs the given Cask
    list       with no args, lists installed Casks; given installed Casks, lists staged files
    outdated   list the outdated installed Casks
    reinstall  reinstalls the given Cask
    style      checks Cask style using RuboCop
    uninstall  uninstalls the given Cask
    upgrade    upgrades all outdated casks
    zap        zaps all files associated with the given Cask

See also "man brew-cask"
Error: help does not take arguments.
```

**Comment by unitof** [comment]
Turns out the relevant code here is in the core [`brew`](/homebrew/brew) repo, not this repo.

https://github.com/unitof/brew/blob/5354ba84e679ba376897fa9036b3d2890e98e3aa/Library/Homebrew/cask/cmd.rb#L226

Happy to close and reopen this suggestion over there if requested, or leave it here since it is specific to `cask`. Unsure how to proceed.

**Comment by vitorgalvao** [comment]
> Happy to close and reopen this suggestion over there if requested, or leave it here since it is specific to `cask`.

It’s fine here. Thank you.

**Comment by jpninanjohn** [comment]
I would like to help on this if it is possible.

**Comment by unitof** [comment]
@jpninanjohn Would love your help. I'm diving in the deep end at https://github.com/unitof/brew/commit/a5ec99caa247386773cf640396bd5933629c8a5a. Seems like a good first-timer PR but I've got a lot to figure out (like how to build & run & test it) next.

**Comment by jpninanjohn** [comment]
Sure. I had a look at the code and understood the problem. Will come up with a solution and discuss it here.

**Comment by jpninanjohn** [comment]
While not showing the `help doesn't take arguments`message makes sense, should there be any additional message saying the command was invalid and hence help is being displayed?

**Comment by jpninanjohn** [comment]
@unitof I am raising a PR for this. In addition to suppressing the error message for help arguments, I have added another message to indicate that the brew command failed...
https://github.com/Homebrew/brew/pull/6531
