### ISSUE TITLE
Make Gimp available in command line

### ISSUE THREAD

**Issue by dalboris** [Homebrew/homebrew-cask#69939]
### Description of feature/enhancement

Currently, the cask for Gimp only installs it as a GUI application (moving the app bundle to Applications). It would be nice if gimp was also installed as a command line tool `gimp`. 

### Justification

Gimp comes with powerful scripting capabilities which allow to automate a lot of graphics-related tasks, and being able to call gimp non-interactively from the command line or other scripts is very useful, the same way that you can call python for example.

Having both the GUI app and the command-line app is useful in different scenarios. The GUI app for doing interactive artwork, in which case I launch it from the Dock or Launchpad, and the command-line app to have gimp automatically execute some tasks in the background. There is precedent: the inkscape cask, for I believe the same reason, is installed both as a GUI application and as a command-line tool:

```
==> Installing Cask inkscape
==> Moving App 'Inkscape.app' to '/Applications/Inkscape.app'.
==> Linking Binary 'inkscape' to '/usr/local/bin/inkscape'.
```

### Example use case

I am using gimp (together with inkscape) as part of a script to generate icons in various formats, see [iconify.sh](https://github.com/vgc/vgc-icons/blob/master/iconify.sh). This only works if gimp is installed as a command-line tool.

Note that another user made a request for this previously, see https://github.com/Homebrew/homebrew-cask/issues/39925 . The request was denied due to calling a GUI app from the command-line not being the "Apple way". I agree, and indeed, if I need to launch the Gimp GUI, I prefer to use the icon in the Dock, or use Launchpad. However, in my case, the reason I'd like the command-line gimp isn't to launch the GUI, but to be able to call gimp non-interactively from scripts, as a non-GUI tool. I hope this makes sense.

### Current workaround

1. Create a symbolic link:
```
ln -s /Applications/GIMP-2.10.app/Contents/MacOS/gimp /usr/local/bin/
```

2. Replace the `BASEDIR=...` line in /Applications/GIMP-2.10.app/Contents/MacOS/gimp to the following two lines:
```
GIMP_EXECUTABLE=$(readlink "$0")
BASEDIR=$(cd `dirname $GIMP_EXECUTABLE` && pwd)
```

Note that the second step is irrelevant to Homebrew Cask and should be fixed upstream, but I thought I'd mention it here for completeness. It is due to a bug/limitation of Gimp not supporting being called via a symbolic link apparently. Without step 2, invoking Gimp via the symlink will fail with:

```
/usr/local/bin/gimp: line 43: /usr/local/bin/gimp-bin: No such file or directory
/usr/local/bin/gimp: line 43: exec: /usr/local/bin/gimp-bin: cannot execute: No such file or directory
```

and even if you add `gimp-bin` as a symbolic link too, it would fail with:

```
babl-extension.c:359 void babl_extension_load_dir_list(const char *)()
	WARNING: the babl installation seems broken, no extensions found in queried
BABL_PATH (/usr/local/bin/../Resources/lib/babl-0.1) this means no SIMD/instructions/special case fast paths and
only slow reference conversions are available, applications might still
run but software relying on babl for conversions will be slow

Cannot spawn a message bus without a machine-id: Unable to load /var/lib/dbus/machine-id or /etc/machine-id: Failed to open file ?/var/lib/dbus/machine-id?: No such file or directory
babl-format.c:716 const Babl *babl_format(const char *)()
	const Babl *babl_format(const char *)("CIE Lab double"): not found
sh: gdb: command not found
```

I have reported this issue to Gimp: https://gitlab.gnome.org/GNOME/gimp/issues/4004

**Comment by vitorgalvao** [comment]
> The request was denied due to calling a GUI app from the command-line not being the "Apple way".

I’ll clarify. The rule is that if you’re linking some binary provided by the software, that is accepted *except* if you’re linking the `Contents/MacOS/app_name` binary, *except* (i.e. it’s allowed again) if upstream explicitly recommends that.

Seeing as with Gimp you can do more than just launch the app, that’s fair game for inclusion. Feel free to submit a PR.

> It is due to a bug/limitation of Gimp not supporting being called via a symbolic link apparently.

That’s a common limitation that we allow working around [in a shimscript](https://github.com/Homebrew/homebrew-cask/search?q=shimscript).

**Comment by dalboris** [comment]
Thanks for the clarification, the rule makes sense. I'll have a look at HBC source code and submit a first PR for the symlink, then perhaps a second PR with a shimscript if time allows and if it still makes sense (I feel it should be fixed upstream soon).

**Comment by dalboris** [comment]
Follow up: GIMP doesn't currently support being called via a symlink, and doesn't plan on supporting this in the future. See: https://gitlab.gnome.org/Infrastructure/gimp-macos-build/issues/5.

Therefore, we'll have to modify the recipe and use a shimscript instead of a symlink. I'll work on this and do a PR soon.

**Comment by dalboris** [comment]
Follow up 2: This might in fact be supported by GIMP in the future. The issue has been moved to: https://gitlab.gnome.org/GNOME/gimp/issues/4161

I will add follow up info here as available.
