### ISSUE TITLE
Duplicate results for brew cask search 

### ISSUE THREAD

**Issue by PandaWhisperer** [Homebrew/homebrew-cask#70044]
## Description

Not sure what happened exactly, but on my system, when I do a `brew search` for something, all cask results are shown *twice*. 

This seems mainly cosmetic, as all other functionality appears to work just fine (i.e. there are no conflicts when installing casks), but it does bother me a little bit, and I'm wondering if my installation is somehow corrupted.

## Details

This is the output for `brew tap`:

```
caskroom/cask
caskroom/fonts
heroku/brew
homebrew/cask
homebrew/command-not-found
homebrew/core
homebrew/services
koekeishiya/formulae
raggi/ale
```

**Comment by reitermarkus** [comment]
You have some old taps installed.

```
brew untap caskroom/cask
brew untap caskroom/fonts
```

**Comment by PandaWhisperer** [comment]
Thanks @reitermarkus. Removing `caskroom/casks‘ did get rid of the duplicate results, but I am using some of the fonts from the other repo. Can I keep that, or is there a newer version of that tap available?

**Comment by reitermarkus** [comment]
`brew tap homebrew/cask-fonts`

**Comment by PandaWhisperer** [comment]
Thank you 🙏🏻

**Comment by PandaWhisperer** [comment]
One last question: if I have casks installed from one of the old taps, and I migrate to the new ones, will there be any issues (such as with upgrading casks)? I.E. do I need to re-install my casks from the new tap or will they migrate automatically?
