### ISSUE TITLE
Monero installs successfully, app reports it is damaged

### ISSUE THREAD

**Issue by dzwiener** [Homebrew/homebrew-cask#70092]
I install the cask "monero-wallet" and it installs successfully, but when I go to run the app I get a pop-up that reads: "You can’t open the application “monero-wallet-gui.app” because it may be damaged or incomplete."

**Comment by dzwiener** [comment]
The cask reports it is the right version, and installing directly from the monero site works correctly.

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

You issue has no actionable info. Remove the app and reinstall it with HBC, following the template.
