### ISSUE TITLE
Some casks have compatibility breaks with major versions of macOS

### ISSUE THREAD

**Issue by brucehs** [Homebrew/homebrew-cask#70103]
### Description of feature/enhancement

I propose adding the ability to specify a minor version of macOS (10.XX.YY) to the version comparison to a Cask's `do…end` block.

I was updating BBEdit's cask today and noticed that it had compatibility breaks within major versions of macOS. BBEdit 12.1.6 is not compatible with El Capitan versions prior to 10.11.6; BBEdit 12.6.7 is not compatible with Sierra versions prior to 10.12.6; and BBEdit 13.0 is not compatible with Mojave versions prior to 10.14.2.  

I looked through the [cask synopsis documentation](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/readme.md) and it said: "The corresponding numeric version strings should be given as major releases containing a single dot." Therefore, I assumed it was not possible to assign a minor version to the comparisons.

### Justification

If a user is not on the most current minor revision, brew cask may install an incompatible version of the software.

### Example use case

```
if MacOS.version <= :sierra
  # ...
elsif MacOS.version <= '10.14.2'
  # ...
else
  # ...
end
```

**Comment by vitorgalvao** [comment]
I agree with @reitermarkus. Such fine grained control would seldom be used; it would just be more code in which to have bugs.
