### ISSUE TITLE
Checksum for Cask 'freecad' does not match.

### ISSUE THREAD

**Issue by markwu** [Homebrew/homebrew-cask#70207]
#### General troubleshooting steps

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

I cleanup all caches several times and try fresh install, all I get is checksum error.

```
==> Casks with `auto_updates` or `version :latest` will not be upgraded
==> Upgrading 1 outdated package:
freecad 0.18.3,16131 -> 0.19_pre,18353
==> Upgrading freecad
==> Satisfying dependencies
==> Downloading https://github.com/FreeCAD/FreeCAD/releases/download/0.19_pre/FreeCAD_0.19-18353-OSX-x86_64-conda-Qt5-Py3.dmg
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/5736080/c46b1080-e758-11e9-8616-402be0ba0678?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'freecad'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
==> Purging files for version 0.19_pre,18353 of Cask freecad
Error: Checksum for Cask 'freecad' does not match.
Expected: abf7a7216497b6aa4135ae60038e70234e5e731b9085f4196c63e7e18b2c5af4
  Actual: f730028ead480b43477e62622bfe757b9ae68b42cb7cddec2736a66a110b6a69
    File: /Users/mark/Library/Caches/Homebrew/downloads/ffd06616f8227737b961a38c1add481c005f9fd0f801cbe0521bd1b6bb30a5ac--FreeCAD_0.19-18353-OSX-x86_64-conda-Qt5-Py3.dmg
To retry an incomplete download, remove the file above.
If the issue persists, visit:
  https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md
```

**Comment by MindTooth** [comment]
Not sure why someone would push an update to a pre-release.  Better off waiting for an maintainer to maybe revert the change, or push an updated checksum.

**Comment by markwu** [comment]
Yes, I revert my local formula to stay with version `0.18.3,16131` to solve the issue.

**Comment by vitorgalvao** [comment]
> Not sure why someone would push an update to a pre-release.

https://github.com/Homebrew/homebrew-cask/pull/70078#issue-324063480:

> The current version (0.18.3,16131) won't download because they have pulled the macOS release of 0.18.3. The [0.18.3 release page](https://github.com/FreeCAD/FreeCAD/releases/0.18.3) says:
> 
> > NOTE: For OSX it is recommended to use the 0.19_dev builds. https://github.com/FreeCAD/FreeCAD/releases/tag/0.19_pre
> > FreeCAD 0.19.x has been ported to QT5.9 and QTWebEngine which solves some OSX specific issues.

**Comment by MindTooth** [comment]
> > Not sure why someone would push an update to a pre-release.
> 
> [#70078 (comment)](https://github.com/Homebrew/homebrew-cask/pull/70078#issue-324063480):
> 
> > The current version (0.18.3,16131) won't download because they have pulled the macOS release of 0.18.3. The [0.18.3 release page](https://github.com/FreeCAD/FreeCAD/releases/0.18.3) says:
> > > NOTE: For OSX it is recommended to use the 0.19_dev builds. https://github.com/FreeCAD/FreeCAD/releases/tag/0.19_pre
> > > FreeCAD 0.19.x has been ported to QT5.9 and QTWebEngine which solves some OSX specific issues.

Thanks for taking the time to give reference to why.  Should of course have checked for myself.

**Comment by markwu** [comment]
Hi @vitorgalvao 

I saw you closed the issue, but the sha256 still wrong for the image. According to the [sha256.txt](https://github.com/FreeCAD/FreeCAD/releases/download/0.19_pre/FreeCAD_0.19-18353-OSX-x86_64-conda-Qt5-Py3.dmg-SHA256.txt), it should be

`5799f74435ebb0faa334850539b5b280b66c09abb6ea4af11f4a3f0a4af22f76`

I download about 20 times, finally I got the correct one this morning in my timezone.

**Comment by markwu** [comment]
And `5799f74435ebb0faa334850539b5b280b66c09abb6ea4af11f4a3f0a4af22f76` is the correct sha256 checksum.

**Comment by vitorgalvao** [comment]
> I saw you closed the issue, but the sha256 still wrong for the image.

But the fix [was already prepared](https://github.com/Homebrew/homebrew-cask/pull/70215).
