### ISSUE TITLE
“calibre.app” is damaged and can’t be opened. You should move it to the Bin.

### ISSUE THREAD

**Issue by tomtastic** [Homebrew/homebrew-cask#70320]
#### General troubleshooting steps

As per https://github.com/Homebrew/homebrew-cask/issues/57153

#### Description of issue

As per https://github.com/Homebrew/homebrew-cask/issues/57153

#### Possible solution

Rather than disabling and reenabling Gatekeeper, just install and then clear the attributes `$ xattr -cr /Applications/calibre.app` before you open the app.

Could the cask do this automatically post install?

Not sure why Calibre in particular is affected here?

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Please don’t ignore the template, and search before posting. This is a repeat of https://github.com/Homebrew/homebrew-cask/issues/70154, which itself got another duplicate today.

Removing the quarantining attribute in the cask would be nonsensical — we’re the ones who added it. You can always install **at your own risk** with `--no-quarantine`.
