### ISSUE TITLE
Removing the “is app open” check from CI

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-cask#70521]
Refs https://github.com/Homebrew/homebrew-cask/pull/70140; https://github.com/Homebrew/homebrew-cask-drivers/pull/1243

Both of those checks failed with:

> Warning: Skipping quitting application ID 'com.iPass.iPass'. Enable Automation Access for “Terminal > System Events” in “System Preferences > Security > Privacy > Automation”.

Which a few lines down translates to:

> Error: Some applications are still running, add them to uninstall quit:
> com.iPass.iPass

or

> Error: Some applications are still running, add them to uninstall quit:
> com.elgato.Elgato-Thunderbolt-Dock-Utility

This might become a problem. If we can no longer automate closing an app, checking if an app is still running is useless and will always result in a failure.

**Comment by core-code** [comment]
an easy fix would be to modify homebrew-cask/cmd/lib/check.rb  to not produce the 'add them to uninstall quit' failure if it actually already is in the "uninstall quit" list

**Comment by vitorgalvao** [comment]
> not produce the 'add them to uninstall quit' failure if it actually already is in the "uninstall quit" list

That warning might mean it requires [`signal:`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md#summary-of-keys) instead.

My suggestion would be to either find a way to disable the macOS protections in the CI or make the CI skip every AppleScript-dependent action, covering other bases as well.

**Comment by core-code** [comment]
> My suggestion would be to either find a way to disable the macOS protections in the CI or 
> make the CI skip every AppleScript-dependent action, covering other bases as well.

certainly sounds like the proper solution. 


if the CI has SIP disabled, this might be an option:
https://github.com/jacobsalmela/tccutil
https://github.com/univ-of-utah-marriott-library-apple/privacy_services_manager

**Comment by core-code** [comment]
i can also confirm that the TCC database is still writable on Mojave - if SIP is disabled:

sudo sqlite3 /Library/Application\ Support/com.apple.TCC/TCC.db "INSERT INTO access VALUES('kTCCServiceAccessibility','com.apple.Terminal',0,1,1,NULL);"

**Comment by core-code** [comment]
is this closed by https://github.com/Homebrew/homebrew-cask/pull/89490

**Comment by vitorgalvao** [comment]
> is this closed by #89490

[Looks like it!](https://github.com/Homebrew/homebrew-cask/pull/89490/files#diff-e68ab8af5672d210206662eaa4650d47R130)
