### ISSUE TITLE
xld cannot be installed on Catalina

### ISSUE THREAD

**Issue by vol24pl** [Homebrew/homebrew-cask#70816]
I cannot install xld on Catalina. Here's my terminal output:

```
» brew cask install xld
==> Satisfying dependencies
==> Downloading https://downloads.sourceforge.net/xld/xld-20191004.dmg
Already downloaded: /Users/JohnDoe/Library/Caches/Homebrew/downloads/f7d4326642fd88def2f3f82c5f41702944e05290ecc7b3159d283f570bc4420b--xld-20191004.dmg
==> Verifying SHA-256 checksum for Cask 'xld'.
==> Installing Cask xld
==> Purging files for version 2019.10.04 of Cask xld
Error: Failed to quarantine one or more files within /usr/local/Caskroom/xld/2019.10.04. Here's the reason:
xattr: No such file: /usr/local/Caskroom/xld/2019.10.04/XLD.app/Contents/PlugIns/XLDSparkleUpdater.bundle/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/fr.lproj/fr.lproj
```

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
