### ISSUE TITLE
tor-browser cannot be installed

### ISSUE THREAD

**Issue by vol24pl** [Homebrew/homebrew-cask#70815]
I cannot install tor-browser via cask on Catalina, this is my terminal output

```
brew cask install tor-browser                      1 ↵
==> Satisfying dependencies
==> Downloading https://dist.torproject.org/torbrowser/8.5.5/TorBrowser-8.5.5-os
Already downloaded: /Users/JohnDoe/Library/Caches/Homebrew/downloads/3bde0998ce070cdd5eabcbdec9774f9b2208c2eecea7f96816d9e4975356879d--TorBrowser-8.5.5-osx64_en-US.dmg
==> Verifying SHA-256 checksum for Cask 'tor-browser'.
==> Installing Cask tor-browser
==> Purging files for version 8.5.5 of Cask tor-browser
Error: It seems the App source '/usr/local/Caskroom/tor-browser/8.5.5/Tor Browser.app' is not there
```

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
