### ISSUE TITLE
Update paste 2.5 please.

### ISSUE THREAD

**Issue by zxdposter** [Homebrew/homebrew-cask#71014]
@ran-dall

**Comment by NealSr** [comment]
It looks like Paste 2.5 got released - is it as simple as updating the sha256?

**Comment by vitorgalvao** [comment]
Bumping an app is an easy procedure, please [do give it a try](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

And please don’t open one-word issues, especially @mentioning a user. It puts undue burden on the person who is volunteering their time.

Finally, it would be appreciated if you followed our carefully laid out instructions, including the fact we don’t accept requests for casks or bumps. PRs are the way to go, and we have extensive documentation on every step, but most bumps are literally a single command away.

**Comment by philltran** [comment]
Looks like the download link has not been updated in their sparklecast feed for 2.5.0. Is there another place to get the download link? The link on the [app's website ](https://pasteapp.me/mac/download)includes a token so it won't work for this purpose.

**Comment by philltran** [comment]
PR submitted. #71862
