### ISSUE TITLE
brew cask does not work

### ISSUE THREAD

**Issue by ModdedGamers** [Homebrew/homebrew-cask#71595]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

when I run 
```
brew cask(any cask command)
```
it fails

#### Command that failed

```
brew cask install
brew cask update
brew cask outdated
etc.
(Any cask-related command)
```

#### Output of command with `--force --verbose --debug`

```
Error: Unknown Cask command: export
/Users/993390/homebrew/Library/Homebrew/cask/cmd.rb:229:in `run'
/Users/993390/homebrew/Library/Homebrew/cask/cmd.rb:119:in `run_command'
/Users/993390/homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/Users/993390/homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/Users/993390/homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/Users/993390/homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/Users/993390/homebrew/Library/Homebrew/cask/cmd.rb:162:in `exit'
/Users/993390/homebrew/Library/Homebrew/cask/cmd.rb:162:in `rescue in run'
/Users/993390/homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/Users/993390/homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/Users/993390/homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/Users/993390/homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew cask doctor`

```
Error: Unknown Cask command: export
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/core
```

**Comment by reitermarkus** [comment]
Try `brew update-reset`.

**Comment by ModdedGamers** [comment]
I have done that, as well as reinstalling brew.

**Comment by ModdedGamers** [comment]
Output from  ```brew update-reset```:
```
==> Fetching /Users/993390/homebrew...

==> Resetting /Users/993390/homebrew...
Branch 'master' set up to track remote branch 'master' from 'origin'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.

==> Fetching /Users/993390/homebrew/Library/Taps/homebrew/homebrew-cask...

==> Resetting /Users/993390/homebrew/Library/Taps/homebrew/homebrew-cask...
Branch 'master' set up to track remote branch 'master' from 'origin'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.

==> Fetching /Users/993390/homebrew/Library/Taps/homebrew/homebrew-core...

==> Resetting /Users/993390/homebrew/Library/Taps/homebrew/homebrew-core...
Branch 'master' set up to track remote branch 'master' from 'origin'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.
```

**Comment by reitermarkus** [comment]
Please post the output of `brew doctor` and `brew config`.

**Comment by ModdedGamers** [comment]
Brew Doctor:
```
993390s-MacBook-Air:~ 993390$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /usr/local/bin/python3.7-config
  /usr/local/bin/python3.7m-config
  /usr/local/bin/python3-config

Warning: Your Homebrew's prefix is not /usr/local.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/usr/local).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this unsupported configuration.
```
Brew Config:
```
993390s-MacBook-Air:~ 993390$ brew config
HOMEBREW_VERSION: 2.1.15-67-g2963bbe
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2963bbec91aa0fdde145d7bf788da54c0bf792f4
Last commit: 10 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 649e46d1f314c757ec387da71ce4d240c7d1a0c4
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /Users/993390/homebrew
HOMEBREW_CELLAR: /Users/993390/homebrew/Cellar
HOMEBREW_REPOSITORY: /Users/993390/homebrew
HOMEBREW_CASK_OPTS: --appdir=~/Applications
export LDFLAGS=-L/Users/993390/homebrew/opt/icu4c/lib
export CPPFLAGS=-I/Users/993390/homebrew/opt/icu4c/include
export PKG_CONFIG_PATH=/Users/993390/homebrew/opt/icu4c/lib/pkgconfig
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.6.3 => /Users/993390/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1001
Git: 2.23.0 => /Users/993390/homebrew/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_171
macOS: 10.14.3-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A
CLT headers: 10.3.0.0.1.1562985497
```

**Comment by ModdedGamers** [comment]
What I found is that if I tab homebrew-cask-versions, cask commands work as intended. I will assume this is not intended behavior.

**Comment by ModdedGamers** [comment]
We should probably document that if using the standard homebrew/cask tap does not work, they should ``` brew tap homebrew/homebrew-cask-versions``` and then run ```brew upgrade``` to make sure that everything is up to date.

**Comment by vitorgalvao** [comment]
> What I found is that if I tab homebrew-cask-versions, cask commands work as intended. I will assume this is not intended behavior.

It’s not

> We should probably document that if using the standard homebrew/cask tap does not work

That is not the case. You’re the only one having this issue, I don’t remember it happening before.

**Comment by vitorgalvao** [comment]
> Warning: Your Homebrew's prefix is not /usr/local.

That’s what jumps out at me. That’s unusual, so the cause of the bug may lie there.

**Comment by ModdedGamers** [comment]
@vitorgalvao I fell that we should document this as an edge case just in case this happens to anyone else. Also, @reitermarkus, I feel that this is not coming from Bash or Ruby as it got fixed once I tapped homebrew/brew-cask-versions. My prefix is not /usr/local as my mac install was setup in a way that I can't write to usr/local, so that's why the prefix is not /usr/local. I wish I could install there, but that's the only thing I can't fix in brew.

**Comment by vitorgalvao** [comment]
> I fell that we should document this as an edge case just in case this happens to anyone else.

This is not an edge case, it’s a bug, and one that happens to a single person so far. Documenting it makes no sense because we don’t know the cause. We don’t even know if the problem in on our side or on your setup.

**Comment by ModdedGamers** [comment]
Alright. I have checked everything that I need to(I think). If there is any other command that I should run to check for problems, I don't know it. Thanks for your help!
