### ISSUE TITLE
unload filesystem 

### ISSUE THREAD

**Issue by hubowestlife** [Homebrew/homebrew-cask#71676]
`─$ brew cask  install tencent-lemon
==> Satisfying dependencies
==> Downloading https://pm.myapp.com/invc/xfspeed/qqpcmgr/module_update/Lemon_3.0.0.dmg
Already downloaded: /Users/brian/Library/Caches/Homebrew/downloads/250ca285e30068adfabb0bd338bcda8853c16ba47f92972c8197dbbd7cba265a--Lemon_3.0.0.dmg
==> Verifying SHA-256 checksum for Cask 'tencent-lemon'.
==> Installing Cask tencent-lemon
hdiutil: attach: WARNING: ignoring IDME options (obsolete)
hdiutil: attach failed - 无可装载的文件系统
==> Purging files for version 3.0.0 of Cask tencent-lemon
Error: Failure while executing; `hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/8d/9g_lbbx10cg4x3r0qgqmcbrm0000gn/T/d20191030-92841-z8ufwi /var/folders/8d/9g_lbbx10cg4x3r0qgqmcbrm0000gn/T/d20191030-92841-z8ufwi/250ca285e30068adfabb0bd338bcda8853c16ba47f92972c8197dbbd7cba265a--Lemon_3.0.0.cdr` exited with 1. Here's the output:
hdiutil: attach: WARNING: ignoring IDME options (obsolete)
hdiutil: attach failed - 无可装载的文件系统

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:19:in `system_command!'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:156:in `block in mount'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:126:in `mount'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/dmg.rb:116:in `extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:123:in `extract'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:130:in `block in extract_nestedly'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:127:in `extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:187:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:77:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:99:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'`

**MacOS version is 10.15 Catalina**
**Does anyone meet such error message like me ? besides I also run the command 'sudo spctl --master-disable' before I install the software.**

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
