### ISSUE TITLE
Adding a tag "delta_updates"

### ISSUE THREAD

**Issue by legendtang** [Homebrew/homebrew-cask#71775]
### Description of feature/enhancement

In addition to tag auto_updates, it is necessary to add a new tag "delta_updates" to inform the user if the software itself has a feature to do an incremental update, instead of downloading the complete software again to update.
![image](https://user-images.githubusercontent.com/1352729/67933692-4be55b80-fc01-11e9-8d33-7ce050f6bdb5.png)

### Justification

Many software provides such a feature to update themselves incrementally, while cask do not support incremental update. The user may prefer delta updates rather than full-update from casks

### Example use case

A user makes a decision whether to let the software to be managed by casks.

**Comment by vitorgalvao** [comment]
A cask that has `auto_updates` will not be updated by HBC by default, that’s the point. `delta_updates` would be redundant and a whole lot of work for no gain.
