### ISSUE TITLE
Fixing XAMPP

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-cask#71798]
[The `xampp` cask](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/xampp.rb) is at version `7.3.4-0` and uses an installer at `XAMPP.app/Contents/MacOS/osx-intel`. It seems to [only be compatible with pre-Catalina macOS](https://github.com/Homebrew/homebrew-cask/issues/71791).

On [the website](https://www.apachefriends.org/index.html), the latest version is `7.3.11` and the previous installation script does not exist: inside `XAMPP.app/Contents/MacOS` we find `stackman` and `stackman_launcher`.

I can’t work on the cask now because I’m without a VM, but documenting these findings to whoever wishes to update it.

**Comment by rockihack** [comment]
I edited the installer script executable from `XAMPP.app/Contents/MacOS/osx-intel` (32bit) to `XAMPP.app/Contents/MacOS/osx-x86_64` (64bit) and bumped the version.
That fixed the "osx-intel: Bad CPU type in executable" error on macOS Catalina.

```
cask 'xampp' do
  version '7.3.11-0'
  sha256 'cf6a2ddedd64955080e09a6279cbda78569a21ba8d017bd035f73a47b8f9da5b'

  # downloadsapachefriends.global.ssl.fastly.net/xampp-files was verified as official when first introduced to the cask
  url "https://downloadsapachefriends.global.ssl.fastly.net/xampp-files/#{version.major_minor_patch}/xampp-osx-#{version}-installer.dmg"
  name 'XAMPP'
  homepage 'https://www.apachefriends.org/index.html'

  installer script: {
                      executable: 'XAMPP.app/Contents/MacOS/osx-x86_64',
                      args:       ['--mode', 'unattended'],
                      sudo:       true,
                    }   

  uninstall quit:   'com.bitnami.manager',
            script: {
                      executable: '/Applications/XAMPP/uninstall.app/Contents/MacOS/osx-x86_64',
                      args:       ['--mode', 'unattended'],
                      sudo:       true,
                    },  
            delete: '/Applications/XAMPP/'
end
```

**Comment by vitorgalvao** [comment]
@rockihack If you have a working solution (or the first steps to one), please submit a PR.

**Comment by rockihack** [comment]
Done. https://github.com/Homebrew/homebrew-cask/pull/72717
