### ISSUE TITLE
JavaScript Lint (jsl) binary doesn't work on Catalina

### ISSUE THREAD

**Issue by marcorocca** [Homebrew/homebrew-cask#71999]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Cask file for JavaScript Lint (jsl) downloads the binary version of the tools which doesn't run on Catalina (64bit only system):

`-bash: /usr/local/bin/jsl: Bad CPU type in executable`

Compiling it from sources gives a working executable but needs a simple patch on jsprf.c file:

```
 #ifdef HAVE_VA_COPY
 #define VARARGS_ASSIGN(foo, bar)        VA_COPY(foo,bar)
+#elif defined(va_copy)
+#define VARARGS_ASSIGN(foo, bar)        va_copy(foo,bar)
 #elif defined(HAVE_VA_LIST_AS_ARRAY)
 #define VARARGS_ASSIGN(foo, bar)        foo[0] = bar[0]
 #else
 #define VARARGS_ASSIGN(foo, bar)        (foo) = (bar)
 #endif
```

I think using sources instead of binary version will completely solve problems.

#### Command that failed

```
$ jsl
-bash: /usr/local/bin/jsl: Bad CPU type in executable
```

**Comment by reitermarkus** [comment]
If it can be built from source it should be a Formula.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/72482
