### ISSUE TITLE
Cask: When is it unsafe to let an app update itself?

### ISSUE THREAD

**Issue by callumlocke** [Homebrew/homebrew-cask#72068]
From [USAGE.md](https://github.com/Homebrew/homebrew-cask/blob/master/USAGE.md#updatingupgrading-casks):

> It is generally safe to run updates from within an application.

Why only generally? When is it _not_ safe to allow an application to update itself, and what might go wrong?

**Comment by vitorgalvao** [comment]
That sentence was added six years ago and doesn’t make much sense. Removing in https://github.com/Homebrew/homebrew-cask/pull/72166.

Thank you for the report.
