### ISSUE TITLE
have a better formatted list of brew casks

### ISSUE THREAD

**Issue by commjoen** [Homebrew/homebrew-cask#72070]
### Description of feature/enhancement

currently the list of to be upgraded casks after "brew cask upgrade" is a bit odd on the screen, a newline after each item would make it easier to read. It means adding` \n` to https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/cmd/upgrade.rb#L44

### Justification

The new formatting should make it easier to see which casks (and how many) are upgraded.

### Example use case

`brew cask upgrade`

**Comment by vitorgalvao** [comment]
Please submit a PR instead, so we can discuss it further.
