### ISSUE TITLE
Homepage and download link change of cask `eudic`

### ISSUE THREAD

**Issue by singularitti** [Homebrew/homebrew-cask#72151]
The current homepage of cask `eudic` is https://www.eudic.net/eudic/mac_dictionary.aspx, which looks like below:
![current](https://user-images.githubusercontent.com/25192197/68272981-3cb44280-0033-11ea-833b-85a33e4e58d9.png)
By clicking the big picture in the middle we go to its download link (http://static.frdic.com/pkg/eudicmac.dmg).
However, if we click the Windows logo at the left corner, we will be redirected to a [newer homepage](https://www.eudic.net/v4/en/app/eudic) of this software. And by clicking the blue button (with "立即下载" on it) we will be redirected to its [download page](https://www.eudic.net/v4/en/app/download).
Here we can download the app by clicking the blue button with Apple logo. The download link will be https://static.frdic.com/pkg/eudicmac.dmg?v=2019-10-06. As you can see, it has a timestamp in the link. I think it is clearer than the old one (http://static.frdic.com/pkg/eudicmac.dmg).
I think https://www.eudic.net/v4/en/app/eudic itself is worthwhile for a new homepage. Considering the homepage of `frhelper`, a similar French dictionary software developed by the same company (`eudic` is an English dictionary), already has the homepage of https://www.eudic.net/v4/fr/app/frhelper.
I can make a PR if you agree.

**Comment by vitorgalvao** [comment]
Seems acceptable, please proceed with the PR.

For future reference, it’s best to open the PR outright and explain the changes there. If we can see the changes, it’s easier to understand if it should be merged or not.
