### ISSUE TITLE
SHA-256 image2icon error

### ISSUE THREAD

**Issue by gamafreire** [Homebrew/homebrew-cask#72177]
#### General troubleshooting steps
- [ x] I have retried my command with `--force`.
- [x ] I ran `brew update-reset && brew update` and retried my command.
- [ x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ x ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.
#### Description of issue

brew cask install image2icon  SHA-256 error

#### Command that failed

```
brew cask install image2icon
==> Downloading https://sf-applications.s3.amazonaws.com/Image2Icon/app-releases
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'image2icon'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'image2icon' does not match.
Expected: aee9bc34a4d382083041f005d0c3f42a74f6a87bfda2815eb3b48d2bcd647154
  Actual: dab045d388910dfafacd71d708285e1fea6614c9f4f2f34c99d1f7439ce94439
    File: /Users/flip/Library/Caches/Homebrew/downloads/ac67fb5d7191e0831869015be7dddb62018c654899d425aeaf3af163156f0652--Image2icon2.10.zip
```

**Comment by vitorgalvao** [comment]
> * [ x ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

That’s what that is, as reported by the error message you posted. Now that you can recognise it, please take it into account for next time.

In the future, please fill the whole template.

Fixed by https://github.com/Homebrew/homebrew-cask/pull/72261.
