### ISSUE TITLE
Check macos version before download

### ISSUE THREAD

**Issue by brandonkal** [Homebrew/homebrew-cask#72474]
### Description of feature/enhancement

Having an app download and then not be installed because of a depends_on clause that specifies a different OS version is not the best experience. Ideally, Homebrew should validate the OS version requirements first before attempting to download a cask.

### Justification

See above

### Example use case

See the calibre cask. The dmg is downloaded on my slow connection and then home-brew reports that mojave is required. The experience could be worse for larger applications.

**Comment by grantfar** [comment]
I will take this

**Comment by vitorgalvao** [comment]
Thank you, @grantfar. We’ll be awaiting the PR. If you have any specific questions, let us know.

**Comment by Akylzhan** [comment]
@vitorgalvao I was thinking about this problem a bit
What if we will change the order in [installer.rb](https://github.com/Homebrew/brew/blob/0e9fe732d7edd5bff485694cc79d13d2420f95c6/Library/Homebrew/cask/installer.rb#L68) to this:
```
satisfy_dependencies
verify_has_sha if require_sha? && !force?
download
verify
```

**Comment by vitorgalvao** [comment]
It probably should be above just above `download`, but yes, that seems like it might work.
