### ISSUE TITLE
Versioning dotnet Casks

### ISSUE THREAD

**Issue by lajoie** [Homebrew/homebrew-cask#72553]
### Description of feature/enhancement

Provide separate dotnet[-sdk] brews for the major version releases of .Net Core.

### Justification

.Net Core recently released its 3.x series.  There are some fairly dramatic (not fully backwards compatible) changes in this release.  Their release roadmap will have that continuing in the foreseeable future with major releases.  It would be really nice if we could have brews that used the "@<major version>" syntax used by other brews.

### Example use case

So, for example:

dotnet@2, dotnet-sdk@2
dotnet@3, dotnet-sdk@3

**Comment by vitorgalvao** [comment]
1. We don’t do `@` versioning in casks.
2. Separate versions belong in [homebrew/cask-versions](https://github.com/Homebrew/homebrew-cask-versions) and [follow strict requirements](https://github.com/Homebrew/homebrew-cask-versions#acceptable-casks).
3. [We don’t accept cask requests](https://github.com/Homebrew/homebrew-cask/issues/new?template=03_cask_request.md), only PRs.
