### ISSUE TITLE
expressVPN website incorrect

### ISSUE THREAD

**Issue by RZXQ** [Homebrew/homebrew-cask#72718]
the `expressvpn` points to a **fake** website : `www.expressvpn.xyz` instead of `https://www.expressvpn.com`

just want to let you know that , thanks

just run `brew info expressvpn`, you can tell the difference, Thank you 

```
expressvpn: 7.5.3.7428 (auto_updates)
https://www.expressvpn.xyz/vpn-software/vpn-mac/
Not installed
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/expressvpn.rb
==> Name
ExpressVPN
==> Artifacts
expressvpn-install_v7.5.3.7428.pkg (Pkg)
```

**Comment by reitermarkus** [comment]
Have you confirmed that it is indeed a fake website and not just a second domain pointing to the same site?

**Comment by vitorgalvao** [comment]
Not fake. The download page on the `.com` (https://www.expressvpn.com/vpn-software/vpn-mac) links to the `.xyz` download.
