### ISSUE TITLE
PowerShell cask install is broken due to openssl issue

### ISSUE THREAD

**Issue by WickedPorter** [Homebrew/homebrew-cask#73016]
Attempting to install PowerShell today via brew cask install powershell ... apparently it relies on a deprecated openssl(?)

==> Downloading https://github.com/PowerShell/PowerShell/releases/download/v6.2.3/powershell-6.2.3-osx-x64.pkg
Already downloaded: /Users/nickc/Library/Caches/Homebrew/downloads/8f038fec01ae8495ce2126bd25251e4a4aa8a4a2a504de07b51cf1faefc29840--powershell-6.2.3-osx-x64.pkg
==> Verifying SHA-256 checksum for Cask 'powershell'.
**Error: No available formula with the name "openssl"**

**Comment by reitermarkus** [comment]
Should be fixed by https://github.com/Homebrew/homebrew-core/pull/47034.
