### ISSUE TITLE
Add more verbose logging when installing pkg

### ISSUE THREAD

**Issue by gdams** [Homebrew/homebrew-cask#73147]
### Description of feature/enhancement

I've had a [request](https://github.com/AdoptOpenJDK/homebrew-openjdk/issues/176#issuecomment-557552883) in the AdoptOpenJDK homebrew tap to log the install location at the end of brew installs. Currently this is the only information I see after an install:

```bash
==> Package installers may write to any location; options such as --appdir are ignored.
installer: Package name is AdoptOpenJDK
installer: Upgrading at base path /
installer: The upgrade was successful.
```

I played around with adding a postflight block like this but couldn't get it to actually appear (I assume that the stdout gets redirected somewhere?)

```ruby
  postflight do
    system_command '/usr/sbin/pkgutil', args: ['--pkg-info', 'net.adoptopenjdk.8.jdk']
  end
```

In the ideal world we could just pull the location like this and add it by default as it seems like a useful feature:

```bash
➜  pkgutil --pkg-info net.adoptopenjdk.8.jdk
package-id: net.adoptopenjdk.8.jdk
version: 1.8.0_232-b09
volume: /
location: Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk
install-time: 1574678870
```

**Comment by vitorgalvao** [comment]
There’s not enough demand for this, and doing it for just one casks doesn’t make much sense. But I don’t see any harm in it—if you want to submit a PR to the core to add the information for all pkgs, I wouldn’t oppose it.
