### ISSUE TITLE
android-platform-tools hash is always wrong for me

### ISSUE THREAD

**Issue by robmonte** [Homebrew/homebrew-cask#73189]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

The android-platform-tools cask *always* tells me the checksum is wrong. This has happened for me across many versions, not just the current. I don't believe it is just a matter of the file being outdated which is why I am opening this issue rather than simply updating the hash.

#### Command that failed

```
brew cask upgrade

Error: Checksum for Cask 'android-platform-tools' does not match.
Expected: f4a671ab24845f26cb4b579079e2cc3a58c9931e07ae2fca1c83ffebdf773cc1
  Actual: 48b15598d61587535a9be277134d47aeac8e1eb402ec9dbb940403483a0114da
```

When I download the file manually via curl OR from a web browser, I get the below checksum:
```
curl -O "https://dl.google.com/android/repository/platform-tools_r29.0.5-darwin.zip"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 7936k    0 7936k    0     0  2213k      0 --:--:--  0:00:03 --:--:-- 2213k

shasum -a 256 platform-tools_r29.0.5-darwin.zip
48b15598d61587535a9be277134d47aeac8e1eb402ec9dbb940403483a0114da  platform-tools_r29.0.5-darwin.zip
```

**Comment by vitorgalvao** [comment]
Can’t reproduce. Issue is likely to be on your end. Check if you have a `~/.curlrc`, as that’s the most common source of these kinds of issues.

**Comment by robmonte** [comment]
@vitorgalvao I do not have a .curlrc file. Plus that wouldn't affect the file when I download it via chrome or firefox. All 3 methods of downloading give me the checksum starting with 48b. Any other ideas?

**Comment by vitorgalvao** [comment]
> Any other ideas?

It may be that the CDN that serves your location has a different file. We’ve seen that happen before. That would have to be fixed upstream.

**Comment by robmonte** [comment]
Interesting if that may be the CDN causing it. Seems like a likely scenario if you've seen it happen before then. It was driving me crazy that the checksums _never_ match for me and I couldn't figure out why. I'm happy to accept that as the cause and have to manually deal with adb myself. Thanks for the info!

**Comment by vitorgalvao** [comment]
> Seems like a likely scenario if you've seen it happen before then.

To clarify, I’ve seen it happen with other casks (Visual Studio Code, if I recall correctly). In those cases, someone contacted them and it was fixed.
