### ISSUE TITLE
Separate appcast check from CI audit

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-cask#73192]
The most common error in `audit` seems to be when an `appcast` doesn’t match with `version`, but often they are false negatives. We already separate Github actions into `style` and `audit` checks, so it would be convenient if we separated `audit --appcast` from the rest as well.

**Comment by andyli** [comment]
+1

It would be great to have the flash-family with the appcast check opted out too. The Flash Player appcast is often outdated when a new release is out. See https://github.com/Homebrew/homebrew-cask/pull/73950#issuecomment-563920561.

**Comment by vitorgalvao** [comment]
> It would be great to have the flash-family with the appcast check opted out too.

The suggestion would work for every cask, no need to opt-out any of them on an individual basis.

**Comment by andyli** [comment]
The flash appcast is really problematic and it delays nearly every PR I made for the flash casks. It happened again now: https://github.com/Homebrew/homebrew-cask/pull/84023

**Comment by vitorgalvao** [comment]
> It happened again now: #84023

That error is unrelated.

**Comment by andyli** [comment]
> > It happened again now: #84023
> 
> That error is unrelated.

I was referring to https://github.com/Homebrew/homebrew-cask/pull/84023#issuecomment-641242891

**Comment by vitorgalvao** [comment]
> I was referring to [#84023 (comment)](https://github.com/Homebrew/homebrew-cask/pull/84023#issuecomment-641242891)

Yes, and that error is unrelated. It’s not even being able to read the appcast, while the issue the other times is that it reads it but has an older version.

**Comment by reitermarkus** [comment]
This can be dealt with using the `ci-skip-appcast` label now.
