### ISSUE TITLE
Cask 'kdiff3' is unavailable: No Cask with this name exists

### ISSUE THREAD

**Issue by dschinkel** [Homebrew/homebrew-cask#73271]
When I run brew cask install kdiff3 I get `Cask 'kdiff3' is unavailable: No Cask with this name exists`

Not sure how to resolve this.

**Comment by vitorgalvao** [comment]
I don’t understand what it is you don’t understand. There’s no such cask in the official repos, so you can’t install it from us.

The cask has been removed in https://github.com/Homebrew/homebrew-cask/pull/67726.
