### ISSUE TITLE
Runway ML overtook runway.rb

### ISSUE THREAD

**Issue by Hologos** [Homebrew/homebrew-cask#73400]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Runway ML overtook runway.rb and running `brew cask upgrade` deleted my app and replaced with a completely different app. It's caused with this PR #68156. How can it be?

**Comment by ran-dall** [comment]
From https://github.com/Homebrew/homebrew-cask/pull/68156#discussion_r317839839
> The other runway is unpopular enough that it can be renamed instead, this one becoming runway.
> 
> runway (added 123 days ago)
> 30 days: 6 (#3079)
> 90 days: 8 (#3994)
> 365 days: 13 (#5022)

From https://github.com/Homebrew/homebrew-cask/pull/68156#discussion_r317849226
> Shall I rename the other one to celestialteapot-runway?
> 
> Yes.

**Comment by vitorgalvao** [comment]
Apologies for the unexpected event. We’d like to have a better way to handle renames, but at the moment we don’t (PRs welcome to implement the equivalent of `formula_renames` into casks).
