### ISSUE TITLE
Error: Cask adoptopenjdk8 exists in multiple taps. So how to use specific tap in Brewfile?

### ISSUE THREAD

**Issue by kenorb** [Homebrew/homebrew-cask#73730]
#### General troubleshooting steps

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

I'm trying to install Java 1.8 using `Brewfile`, but due to be present in multiple taps, it doesn't work.

Related: AdoptOpenJDK/homebrew-openjdk/issues/106

Ideally I want to specify which tap I mean, but then I've got the warning:

> Warning: treating 'adoptopenjdk/openjdk/adoptopenjdk8' cask as 'adoptopenjdk8'!

#### Command that failed

```
brew bundle
```

With the following `Brewfile`:

```
# Install Java 1.8
tap 'AdoptOpenJDK/openjdk'
cask 'adoptopenjdk/openjdk/adoptopenjdk8'
```

#### Output of command with `--force --verbose --debug`

```
$  brew bundle --force --verbose --debug
Warning: treating 'adoptopenjdk/openjdk/adoptopenjdk8' cask as 'adoptopenjdk8'!
Please change `cask "adoptopenjdk/openjdk/adoptopenjdk8"` to `cask "adoptopenjdk8"` in your `Brewfile`.
Skipping install of adoptopenjdk/openjdk tap. It is already installed.
Using adoptopenjdk/openjdk
Using adoptopenjdk8
Homebrew Bundle complete! 2 Brewfile dependencies now installed.
/usr/local/Homebrew/Library/Homebrew/brew.rb:109:in `exit'
/usr/local/Homebrew/Library/Homebrew/brew.rb:109:in `<main>'
```

If I rename `cask 'adoptopenjdk/openjdk/adoptopenjdk8'` to `cask 'adoptopenjdk8'`, I've got:

```
$  brew bundle --force --verbose --debug
Skipping install of adoptopenjdk/openjdk tap. It is already installed.
Using adoptopenjdk/openjdk
Using adoptopenjdk8
Homebrew Bundle complete! 2 Brewfile dependencies now installed.
/usr/local/Homebrew/Library/Homebrew/brew.rb:109:in `exit'
/usr/local/Homebrew/Library/Homebrew/brew.rb:109:in `<main>'
```

And no `java` is installed:

```
$  java --version
No Java runtime present, requesting install.
```

#### Output of `brew cask doctor`

No point.

#### Output of `brew tap`

```
$  brew tap
adoptopenjdk/openjdk
caskroom/versions
homebrew/bundle
homebrew/cask
homebrew/cask-fonts
homebrew/core
homebrew/services
microsoft/mssql-preview
```

```
$  brew --version
Homebrew 2.2.0
Homebrew/homebrew-core (git revision 70ee7; last commit 2019-12-05)
Homebrew/homebrew-cask (git revision 04e7d; last commit 2019-12-05)
```

```
$  brew cask install adoptopenjdk8 --verbose --debug
Error: Cask adoptopenjdk8 exists in multiple taps:
  caskroom/versions/adoptopenjdk8
  adoptopenjdk/openjdk/adoptopenjdk8
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:207:in `for'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:184:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:52:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:52:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:52:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:162:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:162:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

**Comment by vitorgalvao** [comment]
> #### Output of `brew cask doctor`
> No point.

Please let us be the judge of that. `brew cask doctor` is as simple to run as the provided (but not requested) `brew --version` but has way more information.

**Comment by estraph** [comment]
I am seeing this exact same problem. Running `brew cask install ...` with the fully qualified cask name works:

```
brew cask install homebrew/cask-versions/adoptopenjdk8
```

But using that full name in the `Brewfile` does not help because it gets corrected to the ambiguous name:

```
% brew bundle
Warning: treating 'homebrew/cask-versions/adoptopenjdk8' cask as 'adoptopenjdk8'!
Please change `cask "homebrew/cask-versions/adoptopenjdk8"` to `cask "adoptopenjdk8"` in your `Brewfile`.
...
Error: Cask adoptopenjdk8 exists in multiple taps:
  homebrew/cask-versions/adoptopenjdk8
  adoptopenjdk/openjdk/adoptopenjdk8
```

**Comment by estraph** [comment]
I think this is more of a [`brew bundle`](https://github.com/Homebrew/homebrew-bundle/blob/2efa0de33f2885bfd567ba4fdb1ab91f1be8d06c/lib/bundle/dsl.rb#L110) issue than it is a `brew cask` issue.

**Comment by estraph** [comment]
I opened https://github.com/Homebrew/homebrew-bundle/issues/634

**Comment by vitorgalvao** [comment]
> I think this is more of a [`brew bundle`](https://github.com/Homebrew/homebrew-bundle/blob/2efa0de33f2885bfd567ba4fdb1ab91f1be8d06c/lib/bundle/dsl.rb#L110) issue than it is a `brew cask` issue.

Agreed.

> I opened [Homebrew/homebrew-bundle#634](https://github.com/Homebrew/homebrew-bundle/issues/634)

Thank you.
