### ISSUE TITLE
brew search --casks returns an error

### ISSUE THREAD

**Issue by gbstan** [Homebrew/homebrew-cask#73838]
#### General troubleshooting steps

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

brew search --casks seems broken whereas it was working before.

#### Command that failed

```
brew search --casks
```

#### Output of command with `--force --verbose --debug`

```
Error: Cask 'knotes2' definition is invalid: Token 'megahertz-knotes' in header line does not match the file name.
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:73:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:127:in `cask'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/knotes2.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:62:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:62:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:22:in `block in each'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:21:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:21:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:68:in `to_a'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:68:in `search'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew cask doctor`

```
No output
```

#### Output of `brew tap`

```
ggpeti/rmrec
homebrew/cask
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
saulpw/vd
```

**Comment by vitorgalvao** [comment]
Fixed. Please `brew update` and try again.

**Comment by gbstan** [comment]
Wow, that is super fast! Thank you. It works now.
