### ISSUE TITLE
Ignore some cask updates

### ISSUE THREAD

**Issue by wkuckro** [Homebrew/homebrew-cask#74006]
### Description of feature/enhancement

I would like to see an option to ignore updates on specific casks, a blacklist of sorts. 

### Justification

Some casks should be ignored, but having to whitelist casks specifically can be timeconsuming if you are unsure which to update. https://github.com/buo/homebrew-cask-upgrade/issues/90 is an example of this. 

### Example use case

brew cask update -ignore atom,java,vlc

**Comment by vitorgalvao** [comment]
There’s no good way to prevent cask updates, because many pieces of software auto-update out of our control. That’s the reason we don’t have `pin`/`unpin`. This has been discussed before.
