### ISSUE TITLE
Casks with broken homepages

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-cask#74132]
These are casks that, one way or another, have a broken or inaccessible homepage that needs to be fixed. This is a good, low-barrier issue for contributors.

homebrew-cask:

- [x] [airunlock](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/airunlock.rb)
- [x] [alcatraz](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/alcatraz.rb)
- [x] [arrayfire](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/arrayfire.rb)
- [x] [autofirma](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/autofirma.rb)
- [x] [avogadro](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/avogadro.rb)
- [x] [blueservice](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/blueservice.rb)
- [x] [browser-chooserx](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/browser-chooserx.rb)
- [x] [calcservice](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/calcservice.rb)
- [x] [captur](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/captur.rb)
- [x] [cathode](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/cathode.rb)
- [x] [celestia](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/celestia.rb)
- [x] [chameleon-ssd-optimizer](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/chameleon-ssd-optimizer.rb)
- [x] [cliqz](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/cliqz.rb)
- [x] [colorpicker-skalacolor](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/colorpicker-skalacolor.rb)
- [x] [coyim](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/coyim.rb)
- [x] [cyberghost-vpn](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/cyberghost-vpn.rb)
- [x] [data-integration](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/data-integration.rb)
- [x] [deepstream](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/deepstream.rb)
- [x] [delicious-library](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/delicious-library.rb)
- [x] [dictcc-en-de-dictionary-plugin](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/dictcc-en-de-dictionary-plugin.rb)
- [x] [diskwave](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/diskwave.rb)
- [x] [dropbox-encore](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/dropbox-encore.rb)
- [x] [dwgsee](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/dwgsee.rb)
- [x] [easytether](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/easytether.rb)
- [x] [figtree](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/figtree.rb)
- [x] [forticlient](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/forticlient.rb)
- [x] [geotag](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/geotag.rb)
- [x] [gog-galaxy](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/gog-galaxy.rb)
- [x] [gom-player](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/gom-player.rb)
- [x] [goodsync](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/goodsync.rb)
- [ ] [google-nik-collection](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/google-nik-collection.rb)
- [x] [gqrx](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/gqrx.rb)
- [x] [grandperspective](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/grandperspective.rb)
- [x] [hackety-hack](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/hackety-hack.rb)
- [x] [ichm](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/ichm.rb)
- [x] [idisplay](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/idisplay.rb)
- [x] [jami](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/jami.rb)
- [x] [joplin](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/joplin.rb)
- [x] [kitabu](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/kitabu.rb)
- [x] [kompozer](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/kompozer.rb)
- [x] [kvirc](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/kvirc.rb)
- [x] [lab](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/lab.rb)
- [x] [leanpub](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/leanpub.rb)
- [x] [lisanet-gimp](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/lisanet-gimp.rb)
- [x] [macspice](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/macspice.rb)
- [x] [minecraftpe](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/minecraftpe.rb)
- [x] [mollyguard](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/mollyguard.rb)
- [x] [nodeclipse](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/nodeclipse.rb)
- [x] [okapi](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/okapi.rb)
- [x] [osbuddy](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/osbuddy.rb)
- [x] [panda](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/panda.rb)
- [x] [pixi-paint](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/pixi-paint.rb)
- [x] [plan](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/plan.rb)
- [x] [playonmac](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/playonmac.rb)
- [x] [plover](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/plover.rb)
- [x] [prismatik](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/prismatik.rb)
- [x] [qubibox](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/qubibox.rb)
- [x] [relativewave-form](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/relativewave-form.rb)
- [x] [remoteviewer](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/remoteviewer.rb)
- [x] [roboform](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/roboform.rb)
- [x] [runjs](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/runjs.rb)
- [x] [safeincloud-password-manager](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/safeincloud-password-manager.rb)
- [x] [silverback](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/silverback.rb)
- [x] [soundcloud-downloader](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/soundcloud-downloader.rb)
- [x] [strongvpn-client](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/strongvpn-client.rb)
- [x] [sugarsync](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/sugarsync.rb)
- [x] [sweet-home3d](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/sweet-home3d.rb)
- [x] [texmacs](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/texmacs.rb)
- [x] [thunder](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/thunder.rb)
- [x] [timer](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/timer.rb)
- [x] [tracks-live](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/tracks-live.rb)
- [x] [waves-central](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/waves-central.rb)
- [x] [whalebird](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/whalebird.rb)
- [x] [wordservice](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/wordservice.rb)
- [x] [yabumi](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/yabumi.rb)

homebrew-cask-drivers:

- [x] [canon-ufrii-lt-printer-driver](https://github.com/Homebrew/homebrew-cask-drivers/blob/master/Casks/canon-ufrii-lt-printer-driver.rb)
- [x] [fujitsu-scansnap-manager](https://github.com/Homebrew/homebrew-cask-drivers/blob/master/Casks/fujitsu-scansnap-manager.rb)
- [x] [volkswagen-discovercare](https://github.com/Homebrew/homebrew-cask-drivers/blob/master/Casks/volkswagen-discovercare.rb)

homebrew-cask-fonts:

- [x] [font-neodunggeunmo-code](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-neodunggeunmo-code.rb)
- [x] [font-neodunggeunmo](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-neodunggeunmo.rb)
- [x] [font-open-iconic](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-open-iconic.rb)

homebrew-cask-versions:

- [x] [skype-preview](https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/skype-preview.rb)
- [x] [skype7](https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/skype7.rb)

**Comment by carlocab** [comment]
Airunlock and Avogadro fixed in #74633 and #74634.

**Comment by mtklr** [comment]
#### homebrew-cask

alcatraz - site down, github is archived/read-only at https://github.com/alcatraz/Alcatraz

autofirma - might be https://sede.minetur.gob.es/en-us/firmaelectronica/Paginas/AutoFirma.aspx) or https://firmaelectronica.gob.es/Home/Descargas.htm (the latter page has a link to the AutoFirma_Mac.zip download).

blueservice - not listed with calcservice/wordservice (see calcservice below).

browser-chooserx - site is down, can't find replacement.

calcservice/wordservice - don't have their own pages, they're listed on https://www.devontechnologies.com/apps/freeware along with some other stuff.

captur - homepage: "Blog has been removed," can't find replacement.

cathode - is on the app store, https://apps.apple.com/us/app/cathode/id499233976?mt=12, developer website is down.

cliqz - site is down, can't find replacement.

colorpicker-skalacolor - doesn't seem to be available anymore, https://bjango.com/help/skalacolor/gettingstarted/ is still up though.

coyim - https://coy.im seems to be up.

data-integration - https://community.hitachivantara.com/community/products-and-solutions/pentaho/ seems to work, https://www.hitachivantara.com/en-us/products/data-management-analytics/pentaho-platform.html or https://sourceforge.net/projects/pentaho/ may be better though?

dictcc-en-de-dictionary-plugin - page is blank.

diskwave - https://diskwave.barthe.ph seems to be up.

gom-player - page is gom2.gomtv.com, mac player not available anymore though, download package is still available on https://app.gomtv.com/GOMForMac/gom.pkg

google-nik-collection - according to https://expertphotography.com/google-nik-collection-lightroom/: "Google sold the Nik Collection to DxO who now offer the plugin suite for a discount," at https://nikcollection.dxo.com

gqrx - http://gqrx.dk seems to be up.

hackety-hack - application error (heroku) at http://www.hackety.com, maybe https://github.com/hacketyhack/hacketyhack or http://hackety-hack.com?

ichm - site down, dev is https://github.com/robin

jami - https://jami.net seeems to be up.

kitabu - https://www.kitabu.me seems to be up.

kompozer - site certificate error, sourceforge is https://sourceforge.net/projects/kompozer/

lab - site down, https://github.com/c8r/lab up.

leanpub - app discontinued, according to https://leanpub.com/simplifying: "November 1, 2019, We just retired our iOS and Android apps, and our desktop app for Mac, PC and Linux."

lisanet-gimp - site down, sourceforge is https://sourceforge.net/projects/gimponosx/

macspice - https://www.macspice.com seems to be up.

mollyguard - site down, parent https://infinitemonkeytheory.com seems to be up.

nodeclipse - site down, sourceforge is https://sourceforge.net/projects/nodeclipse/, github is https://github.com/Nodeclipse/eclipse-node-ide

panda - site down, http://www.pablosproject.com up, github is https://github.com/pablosproject/Panda-Mac-app

pixi-paint - https://danielx.net/pixel-editor/ is an (online) editor, no app download referenced. github is https://github.com/STRd6/pixel-editor/

plan - https://getplan.co/ seems to be up, download is https://static.getplan.co/plan-latest.dmg

prismatik - page not found, https://lightpack.tv/pages/downloads seems to be up, github is https://github.com/woodenshark/Lightpack/

qubibox - https://qubibox.com/ seems to be up

relativewave-form - certificate error, http redirects to https://material.io (google bought them a while ago).

remoteviewer - page not found, and it isn't mentioned anywhere in the [ovirt](https://www.ovirt.org) documentation. possibly covered by https://github.com/jeffreywildman/homebrew-virt-manager.

silverback - site certificate expired oct. 2019

strongvpn - is https://strongvpn.com, mac-specific is https://strongvpn.com/best-vpn-for-mac/, version is 2.0.2, dl url is https://static.colomovers.com/mac/StrongVPN.dmg

sugarsync - site is down, https://support.sugarsync.com/hc/en-us is up though.

thunder - https://mac.xunlei.com seems to be up, no actual info about the app though.

whalebird - eventually redirects to https://whalebird.social/en

wordservice - see calcservice above.

yambumi - https://diskwave.barthe.ph seems to be up.

#### homebrew-cask-drivers:

canon-ufrii-lt-printer-driver - totally confusing, https://www.usa.canon.com/internet/portal/us/home/support/details/copiers-mfps-fax-machines/support-color-multifunction-copiers/color-imagerunner-lbp5975/color-imagerunner-lbp5975?tab=drivers_downloads is the closest i can find.

fujitsu-scansnap-manager - "does not work on macOS 10.15 Catalina," https://www.fujitsu.com/global/support/products/computing/peripheral/scanners/scansnap/software/s1300m-setuphtml, download link on that page is http://origin.pfultd.com/downloads/IMAGE/driver/ss/mgr/m-s1300/MacS1300ManagerV32L80WW.dmg

volkswagen-discovercare - doesn't seem to exist anymore.

#### homebrew-cask-fonts:

font-neodunggeunmo-code and font-neodunggeunmo - redirect to https://dalgona.github.io/neodgm/, github is https://github.com/Dalgona/neodgm

font-open-iconic - site certificate expired nov. 2019.

**Comment by vitorgalvao** [comment]
Great job there, @mtklr. Hadn’t had the chance to look into everything, but you’re welcome to submit PRs based on your findings, so we can better evaluate each case.

**Comment by vitorgalvao** [comment]
All done!
