### ISSUE TITLE
make cask.pkg accept do block

### ISSUE THREAD

**Issue by holymonson** [Homebrew/homebrew-cask#74169]
### Description of feature/enhancement

Make stanza `cask.pkg` accept block argument and become lazyloading like `cask.url`, as suggested in https://github.com/Homebrew/homebrew-cask-versions/issues/7838#issuecomment-528749049 .

### Justification

To fix Homebrew/homebrew-cask-versions#7838 and reduce unnecessary http request.

### Example use case

```ruby
pkg do
    "MicrosoftEdgeCanary-#{Utils.file_version}.pkg"
end
```

**Comment by vitorgalvao** [comment]
> Make stanza `cask.pkg` accept block argument and become lazyloading like `cask.url`, as suggested in [Homebrew/homebrew-cask-versions#7838 (comment)](https://github.com/Homebrew/homebrew-cask-versions/issues/7838#issuecomment-528749049) .

The suggestion was nesting `pkg` in the `url do` block, not introduce a `do` block for `pkg`. That would be wasteful, and a lot of new code for a single case that isn’t even that popular.

A better option would be to either lazy-load everything non-essential by default, or change that cask, or remove it.
