### ISSUE TITLE
frequent freecad sha256 changes for same version download

### ISSUE THREAD

**Issue by zjttoefs** [Homebrew/homebrew-cask#74318]
#### Description of issue

FreedCAD upstream appears to update the package dmg without changing the version number. The last commits to https://github.com/Homebrew/homebrew-cask/blob/master/Casks/freecad.rb only updated the sha-256. It was last updated yesterday in homebrew-cask, but the FreeCAD version I downloaded today already no longer matches. Maybe FreeCAD are updating the binaries nightly?

Looks like the solution to update the sha so frequently is not sustainable. They do keep https://github.com/FreeCAD/FreeCAD/releases/download/0.18.4/FreeCAD_0.18-16146-OSX-x86_64-conda-Qt5-Py3.dmg-SHA256.txt in sync, though.

#### Command that failed

```
brew cask upgrade freecad
```

#### Output of command with `--force --verbose --debug`

```
Expected: ba57ef6bd5653b75f9bcf33b58a1e71457f66e80b4a26240ab637c620088fc5c
Actual: 46f7c765a21982a6a63beaa2d508673ff5b1a56f6f0c4d18a3d859498a982b9e
```

**Comment by aidancuckoo** [comment]
I second that - same issues here!

**Comment by c0r0nel** [comment]
I'm suffering this too :(

**Comment by vitorgalvao** [comment]
It doesn’t seem to happen that often to justify a change in the cask, particularly when it’s so simple to make the update and it’s merged within a few minutes.

That said, if it becomes a huge issue for users, I wouldn’t mind changing it to `no_check`.

**Comment by zjttoefs** [comment]
> It doesn’t seem to happen that often to justify a change in the cask, particularly when it’s so simple to make the update and it’s merged within a few minutes.
> 
> That said, if it becomes a huge issue for users, I wouldn’t mind changing it to `no_check`.

I am trying to upgrade about once a week and have not been successful since mid December. 
By the time a PR is accepted it is outdated. The last change to the brew sha was yesterday and it is no longer valid today! The change before was 2 days before that. 

https://github.com/Homebrew/homebrew-cask/commits/master/Casks/freecad.rb

The pattern is strikingly obvious. Make it `no_check`.

**Comment by vitorgalvao** [comment]
> I am trying to upgrade about once a week and have not been successful since mid December.

If the shasum is bad and isn’t fixed, trying to update it again doesn’t make a difference.

> By the time a PR is accepted it is outdated.

Let’s please avoid exaggerations. A good PR for this cask is auto-merged within seven-minutes (I tested) and that only happens if it passes CI, which means the shasum is good. So no, PRs are definitely not outdated by the time they are accepted.

Either way, closing this via https://github.com/Homebrew/homebrew-cask/pull/77094.
