### ISSUE TITLE
Unexpected method 'license' called on Cask

### ISSUE THREAD

**Issue by hongyu7** [Homebrew/homebrew-cask#74627]
rickysun@Rickys-MacBook-Pro Caskroom % brew cask install ***********
Warning: Unexpected method 'license' called on Cask wch-ch34x-usb-serial-driver.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs

Actually wch-ch34x-usb-serial-driver have been uninstalled already. but the warning message is always there when you install something.

how ?

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
