### ISSUE TITLE
warning: unable to access '/Users/zhou/.config/git/attributes': Permission denied

### ISSUE THREAD

**Issue by danielb2** [Homebrew/homebrew-cask#74681]
#### Description of issue

`$ cd (brew --repository) && hub issue`
github.com username: danielb2
github.com password for danielb2 (never stored):
two-factor authentication code:
   `#6863  warning: unable to access '/Users/zhou/.config/git/attributes': Permission denied`

this accessing directory caught my attention. Looks like a bug

**Comment by danielb2** [comment]
hm, I don't see anything in the repo here that would cause this error. any idea where this would come from ?

**Comment by vitorgalvao** [comment]
The issue is on your git setup, not HBC. Try something like `sudo chmod 644 '/Users/zhou/.config/git/attributes'.

**Comment by danielb2** [comment]
there's no such user on my machine. I guess I should have made that clear. No such environmental  variable either.

**Comment by vitorgalvao** [comment]
> there's no such user on my machine.

The the issue is definitely in your setup.
