### ISSUE TITLE
Insecure subscripts implementation. 

### ISSUE THREAD

**Issue by petterbj** [Homebrew/homebrew-cask#74799]
#### General troubleshooting steps

- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Inside the script 

https://github.com/Homebrew/homebrew-cask/blob/aa41237d0cc50729d054ac527a9aa8982247ae26/developer/bin/list_loaded_launchjob_ids

The implementation is not very secure

Please  use `/usr/bin/sudo `instead of `sudo`

Also, why using `sudo` anyway? I don't think 
`/bin/launchctl list`
would require root privilege.

**Comment by petterbj** [comment]
I added a little explanation here. 

https://github.com/Homebrew/homebrew-cask/issues/74801

**Comment by vitorgalvao** [comment]
> Also, why using `sudo` anyway?

The script is explicit. `The system password is required to see all launchd jobs`. Some jobs do require it to appear.

> The implementation is not very secure
> 
> Please use `/usr/bin/sudo `instead of `sudo`

As you know the fix, we’d prefer a PR.

> I added a little explanation here.
> 
> #74801

Those have nothing to do with each other. That script is not part of general HBC functionality.
