### ISSUE TITLE
unnecessary sudo comman when uninstall google-chrome

### ISSUE THREAD

**Issue by petterbj** [Homebrew/homebrew-cask#74801]
#### General troubleshooting steps

- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Unnecessary sudo command when uninstalling google-chrome

#### Command that failed

```
brew cask uninstall google-chrome
```
When I typed the above command to uninstall google-chrome. 
It prompted for password as a way to unload two google launchctl jobs. 

```
com.google.keystone.agent
com.google.keystone.daemon
```

Firstly, I don't think chrome installed these two jobs. 
As I typed `launchctl list` and I didn't see the above two jobs. 

Secondly, even if there exists such jobs. It shouldn't need my password as I didn't typed my password when I installed the google-chrome. 
If it didn't require my password to install it why it require my password to uninstall it?

So I did a little research. I found out that the brew cask called a function to list all the loaded launchctl jobs which required the `sudo `command 

I believe this sudo command is unnecessary and may introduce potential security risk when multiple jobs were run at the same time.

**Comment by vitorgalvao** [comment]
> Firstly, I don't think chrome installed these two jobs.

It did. A quick web search will make it clear.

> Secondly, even if there exists such jobs. It shouldn't need my password as I didn't typed my password when I installed the google-chrome.
> If it didn't require my password to install it why it require my password to uninstall it?

Because often that is necessary, so we always use it for uninstalling.

> I found out that the brew cask called a function to list all the loaded launchctl jobs which required the `sudo `command

As explained in the other issue, that’s unrelated. That script is never run as part of HBC usage.

**Comment by petterbj** [comment]
I did the google search. And I found that the chrome installed these two jobs. 
However, after I run `sudo launchctl list` on my computer with chrome installed, I didn't find the two jobs in the output.

**Comment by petterbj** [comment]
Never mind my apologies. After a reboot, there showed up, however, 
instead of 
```
com.google.keystone.agent
com.google.keystone.daemon
```
These showed up 
```
com.google.keystone.user.agent (+)
com.google.keystone.user.xpcservice (+)
```
Are these the normal behavior or the chrome changed the name for the jobs they installed?

**Comment by petterbj** [comment]
I still believe we should avoid using unnecessary `sudo` whenever possible. 
Even if in most cases `sudo` is required, it is not required in this case.
