### ISSUE TITLE
Improve the way to keep large pkg dmg files

### ISSUE THREAD

**Issue by mgomesborges** [Homebrew/homebrew-cask#74831]
### Description of feature/enhancement

To reduce Homebrew Cask disk space usage, keep installation files like `pkg` only in `~/Library/Caches/Homebrew` and delete `dmg` files after installation.

Alert users that large files are cached and that there is the possibility of freeing up xx GB of disk space using `brew cache cleanup` or `rm -rf "$ (brew --cache)"`

### Justification

If you use a Macbook with a 256GB SSD-drive, soon you will be faced with the problem of a shortage of disk space. And Homebrew Cask will not be your best friend regarding this issue.

I noticed that when installing some packages using Homebrew Cask, it stores the pkg or dmg file in `~/Library/Caches/Homebrew`. In my point of view, these files are no longer necessary after installation. A simple solution to remove those files is `rm -rf "$ (brew --cache)"`.

For pkg packages, the situation is a bit more complicated. Homebrew not only stores the pkg file in `~/Library/Caches/Homebrew`, but it also creates a copy of it in `/usr/local/Caskroom`. A simple solution would be to use a symbolic link instead of a copy. However, this solution may have problems if we have the cache removed.

### Example use case

Imagine installing mactex-no-gui with 4.13GB pkg file: Homebrew Cask installation will create two copies of the pkg file and take 8.26GB unnecessarily. Now imagine how much unnecessary space Homebrew will take up if we install many other packages lol

Any ideas on how to solve this?
I am interested in participating in the solution.

**Comment by vitorgalvao** [comment]
Thank you for the well written issue, but this has been discussed before. Multiple times.

https://github.com/Homebrew/homebrew-cask/issues/66242

**Comment by mgomesborges** [comment]
@vitorgalvao thanks for your prompt response.

I believe I have presented one problem that has not been discussed: why Homebrew Cask duplicates and keeps two copies of the pkg files?

**Comment by vitorgalvao** [comment]
> I believe I have presented one problem that has not been discussed: why Homebrew Cask duplicates and keeps two copies of the pkg files?

One is the raw thing you downloaded, while the other is the thing you’re acting upon. The cache is why you can safely delete, while the other may pose issues if deleted. Every download works like that, it’s not pkg-exclusive.
