### ISSUE TITLE
Vagrant/Virtual Box Install Issue on Catalina

### ISSUE THREAD

**Issue by tomrossi7** [Homebrew/homebrew-cask#75239]
I'm not sure if the Vagrant cask just needs to be updated, but I'm unable to install `vagrant` because of a version issue:
```
-> vagrant up
The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant has detected that you have a version of VirtualBox installed
that is not supported by this version of Vagrant. Please install one of
the supported versions listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3, 5.0, 5.1, 5.2, 6.0

A Vagrant update may also be available that adds support for the version
you specified. Please check www.vagrantup.com/downloads.html to download
the latest version.
```

The brew install for virtualbox is version 6.1, which isn't compatible. I can't find a way to install version 6.0 of virtualbox?

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

**Comment by tomrossi7** [comment]
Sorry @vitorgalvao I wasn't sure what else would be relevant. I don't know if the `vagrant` cask is out of date or if its related the `virtualbox`. I'll post on StackOverflow and see if others have figured a workaround.
