### ISSUE TITLE
Add upgrade: procedure to installer method, or add separate upgrade stanza

### ISSUE THREAD

**Issue by danielbayley** [Homebrew/homebrew-cask#75251]
### Description of feature/enhancement

Following on from https://github.com/Homebrew/homebrew-cask/pull/72782#discussion_r356951390, where I already tried to implement something like this:
~~~ rb
if ARGV.include? 'upgrade'
    installer script: {
                        executable: "#{staged_path}/Backblaze Installer.app/Contents/MacOS/bzinstall_mate",
                        args:       ['-upgrade', 'bzdiy'],
                        sudo:       true,
                      }
else
  installer manual: 'Backblaze Installer.app'

  uninstall_postflight do
    bzpkg = '/Library/Backblaze.bzpkg'
    system_command '/bin/mv', args: [bzpkg, "#{Dir.home}/.Trash"], sudo: true if Dir.exist? bzpkg
  end
end
~~~
which did work perfectly, but was deemed too much of a "hack".

### Justification

Some casks would benefit from having a separate `upgrade` procedure from `install`. For example, in this case `brew cask upgrade backblaze` results in a reset of the previous backup state, triggering a whole new lengthy backup from scratch! Yet the app binary explicitly supplies an `-upgrade` argument, which could be utilised for a much smoother `upgrade` procedure.

Another example, which @vitorgalvao cited [here](https://github.com/Homebrew/homebrew-cask/pull/72782#discussion_r351945906) is [lulu](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/lulu.rb) which removes the user configuration on `uninstall`, making `upgrade`s through Homebrew a pain.

### Example use case

Usage could look something like this:
~~~ rb
installer manual: 'Backblaze Installer.app'

upgrade do
  system_command "#{staged_path}/Backblaze Installer.app/Contents/MacOS/bzinstall_mate",
                 args: ['-upgrade', 'bzdiy'], sudo: true
end
~~~
Although, we would also need something like:
~~~ rb
upgrade trash: '/Library/Backblaze.bzpkg'
~~~

**Comment by vitorgalvao** [comment]
> Although, we would also need something like:
> 
> ```ruby
> upgrade trash: '/Library/Backblaze.bzpkg'
> ```

Seeing as the proposed `upgrade` is already a block and would be seldom used, that’s unnecessary.

**Comment by danielbayley** [comment]
> Seeing as the proposed upgrade is already a block and would be seldom used, that’s unnecessary.

Is there, or could/should there be, a way to access methods like `trash:` from within blocks?

**Comment by vitorgalvao** [comment]
> Is there, or could/should there be, a way to access methods like `trash:` from within blocks?

What I mean is that there’s no point in having a `trash` method when we could simply remove it via other means. `upgrade` would already be niche and only applied to a few casks, there’s no point in adding an extra method (with accompanying tests) for something that would be used in a single case.

**Comment by danielbayley** [comment]
> What I mean is that there’s no point in having a trash method when we could simply remove it via other means. `upgrade` would already be niche and only applied to a few casks, there’s no point in adding an extra method (with accompanying tests) for something that would be used in a single case.

Fair enough.

So is the thinking here that this `upgrade` block should run _instead of_ `uninstall && install` when `brew cask upgrade` is called?

**Comment by vitorgalvao** [comment]
> So is the thinking here that this `upgrade` block (if specified) should run _instead of_ `uninstall && install` when `brew cask upgrade` is called?

That seems best. `upgrade` is bound to be wildly different for every cask, so making it similar to the `*flight` blocks that can run arbitrary code seems to be the most sensible option. It should also be easier to implement.

**Comment by danielbayley** [comment]
> That seems best. `upgrade` is bound to be wildly different for every cask, so making it similar to the `*flight` blocks that can run arbitrary code seems to be the most sensible option. It should also be easier to implement.

Makes sense 👍

**Comment by danielbayley** [comment]
@BrewTestBot Will revisit soon!
