### ISSUE TITLE
Can't uninstall Spectacle on Catalina

### ISSUE THREAD

**Issue by redreceipt** [Homebrew/homebrew-cask#75610]
Getting this error trying to uninstall Spectacle on Catalina:

```
Warning: Unexpected method 'accessibility_access' called on Cask spectacle.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Error: Cask 'spectacle' definition is invalid: invalid 'depends_on macos' value: ">= :lion"
```

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

**Comment by vitorgalvao** [comment]
Second error (and the fix) is explained in this pinned issue: https://github.com/Homebrew/homebrew-cask/issues/58046

For the first one we need the information in the template.

**Comment by vitorgalvao** [comment]
Second error (and the fix) is explained in this pinned issue: https://github.com/Homebrew/homebrew-cask/issues/58046. Do it, as it will fix other casks anyway.

For the first one, delete the `"$(brew --prefix)/Caskroom/spectacle"` directory.

Please don’t ignore the template next time. We worked hard on it and ask you politely to fill it, without which we mostly don’t have the required information to fix problems.

**Comment by redreceipt** [comment]
Thanks.

And FWIW, I clicked a link in your own support article that opened a blank
issue.

**Comment by vitorgalvao** [comment]
> I clicked a link in your own support article that opened a blank

Those tend to say that when opening the issue you should explain why you weren’t able to perform the steps. May have to fix it. Which one was it?

**Comment by vitorgalvao** [comment]
> The first link in the "Questions?" section.

Thank you. That one really is wrong, it should be the same as `My problem isn’t listed`.
