### ISSUE TITLE
vmware-fusion bootcamp virtual machine does not boot if installed via brew and ran as non-admin user

### ISSUE THREAD

**Issue by Tormen** [Homebrew/homebrew-cask#75756]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

My main user has NO admin rights !
So when installing the mac I created the user "admin"
then I created my user which then has no admin rights.

I am using this 2nd user! In a terminal I do then `su - admin` and as admin in the terminal (but logged in as my user!) I ran `brew cask install vmware-fusion` and then as my user I did run vmware-fusion.

I have used the apple bootcamp tool to install Windows 10 64bit.
I created with Vmware Fusion then a virtual machine (VM) using the bootcamp harddisk windows partition.
When starting the VM, Vmware Fusion hangs for >20min and then displays an error message saying that it could not start ;)

Here is how I solved the problem:

 I completely removed any trace from VMware / Fusion from the mac. The following commands were executed in a shell as user admin running in a terminal as my user:
* `brew cask remove vmware-fusion`
* `sudo reboot`
* `sudo kextcache -invalidate /`
* `find / -iname "vmware\|fusion"`
* `rm -Rf <on what was to remove (NOT all hits are to remove! )>`

Now I downloaded the dmg installer from VMware and used this.

When double clicking the installer: It also warned saying, "Downloaded from the internet... do you really want to open..." and the message had an "Open" button... but ALSO had a checkbox: "Do not ask for other content from this image" and I checked this box.

Maybe not checking this checkbox might be what the brew cask is missing / doing wrong ?!

So maybe this checkbox, maybe the fact that I avoided brew... but right after the installer I created the VM (yellow exclamation mark was still there ... but this time it started right away.

**Comment by Tormen** [comment]
I won't have time investigating this further unfortunately, but I gave you all I have. Hopefully this might be enough to either improve the cask (checkbox idea?) .... or being able to reproduce the problem maybe ?

Please accept my appologies, but I already spent super long with the vmware support on this issue... finally solving it alone ;)

I also documented it for the vmware support and in the vmware community here:
https://communities.vmware.com/message/2911107#2911107

**Comment by vitorgalvao** [comment]
Thank you for your research. Unfortunately, there’s really nothing for us to solve. We support what the software does, and many software doesn’t work well with non-admin user accounts (though the case is way less problematic than on Windows).
