### ISSUE TITLE
Should a cask attempt to resolve Gatekeeper issues?

### ISSUE THREAD

**Issue by natevw** [Homebrew/homebrew-cask#75897]
Someone I'm working with recently used the `prince` cask to install Prince XML on their Catalina machine, and reported that they were unable to actually run prince once it was installed due to Gatekeeper. They found a [workaround tip](https://www.princexml.com/forum/topic/4255/macos-catalina-prince-cannot-be-opened-because-the-developer) but reported that the instructions didn't work for them. I provided a version that explicitly followed the cask's symlinks in case that was the issue:

```
xattr -d -r com.apple.quarantine "$(readlink /usr/local/bin/prince)"
spctl --add --label "Approved" "$(readlink /usr/local/bin/prince)"
```

The user reported that *that* version worked on their machine, albeit after one final Catalina prompt [which they were able to accept and run the CLI tool, rather than just dismiss some sort of "app was blocked" message].

I have avoided Catalina personally so I can't confirm or test this myself, but it made me wonder if the cask formula should be modified to run those workarounds itself on behalf of the user? Does this project have an official policy on that?

OTOH the formula is sort of broken without it as it installs an tool that can't be used without further intervention. But OTO, this doesn't seem like something that should/would be handled on a per-formula level; the real solution is probably either:

 * something Homebrew Cask will need to deal globally with w.r.t. Catalina and downloads like this?
*  that the upstream developer will have to deal with by making their macOS download more compatible with the Submit-to-Apple® era?

[I think this may be related to the #70798 discussion but I didn't want to hijack that thread.]

**Comment by vitorgalvao** [comment]
> I think this may be related to the #70798 discussion but I didn't want to hijack that thread.

It is related, yes.

Note that we *add* those protections, as do web browsers when you download something. In HBC’s case, a quick trip to the `man` page might’ve given you the answer: use the `--no-quarantine` flag.

**Comment by natevw** [comment]
@vitorgalvao I'm assuming the `--no-quarantine` flag removes the need for the `xattr -d -r com.apple.quarantine …` fixup, thanks for that tip! Does it have any affect on the need for the `spctl --add --label "Approved" …` step or is that something that the cask formula should still do if the binary is unsigned and/or un-notarized?

**Comment by vitorgalvao** [comment]
Quarantining is a flag that must be added for Gatekeeper to do its work. Apple doesn’t provide a way to do it with CLI tools, so we needed to invent a way to add the security feature. `--no-quarantine` simply skips that process. However, we’re not going to *actively remove* security features.

Also note it’s not a “cask formula”, it’s just a “cask”.
