### ISSUE TITLE
Missing update subcommand

### ISSUE THREAD

**Issue by evitalis** [Homebrew/homebrew-cask#76002]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

`brew cask` is missing an update option similar to `brew update`, and casks are not included in the check with the latter command (that I can tell). The only way to update casks is with `brew cask upgrade` which may install an undesired version without notice. I would like to see an option to fetch updates for review without needing to install them.

#### Command that failed

```
brew cask update
```

#### Output of command with `--force --verbose --debug`

```
n/a
```

#### Output of `brew cask doctor`

```
n/a
```

#### Output of `brew tap`

```
n/a
```

**Comment by reitermarkus** [comment]
`brew update` is all you need.

**Comment by evitalis** [comment]
@reitermarkus I have confirmed over a few days that `brew update` by itself does not list casks that I can see. Does this issue need to be reported in some other repo to get properly resolved?

I ran a `brew update` the other day and saw no updates. Ran `brew cask upgrade` and chromium got updated. The day before the same happened with keepassxc.

**Comment by reitermarkus** [comment]
You're right that `brew update` does not currently *list* updated casks, but it does update all taps, which includes casks. Feel free to open a new issue regarding the output of `brew update`.
