### ISSUE TITLE
Latest Vagrant/Virtual versions are incompatable

### ISSUE THREAD

**Issue by zensunni** [Homebrew/homebrew-cask#76070]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

The current version of vagrant (2.2.7) doesn't support the current version of virtualbox (6.1). Vagrant hasn't added support in over a month. While I understand that this could be interpreted as a vagrant issue, this stops our ability to automate using homebrew, given that homebrew doesn't allow local pinning of versions.

At what point can homebrew allow pinned versions like it does for something like node (ex: node@10) or lua (ex: lua@5.1)? Is there a precedence for this?

#### Command that failed

```
brew cask install virtualbox
brew cask install vagrant
vagrant up
```

#### Output of command with `--force --verbose --debug`

```
The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant has detected that you have a version of VirtualBox installed
that is not supported by this version of Vagrant. Please install one of
the supported versions listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3, 5.0, 5.1, 5.2, 6.0

A Vagrant update may also be available that adds support for the version
you specified. Please check www.vagrantup.com/downloads.html to download
the latest version.
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew Version
2.2.4-2-g23108f3
==> macOS
10.15
...
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
$ brew tap
azure/draft
caskroom/cask
caskroom/versions
homebrew/bundle
homebrew/cask
homebrew/core
homebrew/php
weaveworks/tap
```

**Comment by vitorgalvao** [comment]
> While I understand that this could be interpreted as a vagrant issue

It is.

> homebrew doesn't allow local pinning of versions.

Homebrew *Cask* doesn’t.

> At what point can homebrew allow pinned versions like it does for something like node

Never, because casks can’t be reliably pinned, seeing as GUI software likes to update itself.

> (ex: node@10) or lua (ex: lua@5.1)?

That’s not pinning. Specific versions for casks already exist in [homebrew/cask-versions](https://github.com/Homebrew/homebrew-cask-versions). Use that repo to install specific versions.
