### ISSUE TITLE
Ability to downgrade app versions

### ISSUE THREAD

**Issue by GingkathFox** [Homebrew/homebrew-cask#76153]
### Description of feature/enhancement

It would be useful to be able to downgrade to a older version (for bug testing and such) using something like `brew cask install foobar@1.0.0`. Would this be doable?

**Comment by vitorgalvao** [comment]
That would require keeping casks for every possible version and wouldn’t work every time (i.e. in cases where upstream uses the same URL for every version). Too much work for too little demand.

We have some versions in [homebrew/cask-versions](https://github.com/Homebrew/homebrew-cask-versions), but they have specific rules for being included.

If you need to install older versions, you an either `brew cask install <URL>` where `<URL>` is a particular cask at a particular git revision (it works, but we don’t support it) or manage your own [tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md).

**Comment by GingkathFox** [comment]
alrighty, thanks!
