### ISSUE TITLE
Cask postbox is incorrectly not marked as auto-updates.

### ISSUE THREAD

**Issue by StrangeNoises** [Homebrew/homebrew-cask#76187]
Deleted superfluous sections. A command did not *fail* as such, and there are no error messages to report. It's just doing something unnecessarily but with the possibility of confusion.

#### Description of issue

brew cask upgrade just now upgraded postbox from 7.0.10 to 7.0.11. The app itself had done that already a day or few ago. It looks like the cask ought to be marked as being one that auto-updates.

#### Command that failed

```
brew cask upgrade
```

It didn't actually fail as such. cask correctly installed the new version of Postfix. Launching it afterwards, it was definitely the new one, as macos asked if I was sure I wanted to open it. So it's harmless, but it's doing an unnecessary and potentially confusing thing.

```
brew cask info postbox
```

shows that the cask is not auto-updates. But the app itself does. Auto update.

I've now checked the app and note that its Preferences->Advanced->Update does allow one to turn auto-update *off*, and I think I'll probably do that in favour of letting brew cask do it, seeing as it's going to anyway. That may count as a workaround. But by default it is enabled. Thinking about it, I wonder if it was a deliberate thing to only mark a cask auto-updates if it's not turn-offable in the app?

**Comment by vitorgalvao** [comment]
> Thinking about it, I wonder if it was a deliberate thing to only mark a cask auto-updates if it's not turn-offable in the app?

It was not. Thank you for the detailed explanation, but it was not needed. It’s not like `auto_updates` is harmful, so you could just have submitted a PR and we would have accepted it.

Making the change in https://github.com/Homebrew/homebrew-cask/pull/76188/files.
