### ISSUE TITLE
Mysql utilities url is outdated! 

### ISSUE THREAD

**Issue by GuusDijkhuis** [Homebrew/homebrew-cask#76267]
#### Description of issue

Mysql utilities url is outdated! The url is different.

Old:
```
https://dev.mysql.com/get/Downloads/MySQLGUITools/mysql-utilities-#{version}-macos10.12.dmg
```

New:
```
https://downloads.mysql.com/archives/get/p/30/file/mysql-utilities-#{version}-macos10.12.dmg
```

**Comment by vitorgalvao** [comment]
Thank you, fixing in https://github.com/Homebrew/homebrew-cask/pull/76268. But if you knew the fix, why not submit a PR instead?

**Comment by GuusDijkhuis** [comment]
Next time I'll make a PR! Thanks!
