### ISSUE TITLE
Clover Configurator cask is broken due to change in source website URL

### ISSUE THREAD

**Issue by ffloimair** [Homebrew/homebrew-cask#76589]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Since commit 77815254fd this cask is more or less broken.
The download URL no longer includes the version (which is a change on the site the binary gets pulled from), however homebrew-cask now considers the already installed version the same as the remote and therefore a checksum mismatch will happen.

Nevertheless the application now supports automatic updates. So as far as I understand the methodology in homebrew-cask this cask should be enhanced with the auto_updates step to work around it

I have created a commit on my fork that adds this: https://github.com/ffloimair/homebrew-cask/commit/575b389dd9a1a9b5a42465c9da0f6f19a4cc98ca

Can someone please verify that this is the correct approach and if yes I will create a pull request for it.

Thanks

#### Command that failed

```
homebrew cask upgrade clover-configurator
```

#### Output of command with `--force --verbose --debug`

see https://github.com/Homebrew/homebrew-cask/issues/76103 as it is the same problem with every new version

#### Output of `brew cask doctor`

see https://github.com/Homebrew/homebrew-cask/issues/76103 as it is the same problem with every new version

#### Output of `brew tap`

see https://github.com/Homebrew/homebrew-cask/issues/76103 as it is the same problem with every new version

**Comment by ran-dall** [comment]
@ffloimair LGM 👍 However, make sure you update it when you submit the PR. If you'd like I can submit it for you with your changes...

**Comment by ffloimair** [comment]
> @ffloimair LGM 👍 However, make sure you update it when you submit the PR. If you'd like I can submit it for you with your changes...

Thanks @ran-dall. I'm aware of how this works, but am currently away from my PC. If you can submit it then please go ahead. Otherwise I can do it later tonight.

**Comment by ran-dall** [comment]
@ffloimair You got it! 🔧 https://github.com/Homebrew/homebrew-cask/pull/76597

**Comment by vitorgalvao** [comment]
Thank you both.

@ffloimair For future reference, it’s best if you just submit the PR. If there’s an issue we can resolve it then. It’s way faster than having to create an issue first.

**Comment by ffloimair** [comment]
Thanks. Will do.
