### ISSUE TITLE
Cleanmymac cask is not working (devmate link is dead)

### ISSUE THREAD

**Issue by ahmadassaf** [Homebrew/homebrew-cask#76653]
`brew cask install cleanmymac` fails due to the download on devmate to be dead.

```
==> Downloading https://dl.devmate.com/com.macpaw.CleanMyMac4/4.5.2/1576752725/CleanMyMacX-4.5.2.zip

curl: (22) The requested URL returned error: 404 
Error: Download failed on Cask 'cleanmymac' with message: Download failed: https://dl.devmate.com/com.macpaw.CleanMyMac4/4.5.2/1576752725/CleanMyMacX-4.5.2.zip
```

**Comment by core-code** [comment]
Submitted (https://github.com/Homebrew/homebrew-cask/pull/76655)

**Comment by vitorgalvao** [comment]
@ahmadassaf Next time, please do not skip the template. It’s explicit that you shouldn’t do it, and following it would have showed how to fix the error.

**Comment by ahmadassaf** [comment]
sorry for this @vitorgalvao, I have assumed that if a template exists it will be present when opening the issue which was not the case.

Will do in the future.
