### ISSUE TITLE
Sug: skype-for-business should not add to dock, login

### ISSUE THREAD

**Issue by edrozenberg** [Homebrew/homebrew-cask#76721]
### Description of feature/enhancement

Currently the installation of the cask `skype-for-business` does a few things I don't want (and suspect lots of other users don't want):
* Restarts the Dock, causing **all** windows (hidden or not) to appear on the screen
* Adds itself to the Dock
* Adds itself to the user's Login Items so that it starts at boot

But - it could be the cask installation has no control over this, and just runs the default `skype-for-business` installer.

### Justification

Installing apps should not automatically have them show up in the dock, restart the dock, or add themselves to login items. It clutters the Dock, and slows down system startup by cluttering login items with additional, likely unwanted items. 99.9% of other cask installs (scientifically measured!) do not do any of this - and that's how it should be.

### Example use case

1. Install `skype-for-business`
2. Cask is installed, but no other changes are made to the user's system

**Comment by vitorgalvao** [comment]
> But - it could be the cask installation has no control over this, and just runs the default `skype-for-business` installer.

Correct. Unless those options are modifiable in the PKG, you’ll need to take up your complaint with Microsoft.
