### ISSUE TITLE
Uninstall TeamViewer bricks Catalina

### ISSUE THREAD

**Issue by palxex** [Homebrew/homebrew-cask#76829]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Uninstall Teamviewer on Catalina will cause the system hang on boot, reports "Unrecoverable Error: securityagent cannot generate requested teamviewerauthplugin: start" and stuck there. 

#### Command that failed

No failure found, uninstall succeed. Only if you reboot, you can never get back.

I found two way resolve it, both need go into recovery mode:
1. get a copy of TeamViewerAuthPlugin.bundle from anywhere like another mac, and put it to /Volume/Macintosh HD/Library/Security/SecurityAgentPlugins.
2.  After I could get into system follow method 1, I found [this topic in teamviewer forum](https://community.teamviewer.com/t5/General-Questions/Can-t-Boot-after-uninstalling-Teamviewer-on-Mac-OS-Catalina/td-p/73434#), which suggests directly delete /Volume/Macintosh HD/var/db/auth.db and let macOS rebuild it. I've also tried remove TeamViewerAuthPlugin.bundle and auth.db and it really work.

In method 2, teamviewer employers suggest this should be caused by the teamviewer security agent was removed without unregister, which causes during booting macOS still looking for it and hangs. They suggest using the built-in uninstaller( in Preferences > Advanced ), but I think homebrew users prefer uninstall with homebrew itself, so the correct way should be find the way of unregistering it, which I failed on searching.

**Comment by vitorgalvao** [comment]
That looks like a pretty nasty bug on their side, and something they should fix. I’m familiar with TeamViewer (as a user) and the fact they have something that can cause an issue like that makes me think they’re doing things on the system that they shouldn’t.

If they could provide a script to their bult-in uninstaller, it would be ideal. We don’t yet support [GUI uninstallers](https://github.com/Homebrew/homebrew-cask/issues/24377).

**Comment by palxex** [comment]
So let's wait solution from teamviewer; before that happened, I think it's better warn user at least?

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/76878
