### ISSUE TITLE
Changes in future Thonny distributions

### ISSUE THREAD

**Issue by aivarannamaa** [Homebrew/homebrew-cask#76995]
### Description of feature/enhancement

This is not really a feature request, but it is also neither a bug nor cask request.

I just wanted to let the maintainer of `thonny` cask ( @ran-dall ) know that future Thonny versions will be (probably) distributed as pkg instead of dmg.

### Justification

Because of permission problems in Catalina, I experimented with different packaging options and decided to go forward with pkg. I hope it doesn't cause problems for preparing Thonny for brew. If it does, I can continue supporting dmg, but I prefer not to.

Thonny's current version now has both dmg and pkg (https://github.com/thonny/thonny/releases/download/v3.2.6/thonny-3.2.6-macos-installer.pkg) available.

**Comment by aivarannamaa** [comment]
The installer is quite simple: it just copies Thonny bundle and runs a postinstall script. I could replicate this process with following commands:

```
pkgutil --expand-full thonny-3.2.6-macos-installer.pkg temp
cp -R temp/ThonnyComponent.pkg/Payload/Thonny.app /Applications
temp/ThonnyComponent.pkg/Scripts/postinstall dummy /Applications
```

**Comment by vitorgalvao** [comment]
Thank you for letting us know. Closing since the issue has served its purpose, but feel free to comment further if applicable.
