### ISSUE TITLE
signal is not self updating, disable auto_update setting

### ISSUE THREAD

**Issue by schlomo** [Homebrew/homebrew-cask#77214]
https://github.com/Homebrew/homebrew-cask/blob/master/Casks/signal.rb#L10 prevents `brew cask upgrade` updates of [signal](https://signal.org/). However, the update process of signal is manual: Download new version from website & install.

I therefore suggest to remove the `auto_updates true` line so that signal will be automatically updated.

If this wish meets with approval I submit a PR with the change.

**Comment by vitorgalvao** [comment]
> If this wish meets with approval I submit a PR with the change.

Please do. For future reference, for such simple changes it’s best you submit the PR directly and explain why there. It can either be merged directly or closed and we save time.
