### ISSUE TITLE
Marginnote  3.6.3002 cannot be downloaded

### ISSUE THREAD

**Issue by XsterreX** [Homebrew/homebrew-cask#77604]
==> Upgrading marginnote to 3.6.3002
==> Downloading https://appcenter-filemanagement-distrib4ede6f06e.azureedge.net/e817e853-6a6f-41 
                                                                         
curl: (22) The requested URL returned error: 403 

This problem happened since a few weeks ago. Until now still unsolved.

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
