### ISSUE TITLE
VMware Remote Console fails to download

### ISSUE THREAD

**Issue by bbufalo** [Homebrew/homebrew-cask#78031]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Download is failing with the errors included below. 

#### Command that failed

```
 ~ % brew cask install vmware-remote-console
==> Downloading https://softwareupdate.vmware.com/cds/vmw-desktop/vmrc/10.0.6/14247266/macos/com.vmware.vmrc.zip.tar
```

#### Output of command with `--force --verbose --debug`

```
 ~ % brew cask install vmware-remote-console --force --verbose --debug
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
sbcl

==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.2.7-22-g0cf4596\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.3\)\ curl/7.64.1 --location --silent --head --request GET https://softwareupdate.vmware.com/cds/vmw-desktop/vmrc/10.0.6/14247266/macos/com.vmware.vmrc.zip.tar
==> Downloading https://softwareupdate.vmware.com/cds/vmw-desktop/vmrc/10.0.6/14247266/macos/com.vmware.vmrc.zip.tar
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.2.7-22-g0cf4596\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.3\)\ curl/7.64.1 --location --range 0-1 --dump-header - --write-out \%\{http_code\} --output /dev/null https://softwareupdate.vmware.com/cds/vmw-desktop/vmrc/10.0.6/14247266/macos/com.vmware.vmrc.zip.tar
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.2.7-22-g0cf4596\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.3\)\ curl/7.64.1 --fail --progress-bar --location --remote-time --continue-at 0 --output /Users/bmbufalo/Library/Caches/Homebrew/downloads/e85be4f199d504873c0f9b65a8d544d35b7c5ca430a70115d04b2ab80d5b5442--com.vmware.vmrc.zip.tar.incomplete https://softwareupdate.vmware.com/cds/vmw-desktop/vmrc/10.0.6/14247266/macos/com.vmware.vmrc.zip.tar

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'vmware-remote-console' with message: Download failed: https://softwareupdate.vmware.com/cds/vmw-desktop/vmrc/10.0.6/14247266/macos/com.vmware.vmrc.zip.tar
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:311:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:308:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:42:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:20:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:152:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:62:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:90:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:103:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:162:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:162:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:103:in `<main>'
```

#### Output of `brew cask doctor`

```
 ~ % brew doctor
Your system is ready to brew.
```

#### Output of `brew tap`

```
 ~ % brew tap
homebrew/bundle
homebrew/cask
homebrew/core
```

**Comment by vitorgalvao** [comment]
[Reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs) → [`curl` error](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/curl_error.md).

**Comment by raoulbhatia** [comment]
I have the same issue.

I didn't find a suitable work around and registered via https://my.vmware.com/ to get the download for `VMware-Remote-Console-11.0.0-15201582.dmg` from https://my.vmware.com/en/group/vmware/details?downloadGroup=VMRC1100&productId=742#product_downloads

**Comment by vitorgalvao** [comment]
> The download link seems to contain an auth key. I am not sure if there is another way to get this software.

It’s not a popular cask, so I doubt a maintainer will want to go through the hassle of registering and trying to get a good link, meaning we’re counting on an outside contribution for this. If we don’t get it, we’ll need to remove the cask.

**Comment by bbufalo** [comment]
I'm new to contributing here so I apologize for my ignorance, but what would we need from VMware to improve this process, if we could? Can you point me to documentation on how to formulate these casks so I can ask the right questions of their support?

**Comment by vitorgalvao** [comment]
> I apologize for my ignorance

Ignorance is nothing to apologise for when one wants to learn. Thank you for posing the question and trying to help.

We need a URL that is accessible with `curl`, doesn’t require a download key, and doesn’t expire on a timer. In other words, we need them to not be [actively trying to prevent automated downloads](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#some-providers-block-command-line-downloads).

In addition, it need to either be:

* On the same domain as the `homepage` (`vmware.com`).
* On a different domain, but the page that links to it is proven official and reachable without a login (i.e. not [walled](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask)).

**Comment by bbufalo** [comment]
Thanks, that helps! I'm checking with VMware to see what their support states and seeing if there are any other available download locations they provide.

**Comment by bbufalo** [comment]
It looks like this should probably be removed from the cask as this method isn't changing. However, they did send me a document that shows this app is now available in the Mac App Store so I can use mas-cli instead to get this file as needed. Thanks for all the assistance and feel free to close this ticket out at your leisure! 

https://apps.apple.com/us/app/vmware-remote-console/id1230249825?mt=12

**Comment by vitorgalvao** [comment]
Removed. Thank you for the report and looking into it.
