### ISSUE TITLE
zap stanza for Firefox Nightly erases data for all installed versions of Firefox

### ISSUE THREAD

**Issue by paulzzy** [Homebrew/homebrew-cask#78213]
### Description of feature/enhancement

Modify the `zap` stanza for `firefox-nightly` to only remove Firefox Nightly profiles while leaving other versions of Firefox untouched. Maybe remove all folders with `nightly` in their name under `~/Library/Application Support/Firefox/Profiles/`?

### Justification

Currently the zap stanza for `firefox-nightly` is
```
  zap trash: [
               '~/Library/Application Support/Firefox',
               '~/Library/Caches/Firefox',
             ]
```
Removing `~/Library/Application Support/Firefox` also deletes the profile for other installed Firefox versions, effectively resetting them as well.

### Example use case

A user who runs `brew cask zap firefox-nightly` probably expects to delete the data for just Firefox Nightly, leaving other versions of Firefox untouched. At least, this was my assumption 🙃.

**Comment by paulzzy** [comment]
Also, I think other versions of Firefox have the same issue with the `zap` stanza; they remove `~/Library/Application Support/Firefox`.

**Comment by vitorgalvao** [comment]
`zap` documentation:

> Since shared resources may be removed, other applications may be affected by `brew cask zap`. Understanding that is the responsibility of the end user.
