### ISSUE TITLE
Global prefpane uninstallation

### ISSUE THREAD

**Issue by qaisjp** [Homebrew/homebrew-cask#78337]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

If a prefpane was installed for all users — if the prefpane is inside `/Library/PreferencePanes/` instead of `~/Library/PreferencePanes/` — then the `prefpane` stanza does not do anything.

https://github.com/Homebrew/homebrew-cask/blob/202d6019f83bbcea29ca04b41e17a3db515b0f59/lib/hbc/locations.rb#L31-L33

The above snippet needs support for `/Library/PreferencePanes`.

**Comment by vitorgalvao** [comment]
the `prefpane` stanza does not install globally, so it has no obligation to check for whatever the user did with a manual install. If a user uses a custom install method, they’re expected to know what they’re doing and how to undo it.

**Comment by qaisjp** [comment]
Okay. Thanks!
