### ISSUE TITLE
Next formulae pretends to install 1.4 but it install 1.2 

### ISSUE THREAD

**Issue by Bounga** [Homebrew/homebrew-cask#78426]
#### General troubleshooting steps

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Formulae for Next Browser was updated [here](https://github.com/Homebrew/homebrew-cask/pull/75159/files) but in fact it doesn't do anything at all. It only changes the `version` string in the recipe…

The checksum nor the url was changed so it always pulling an old version.

#### Command that failed

```
brew cask install next
```
works but when you check next version, it's still 1.2

I think the commits should be reverted to reflect the fact that Next version provided through Brew is 1.2 and not 1.4

**Comment by vitorgalvao** [comment]
Reverted to 1.2. Thank you for the report.

Pinging @ran-dall. The system can’t rely on the Github appcast for this one, it seems.

But I’m not even finding the download for 1.2 on the website.
