### ISSUE TITLE
Improve `brew cask --help` output

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/homebrew-cask#78491]
### Description of feature/enhancement

`brew cask --help` should display nicely formatted output (like `brew bundle --help` or `brew install --help`. 

This should be done by using the CLI/Parser logic in Homebrew/brew.

This can also result in `brew cask --help` output being included in `man brew` and will allow proper optional validation.

### Justification

This would be more consistent with the behaviour of other Homebrew official commands.

### Example use case

A user runs `brew man` and expects to find help for `brew cask`.

**Comment by reitermarkus** [comment]
This is done.

**Comment by MikeMcQuaid** [comment]
Nice work @reitermarkus 🎉
