### ISSUE TITLE
Add a `--dictionariesdir` parameter

### ISSUE THREAD

**Issue by tbussmann** [Homebrew/homebrew-cask#78546]
### Description of feature/enhancement

Add a `--dictionariesdir` parameter that defaults to `~/Library/Dictionaries` similar to the existing `screen_saverdir`, `input_methoddir`, `qlplugindir` and `prefpanedir` parameters.

### Justification

If you want to install a Dictionary like the `emojipedia` cask does to either the global Library or to the library of another user. This is commonly necessary if you do your daily work with an non-admin user and run homebrew with an admin user like described in #27431. Alternatively I would rather like to see a global `--librarydir` but this was discarded in #2310 or a per user linking like suggested in #11584 

### Example use case

`brew cask install emojipedia --dictionariesdir=/Users/other_user/Library/Dictionaries/`

**Comment by vitorgalvao** [comment]
It’s `--dictionarydir`. All those options are consistently singular.
