### ISSUE TITLE
Auto check for notability

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-cask#78675]
Ideally, `audit` should check for the notability requirements of new casks.

non-Cask Homebrew can do this more easily by only supporting open-source tools, but perhaps we can get some of those auto-checks as well. At the moment we only do a (manual) notability check for Github repos, which can be unfair: a non-open-source tool has an easier time getting accepted, but we shouldn’t be encouraging tools not being open-source.

Perhaps we could leverage the platform’s data [when available](https://github.com/Homebrew/brew/blob/78140cef4aea88c693d7f28a9ff6f8c288d0b944/Library/Homebrew/dev-cmd/audit.rb#L582L586) and some external source (Alexa rankings?) when not.

All ideas are welcome.

**Comment by core-code** [comment]
feel free to use our popularity ranking here :)

http://macupdater.net/app_updates/top-2500-mac-apps.html
