### ISSUE TITLE
supercollider cask has wrong sha256 sum

### ISSUE THREAD

**Issue by koaps** [Homebrew/homebrew-cask#78699]
the supercollider cask:

https://github.com/Homebrew/homebrew-cask/blob/master/Casks/supercollider.rb#L3

for the supercollider 3.11.0 signed OSX binary:

https://github.com/supercollider/supercollider/releases/download/Version-3.11.0/SuperCollider-3.11.0-macOS-signed.zip

doesn't seem to match sha256 sums:

```
sha256sum SuperCollider-3.11.0-macOS-signed.zip
549e098f1895d3ae83ce12065b42c34b5cad5b3daebe75bb3002f659d686f04b  SuperCollider-3.11.0-macOS-signed.zip
```

and fails to install:

```
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'supercollider' does not match.
Expected: 89631b3f4685b7b49fb10358feff5e255ee86f1c1c1be478d9d199c4e158cb05
  Actual: 549e098f1895d3ae83ce12065b42c34b5cad5b3daebe75bb3002f659d686f04b
```

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
