### ISSUE TITLE
Update lando from 3.0.0-rc.23 to 3.0.0-aft.1

### ISSUE THREAD

**Issue by johnpicozzi** [Homebrew/homebrew-cask#78749]
### Description of feature/enhancement

Need to update Lando from 3.0.0-rc.23 to 3.0.0-aft.1. 

### Justification

The latest version fixes an issue with Docker 2.2 that makes Lando unusable.

**Comment by vitorgalvao** [comment]
Please try a PR. Since you already know the version, in a few commands you can be done.

https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask

**Comment by johnpicozzi** [comment]
Ok, well that was cool! 

https://github.com/Homebrew/homebrew-cask/pull/78777

**Comment by vitorgalvao** [comment]
> Ok, well that was cool!

Thank you. And thank you for the PR. Closing this in its favour.
