### ISSUE TITLE
wkhtmltopdf outdated link

### ISSUE THREAD

**Issue by Czternasty** [Homebrew/homebrew-cask#78781]
Hello, 

Since this morning the SSL certificates on the URL used to install wkhtmltopdf is invalid : https://www.sslshopper.com/ssl-checker.html#hostname=https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox-0.12.5-1.macos-cocoa.pkg 

And by checking on wkhtmltopdf official website (https://wkhtmltopdf.org/downloads.html), versions are now hosted on GitHub. 

Could you update the cask to install wkhtmltopdf?

Thanks,

**Comment by edmz** [comment]
New links seem to point to, for example:

https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox-0.12.5-1.macos-cocoa.pkg

So the new cask should have something like so:

   `url "https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/#{version}/wkhtmltox-#{version}-1.macos-cocoa.pkg"`

**Comment by vitorgalvao** [comment]
You’ll get this fixed faster by trying to submit a PR that we can help you with than just asking for it to be outright done for you. It shouldn’t be a hard fix.

**Comment by ashkulz** [comment]
@vitorgalvao: see #79114

**Comment by vitorgalvao** [comment]
Thank you @ashkulz. Closing this in favour of the PR.
