### ISSUE TITLE
Update lando from 3.0.0-aft.1 to 3.0.0-aft.2

### ISSUE THREAD

**Issue by jcandan-achieve** [Homebrew/homebrew-cask#78979]
### Description of feature/enhancement

Need to update Lando from  3.0.0-aft.1 to  3.0.0-aft.2.

### Justification

This is the latest release version with the following changes:

- Added support for mariadb 10.4 #2004
- Added patch version pinning to bitnami based services #2057
- Added rsync to the php:7.4 image #2056
- Fixed bug causing --secret-toggle to break packaged landos
- Fixed bug causing prerelease version comparison produce unexpected results #2049
- Fixed breaking upstream change in all bitnami based services #2057

**Comment by vitorgalvao** [comment]
Please try a PR.

[You can be done in a few minutes with simple commands](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/78985
