### ISSUE TITLE
WPS Office Distributions: English v.s. Chinese

### ISSUE THREAD

**Issue by laggardkernel** [Homebrew/homebrew-cask#78984]
The current wps office app in `wpsoffice.rb` is a variant for the Chinese market only. The international version is on https://www.wps.com/mac/. 

And the download links are different. For the international version,

http://wdl1.pcfg.cache.wpscdn.com/wpsdl/macwpsoffice/download/2.0.2.3356/WPSOffice_2.0.2(3356).dmg

For the Chinese version,

http://package.mac.wpscdn.cn/mac_wps_pkg/2.0.1/WPS_Office_2.0.1(3256).dmg

I guess we should split the formulae into two.

There's also an issue #65078 related to the problem.

**Comment by vitorgalvao** [comment]
Seems I may have misunderstood that issue. That cask should indeed be the international version. can you create a PR?

**Comment by laggardkernel** [comment]
@vitorgalvao Done. GH-79029. What about the Chinese version, do we need to keep it in another Cask like `wpsoffice-cn.rb`?

**Comment by vitorgalvao** [comment]
> What about the Chinese version, do we need to keep it in another Cask like `wpsoffice-cn.rb`?

Make a `language` instead. See https://github.com/Homebrew/homebrew-cask/pull/76219.
