### ISSUE TITLE
Upgrade Max

### ISSUE THREAD

**Issue by mcandre** [Homebrew/homebrew-cask#79289]
Homebrew casks pins Max at v0.9.1, which is 32-bit and therefore incompatible with modern macOS Catalina. Fortunately, the maintainers have produced a newer 64-bit Max, v0.9.2b2.

https://files.sbooth.org/Max-0.9.2b2.dmg

Can we please update the cask to match?

**Comment by vitorgalvao** [comment]
Would you try a PR?

You can be done in [just a few commands](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).
