### ISSUE TITLE
homepage of `autovolume` is down

### ISSUE THREAD

**Issue by yume-chan** [Homebrew/homebrew-cask#79647]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- N/A I have retried my command with `--force`.
- N/A I ran `brew update-reset && brew update` and retried my command.
- N/A I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

The homepage link of `autovolume` cask results in 404.

https://github.com/Homebrew/homebrew-cask/blob/a8ad5fc90aec606c4be4e124df34901ea6002f93/Casks/autovolume.rb#L9

```plain
> curl -L -I http://jesseclaven.com/projects/AutoVolume/
HTTP/1.1 301 Moved Permanently
Server: nginx/1.16.1
Date: Tue, 31 Mar 2020 02:33:44 GMT
Content-Type: text/html
Content-Length: 169
Connection: keep-alive
Location: https://jesseclaven.com/projects/AutoVolume/

HTTP/1.1 404 Not Found
Server: nginx/1.16.1
Date: Tue, 31 Mar 2020 02:33:58 GMT
Content-Type: text/html
Content-Length: 153
Connection: keep-alive
```

The link in its [GitHub repo](https://github.com/jesse-c/AutoVolume), http://www.jesseclaven.com/projects/AutoVolume (without the last back slash), jumps back to its GitHub repo.

#### Command that failed

```
N/A
```

#### Output of command with `--force --verbose --debug`

```
N/A
```

#### Output of `brew cask doctor`

```
N/A
```

#### Output of `brew tap`

```
N/A
```

**Comment by vitorgalvao** [comment]
Why not make a PR instead?

Anyway, closing in favour of https://github.com/Homebrew/homebrew-cask/pull/79682.
