### ISSUE TITLE
rmdir entire Microsoft dir???

### ISSUE THREAD

**Issue by fengsi** [Homebrew/homebrew-cask#79670]
https://github.com/Homebrew/homebrew-cask/blob/faea7e1f498c3049d0ffd7b0406fa7946f18c888/Casks/microsoft-edge.rb#L16

I don't think it's safe to simply delete the entire Microsoft dir when uninstalling Edge:
```
$ pwd
/Library/Application Support/Microsoft

$ ls -l
total 0
drwxr-xr-x  3 root  wheel  96 Mar 18 18:29 MAU2.0
drwxr-xr-x  3 root  wheel  96 Mar 29 03:19 TeamsUpdaterDaemon
```
There could be other MS apps under that dir.

**Comment by vitorgalvao** [comment]
`rmdir` only removes empty directories.

Please do not ignore the template. Repeated offences will result in banning.
