### ISSUE TITLE
brew cask install macdown test version

### ISSUE THREAD

**Issue by MediEvil** [Homebrew/homebrew-cask#79907]
hey, i got a problem when i installing macdown with cask.
cask links to the testing version of macdown, instead of stable one.
Really appreciate if you can change the download url of macdown

**Comment by core-code** [comment]
there was a PR to revert to the stable version here:
https://github.com/Homebrew/homebrew-cask/pull/77654

@suschizu why did you close it?

**Comment by suschizu** [comment]
https://github.com/Homebrew/homebrew-cask/pull/79916
