### ISSUE TITLE
brew cask ci -> Unknown Cask command: --no-quarantine

### ISSUE THREAD

**Issue by AustinShalit** [Homebrew/homebrew-cask#80111]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

I have an [Azure CI script](https://github.com/wpilibsuite/homebrew-wpilib/blob/master/azure-pipelines.yml) that used to work without error but after updating to the latest Xcode version is printing an error message: `Error: Unknown Cask command: --no-quarantine`. I am just looking for some advice to see if anyone knows what this warning means and how to solve it.

Take a look at my PR to update to the latest version of Xcode where you can also view the build logs here:

https://github.com/wpilibsuite/homebrew-wpilib/pull/12

#### Command that failed

```
brew cask ci
```

#### Output of command with `--force --verbose --debug`

```
Error: Unknown Cask command: --no-quarantine
Homebrew Cask provides a friendly CLI workflow for the administration
of macOS applications distributed as binaries.

Commands:

    --cache    display the file used to cache the Cask
    audit      verifies installability of Casks
    cat        dump raw source of the given Cask to the standard output
    create     creates the given Cask and opens it in an editor
    doctor     checks for configuration issues
    edit       edits the given Cask
    fetch      downloads remote application files to local cache
    home       opens the homepage of the given Cask
    info       displays information about the given Cask
    install    installs the given Cask
    list       with no args, lists installed Casks; given installed Casks, lists staged files
    outdated   list the outdated installed Casks
    reinstall  reinstalls the given Cask
    style      checks Cask style using RuboCop
    uninstall  uninstalls the given Cask
    upgrade    upgrades all outdated casks
    zap        zaps all files associated with the given Cask

See also "man brew-cask"

##[error]Bash exited with code '1'.
```

#### Output of `brew cask doctor`

```
Your system is ready to brew.
```

**Comment by xcorlett** [comment]
What is the output of `echo $HOMEBREW_CASK_OPTS` on your system? 

At some point in the past I added this line to my `~/.brew profile`, likely copied in an attempt to fix problems I was having with Apple's good-intentioned but terribly annoying attempts to securitize my system:

`export HOMEBREW_CASK_OPTS="--fontdir=/Library/Fonts --no-quarantine`

The `--no-quarantine` option works with a number of cask commands, such as `brew cask install`, appears to be ignored when used with commands like `brew cask info` and `brew cask uninstall`, and is still parsed when no command is given or if the command is not found, as in `brew cask wrongcommand`.  The export in my bash profile was applying it to every run of `brew cask`.  It's been this way for a while but it looks like your friendly local developer @reitermarkus is on it.

**Comment by AustinShalit** [comment]
`echo $HOMEBREW_CASK_OPTS` yields `--no-quarantine`: https://dev.azure.com/wpilib/dfeeb3f5-09b9-481a-9833-ea539b674373/_apis/build/builds/12005/logs/13

It looks like Azure sets that by default. I'll probably wait for @reitermarkus to finish– thank you!
