### ISSUE TITLE
asking for and refusing my credential with this comman 'brew tap homebrew/headonly'

### ISSUE THREAD

**Issue by imshoukry** [Homebrew/homebrew-cask#80205]
I am trying to download pygame and used this command: brew tap homebrew/headonly to download pygame's dependencies. I input my credentials and receive the following error:

remote: Repository not found.
fatal: repository 'https://github.com/Homebrew/homebrew-headonly/' not found
Error: Failure while executing; `git clone https://github.com/Homebrew/homebrew-headonly /usr/local/Homebrew/Library/Taps/homebrew/homebrew-headonly` exited with 128.

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
