### ISSUE TITLE
Cask Removal: zoomus-outlook-plugin [Catalina]

### ISSUE THREAD

**Issue by Amar1729** [Homebrew/homebrew-cask#80237]
Sorry if this issue is the wrong type, wasn't sure if it should be a Bug or not.
The `zoomus-outlook-plugin` cask should not be allowed for installation on Catalina or above.

According to the [current Zoom documentation page for their plugin](https://support.zoom.us/hc/en-us/articles/200881399-Microsoft-Outlook-plugin-desktop-), macOS Catalina does NOT support plugins. This cask will not provide functionality on Catalina, and in fact when I attempt installation I do get an error:
```
Error: pkg source file not found: 'ZoomMacOutlookPlugin.pkg'
```

Relevant content from Zoom page copied here:

> Prerequisites
> - Windows: Microsoft Outlook 2010 or higher (2007 with limited features), or Outlook as part of Microsoft Office 365
> - Mac: Microsoft Outlook 2011 or higher, macOS 10.14 Mojave or below* 
> - You must have the Zoom client installed and be logged in to your account
> - Install the Zoom Microsoft Outlook Plugin from Zoom
> - 64-bit PC or Mac (the Outlook plugin is an 64-bit application; if you're using a 32-bit system, consider using the Office 365 Add-In)
>
> *macOS 10.15 Catalina does not support plug-ins, including the Microsoft Outlook Plugin for Zoom.

**Comment by Amar1729** [comment]
Not as familiar with homebrew-cask syntax so I'm not sure if this can be done programmatically or not. Figured it should at least be noted somewhere here for others.

**Comment by vitorgalvao** [comment]
> and in fact when I attempt installation I do get an error:
> 
> ```
> Error: pkg source file not found: 'ZoomMacOutlookPlugin.pkg'
> ```

That error is unrelated to the issue you’re describing. But thank you for the report. [Installation on Catalina is now prevented](https://github.com/Homebrew/homebrew-cask/pull/80241/files).
