### ISSUE TITLE
`zap multipass` leaves files behind

### ISSUE THREAD

**Issue by lulor** [Homebrew/homebrew-cask#80352]
When executing `brew cask zap multipass` to uninstall [multipass](https://multipass.run), many files are actually left behind, in particular:
* Everything under `/var/root/Library`
* Everything under `/Library/Logs`
* `~/Library/Application Support/multipass`
* `~/Library/Preferences/multipass`

The files under `$HOME` are not present at all in the cask file, while the other ones just fail to be removed, probably because they would require `sudo`

**Comment by vitorgalvao** [comment]
> The files under `$HOME` are not present at all in the cask file

Then please add them. We can’t guess what they are, and depend on contributions to keep those updated.

Closing because this does not follow the template and we already have similar issues for other casks.
