### ISSUE TITLE
Should font-cica be in homebrew-cask-fonts?

### ISSUE THREAD

**Issue by adavidzh** [Homebrew/homebrew-cask#80711]
While creating a new font cask, I stumbled upon [`font-cica`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/font-cica.rb) being in `homebrew-cask` (i.e., here) rather than in [`homebrew-cask-fonts`](https://github.com/Homebrew/homebrew-cask-fonts).

Should the `font-cica` cask be moved?

**Comment by vitorgalvao** [comment]
Yes. I’m already doing the move. Thank you.

**Comment by adavidzh** [comment]
Thanks @vitorgalvao!

**Comment by vitorgalvao** [comment]
Just noticed your name. Hello from Portugal.

**Comment by adavidzh** [comment]
_Olá!_
I just noticed that you deleted `font-cica` in #80722 and was feeling bad but then I saw homebrew/homebrew-cask-fonts#2014. _Obrigado._
