### ISSUE TITLE
Powershell cask takes several minutes to zap following new recursive rmdir: behaviour

### ISSUE THREAD

**Issue by g-a-c** [Homebrew/homebrew-cask#80794]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

The Powershell cask takes a long to zap due to recent changes in `rmdir:` behaviour to make it recursive. Powershell and one other cask that I've found (sfdx.rb) call `rmdir:` on four directories which can be very large, which causes it to take several minutes to run. These directories being:

```
~/.cache
~/.config
~/.local/share
~/.local
```

On my system, `~/.local/share` in particular is problematic - there are many Python `pipenv` environments so the recursive search for empty directories has to go both wide and deep and iterate over many folders. The actual uninstall of the Powershell package took a few seconds, the rest of the `zap` took several minutes.

From what I can tell, the `rmdir:` behaviour in these two casks pre-dates the recursive behaviour being added and this was NOT the intended behaviour for these Casks, but only to delete those four top-level directories specifically if they happen to be empty. There may also be unintended behaviour if someone deliberately has an empty directory in there which is nothing to do with Powershell, and which in my opinion `brew cask zap powershell` has no business touching.

I'm happy to make the change to fix/remove this behaviour assuming the project overall agrees that this is a regression and is "a bad thing"...

#### Command that failed

```
n/a
```

#### Output of command with `--force --verbose --debug`

```
n/a
```

#### Output of `brew cask doctor`

```
n/a
```

#### Output of `brew tap`

```
n/a
```

**Comment by vitorgalvao** [comment]
> These directories being:
> 
> ```
> ~/.cache
> ~/.config
> ~/.local/share
> ~/.local
> ```

We shouldn’t be zapping those. The correct fix here is to remove those from zap in the affected casks.

https://github.com/Homebrew/homebrew-cask/pull/80799
https://github.com/Homebrew/homebrew-cask/pull/80800

If you find anymore, please submit a PR like that.
