### ISSUE TITLE
On zap, detect if terminal has Full Disk Access, and warn if not

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-cask#80835]
Refs https://github.com/Homebrew/homebrew-cask/issues/80369. We should catch the `Operation not permitted` error on trashing something with `zap`, and instruct users to give their terminal app `Full Disk Access` under `Security & Privacy`.

**Comment by Rylan12** [comment]
Should this change be made in [`Library/Homebrew/cask/artifact/abstract_uninstall.rb`](https://github.com/Homebrew/brew/blob/56f0308fe7e2dd4a35823aa71ad838b51afe6db5/Library/Homebrew/cask/artifact/abstract_uninstall.rb#L311)?

I'm looking at line 311:

```ruby
def each_resolved_path(action, paths)
  return enum_for(:each_resolved_path, action, paths) unless block_given?

  paths.each do |path|
    resolved_path = Pathname.new(path)

    resolved_path = resolved_path.expand_path if path.to_s.start_with?("~")

    if resolved_path.relative? || resolved_path.split.any? { |part| part.to_s == ".." }
      opoo "Skipping #{Formatter.identifier(action)} for relative path '#{path}'."
      next
    end

    if MacOS.undeletable?(resolved_path)
      opoo "Skipping #{Formatter.identifier(action)} for undeletable path '#{path}'."
      next
    end

    yield path, Pathname.glob(resolved_path)
  end
end
```

That's where the error in #80369 led me.

I'm not so familiar with ruby and the Homebrew project structure but if this is the correct place to start, I can try to work my way through it.

**Comment by reitermarkus** [comment]
Yes, @Rylan12, that's probably the right spot. Feel free to start working on it.
