### ISSUE TITLE
Suitcase cask

### ISSUE THREAD

**Issue by Hipska** [Homebrew/homebrew-cask#81586]
This is a note for myself if no-one else is adding this cask.

Request to add [Suitcase](https://github.com/Impedimenta/Suitcase) tool as they only provide .dmg with .pkg.

**Comment by vitorgalvao** [comment]
[From the README](https://github.com/Homebrew/homebrew-cask/#requests):

> Issues requesting new casks will be closed. If you want a cask added to the main repositories, [submit a pull request](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#adding-a-cask).

This is also explicit in [the issue templates](https://github.com/Homebrew/homebrew-cask/issues/new/choose), where the one clearly labeled `Cask Request` with the subtitle `For requesting new casks`, states the same thing.

It’s fine if you want to add it, but please don’t use our issue tracker as a reminder for yourself.
