### ISSUE TITLE
Cask for `adoptopenjdk` has version string inconsistency

### ISSUE THREAD

**Issue by woj-tek** [Homebrew/homebrew-cask#81889]
### Description of feature/enhancement

`adoptopenjdk` cask (https://github.com/Homebrew/homebrew-cask/blob/master/Casks/adoptopenjdk.rb) should only use major version. Currently it points to version `adoptopenjdk: 14.0.1,7` which installs as `/Library/Java/JavaVirtualMachines/adoptopenjdk-14.0.1.jdk`. Previous version was installed as `/Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk`

Similar request was raised in adoptopenjdk tap: https://github.com/AdoptOpenJDK/homebrew-openjdk/issues/77

### Justification

Changing JDK location with the minor version upgrade breaks quite often IDE integrations (you have to setup and point it to exact location) and it would be preferred to stick to the major version (or even better - just use `adoptopenjdk.jdk` as it's rolling and would match naming/versioning in the cask itself.

### Example use case

Jetbrains IDEA requires setting path of the installed JDK, after recent upgrade I was surprised that after starting of the IDE no language feature was recognised and I had to configured JDK it again.

**Comment by vitorgalvao** [comment]
Sounds reasonable. https://github.com/Homebrew/homebrew-cask/pull/81892.

**Comment by woj-tek** [comment]
Not sure if I should submit new issue but seemingly quite similar issue applies to https://github.com/Homebrew/homebrew-cask/blob/master/Casks/oracle-jdk-javadoc.rb

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/82169
