### ISSUE TITLE
Inkscape installation hangs indefinitely

### ISSUE THREAD

**Issue by skyfaller** [Homebrew/homebrew-cask#81974]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

When attempting to install the latest 1.0.0 release of Inkscape, the command hangs indefinitely, with no error and no internet traffic indicating that my computer is downloading anything. I waited more than 5 minutes with no sign of activity.

FWIW, I went to their website and tried downloading it manually, and while the download is slow (~200 kb/s), both the download and their website seem to be working, so I don't think it's that their server has died under the load of everyone wanting to upgrade/install.

I tried upgrading from the previous version of Inkscape, with no joy, so I ran `brew cask uninstall inkscape` and then `brew cask install inkscape`, which got me to the current state of affairs.

#### Command that failed

```
brew cask install inkscape --verbose --debug --force
```

#### Output of command with `--force --verbose --debug`

```
nelson@Valence ~/D/G/devops (master)> brew cask install inkscape --verbose --debug --force
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.2.15-12-ga5a5a1a\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.4\)\ curl/7.64.1 --retry 3 --location --silent --head --request GET https://media.inkscape.org/dl/resources/file/Inkscape-1.0.0.dmg

```

#### Output of `brew cask doctor`

```
nelson@Valence ~/D/G/devops (master) [SIGINT]> brew cask doctor
==> Homebrew Version
2.2.15
==> macOS
10.15.4
==> SIP
Unknown (custom configuration)

configuration:
apple internal: disabled
kext signing: disabled
filesystem protections: disabled
debugging restrictions: disabled
dtrace restrictions: disabled
nvram protections: disabled
basesystem verification: enabled
==> Java
1.8.0_131
==> xattr issues
<NONE>
==> Gatekeeper support
Error: Unknown support status
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3525 casks)
/usr/local/Homebrew/Library/Taps/lukakerr/homebrew-things (2 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (151 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (923 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (148 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.39.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/usr/local/bin/fish"
```

#### Output of `brew tap`

```
nelson@Valence ~/D/G/devops (master) [SIGINT]> brew tap
bvaisvil/zenith
cjbassi/ytop
clangen/musikcube
homebrew/bundle
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
lukakerr/things
prologic/gopherclient
```

**Comment by miccal** [comment]
@skyfaller I would guess that their server is under a bit of load and suggest you wait a little while. It is working for me, but as you said it was quite slow:
```
-bash-5.0.17- /Users/miccal (32) [> brew cask fetch inkscape

==> Downloading external files for Cask inkscape
==> Downloading https://media.inkscape.org/dl/resources/file/Inkscape-1.0.0.dmg
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'inkscape'.
==> Success! Downloaded to -> /Users/miccal/Library/Caches/Homebrew/downloads/eaf062785fa5c85e3db153144c60f92970f9db
```

**Comment by skyfaller** [comment]
OK, I tried it again, and Inkscape downloaded very quickly and installed fine. I think you were correct that their server was just getting hammered.

That said, is it really right for `homebrew cask install` to just silently do nothing for 5-10 minutes? Shouldn't it throw an error or something eventually? Or at least put something in the debug output? My problem installing Inkscape is gone for now, but I think similar situations could be handled better in the future.

**Comment by miccal** [comment]
@skyfaller a `curl` request is [re-tried three times](https://github.com/Homebrew/brew/pull/7196), which when there is a problem can take some time to finish.
