### ISSUE TITLE
Can someone help updating `zoomus` `zap` stanza?

### ISSUE THREAD

**Issue by singularitti** [Homebrew/homebrew-cask#82016]
### Description of feature/enhancement

According to [this post](https://github.com/kris-anderson/remove-zoom-macos/blob/master/README.md#why-this-script-exists), `zoomus` is hard to clean up after an uninstallation. It has several security concerns. Can we update the `zap` stanza to align with [this script](https://github.com/kris-anderson/remove-zoom-macos/blob/master/remove_zoom_macos.sh)?

### Justification

After I `brew cask zap zoomus`, I can still use the script above to delete something, which means the current cask `zap` is not complete.
![image](https://user-images.githubusercontent.com/25192197/81142862-bd9abb00-8f3e-11ea-89ba-22bc33567610.png)

**Comment by miccal** [comment]
I do not think that Cask can (or should) use an external script, but I would suggest that you go ahead and add to the existing `zap` stanza for `zoomus` what files are left behind.

**Comment by singularitti** [comment]
> I do not think that Cask can (or should) use an external script, but I would suggest that you go ahead and add to the existing `zap` stanza for `zoomus` what files are left behind.

That's what I mean. Give some time.

**Comment by lulor** [comment]
Hey @singularitti, I've opened #82020

**Comment by vitorgalvao** [comment]
Closing in favour of #82020.
