### ISSUE TITLE
Add `uninstall :delete_by_bundle_id`

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-cask#8211]
Refs #8210.

> In a way, a better solution would be to automatically detect where an application is by their application bundle, but that would not work in cases like blast2go.rb since it would still leave its directory (and possibly sibling files) intact. It would still be nice to be able to do this on the casks that need nothing more, but that is for another issue.

We can detect the location on an app bundle by its bundle ID by leveraging spotlight, with `mdfind kMDItemCFBundleIdentifier = <app_bundle_id>`

In casks like [`battle-net.rb`](https://github.com/caskroom/homebrew-cask/blob/67758531b7d688e304d68a85dbcd62886f7457ce/Casks/battle-net.rb) and [`vuze.rb`](https://github.com/caskroom/homebrew-cask/blob/67758531b7d688e304d68a85dbcd62886f7457ce/Casks/vuze.rb), an `uninstall :delete_by_bundle_id` would be way more useful since it’d always work, and they would not need a caveat.

**Comment by adityadalal924** [comment]
Closing in favor of https://github.com/caskroom/homebrew-cask/issues/16339.

**Comment by vitorgalvao** [comment]
@adityadalal924 Different issues. I did come across (and even considered closing) this one when drafting #16339, but they don’t depend on each other. Even if we never implement `bundle_id`, this could still come to fruition and be useful (and vice-versa).

**Comment by reitermarkus** [comment]
@vitorgalvao, is there any other cask other than `battle-net` that would benefit from this at this point?

**Comment by vitorgalvao** [comment]
@reitermarkus Yes, let’s close it.
