### ISSUE TITLE
Support checking available disk space before running installation?

### ISSUE THREAD

**Issue by cpaika** [Homebrew/homebrew-cask#82277]
### Description of feature/enhancement
The ability for Homebrew Casks to specify a 'minimum disk space free' requirement, so that when brew does an install it makes sure there is enough disk space available.

I'm not sure if this is currently available - if so just let me know and I'll fix the package in question!  Otherwise with a lot of help if it seems like a reasonable request I could contribute a PR
### Justification
I was recently trying to install MacTex via Homebrew, and was getting a weird error message.  The installer in question didn't tell me it was out of space, but considering how large the package was and the fact I had 10 GB left on my system it made sense that was the cause.  

It would be amazing if we could add functionality to Casks that would first get the disk space available to make sure there was enough to install the package before the package installed.
{{replace this}}

### Example use case
I have 5 Gb off disk space left.  I run `brew cask install mactex`.  It notifies me that I don't have enough free space and fails the install before trying.

**Comment by cpaika** [comment]
Looking through the [hacking](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/hacking.md) docs, it doesn't look like this is part of the cask DSL.  Should I try adding a bit of Ruby for checking disk space in this particular cask, MacTex?

**Comment by vitorgalvao** [comment]
Adding this to the cask DSL would be overkill. We’re talking about a whole new functionality just for one or two casks, for an issue that almost no one ever runs into.

Ideally this is something the mactext installer scripts should check for and warn, not the cask.

**Comment by cpaika** [comment]
@vitorgalvao Makes sense 👍
