### ISSUE TITLE
wxmaxima producing bad bundle message on start up

### ISSUE THREAD

**Issue by tomoda** [Homebrew/homebrew-cask#82400]
#### General troubleshooting steps

- [x ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [x ] I ran `brew update-reset && brew update` and retried my command.
- [ x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

After using brew install for sbcl and maxima and wxmaxima today, installation succeeded. Then calling wxmaxima from the command line, the GUI opens and on the terminal prints: 
Debug: wxMacLaunch Bad bundle: /usr/local/bin/maxima. 
The GUI accepts input but does not respond. I then uninstalled the three, did the brew update-reset && brew update. Then I repeated the installation as before. That did not make any difference. With the feedback from brew doctor, I am at a loss, I don't know what I should be doing. Sorry.  Same for the checksum-check. Would love to see wxmaxima working as it did on my Linux System for many years.
Grateful for any help I can get!

#### Command that failed

```
wxmaxima
```

#### Output of command with `--force --verbose --debug`

```
wxmaxima did not accept any of these three options
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.2.16-28-gfa980e9
==> macOS
10.13.6
==> SIP
Enabled
==> Java
13.0.2
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3534 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.39.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/x86_64-darwin13
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/bash"
Families-iMac:~ familierauh$ 

```

#### Output of `brew tap`

```
Families-iMac:~ familierauh$ brew tap
homebrew/cask
homebrew/core
homebrew/services
Families-iMac:~ familierauh$ 
```

**Comment by vitorgalvao** [comment]
You’re dealing with a formula, not a cask. You’re looking for https://github.com/Homebrew/homebrew-core.

**Comment by tomoda** [comment]
Thank you very much for looking at it and telling me, were to go!
Kind regards
Jörg
