### ISSUE TITLE
How should a cask get moved to cask-versions and the new one stay here?

### ISSUE THREAD

**Issue by morganestes** [Homebrew/homebrew-cask#82429]
Local is a the generation of the old Local by Flywheel app, which still exists as a legacy app.

In #68985, the cask was renamed from "local-by-flywheel" to "[local](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/local.rb)" to reflect the change in the app name, but it's still fraught with references to the old app which prevents it from being updated with `cask-repair`.

I'd like to suggest (and help contribute to) creating/moving "local-by-flywheel" to homebrew/cask-versions as a legacy app, and fully updating the existing "local" package here to reflect the distribution channels for the new Local.app.

Because of the way the existing cask was renamed and formulated, it seems to me that this would require creating a new cask in versions and updating the one here, but since it's already been through a name change I wanted to check before I started down that path.

Can you suggest the best way forward for doing this?

**Comment by vitorgalvao** [comment]
> but it's still fraught with references to the old app which prevents it from being updated with `cask-repair`.

I have no idea what that means. `cask-repair` doesn’t care, it lets you edit the cask to be whatever, as long as it passes `audit` and `style`.

You’ll have to be specific about what’s happening.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/82440
