### ISSUE TITLE
zoomus zap stanza does not remove loopback device ZoomAudioDevice

### ISSUE THREAD

**Issue by RogerThiede** [Homebrew/homebrew-cask#82570]
Zoom (`zoomus`) offers the capability to setup a loopback audio device called _ZoomAudioDevice_ and can be viewed in _Audio MIDI Setup.app_.  While `brew cask uninstall zoomus` is expected to uninstall a cask application, `brew cask zap zoomus` is expected to remove all preferences, logs, and associated files installed by the cask.

The zap stanza can be enhanced to thoroughly eliminate plug-ins and kernel extensions installed by the cask.

After executing `brew cask zap zoomus`, my macOS 10.15.4 system continued to have a MIDI device called `ZoomAudioDevice` and files located in `/Library/Audio/Plug-Ins/HAL/ZoomAudioDevice.driver`.

**Comment by RogerThiede** [comment]
I have not reviewed this bash-script or know the author, but https://github.com/kris-anderson/remove-zoom-macos/ appears to be made to be the equivilent of an ideal `brew cask zap zoomus`.

**Comment by miccal** [comment]
@RogerThiede why not open a PR and add this yourself? Just add the line
```
/Library/Audio/Plug-Ins/HAL/ZoomAudioDevice.driver
```
to the list in the `uninstall delete:` part.

**Comment by vitorgalvao** [comment]
Agreed with @miccal. If you open a PR, your requested change will be easier to understand and review / approve.
