### ISSUE TITLE
stable version for mendeley

### ISSUE THREAD

**Issue by holymonson** [Homebrew/homebrew-cask#82699]
### Description of feature/enhancement

mendeley releases stable version v1.19.6 (check https://www.mendeley.com/release-notes/), so the cask updated on #82008 . 

But mendeley.com merely update their download homepage (https://www.mendeley.com/download-desktop-new), the version there stuck in v1.19.4 for a long time, and the cask reverted back on #82556 .

IMHO, I suggest we use the stable version in release-notes instead of the outdated download page, just like other linux distro do.

Alternatively, I was thinking about a new mendeley-stable in homebrew-cask-versions, but there are mainly non-stable verions. 

CC @ran-dall

**Comment by miccal** [comment]
There does not seem to be a download link for version 1.19.6 on their website, though -- the only download link available seems to be `https://www.mendeley.com/autoupdates/installer/Mac-x64/stable-incoming` withs points to version 1.19.4:
```
-bash-5.0.17- /Users/miccal (30) [>  curl -sLI https://www.mendeley.com/autoupdates/installer/Mac-x64/stable-incoming | grep -i Location
Location: https://desktop-download.mendeley.com/download/Mendeley-Desktop-1.19.4-OSX-Universal.dmg
```
Do you know of a link that points to the newer version as stated in the release notes?

**Comment by holymonson** [comment]
download page is https://www.mendeley.com/autoupdates/installers/1.19.6 , and download link is https://www.mendeley.com/autoupdates/installer/Mac-x64/1.19.6 . You can download any version by replacing the version if it exists, otherwise will get a 403.

But I haven't find the link from homepage to those download pages. They seems reconstructing their homepage and paused for a year since 1.19.4 released . (1.19.5 was released around 2019-08-31.)

It's amazing that their devel team keep doing a good job and released several dev versions while their website team did nothing even for stable release. Since mendeley is mainly for academic use maybe they have other channels to academic institutions.

**Comment by ran-dall** [comment]
@holymonson Unless, we get some sort of confirmation from the developers that `1.19.6` is the latest stable release, we have no other option than to provide `1.19.4` as stable on HBC; as that's what's listed as 'last stable version' on their website.
