### ISSUE TITLE
Fliqlo installs only for current user

### ISSUE THREAD

**Issue by knyttl** [Homebrew/homebrew-cask#82850]
When you install fliqlo screensaver:

`brew cask install fliqlo`

It is installed only for current user. When some other user tries to install it, it just says it is already installed and user cannot use it.

I guess the screensaver should be moved to global `/Library/Screen Savers` instead of local.

**Comment by miccal** [comment]
[The location is set to be `~/Library/Screen Savers`](https://github.com/Homebrew/brew/blob/0e9897c86d8e1e866d08ce1a065fe80a7f920b59/Library/Homebrew/cask/config.rb#L24), and I think then only way around this would be to move it to `/Library/Screen Savers` manually.

**Comment by knyttl** [comment]
The problem is that it is not clear for the user who is told "already installed" and he doesn't see it.

**Comment by miccal** [comment]
This is because Homebrew only supports running as the owning user. The details of what is installed via Cask are kept in `/usr/local/Caskroom/`, so the other user can "see" that something has been installed via Cask but does not have permission to "use" it.

**Comment by vitorgalvao** [comment]
```console
$ man -P 'less --pattern "^ {7}--screen_saverdir="' brew-cask

      --screen_saverdir=<path>
              Target  location  for  Screen  Savers.  The default value is
              ~/Library/Screen Savers.
```
