### ISSUE TITLE
[Feature Request] Use snap for Linux as Homebrew Casks source

### ISSUE THREAD

**Issue by dalisoft** [Homebrew/homebrew-cask#82914]
### Description of feature/enhancement

In Linux Homebrew casks does not works as i know (for macOS only), i think would be good to use `snap` as Homebrew Cask alternative for available apps.

This allows users more benefits, in example:
- One @ansible playbook will work on both macOS and Linux which makes developers migrate between OS easier
- User always choose Homebrew Cask over different sources (i will choose Homebrew Cask if it's supported)

If some apps does not exist in `snap`, just skip or fail (with option for passing/skip) that cask.

I hope you understand my feature request and thanks a lot of very useful tool for developers

### Example use case

- `brew cask install vscodium` => `snap install vscodium`
- `brew cask install postman` => `snap install postman --classic`

**Comment by vitorgalvao** [comment]
We don’t have a desire to support casks in Linux. They’re hard enough to do on macOS already, and having to keep track of them over another package manager and then only work some of the time is a bunch of work for a bad experience.

**Comment by dalisoft** [comment]
Thanks for reply. I understand :)
