### ISSUE TITLE
Update breaks outdated check

### ISSUE THREAD

**Issue by ralphrmartin** [Homebrew/homebrew-cask#83163]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
brew cask outdated --greedy

## What happened (include command output)

Error due to internal changes in homebrew rendering previously correct formulae invalid

<details>
  <summary>Command output</summary>
  <pre>
Error: Cask 'aquiline-check' definition is invalid: invalid 'depends_on macos' value: ">= 10.11"
  </pre>
</details>

## What you expected to happen

List of outdated packages

## Step-by-step reproduction instructions (by running `brew` commands)

as above

As an aside, I'd note that this is not the only problem of this kind to happen recently, where changes to homebrew have broken older formaulae.

## Output of `brew config` and `brew doctor` commands

<pre>
brew config                
HOMEBREW_VERSION: 2.2.17-98-ge6dda52
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: e6dda524debff777d0c97a6bee22369cf76c207e
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 572fc56b93562aa2d07749e826f8b4ab6cc04090
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.avNulD1YCk/org.macosforge.xquartz:0
HOMEBREW_EDITOR: /usr/local/bin/emacs
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 12
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.26.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14.0.1, 1.8.0_251
macOS: 10.15.4-x86_64
CLT: 11.5.0.0.1.1588476445
Xcode: 11.5
XQuartz: 2.7.11 => /opt/X11

brew doctor                                
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libaspell.15.dylib
  /usr/local/lib/libchkp.dylib
  /usr/local/lib/libghdlvpi.dylib
  /usr/local/lib/libifcore.dylib
  /usr/local/lib/libifcoremt.dylib
  /usr/local/lib/libifport.dylib
  /usr/local/lib/libifportmt.dylib
  /usr/local/lib/libimf.dylib
  /usr/local/lib/libintlc.dylib
  /usr/local/lib/libiompstubs5.dylib
  /usr/local/lib/libirc.dylib
  /usr/local/lib/libirng.dylib
  /usr/local/lib/libjlinkpic32.6.34.6.dylib
  /usr/local/lib/libjpeg.8.dylib
  /usr/local/lib/libmkl_avx.dylib
  /usr/local/lib/libmkl_avx2.dylib
  /usr/local/lib/libmkl_avx512.dylib
  /usr/local/lib/libmkl_blacs_mpich_ilp64.dylib
  /usr/local/lib/libmkl_blacs_mpich_lp64.dylib
  /usr/local/lib/libmkl_cdft_core.dylib
  /usr/local/lib/libmkl_core.dylib
  /usr/local/lib/libmkl_intel_ilp64.dylib
  /usr/local/lib/libmkl_intel_lp64.dylib
  /usr/local/lib/libmkl_intel_thread.dylib
  /usr/local/lib/libmkl_mc.dylib
  /usr/local/lib/libmkl_mc3.dylib
  /usr/local/lib/libmkl_rt.dylib
  /usr/local/lib/libmkl_scalapack_ilp64.dylib
  /usr/local/lib/libmkl_scalapack_lp64.dylib
  /usr/local/lib/libmkl_sequential.dylib
  /usr/local/lib/libmkl_tbb_thread.dylib
  /usr/local/lib/libmkl_vml_avx.dylib
  /usr/local/lib/libmkl_vml_avx2.dylib
  /usr/local/lib/libmkl_vml_avx512.dylib
  /usr/local/lib/libmkl_vml_mc.dylib
  /usr/local/lib/libmkl_vml_mc2.dylib
  /usr/local/lib/libmkl_vml_mc3.dylib
  /usr/local/lib/libnettle.6.3.dylib
  /usr/local/lib/libpspell.15.dylib
  /usr/local/lib/libsvml.dylib
  /usr/local/lib/libusb-1.0.0.dylib
  /usr/local/lib/libusb-1.0.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/aspell.h
  /usr/local/include/vpi_user.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libaspell.la
  /usr/local/lib/libpspell.la
</pre>

**Comment by ralphrmartin** [comment]
Perhaps I should make clear that there are 2 issues here

- first and foremost, one cask formula with errors in it should not bring the whole command down. 

- secondly, it is bad practice for some change in homebrew cask to make a previously valid formula invalid with a hard error. That cask may have been abandoned by its author, for example, leaving end-users with no clue what to do.

**Comment by ralphrmartin** [comment]
A similar issue exists with respect to the licence stanza in manopen.rb, although that only emits a warning rather than a hard error.

**Comment by vitorgalvao** [comment]
> first and foremost, one cask formula with errors in it should not bring the whole command down.

That is correct. We’re aware, though we might not have an issue to track that. Please make a new issue with that as the point (and use our template).

Neither of the mentioned casks is on this repo, and the original one looks like it never even was.

**Comment by ralphrmartin** [comment]
It's irrelevant where the formula came from. Your actions broke it.

**Comment by vitorgalvao** [comment]
> It's irrelevant where the formula came from. Your actions broke it.

1. It’s not a formula, it’s a cask. They’re different things.
2. I just told you you are correct and asked you to make an issue specifically on it. I don’t get what you’re complaining about.

**Comment by ralphrmartin** [comment]
Sorry, but I dont understand what you want me to do different. I've submitted an issue, which you have closed, telling me to submit an issue.
Is it the title you are objecting to? 
Or that you believe that this is just one example of a more serious problem? I can hardly file a different issue on that when I dont know how far or deep that problem goes. All I can do is to report the thing that I am sure is broken - its pointless for me to speculate on when else similar behaviour might be triggered, or that error handling is shared in some way.
What I was "complaining" about was your remark "Neither of the mentioned casks is on this repo, and the original one looks like it never even was." which somehow seems to imply that it was their fault. Perhaps I misunderstood what you meant.  As external taps are allowed, all I was saying was that changes which break stuff need to take that into account, and in that sense it was irrelevant where the casks came from - they worked before.

**Comment by vitorgalvao** [comment]
> Sorry, but I dont understand what you want me to do different.

You’ve submitted the issue to Homebrew/brew. It was transferred to Homebrew/homebrew-cask (here). We have different templates when opening issues, and it’s with that one I’m asking you to make your new one.

> one cask ~~formula~~ with errors in it should not bring the whole command down.

With that being the point. You may use the example you’ve bumped into *as an example*, but the main point is in that quote.

> secondly, it is bad practice for some change in homebrew cask to make a previously valid formula invalid with a hard error. That cask may have been abandoned by its author, for example, leaving end-users with no clue what to do.

That said, I don’t find this a good take. We shouldn’t be expected to keep old code hanging around to support old features indefinitely, especially not to support abandoned casks. We deprecate things and then we remove them at a later date. If we did as you suggest, we’d still be supporting cask syntax that was deprecated years ago.

But as you correctly pointed out, bad casks shouldn’t stop usage of other casks, they should be ignored with a warning.

> What I was "complaining" about was your remark "Neither of the mentioned casks is on this repo, and the original one looks like it never even was." which somehow seems to imply that it was their fault.

Please don’t assume things I haven’t said. There’s no implication. That was a mere truthful remark, it neither condones nor condemns. To whoever comes after (likely another maintainer), it helps to put into perspective where the issue happened. Because it happened outside of the main repos, its importance is lower because it affects fewer users and we have no control over it. It doesn’t mean it isn’t important nor does it assign blame, but it identifies what part is relevant to us.

**Comment by ralphrmartin** [comment]
> On 24 May 2020, at 20:30, Vítor Galvão <notifications@github.com> wrote:
> 
> 
> Sorry, but I dont understand what you want me to do different.
> 
> You’ve submitted the issue to Homebrew/brew. It was transferred to Homebrew/homebrew-cask (here). We have different templates when opening issues, and it’s with that one I’m asking you to make your new one.

Thanks. I now understand. I'll do that.

**Comment by ralphrmartin** [comment]
See #83178
