### ISSUE TITLE
Use new location for Docker Desktop

### ISSUE THREAD

**Issue by StefanScherer** [Homebrew/homebrew-cask#83360]
### Description of feature/enhancement

This is a heads up that new versions of Docker Desktop are available at desktop.docker.com. The download.docker.com will be deprecated at some future point.

### Justification

https://github.com/Homebrew/homebrew-cask/blob/master/Casks/docker.rb#L10-L11

**Comment by ran-dall** [comment]
@StefanScherer Is it currently working for us to update? I'm getting an error when I go to `https://desktop.docker.com/`.

![Screen Shot 2020-05-28 at 12 55 23 AM](https://user-images.githubusercontent.com/17261190/83114575-a9b72480-a0b8-11ea-9487-2a0ee5cb5475.png)

**Comment by StefanScherer** [comment]
@ran-dall The directory browsing is disabled on that website, but things like `curl https://desktop.docker.com/mac/stable/appcast.xml` work. 
Desktop downloads never were browsable. I guess you should be good to switch over.

**Comment by ran-dall** [comment]
@StefanScherer Ok, great! I went ahead and updated that. #83361
