### ISSUE TITLE
mactex installs binaries in /Library/TeX/texbin and none are softlinked to /usr/local/bin/

### ISSUE THREAD

**Issue by nitrocode** [Homebrew/homebrew-cask#83467]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

After installing `mactex`, it installs all the binaries in `/Library/TeX/texbin` and none of those binaries are softlinked to `/usr/local/bin` and the path is not added to the global path.

#### Command that failed

This command did not fail but it failed to update my global path or failed to softlink the binaries to `/usr/local/bin`

```
brew cask install mactex
```

#### Output of command with `--force --verbose --debug`

```
N/A
```

#### Output of `brew cask doctor`

```
N/A
```

#### Output of `brew tap`

```
N/A
```

**Comment by ran-dall** [comment]
@nitrocode FMU the cask simply runs the `.pkg` provided by `MacTeX`. We don't select where the `.pkg` installation puts the files.

**Comment by nitrocode** [comment]
Can't we create bin symlinks to each binary?

**Comment by ran-dall** [comment]
> We don't select where the .pkg installation puts the files.

@nitrocode Usually don't modify what is intended by the `.pkg` installer.

**Comment by nitrocode** [comment]
Why can't we?


If we cannot do symlinks then we could at least put additional information after the installation to tell the user to update their $PATH variable. I'd prefer if it was automatic but if not, a message would suffice.

**Comment by miccal** [comment]
@nitrocode the MacTex installer should automatically update your PATH:

<img width="948" alt="Screen Shot 2020-05-30 at 09 04 46" src="https://user-images.githubusercontent.com/6127163/83315763-c2f4d800-a254-11ea-9104-6246ef539e18.png">

and the cask should definitely not modify this in any way.

If the MacTex installer is not working correctly for you, you should report it to [MacTex support](http://www.tug.org/mactex/support/emailform/index.html).

**Comment by ran-dall** [comment]
> Why can't we?

It's not what we do. We try to be unopinionated like that.
