### ISSUE TITLE
wpsoffice can find newer version in china's official website

### ISSUE THREAD

**Issue by CallMeR** [Homebrew/homebrew-cask#83483]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

wpsoffice official website in china is “https://mac.wps.cn/”
Current version is 2.3.1(3761)/2020.05.18
The version is newer than “https://www.wps.com/mac/”

#### Command that failed

```
{{replace this}}
```

#### Output of command with `--force --verbose --debug`

```
{{replace this}}
```

#### Output of `brew cask doctor`

```
{{replace this}}
```

#### Output of `brew tap`

```
{{replace this}}
```

**Comment by ran-dall** [comment]
@CallMeR Could it be that that release is meant specifically for China-based users?

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/80208

**Comment by ran-dall** [comment]
@miccal Thank you for reminding me. 😁

@CallMeR So we've actually already considered this before (as @miccal pointed out). We're open to modifying a cask so that users in China can get the right cask, however, no one has submitted the changes yet. You're more then welcome to submit a PR if you feel the change should be implemented.
