### ISSUE TITLE
Add official Facebook Messenger Desktop application / clash with existing cask name

### ISSUE THREAD

**Issue by 0xdevalias** [Homebrew/homebrew-cask#83578]
I realise that cask requests aren't currently accepted via issues, but I wanted to open this anyway to get better insight on how to go about it.

Facebook Messenger has an official desktop client these days:

- https://www.messenger.com/desktop

The name I would expect to find this under would be `messenger`, but that appears to already be used by an existing app that is sort of a 3rd party desktop messenger wrapper called "Messenger for Mac":

- https://github.com/Homebrew/homebrew-cask/blob/master/Casks/messenger.rb
  - https://fbmacmessenger.rsms.me/

Ideally I would think the official messenger app should be called `messenger`, or maybe `messenger-desktop` or similar, but given this likely clashes/confuses with the existing package, I am wondering if that package should be renamed something that better represents it's app title (rather than `messenger`, perhaps `messenger-for-mac` or similar?)

Once I have better clarity on the best path forward, I can [create the cask](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#adding-a-cask)/PR:

- `brew cask create THEBESTNAMEHERE`

Following https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#generating-a-token-for-the-cask

```
⇒  "$(brew --repository)/Library/Taps/homebrew/homebrew-cask/developer/bin/generate_cask_token" "Messenger"
Proposed token:               messenger
Proposed file name:           messenger.rb
Cask Header Line:             cask 'messenger' do

WARNING: the file '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/messenger.rb' already exists. Prepend the vendor name if this is not a duplicate.

⇒  "$(brew --repository)/Library/Taps/homebrew/homebrew-cask/developer/bin/generate_cask_token" "Facebook Messenger"
Proposed token:               facebook-messenger
Proposed file name:           facebook-messenger.rb
Cask Header Line:             cask 'facebook-messenger' do
```

**Comment by 0xdevalias** [comment]
Actually.. disregard.. I just realised that this is now on the Mac App Store (it wasn't when I initially installed it, and was just a direct download)

**Comment by vitorgalvao** [comment]
This is covered in the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md) (last point).

The official cask would get the official name, and the other one would get the `-unofficial` prefix.

**Comment by 0xdevalias** [comment]
That makes sense, I missed it the first time as it’s right down the bottom.

In that section is talks about if the unofficial cask could be confused as an official one. I wonder if that applies to this situation, even though the official app is on the App Store? I can easily imagine myself trying to brew cask install messenger before remembering that’s unofficial and having to go to the App Store again.

**Comment by vitorgalvao** [comment]
That’s a good point. Renaming the one we have.
