### ISSUE TITLE
Error when updating forticlient

### ISSUE THREAD

**Issue by DanielNetoP** [Homebrew/homebrew-cask#83751]
I'm trying to upgrade the forticlient cask but I got an error due to the lack of a uninstall script:

`
Error: uninstall script /Applications/FortiClientUninstaller.app/Contents/Resources/uninstall_helper does not exist.
`

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
