### ISSUE TITLE
How to extract full "real" installed app name with --json=v1 in shell script?

### ISSUE THREAD

**Issue by tiiiecherle** [Homebrew/homebrew-cask#83889]
Hey,

I'm trying to get the "real full app name" of a cask/app under which it is installed in a shell script, like
`/Applications/APP_NAME.app`

Example:
```
CASK="geburtstagschecker"
CASK_ARTIFACT_APP=$(brew cask info --json=v1 "$CASK" | jq -r '.[]|(.artifacts|map(.[]?|select(type=="string")|select(test(".app$"))))|.[]')
APP_NAME=$(basename "$CASK_ARTIFACT_APP")
echo "$APP_NAME"
```

Is there an easier/better way to do this that also works for casks installed via pkg? Or to get the full install path of the cask? Would be easy to get its basename then.

Thanks a lot for any help and for this nice project.

**Comment by vitorgalvao** [comment]
No, you can’t do it for `pkg` casks, because you’d need to download and extract the `pkg` to find the app’s name (if it even installs one).
