### ISSUE TITLE
Unclear about why the `cloudlibrary` cask was removed.

### ISSUE THREAD

**Issue by aisamji** [Homebrew/homebrew-cask#83970]
I recently attempted to install [CloudLibrary](https://www.yourcloudlibrary.com/mac/) via Homebrew but it seems the cask for it has been previously removed.

```
alisamji@MacBook-Pro ~ % brew search cloudlibrary
No formula or cask found for "cloudlibrary".
Closed pull requests:
Update cloudlibrary to add appcast stanza (https://github.com/Homebrew/homebrew-cask/pull/68162)
Update cloudlibrary to 2.3.1708230907 (https://github.com/Homebrew/homebrew-cask/pull/42817)
Update cloudlibrary to 2.3.1708230907 (https://github.com/Homebrew/homebrew-cask/pull/42961)
Update cloudlibrary to 2.3.1708230907 (https://github.com/Homebrew/homebrew-cask/pull/42839)
Update cloudlibrary to 2.2.1706151134 (https://github.com/Homebrew/homebrew-cask/pull/37161)
Update cloudlibrary to 2.1.1701121409 (https://github.com/Homebrew/homebrew-cask/pull/34734)
Update cloudlibrary to 2.1.1701121409 (https://github.com/Homebrew/homebrew-cask/pull/33210)
Change token from 3mcloudlibrary to cloudlibrary (https://github.com/Homebrew/homebrew-cask/pull/25497)
```

Upon reviewing the list of [closed PRs](https://github.com/Homebrew/homebrew-cask/pulls?q=is%3Apr+is%3Aclosed+cloudlibrary), I couldn't find any explanation as to why it was removed. Would someone be able to provide some clarity on this?

**Comment by miccal** [comment]
This was removed in https://github.com/Homebrew/homebrew-cask/pull/69981

**Comment by vitorgalvao** [comment]
It was removed because almost nobody used it and those casks tend to be abandoned and break. You’re welcome to resubmit if you need it. It will be excluded from such removals for at least one year.
