### ISSUE TITLE
CI Issues

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-cask#84037]
CI is crapping itself again. Making this issue so we can track the problems.

- [x] Error: Calling brew pull is deprecated! Use hub checkout instead. ([example](https://github.com/Homebrew/homebrew-cask/pull/84018/checks))
- [x] appcast at URL '{{SOMETHING}}' offline or looping ([example](https://github.com/Homebrew/homebrew-cask/pull/84018/checks)).
- [x] `Error: undefined method any_version_installed?` ([example](https://github.com/Homebrew/homebrew-cask/pull/83730/checks))
- [x] `Error: Calling Formula#installed? is deprecated! Use Formula#latest_version_installed? (or Formula#any_version_installed? ) instead.`([example](https://github.com/Homebrew/homebrew-cask/pull/84432/checks))

**Comment by ran-dall** [comment]
I’ve been meaning to fix GitHub Actions. I already have a fix for it. I’ll set it up and push it this morning.

**Comment by vitorgalvao** [comment]
> I already have a fix for it.

Thank you!

I was under the impression you had already mentioned the `brew pull` issue and had fixed it, but didn’t find it in a quick search. Don’t forget it needs to apply to all repos. We have a Workflow to sync it between repos, but I’m unsure of how well it works.

**Comment by ran-dall** [comment]
@vitorgalvao Noted. Do you know if there is there a way to test out the CI modifications?

**Comment by vitorgalvao** [comment]
> Do you know if there is there a way to test out the CI modifications?

I think it works if you make a PR but don’t merge (i.e. you can keep iterating on the PR itself until it passes).

**Comment by ran-dall** [comment]
#84053

**Comment by ran-dall** [comment]
I'll do Travis next...

**Comment by ran-dall** [comment]
#84058

**Comment by ran-dall** [comment]
That last one, I made comments on https://github.com/Homebrew/homebrew-cask/pull/83730#issuecomment-639769767.

I'm pretty sure I referenced something that doesn't exist?

**Comment by ran-dall** [comment]
@vitorgalvao I set them for you to review. If they're correct, I can run the workflow. I found it.

**Comment by vitorgalvao** [comment]
> Also, I'm seeing "Cask '{{SOMETHING}}' definition is invalid: invalid `depends_on macos:` value: `>= :mavericks`" CI errors in PRs… Presumably, this is another symptom?

No, that’s unrelated. That’s due to us still having the (quite broken) system of keeping a cask copy from install time and not failing well when it becomes unreadable. Homebrew just dropped support for pre-Yosemite, so it might happen a lot.

Do https://github.com/Homebrew/homebrew-cask/issues/58046.

**Comment by danielbayley** [comment]
Thanks @vitorgalvao!

**Comment by fanninpm** [comment]
I'm assuming [this](https://github.com/Homebrew/homebrew-cask/runs/766230824?check_suite_focus=true) is unrelated/irrelevant? (I found it in the Actions tab, and I don't know if it does anything important.)

**Comment by vitorgalvao** [comment]
Thank you @ran-dall for the fast action, and @reitermarkus for the reviews.

**Comment by vitorgalvao** [comment]
@ran-dall I see you added another one and are keeping track. Carry on, then!

**Comment by SeekingMeaning** [comment]
For `Calling Formula#installed? is deprecated` audit seems to mistake `Cask#installed?` for `Formula#installed?`
