### ISSUE TITLE
4k-youtube-to-mp3 SSL certificate problem

### ISSUE THREAD

**Issue by ppo** [Homebrew/homebrew-cask#84041]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

`curl: (60) SSL certificate problem: certificate has expired` but the certificate seems valid.

```
$ echo | openssl s_client -showcerts -servername dl.4kdownload.com -connect dl.4kdownload.com:443 2>/dev/null | openssl x509 -inform pem -noout -text
[…]
        Validity
            Not Before: Oct 10 00:00:00 2018 GMT
            Not After : Nov  6 23:59:59 2020 GMT
[…]
```

#### Command that failed

```
brew cu --yes --all
```

#### Output of command with `--force --verbose --debug`

```
==> Found outdated apps
     Cask               Current      Latest       A/U    Result    URL
1/1  4k-youtube-to-mp3  3.12.1.3660  3.12.3.3680       [OUTDATED]  https://www.4kdownload.com/products/product-youtubetomp3

==> Upgrading 4k-youtube-to-mp3 to 3.12.3.3680
==> Backing up metadata
==> Downloading https://dl.4kdownload.com/app/4kyoutubetomp3_3.12.3.dmg

curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
Error: Download failed on Cask '4k-youtube-to-mp3' with message: Download failed: https://dl.4kdownload.com/app/4kyoutubetomp3_3.12.3.dmg
==> Restoring old metadata folder
```

**Comment by ran-dall** [comment]
#83481
