### ISSUE TITLE
App source not there for Spotify (not a zip/gz but dmg)

### ISSUE THREAD

**Issue by ppo** [Homebrew/homebrew-cask#84040]
I read the instructions about [`source is not there` error](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/source_is_not_there_error.md) but they are not clear.

I think it would be good to give a bit more details about `manually unpack it`. For `zip`, `gz` and `tar.gz` OK but what about `dmg` files?

I mounted the .dmg file and there is well a `Spotify.app` file at the root, which should be OK regarding the `app 'Spotify.app'` found in the `spotify.rb` cask file. So sorry but I don't understand what's wrong.

#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

`It seems the App source '/usr/local/Caskroom/spotify/latest/Spotify.dmg' is not there.`

#### Command that failed

```
brew cu --yes --all --force
```

#### Output of command with `--force --verbose --debug`

```
==> Upgrading spotify to latest
==> Downloading https://download.scdn.co/Spotify.dmg
Already downloaded: /Users/ppo/Library/Caches/Homebrew/downloads/5ef9b045e7e6dfeb70b32abfa9ca2da11e85c9b27ab7f6403658ddb1fcfdc00a--Spotify.dmg
==> No SHA-256 checksum defined for Cask 'spotify', skipping verification.
==> Installing Cask spotify
==> Purging files for version latest of Cask spotify
Error: It seems the App source '/usr/local/Caskroom/spotify/latest/Spotify.dmg' is not there.
```

**Comment by ppo** [comment]
Weird. It works when I execute `brew cu --yes --all --force --verbose`. But right after, it fails when trying without the `--verbose`.

**Comment by miccal** [comment]
The `url` has changed to `https://download.scdn.co/SpotifyInstaller.zip` which contains an `Install Spotify.app`, so this Cask will need to be changed to include an [`installer manual:`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/installer.md#installer-manual) and a re-worked [`uninstall`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md#uninstall-is-required-for-casks-that-install-a-pkg-or-installer-manual).

**Comment by vitorgalvao** [comment]
> It seems the App source '/usr/local/Caskroom/spotify/latest/Spotify.dmg' is not there.

That shouldn’t be happening, because it shouldn’t be searching for the DMG.

I can’t reproduce your error, installation worked fine for me.

Note we don’t support `brew cu` commands. That’s an external tool, so issues derived from it must be reported to its author. We have an official `upgrade` command, and that’s what we support.

**Comment by ppo** [comment]
For reference [issue on `homebrew-cask-upgrade`](https://github.com/buo/homebrew-cask-upgrade/issues/165)
