### ISSUE TITLE
Better handling of downloading errors due to a firewall

### ISSUE THREAD

**Issue by Kentzo** [Homebrew/homebrew-cask#84182]
### Description of feature/enhancement

Whenever downloading stage fails with an error that suggests a reachability restriction, Homebrew should provide guidance explaining where a package dowloaded through other means can be placed to be recognized by the tool.

### Justification

Some packages cannot be accessed due to URL being blocked by a firewall outside of user's control. While often the user can still reach the package via VPN or Tor it's not immediately clear where to put the package so that `brew [cask] install` can recognize it and bypass downloading.

### Example use case

```
> brew cask -vvv install ghidra
==> Caveats
ghidra requires Java 11+. You can install the latest version with:
  brew cask install adoptopenjdk

==> Downloading https://www.ghidra-sre.org/ghidra_9.1.2_PUBLIC_20200212.zip

curl: (22) The requested URL returned error: 403 
Error: Download failed on Cask 'ghidra' with message: Download failed: https://www.ghidra-sre.org/ghidra_9.1.2_PUBLIC_20200212.zip
```

In that case the downloading is blocked due to origin of the request. However it's possible to bypass the downloading stage: the user just needs to put the package obtained through other means at `$(brew --cache ghidra)`. Thus it would be helpful if Homebrew added the following lines to its output:

```
curl: (22) The requested URL returned error: 403 
Error: Download failed on Cask 'ghidra' with message: Download failed: https://www.ghidra-sre.org/ghidra_9.1.2_PUBLIC_20200212.zip

If you have that file already downloaded just put that while at [...] such as it's owned by [...] and its file mode is at least [...], and then re-run installation.
```

**Comment by miccal** [comment]
If a manual download is required, why not just install it manually? The main purpose of `homebrew-cask` is to install applications with minimal user input, and doing something like this would defeat this purpose, no?

**Comment by Kentzo** [comment]
It's not really a manual _installation_, it's manual _downloading_. I'd still prefer a package manager installation:

1. At the very least you get notifications about updates
2. SHA is automatically checked
3. Uninstallation is automatically handled
4. People happen to move and travel. Firewall restriction can be temporal.

**Comment by vitorgalvao** [comment]
This is a too-specific issue that almost nobody runs into. We might consider a PR, but I doubt anyone on the team would want to work on this.

**Comment by Kentzo** [comment]
Out of curiosity, do you collect some metric that could show whether this happen?
