### ISSUE TITLE
List of some casks that should have auto_updates set to true but don't

### ISSUE THREAD

**Issue by Zialus** [Homebrew/homebrew-cask#84190]
The following casks can auto-update, but don't have the option set to true

```
farrago
geekbench
insomnia-designer
omniplan
piezo
```

**Comment by miccal** [comment]
@Zialus please open a [pull request](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md) to add an `auto_updates true` for each of these, thanks.
