### ISSUE TITLE
Upgrading Apps removes file Tags

### ISSUE THREAD

**Issue by brandonjp** [Homebrew/homebrew-cask#84268]
When I run `brew cask upgrade` it removes any Spotlight/Finder tags that were on the file. Comments remain, but Tags do not. 

Is this known, intended, expected? 

![CleanShot 2020-06-12 at 13 14 35@2x](https://user-images.githubusercontent.com/199599/84534039-d8372100-acae-11ea-8743-a5be74cb475e.png)

**Comment by vitorgalvao** [comment]
> Is this known, intended, expected?

Yes. The way we upgrade is by uninstalling a version (effectively removing it from its place) and installing the new one.

In theory we could save that information and replicate it on the upgraded version. In practice that would fail some of the time (e.g. when software switches from an `app` to a `pkg`). We’d likely consider a PR / ideas for this, but I doubt we’d want to work on it ourselves, as the use case is too specific.

**Comment by vitorgalvao** [comment]
Closing due to lack of interest.
