### ISSUE TITLE
“Dropbox.app” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by williamsmj** [Homebrew/homebrew-cask#85170]
#### General troubleshooting steps

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

I get this error message when I open Dropbox.app after installing it with `brew cask install dropbox`:

> “Dropbox.app” cannot be opened because the developer cannot be verified.
> macOS cannot verify that this app is free from malware.
> This file was downloaded on an unknown date.

![Screen Shot 2020-06-29 at 15 47 24](https://user-images.githubusercontent.com/370930/86063778-77367980-ba20-11ea-8c89-4d030ba1732b.png)

I've followed [the instructions here](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/the_app_cant_be_opened.md) to open the app using "Open" from the right-click menu, but I get the same dialog immediately (no option to override).

I have cask installed a number of other applications, which all launch fine:

```
$ brew cask list -1
font-source-code-pro
netnewswire
nvalt
psequel
sekey
syncthing
```

#### Command that failed

`brew cask install dropbox`

#### Output of command with `--force --verbose --debug`

```
$ brew cask install dropbox --force
Updating Homebrew...
==> Downloading https://www.dropbox.com/download?plat=mac&full=1
==> Downloading from https://clientupdates.dropboxstatic.com/dbx-releng/client/D
######################################################################## 100.0%
==> No SHA-256 checksum defined for Cask 'dropbox', skipping verification.
==> Installing Cask dropbox
==> Moving App 'Dropbox.app' to '/Applications/Dropbox.app'.
🍺  dropbox was successfully installed!
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew Version
2.4.2-55-g84f3dc4
==> macOS
10.15.5
==> SIP
Enabled
==> Java
N/A
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3600 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1547 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.40.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/usr/local/bin/bash"
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/cask-fonts
homebrew/core
```

**Comment by miccal** [comment]
Does this also happen when you install `Dropbox` manually?

**Comment by williamsmj** [comment]
False alarm, sorry. Turns out Dropbox is blocked by IT. Yay IT.
