### ISSUE TITLE
Process `zap.early_script` before `uninstall.launchctl`

### ISSUE THREAD

**Issue by Saviq** [Homebrew/homebrew-cask#85498]
### Description of feature/enhancement

When using `brew cask zap …`, `uninstall` is implicitly called _before_ `zap`. I believe all `uninstall.*` stanzas should be merged with the corresponding ones in `zap.*`, and processed together, in [the documented order](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md#summary-of-keys).

### Justification

Consider the case when `zap`ping a cask requires the service to do some initial cleanup. The implicit `uninstall.launchctl` processing will remove the service before `zap.early_script` gets invoked.

### Example use case

[Multipass](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/multipass.rb) may optionally use VirtualBox as the VM backend, and `brew cask zap multipass` should remove those. But the service is stopped through `uninstall.launchctl`, so even in `zap.early_script` it's too late.

**Comment by miccal** [comment]
As far as I am aware, the `zap` stanza is used to remove files and folders only and is not used to run any scripts -- can you please explain in more detail the problem you are experiencing?

**Comment by Saviq** [comment]
Hi, according to [the `zap` docs](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md#zap-stanza-syntax):
> The form of zap stanza follows the [`uninstall` stanza](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md). All of the same directives are available.

I don't know what more I can add, there's two "modes" that you can uninstall Multipass - non-, and -destructive to user data, so that maps quite nicely to `uninstall` and `zap`. But as far I can tell, there's currently no way to use it that way, since `uninstall` is always called before `zap`.

**Comment by miccal** [comment]
So if I understand correctly, you want to call `zap` _without_ calling `uninstall`?

**Comment by vitorgalvao** [comment]
> Consider the case when `zap`ping a cask requires the service to do some initial cleanup.

That cleanup should be done in `uninstall`, likely.

> [Multipass](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/multipass.rb) may optionally use VirtualBox as the VM backend, and `brew cask zap multipass` should remove those.

“Those” what? We’re not going to break a Virtualbox installation on the `zap` of another cask that may optionally have used it. Yes, `zap` can remove things that were installed by other apps, but within reason.

> So if I understand correctly, you want to call `zap` _without_ calling `uninstall`?

If that’s what you’re asking, we have no plans to do it.

**Comment by Saviq** [comment]
>> So if I understand correctly, you want to call `zap` _without_ calling `uninstall`?
> If that’s what you’re asking, we have no plans to do it.

No, we'd need things to be called in this order:
- `uninstall.early_script`
- `zap.early_script`
- `uninstall.launchctl`
- `zap.launchctl`
- etc.

So interleave each _step_ of `uninstall.*` with the corresponding step from `zap.*`, rather than going through all of `uninstall.*` first.

> That cleanup should be done in `uninstall`, likely.

I'd say the split between `uninstall` and `zap` maps quite nicely to _non-destructive_ and _destructive_.

> “Those” what? We’re not going to break a Virtualbox installation on the `zap` of another cask that may optionally have used it. Yes, `zap` can remove things that were installed by other apps, but within reason.

No, the exact case is: we register VMs and VM disks with VirtualBox, `brew cask uninstall` does not remove them to avoid data loss, but `brew cask zap` would. It's not just about removing files, for that we'd need the Multipass daemon to still be running, so `zap.early_script` felt like the right place - but the daemon is already stopped and removed through `uninstall.launchctl`.

**Comment by vitorgalvao** [comment]
I understand your request, but I also think it’s too specific to bother with officially. Almost no cask would benefit from it.

If you’d be willing to make a PR for it, we can consider it and I’ll ping other maintainers to see if they think the feature has merit and would be willing to review it. But if you’re not willing / able to do the legwork, we can close this now.

**Comment by vitorgalvao** [comment]
Closing for lack of reply.
