### ISSUE TITLE
remove Nocturnal?

### ISSUE THREAD

**Issue by deadlyicon** [Homebrew/homebrew-cask#85501]
### Description of feature/enhancement

Should https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/nocturnal.rb be removed from Homebrew?

### Justification

![image](https://user-images.githubusercontent.com/8385/86829010-c8f68980-c048-11ea-8b23-e7147b5b5677.png)

### Example use case

```sh
brew cask install nocturnal
open /Applications/Nocturnal.app
```

**Comment by ran-dall** [comment]
I'm not getting anything: https://www.virustotal.com/gui/file/a66c59daa1d1c59e5403aee4eb868a3967f1bdb4d90033fa3ee692bffd7db0b9/detection/f-a66c59daa1d1c59e5403aee4eb868a3967f1bdb4d90033fa3ee692bffd7db0b9-1573281063

**Comment by deadlyicon** [comment]
So this Mac OS level warning is of no concern to Hombrew? That does not inspire confidence.

**Comment by ran-dall** [comment]
@deadlyicon Yes, well sometimes it does give out false positives based on certain behaviors an app performs. In this case, the `sha256` hasn't changed in a while, and it's been checked on VirusTotal several times, so I fail to see where we should be concerned.

**Comment by vitorgalvao** [comment]
> So this Mac OS level warning is of no concern to Hombrew? That does not inspire confidence.

From reports I’ve seen, it seems that macOS can straight up throw that warning just because an app isn’t signed and notarised.

Yes, malware is of concern to us—which you can figure out pretty quickly by searching—but this case seems to require a bit more proof.
