### ISSUE TITLE
Duplicate pkg files in Caskroom and brew --cache

### ISSUE THREAD

**Issue by koallen** [Homebrew/homebrew-cask#85669]
When installing a cask, brew downloads the `.pkg` file into `brew --cache` directory. After installing the cask, another copy would appear under `/usr/local/Caskroom` (I checked and this is not a symlink).

For normal casks, this is probably fine, but for things like mactex, two identical pkg file basically takes up 8GB of space. I read from other issues that the pkg file is kept such that in case of an upgrade failure, the old version could be reinstalled. It makes sense, but I wonder if it could have better integration with the brew cache such that there will be only 1 copy on the disk?

Meanwhile, I want to know if I don't mind downloading it again, can I remove the pkg inside `/usr/local/Caskroom`?

**Comment by miccal** [comment]
From `brew cleanup --help`:
```
-bash-5.0.17- /Users/miccal (29) [> brew cleanup --help
Usage: brew cleanup [options] [formula|cask]

Remove stale lock files and outdated downloads for all formulae and casks, and
remove old versions of installed formulae. If arguments are specified, only do
this for the given formulae and casks. Removes all downloads more than 120 days
old. This can be adjusted with HOMEBREW_CLEANUP_MAX_AGE_DAYS.

        --prune                      Remove all cache files older than specified
                                     days.
    -n, --dry-run                    Show what would be removed, but do not
                                     actually remove anything.
    -s                               Scrub the cache, including downloads for
                                     even the latest versions. Note downloads
                                     for any installed formulae or casks will
                                     still not be deleted. If you want to delete
                                     those too: rm -rf "$(brew --cache)"
        --prune-prefix               Only prune the symlinks and directories
                                     from the prefix and remove no other files.
    -v, --verbose                    Make some output more verbose.
    -d, --debug                      Display any debugging information.
    -h, --help                       Show this message.
```
So you can run `rm -rf "$(brew --cache)"` to remove one of them.

**Comment by vitorgalvao** [comment]
> Meanwhile, I want to know if I don't mind downloading it again, can I remove the pkg inside `/usr/local/Caskroom`?

You can remove both, as long as you understand the risk that if you encounter a failed upgrade you might not be able to revert to the version you had.
