### ISSUE TITLE
Reopen #85672

### ISSUE THREAD

**Issue by iMonZ** [Homebrew/homebrew-cask#85680]
#85672 This pull request closed because the version is not on the website!
The version is on the website but not inside of the changelog:
https://mackie100projects.altervista.org/download/occ/

**Comment by miccal** [comment]
Perhaps re-submit and change the `appcast` to `https://mackie100projects.altervista.org/download/occ/` which lists the newer version.

**Comment by iMonZ** [comment]
Thanks #85743

**Comment by vitorgalvao** [comment]
Please don’t make issues requesting to open other issues. Closing does not lock the conversation, nothing stops you from commenting there.
