### ISSUE TITLE
assistance with added casks

### ISSUE THREAD

**Issue by ans87gh** [Homebrew/homebrew-cask#85704]
Hi all. I submitted 3 casks (icollections, slimhud, and windocd) created pull requests. All returned with runs failed. I am not sure what was done wrong, and how to correct it.

Here are the pull requests
https://github.com/Homebrew/homebrew-cask/pull/85702
https://github.com/Homebrew/homebrew-cask/pull/85703
https://github.com/Homebrew/homebrew-cask/pull/85701

I'm sure I'm doing something wrong. Just don't know what that is. And this is the first time submitting, let alone using GitHub more intimately (to me, this is deeper than I have gone before). Any assistance would be appreciated. Thanks.

**Comment by miccal** [comment]
@ans87gh I have reviewed each of your PR's.

**Comment by ans87gh** [comment]
@miccal .. so  reworked all three, and they returned failed again. Could you point out and help me resolve the mistake? Thanks.

**Comment by miccal** [comment]
@ans87gh all three of your PR's now have a bunch of unrelated commits -- are you using `git` via the command line to submit them?

**Comment by ans87gh** [comment]
@miccal .. yes the CLI .. I thought I had to do revisions. Was I mistaken?

**Comment by miccal** [comment]
Ok, I think you need to rebase and force-push -- lest try this on any one of your open PR's:

Go into the casks directory, and 
```
git checkout <YOUR_BRANCH_NAME>
```
and make any changes to the cask you are submitting (if required), then run
```
git rebase --interactive origin/master
```
which _should_ open a file in your `editor` with all the commits you submitted from your branch, followed by the following information:
```
# Commands:
# p, pick <commit> = use commit
# r, reword <commit> = use commit, but edit the commit message
# e, edit <commit> = use commit, but stop for amending
# s, squash <commit> = use commit, but meld into previous commit
# f, fixup <commit> = like "squash", but discard this commit's log message
# x, exec <command> = run command (the rest of the line) using shell
# b, break = stop here (continue rebase later with 'git rebase --continue')
# d, drop <commit> = remove commit
# l, label <label> = label current HEAD with a name
``` 
Change any _unrelated_ commits to the file you are submitting to `drop`, leave the first related commit to the file you are submitting as `pick`, and any further related commits to the file you are submitting to `squash`, then run
```
git push --force
```
This _should_ results in a single commit with a single added cask file.

**Comment by ans87gh** [comment]
@miccal So I did as you said, but when doing git push --force, returning 

git push origin HEAD:<name-of-remote-branch>

**Comment by miccal** [comment]
Try `git push --force ans87gh <YOUR_BRANCH_NAME>` instead of just `git push --force`.

**Comment by ans87gh** [comment]
@miccal worked for collections .. will do for other 2 now; if you could, please followup to confirm done right. Thanks a bunch.

**Comment by ans87gh** [comment]
@miccal and just did the same for the remaining 2.

**Comment by miccal** [comment]
@ans87gh I do not see any updates in your three PR's?

**Comment by ans87gh** [comment]
@miccal 🤦‍♂️😳 .. I'll be honest: I'm absolutely lost right now and have no idea where to go from here. would it be any trouble if I ask you to resolve them. I feel any more manipulation on my part ill just make things more convoluted.

**Comment by miccal** [comment]
@ans87gh I am not have write access, so I cannot -- I would suggest that you close your three PR's, delete your local branches, and try submitting them again.

**Comment by ans87gh** [comment]
will do .. and ill do it based on your previous comments for direction. If you could, please keep an eye out for them in the next hr or 2 to see if they work. Thanks.

**Comment by miccal** [comment]
No problem @ans87gh, and don't feel bad -- `git` has a bit of a learning curve.

**Comment by ans87gh** [comment]
@miccal Thanks! .. learning curve is a nice way of putting it .. but when u start visualizing it and understanding some of the language, it makes much more sense .. but then you have to understand the rules and conditions etc etc .. anyways, pushed all three. Could you look at them and lmk.

**Comment by ans87gh** [comment]
@miccal done! lets wait and see!! the help is much appreciated.

**Comment by miccal** [comment]
@ans87gh your three PR's look good :)

**Comment by ans87gh** [comment]
@miccal 🎉
