### ISSUE TITLE
Intel Power Gadget: 3.7.0 but same sha256

### ISSUE THREAD

**Issue by adavidzh** [Homebrew/homebrew-cask#85818]
I just found that there is a [`3.7.0` version](https://software.intel.com/content/www/us/en/develop/articles/intel-power-gadget.html#attachment-heading) and was about to update the recipe.

For some reason the `sha256` for the `3.7.0` `dmg` file is identical to [what is presently in the recipe](https://github.com/Homebrew/homebrew-cask/blob/8714f14906deaebc60032c64b7ace280ed1e5445/Casks/intel-power-gadget.rb#L2-L5).
This is very strange and I wonder if the present `3.6.0` label is incorrect.

I don't know how to solve this either way (present label wrong vs new version with same `sha`)and I thought it would be good to flag it.

**Comment by ran-dall** [comment]
@adavidzh We already looked into this. The `.plist` file that's included with the download denotes `3.6.0`; therefore no change is required. It's just a fluke on their side.
