### ISSUE TITLE
x48 doesn't run as-is on modern macOS

### ISSUE THREAD

**Issue by steakknife** [Homebrew/homebrew-cask#86110]
It needs a patch and then it works. ~~PR incoming.~~ (Actually, I'm not familiar with the DSL to modify an .app or if it's even allowed/possible.)

## The fix

Set the contents of the file `x48.app/Contents/Resources/script` to the following and it works fine:

```
if ! pgrep -q Xquartz; then
  open -a xquartz
  sleep 2
fi
./x48 +terminal -display :0
```

**Comment by vitorgalvao** [comment]
> or if it's even allowed

It’s not. It’s also not a very popular cask, so if it doesn’t work anymore might as well remove it.

Thank you for the report.

**Comment by steakknife** [comment]
I'll just close this issue and leave it; people will find this issue and
it's an easy fix.

Popularity isn't everything, after all; if it were, there would be a Kim
Kardashian shell written in Java. ;-)
