### ISSUE TITLE
daemon-tools: old URL no longer updated, new URL is unstable

### ISSUE THREAD

**Issue by i0ntempest** [Homebrew/homebrew-cask#86151]
Recently DAEMON Tools had a new appcast: https://secure.disc-soft.com/DAEMONToolsLite/appcast.xml
And the old URL in the cask file seems no longer updated, plus there isn't a stable URL to download the latest release. So what should we do about this cask? Can we use a `url do` block to parse this xml? There's a lot of people using this so I guess we can't simply delete it.

**Comment by miccal** [comment]
```
-bash-5.0.18- /Users/miccal (29) [> curl -I https://www.daemon-tools.cc/downloads/dtMacLite?direct=1
HTTP/1.1 302 Found
Server: nginx/1.10.3
Date: Sat, 18 Jul 2020 01:12:07 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
X-Powered-By: PHP/7.1.33
Set-Cookie: PHPSESSID=kl8evsu16u2tkpvv1qpamhh6j5; expires=Sun, 19-Jul-2020 01:12:07 GMT; Max-Age=86400; path=/; domain=.daemon-tools.cc
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Location: https://www.daemon-tools.cc/downloads/dtMacLite?direct=1
```
The `Set-Cookie: PHPSESSID=kl8evsu16u2tkpvv1qpamhh6j5` constantly changes.

Also see https://github.com/Homebrew/homebrew-cask/issues/69608#issuecomment-534704963

This cask may have to be removed.

**Comment by vitorgalvao** [comment]
> Can we use a `url do` block to parse this xml?

No, that’s only for nightlies and the like. [It’s documented](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#some-providers-block-command-line-downloads).

> There's a lot of people using this

Not that many.

```
daemon-tools
30 days: 24 (#1561)
90 days: 43 (#2434)
365 days: 155 (#2573)
Age: 1320 days (added 2016, December 08)
```

>  so I guess we can't simply delete it.

Sure we can. If the vendor is making CLI downloads hard or impossible on purpose, that’s neither our fault nor responsibility to circumvent. Doing so would lead to a never-ending game of cat and mouse.

The solution is to ask upstream to provide downloads we can use, not have us continually bend over backwards to try to go against their wishes.

Opened https://github.com/Homebrew/homebrew-cask/pull/86256. Will leave open for a while in case anyone comes up with a solution.

**Comment by i0ntempest** [comment]
Welp, that's a shame cuz I use this software a lot. I'll contact the vendor to see if they're willing to do anything, last time I contacted them about the broken appcast they came back pretty quick.

**Comment by vitorgalvao** [comment]
> I'll contact the vendor to see if they're willing to do anything

That’s why I’m not merging the removal yet. Please get back to us either way.

**Comment by i0ntempest** [comment]
![IMG_1440](https://user-images.githubusercontent.com/16017904/88108595-21fd0c00-cb77-11ea-95e4-b093149ae068.png)
Guess we'll have to remove it.

**Comment by ran-dall** [comment]
@i0ntempest Outstanding follow thru. I'll let @vitorgalvao do the honors but just wanted to say something.
