### ISSUE TITLE
If an appcast is from Github releases, check if submitted version is stable

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-cask#86192]
With `brew cask audit --appcast`, we do a simple check of “is the text in `version` somewhere in the contents of the `appcast` url?”.

That’s insufficient for Github feeds that have pre-releases, because those will pass the check.

Solution: on the `audit --appcast` check, if the URL is from Github releases, only grab versions marked as `stable` and check against those.

Ideally we’d add a `disable_smart_check: true` parameter to get back the default behaviour when we don’t mind pre-releases (e.g. casks in [homebrew/cask-versions](https://github.com/Homebrew/homebrew-cask-versions), or casks in the main repo that don’t have a stable version yet).

**Comment by neeldug** [comment]
Would this be implemented in the `SharedAudits.github(user, repo)` method or elsewhere? As I'd assume the implementation would occur solely in the github audit, or a separate method that's called by the github audit?

**Comment by vitorgalvao** [comment]
`SharedAudits` are—if I’m not mistaken—exclusively for notability checks, which don’t apply here.

This should be implemented in the `cask` `audit` section of the `--appcast` flag (which does not exist on formulae).

**Comment by core-code** [comment]
support for this would be awesome. unfortunately the github release atom feed doesn't store the latest/pre-release status. however the API can be used.

e.g. 
`https://api.github.com/repos/Gcenx/WineskinServer/releases/latest
`lists 1.8.4 but not 1.8.4.2 which is marked as pre-release

**Comment by vitorgalvao** [comment]
That brings up a nice point. Maybe we could just default to using the API endpoint as an appcast, and the atom feed when pre-releases are accepted (no stable version available yet, or in [homebrew/cask-versions](https://github.com/Homebrew/homebrew-cask-versions)).

**Comment by core-code** [comment]
one problem here is that the API is rate limited. without credentials the limit is low, with them a bit higher. i can add something to our system to deal with these appcasts (if they are added) but it would be bad if travis would run into the limit when doing audits

**Comment by vitorgalvao** [comment]
> one problem here is that the API is rate limited.

Fair point. That’s problematic for the feature in general, because we’d need to use the API for that check anyway, essentially converting atom feeds to API  requests.

On the other hand, checks are running on GitHub’s CI and some Homebrew maintainers work at GitHub, so we if we bump into the limits we may be able to solve that problem.

**Comment by SMillerDev** [comment]
> SharedAudits are—if I’m not mistaken—exclusively for notability checks, which don’t apply here.

They are for any shared audits. And homebrew/core already has a similar check so this would be easy to implement by just moving the code.
