### ISSUE TITLE
Do not overwrite files in /usr/local/bin without warning when installing MacVim.app

### ISSUE THREAD

**Issue by williamsmj** [Homebrew/homebrew-cask#86221]
### Description of feature/enhancement

During `brew cask install macvim`, symlinks to /Applications/MacVim.app/Contents/bin/mvim are installed in /usr/local/bin:

```
/Applications/MacVim.app/Contents/bin/mvim -> gview (Binary)
/Applications/MacVim.app/Contents/bin/mvim -> gvim (Binary)
/Applications/MacVim.app/Contents/bin/mvim -> gvimdiff (Binary)
/Applications/MacVim.app/Contents/bin/mvim -> mview (Binary)
/Applications/MacVim.app/Contents/bin/mvim -> mvimdiff (Binary)
/Applications/MacVim.app/Contents/bin/mvim -> view (Binary)
/Applications/MacVim.app/Contents/bin/mvim -> vim (Binary)
/Applications/MacVim.app/Contents/bin/mvim -> vimdiff (Binary)
/Applications/MacVim.app/Contents/bin/mvim -> mvim (Binary)
```

1. There should be a warning about this if it will overwrite existing files (which it will if the user has previously installed vim)
2. Creating these symlinks is a reasonable default, but it should be optional.

### Justification

1. There must be a warning. These symlinks overwrite existing files. Depending on how the files that get overwritten were created, this may result in data loss. (In that sense, this is a bug report, not a feature request.)
2. Creating these links should be optional. There are lots of situations in which a user might not want these symlinks to exist (e.g. they have already installed vim and don't want `vim` on the command line to run the build of vim that happens to be bundled in MacVim.app).

**Comment by vitorgalvao** [comment]
Making it optional isn’t a good solution, because that requires yet another option to support at installation time for a situation that almost never happens.

https://github.com/Homebrew/homebrew-cask/pull/86222

**Comment by williamsmj** [comment]
Thanks for the quick response. I think the solution in #86222 is a shame.

There is no reason from the user's point of view to forbid the coexistence of the vim brew and the macvim cask, other than the cask's insistence on overwriting the brew's files, which is something MacVim.app does not need to do in order to function. Wanting both brew vim and macvim cask is a pretty reasonable request. While macvim comes with a handy GUI, it uses an older version of vim itself and is generally kept less up to date.

There are patterns to handle this situation throughout the brew project, e.g. caveats that inform the user of additional post-install steps they may take to set up links or configure their shell, `brew cask install --links` options etc. I understand setting these up are not free, and simply declaring a conflict is the easiest solution, but would you consider another PR?

**Comment by vitorgalvao** [comment]
> So I disagree with "almost never happens". It happened to me! :-)

Before it happened to you, I wouldn’t have needed to say “almost”. And the point was that it seldom happens in the context of all casks. You’re suggesting an option that so far only a single cask would take advantage of, and even then only sometimes.

> but would you consider another PR?

Doing what?

**Comment by williamsmj** [comment]
It has affected anyone installed the vim brew (or who has installed vim in /usr/local in any other way) and the macvim cask. I doubt I'm the only person. In any case, as I say, there is no reason to conflict macvim cask and vim brew.

My suggestion is a PR that either:

- Does not make the links, but gives the commands to make them as a caveat that is shown to cask users who install macvim.
- Adds a `--without-links` option to the macbrew that installs the macvim cask without these links (off by default, so retaining the current behaviour).

Both of these small changes would be an improvement over simply refusing to install macvim. I'm happy to do the work in either case if they're likely to get through review.

**Comment by vitorgalvao** [comment]
Just remembered and checked the docs. `--no-binaries` already exists.

**Comment by williamsmj** [comment]
Ah, thanks for #86248.
