### ISSUE TITLE
Cask uninstall behavior question

### ISSUE THREAD

**Issue by targendaz2** [Homebrew/homebrew-cask#86426]
I'd like to update the `zoomus` and `zoom-for-it-admins` casks to only uninstall if the app is not actively being used in a meeting. The goal being to prevent the app from force quitting if someone's actively using it. It looks like doing so would require creating a shimscript with the following that would be called in the uninstall stanza as an `early_script`:
```
#!/bin/bash

if [[ "$(/usr/bin/pmset -g | /usr/bin/grep ' sleep')" == *"coreaudiod"* ]]; then
    exit 1
fi

exit 0
```

Is this supported/encouraged? I don't see any casks doing something like this and worry that this oversteps the bounds of what Homebrew is designed to do.

**Comment by miccal** [comment]
Might be better to use:
```
if [[ "$(/usr/bin/pmset -g | /usr/bin/grep ' sleep')" == *"zoom.us"* ]]; then
```
When running a Zoom meeting on my machine `pmset -g` lists:
```
displaysleep 10 (display sleep prevented by zoom.us)
```

**Comment by vitorgalvao** [comment]
> Is this supported/encouraged?

Nope. Quit the opposite, we try to quit the apps.

**Comment by targendaz2** [comment]
@vitorgalvao noted, thank you!
