### ISSUE TITLE
Remove Application Support when uninstalling

### ISSUE THREAD

**Issue by Matt-Gleich** [Homebrew/homebrew-cask#86427]
### Description of feature/enhancement

When uninstalling a cask uninstall the Application Support for the application

### Justification

There is a lot of leftover artifacts that I just found when looking there. When uninstalling a cask it should be like it was never there IMO. Helpful for someone like me that tries about a bunch of different apps all the time with homebrew.

### Example use case

Used when uninstalling.

**Comment by vitorgalvao** [comment]
That’s what [`zap`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md) is for. Each cask needs their own.
