### ISSUE TITLE
error command not found

### ISSUE THREAD

**Issue by paowiicarina** [Homebrew/homebrew-cask#86450]
![15955198164678710217502592590868](https://user-images.githubusercontent.com/41752060/88308922-ed6f8880-cd0d-11ea-871e-ce0650784ea3.jpg)
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

{{replace this}}

#### Command that failed

```
{{replace this}}
```

#### Output of command with `--force --verbose --debug`

```
{{replace this}}
```

#### Output of `brew cask doctor`

```
{{replace this}}
```

#### Output of `brew tap`

```
{{replace this}}
```

**Comment by vitorgalvao** [comment]
The installation failed because you’re missing system tools. Naturally anything after will fail. You want [Homebrew/brew](https://github.com/Homebrew/brew).
