### ISSUE TITLE
kafka-tool cask: application does not work when JDK11 is already installed

### ISSUE THREAD

**Issue by timothybasanov** [Homebrew/homebrew-cask#86628]
#### Description of issue

Kafka Tool cask installs the app successfully and wars that it needs JDK8 to run correctly.
I already have JDK11 installed.
When I try to run an app it fails with some of the rendering of data.

Installing the same application from the web site works just fine as application packages JRE8 already.

#### Command that failed
```sh
brew cask install kafka-tool
```

**Comment by vitorgalvao** [comment]
> Kafka Tool cask installs the app successfully and wars that it needs JDK8 to run correctly.
I already have JDK11 installed.

It says it needs “8”, nor “8 or later”.

> Installing the same application from the web site works just fine as application packages JRE8 already.

If you can update the cask to use that app instead, that’d work.

> When I try to run an app it fails with some of the rendering of data.

But otherwise there’s nothing we can do. The java version warning is just that, a warning. It’s up to the user to fulfil the requirement.

**Comment by timothybasanov** [comment]
I think that cask already downloads the right DMG. 
Not sure what is the difference that causes this issue.

**Comment by miccal** [comment]
@timothybasanov can you please test if the [changes I made](https://github.com/Homebrew/homebrew-cask/pull/86632) work for you, thanks.
