### ISSUE TITLE
Show app icons in brew info

### ISSUE THREAD

**Issue by KhushrajRathod** [Homebrew/homebrew-cask#86965]
### Description of feature/enhancement

Display the application icon in `brew info` - There are plenty of libraries to show images in supporting terminals

### Justification

Many users relate to and identify apps using their icons, this makes it easier to actually know which app you're talking about without command clicking the website

### Example use case

> - User: *sees FOSS Gifski project by Sindresorhus*
> - User: Ooohhh let's download this!
> - User: `brew search gifski`
> - Brew: 
==> Formulae
gifski
> - User: `brew info gifski`
> - Brew: 
gifski: stable 0.10.4 (bottled)
Highest-quality GIF encoder based on pngquant
> - User: brew install gifski

User gets https://github.com/ImageOptim/gifski instead of https://github.com/sindresorhus/Gifski - although Sindresorhus/Gifski is a GUI for ImageOptim/gifski

**Comment by vitorgalvao** [comment]
That would require us to host, gather, and update icons for every app, which is not a good use of our time or resources.

> User gets https://github.com/ImageOptim/gifski instead of https://github.com/sindresorhus/Gifski - although Sindresorhus/Gifski is a GUI for ImageOptim/gifski

If you understand the difference between Homebrew and Homebrew Cask, and that the former doesn’t want to provide GUI apps, that’s never a problem. In addition, [we’re not a discoverability service](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/not_a_discoverability_service.md).
