### ISSUE TITLE
plex-media-server  overwrites symlink to `pms`-binary in homebrew-core.

### ISSUE THREAD

**Issue by jottr** [Homebrew/homebrew-cask#87304]
`plex-media-server` overwrites the symlink to the `pms`-binary which already exists in `homebrew-core` as the executable name for [Practical Music Search](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/pms.rb).

https://github.com/Homebrew/homebrew-cask/blob/abc2a7ce4182949ee5e663d5e96d1ee4d77d095b/Casks/plex-media-server.rb#L13
The installation procedure overwrites of the`plex-media-server` cask overwrites the [`/usr/local/bin/pms`-symlink](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/pms.rb#L23) without asking/notifying the user, thus breaking _Practical Music Search_'s `pms` executable.

**Comment by miccal** [comment]
To overcome this problem the `target:` just needs to be re-named to something else -- I am thinking `plexms`?

The Plex support article [here](https://support.plex.tv/articles/201242707-plex-media-scanner-via-command-line/) recommends an `alias` as follows:
```
alias pms="/Applications/Plex Media Server.app/Contents/MacOS/Plex Media Scanner"
```
but it can be called something else.

@jottr any thoughts and/or suggestions?

**Comment by jottr** [comment]
`plexms` sounds good to me.
It's probably a good idea to warn users of the name change. Maybe in a [`Caveats`](https://rubydoc.brew.sh/Formula.html#caveats-instance_method)-section?

**Comment by vitorgalvao** [comment]
> It's probably a good idea to warn users of the name change. Maybe in a [`Caveats`](https://rubydoc.brew.sh/Formula.html#caveats-instance_method)-section?

Those caveats only linger. That section is not meant for temporary user warnings.

https://github.com/Homebrew/homebrew-cask/pull/87340.

**Comment by reitermarkus** [comment]
> cask overwrites the [`/usr/local/bin/pms`-symlink](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/pms.rb#L23) without asking/notifying the user

I think this should be considered a bug.

**Comment by miccal** [comment]
@reitermarkus please also see https://github.com/Homebrew/homebrew-cask/issues/86221 for a similar issue.

**Comment by miccal** [comment]
@reitermarkus I do not quite understand why [these lines of `Library/Homebrew/cask/artifact/symlinked.rb`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/artifact/symlinked.rb#L47-L51) are not detecting this issue?

**Comment by vitorgalvao** [comment]
> I think this should be considered a bug.

Agreed. I’m pretty sure we already had this check, so it’s a regression as well.

Still going ahead with https://github.com/Homebrew/homebrew-cask/pull/87340 because there’s not a strong reason to make this conflict with an unrelated cask when all upstream does is suggest an alias.

**Comment by vitorgalvao** [comment]
> I do not quite understand why [these lines of `Library/Homebrew/cask/artifact/symlinked.rb`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/artifact/symlinked.rb#L47-L51) are not detecting this issue for the `binary`?

From the `if` line, it seems that only triggers if the target is *not* a symlink, which in this case it is.

**Comment by miccal** [comment]
I have a simple idea to rectify this -- how about adding the following [after these lines of `Library/Homebrew/cask/artifact/symlinked.rb`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/artifact/symlinked.rb#L47-L51):
```
if target.exist? && target.symlink?
  raise CaskError,
        "something about passing the '-no-binaries' option"
end
```
Thoughts?

**Comment by vitorgalvao** [comment]
It’d be useful to remember what was the rationale behind checking if the target is a symlink. It might make sense to remove the second part of that conditional and be done with it.

**Comment by miccal** [comment]
That is a good point -- I suspect that the first part of the conditional with `!target.symlink?` was to ensure that `brew` does not attempt to overwrite anything in `/usr/local/bin` that was _not_ put there by `brew` -- perhaps the `CaskError` message can be improved here to reflect this?

For instance, on my machine I have non-symbolic-link things in `/usr/local/bin` that were put there by `python3 -m pip install`. Since the Python Package Index is _vast_, this is a good thing to check.

Adding a second one with a `target.symlink?` conditional could then have its own `CaskError` message, possibly mentioning the `--no-binaries` option as I suggested. I think this would be useful -- I was not aware of this option until [you mentioned it](https://github.com/Homebrew/homebrew-cask/issues/86221#issuecomment-660756119), and then we could dispense with a `caveat` like [this one](https://github.com/Homebrew/homebrew-cask/pull/86248).

Perhaps @reitermarkus could also shed some more light on the reason for the symlink check.

**Comment by reitermarkus** [comment]
I'm not sure why the check is there. I guess we can remove it, since we actually want an error instead of overwriting a valid symlink.

**Comment by miccal** [comment]
Thank you @reitermarkus.

So how about something like this:
```
if target.exist? && !target.symlink?
  raise CaskError,
        "It seems there already exists a file #{self.class.english_article} " \
        "#{self.class.english_name} at '#{target}'; not overwriting."
end

if target.exist? && target.symlink?
  raise CaskError,
        "It seems there already exists a symbolic link #{self.class.english_article} " \
        "#{self.class.english_name} at '#{target}'; not linking. To install the Cask " \
        "without this symbolic link, use the #{Formatter.identifier("--no-binaries")} option."
end


```

**Comment by miccal** [comment]
Or perhaps just:
```
if target.exist?
  raise CaskError,
        "It seems there already exists #{self.class.english_article} " \
        "#{self.class.english_name} at '#{target}'; not overwriting." \
        "Consider installing the Cask using the " \
        "#{Formatter.identifier("--no-binaries")} option."
end
```

**Comment by vitorgalvao** [comment]
> Or perhaps just replace the whole thing with

Yes, that one. But not “consider installing” because that comes across as a recommendation.

**Comment by miccal** [comment]
https://github.com/Homebrew/brew/pull/8370
