### ISSUE TITLE
Prevent homebrew cask to report updates when it's only linting changes

### ISSUE THREAD

**Issue by Porkepix** [Homebrew/homebrew-cask#87343]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue
First of all I'm not aware enough if the issue is about casks only of should be reported in anther more general repository for the whole Homebrew, though I think casks have more often a special versioning and oftentimes does not automatically update as it consider getting updates from the app itself.

When updating homebrew, casks are often reported as having an update, but there's nothing to update on the upgrade we can try after.

This is generally due to linting changes, like https://github.com/Homebrew/homebrew-cask/pull/87307 or another big one we got in the past weeks I don't find back right now, or due to changes on rules like zap one.

It would be quite useful to not report update on applications for this kind of changes, if this is possible.

**Comment by vitorgalvao** [comment]
Linting changes aren’t common. This isn’t an issue.

Other changes may indeed be relevant even if the version doesn’t change, so they’re useful to see.

**Comment by Porkepix** [comment]
@vitorgalvao Imho, zap updates for example aren't worth notifying an update, which result in user running a `brew cask upgrade [formula]`… for end up seeing nothing updates, because there's actually no new release, just zap or linting changes (even a simple url change display an update available during `brew update`!)

**Comment by vitorgalvao** [comment]
I still don’t think this affects (bothers) enough users to warrant the change. That said, I also think this affects both formulae and casks, as you mention above, meaning it should be reported on [Homebrew/brew](https://github.com/Homebrew/brew), which you may want to try (note that repo has a different template that needs to be filled).

**Comment by MikeMcQuaid** [comment]
> I also think this affects both formulae and casks, as you mention above, meaning it should be reported on [Homebrew/brew](https://github.com/Homebrew/brew), which you may want to try (note that repo has a different template that needs to be filled).

It doesn't, actually. Formulae only are reported as "updated" here when the version changes and, when we don't calculate version changes (for performance reasons), we don't show any as "updated". This could (and probably should) be behaviour we adopt for casks?

**Comment by Porkepix** [comment]
> It doesn't, actually. Formulae only are reported as "updated" here when the version changes

This probably happens much less often, but I believe that it happened fore core a couple of days/weeks ago with a big commit that happened. I might be wrong, and have bad memories though.

> and, when we don't calculate version changes (for performance reasons)

For my information, can you give an example of what can this be?

**Comment by MikeMcQuaid** [comment]
> For my information, can you give an example of what can this be?

Whenever `brew update` is run as an autoupdate i.e. before a `brew install`.

**Comment by Porkepix** [comment]
> > For my information, can you give an example of what can this be?
> 
> Whenever `brew update` is run as an autoupdate i.e. before a `brew install`.

Oh, so one can miss updates in such cases? Damn, didn't knew this changed. I thought it was still reporting applications that could be updated.

**Comment by miccal** [comment]
For future reference: https://github.com/Homebrew/brew/pull/8395

**Comment by Porkepix** [comment]
This just happened again with https://github.com/Homebrew/homebrew-cask/pull/87436 : huge amount of updates reported, including most if not all of the installed casks, while no versions changed at all.

**Comment by MikeMcQuaid** [comment]
I was also annoyed by this so opened https://github.com/Homebrew/brew/pull/8693

**Comment by vitorgalvao** [comment]
@miccal Is this solved? Can it be closed?

**Comment by miccal** [comment]
> @miccal Is this solved? Can it be closed?

No I have not done this yet -- it was not as straight-forward as I initially thought, and I have not yet had the time to investigate this further.

**Comment by Porkepix** [comment]
Issue's still here, especially now we got all the updates report just because of the livecheck addition. Or some description edits.

**Comment by vitorgalvao** [comment]
> Issue's still here

The point of the bot is not to find issues we forgot to close after fixing; it’s to point out issues with no momentum.

Bottom line, this isn’t a bug but a small inconvenience that’s low on the list of maintainer priorities. If, at the same time, no outside contributed cares enough about this to fix it, it does us no good to keep it open (quite the contrary, it just makes other issues harder to find).
