### ISSUE TITLE
VMWare Fusion shows Gatekeeper alerts

### ISSUE THREAD

**Issue by ItalyPaleAle** [Homebrew/homebrew-cask#87357]
I installed VMWare Fusion on my MacBook with brew, as a cask. When launching any virtual machine, I get 2 warnings like these from Gatekeeper:

![image](https://user-images.githubusercontent.com/43508/89808910-b52ebf00-daef-11ea-8523-70c0a26b5489.png)

**Comment by vitorgalvao** [comment]
That’s a macOS feature. You’d get the same even if you hadn’t downloaded from us.

**Comment by ItalyPaleAle** [comment]
It can be fixed by the formula by adding a command with "xattr-rc /path/to/file" however. It would make life much easier as those pop up every time I launch a VM.

**Comment by vitorgalvao** [comment]
> It can be fixed by the formula

Cask.

> by adding a command with "xattr -rc /path/to/file" however.

That’s unnecessary, disables an important security feature without user choice, and would be redundant. `curl` downloads (which Homebrew uses) do not quarantine apps, we go to great lengths to provide that.

If you don’t want it, install with the `--no-quarantine` flag. This is explained in the `man` page.

**Comment by ItalyPaleAle** [comment]
> You’d get the same even if you hadn’t downloaded from us.

FWIW, I have just tried re-instaling VMWare Fusion by downloading the DMG from the official website, and now the warnings have disappeared.

I'm not sure that the official installer is doing that brew isn't, but if you could investigate into the issue and offer a fix that works by default it would be really nice. The experience of having to accept 2 warnings every time you boot up a VM is really annoying for users (and prevents things like auto-start) and makes using brew a sub-optimal solution...

**Comment by vitorgalvao** [comment]
> if you could investigate into the issue and offer a fix

I also use VMWare Fusion installed via Homebrew Cask and never saw this. We’d need reliable reproduction steps from you.

**Comment by ItalyPaleAle** [comment]
I got a new laptop, with a fresh install of macOS (no backups restored) and installed Fusion with:

```
brew cask install vmware-fusion
```

That's it

**Comment by ItalyPaleAle** [comment]
Worth pointing out I saw this on my other laptop too after using brew to upgrade VMWare Fusion. I did not experience the issue before, but it started appearing after that. But the fresh install should be easy to repro.

**Comment by vitorgalvao** [comment]
You’re seemingly the only person experiencing this and suggested removing the quarantining attribute above, so use `--no-quarantine`. It’s not a good use of our volunteer time to blindly search for an issue a single user has that has a simple workaround.

Either we get concrete concrete reproduction steps (or a fix) or there’s nothing we can do, especially when you haven’t even filled the issue template, which makes clear we could have closed this without further comment.

For the moment we’ll just consider this *possibly* another instance of https://github.com/Homebrew/homebrew-cask/issues/70798.

**Comment by ItalyPaleAle** [comment]
The repro instructions were really just running `brew cask install vmware-fusion` on a clean system. As for the template, it did not apply to this case because the cask did install successfully (all the steps in the template were for casks that failed to install).

In any case, here's how you can repro it step-by-step.

1. Install macOS (I'm using Catalina 10.15.6 (19G73))
    - In this specific case, I have installed it in a VM running on VMWare Fusion on a macOS Catalina host. The VM has nested virtualization and IOMMU enabled. I used the ISO downloaded from the App Store (converted from DMG).
2. Install brew with `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"`
    - At this point, I shut down my VM and took a snapshot
3. Install VMWare Fusion with `brew cask install vmware-fusion`
4. Complete all the necessary things (add the license or start the trial, then enable Fusion to manage accessibility things, then enable the kernel extension - I also had to relaunch VMWare Fusion to make sure the kernel extension was loaded)
5. Launch a VM and experience the error every time you launch it (in this case I'm also getting a warning that I'm using nested virtualization, but that's fine)

Screen recording of steps 3-5 (I ran `brew cask update` beforehand to make this quicker): https://1drv.ms/u/s!AlOpbcHLjpOv48Q7pG0L7wjpeNyLGA?e=TIq7Sm

After that, I've restored from the snapshot before point 3. This time I'm installing Fusion by downloading the installer from the official website. Screen recording:  https://1drv.ms/v/s!AlOpbcHLjpOv48Q625BJoXwYkKXlxw?e=ZUqM85

In this case, you can see there's never any Gatekeeper error (I'm still getting the warning that I'm using nested virtualization, but that's because of this specific setup).

These repro instructions happen while using nested virtualization, but like I said, I experienced the same thing on my laptop. That was the same situation: fresh install, then running `brew cask install vmware-fusion`.

I don't know if this is a duplicate of the issue you shared, but I feel that the user experience was damaged enough by the fact that the warnings constantly appear every time. Not sure why I'm the first one to write this, but I apologize for having wasted your time by reporting this issue.

**Comment by tomyun** [comment]
I confirm I have the same Gatekeeper alerts as OP when running vmware-fusion 12.0 on fresh installed macOS 10.15.7. There are a lot of different names coming up in the dialogue including "VMware Fusion Services", "vmware-id", "vmware-cli", "vmnet-bridge", "vmnet-netifup", "vmnet-dhcpd", "vmnet-natd", "vmware-usbarbitrator", "com.vmware.VMMonHelper", "com.vmware.KextControlHelper". I have to go through clicking each one of these dialogues to get past.

**Comment by tomyun** [comment]
For anyone having the same issue, reinstalling by `brew cask reinstall --no-quarantine vmware-fusion` worked for me.
