### ISSUE TITLE
BlackmagicDesign DaVinci Resolve

### ISSUE THREAD

**Issue by danielferster** [Homebrew/homebrew-cask#87496]
Hey there,

actually i'm very new to homebrew and github at all, but i like it very much.
There is one program would also like to install via homebrew: **DaVinci Resolve**

There is also another Cask Request (from 2017) to implement. It's closed because the _downloadlink gets randomly created_.
See: https://github.com/Homebrew/homebrew-cask/issues/33251

In Arch Linux it's possible to add DaVinci Resolve via **AUR** and download it. There is the PKGBUILD for downloading it and use it:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=davinci-resolve

With that script it's possible to get an download-link.

Maybe it's possible to implement this in HomeBrew too?

I would be very happy :)

**Comment by vitorgalvao** [comment]
Even if it is, we’ll still need a PR to begin looking at it. As the templates make clear, we don’t take cask requests (we already have our hands full as it is).

**Comment by miccal** [comment]
Looking at the `PKGBUILD` script from Arch Linux ,it would be _awfully_ difficult to obatin a valid and stable `url`:
```
_downloadid='702dc3eb8e7641fe8617c2cb99cd89d6'
_referid='8575c2788fd1418fb00a0de3a4dfae45'
_siteurl="https://www.blackmagicdesign.com/api/register/us/download/${_downloadid}"

_useragent="User-Agent: Mozilla/5.0 (X11; Linux ${CARCH}) \
                        AppleWebKit/537.36 (KHTML, like Gecko) \
                        Chrome/77.0.3865.75 \
                        Safari/537.36"

_reqjson="{ \
    \"firstname\": \"Arch\", \
    \"lastname\": \"Linux\", \
    \"email\": \"someone@archlinux.org\", \
    \"phone\": \"202-555-0194\", \
    \"country\": \"us\", \
    \"state\": \"New York\", \
    \"city\": \"AUR\", \
    \"product\": \"DaVinci Resolve\" \
}"

_reqjson="$(  printf '%s' "$_reqjson"   | sed 's/[[:space:]]\+/ /g')"
_useragent="$(printf '%s' "$_useragent" | sed 's/[[:space:]]\+/ /g')"
_useragent_escaped="${_useragent// /\\ }"

_srcurl="$(curl \
            -s \
            -H 'Host: www.blackmagicdesign.com' \
            -H 'Accept: application/json, text/plain, */*' \
            -H 'Origin: https://www.blackmagicdesign.com' \
            -H "$_useragent" \
            -H 'Content-Type: application/json;charset=UTF-8' \
            -H "Referer: https://www.blackmagicdesign.com/support/download/${_referid}/Linux" \
            -H 'Accept-Encoding: gzip, deflate, br' \
            -H 'Accept-Language: en-US,en;q=0.9' \
            -H 'Authority: www.blackmagicdesign.com' \
            -H 'Cookie: _ga=GA1.2.1849503966.1518103294; _gid=GA1.2.953840595.1518103294' \
            --data-ascii "$_reqjson" \
            --compressed \
            "$_siteurl")"

DLAGENTS=("https::/usr/bin/curl \
              -gqb '' -C - --retry 3 --retry-delay 3 \
              -H Host:\ sw.blackmagicdesign.com \
              -H Upgrade-Insecure-Requests:\ 1 \
              -H ${_useragent_escaped} \
              -H Accept:\ text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8 \
              -H Accept-Language:\ en-US,en;q=0.9 \
              -o %o \
              --compressed \
              %u")
```

**Comment by danielferster** [comment]
@vitorgalvao Thank you for your quick response. I read the template and tried to make a pull request. But actually i only created a github-account for this request/issue because I’m completely new to this. So sorry about posting this as a issue instead of an pull request.

@miccal Thank you also for your quick response 👍 
Yes i had a look at this code from Arch Linux and thought I would be easy to implement when it’s working there. By myself I’m completely new to this topic and my idea was to suggest this method of arch Linux to you guys in case you don’t know this and the implementation in homebrew would be easy then.

So I will download it the oldschool way - maybe it will be possible to handle DaVinci Resolve with homebrew in the near future. ;)

**Comment by vitorgalvao** [comment]
> maybe it will be possible to handle DaVinci Resolve with homebrew in the near future.

Unlikely. They do this on purpose.
