### ISSUE TITLE
unable to push changes 

### ISSUE THREAD

**Issue by ans87gh** [Homebrew/homebrew-cask#87609]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

created rb for new cask

usenapp.rb

cask "usenapp" do
  version "0.80.5"
  sha256 "55e9da1c470b7de7972128315fdaa7fdcc8e14b8805289866b76b809983090fc"

  url "https://www.usenapp.com/download/Usenapp-0.80.5.dmg"
  name "Usenapp"
  desc "Newsreader / usenet client for Mac OSX"
  homepage "https://www.usenapp.com/"

  app "Usenapp.app"

  zap trash: [
             '~/Library/Application Support/Usenapp',
             '~/Library/Caches/com.xoroxsoft.usenapp',
             '~/Library/Preferences/com.xoroxsoft.usenapp.plist',
             '~/Library/Saved Application State/com.xoroxsoft.usenapp.savedState',
           ]
end

went through systematically completing every step outlined on
https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md

unable to push my branch usenapp-branch. Returning:

kex_exchange_identification: write: Broken pipe
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Changed my

#### Command that failed

```
{{git push ans87gh usenapp-branch}}
```

#### Output of command with `--force --verbose --debug`

```
{{Pushing to github.com:ans87gh/homebrew-cask.git
kex_exchange_identification: write: Broken pipe
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.}}
```

#### Output of `brew cask doctor`

```
{{Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have installed Bitdefender. The "Traffic Scan" option interferes with
Homebrew's ability to download packages. See:
  https://github.com/Homebrew/brew/issues/5558

Warning: You are using macOS 11.0.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this pre-release version.

}}
```

#### Output of `brew tap`

```
{{beeftornado/rmtree
buo/cask-upgrade
homebrew/bundle
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/services
mongodb/brew
nrlquaker/createzap
open-arsenal/hackers-brew
vitorgalvao/tiny-scripts
}}
```

**Comment by miccal** [comment]
```
Warning: You have installed Bitdefender. The "Traffic Scan" option interferes with
Homebrew's ability to download packages. See:
  https://github.com/Homebrew/brew/issues/5558
```
This _may_ be the problem, but let's check -- go into your casks directory by running `cd "$(brew --repository)"/Library/Taps/homebrew/homebrew-cask`, then run the command:
```
git remote -v
```
and please post the output.

**Comment by ans87gh** [comment]
ans87gh	git@github.com:ans87gh/homebrew-cask.git (fetch)
ans87gh	git@github.com:ans87gh/homebrew-cask.git (push)
origin	https://github.com/Homebrew/homebrew-cask (fetch)
origin	https://github.com/Homebrew/homebrew-cask (push)

**Comment by ans87gh** [comment]
regarding Bitdefender, I haven't had an issue in the past pushing casks

**Comment by miccal** [comment]
In your casks directory, run the command:
```
git remote set-url ans87gh https://github.com/ans87gh/homebrew-cask
```
and then please post the output of `git remote -v` again.

**Comment by ans87gh** [comment]
ans87gh	https://github.com/ans87gh/homebrew-cask (fetch)
ans87gh	https://github.com/ans87gh/homebrew-cask (push)
origin	https://github.com/Homebrew/homebrew-cask (fetch)
origin	https://github.com/Homebrew/homebrew-cask (push)

**Comment by miccal** [comment]
Ok, looks good -- now try pushing again.

**Comment by ans87gh** [comment]
will do - thanks! I'll keep you posted!

**Comment by ans87gh** [comment]
Worked until the END:

 ! [remote rejected]       usenapp-branch -> usenapp-branch (refusing to allow an OAuth App to create or update workflow `.github/workflows/automerge.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/ans87gh/homebrew-cask'
???

**Comment by miccal** [comment]
Ok, you may need to delete your branch, update your fork and re-create your new cask.

In your casks directory, checkout the master branch by running `git checkout master`, then please post the output of `git branch -a`.

**Comment by ans87gh** [comment]
I thought I was starting over; here is the output:

icollections-branch
* master
  screenfocus-branch
  sessionrestore-branch
  slimhud-branch
  usenapp-branch
  windocd-branch
  remotes/ans87gh/appdir
  remotes/ans87gh/icollections-branch
  remotes/ans87gh/master
  remotes/ans87gh/screenfocus-branch
  remotes/ans87gh/sessionrestore-branch
  remotes/ans87gh/slimhud-branch
  remotes/ans87gh/url-verified
  remotes/ans87gh/windocd-branch
  remotes/origin/HEAD -> origin/master
  remotes/origin/appdir
  remotes/origin/brew-cask-style
  remotes/origin/core-code-patch-1
  remotes/origin/core-code-patch-5
  remotes/origin/master
  remotes/origin/url-verified

**Comment by miccal** [comment]
Are you still using any of these branches?
```
screenfocus-branch
sessionrestore-branch
slimhud-branch
usenapp-branch
windocd-branch
```

**Comment by ans87gh** [comment]
No. I was at one point when making the casks.

**Comment by miccal** [comment]
Ok, run:
```
git branch -D screenfocus-branch sessionrestore-branch slimhud-branch usenapp-branch windocd-branch
```
then run:
```
git remote prune ans87gh
```
and:
```
git remote prune origin
```
then post the output of `git branch -a` again.

**Comment by ans87gh** [comment]
didn't change?

  icollections-branch
* master
  remotes/ans87gh/appdir
  remotes/ans87gh/icollections-branch
  remotes/ans87gh/master
  remotes/ans87gh/screenfocus-branch
  remotes/ans87gh/sessionrestore-branch
  remotes/ans87gh/slimhud-branch
  remotes/ans87gh/url-verified
  remotes/ans87gh/windocd-branch
  remotes/origin/HEAD -> origin/master
  remotes/origin/appdir
  remotes/origin/core-code-patch-1
  remotes/origin/master
  remotes/origin/url-verified

**Comment by ans87gh** [comment]
correction - I see it now

**Comment by miccal** [comment]
Your `remotes/ans87gh` branches did not change?

**Comment by ans87gh** [comment]
no they did not

**Comment by miccal** [comment]
Ok, let's try updating your fork -- run:
```
git checkout master; git pull --rebase origin; git push ans87gh master
```

**Comment by ans87gh** [comment]
another error at the end:

To https://github.com/ans87gh/homebrew-cask
 ! [remote rejected]       master -> master (refusing to allow an OAuth App to create or update workflow `.github/workflows/automerge.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/ans87gh/homebrew-cask'

**Comment by miccal** [comment]
Try again with `--force`:
```
git checkout master; git pull --rebase origin; git push --force ans87gh master
```

**Comment by ans87gh** [comment]
same outcome

**Comment by miccal** [comment]
Very odd -- when you run `git config --list`, are your `user.email=` and `user.name=` set correctly to those you use for GitHub?

**DON'T** post the output of `git config --list`, it may contain sensitive information.

**Comment by miccal** [comment]
You may need to [create a new personal access token](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token).

**Comment by ans87gh** [comment]
yes they are

**Comment by miccal** [comment]
If you go to `https://github.com/settings/tokens`, do you have a personal access token listed for `hub`?

**Comment by ans87gh** [comment]
that worked! Thanks miccal!
