### ISSUE TITLE
Missing dependency to qt?

### ISSUE THREAD

**Issue by rngadam** [Homebrew/homebrew-cask#87679]
https://github.com/Homebrew/homebrew-cask/blob/334764e0d9d67dc2cf0ab855a7bf3a758bec70e2/Casks/openscad.rb#L1

running this:

```
rngadam-mac:Downloads rngadam$ brew cask install openscad
==> Downloading https://files.openscad.org/OpenSCAD-2019.05.dmg
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'openscad'.
==> Installing Cask openscad
==> Moving App 'OpenSCAD.app' to '/Applications/OpenSCAD.app'.
==> Linking Binary 'OpenSCAD' to '/usr/local/bin/openscad'.
🍺  openscad was successfully installed!
rngadam-mac:Downloads rngadam$ openscad
This application failed to start because it could not find or load the Qt platform plugin "cocoa"
in "".

Reinstalling the application may fix this problem.
Abort trap: 6
```

However installing qt by itself does not work

**Comment by miccal** [comment]
`Abort trap: 6` is a problem with the `binary`, which can be fixed by adding a `shimscript` -- https://github.com/Homebrew/homebrew-cask/pull/87711 should hopefully fix this.

**Comment by vitorgalvao** [comment]
This `binary` was added without a report that upstream recommends this linkage. Linking from the app’s binary is usually a giveaway.

Unless there’s upstream documentation showing this should be done, the correct step is to remove that line. Can you find such documentation @rngadam?

https://github.com/Homebrew/homebrew-cask/pull/87720.

**Comment by rngadam** [comment]
@vitorgalvao oh wow, ok, if I start the OpenSCAD executable from the command-line it does work:

```
$ /Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD 
```

the symlink:

```
$ ls -al `which openscad`
lrwxr-xr-x  1 rngadam  admin  50 Aug 16 10:25 /usr/local/bin/openscad -> /Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD
```

if i replace by a shell script it works:

```
$ rm /usr/local/bin/openscad
$ cat /usr/local/bin/openscad
#!/bin/bash
/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD
$ chmod u+x /usr/local/bin/openscad
$ openscad
```

**Comment by vitorgalvao** [comment]
> if I start the OpenSCAD executable from the command-line it does work

That’s not the question. It’s supposed to work like that, because that’s essentially what invoking the app is. The question if is upstream recommends doing that symlink or not.
