### ISSUE TITLE
Make "brew cask info" print out sudo requirement

### ISSUE THREAD

**Issue by radeksimko** [Homebrew/homebrew-cask#8817]
There's a bunch of casks that require sudo permission, but installing all casks with sudo is not the best solution, which is why we should IMO start tracking which casks have this requirement and allow users & external tools to use this fact accordingly.

Related: https://github.com/boxen/puppet-brewcask/issues/22#issuecomment-69498178 and https://github.com/caskroom/homebrew-cask/issues/5667
### How do we identify these casks?

I think there might be certain installation types which may be automatically considered as problematic (pkg) + there will be some that we'll have to mark explicitely, e.g. `*.app` which will only work from `/Applications/`.
### In what format should we print this fact?

I'd can imagine that there are 2 use-cases:
   a) user form CLI
   b) scripts and external tools

which is why I suggest something like this:

```
$ brew cask info google-chrome
google-chrome: latest
google-chrome
https://www.google.com/chrome/
/opt/homebrew-cask/Caskroom/google-chrome/latest (385 files, 359M)
https://github.com/caskroom/homebrew-cask/blob/master/Casks/google-chrome.rb
==> Installation requires su privilege
yes
==> Contents
  Google Chrome.app (app)
```

```
$ brew cask info google-chrome --requires-su
1
```

The naming would be subject to discussion as `su` may stand for _super user_ or _switch user_, so maybe _admin privilege_ as _super user_ might be too long?

**Comment by phinze** [comment]
:+1: I think we'll catch >80% of the cases in question by just doing this for pkg casks (since they _always_ require sudo).

Rather than special casing `--requires-su` I think might be better to just add `--machine-readable` output for `brew cask info` ... looking into this now...

**Comment by radeksimko** [comment]
> Rather than special casing --requires-su I think might be better to just add --machine-readable output for brew cask info ... looking into this now...

Good point, I agree.

**Comment by salimane** [comment]
:+1:

**Comment by alebcay** [comment]
> The naming would be subject to discussion as su may stand for super user or switch user, so maybe admin privilege as super user might be too long?

The output in `brew cask doctor` reads:

```
==> Running As Privileged User:
No
```

Thus, it may be best to stick with consistent terminology - so perhaps "Installation requires privileged user" or something along those lines.

> I think might be better to just add --machine-readable output for `brew cask info`

Perhaps formatted as JSON, XML, or, heaven forbid, YAML?

**Comment by tamasflamich** [comment]
Thank you for this. Adding `--machine-readable` would be a welcome change for me as well. May I suggest to include the version of the formula in the JSON as well?

**Comment by vitorgalvao** [comment]
Not problematic enough and not enough interest in implementing this, so closing as part of issues cleanup.
