### ISSUE TITLE
google-cloud-sdk versioned and maybe formular

### ISSUE THREAD

**Issue by Mazorius** [Homebrew/homebrew-cask#88183]
### Description of feature/enhancement

Google has a versioned archive so that the cask does not need latest anymore — I think.
e.g.: https://storage.googleapis.com/cloud-sdk-release/google-cloud-sdk-307.0.0-darwin-x86_64.tar.gz

As mentioned in #62715 maybe a switch to formular is possible as it is a CLI?

### Justification

A update is much easier to see … and I find cask a bit strange for a CLI — hmmm.
Also it can be listed by `brew cask outdated` or `brew outdated` if no more a cask.

### Example use case

Checking output of outdated via script is much easier.

**Comment by miccal** [comment]
Although the `google-cloud-sdk` is a CLI tool, as per the [Homebrew documentation](https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae) a formula must either build from source or produce cross-platform binaries. Binary-only tools belong in `homebrew-cask`.

Also, there is a note in the [cask file itself](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/google-cloud-sdk.rb#L2) explaining why it is un-versioned.

**Comment by Mazorius** [comment]
Ok – so without cask is not possible. Thank you for the clarification!

I read the comment but the comment blame is the following.

```
fcb36135f6e (Ondřej Führer 2018-04-11 23:52:56 +0200
```

I think maybe this is a outdated comment?

If I know how to test this, I would do this in a PR … but I not really have an idea about that.

**Comment by vitorgalvao** [comment]
You’re welcome to try to make this into a formula, but that’s the domain of https://github.com/Homebrew/homebrew-core; this repo is only concerned with casks.

If you can make it into a formula and have it merged in that repo, we’ll remove it from here.
