### ISSUE TITLE
Update Homebrew casks versions

### ISSUE THREAD

**Issue by yumauri** [Homebrew/homebrew-cask#88440]
(Originally asked [here](https://stackoverflow.com/questions/63651114/update-homebrew-casks-versions))

I know, that Homebrew doesn't upgrade casks with auto-update (without force). So eventually, software versions, actually installed, and tracked by Homebrew, become different. For example:

```bash
$ brew cask outdated --greedy
firefox (79.0) != 80.0
google-chrome (84.0.4147.105) != 85.0.4183.83
microsoft-edge (84.0.522.48) != 85.0.564.41
```

Firefox, Chrome and Edge auto-updates themselves and actually has latest versions. But Homebrew doesn't know about it.

So, is there a way to tell Homebrew, that some cask is the latest version already, _without reinstalling cask with brew_? Just update record in Homebrew database (or whatever brew stores casks' versions in).

I don't like seeing old irrelevant versions of software in brew output, and I don't want to make force reinstallations. Just notify Homebrew, that "Listen, I know the version installed, can you update your tracking version, please?".

**Comment by vitorgalvao** [comment]
No, there’s no official way to do it. There’s also not much *point*. If you don’t want to see those versions, don’t use `--greedy`.

You can fake the behaviour you want by changing the name of the version directory inside the directory in `$(brew --caskroom)/<CASK NAME>/.metadata`. **You do so at your own risk, and will get no support for issues that arise from it.**

**Comment by yumauri** [comment]
Some software has checkbox, either to check updates and upgrades automatically, or do not. Homebrew doesn't know about this behaviour.
It is possible case, when brew thinks software auto-upgrades automatically, but it does not.
So I use `--greedy` to be sure, that if some software has new version — it actually upgrades, and this new version is actually installed, and I did't forget to find that checkbox in settings, or whatever.

**Comment by vitorgalvao** [comment]
I don’t recall every seeing a macOS app that has the ability to auto-update but turns the option off by default.

**Comment by yumauri** [comment]
Maybe this is just my corrupted scenario...

I use `--greedy` like "installed software version checker", to be in full control of my software.

In other words, I check `brew cask outdated --greedy`, see, that, lets say, Firefox has new version. I launch Firefox and verify version. If it is new — I think "good boy", otherwise I select "Check updates" in Firefox menu.

Am I the only guy who checks versions like that? :)

**Comment by vitorgalvao** [comment]
> Am I the only guy who checks versions like that? :)

Probably not the only one, but I doubt a significant number of our users have such a level of obsession that they check the versions in multiple places. Especially since we can’t provide updates before they exist, we’ll always be a bit behind.

**Comment by yumauri** [comment]
Ok, let's see from another point:
I can uninstall cask using `brew cask uninstall`.

Let's say I installed version 79 of Firefox. Brew cask has version 79 and *.rb script, related to version 79.
Then Firefox auto-upgrades itself to version 80, and added some new files, not covered by cask version 79.
Then I use `brew cask uninstall firefox` and those new files from version 80 are left in my system, because brew has used script for version 79.

But if there were a way to update cask itself, without reinstalling software, there will be not such problem, because brew will use script from version 80.

**Comment by vitorgalvao** [comment]
That point is already being handled in another issue. Our uninstallation methodology sucks in general (and that’s not the fault of `auto_updates`).

**Comment by yumauri** [comment]
@vitorgalvao Following your hint about faking the behaviour I want, I wrote small shell script to "update cask version": https://gist.github.com/yumauri/1915426eff7c07990fbc802376db8f30

Maybe you can point obvious pitfalls of that approach, please?
Obvious for you, but not for me.

**Comment by vitorgalvao** [comment]
You should probably also move the newer cask file in there.

Nothing else obvious occurs to me.

**Comment by yumauri** [comment]
Last line of a script, is that what you mean?

> brew cask cat $CASKNAME > "$CASKDIR/.metadata/$CURRENT/$DATE/Casks/$CASKNAME.rb"

**Comment by vitorgalvao** [comment]
> Last line of a script, is that what you mean?

Yes.

**Comment by yumauri** [comment]
Ok, thank you! I'll try to use it on my own risk :)
