### ISSUE TITLE
Blender cask should enable installing LTS version

### ISSUE THREAD

**Issue by walles** [Homebrew/homebrew-cask#88481]
Here's the Blender cask:
<https://github.com/Homebrew/homebrew-cask/blob/master/Casks/blender.rb>

Currently it tracks the latest version of Blender.

I would appreciate if there was an option to have it tracking Blender's Long Term Support version instead:
<https://www.blender.org/download/lts/>

**Comment by miccal** [comment]
Feel free to submit the LTS version to the [`homebrew-cask-versions` repository.](https://github.com/Homebrew/homebrew-cask-versions)

**Comment by reitermarkus** [comment]
Closing in favour of a pull request to the [`homebrew-cask-versions` repository](https://github.com/Homebrew/homebrew-cask-versions).

**Comment by walles** [comment]
AFAICT the PR should now be ready to merge: https://github.com/Homebrew/homebrew-cask-versions/pull/9542
