### ISSUE TITLE
After upgrade from 10.13 to 10.15 nvidia-cuda uninstall failing

### ISSUE THREAD

**Issue by ylluminate** [Homebrew/homebrew-cask#88614]
After having upgraded from macOS 10.13 (was running an Nvidia card) to 10.15 I found a troublesome issue when I `brew upgrade` in that I can't uninstall or reinstall to uninstall `nvidia-cuda`.  In this case I'd upgraded and got an error in the System Preferences and, unthinkingly, manually removed the CUDA drivers as per the uninstall instructions from them.  After doing this I ran a `brew upgrade` and since it was no longer installed properly, Homebrew wanted to reinstall it, but fails with:
```
==> Purging files for version 10.1.105 of Cask nvidia-cuda
Error: nvidia-cuda: macOS Sierra or High Sierra is required.
```

I thought a `brew update-reset && brew update` would help, but unfortunately it doesn't.

What should I do to remove this properly in this state?

**Comment by miccal** [comment]
Please run:
```
brew cask uninstall --force nvidia-cuda
```
then run:
```
rm -r "$(brew --prefix)/Caskroom/nvidia-cuda"
```
and this should hopefully fix your issue.

**Comment by ylluminate** [comment]
Thanks very much - that did the trick. The second command was not necessary, but I had forgotten about `--force` overriding things like this.
