### ISSUE TITLE
support a --ignore-sha flag to continue even if the SHA does not match

### ISSUE THREAD

**Issue by core-code** [Homebrew/homebrew-cask#89484]
it would be great if there was a flag to force 'brew cask install' to continue even if the checksum of the downloaded file does not match.

use case are advanced users or pipelines that are made in support of HBC's maintainance work. e.g. i have have 'findVersionOfCask' script that has to modify HBC's internals to make 'brew cask install' work even in a mismatch case. 'cask-repair' does something similar.

if it is not decided that users should have access to such a flag, i guess a more hidden or private flag like --debugForce might still be useful for the supporting pipeline

more discussion is here https://github.com/Homebrew/homebrew-cask/issues/49764

[findVersionOfCask.py.txt](https://github.com/Homebrew/homebrew-cask/files/5241798/findVersionOfCask.py.txt)

**Comment by core-code** [comment]
might also be useful for recurring problems where there are different checksums depending on the region with some chinese casks e.g. https://github.com/Homebrew/homebrew-cask/pull/89305

**Comment by reitermarkus** [comment]
> might also be useful for recurring problems where there are different checksums depending on the region with some chinese casks

I that case we should just use `:no_check` and a comment. It doesn't make sense that some people would have to use `--ignore-sha` an others wouldn't.

**Comment by core-code** [comment]
i'll try to make this change the next time this comes up, thanks

**Comment by MikeMcQuaid** [comment]
I think it may still be worth having a flag like this for users where they want to install e.g. Google Chrome programmatically and trust Homebrew/homebrew-cask and the upstream download service sufficiently that they don't care if the SHA doesn't match.
