### ISSUE TITLE
Prevent homebrew cask from removing app metadata during update

### ISSUE THREAD

**Issue by mkll** [Homebrew/homebrew-cask#89497]
### Description of feature/enhancement

Many of us use the grouping of app icons in the Launchpad. The current implementation of the update destroys all metadata regarding where exactly in the Launchpad the app was located before the update.

This happens because the process of updating the app in reality consists of two processes — firstly the app is deleted, then it is created anew. Of course the metadata is lost.

As a result, after each update of the app, you have to move the icon to the place where it was before the update. It's pretty annoying.

### Example use case

```
==> Uninstalling Cask visual-studio-code
==> Backing App 'Visual Studio Code.app' up to '/usr/local/Caskroom/visual-studi
==> Removing App '/Applications/Visual Studio Code.app'.
==> Unlinking Binary '/usr/local/bin/code'.
==> Purging files for version 1.49.0 of Cask visual-studio-code
==> Installing Cask visual-studio-code
==> Moving App 'Visual Studio Code.app' to '/Applications/Visual Studio Code.app
```

**Comment by reitermarkus** [comment]
> This happens because the process of updating the app in reality consists of two processes — firstly the app is destroyed, then it is created anew. Of course the metadata is lost.

How would you avoid this? What would be the correct way to replace apps?

**Comment by mkll** [comment]
Maybe copy with overwrite?

**Comment by reitermarkus** [comment]
That won't work if there are files that were deleted in the new version. `rsync --delete` could work.

**Comment by mkll** [comment]
The `rsync` command should looks exactly like that:
```
rsync -av --delete "Skype.app/" "/Applications/Skype.app"
```
Note the trailing '/' on the first filename operand.

**Comment by reitermarkus** [comment]
One more thing to look out for: The app name could have changed with an update.

**Comment by L1cardo** [comment]
So what is the reason of not using old update method?
My launchpad will be a mess every time I use `brew cask upgrade`.

**Comment by reitermarkus** [comment]
> So what is the reason of not using old update method?

What would be the old method?

**Comment by L1cardo** [comment]
> > So what is the reason of not using old update method?
> 
> 
> 
> What would be the old method?

Update apps without messing around with my launchpad.

**Comment by mkll** [comment]
@L1cardo Overwrite...
> ...won't work if there are files that were deleted in the new version

as noted above.

**Comment by tiiiecherle** [comment]
I had the same "problem" and made an update script that uses `cask install --force` for each cask to update.
I never had a problem regarding a rename.
There maybe leftover old files sometimes, but keeping my settings is way more important to me.

[https://github.com/tiiiecherle/osx_install_config/blob/master/03_homebrew_casks_and_mas/3c_homebrew_formulae_and_casks_update/shell_script/brew_casks_update.sh](https://github.com/tiiiecherle/osx_install_config/blob/master/03_homebrew_casks_and_mas/3c_homebrew_formulae_and_casks_update/shell_script/brew_casks_update.sh)

**Comment by vitorgalvao** [comment]
> One more thing to look out for: The app name could have changed with an update.

In that case the cask will be renamed as well.

> So what is the reason of not using old update method?

There is no “old method”, `brew cask upgrade` always worked like this. Whatever solution you may have been using before, it wasn’t official.

**Comment by core-code** [comment]
i am not sure if its helpful but i've contributed code to Sparkle to make it preserve Finder tags while updating apps:

https://github.com/sparkle-project/Sparkle/pull/1512
