### ISSUE TITLE
Consistent output for pinned casks in the upgrade command

### ISSUE THREAD

**Issue by jrslv** [Homebrew/homebrew-cask#89605]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

In the presence of pinned casks, the output of `brew upgrade` shows something like:
```
λ ~ > brew upgrade
Error: Not upgrading 1 pinned package:
awscli 2.0.50
==> Would upgrade 109 outdated packages:
rubberband 1.8.2_1 -> 1.9.0
git-quick-stats 2.0.12 -> 2.1.4
...
```

For the sake of consistency, I believe the "Not upgrading 1 pinned package" message should be prefixed with "==> " instead of "Error".

**Comment by miccal** [comment]
You have reported this issue to the wrong repository; `awscli` is a Formula, not a Cask.

Please open an issue in the [`brew` repository.](https://github.com/Homebrew/brew)
