### ISSUE TITLE
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper

### ISSUE THREAD

**Issue by jderlatka** [Homebrew/homebrew-cask#89874]
I keep getting this in my output.. I'm installing via a jamf mdm script.

sudo -u $loggedInUser /usr/local/bin/brew cask install $5

any suggestions..

**Comment by reitermarkus** [comment]
Well, as the message suggests: Configure an askpass helper.

Search `man sudo` for `SUDO_ASKPASS`.
