### ISSUE TITLE
Issue installing Sequel Pro on Catalina (10.15.7)

### ISSUE THREAD

**Issue by gheydon** [Homebrew/homebrew-cask#90172]
#### General troubleshooting steps

- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

When trying to install Sequel Pro I get the a definition invalid error

#### Command that failed

```
brew reinstall sequel-pro
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#reinstall
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading
==> Downloading https://github.com/sequelpro/sequelpro/releases/download/release-1.1.2/sequel-pro-1.1.2.dmg
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.5.2-67-g32a3d49\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.7\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://github.com/sequelpro/sequelpro/releases/download/release-1.1.2/sequel-pro-1.1.2.dmg
Already downloaded: /Users/gordon/Library/Caches/Homebrew/downloads/8b2af6c2be31a86ac4b9efca5d7ea014fd3fcab9f05e589d0041097cd916f0d3--sequel-pro-1.1.2.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/gordon/Library/Caches/Homebrew/downloads/8b2af6c2be31a86ac4b9efca5d7ea014fd3fcab9f05e589d0041097cd916f0d3--sequel-pro-1.1.2.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/gordon/Library/Caches/Homebrew/downloads/8b2af6c2be31a86ac4b9efca5d7ea014fd3fcab9f05e589d0041097cd916f0d3--sequel-pro-1.1.2.dmg
==> /Users/gordon/Library/Caches/Homebrew/downloads/8b2af6c2be31a86ac4b9efca5d7ea014fd3fcab9f05e589d0041097cd916f0d3--sequel-pro-1.1.2.dmg is quarantined
==> Downloaded to -> /Users/gordon/Library/Caches/Homebrew/downloads/8b2af6c2be31a86ac4b9efca5d7ea014fd3fcab9f05e589d0041097cd916f0d3--sequel-pro-1.1.2.dmg
tar tf /Users/gordon/Library/Caches/Homebrew/downloads/8b2af6c2be31a86ac4b9efca5d7ea014fd3fcab9f05e589d0041097cd916f0d3--sequel-pro-1.1.2.dmg
hdiutil imageinfo -format /Users/gordon/Library/Caches/Homebrew/downloads/8b2af6c2be31a86ac4b9efca5d7ea014fd3fcab9f05e589d0041097cd916f0d3--sequel-pro-1.1.2.dmg
==> Verifying SHA-256 checksum for Cask 'sequel-pro'.
Error: Cask 'sequel-pro' definition is invalid: invalid 'depends_on macos' value: ">= :leopard"
/usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:222:in `rescue in depends_on'
/usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:219:in `depends_on'
/usr/local/Caskroom/sequel-pro/.metadata/1.1.2/20170321050243.048/Casks/sequel-pro.rb:12:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:58:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:58:in `config='
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:45:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:42:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:42:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:86:in `cask'
/usr/local/Caskroom/sequel-pro/.metadata/1.1.2/20170321050243.048/Casks/sequel-pro.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:71:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:71:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:198:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:138:in `uninstall_existing_cask'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:94:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:130:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:48:in `block in reinstall_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:47:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:47:in `reinstall_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:81:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'```

#### Output of `brew doctor --verbose`

```
==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
==> $LOAD_PATHS
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.43.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.8.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/patchelf-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/elftools-1.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bindata-2.4.8/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.3.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Homebrew Version
2.5.2-67-g32a3d49
==> macOS
10.15.7
==> SIP
Enabled
==> Java
12.0.1
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3672 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (160 casks)
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae were deleted!
You should find replacements for the following formulae:
  wine
  phantomjs

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc```

#### Output of `brew tap`

```
brew tap
drud/ddev
homebrew/cask
homebrew/cask-versions
homebrew/core
```

**Comment by Spriz** [comment]
Not really related - but you should install `sequel-ace` instead of as `sequel-pro` project has been left AFAIK

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/issues/58046
