### ISSUE TITLE
Warnings and error. Warning: Cask '' is unreadable: invalid keys: :caskroom

### ISSUE THREAD

**Issue by npklein** [Homebrew/homebrew-cask#90233]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

When I install anything with homebrew I get a bunch of warnings about invalid keys (2 examples but there are 10+):

```
Warning: Cask 'slack' is unreadable: invalid keys: :caskroom
Warning: Cask 'pycharm-edu' is unreadable: invalid keys: :caskroom
```

Usually I can still install even with these warnings. However, when I try to install rstudio with `brew cask install rstudio` I get:

    Error: Cask 'rstudio' is unreadable: invalid keys: :caskroom Did you mean one of these?

and it doesn't install. When I do `brew doctor` I get

    Error: Cask 'bbedit' is unreadable: invalid keys: :caskroom

even though bbedit is installed and working. 

#### Command that failed

```
brew cask install rstudio
```

#### Output of command with `--force --verbose --debug`

```
Warning: Cask 'rstudio' is unreadable: invalid keys: :caskroom
Warning: Cask 'slack' is unreadable: invalid keys: :caskroom
Warning: Cask 'pycharm-edu' is unreadable: invalid keys: :caskroom
Warning: Cask 'bbedit' is unreadable: invalid keys: :caskroom
Warning: Cask 'evernote' is unreadable: invalid keys: :caskroom
Warning: Cask 'iterm2' is unreadable: invalid keys: :caskroom
Warning: Cask 'firefox' is unreadable: invalid keys: :caskroom
Warning: Cask 'google-chrome' is unreadable: invalid keys: :caskroom
Warning: Cask 'texstudio' is unreadable: invalid keys: :caskroom
Warning: Cask 'zotero' is unreadable: invalid keys: :caskroom
Warning: Cask 'pycharm' is unreadable: invalid keys: :caskroom
Error: Cask 'rstudio' is unreadable: invalid keys: :caskroom Did you mean one of these?
beekeeper-studio                  rapidminer-studio                 rstudio-daily                     rstudio-preview
/Users/nd7/homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:112:in `rescue in casks'
/Users/nd7/homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:106:in `casks'
/Users/nd7/homebrew/Library/Homebrew/cask/cmd/install.rb:38:in `run'
/Users/nd7/homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:95:in `run'
/Users/nd7/homebrew/Library/Homebrew/cask/cmd.rb:252:in `run'
/Users/nd7/homebrew/Library/Homebrew/cask/cmd.rb:186:in `run'
/Users/nd7/homebrew/Library/Homebrew/cmd/cask.rb:14:in `cask'
/Users/nd7/homebrew/Library/Homebrew/brew.rb:119:in `<main>'
Error: Kernel.exit
/Users/nd7/homebrew/Library/Homebrew/cask/cmd.rb:257:in `exit'
/Users/nd7/homebrew/Library/Homebrew/cask/cmd.rb:257:in `rescue in run'
/Users/nd7/homebrew/Library/Homebrew/cask/cmd.rb:234:in `run'
/Users/nd7/homebrew/Library/Homebrew/cask/cmd.rb:186:in `run'
/Users/nd7/homebrew/Library/Homebrew/cmd/cask.rb:14:in `cask'
/Users/nd7/homebrew/Library/Homebrew/brew.rb:119:in `<main>'
```

#### Output of `brew doctor --verbose`

```
Error: Cask 'bbedit' is unreadable: invalid keys: :caskroom
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/cask-versions
homebrew/core
sachaos/todoist
```

**Comment by vitorgalvao** [comment]
Go into `$(brew --repository)/Library/Taps/homebrew/homebrew-cask/Casks` and `cat` any of those casks. What are the contents?

**Comment by npklein** [comment]
```
$ cat zotero.rb
cask "zotero" do
  version "5.0.90"
  sha256 "26c3d59834b81d46cff3fd53791e2d758a971943102d21093d0b8b23b18f77f9"

  url "https://download.zotero.org/client/release/#{version}/Zotero-#{version}.dmg"
  appcast "https://www.zotero.org/download/"
  name "Zotero"
  desc "Collect, organize, cite, and share research sources"
  homepage "https://www.zotero.org/"

  auto_updates true

  app "Zotero.app"
end
```

**Comment by vitorgalvao** [comment]
Is Zotero installed? If so, go into `$(brew --prefix)/Caskroom/zotero/.metadata` and drill down until you find the cask. `cat` that one.

**Comment by npklein** [comment]
Do you mean the zotero.rb in the .metadata/../Casks?

```
nd7@mib114731i:~/homebrew/Caskroom/zotero/.metadata/5.0.90/20200909175157.000/Casks$ cat zotero.rb
cask "zotero" do
  version "5.0.90"
  sha256 "26c3d59834b81d46cff3fd53791e2d758a971943102d21093d0b8b23b18f77f9"

  url "https://download.zotero.org/client/release/#{version}/Zotero-#{version}.dmg"
  appcast "https://www.zotero.org/download/"
  name "Zotero"
  homepage "https://www.zotero.org/"

  auto_updates true

  app "Zotero.app"
end
```

**Comment by vitorgalvao** [comment]
As you can attest, there’s no `caskroom` key in any of those casks. Your installation is borked, but I can’t say where or how. Assuming you did run the commands in the template, that shouldn’t be happening. I’d try reinstalling.

I’ve also noticed you’ve installed HB to an atypical location. While that‘s allowed, we only support installations done on the default path of `/usr/local/`, because the alternatives often lead to problems.

I’ll leave this open for a few days in case anyone has any insight, but it’s an error you may need to pursue yourself.
