### ISSUE TITLE
Cannot remove nor update haskell

### ISSUE THREAD

**Issue by chasrmartin** [Homebrew/homebrew-cask#90318]
#### General troubleshooting steps

- [ x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ x] I have retried my command with `--force`.
- [x ] I ran `brew update-reset && brew update` and retried my command.
- [ x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ]x I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue
Warning: Unexpected method 'license' called on Cask haskell-platform.

Error: Cask 'haskell-platform' definition is invalid: invalid 'depends_on macos' value: ">= :snow_leopard"

#### Command that failed

```
brew doctor
```

#### Output of command with `--force --verbose --debug`

```
$ brew doctor --force --verbose --debug
Usage: brew doctor [options]

Check your system for potential problems. Will exit with a non-zero status if
any potential problems are found. Please note that these warnings are just used
to help the Homebrew maintainers with debugging if you file an issue. If
everything you use Homebrew for is working fine: please don't worry or file an
issue; just ignore this.

      --list-checks                List all audit methods, which can be run
                                   individually if provided as arguments.
  -D, --audit-debug                Enable debugging and profiling of audit
                                   methods.
  -d, --debug                      Display any debugging information.
  -q, --quiet                      Suppress any warnings.
  -v, --verbose                    Make some output more verbose.
  -h, --help                       Show this message.
Error: invalid option: --force
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:170:in `parse_remaining'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:218:in `parse'
/usr/local/Homebrew/Library/Homebrew/compat/cli/parser.rb:22:in `parse'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:30:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'
(base) [~]:527 $

```

#### Output of `brew doctor --verbose`

```
$ brew doctor --verbose
Warning: Unexpected method 'license' called on Cask haskell-platform.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Error: Cask 'haskell-platform' definition is invalid: invalid 'depends_on macos' value: ">= :snow_leopard"
(base) [~]:525 $
```

#### Output of `brew tap`

```
$ brew tap
coursier/formulas
dart-lang/dart
heroku/brew
homebrew/cask
homebrew/core
homebrew/services
koekeishiya/formulae
mongodb/brew
railwaycat/emacsmacport
snaipe/soft
(base) [~]:526 $
```

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/issues/90224#issuecomment-702508955

https://github.com/Homebrew/homebrew-cask/issues/58046

**Comment by chasrmartin** [comment]
```
brew cask uninstall --force snaipe/soft
Error: Cask 'soft' is unavailable: No Cask with this name exists. Did you mean one of these?
8bitdo-ultimate-software                    microsoft-excel                             microsoft-word
aimersoft-video-converter-ultimate          microsoft-lync                              molsoftbrowser
beoplay-software-update                     microsoft-office                            ondesoft-audiobook-converter
charlessoft-timetracker                     microsoft-outlook                           sipgate-softphone
microsoft-auto-update                       microsoft-powerpoint                        softmaker-freeoffice
microsoft-azure-storage-explorer            microsoft-r-open                            softorino-youtube-converter
microsoft-edge                              microsoft-teams
(base) [~]:503 $ brew cask uninstall --force dart-lang/dart
Error: Cask 'dart' is unavailable: No Cask with this name exists.
(base) [~]:504 $ brew cask uninstall --force railwaycat/emacsmacport
Error: Cask 'emacsmacport' is unavailable: No Cask with this name exists.
(base) [~]:505 $
```

Could you possibly offer more of a hint?

**Comment by vitorgalvao** [comment]
> brew cask uninstall --force snaipe/soft

Why are you running that command? Your error was on `haskell-platform`.

**Comment by chasrmartin** [comment]
Because your total description of why you closed my bug was referencing a different bug that said to run that command. Why are you linking another answer if it doesn't answer my issue? Oh, and by the way,

```
$ brew cask uninstall --force haskell-platform
Warning: Unexpected method 'license' called on Cask haskell-platform.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Error: Cask 'haskell-platform' definition is invalid: invalid 'depends_on macos' value: ">= :snow_leopard"
(base) [Pset2]:502 $
```

**Comment by chasrmartin** [comment]
Please reopen the issue unless you have a solution.

**Comment by vitorgalvao** [comment]
Reopening won’t do anything. You may not have understood the instructions, but they are there and enough. You’re supposed to run every command, not stop at the first error. Most people don’t have trouble when linked to the solution, which is why I haven’t expanded.

```
brew cask uninstall --force haskell-platform # May work or not
rm -r "$(brew --prefix)/Caskroom/haskell-platform" # Always works, hence why it’s there
/usr/bin/find "$(brew --prefix)/Caskroom/"*'/.metadata' -type f -name '*.rb' -print0 | /usr/bin/xargs -0 /usr/bin/perl -i -pe 's/depends_on macos: \[.*?\]//gsm;s/depends_on macos: .*//g' # Fixes the other error for installed casks
```

**Comment by chasrmartin** [comment]
Imagine how cool it would have been to simply answer the question.

**Comment by vitorgalvao** [comment]
> Imagine how cool it would have been to simply answer the question.

Please moderate your tone; your increasing sarcasm is not appreciated. It’s not our obligation to spend our free volunteer time responding to your issues with a tool you benefit from at no cost. On the contrary, it’s on you to make an effort.

Responding with direct links is enough in the *vast* majority of cases. Most people are understanding and capable enough to follow instructions on the first try. It’s fine to ask for clarification, it’s not fine to act like you’re owed something.

You seemingly haven’t searched for your problem; haven’t read the instructions; haven’t tried the resolution steps until the end; and are acting entitled to boot. You’re not on the side of right.

I’ll ask you again to moderate your tone on future interactions, or risk being barred from posting.
