### ISSUE TITLE
issue with qgis cask

### ISSUE THREAD

**Issue by lhahne** [Homebrew/homebrew-cask#90322]
`Error: Cask 'qgis' is unreadable: undefined method `undent' for #<String:0x00007fbeaca18980>`

**Comment by miccal** [comment]
You currently installed version of `qgis` is from an old version of the Cask file -- please run
```
brew cask uninstall --force qgis
```
then
```
rm -r "$(brew --prefix)/Caskroom/qgis"
```
then
```
brew cask install qgis
```
and this may fix your issue.

Next time please fill out the issue template as asked.
