### ISSUE TITLE
(10.12/ mpv) SHA256 mismatch

### ISSUE THREAD

**Issue by mrkapqa** [Homebrew/homebrew-cask#90410]
#### Description of issue

brew install mpv

on Mac OS Sierra results

Downloading https://github.com/erikd/libsndfile/releases/download/v1.0.30/li
Already downloaded: /Users/rich/Library/Caches/Homebrew/downloads/71cd51640a04d9625f2f0f94915ff20da52fb52e61808a2027c9c0754a0d736b--libsndfile-1.0.30.tar.bz2
Error: SHA256 mismatch
Expected: ec898634766595438142c76cf3bdd46b77305d4a295dd16b29d024122d7a4b3f
  Actual: 9df273302c4fa160567f412e10cc4f76666b66281e7ba48370fb544e87e4611a
 Archive: /Users/rich/Library/Caches/Homebrew/downloads/71cd51640a04d9625f2f0f94915ff20da52fb52e61808a2027c9c0754a0d736b--libsndfile-1.0.30.tar.bz2
To retry an incomplete download, remove the file above.

please show how to correct this

thank you.

**Comment by miccal** [comment]
Your query relates to `libsndfile` which is a formula, not a cask -- please report this issue to [`homebrew-core`](https://github.com/Homebrew/homebrew-core).
