### ISSUE TITLE
brew cask install google-chrome failed checksum

### ISSUE THREAD

**Issue by aniruddha211** [Homebrew/homebrew-cask#90567]
General troubleshooting steps
Install Google Chrome via brew cask install command.

Description of issue
Hash of the file doesn't match.

Command that failed
brew cask install google-chrome
Output of command
dast7 at macOS-246851 in ~ $ brew cask install google-chrome
Tapped 161 casks (208 files, 65.4MB).
==> Downloading https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
Error: Checksum for Cask 'google-chrome' does not match.
Expected: b37980c7d92b589c062f748465a317af460ac29a0adde8e881e8ecd0b09a69a7
  Actual: 3ab76266189a7b2c5b9f789fbae7f7d25404e7158ee3e841dc0692eae2718182
    File: /Users/vagrant/Library/Caches/Homebrew/downloads/9830ac8a5256756d2643fbdb6a47ba0eb019c3816fc4366049f2483999b2ee4f--googlechrome.dmg
To retry an incomplete download, remove the file above.

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
