### ISSUE TITLE
MuseScore Error

### ISSUE THREAD

**Issue by perdomwx** [Homebrew/homebrew-cask#90641]
Updating MuseScore to 3.5.1 (brew cu) gives me this error in MacOS Catalina 10.15.16. I've tried running brew update but I still get the same issue.

==> Upgrading musescore to 3.5.1
==> Downloading https://github.com/musescore/MuseScore/releases/download/v3.5.1/
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/828e23ad3b21a17c9823088035dd786993b62f50d1ca9bf2acae1732eadd6db1--MuseScore-3.5.1.dmg
==> Verifying SHA-256 checksum for Cask 'musescore'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'musescore' does not match.
Expected: b3316b1ad11ba011e2505691d861287173639644616753ee9525330c2a41dabe
  Actual: 4c9f4daac8486b61be4cf31d75d078141fc5c97a71e6b7ddbc7dbaed8167cd5f
    File: /Users/user/Library/Caches/Homebrew/downloads/828e23ad3b21a17c9823088035dd786993b62f50d1ca9bf2acae1732eadd6db1--MuseScore-3.5.1.dmg
To retry an incomplete download, remove the file above.
If the issue persists, visit:
  https://github.com/Homebrew/homebrew-cask/blob/HEAD/doc/reporting_bugs/checksum_does_not_match_error.md

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

The template itself has a point that helps you fix this for everyone.

In addition, `brew cu` is a third-party tool, so we don’t support it.
