### ISSUE TITLE
Incorrect SHA

### ISSUE THREAD

**Issue by TheSecEng** [Homebrew/homebrew-cask#90827]
https://github.com/Homebrew/homebrew-cask/blob/26b6251e7691f3aa8c62f3c2534f5dc3b690b0ae/Casks/sip.rb#L7

```
Expected: 448e6e6ccc696b919aba5edf2068e114268d3ef86e8ebdd7151bd961d50b13d3
Actual: 19f956975113698abc10c869948f2616fe90d26cb4f2ff1cbfc56f2cfcd9247f
```

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/90828

Please fill in the issue template next time as requested.
