### ISSUE TITLE
Error: Cask 'java' is unreadable: undefined method `undent' for #<String:0x00007fd4751f2998> when running brew doctor

### ISSUE THREAD

**Issue by seanreed1111** [Homebrew/homebrew-cask#90904]
#### General troubleshooting steps

- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

{{Error: Cask 'java' is unreadable: undefined method `undent' for #<String:0x00007fd4751f2998> when running brew doctor}}

#### Command that failed

```
brew doctor
```

#### Output of command with `--verbose --debug`

```
Warning: Unexpected method 'license' called on Cask java.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Error: Cask 'java' is unreadable: undefined method `undent' for #<String:0x00007ffe8fa1b720>
/usr/local/Caskroom/java/.metadata/1.8.0_102-b14/20160820230236.261/Casks/java.rb:70:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:59:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:59:in `config='
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:46:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:43:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:43:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:87:in `cask'
/usr/local/Caskroom/java/.metadata/1.8.0_102-b14/20160820230236.261/Casks/java.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:72:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:72:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:42:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:36:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:36:in `casks'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:48:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:120:in `<main>'


```

#### Output of `brew doctor --verbose`

```
{{Warning: Unexpected method 'license' called on Cask java.}}
```

#### Output of `brew tap`

```
gschool/learn
homebrew/cask
homebrew/core
homebrew/services
thoughtbot/formulae
weaveworks/tap

```

**Comment by miccal** [comment]
You currently installed version of `java` is from an old version of the Cask file -- please run
```
brew uninstall --force java
```
then
```
rm -r "$(brew --prefix)/Caskroom/java"
```
then
```
brew install java
```
and this may fix your issue.

**Comment by ilciavo** [comment]
Remove previous cask as mentioned [here] (https://github.com/Homebrew/homebrew-cask/issues/63117#issuecomment-491466734) `rm -rf $(brew --prefix)/Caskroom/java`

**Comment by seanreed1111** [comment]
Thank you this solved the problem.
