### ISSUE TITLE
Error: Cask 'java' is unreadable: undefined method `release'

### ISSUE THREAD

**Issue by martinsluka** [Homebrew/homebrew-cask#91488]
#### General troubleshooting steps

- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

{{$ brew doctor
Warning: Unexpected method 'license' called on Cask java.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Error: Cask 'java' is unreadable: undefined method `release' for OS::Mac:Module
}}

#### Command that failed

```
{{brew doctor}}
```

#### Output of command with `--verbose --debug`

```
{{replace this}}
```

#### Output of `brew doctor --verbose`

```
{{$ brew doctor --verbose
Warning: Unexpected method 'license' called on Cask java.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Error: Cask 'java' is unreadable: undefined method `release' for OS::Mac:Module
}}
```

#### Output of `brew tap`

```
{{$ brew tap
homebrew/cask
homebrew/core
survex/survex
}}
```

**Comment by miccal** [comment]
You currently installed version of `java` is from an old version of the Cask file -- please run
```
brew uninstall --force java
```
then
```
rm -r "$(brew --prefix)/Caskroom/java"
```
then
```
brew install java
```
and this may fix your issue.

**Comment by martinsluka** [comment]
Thnx

Martin

Odesláno z iPhonu

27. 10. 2020 v 22:34, Miccal Matthews <notifications@github.com>:
