### ISSUE TITLE
Rename github cask to github-desktop

### ISSUE THREAD

**Issue by mariobrostech** [Homebrew/homebrew-cask#91840]
Hi,

The title for the GitHub Desktop cask is simply `github`, which has the potential to be confusing for newcomers who might get the cask confused with the core `git` package. I don't think it's unreasonable to rename the cask to github-desktop, which is both more descriptive (mirrors the application name) and less confusing to new users (`git` and `github` are more likely to get confused than `git` and `github-desktop`).

Thanks in advance for your consideration!

**Comment by miccal** [comment]
Thank you for the suggestion, but the name currently follows our [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md#simplified-names-of-apps) as it should.
