### ISSUE TITLE
Error: Cask 'java' is unreadable

### ISSUE THREAD

**Issue by dwiggles** [Homebrew/homebrew-cask#92050]
#### General troubleshooting steps

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

So I was trying to brew install black and after a lot of processing and couple of errors which I think I addressed correctly, black doesn't work. When I run brew doctor I get a prompt to submit a bug. So... Now I see this:
dw@Dans-MacBook-Air atomicEC % **brew doctor**
Warning: Unexpected method 'license' called on Cask java.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Error: Cask 'java' is unreadable: undefined method `release' for OS::Mac:Module

#### Command that failed

```
brew doctor
```

#### Output of command with `--verbose --debug`

```
Warning: Unexpected method 'license' called on Cask java.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Error: Cask 'java' is unreadable: undefined method `release' for OS::Mac:Module
/usr/local/Caskroom/java/.metadata/1.8.0_102-b14/20160806204914.728/Casks/java.rb:55:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:59:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:59:in `config='
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:46:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:43:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:43:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:87:in `cask'
/usr/local/Caskroom/java/.metadata/1.8.0_102-b14/20160806204914.728/Casks/java.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:72:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:72:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:42:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:36:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:36:in `casks'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:48:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:120:in `<main>'
dw@Dans-MacBook-Air atomicEC %
```

#### Output of `brew doctor --verbose`

```
dw@Dans-MacBook-Air atomicEC % brew doctor --verbose
Warning: Unexpected method 'license' called on Cask java.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Error: Cask 'java' is unreadable: undefined method `release' for OS::Mac:Module
dw@Dans-MacBook-Air atomicEC %```

#### Output of `brew tap`

```
dw@Dans-MacBook-Air atomicEC % brew tap
homebrew/cask
homebrew/core
dw@Dans-MacBook-Air atomicEC %
```

**Comment by miccal** [comment]
Please see the answer [here](https://github.com/Homebrew/discussions/discussions/113) for a fix to this problem.
