### ISSUE TITLE
docker should be renamed to docker-desktop

### ISSUE THREAD

**Issue by lulor** [Homebrew/homebrew-cask#92100]
With the recent unification of casks and formulae under the same set of commands, it's my understanding that it would be better to differentiate these two categories relying on just the names as much as possible.

Right now `docker` corresponds to both a formula and a cask. In order to install the cask the user has to either run `brew install homebrew/cask/docker` or `brew install docker --cask`.
In order to add clarity to the current situation, I personally think it would be better to rename the cask version to `docker-desktop` since this is already [the official name used by Docker](https://www.docker.com/products/docker-desktop).

**Comment by miccal** [comment]
Thank you for the suggestion, but the name currently follows our [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md#simplified-names-of-apps) as it should.
