### ISSUE TITLE
separate non-free / commercial app casks into another brew tap

### ISSUE THREAD

**Issue by ryh** [Homebrew/homebrew-cask#92714]
### Description of feature/enhancement

separate non-free / commercial app casks like microsoft-office into another brew tap, so users won't see those 

### Justification

I recent use `brew update` found a lot commercial apps like ms office, those are not why I am using brew cask,
please please please make those casks into another tap. Thanks a lot.

### Example use case

`brew tap homebrew/cask-commercial` or something for those casks

**Comment by reitermarkus** [comment]
There is no reason to split these into a separate tap. Users are expected to know what they are installing. Also, splitting these would only result in more work for maintainers for virtually no benefit.

**Comment by ryh** [comment]
@reitermarkus One more thing, maybe new cask tap for Apps works only on Apple Silicon / macOS Big Sur? Or new property `platform` (hardware) / `target` (os) for cask description file

**Comment by vitorgalvao** [comment]
> I recent use `brew update` found a lot commercial apps like ms office, those are not why I am using brew cask

What about the overwhelming majority of your fellow users who *do* want those in an accessible manner? When requesting a feature please think of everyone, not just your needs. In addition, the difference between commercial and non-commercial apps is not clear cut, as we painstakingly found out with `license`.

> One more thing, maybe new cask tap for Apps works only on Apple Silicon / macOS Big Sur?

No, that also makes no sense. What @reitermarkus said above still applies. Please stop suggesting things that only benefit you, we have tons of other users.

> Or new property `platform` (hardware) / `target` (os) for cask description file

Those already exist (with different names) and are in use.

I will urge you to use and spend time with Homebrew Cask before suggesting features that cause so much disruption. If you want to not use and not even see non-commercial software, you’ll need to host your own tap or not use Cask (CLI Homebrew only ships open-source tools).

**Comment by ryh** [comment]
@ who may concern
> Please stop suggesting things that only benefit you
No, I am not using macOS  Big Sur nor Apple Silicon Mac, but sooner or later  users not just me will encounter this problem.

> you’ll need to host your own tap
I already trying to do that...

Whatever...
