### ISSUE TITLE
'brew bump-cask-pr' considers closed PRs when looking for duplicates

### ISSUE THREAD

**Issue by core-code** [Homebrew/homebrew-cask#93014]
one *great* feature of 'brew bump-cask-pr' is that it will not allow you to send duplicate PRs by default.

however the problem is that it also considers closed PRs when looking for duplicates

i think it should

• either be modified to only look at open PRs

• or accept an additional flag so that it will continue if duplicate PRs are closed but stop if duplicate PRs are open (--force will make it go ahead in *any* case which is undesirable)

**Comment by miccal** [comment]
Ping @SeekingMeaning.

**Comment by SeekingMeaning** [comment]
cc @vitorgalvao

**Comment by vitorgalvao** [comment]
The context for this feature is automation, so the solution should likely be the flag instead of changing the default.

**Comment by zachauten** [comment]
When would you want to open a bump pr that had been previously closed? Usually if a pr has been opened and closed previously it's because the version upgrade requires more than a simple automated version bump. I think the vast majority of pr's like this would be guaranteed to fail the ci.

**Comment by core-code** [comment]
@zachauten i think you are talking about formulae and not about casks. the version numbers of casks change a lot, not only up, sometimes down and up again too. there are examples each day. also some contributors close perfectly fine PRs. this means the same PR cannot be sent again although it *needs* to be sent. i have a system that downloads each cask with a static download URL every 4 hours and the PRs it generates are guaranteed to be 100% accurate. however they often fail to send because of limitations in 'brew bump-cask-pr'. i'll just switch back to 'cask-repair' until this is addressed.

**Comment by SeekingMeaning** [comment]
> accept an additional flag so that it will continue if duplicate PRs are closed but stop if duplicate PRs are open

> the solution should likely be the flag instead of changing the default.

What do you propose to call the flag? Possible options: `--ignore-closed-prs`, `--skip-closed-prs`, `--check-open-prs-only` (I'm open to other names)

**Comment by core-code** [comment]
both --ignore-closed-prs and --check-open-prs-only sound sensible to me

**Comment by SeekingMeaning** [comment]
Sorry for the wait—closed cask PRs are now ignored by default

**Comment by vitorgalvao** [comment]
Thank you, @SeekingMeaning.
