### ISSUE TITLE
Building app's from source for homebrew cask.

### ISSUE THREAD

**Issue by jameshilliard** [Homebrew/homebrew-cask#93088]
### Description of feature/enhancement

A bunch of the upstreams for opensource qt based gui apps these days don't publicly distribute useable binaries anymore. Homebrew should build these apps from source using the CI infrastructure.

### Justification

Since qt apps are slow and difficult to compile it would greatly speed up installation if homebrew would pre-compile these apps using formulas.

### Example use case

Apps such as [pgmodeler](https://github.com/pgmodeler/pgmodeler) or [rdm](https://github.com/uglide/RedisDesktopManager) are currently entirely unavailable on homebrew since they need to be built from source but are not cli apps.

**Comment by vitorgalvao** [comment]
There are other issues on this, going back several years. We don’t have facilities to build from source in casks. A handful of apps don’t justify adding the feature.

Instead, ask the upstream developers to provide binaries or offer to help them build them.

**Comment by vitorgalvao** [comment]
Or make them as formulae and host them in your tap.

**Comment by jameshilliard** [comment]
> There are other issues on this, going back several years. We don’t have facilities to build from source in casks. A handful of apps don’t justify adding the feature.

Can we not just reuse the regular build infrastructure from homebrew-core for this?

> Instead, ask the upstream developers to provide binaries or offer to help them build them. Or make them as formulae and host them in your tap.

This is mostly an issue for upstreams like pgmodeler or rdm that deliberately don't distribute binaries, I can build the project just fine and write a homebrew formula.

**Comment by reitermarkus** [comment]
> Can we not just reuse the regular build infrastructure from homebrew-core for this?

Sure you *can*, but that doesn't really help, because formulae have no way to actually install GUI apps, which is why we don't accept formulae that build GUI apps in `homebrew-core`.

As @vitorgalvao said, your best bet is to convince/help upstream to distribute binaries or to create your own tap.

**Comment by jameshilliard** [comment]
> because formulae have no proper way to actually install GUI apps

What's the issue here? Seemed to work fine for me last time I tried with `prefix.install`, basically the exact same way as the existing GUI apps in `homebrew-core` that seem to be grandfathered in from before the new non-GUI apps in `homebrew-core` policy was added work.

> which is why we don't accept formulae that build GUI apps in `homebrew-core`

There are GUI apps in `homebrew-core` such as [tarsnap-gui](https://github.com/Homebrew/homebrew-core/blob/master/Formula/tarsnap-gui.rb) that work fine from what I can tell so this doesn't appear to be a technical issue.

> convince/help upstream to distribute binaries

Since the lack of binaries is deliberate for these projects I don't think that's going to happen.

> create your own tap.

How would binaries get built if I did it that way? Is there a way to make that work without setting up my own CI infrastructure?

**Comment by reitermarkus** [comment]
> How would binaries get built if I did it that way?

There has just been a blog post on how to set up a tap with bottles here: https://brew.sh/2020/11/18/homebrew-tap-with-bottles-uploaded-to-github-releases/

**Comment by jameshilliard** [comment]
> There has just been a blog post on how to set up a tap with bottles here: https://brew.sh/2020/11/18/homebrew-tap-with-bottles-uploaded-to-github-releases/

Oh, neat, could this potentially be used to allow building `.app`'s from source(for just the upstream projects that don't do binary builds) for the `homebrew-cask` tap as well? I'm thinking in regards to how the trusted binary issue could be solved potentially.

**Comment by vitorgalvao** [comment]
> Oh, neat, could this potentially be used to allow building `.app`'s from source(for just the upstream projects that don't do binary builds) for the `homebrew-cask` tap as well?

No.

> I'm thinking in regards to how the trusted binary issue could be solved potentially.

Because of that.

**Comment by jameshilliard** [comment]
> Because of that.

I mean, couldn't we just enable this feature in the `homebrew-cask` repo itself?

**Comment by vitorgalvao** [comment]
> I mean, couldn't we just enable this feature in the `homebrew-cask` repo itself?

Have you looked at casks and formulae? They’re built differently, this is not a case of “start using the same lines to begin compiling software in casks”. Is it worth it to port functionality over for a handful of apps, especially when that will eventually mean dealing with signing them? I don’t think it is.

**Comment by jameshilliard** [comment]
> Have you looked at casks and formulae?

Not in too much depth, I've written a normal formula for one of these gui apps though.

> Is it worth it to port functionality over for a handful of apps

Would it be difficult to reuse the code for building normal formula bottles for this? I think a build cask from source feature could potentially be also used by upstream projects for their own `.app` packaging so seems like it could be worthwhile even if not used a whole lot in homebrew itself. A lot of the toolchains/dependencies for these qt/gui apps can be pretty tricky to get working consistently without something like a homebrew formula that can resolve/set dependency paths/configs as part of the build.

> especially when that will eventually mean dealing with signing them

I would think that would be no different from however normal bottles/non-gui apps would be signed for the most part right?

**Comment by reitermarkus** [comment]
> Would it be difficult to reuse the code for building normal formula bottles for this?

Yes it would be, otherwise it would have been done. Casks and formulae work in vastly different ways, you cannot *just* reuse one part in the other without making huge changes.
