### ISSUE TITLE
`app` stanza should `uninstall :quit` or `uninstall :trash` automatically

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-cask#9312]
As per https://github.com/caskroom/homebrew-cask/pull/7801#issuecomment-65914837.

**Comment by phinze** [comment]
Totally! This would be awesome.

I can see arguments for both sides. I guess I'd lean towards `:quit` being more helpful - trusting the intention of the `uninstall` we've been issued. It seems much more likely a user attempts to uninstall a program they accidentally (or unknowingly) have running in the background than they accidentally uninstall a program they wanted to keep running.

**Comment by vitorgalvao** [comment]
> I guess I'd lean towards `:quit` being more helpful

Agreed.

**Comment by reitermarkus** [comment]
I think we can close this in favour of https://github.com/Homebrew/homebrew-cask/issues/16339.
