### ISSUE TITLE
Cask 'hopper-disassembler' definition is invalid: invalid 'depends_on macos' value: unknown or unsupported macOS version: :lion

### ISSUE THREAD

**Issue by xuanmings** [Homebrew/homebrew-cask#93369]
After 'brew doctor' command,here are many errors: 
Warning: Unexpected method 'license' called on Cask betterzipql.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Warning: Unexpected method 'license' called on Cask hopper-disassembler.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Error: Cask 'hopper-disassembler' definition is invalid: invalid 'depends_on macos' value: unknown or unsupported macOS version: :lion

**Comment by xuanmings** [comment]
solution :https://github.com/Homebrew/homebrew-cask/issues/58046
but new errors: 
Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python@2
Error: unknown or unsupported macOS version: :mountain_lion

**Comment by miccal** [comment]
> solution :#58046
> but new errors:
> Warning: You have unlinked kegs in your Cellar.
> Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
> those kegs to fail to run properly once built. Run `brew link` on these:
> python@2
> Error: unknown or unsupported macOS version: :mountain_lion

This is an issue with a formula, so you will need to report this to the `homebrew-core` repository.
