### ISSUE TITLE
Teamviewer  checksum doesn't match

### ISSUE THREAD

**Issue by bzumik1** [Homebrew/homebrew-cask#93459]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

I am not able to install teamviewer because of: "Checksum for Cask 'teamviewer' does not match."

#### Command that failed

```
brew install teamviewer
```

#### Output of command with `--verbose --debug`

```
==> Caveats
WARNING: teamviewer has a bug in Catalina where it doesn't deal well with being uninstalled by other utilities.
The recommended way to remove it is by running their uninstaller under:

   Preferences → Advanced

==> Downloading https://download.teamviewer.com/download/TeamViewer.dmg
==> Downloading from https://dl.teamviewer.com/download/version_15x/TeamViewer.dmg
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'teamviewer'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'teamviewer' does not match.
Expected: 39da48b95ad91ab1aabe8b4fbc43b6e9cc5fa0f31940d8e9cb2f15fd1408871b
  Actual: 220067b109a5148b2799b973cdb8117f2975b536a42bd0c9126e48aac2c495cb
    File: /Users/jakub/Library/Caches/Homebrew/downloads/be05736e528dcf66445ab64fbce55935ab099e89bc1ce99f07b9aa827d3ea6e4--TeamViewer.dmg
To retry an incomplete download, remove the file above.
If the issue persists, visit:
  https://github.com/Homebrew/homebrew-cask/blob/HEAD/doc/reporting_bugs/checksum_does_not_match_error.md
```

#### Output of `brew doctor --verbose`

```
{{replace this}}
```

#### Output of `brew tap`

```
{{replace this}}
```

**Comment by vitorgalvao** [comment]
> * [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

That’s exactly what that is.

**Comment by bzumik1** [comment]
Oh, I am so sorry I overlooked the **NOT**.

**Comment by bzumik1** [comment]
> > * [x]  I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.
> 
> That’s exactly what that is.
Oh, I am so sorry I overlooked the **NOT**.

**Comment by vitorgalvao** [comment]
`brew bump-cask-pr --version 15.12.4 teamviewer` will fix it. I’m already running it but the connection is slow.
