### ISSUE TITLE
Tracking Issue: “bom contains no files, nothing copied”

### ISSUE THREAD

**Issue by reitermarkus** [Homebrew/homebrew-cask#93482]
Let's try to figure out this error. @Homebrew/cask, please append PRs where this happens to the list below:

- https://github.com/Homebrew/homebrew-cask/pull/85673 (balenaetcher)
- https://github.com/Homebrew/homebrew-cask/pull/89709 (browserosaurus)
- https://github.com/Homebrew/homebrew-cask/pull/90070 (sizzy)
- https://github.com/Homebrew/homebrew-cask/pull/92091 (vrew)
- https://github.com/Homebrew/homebrew-cask/pull/93470 (goodsync)
- https://github.com/Homebrew/homebrew-cask/pull/93534 (trainerroad)

**Comment by core-code** [comment]
https://github.com/Homebrew/homebrew-cask/pull/93534

**Comment by core-code** [comment]
fixed? awesome!

**Comment by reitermarkus** [comment]
fixed?

Worked around, rather. Hopefully … 😉
