### ISSUE TITLE
Warning: Calling brew cask install is deprecated! Use brew install [--cask] instead.

### ISSUE THREAD

**Issue by simonhaenisch** [Homebrew/homebrew-cask#93556]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

```
Warning: Calling brew cask install is deprecated! Use brew install [--cask] instead.
```

#### Command that failed

```
brew cask install some-formula
```

But when I go to the website:

<img width="863" src="https://user-images.githubusercontent.com/3410759/100224192-cc69af00-2f1c-11eb-81ce-06cfbf7a72b3.png">

When I go to the Github repo's readme:

```
$ brew cask install atom
```

---

Where can I find out about this new `--cask` flag? What benefit has it that makes it worth typing two extra characters to install a cask formula now? Why has the `cask` command been deprecated before there's any doc updates?

**Comment by vitorgalvao** [comment]
> Where can I find out about this new `--cask` flag?

`man brew`.

> Why has the `cask` command been deprecated before there's any doc updates?

It wasn’t. The website is probably the only place where we forgot. The `man` page is the authorative source.

> What benefit has it that makes it worth typing two extra characters to install a cask formula now?

Not a “cask formula”, just “cask”. You *don’t* need to type two extra characters, you can type four less: `--cask` is useful for disambiguation but not mandatory (which is why it’s in brackets, common notation for an optional command), `brew install firefox` works.
