### ISSUE TITLE
Update deprecated brew cask command throughout repository

### ISSUE THREAD

**Issue by strafe** [Homebrew/homebrew-cask#93737]
`brew cask [...]` still appears [quite a lot](https://github.com/Homebrew/homebrew-cask/search?q=%22brew+cask%22) in this repo, even in the README.

**Comment by vitorgalvao** [comment]
Well, yes, we’re aware of it, but what we need are PRs or an issue that points out every place where it needs fixing (which wouldn’t be too useful, because might as well PR at that point). Just pointing it out isn’t necessary.

**Comment by strafe** [comment]
@vitorgalvao I tried to do a new gif previously but, wasn't able to get the same filesize/fps tradeoff that you were in the current one, even after referencing your PR to add the initial one a few years ago. Would this one be acceptable?

- I think it's best to avoid mentions of homebrew, brew, hbc and caskroom in the prompt as it may confuse novice CLI users.
- It's recorded on Big Sur and with the zsh shell since this will be the default, and hopefully look familiar for a lot of people going forward.

![out mp4](https://user-images.githubusercontent.com/15663890/100484618-11e0d480-30f5-11eb-8083-ef5c932b64ec.gif)

[If you're able to generate a GIF of equal quality from the video, that would be great too.](https://github.com/Homebrew/homebrew-cask/files/5609571/vid.zip)
