### ISSUE TITLE
Cask installs and reinstalls cask that doctor says does not exist

### ISSUE THREAD

**Issue by jasonhemann** [Homebrew/homebrew-cask#94058]
#### General troubleshooting steps

- [X ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`. N/A
- [X ] I ran `brew update-reset && brew update` and retried my command.
- [X ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Cask says `swi-prolog` is unavailable, and yet I can install, uninstall, and reinstall it. 

#### Command that failed

```
07:30:29$ brew doctor
Error: Cask 'swi-prolog' is unavailable: No Cask with this name exists.
07:31:04$ brew install swi-prolog
Warning: swi-prolog 8.2.3 is already installed and up-to-date
To reinstall 8.2.3, run `brew reinstall swi-prolog`
07:31:10$
```

#### Output of command with `--verbose --debug`

```
07:30:13$ brew doctor --verbose --debug
Error: Cask 'swi-prolog' is unavailable: No Cask with this name exists.
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:196:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:205:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:47:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:39:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:39:in `casks'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:51:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'
[jhemann:~] 07:30:22$ brew install swi-prolog --verbose --debug
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/swi-prolog.rb
Warning: swi-prolog 8.2.3 is already installed and up-to-date
To reinstall 8.2.3, run `brew reinstall swi-prolog`
```

#### Output of `brew doctor --verbose`

```
07:31:10$ brew doctor --verbose
Error: Cask 'swi-prolog' is unavailable: No Cask with this name exists.
```

#### Output of `brew tap`

```
07:32:15$ brew tap
github/gh
homebrew/cask
homebrew/cask-drivers
homebrew/cask-versions
homebrew/core
railwaycat/emacsmacport
```

**Comment by miccal** [comment]
That is because `swi-prelog` was migrated from a [Caks to a Formula](https://github.com/Homebrew/homebrew-cask/pull/23911).

Please run:
```
rm -r "$(brew --prefix)/Caskroom/swi-prelog"
```
which should fix your issue.
