### ISSUE TITLE
source not there instructions predate cask integration; assume archives

### ISSUE THREAD

**Issue by jasonhemann** [Homebrew/homebrew-cask#94068]
### Description of feature/enhancement

Make the source not there instructions uniform for casks as well as formulae

### Justification

Right now the source not there instructions implicitly presume (by asking users to unpack the formula) that the problem formula is an tarball archive. .dmg files, for instance, AFAIK, don't unzip the same way. 

### Example use case

Any cask formula doctor says is "not there"

**Comment by miccal** [comment]
Are you able to provide an example of what you mean?

**Comment by jasonhemann** [comment]
https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/source_is_not_there_error.md#readme:~:text=Navigate%20there%20and%20manually%20unpack%20it.%20As

**Comment by vitorgalvao** [comment]
I don’t see a problem there. Those instructions were always made for casks only and they’re as valid as ever, barring the outdated `brew cask fetch` command. Do formulae even suffer from `source not there`?

Please be specific. A link to a text portion of our documentation doesn’t clarify what you mean.

**Comment by vitorgalvao** [comment]
Or better yet, make a PR with exactly what you think should be changed. It’s a single documentation file, so that’s bound to be faster than trying to describe what you see as the issue.

**Comment by jasonhemann** [comment]
Well then I'm gonna close this out under the assumption that I'm mistaken.
