### ISSUE TITLE
source not there .md instructions use deprecated features, should upgrade to force --cask and cat --cask

### ISSUE THREAD

**Issue by jasonhemann** [Homebrew/homebrew-cask#94066]
### Description of feature/enhancement

source not there .md instructions use deprecated features, should upgrade to force --cask and cat --cask

### Justification

It's confusing and potentially a future problem to tell users to rely on these deprecated features. Shouldn't be encouraged. 

### Example use case

See the instructions in the file on this repo. C+f 'brew cask'

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/issues/93737#issuecomment-734941449
