### ISSUE TITLE
webex-meetings cask is dated for big sur

### ISSUE THREAD

**Issue by edestecd** [Homebrew/homebrew-cask#94229]
#### Description of issue

Webex Meetings will install correctly but it appears to be at an older version.
Video does not work with this older version. When I install the pkg from the browser video works. When I install from homebrew my camera is not recognized.

I am unsure of how to update the formula atm but am willing to try with some help to install the latest pkg.
It is worth noting that the current formula seems to install an older app and the web launch app (2 apps in mac)
whereas the new one only install the one web launch app.

**Comment by miccal** [comment]
Can you provide a `url` for the newer version you speak of? Downloading from [here](https://www.webex.com/downloads.html) gives me the exact same `.dmg` as the Cask.

**Comment by peterlewis** [comment]
Just to add, I've updated WebEx Meetings from within the application and the latest version available for installation appears to be `40.12.3.11`.

The `.pkg` within the [`.dmg` linked by the cask](https://akamaicdn.webex.com/client/webexapp.dmg) also appears to install `40.12.3.11`.

**Comment by peterlewis** [comment]
Ah righty ho, I see the issue, I think! When you download WebEx from within an active meeting, it downloads a much-smaller package (`Webex.pkg`) that only installs the `Cisco Webex Start.app` component.

**Comment by edestecd** [comment]
Correct you only get the pkg, which reports a version of 40.12.3.11

**Comment by edestecd** [comment]
So I am not sure why one works and the other does not since they both seem to be at the same version. The only difference is that you get 2 apps with the DMG.

**Comment by peterlewis** [comment]
I believe that the version downloaded from within the call is designed to be a quick connect client, i.e. not containing the full software and just containing the bare minimum to join a session?

Whilst I appreciate that this doesn't answer your predicament of why this lite client works, whilst the full client does not, I wouldn't say it would be a good idea to replace the existing cask with this slimmed-down install, personally.

**Comment by edestecd** [comment]
I agree and now the slim client is failing for me after a reboot so now I believe the cask is just fine and webex meetings has a bug.
