### ISSUE TITLE
Transitioning from "verified" comment to verified parameters

### ISSUE THREAD

**Issue by gtmgianni** [Homebrew/homebrew-cask#94698]
I've created a small Python script to convert the `# [url] was verified as official when first introduced to the cask` comments in cask files to `verified: [url]`.

I ran `brew style --fix` to correct any style errors, then manually adjusted a few cask files until `brew style` returned no errors.

~~You can view the changes on this branch: https://github.com/gtmgianni/homebrew-cask/tree/verified~~

I thought it would be wise to create an issue rather than a pull request, since I'm not sure if I've gone about this the right way (e.g. Would it be better to create separate commits/pull requests for each cask? Or perhaps there is already a plan in place to transition from verified comments to verified parameters?)

**Comment by vitorgalvao** [comment]
> Would it be better to create separate commits/pull requests for each cask?

Yes, please. But phase them; no more than 20 or 30 at a time. This is so the ones that fail CI for unrelated reasons don’t accumulate.

**Comment by gtmgianni** [comment]
@vitorgalvao Is there a way to automate merging of the casks which pass the CI? I'm conscious that there are just under 3000 casks which need adjusting, and don't want to create unnecessary work for the maintainers.

Alternatively, I could submit a specific number of pull requests each day to avoid a significantly increased workload.

**Comment by vitorgalvao** [comment]
> Is there a way to automate merging of the cask PRs which pass the CI?

Yes, but not for this particular change (as it should be).

> Alternatively, I could submit a specific number of pull requests each day to avoid a significantly increased workload.

That sounds good. I can accept/merge PRs fast via a custom tool.

**Comment by gtmgianni** [comment]
Whenever I run the script, I set it to submit PRs in a batch of about 30.

> That sounds good. I can accept/merge PRs fast via a custom tool.

In that case, I'll continue to submit a new batch once the CI has caught up. I'll try to avoid times where other contributors' scripts are also submitting PRs, as I assume there's a limit on how many CI jobs can be running concurrently.

**Comment by reitermarkus** [comment]
@gtmgianni, your script seems to be going rogue. More than 90 PRs open are now queued at https://github.com/Homebrew/homebrew-cask-fonts/pulls/gtmgianni.

I have temporarily limited the repo to collaborators to block any new PRs.

**Comment by gtmgianni** [comment]
@reitermarkus It's not going rogue – I'm not going to have access to my computer for the rest of today, so wanted to submit a larger batch of PRs which could be processed while I'm gone. (I set the last group size to 65 PRs)

However, in future I can stick to submitting PRs in groups of up to 30, as I understand why you (or other collaborators) would limit the repository if you saw lots of PRs coming in.

**Comment by reitermarkus** [comment]
Basically, this will block CI for hours, since the workers are shared across the whole Homebrew organization, so you should really limit it to 30 at a time at max.

**Comment by gtmgianni** [comment]
I was not aware it would have this effect across the whole Homebrew organisation, thank you for informing me of this. I'll stick to 30 PRs at a time in future.

**Comment by reitermarkus** [comment]
I'd say that even 30 at a time is too much, since this will block CI for ~150 minutes (30*5). Maybe 10 per hour, or 5 minutes delay between each PR so that other PRs can be “interleaved“ so to say.

**Comment by gtmgianni** [comment]
Tomorrow I'll either automate the script to submit PRs every 5 minutes, or I'll manually set it to submit PRs in batches of 10. 

I'm usually hesitant to fully automate a script, especially if I'm not there to stop its execution, so I'll build in some failsafes so that the script (in theory) stops execution upon encountering any error. I guess I can always revoke my `hub` personal OAuth token using my phone, to prevent PRs from being submitted if I need to stop the script remotely.
