### ISSUE TITLE
brew bump-cask-pr should not add a checksum when a cask is versioned and has :no_check

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-cask#94942]
With https://github.com/Homebrew/brew/pull/9423 and other changes, we’re going to have a lot of casks that have a `version` but `sha256 :no_check`. `brew bump-cask-pr` should be updated to handle those.

When `brew bump-cask-pr` is called, if the cask is NOT `version :latest` but IS `sha256 :no_check`, do not update `sha256` unless the user specifically submitted one with `--sha256`.

Ping @reitermarkus @core-code @SeekingMeaning in case I forgot something.

@SeekingMeaning There’s this and a few other `bump-cask-pr` issues on this tracker. Are you available to continue the work on those? As it is, it still doesn’t replace `cask-repair` for most needed automation cases.

**Comment by vitorgalvao** [comment]
@SeekingMeaning There’s this and a few other `bump-cask-pr` issues on this tracker. Are you available to continue the work on those? As it is, it still doesn’t replace `cask-repair` for most needed automation cases.

**Comment by SeekingMeaning** [comment]
This should be fixed with `brew` version 2.6.2
