### ISSUE TITLE
brew bump-cask-pr should ignore downgrades

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-cask#94944]
As pointed out in https://github.com/Homebrew/homebrew-cask/issues/93013#issuecomment-730714988 and https://github.com/Homebrew/homebrew-cask/issues/93014#issuecomment-735487550, `brew bump-cask-pr` sometimes mistakes upgrades for downgrades, but it also doesn’t take into account that downgrades for apps are often necessary.

Seeing as an increasing amount of version bumps are handled by automation controlled by maintainers, there should be no version checking on `bump-cask-pr`. @BrewTestBot already does the downgrade/upgrade check on submissions anyway, and that’s the time to decide if they should be approved or closed, not before they are submitted.

Pinging @reitermarkus @core-code @SeekingMeaning.

**Comment by SeekingMeaning** [comment]
Is it safe to assume the the actual version number is always the part before the comma (if the version string contains a comma)?

**Comment by core-code** [comment]
what 'actual version number' do you mean? each macOS app has at least two version numbers: CFBundleShortVersionString (user visible) and CFBundleVersion (the technically relevant one). often those are the same but not always.

**Comment by vitorgalvao** [comment]
> Is it safe to assume the the actual version number is always the part before the comma (if the version string contains a comma)?

No, not always. The part before the command may be CFBundleVersion, CFBundleShortVersionString, or a third value used for interpolation in `url` (though these days those are less often before the comma).

**Comment by SeekingMeaning** [comment]
Relevant comments for posterity:

https://github.com/Homebrew/homebrew-cask/issues/93013#issuecomment-730714988

> also
> 1.) it will not send downgrades even with the --force option. downgrades are quite common for casks
> 
> 2.) it misdetects what a downgrade is. it thinks this upgrade is a downgrade:
> 
> ```
> 
> brew bump-cask-pr --force --message 'Automatically created and submitted by muUpdateStaticHomebrewCask' --no-browse --sha256 '35693e38179cda5beabf8f4eff7bc9cc0c423086c248598734b74b393abde67d' --version '1.3.2,74' sensei
> 
> Error: You need to bump this cask manually since changing the
> version from 1.3,71 to 1.3.2,74 would be a downgrade.
> ```

https://github.com/Homebrew/homebrew-cask/issues/93013#issuecomment-734771700

> another valid update that is impossble to make because it is considered as a 'downgrade'
> 
> `brew bump-cask-pr --force --no-browse --sha256 'f7067016df7488b6676d7dff16282796278a0b8e47d5e908b0a65b9609f06e6d' --version '1.4.1,135' touchswitcher; `

**Comment by SeekingMeaning** [comment]
If I remember right, the version `1.3,71` is seen as older than `1.3.2,74` because the `Version` class checks each token individually, i.e. `1 == 1`, `3 == 3`, `71 > 2`

Currently, there is no mechanism for `bump-cask-pr` to correctly compare cask versions

**Comment by core-code** [comment]
the appcast check always only considers the left part of the version stanza if there is a ',' or a '-'

i think something similar should done here

**Comment by SeekingMeaning** [comment]
This should be fixed with `brew` version 2.6.2
