### ISSUE TITLE
Error: Cask 'spotify' definition is invalid

### ISSUE THREAD

**Issue by RobertFloor** [Homebrew/homebrew-cask#95007]
On brew upgrade I get the error: 

Error: Cask 'spotify' definition is invalid: invalid 'depends_on macos' value: unknown or unsupported macOS version: :lion
Mac OS 11

**Comment by gtmgianni** [comment]
@RobertFloor Please use the provided [Bug Report](https://github.com/Homebrew/homebrew-cask/issues/new?template=01_bug_report.md) issue template, otherwise your issue may be [closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/issues/58046#issue-403953746

**Comment by RobertFloor** [comment]
Super it was fixed with the command:
/usr/bin/find "$(brew --prefix)/Caskroom/"*'/.metadata' -type f -name '*.rb' -print0 | /usr/bin/xargs -0 /usr/bin/perl -i -pe 's/depends_on macos: \[.*?\]//gsm;s/depends_on macos: .*//g'
