### ISSUE TITLE
unable to install FileZilla

### ISSUE THREAD

**Issue by WeisseTeetasse** [Homebrew/homebrew-cask#95014]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Filezilla installation gives the following error:
Error: Cask 'filezilla' definition is invalid: invalid 'depends_on macos' value: unknown or unsupported macOS version: :mavericks

#### Command that failed

```
brew install filezilla
```

#### Output of command with `--verbose --debug`

```
Updating Homebrew...
Error: Cask 'filezilla' definition is invalid: invalid 'depends_on macos' value: unknown or unsupported macOS version: :mavericks
/usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:229:in `rescue in depends_on'
/usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:226:in `depends_on'
/usr/local/Caskroom/filezilla/.metadata/3.35.2/20180820214746.032/Casks/filezilla.rb:10:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:61:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:61:in `config='
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:48:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:43:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:43:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:87:in `cask'
/usr/local/Caskroom/filezilla/.metadata/3.35.2/20180820214746.032/Casks/filezilla.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:72:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:72:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:205:in `load'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:98:in `load_formula_or_cask'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:50:in `block in to_formulae_and_casks'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:49:in `each'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:49:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:49:in `to_formulae_and_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:154:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'
```

#### Output of `brew doctor --verbose`

```
Error: Cask 'filezilla' definition is invalid: invalid 'depends_on macos' value: unknown or unsupported macOS version: :mavericks
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/core
```

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/issues/58046#issue-403953746
