### ISSUE TITLE
Cannot install Punto Switcher

### ISSUE THREAD

**Issue by mmalchuk** [Homebrew/homebrew-cask#95089]
==> Downloading https://yandex.ru/soft/punto/download/?os=mac
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.6.1\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.7\)\ curl/7.64.1 --header Accept-Language:\ en --fail --retry 3 --location --remote-time --continue-at 0 --output /Users/mmalchuk/Library/Caches/Homebrew/downloads/35eaa837b1b90ba7147f708c2e50f73b05aa2ae854a78ccf7d319438c90a9cfa--\?os=mac.incomplete https://yandex.ru/soft/punto/download/\?os=mac
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  859k    0  859k    0     0  2133k      0 --:--:-- --:--:-- --:--:-- 2133k
Warning: No checksum defined for cask 'punto-switcher', skipping verification.
==> Installing Cask punto-switcher
cp -p /Users/mmalchuk/Library/Caches/Homebrew/downloads/35eaa837b1b90ba7147f708c2e50f73b05aa2ae854a78ccf7d319438c90a9cfa--?os=mac /usr/local/Caskroom/punto-switcher/latest/download
==> Running installer for punto-switcher; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> Purging files for version latest of Cask punto-switcher
Error: pkg source file not found: 'PuntoSwitcher Installer.pkg'

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
