### ISSUE TITLE
audit: ignore `verified` on `url do` blocks

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-cask#95081]
As per https://github.com/Homebrew/homebrew-cask-versions/pull/10048#discussion_r538972290.

- [x] Make `audit` ignore the need for `verified` on `url do` block.
- [x] Remove the `was verified as official when first introduced to the cask` comment on every cask with `url do`.

Ping @reitermarkus @gtmgianni.

**Comment by yhu266** [comment]
For the item
> Remove the `was verified as official when first introduced to the cask` comment on every cask with `url do`.

Is it supposed to be done individually? Or is there a script in development to remove all of them in one go?

**Comment by reitermarkus** [comment]
@yhu266, see https://github.com/Homebrew/homebrew-cask/issues/94698.
