### ISSUE TITLE
Brew bump-cask-pr should respect sig int

### ISSUE THREAD

**Issue by korthout** [Homebrew/homebrew-cask#95518]
### Description of feature/enhancement

I accidentally forgot to add `--dry-run` to the `brew bump-cask-pr` command I wanted to test, so I had to kill it. To my surprise, `SIGKILL` (i.e. CTRL+c in iTerm2) did bring back my prompt, but continued to execute in the background. I could see this because the output still arrived in standard out. 

### Justification

I think that commands should be able to be killed like any other. And the expected behaviour is to also kill subprocesses / background processes that were started by the main process.

### Example use case

Command I ran: `brew bump-cask-pr --version 0.11.0 zeebe-modeler --sha256 6d0e08b53959d4c38afe193fdc3f3113c0f46403a55574f4359d23d1e1313891`.
After a few likes of output, I followed with a `SIGKILL` using CTRL+c.
Prompt came back, but output continued.

**Comment by vitorgalvao** [comment]
You don’t need to specify `--sha256`. This bug report is valid, but please make it on https://github.com/Homebrew/brew because it pertains to the core.
