### ISSUE TITLE
Is there a way to prevent homebrew cask installing package like 'brew pin package'

### ISSUE THREAD

**Issue by justdayan** [Homebrew/homebrew-cask#95622]
When I try to upgrade my packages, I get this error:

==> Upgrading 1 outdated package:
qlcolorcode 3.1.1 -> 4.0.0
==> Upgrading qlcolorcode
==> Purging files for version 4.0.0 of Cask qlcolorcode
Error: qlcolorcode: macOS Catalina or newer is required for this software.

-----
I would like not to update the version, because I'm not using Catalina, and won't upgrading to that version of macOS.

Is there a way to do this with cask?

Thank you in advance for any assistance.

jD

**Comment by vitorgalvao** [comment]
This is missing information.

> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.
