### ISSUE TITLE
brew install google-cloud-sdk results in compinit warnings

### ISSUE THREAD

**Issue by jasikpark** [Homebrew/homebrew-cask#95710]
#### General troubleshooting steps

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

When google-cloud-sdk is installed, it installs zsh completions in /usr/local/share/zsh and /usr/local/share/zsh/site-functions

When reloading the shell, compinit complains: 
```
zsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]? y
calebjasik@Calebs-MacBook-Pro rust-p2p-example % 
calebjasik@Calebs-MacBook-Pro rust-p2p-example % compaudit
There are insecure directories:
/usr/local/share/zsh/site-functions
/usr/local/share/zsh
```

`ls -al` shows that the group has write access, which is what is being complained about. https://unix.stackexchange.com/questions/383365/zsh-compinit-insecure-directories-run-compaudit-for-list

I'm not sure whether this is due to the homebrew recipe or the install script for google-cloud-sdk

#### Command that failed

```
{{replace this}}
```

#### Output of command with `--verbose --debug`

```
{{replace this}}
```

#### Output of `brew doctor --verbose`

```
{{replace this}}
```

#### Output of `brew tap`

```
{{replace this}}
```

**Comment by vitorgalvao** [comment]
> I'm not sure whether this is due to the homebrew recipe or the install script for google-cloud-sdk

Seeing as we [basically run the script](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/google-cloud-sdk.rb#L14L21), it’s either the latter (and should be reported upstream) or an oddity in your setup.
