### ISSUE TITLE
How to create a cask with different binaries for intel / M1

### ISSUE THREAD

**Issue by kortenkamp** [Homebrew/homebrew-cask#95776]
I would like to create a cask that uses different binaries (i.e. URLs) for Intel and M1 processors. Unfortunately the app is not available (yet) as a universal binary. What is the recommend way to do this?  Or better: is it possible at all?

**Comment by miccal** [comment]
Thank you for your interest in helping out @kortenkamp, but we do not wish to add ARM-specific Casks until Hombrew itself officially supports ARM-only Mac's and https://github.com/Homebrew/brew/issues/7857 has been resolved.

**Comment by kortenkamp** [comment]
Ok, that’s fine. But it should be kept in mind that this might be necessary some day.

**Comment by domoritz** [comment]
Now that https://github.com/Homebrew/brew/issues/7857 is closed, how do you imagine a formula could support binaries/downloads for different architectures?

**Comment by vitorgalvao** [comment]
We should start dealing with this. @reitermarkus What’s the best syntax we have for it right now? Do we have something like `MacOS.arch` for conditionals?

**Comment by reitermarkus** [comment]
We have `Hardware::CPU.arm?`.

**Comment by vitorgalvao** [comment]
> We have `Hardware::CPU.arm?`.

Maybe we should default to the reverse? `if Hardware::CPU.intel?`, to follow the same logic has `MacOS.version`, where what comes after is in the `else`.

@domoritz Do you want to update your PR accordingly?

**Comment by domoritz** [comment]
Ehh, how do I provide multiple binaries and choose by architecture? I'm not very familiar with ruby. Do you have an example I could look at?

**Comment by vitorgalvao** [comment]
@domoritz Search for `if MacOS.version` on other casks (same logic).

I’m on a phone now or I’d link you and be more precise. If the explanation was insufficient, let me know.

**Comment by domoritz** [comment]
That was exactly what I needed. I sent https://github.com/Homebrew/homebrew-cask/pull/97538.
