### ISSUE TITLE
Garmin Basecamp upgraded to 4811

### ISSUE THREAD

**Issue by metbril** [Homebrew/homebrew-cask#96049]
#### General troubleshooting steps

- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

The `garmin-basecamp` cask is not working. As of 16 December, the proper download link is

    https://download.garmin.com/software/BaseCampforMac_4811.dmg

#### Command that failed

```
brew install garmin-basecamp --cask
```

#### Output of command with `--verbose --debug`

```
==> Downloading https://download.garmin.com/software/BaseCampforMac_4810.dmg
#=#=#                                                                         
curl: (22) The requested URL returned error: 404 
Error: Download failed on Cask 'garmin-basecamp' with message: Download failed: https://download.garmin.com/software/BaseCampforMac_4810.dmg
```

#### Output of `brew doctor --verbose`

```
{{replace this}}
```

#### Output of `brew tap`

```
{{replace this}}
```

**Comment by miccal** [comment]
Fixed in https://github.com/Homebrew/homebrew-cask-drivers/pull/1988:
```
|-> brew fetch garmin-basecamp
==> Downloading https://download.garmin.com/software/BaseCampforMac_4811.dmg
######################################################################## 100.0%
Downloaded to: /Users/miccal/Library/Caches/Homebrew/downloads/c31c6bf081362b8817aaeaa8fe961d55d79e549f06cabeb6790e74b1fe059281--BaseCampforMac_4811.dmg
SHA256: f6c15afd513eefa17bd96c7ba062ccf0af441c92b014ab350e029cd57b2280e2
```
