### ISSUE TITLE
Bug in PR #96013 created by BrewTestBot

### ISSUE THREAD

**Issue by thecesrom** [Homebrew/homebrew-cask#96054]
There seems to be an error with this change. My current installed version (which I initially installed via `brew install --cask box-drive`) is now version `2.19.292`, which is greater than `2.18.117`.

Since the download link does not contain a version, using `version :latest` should be correct.

_Originally posted by @thecesrom in https://github.com/Homebrew/homebrew-cask/issues/96013#issuecomment-748505777_

**Comment by thecesrom** [comment]
Additionally, running `brew upgrade` gets stuck.

```bash
$ brew upgrade
==> Casks with `auto_updates` or `version :latest` will not be upgraded; pass `--greedy` to upgrade them.
==> Upgrading 1 outdated package:
box-drive latest -> 2.18.117
==> Upgrading box-drive
==> Downloading https://e3.boxcdn.net/box-installers/desktop/releases/mac/Box.pkg
Already downloaded: /Users/thecesrom/Library/Caches/Homebrew/downloads/ead8efc7aa5df6a8a9fbd406cae816ebf6f8af5da68075f8ed48071a7fdec8b5--Box.pkg
Warning: No checksum defined for cask 'box-drive', skipping verification.
==> Removing launchctl service com.box.desktop.helper
```

Possible fixes:

1. Restoring `version :latest`
2. Fix 1, and adding `auto_updates true`

**Comment by thecesrom** [comment]
I have to hit Ctrl+C to cancel that task.

Complete output:

```bash
brew upgrade                                                                                                      ─╯
==> Casks with `auto_updates` or `version :latest` will not be upgraded; pass `--greedy` to upgrade them.
==> Upgrading 1 outdated package:
box-drive latest -> 2.18.117
==> Upgrading box-drive
==> Downloading https://e3.boxcdn.net/box-installers/desktop/releases/mac/Box.pkg
Already downloaded: /Users/thecesrom/Library/Caches/Homebrew/downloads/ead8efc7aa5df6a8a9fbd406cae816ebf6f8af5da68075f8ed48071a7fdec8b5--Box.pkg
Warning: No checksum defined for cask 'box-drive', skipping verification.
==> Removing launchctl service com.box.desktop.helper
^C==> Purging files for version 2.18.117 of Cask box-drive
Error: box-drive: Operation not permitted
```

**Comment by thecesrom** [comment]
PR created #96056

**Comment by reitermarkus** [comment]
The download actually contains 2.18.117 for me.

**Comment by thecesrom** [comment]
But why would BrewTestBot change the `version :latest` if it is allowed?

It clearly states that "Casks with `auto_updates` or `version :latest` will not be upgraded; pass `--greedy` to upgrade them."

As I explain, `brew upgrade` breaks due to this change.

**Comment by thecesrom** [comment]
Apparently the `brew upgrade` breaking was unrelated to this change; something that got fixed on its own with a restart.

But I don't see why `version :latest` had to be changed.

Thanks.

**Comment by reitermarkus** [comment]
We prefer versions where possible, since this avoids re-downloading every time you use `--greedy`. With `:latest`, we always have to assume it is outdated.

**Comment by thecesrom** [comment]
Understood. Thanks for clarifying.
