### ISSUE TITLE
Need to update Cask Language Reference

### ISSUE THREAD

**Issue by ed9w2in6** [Homebrew/homebrew-cask#96059]
I noticed the [Cask Language Reference](https://github.com/Homebrew/homebrew-cask/tree/b9e51323b5593e2b46ef4f45c163e5fe25101079/doc) have not been update since 2016.

I am not sure how much have changed since then but at least for me, the path to some useful script are relocated somewhere else as for now, near the end of 2020.  This is mainly due to that we had moved from _caskroom_ to _homebrew_ since 2018!

One example would be for the [documentation for the _uninstall_ stanza](https://github.com/Homebrew/homebrew-cask/blob/b9e51323b5593e2b46ef4f45c163e5fe25101079/doc/cask_language_reference/stanzas/uninstall.md), where it mentioned path to a script as:

```shell
"$(brew --repository)/Library/Taps/caskroom/homebrew-cask/developer/bin/list_recent_pkg_ids"
```

But it should really be this instead:

```shell
"$(brew --repository)/Library/Taps/homebrew/homebrew-cask/developer/bin/list_recent_pkg_ids"
```

Notice that the path has changed from `...../Library/Taps/caskroom/.....` to `...../Library/Taps/homebrew/.....`.

-------------------------------

I am not an active contributor of homebrew-cask so I am not sure if there are other major changes that have not been documented.  So I believe it will be more efficient to have some other contributors with more knowledge of the current state to read through the documentation and update it.

If no one else is bothered to update the documentation, or that nothing substantial has changed to the Cask Language, I would only submit an update to the [documentation for the _uninstall_ stanza](https://github.com/Homebrew/homebrew-cask/blob/b9e51323b5593e2b46ef4f45c163e5fe25101079/doc/cask_language_reference/stanzas/uninstall.md) as I believe thats all the problem with it.

**Comment by reitermarkus** [comment]
I don't see any reference to

```
"$(brew --repository)/Library/Taps/caskroom/homebrew-cask/developer/bin/list_recent_pkg_ids"
```

You seem to have a link pointing to an old commit. This is the current version: https://github.com/Homebrew/homebrew-cask/blob/b9e51323b5593e2b46ef4f45c163e5fe25101079/doc/cask_language_reference/stanzas/uninstall.md

**Comment by ed9w2in6** [comment]
@reitermarkus I am sorry but can you please check that again?  I have clicked through your link and still see the problem.  
Either I am cursed or you are mistaken.

**Comment by reitermarkus** [comment]
I copied the wrong link, updated my post above.

**Comment by ed9w2in6** [comment]
Weird, not sure why i'm not on the master branch.  Guess I followed some weird link.  My bad.  Much thanks.
I am closing this issue.
