### ISSUE TITLE
Need a way to run a script at the end of uninstallation

### ISSUE THREAD

**Issue by ed9w2in6** [Homebrew/homebrew-cask#96088]
## Background

I would love to update a formula to improve to uninstallation experience and behaviour.

These are the 2 formula [Blackhole-2ch](https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/blackhole-2ch.rb) and [Blackhole-16ch](https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/blackhole-16ch.rb).

The _Blackhole-2ch_ and _Blackhole-16ch_ are formulas for a Virtual Audio Driver on the MacOS.

Currently the formula uninstalls using pkgutil, which _**correctly**_ deletes the installed files and directories as expected.
However as this is a audio driver, after uninstallation it will still show up at the audio input and output settings, as well as some other applications such as `Audio MIDI Setup.app`.  This will be fixed upon restart of the computer, or alternatively by running this command / script:

```shell
sudo launchctl kickstart -k system/com.apple.audio.coreaudiod
```

which will restarts the coreaudio daemon only.

### Problem
I would love to do this automatically with brew, in which will need to run the above script after the `uninstall` technique for the `pkgutil` key has been ran.  However, currently the execution order for the `script` key is before `pkgutil` key, making it impossible to do so.

----------------------------------------

## Possible solutions

So now, there is 2 ways to change that I can think of:

1. Make a new `late_script` key that runs at the end for the `uninstall` stanza.  If this is not a good idea for whatever reasons:
2. Introduce a way to display a message to the user after uninstalling, just like the `caveats` stanza for the installation process.  Prompting the user to do it themselves.

----------------------------------------

## User experience

Currently, IMHO the user experience is bad / weird.  As a user, I expect an app / a driver like the above to be gone from the computer after running `brew uninstall`, yet it contradicts the expectation by showing up in other apps or even at the settings. ( System Preferences.app )

For (1), I believe this is a positive change to make, because AFAIK many drivers requires a restart of the corresponding daemons to remove fully.  For (2), I believe it is not ideal as it might encourage people to tell the user to do things manually, but it not a bad idea as then the user will at least have a different expectation, thus improving their experience.

----------------------------------------

I am not an active contributor of homebrew-cask, so if there are other solutions, please help me on this.
Or if there are issues that I have not considered, please discuss with me.

**Comment by miccal** [comment]
I think what you are after is `uninstall_postflight` -- see our documentation [here](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/flight.md).

**Comment by ed9w2in6** [comment]
@miccal I have read that before, but I am not sure if I can execute a script there, as there are no mention of any proper DSL method to do so for the *flight stanzas in the Cask Language Reference.

I have also read the rubydoc but there it explicitly stated that I should not use those private methods whenever possible.

**Comment by vitorgalvao** [comment]
> But I guess the method `system_command(executable, **options)` is applicable?

Yes. That inside `uninstall_postflight` is absolutely the right solution. Adding a `late_script` for a handful of casks would be a lot of code (and possible bugs) for little gain.

One nitpick: those are casks, not formulae. The distinction matters in the sense they are built differently and have different rules and capabilities, so when talking about them it helps to be precise. In this case it wasn’t an issue because you helpfully linked to them.

I’d also like to thank you for the effort put into writing up a detailed and well-reasoned issue. That really makes our work easier.

**Comment by ed9w2in6** [comment]
Thank you for your explanation.
