### ISSUE TITLE
No mountable filesystems when my cask extracts an app from a .dmg.zip file

### ISSUE THREAD

**Issue by Yann-R** [Homebrew/homebrew-cask#96093]
Hi all,

I have a problem with writing a cask for an application often used by my colleagues.
The upstream app is supplied in a zipped DMG file (suffixed by .dmg.zip).

I noticed several available casks that work simply and perfectly from such a .dmg.zip file (e.g. [creepy.rb](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/creepy.rb))

I wrote something similar:
```
cask "macghostview" do
  version "6.1"
  sha256 "b20270fffea09bb4ca6c19fa41a18e8ef0071402a4b8ba17927f3da3c6f848d3"

  url "https://www.math.tamu.edu/~tkiffe/tex/programs/MacGhostView#{version.no_dots}.dmg.zip"
  appcast "https://www.math.tamu.edu/~tkiffe/macghostview.html"
  name "MacGhostView"
  desc "Application for previewing Postscript and encapsulated Postscript files"
  homepage "https://www.math.tamu.edu/~tkiffe/macghostview.html"

  app "MacGhostView.app"
end
```
Surprinsingly, after downloading from the URL, `brew install --cask` fails when mounting the downloaded result, 
```
Error: Failure while executing; `hdiutil attach -plist -nobrowse -readonly -mountrandom /var/folders/9p/ztbq9wsn6195z4c5d25_7b340000gq/T/d20201220-71972-19mlccu /var/folders/9p/ztbq9wsn6195z4c5d25_7b340000gq/T/d20201220-71972-19mlccu/MacGhostView61.cdr` exited with 1. Here's the output:
hdiutil: attach failed - no mountable filesystems
```
Don't know if the `MacGhostView61.cdr` in the failure output above (and not .dmg as it is inside the zip) can be a clue to explain the failure? Nevertheless:
- downloading and mounting a .dmg.zip file works in other cask scripts (mentioned above)
- rewriting my cask to download the dmg file (manually unzipped with macOS Finder integrated function (Archive Utility), and uploaded to my own server) mounts perfectly.

I tried to play a little with `container type:`and `container nested:` (mentioned [here](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/all_stanzas.md)) in my cask, but to no avail.

Have you any idea for the mount failure when directly using the .dmp.zip file?
Would there be limitations in zip-format support in cask subroutines different from the Finder function?

Any help welcome, best regards.

**Comment by ed9w2in6** [comment]
Have you ran `brew audit --new-cask macghostview.rb` yet?

I ran it and it shows:

```shell
==> Downloading https://www.math.tamu.edu/~tkiffe/tex/programs/MacGhostView61.dmg.zip
##O#- #
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
audit for macghostview: failed
 - download not possible: Download failed on Cask 'macghostview' with message: Download failed: https://www.math.tamu.edu/~tkiffe/tex/programs/MacGhostView61.dmg.zip
 - The URL https://www.math.tamu.edu/~tkiffe/tex/programs/MacGhostView61.dmg.zip is not reachable
 - The URL https://www.math.tamu.edu/~tkiffe/macghostview.html is not reachable
 - The URL https://www.math.tamu.edu/~tkiffe/macghostview.html is not reachable
 - appcast at URL 'https://www.math.tamu.edu/~tkiffe/macghostview.html' does not contain the version number '6.1':
Error: 4 problems in 1 cask detected
```

First, the website at url and homepage are both insecure as the certificate has expired.
Second, the provided appcast link is not an appcast.  See the [Cask Language Reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md)
Note that the `appcast` stanza is optional.

**Comment by Yann-R** [comment]
Many thanks @ed9w2in6 

Yes I used `brew audit` that returned "passed" :-) But thanks to you I notice I forgot to add the option `--new-cask` that reveals the curl problem you showed above!

You are right, I should have removed the "appcast" line, it was just one of my tries since I was not sure (even after reading the stanza documentation) what alternatives could be suited for `appcast`.

OK, that's much clearer now to understand the reason of the failure.
I will report the expired certificate upstream.
Do you know if there is any way to workaround this expired certificate and perform the download all the same meantime?
Regards.

**Comment by ed9w2in6** [comment]
I emailed the webmaster for you and I just got informed the SSL certificate got updated.
Try doing `brew audit --new-cask` again, as well as [testing it locally first](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#testing-your-new-cask).

If you can install and uninstall it correctly, it should be fine!

Then make sure you do `brew style` as well.

For details please refer to [CONTRIBUTING.md](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#adding-a-cask)

**Comment by Yann-R** [comment]
Thank you so much for all 👍 
Everything is OK now for my cask, I close the issue.

**Comment by Yann-R** [comment]
Arg, in fact this step beyond doesn't change the failure:

1. now the cask passes the audit
2. `brew install --cask` still tries and succeeds to download the 46 MB .dmg.zip
3. but when brewed, I still get the same mounting error as above.

And this time, I checked the downloaded file  in `/Users/me/Library/Caches/Homebrew/downloads/XXX.dmg.zip`:

- I can manually unzip it and mount it.

Then I really don't know why `brew install` fails to mount this correct .dmg.zip file?

**Comment by ed9w2in6** [comment]
Hmm, weird, not sure why.  I can reproduce it.

Here is my `brew install -fv`

```shell
% brew install -fdv /Users/*******/Desktop/macghostview.rb
==> Downloading https://www.math.tamu.edu/~tkiffe/tex/programs/MacGhostView61.dmg.zip
Already downloaded: /Users/*******/Library/Caches/Homebrew/downloads/68d7e7b0b2f47dc0c3629c4247fb8ff69fd42c9f03f60f6f4187\
a3853a99826c--MacGhostView61.dmg.zip
==> Installing Cask macghostview
unzip -o /Users/*******/Library/Caches/Homebrew/downloads/68d7e7b0b2f47dc0c3629c4247fb8ff69fd42c9f03f60f6f4187a3853a99826\
c--MacGhostView61.dmg.zip -d /var/folders/6w/2jtnw0rn3sl6_mlndrzjvdzw0000gn/T/d20201221-66000-1apw0sa
chmod -Rf +rw /var/folders/6w/2jtnw0rn3sl6_mlndrzjvdzw0000gn/T/d20201221-66000-1apw0sa/MacGhostView61.dmg
hdiutil attach -plist -nobrowse -readonly -mountrandom /var/folders/6w/2jtnw0rn3sl6_mlndrzjvdzw0000gn/T/d20201221-66000-3\
mpimy /var/folders/6w/2jtnw0rn3sl6_mlndrzjvdzw0000gn/T/d20201221-66000-1apw0sa/MacGhostView61.dmg
hdiutil convert -format UDTO -o /var/folders/6w/2jtnw0rn3sl6_mlndrzjvdzw0000gn/T/d20201221-66000-3mpimy/MacGhostView61.cd\
r /var/folders/6w/2jtnw0rn3sl6_mlndrzjvdzw0000gn/T/d20201221-66000-1apw0sa/MacGhostView61.dmg
hdiutil attach -plist -nobrowse -readonly -mountrandom /var/folders/6w/2jtnw0rn3sl6_mlndrzjvdzw0000gn/T/d20201221-66000-3\
mpimy /var/folders/6w/2jtnw0rn3sl6_mlndrzjvdzw0000gn/T/d20201221-66000-3mpimy/MacGhostView61.cdr
hdiutil: attach failed - no mountable filesystems
==> Purging files for version 6.1 of Cask macghostview
Error: Failure while executing; `hdiutil attach -plist -nobrowse -readonly -mountrandom /var/folders/6w/2jtnw0rn3sl6_mlnd\
rzjvdzw0000gn/T/d20201221-66000-3mpimy /var/folders/6w/2jtnw0rn3sl6_mlndrzjvdzw0000gn/T/d20201221-66000-3mpimy/MacGhostVi\
ew61.cdr` exited with 1. Here's the output:
hdiutil: attach failed - no mountable filesystems
```

I suspect this is something with the permissions / security.
The three lines associated with the hdiutil tool runs successfully when executed manually.

Here is a possible similar issue that is closed and locked [#73876](https://github.com/Homebrew/homebrew-cask/issues/73876)

**Comment by miccal** [comment]
Does the install succeed if you pass the `--no-quarantine` flag?

**Comment by ed9w2in6** [comment]
No it doesn't.

**Comment by miccal** [comment]
I just updated a Cask that used a `.dmg.zip` in https://github.com/Homebrew/homebrew-cask/pull/96858, which passed our CI tests.

Comparing this to your `.dmg.zip` file, the _only_ difference I can find is that your `.dmg` file does NOT open in a new window in the Finder, unlike most `.dmg` files, and just shows up as a mounted drive.

That is, the focus when opening the `.dmg` file is NOT directed to the files inside the `.dmg` file.

Could this have something to do with the problem?

**Comment by ed9w2in6** [comment]
Yeah I do not think the fact that it is zipped have anything to do with the problem.
1. I think it is might be related with the type of image it is?
For images of type UDRW, brew seems to be converting it first into UDTO ( thus the `.cdr` file extension ), then extracting it, which fails.
2. Besides, the particular image in this issue is also not  checksummed.

@Yann-R You better look more into this issue yourself actively, as previous issue related to “hdiutil: attach failed - no mountable file systems” are all closed as it is not a widespread issue.

**Comment by ed9w2in6** [comment]
I had tried to manually run `hdiutil attach -plist -nobrowse -readonly -mountrandom` again, and found that it fails with the said message.  If one attaches it by clicking it, then detaches it, and run the same command again, it runs successfully.
Probably something to do with Mac's security (and the image itself.)  I had run `ls -lah@` and made sure that it is not quarantined.

**Comment by Yann-R** [comment]
Thanks for your investigations.

1. I agree that some other dmg.zip DO work in other casks: I mentioned it in my first message.
2. But for now,  I don't agree that the problem I'm facing has nothing to do with the fact it is zipped, because:

=> as I also mentioned in my first message:

- rewriting my cask to download the dmg file (manually unzipped with macOS Finder integrated function (Archive Utility), and uploaded to my own server) mounts perfectly.

In other words:

1. I manually unzip the .dmg.zip (so I get a simple .dmg)
2. I upload the dmg on my own server
3. I rewrite my cask-script to use this .dmg (and not the original .dmz.zip)

=> and it works perfectly.

That's why I'm quite puzzled by the following facts:

- when zipped, the same DMG does not work any longer with cask commands
- and the zip seem not corrupted according to th Apple Archive Utility

What strikes me is that the same DMG concerned by the thread:

1. works perfectly with cask routines when supplied as direct DMG file
2. fails with cask routines when suppled as .DMG.ZIP file (while the ZIP seems not corrupted)

Strange for me...

**Comment by Yann-R** [comment]
@ed9w2in6, thank you for your last observation:
- indeed the Finder has no problem to mount and use this DMG by a user click
- but the `hdutil` command made by homebrew-cask routines fails at first mount... and succeeds if Finder mounted it at least once before.

And I found the difference:
- the Finder mounts it "normally" (i.e. not read-only) => it works at first attempt
- hombrew-cask mounts it "read-only" and it fails.

But if I modify the above commands you copied, raised by hombrew-cask `hdiutil attach -plist -nobrowse -readonly -mountrandom` into `hdiutil attach -plist -nobrowse -mountrandom` (I just removed the `-read-only` option)
=> it works like a charm even as a first attempt, manually from the command-line.

So my last question (to make my cask scrip work) is:
is there a way to prevent homebrew-cask from mounting `read-only`?

Best regards.

**Comment by Yann-R** [comment]
Hi all,
No ideas about my last question? => how to perform a "not read-only mount" with homebrew-cask so as to simulate the same behaviour that the manual use of the DMG with Finder? @vitorgalvao ?

**Comment by vitorgalvao** [comment]
If you need different `hdutil` commands, do them in a `preflight` block. We may still have a few casks which use that technique.

**Comment by Yann-R** [comment]
Oh, thanks! 
I'll look for that kind of examples 👍

**Comment by Yann-R** [comment]
Unfortunately, none of the examples I found in existing casks for `preflight` helped me in writing a working solution to:
- mount the DMG image found in the downloaded ZIP (to mount it at least once in read-write before the cask processing)
- then force cask-processing into using the already-mounted mounted image OR into re-mounting the image file that was mount once before.
- ... and not let the cask-processing extract again the DMG from the ZIP (since we learned that the 1st mount as read-only by the cask processing makes it fail).

I'm not experienced enough with those casks tricks to reach my goal.
If anyone has an idea to help me, much appreciated.
regards.

**Comment by vitorgalvao** [comment]
Giving this another chance.

**Comment by Yann-R** [comment]
Meantime a contact with the upstream author made him repack the zipped DMG and now the problem is solved without needing tricks like `preflight`.
Can then be closed for now at last!

**Comment by Yann-R** [comment]
Meantime a contact with the upstream author made him repack the zipped DMG and now the problem is solved without needing tricks like preflight.
Can then be closed for now at last!
