### ISSUE TITLE
How to make appcast stanza really optional

### ISSUE THREAD

**Issue by Yann-R** [Homebrew/homebrew-cask#96108]
Hello,

I need some more help about a detail in my discovery of the writing of casks.

The `appcast` stanza is documented as optional (e.g. [here](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/all_stanzas.md)).
I am writing a cask related to this app ([here](https://runtimesharks.com/projects/dnd-me)) that is:

1. without versioned filename when downloading the app
2. without any page giving the current version: just written in the "About" dialog when using the app

Astonishingly, in this case, the stanza `appcast` seems not to be optional.
if I don't give it:
```
$ brew audit --new-cask dnd-me.rb
audit for dnd-me: failed
 - Use `sha256 :no_check` when URL is unversioned.
 - Download is hosted on DevMate, please add an appcast. See https://github.com/Homebrew/homebrew-cask/blob/HEAD/doc/cask_language_reference/stanzas/appcast.md
Error: 2 problems in 1 cask detected
```
After the above result with 2 errors, I try to correct both and I have no other solution than giving the homepage as `appcast`, then:
```
$ brew audit --new-cask dnd-me.rb
Warning: No checksum defined for cask 'dnd-me', skipping verification.
audit for dnd-me: failed
 - appcast at URL 'https://runtimesharks.com/projects/dnd-me' does not contain the version number '1.1.2':
[dump appcast]
Error: 1 problem in 1 cask detected
```
As you can see, then (of course) the appcast is not satisfied with a page without version number.
Therefore I have no way to avoid an error (and not only a warning) for the appcast stanza, which is therefore not totally optional in that case it seems.
Have you any suggestions for me as the best practice to handle such a release case?
Regards.

**Comment by vitorgalvao** [comment]
`appcast` is optional in the sense that not every app can have it, but it is heavily encouraged.

It’s our fault for having missed on the documentation how to add a devmate appcast. Make it `https://updates.devmate.com/com.runtimesharks.dndme.xml` (and look inside to find a versioned download URL).

Submit your PR and @mention me, and we’ll iron out any kinks.

**Comment by vitorgalvao** [comment]
Just remembered DevMate is deprecated, which is probably why we removed the instructions for it.

**Comment by vitorgalvao** [comment]
I’d also like to thank you for being detailed in your issue. That makes our work easier in helping you help us.
