### ISSUE TITLE
homebrew cask or homebrew alone pulling from github is REALLY slow

### ISSUE THREAD

**Issue by franferri** [Homebrew/homebrew-cask#96131]
Please ALWAYS "--depth 1" in the cli and scripts when pulling stuff from github.

If you google github clone slow you'll see ever since the big company acquired Github, this is a recurrent pain in the a**.

And is transient and non getting better.

**Comment by vitorgalvao** [comment]
1. This is an issue for https://github.com/Homebrew/brew, not this repo.
2. [GitHub specifically asked us to not perform shallow clones](https://github.com/Homebrew/brew/pull/9383).

**Comment by franferri** [comment]
I suggest to change to gitlab.com then.
Thanks for you answer.

**Comment by vitorgalvao** [comment]
> I suggest to change to gitlab.com then.

That’s unlikely to happen, and the disruption for that one issue would be huge. Plus, if we’re causing a strain on GitHub—backed by Microsoft’s money—I doubt GitLab could handle it.
