### ISSUE TITLE
Nomachine - SHA256 mismatch

### ISSUE THREAD

**Issue by vutfastcit** [Homebrew/homebrew-cask#96726]
Hello,

I have problem with upgrade Nomachine formula. Log is bellow. Any fix?

==> Upgrading 1 outdated package:
nomachine 6.12.3_8 -> 7.0.209_4
==> Upgrading nomachine
==> Downloading https://download.nomachine.com/download/7.0/MacOSX/nomachine_7.0.209_4.dmg
==> Downloading from https://www.nomachine.com
#=#=-#  #                                                                     
==> Purging files for version 7.0.209_4 of Cask nomachine
Error: nomachine: SHA256 mismatch
Expected: 19d334f9665e2ba62249a8af3266598ed7612cb31b487abb7f1fb082f5b2f630
  Actual: ba24b523476f9032e2ee16191b754f9d9651bbdbf2935af82e9b3b20a4af93a8
    File: /Users/***/Library/Caches/Homebrew/downloads/22cd90e8d256e4316b1a3d7cd6a13d6e16aaa495e1cad0deac306855df848b75--
To retry an incomplete download, remove the file above.

--
vutfastcit

**Comment by ykursadkaya** [comment]
It looks like any time they release a new minor version, they make old versioned URL response 302 Moved Temporarily.

**Comment by miccal** [comment]
Fixed in https://github.com/Homebrew/homebrew-cask/pull/96763.
