### ISSUE TITLE
texstudio 3.0.2 error

### ISSUE THREAD

**Issue by fblupi** [Homebrew/homebrew-cask#97058]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

There is no issue with brew. The problem is with the proper software installed that fails in its version 3.0.2. I recommend coming back to the previous version 3.0.1 by discarding the changes of [this PR](https://github.com/Homebrew/homebrew-cask/pull/97028/commits/f25806dc064b6c976110532b98109a4bc6fd64d4).

<img width="331" alt="Screenshot 2020-12-29 at 13 29 14" src="https://user-images.githubusercontent.com/6973564/103283984-3ffa5280-49da-11eb-8c84-5f43e5d6279f.png">

<img width="1015" alt="Screenshot 2020-12-29 at 13 29 44" src="https://user-images.githubusercontent.com/6973564/103283992-45579d00-49da-11eb-953d-14d4c7a95189.png">

#### Command that failed

```
```

#### Output of command with `--verbose --debug`

```
```

#### Output of `brew doctor --verbose`

```
```

#### Output of `brew tap`

```
```

**Comment by miccal** [comment]
Should be fixed by https://github.com/Homebrew/homebrew-cask/pull/97064.
