### ISSUE TITLE
Cask 'mysqlworkbench' definition is invalid: Token '{:v1=>"mysqlworkbench"}' in header line does not match the file name.

### ISSUE THREAD

**Issue by saulspatz** [Homebrew/homebrew-cask#97136]
When I run `brew upgrade` I get the message

     Cask 'mysqlworkbench' definition is invalid: Token '{:v1=>"mysqlworkbench"}' in header line does not match the file name.

I haven't had mysqlworkbench on my computer for a long time, and this is the first time I've seen this message.  I'm not sure what changed, although homebrew updated my python from 3.8 to 3.9 today.  When I list /usr/local/Cellar, mysqlworkbech does not appear.  I've tried `brew cleanup`, `brew uninstall --force mysqlworkbench`, `brew uninstall --force 'mysqlworkbench'`  and none makes the error go away.  

I've considered installing mysqlworkbench and then uninstalling it, but I'm afraid I may just make matters worse, since I have no idea what's going on.

Please advise.

**Comment by saulspatz** [comment]
I think I posted this at the wrong place

**Comment by vitorgalvao** [comment]
> I haven't had mysqlworkbench on my computer for a long time

Then delete the directory at `"$(brew --prefix)/Caskroom/mysqlworkbench` and the problem should go away.

**Comment by saulspatz** [comment]
@vitorgalvao Spot on, thank you.

**Comment by immense055** [comment]
Thank you.
