### ISSUE TITLE
Missing git origin remote

### ISSUE THREAD

**Issue by eloyaldea** [Homebrew/homebrew-cask#97226]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

I was trying to set up my GitHub access token for `brew bump-cask-pr` and after many attempts an guides followed I was unable to make it work, with multiple 'permission dennied' messages. I decided to delete all traces of GitHub that I had previously attempted. I deleted Homebrew entirely using this guide [https://github.com/homebrew/install](url) and reinstalling it again with the same guide, with the following messages displayed: 

> /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
Password:
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

> Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /usr/sbin/chown eag:admin /usr/local/Homebrew
==> Downloading and installing Homebrew...
HEAD is now at e5eb6a264 Merge pull request #10190 from SeekingMeaning/bottle-keep-old
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

> Please make sure you have the correct access rights
and the repository exists.
Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask failed!
fatal: invalid upstream 'origin/master'
Failed during: /usr/local/bin/brew update --force

Note: After running `brew doctor` I have tried `git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask" remote add origin` as it tells me with the following result: 

> git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask" remote add origin
usage: git remote add [<options>] <name> <url>

>    -f, --fetch           fetch the remote branches
    --tags                import all tags and associated objects when fetching
                          or do not fetch any tag at all (--no-tags)
    -t, --track <branch>  branch(es) to track
    -m, --master <branch>
                          master branch
    --mirror[=(push|fetch)]
                          set up remote as a mirror to push to or fetch from

My knowledge of Git and coding in general is fairly limited and I just wanted to setup my GitHub account to submit new cask versions and messed something up in the process. I followed as much guides as I could but gave up as it seemed it only got worse and less things started to function. I hope I wrote correctly everything, it's my first bug report here. The help would be greatly appreciated, thanks!

#### Command that failed

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
```

#### Output of command with `--verbose --debug`

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" --verbose --debug
Password:
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /usr/sbin/chown eag:admin /usr/local/Homebrew
==> Downloading and installing Homebrew...
HEAD is now at e5eb6a264 Merge pull request #10190 from SeekingMeaning/bottle-keep-old
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask failed!
fatal: invalid upstream 'origin/master'
Failed during: /usr/local/bin/brew update --force
```

#### Output of `brew doctor --verbose`

```
brew doctor --verbose
/usr/local/Homebrew/Library/Homebrew/shims/scm/git --version
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Missing  git origin remote.

Without a correctly configured origin, Homebrew won't update
properly. You can solve this by adding the remote:
  git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask" remote add origin
```

#### Output of `brew tap`

```
brew tap
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
kkevinm/itunes-discord-rp
mas-cli/tap
teamookla/speedtest
vitorgalvao/tiny-scripts
```

**Comment by miccal** [comment]
Please run `cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask` and then post the output of `git remote -v`.

**Comment by eloyaldea** [comment]
Done, there is no output :'(

**Comment by miccal** [comment]
Please try running `brew untap homebrew/cask` then `brew tap homebrew/cask`.

**Comment by eloyaldea** [comment]
> brew untap homebrew/cask
> Untapping homebrew/cask...
> Error: Directory not empty @ dir_s_rmdir - /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask

**Comment by miccal** [comment]
Run `rm -r /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask` first, then try again.

**Comment by eloyaldea** [comment]
Oh wait it fixed itself after running `brew untap homebrew/cask` again:

> brew untap homebrew/cask
> Untapping homebrew/cask...
> Untapped (12.2KB).

And after `brew tap homebrew/cask` :

> brew tap homebrew/cask  
==> Tapping homebrew/cask
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask'...
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 542245 (delta 21), reused 0 (delta 0), pack-reused 542201
Receiving objects: 100% (542245/542245), 238.98 MiB | 16.80 MiB/s, done.
Resolving deltas: 100% (382743/382743), done.
Updating files: 100% (3880/3880), done.
Tapped 3784 casks (3,905 files, 256.4MB).

Should I run `rm -r /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask` after this?

**Comment by miccal** [comment]
No, now check `brew doctor` again.

**Comment by eloyaldea** [comment]
> brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have uncommitted modifications to Homebrew/homebrew-core.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core && git stash && git clean -d -f

Uncommitted files:
  ?? .DS_Store

**Comment by miccal** [comment]
Looks fixed now :)

**Comment by eloyaldea** [comment]
After `cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core && git stash && git clean -d -f`:

> No local changes to save
Removing .DS_Store

After `brew doctor`:
> Your system is ready to brew.

I assume I can now install casks and everything like before. Should I untap all my taps?

Also if I want to ask for help for cask contributing who/where can I ask?

Thanks a lot for the help!!

**Comment by miccal** [comment]
Yes, all should be fine now.
