### ISSUE TITLE
`brew upgrade` fails forever when installed casks become uninstallable

### ISSUE THREAD

**Issue by nopdotcom** [Homebrew/homebrew-cask#97285]
#### General troubleshooting steps

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

I have `homebrew/cask/gqrx` installed on an older machine. Gqrx added a dependency on `macos: >= :catalina`. Now any invocation of `brew upgrade` fails, presumably permanently.

My understanding is that `brew cask` is dead, and we should be able to manage casks like other packages. When I don't want Homebrew to try to upgrade a package, I pin it:

```
$ brew pin
Usage: brew pin formula

Pin the specified formula, preventing them from being upgraded when issuing
the brew upgrade formula command. See also unpin.
```

but `brew pin homebrew/cask/gqrx` also fails. Should I file a bug for the documentation of `pin` instead, to make clear it doesn't work on casks?

I assume I could delete Gqrx, but the last version was working software; I don't want to be forced to remove it just to make `brew upgrade && echo succeeded` work. If there was a mechanism that said "keep the cask contents, but remove the pointer from Homebrew", that would probably cover this situation since no further updates will be coming from the Homebrew channel for this package.

#### Command that failed

```
$ brew upgrade --force
==> Casks with `auto_updates` or `version :latest` will not be upgraded; pass `--greedy` to upgrade them.
==> Upgrading 1 outdated package:
gqrx 2.14.3 -> 2.14.4
==> Upgrading gqrx
==> Purging files for version 2.14.4 of Cask gqrx
Error: gqrx: macOS Catalina or newer is required for this software.
$
```

#### Output of command with `--verbose --debug`

```
~ centrism$ brew upgrade --force --verbose --debug
[taploader lines redacted; supplied on request]
==> Casks with `auto_updates` or `version :latest` will not be upgraded; pass `--greedy` to upgrade them.
==> Upgrading 1 outdated package:
gqrx 2.14.3 -> 2.14.4
==> Started upgrade process for Cask gqrx
==> Upgrading gqrx
==> Printing caveats
==> Cask::Installer#fetch
==> Purging files for version 2.14.4 of Cask gqrx
Error: gqrx: macOS Catalina or newer is required for this software.
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:132:in `upgrade_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:181:in `upgrade_outdated_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:106:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:124:in `<main>'
```

#### Output of `brew doctor --verbose`

```
$ brew doctor --verbose
/usr/local/Homebrew/Library/Homebrew/shims/scm/git --version
==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
==> $LOAD_PATHS
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-stub-0.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-sorbet-0.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rails-2.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.9.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.11.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rack-2.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/patchelf-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/elftools-1.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov_json_formatter-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bindata-2.4.8/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.4.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-2.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/x86_64-darwin14
/usr/local/Homebrew/Library/Homebrew
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Homebrew Version
2.7.1-123-g7eca0d7
==> macOS
10.14.6
==> SIP
Disabled
/usr/libexec/java_home --xml --failfast
==> Java
14.0.2, 1.8.0_144
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3772 casks)
/usr/local/Homebrew/Library/Taps/railwaycat/homebrew-emacsmacport (2 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1598 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (167 casks)
/usr/bin/xattr
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:

[...list of local packages redacted, available on request...]

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:

[...list of locally preserved packages redacted, available on request...]

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /usr/local/CrossPack-AVR/bin/libusb-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libFastCompression.1.0.dylib
  /usr/local/lib/libexiv2.26.dylib
  /usr/local/lib/libjson-c.2.dylib
  /usr/local/lib/libykclient.3.dylib
  /usr/local/lib/ss_conn_lib.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/FastCompression.h
  /usr/local/include/libopensc/asn1.h
  /usr/local/include/libopensc/authentic.h
  /usr/local/include/libopensc/aux-data.h
  /usr/local/include/libopensc/card-gids.h
  /usr/local/include/libopensc/card-sc-hsm.h
  /usr/local/include/libopensc/cardctl.h
  /usr/local/include/libopensc/cards.h
  /usr/local/include/libopensc/compat_getopt.h
  /usr/local/include/libopensc/compat_getpass.h
  /usr/local/include/libopensc/compat_strlcat.h
  /usr/local/include/libopensc/compat_strlcpy.h
  /usr/local/include/libopensc/compat_strnlen.h
  /usr/local/include/libopensc/compression.h
  /usr/local/include/libopensc/ctbcs.h
  /usr/local/include/libopensc/cwa-dnie.h
  /usr/local/include/libopensc/cwa14890.h
  /usr/local/include/libopensc/errors.h
  /usr/local/include/libopensc/esteid.h
  /usr/local/include/libopensc/iasecc-sdo.h
  /usr/local/include/libopensc/iasecc.h
  /usr/local/include/libopensc/internal-winscard.h
  /usr/local/include/libopensc/internal.h
  /usr/local/include/libopensc/iso7816.h
  /usr/local/include/libopensc/itacns.h
  /usr/local/include/libopensc/jpki.h
  /usr/local/include/libopensc/libpkcs11.h
  /usr/local/include/libopensc/libscdl.h
  /usr/local/include/libopensc/log.h
  /usr/local/include/libopensc/muscle-filesystem.h
  /usr/local/include/libopensc/muscle.h
  /usr/local/include/libopensc/opensc.h
  /usr/local/include/libopensc/p15card-helper.h
  /usr/local/include/libopensc/pace.h
  /usr/local/include/libopensc/pkcs15-syn.h
  /usr/local/include/libopensc/pkcs15.h
  /usr/local/include/libopensc/sc-ossl-compat.h
  /usr/local/include/libopensc/scconf.h
  /usr/local/include/libopensc/simclist.h
  /usr/local/include/libopensc/sm.h
  /usr/local/include/libopensc/types.h
  /usr/local/include/lzvn.h
  /usr/local/include/python2.7/greenlet/greenlet.h
  /usr/local/include/python3.6m/greenlet/greenlet.h

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libFastCompression.a

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:

[...local package names available on request...]
```

#### Output of `brew tap`

```
dunn/emacs
dustinwilson/tap
homebrew/bundle
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/core
homebrew/services
jeffreywildman/virt-manager
martido/graph
nopdotcom/random
railwaycat/emacsmacport
```

**Comment by reitermarkus** [comment]
> and we should be able to manage casks like other packages

>  Should I file a bug for the documentation of `pin` instead, to make clear it doesn't work on casks?

`brew pin` does not work for casks, if it did, the help page would say `formula|cask` instead of just `formula`.

We'll accept a PR to make this a warning during `brew upgrade`, i.e. “ Warning: gqrx:  Skipping; macOS Catalina or newer is required for this software.”

**Comment by vitorgalvao** [comment]
> My understanding is that `brew cask` is dead, and we should be able to manage casks like other packages.

No. `brew cask` *as a command* is deprecated, but functionality remains the same.

> Should I file a bug for the documentation of `pin` instead, to make clear it doesn't work on casks?

As @reitermarkus pointed out, that’s already documented. [The larger explanation is in the FAQ](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/app_not_upgrading.md).

> We'll accept a PR to make this a warning during `brew upgrade`, i.e. “ Warning: gqrx: Skipping; macOS Catalina or newer is required for this software.”

From the top post, that seems to already happen. The issue is that it tries to upgrade it anyway.

This will only be a serious bug if it prevents other software from being upgraded, though. Does that happen, @nopdotcom?

> If there was a mechanism that said "keep the cask contents, but remove the pointer from Homebrew"

There is. Delete the `/usr/local/Casrkoom/gqrx` directory.

**Comment by swrobel** [comment]
@vitorgalvao @reitermarkus with all of the new work done to separate out auto-updating casks vs versioned ones, shouldn't it theoretically be possible (with some work) to pin versioned casks?

**Comment by vitorgalvao** [comment]
> with all of the new work done to separate out auto-updating casks vs versioned ones, shouldn't it theoretically be possible (with some work) to pin versioned casks?

[No](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/app_not_upgrading.md). We cannot pin casks without risking breaking the installed software.

**Comment by swrobel** [comment]
Like I said, *versioned* casks, ie: those that do _not_ auto-update

**Comment by vitorgalvao** [comment]
So your suggestion is to only allow pinning on *some* casks, which the user has to guess and which can change at any time? That’d be an awful user experience, the likes of which we’d never stop getting duplicate bug reports about. That has also been discussed and refused in the past.

We may have more versioned casks now, but nothing else changed. There’s no “work done to separate out auto-updating casks vs versioned ones”. Auto-updating casks are still versioned.

**Comment by swrobel** [comment]
If you want to talk about awful UX:

```
$ brew pin dteoh-devdocs
Error: No available formula with the name "dteoh-devdocs".
```

Useful error messages go a long way toward making for good UX for CLIs. Simply saying "cannot pin auto-updating cask X" would solve the issue, IMHO.

**Comment by vitorgalvao** [comment]
> If you want to talk about awful UX

What I want is for you to respect our decision and not change the subject to try to win an argument. This has been *publicly* discussed repeatedly in the past, and I shouldn’t have to spend my volunteer free time repeating a discussion that was had multiple times. It would also be welcome if you didn’t hijack unrelated issues for your questions, or directly ping maintainers when it’s not necessary.

Your rebuttal boils down to “you have a bad user experience in this unrelated area, so you should add more bad user experiences in this area I particularly care about”. Unlike you, we have to think of all users and the project as a whole.

> Simply saying "cannot pin auto-updating cask X" would solve the issue, IMHO.

No, it would not. We don’t exhaustively know which software auto-updates, meaning *we have no real control over pinning*.
