### ISSUE TITLE
Add HHKB-pro-driver cask

### ISSUE THREAD

**Issue by diohabara** [Homebrew/homebrew-cask#97569]
Lately Happy Hacking KeyBoard(a.k.a., HHKB)'s driver has been updated for the new macOS Big Sur 11.1.
There is, however, no CUI tool for this driver installation.
If this cask is not rejected, I'd like to add it.

This page is for its download: https://www.pfu.fujitsu.com/hhkeyboard/macdownload.html
The latest version: https://www.pfu.fujitsu.com/hhkeyboard/downloads/HHKBProDriver5.0.1.dmg

**Comment by miccal** [comment]
Please feel free to make a pull request to add this to the [`homebrew-cask-drivers` repository.](https://github.com/Homebrew/homebrew-cask-drivers)
