### ISSUE TITLE
You're deleting a lot of unrelated stuff with `brew uninstall --cask --zap  android-file-transfer`

### ISSUE THREAD

**Issue by nikolay** [Homebrew/homebrew-cask#97923]
https://github.com/Homebrew/homebrew-cask/blob/d940c682f5a0a6da9cd396ceb809b9c8bcb70fb5/Casks/android-file-transfer.rb#L25

**Comment by miccal** [comment]
`rmdir:` will only remove that folder if it is empty -- see the documentation [here](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md#summary-of-keys).
