### ISSUE TITLE
kotlin-native cask uses incorrect filename (404 Not Found)

### ISSUE THREAD

**Issue by JannikGM** [Homebrew/homebrew-cask#98137]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] (*Other points not relevant*)

#### Description of issue

The filename for `kotlin-native` is incorrect, so the download fails with error 404.

Cask contains `kotlin-native-macos-#{version}.tar.gz`:
https://github.com/Homebrew/homebrew-cask/blob/434e7efd13c68f05a03ac46ecbba133dd1a31ff1/Casks/kotlin-native.rb#L4-L6

Proper filename ([according to 1.4.21 release](https://github.com/JetBrains/kotlin/releases/tag/v1.4.21)) is probably `kotlin-native-prebuilt-macos-1.4.21.tar.gz`, so `kotlin-native-prebuilt-macos-#{version}.tar.gz` (note the additional `-prebuilt`).

`-prebuilt` was [also part of 1.4.20 already](https://github.com/JetBrains/kotlin/releases/tag/v1.4.20), so I'm not sure how https://github.com/Homebrew/homebrew-cask/pull/94989 was tested. The error was first introduced when [the filename changed from 1.4.0 to 1.4.20](https://github.com/JetBrains/kotlin/releases/tag/v1.4.0) in https://github.com/Homebrew/homebrew-cask/pull/93941.

The checksums for casks in 1.4.20 / 1.4.21 also don't match the checksums in the release announcements. I assume they are hashes of an error page.

Pinging @pthariensflame (author of those PRs) to keep an eye out for future name changes.

*(I currently don't plan to send a fix, so I'd appreciate if someone else does it)*

#### Command that failed

```
$ brew install kotlin-native
==> Caveats
kotlin-native requires Java 6+. You can install the latest version with:
  brew install --cask adoptopenjdk

==> Downloading https://github.com/JetBrains/kotlin/releases/download/v1.4.21/kotlin-native-macos-1.4.21.tar.gz
#=#=#
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'kotlin-native' with message: Download failed: https://github.com/JetBrains/kotlin/releases/download/v1.4.21/kotlin-native-macos-1.4.21.tar.gz
```

**Comment by vitorgalvao** [comment]
> I currently don't plan to send a fix

Why not? You’ve already done the research and found the problem and solution, so even if you edit the cask directly from the web interface and don’t fill any of the checkboxes, that would already be a huge improvement and time-saver for everyone, including yourself.

As it is, I have to read and parse your post, understand your explanation, and apply the fix. It’s inefficient and greatly delays the issue being solved.
