### ISSUE TITLE
Homebrew/Docker - SHA256 mismatch

### ISSUE THREAD

**Issue by leepowelldev** [Homebrew/homebrew-cask#98171]
Installing Docker via Homebrew is failing with a SHA256 mismatch.

Following install procedure from: https://formulae.brew.sh/cask/docker#default

Downloading https://desktop.docker.com/mac/stable/51484/Docker.dmg
Error: SHA256 mismatch
Expected: 9e68684d7d19de90034630ec2127a5d49138dc314857059fa75a99687be2b6b8
Actual: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

Is this something Docker team or Homebrew team need to investigate?

**Comment by miccal** [comment]
I cannot reproduce this -- I have checked manually and via `brew fetch homebrew/cask/docker` and the `sha256` seems correct.

Please run `brew update` and try again.

**Comment by leepowelldev** [comment]
Well that's odd. I tried deleting the downloaded dmg, doing a `brew update` and running again - still failed.

However, if I did the `brew fetch homebrew/cask/docker` first, and then ran the install command it worked...
