### ISSUE TITLE
qt* Casks

### ISSUE THREAD

**Issue by miccal** [Homebrew/homebrew-cask#98316]
For me at least, `brew fetch` is failing for all four of the `qt*` Casks, namely [`qt-design-studio`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/qt-design-studio.rb), [`qt3dstudio`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/qt3dstudio.rb), [`qt-creator`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/qt-creator.rb) and [`qt-creator-dev`](https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/qt-creator-dev.rb).

From their respective `homepage`'s the download links seem to be behind a registration.

Can anyone else confirm these findings?

**Comment by adithyasunil26** [comment]
Yes, you are right. The URLs don't seem to be working anymore. The only download available from their website without registration is the online installer common to all qt packages.

**Comment by yurikoles** [comment]
Qt Open Source downloads was temporarily offline: https://www.qt.io/blog/problem-with-open-source-downloads
But they should work now: https://www.qt.io/blog/open-source-downloads-working-again
