### ISSUE TITLE
Casks from thelittleappfactory.com 

### ISSUE THREAD

**Issue by miccal** [Homebrew/homebrew-cask#98317]
For me at least, the `homepage` and `url` appear to be dead for all Casks hosted from the domain `thelittleappfactory.com`, namely [`evom`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/evom.rb), [`irip`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/irip.rb), [`ringtones`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/ringtones.rb), [`ripit`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/ripit.rb) and [`tagalicious`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/tagalicious.rb).

Can anyone else confirm these findings?

**Comment by adithyasunil26** [comment]
Yes, it looks like ```thelittleappfactory.com``` is down.

**Comment by vitorgalvao** [comment]
They seems to have been dead for about a month, and not popular before that:

```
evom
30 days: n/a
90 days: 82 (#1581)
365 days: 94 (#3247)
Age: 2720 days (added 2013, August 09)

irip
30 days: n/a
90 days: 2 (#5972)
365 days: 4 (#7154)
Age: 3014 days (added 2012, October 19)

ringtones
30 days: n/a
90 days: 1 (#6918)
365 days: 12 (#6159)
Age: 3014 days (added 2012, October 19)

ripit
30 days: 1 (#6028)
90 days: 18 (#3202)
365 days: 87 (#3359)
Age: 3014 days (added 2012, October 19)

tagalicious
30 days: n/a
90 days: n/a
365 days: 2 (#7956)
Age: 3014 days (added 2012, October 19)
```

Sending PRs to delete them.

**Comment by idiomatic** [comment]
It looks like `thellittleappfactory.com` is back up.  Revert?

**Comment by vitorgalvao** [comment]
> It looks like `thellittleappfactory.com` is back up. Revert?

*Maybe* `evom` and `ripit`. No point in the others. We’re also not going to revert because there may be changes. You may resubmit them (and fix any issues), though.
