### ISSUE TITLE
MacFuse vs OSXFuse

### ISSUE THREAD

**Issue by deftdawg** [Homebrew/homebrew-cask#98533]
#### Description of issue

When looking to install NTFS support for my mac, I searched for macfuse. 

There is some documentation that suggests that OSXFuse was intended as the newest version of MacFuse.  However, it appears that MacFuse and OSXFuse are the same thing and the OSXFuse website uses MacFuse branding.

MacFuse in homebrew is the latest release 4.0.5, where as OSXFuse is a year out of date (3.11.2).

The brew install stats from https://formulae.brew.sh/cask/macfuse and https://formulae.brew.sh/cask/osxfuse, show some 13000 or so installs of the older OSXFuse vs just 200 for MacFuse.   So it seems confusion is widespread.

@miccal was there a reason you created MacFuse instead of updating OSXFuse?   

Should these packages be unified?

**Comment by miccal** [comment]
This is because of https://github.com/Homebrew/brew/pull/10276 -- `osxfuse` will be removed when `homebrew-core` is ready for this change. For the moment, `macfuse` is the latest one and `osxfuse` is kept to prevent problems in `homebrew` and `homebrew-core`.

**Comment by deftdawg** [comment]
@miccal thank you for the clarification. 

Think I need to install the older `osxfuse` for now, as `macfuse` doesn't satsify `ntfs-3g`'s requirements.

**Comment by shoogle** [comment]
Could the difference between `macfuse` and `osxfuse` be explained somewhere? It's annoying to have to go looking to find out which one is the right one.

Perhaps the `osxfuse` cask could say:

> A never version of this program is available called 'macfuse'. This 'osxfuse' cask exists to satisfy dependencies.

Meanwhile the `macfuse` cask could say:

> 'macfuse' was previously called 'osxfuse'. An 'osxfuse' cask is still available for people who need the older version.

[`osxfuse`](https://formulae.brew.sh/cask/osxfuse) still gets more installs than [`macfuse`](https://formulae.brew.sh/cask/macfuse) which suggests many people don't know the difference. If they only look at download stats they might even think that `osxfuse` is the current version.
