### ISSUE TITLE
BlackHole SHA256 update.

### ISSUE THREAD

**Issue by devinroth** [Homebrew/homebrew-cask#98610]
BlackHole dev here. I just updated the installers to fix a macOS 10.11 bug so now there is a SHA256 mismatch.

The link is the same but the SHA256 needs updating.

2ch: ```2d834bcd54d35db691c6694cc618ee5df8e683d78fbeed45eb2f0b94545e46b9```
16ch: ```87c10fc09406b39de3e9f0366ff49c09dadbde4fb3088cdc36a59ee2dc6da031```

https://github.com/ExistentialAudio/BlackHole/issues/277

**Comment by adithyasunil26** [comment]
PRs updating the checksums have been merged. This issue can be closed now

**Comment by vitorgalvao** [comment]
@devinroth For future reference, you need only `brew bump-cask-pr --version VERSION_HERE blackhole-2ch` and you’re done; the PR is sent to us. In this case, you’d use the same version and it’s fix the checksum.

**Comment by devinroth** [comment]
Thanks. This was a strange situation since the version is exactly the same but the installer was signed differently. BlackHole version was exactly the same. Nothing changed. Turns out signing code on Big Sur doesn’t work on MacOS 10.11 or earlier. I needed to sign on an older version of macOS.

But that’s good to know for the next release.

Devin
