### ISSUE TITLE
android-sdk missing build-tools dir (e.g. aapt/aapt2 binary)

### ISSUE THREAD

**Issue by OJFord** [Homebrew/homebrew-cask#98972]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

There is no `build-tools` directory in:
```
/usr/local/Caskroom/android-sdk/4333796/
```

as there was in previous versions; nor is the `aapt`/`aapt2` binary anywhere else to be found. As far as I can tell it's [still included upstream](https://developer.android.com/studio/command-line/aapt2), it's just missing from the list of `binary <path>`s in [the brew formula](https://developer.android.com/studio/command-line/aapt2):

https://github.com/Homebrew/homebrew-cask/blob/125cd9a5cae6f0a7a811afd1e0b9b9f8dc110530/Casks/android-sdk.rb#L10-L22

#### Command that failed

```
aapt
```

(/ N/A)

#### Output of command with `--verbose --debug`

N/A

#### Output of `brew doctor --verbose`

N/A

#### Output of `brew tap`

N/A

**Comment by miccal** [comment]
These are part of [`android-studio`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/android-studio.rb), not `android-sdk`.

Also note that we tried to add the [command-line tools to `homebrew-cask`](https://github.com/Homebrew/homebrew-cask/pull/80305), but it proved too difficult (at the time).
