### ISSUE TITLE
Reconsidering the install path of `binary`

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-cask#99095]
On Apple Silicon, Homebrew defaults its installation to `/opt/homebrew/bin`. However, `binary` in casks still installs to `/usr/local/bin` (and silently fails if it cannot do it).

We should consider using `/opt/homebrew/bin` for `binary` on Apple Silicon.

Ping @Homebrew/cask.

**Comment by carlocab** [comment]
Oops. I missed this one as I only recently started following Homebrew/cask. This idea sounds good to me.

**Comment by vitorgalvao** [comment]
@carlocab This seems to have been independently done in the meantime, which is why I let it close.
