### ISSUE TITLE
Tap package naming  issue: Warning: apm-server-oss: No available formula with the name "apm-server".

### ISSUE THREAD

**Issue by based2** [Homebrew/homebrew-cask#99093]
#### General troubleshooting steps

brew tap elastic/tap
brew install elastic/tap/apm-server-oss

- [X ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Warning: apm-server-oss: No available formula with the name "apm-server".
'conflicts_with "apm-server"' should be removed from apm-server-oss.rb.
Please report this issue to the elastic/tap tap (not Homebrew/brew or Homebrew/core)!

#### Command that failed

```
{{replace this}}
```

#### Output of command with `--verbose --debug`

```
{{replace this}}
```

#### Output of `brew doctor --verbose`

```
{{replace this}}
```

#### Output of `brew tap`

```
==> Installing apm-server-oss from elastic/tap
==> Downloading https://artifacts.elastic.co/downloads/apm-server/apm-server-oss-7.10.2-darwin-x86_64.tar.gz?tap=elastic/homebrew-tap
######################################################################## 100.0%
Warning: apm-server-oss: No available formula with the name "apm-server".
'conflicts_with "apm-server"' should be removed from apm-server-oss.rb.
Please report this issue to the elastic/tap tap (not Homebrew/brew or Homebrew/core)!
==> Caveats
To have launchd start elastic/tap/apm-server-oss now and restart at login:
  brew services start elastic/tap/apm-server-oss
Or, if you don't want/need a background service you can just run:
  apm-server
==> Summary
🍺  /usr/local/Cellar/apm-server-oss/7.10.2: 10 files, 95.6MB, built in 3 seconds
```

**Comment by vitorgalvao** [comment]
> Please report this issue to the elastic/tap tap (not Homebrew/brew or Homebrew/core)!
