### ISSUE TITLE
x11 is disabled

### ISSUE THREAD

**Issue by LiuJiLan** [Homebrew/homebrew-cask#99179]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [√] ran `brew update` and can still reproduce the problem?
- [√] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [√] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [√] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Firstly `brew search R`
Then `brew search xxx`(xxx means anything)

## What happened (include command output)

First, I wanted to use `brew search R` to search something, then I had a warning.

Then, I used `brew update`. When finished, I tried to use search, and I get a new Error:
`Error: Calling depends_on :x11 is disabled! Use depends_on specific X11 formula(e) instead.
Please report this issue to the homebrew/cask tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/x48.rb:11`

Then, I tried `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/x48.rb`
And it told me what is showed in folliwing part.

By the way:
Before updating , the warning only happened when I `brew search R`. It seems about the java and `depends_on`.

<details>
  <summary>Command output</summary>
  <pre>
Last login: Mon Feb  1 22:56:13 on ttys000
liujilan@LiuJiLans-MBP-2019 ~ % brew search java
Error: Calling depends_on :x11 is disabled! Use depends_on specific X11 formula(e) instead.
Please report this issue to the homebrew/cask tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/x48.rb:11

liujilan@LiuJiLans-MBP-2019 ~ % /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/x48.rb
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/x48.rb: line 1: cask: command not found
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/x48.rb: line 3: version: command not found
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/x48.rb: line 4: sha256: command not found
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/x48.rb: line 7: url: command not found
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/x48.rb: line 8: name: command not found
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/x48.rb: line 9: homepage: command not found
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/x48.rb: line 11: depends_on: command not found
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/x48.rb: line 13: app: command not found
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/x48.rb: line 14: end: command not found

  </pre>
</details>

`brew config` and `brew doctor` will be attached by the file.
[output.txt](https://github.com/Homebrew/homebrew-core/files/5904679/output.txt)

**Comment by miccal** [comment]
The Cask `x48` [was removed](https://github.com/Homebrew/homebrew-cask/pull/86119), so please run `rm -rf "$(brew --prefix)/Caskroom/x48`, which should then fix your issue.

**Comment by LiuJiLan** [comment]
But the main problem that `Error: Calling depends_on :x11 is disabled! Use depends_on specific X11 formula(e) instead. Please report this issue to the homebrew/cask tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/x48.rb:11` is unsolved.

**Comment by miccal** [comment]
The file `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/x48.rb` should no longer exist -- this output of your `brew doctor`:
```
Warning: Suspicious https://github.com/Homebrew/brew git origin remote found.
The current git origin is:
  https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git

With a non-standard origin, Homebrew won't update properly.
You can solve this by setting the origin remote:
  git -C "/usr/local/Homebrew" remote set-url origin https://github.com/Homebrew/brew

Warning: Suspicious https://github.com/Homebrew/homebrew-core git origin remote found.
The current git origin is:
  https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git

With a non-standard origin, Homebrew won't update properly.
You can solve this by setting the origin remote:
  git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" remote set-url origin https://github.com/Homebrew/homebrew-core
```
is most likely the problem -- your copy of the `hombrew-cask` tap is out-of-date.

Why are you not using the standard `git origin`?

**Comment by LiuJiLan** [comment]
Now, I change the origin to `git origin`. And when running `brew doctor`, the warning about the origin disappeared .
I ran `brew update `, and it told me that `Already up-to-date.`.
But, when ran  `brew search java`, it still told me that `Error: Calling depends_on :x11 is disabled! Use depends_on specific X11 formula(e) instead.
Please report this issue to the homebrew/cask tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/x48.rb:11`

**Comment by miccal** [comment]
Something is very wrong with your `brew` setup -- please run the command `brew update-reset` and try again.

**Comment by LiuJiLan** [comment]
It seems that you are right. After running `brew update-reset`, it seemed fix something.
But when running `brew search java`, nothing had changed.
The following is the output:
[output2.txt](https://github.com/Homebrew/homebrew-cask/files/5910859/output2.txt)

**Comment by miccal** [comment]
Does simply running `rm /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/x48.rb` and then trying `rew search java` fix the problem?

**Comment by LiuJiLan** [comment]
This time it perfectly works . Thank you so much .
