### ISSUE TITLE
Latest versions of node & npm

### ISSUE THREAD

**Issue by CodeByZach** [Homebrew/homebrew-cask#99193]
I have the latest version of [node](https://formulae.brew.sh/formula/node) (15.7.0 at the time of this comment) installed. Per https://github.com/Homebrew/homebrew-core/pull/69816, it comes with npm version 7.4.3 by default.

The issue:
When I run `npm --global outdated;` this is the output:
<img width="517" alt="image" src="https://user-images.githubusercontent.com/20159826/106532882-15128b00-64bf-11eb-869a-051796aae781.png">

Of course, downgrading to this "latest" version breaks the existing installation. Does anyone understand what's going on here?

Thanks

**Comment by miccal** [comment]
`node` is a Formula, not a Cask, so you have reported this to the wrong repository.

Please report this to the [`homebrew-core` repository](https://github.com/Homebrew/homebrew-core), ensuring that you fill out the issue template.
