### ISSUE TITLE
Update prey instructions

### ISSUE THREAD

**Issue by moltar** [Homebrew/homebrew-cask#99252]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

`prey` cask has the following instructions:

>    Prey requires your API key, found in the bottom-left corner of
>    the Prey web account Settings page, to complete installation.
>    The API key may be set as an environment variable as follows:

Source: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/prey.rb

These instructions seem to be outdated.

Source: https://help.preyproject.com/article/316-unattended-install-for-macos

>  You can find your Setup API Key on your About page, on the Setup API Key section. Click on it to save to the clipboard.

Maybe add the direct link to the instructions as well: https://panel.preyproject.com/settings/about

**Comment by vitorgalvao** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-cask/pull/99254/.
