### ISSUE TITLE
Question of BrewTestBot & livecheck section.

### ISSUE THREAD

**Issue by VergeDX** [Homebrew/homebrew-cask#99314]
I noticed that cask's file contains "livecheck" section, but after I flip through [brew livecheck Documentation](https://docs.brew.sh/Brew-Livecheck), 
I'm confused, here's My question: 
 - Homebrew's outdated cask will be auto-update? I noticed @BrewTestBot can auto-update cask but seems the bot still testing.
 - I noticed the `brew bump-cask-pr` command can auto-create update PR, it needs an environment variable `HOMEBREW_GITHUB_API_TOKEN`, what is the minimal scoop of the GitHub person token?

That's all, thanks for the Homebrew team!

**Comment by miccal** [comment]
> * Homebrew's outdated cask will be auto-update? I noticed @BrewTestBot can auto-update cask but seems the bot still testing.

No, they will not always auto-update -- we rely heavily on users submitting PR's to update various Casks.

> * I noticed the `brew bump-cask-pr` command can auto-create update PR, it needs an environment variable `HOMEBREW_GITHUB_API_TOKEN`, what is the minimal scoop of the GitHub person token?

The minimum scope is setting `public_repo Access public repositories`.

> That's all, thanks for the Homebrew team!

Thank you for the kind words.

**Comment by VergeDX** [comment]
@miccal 
Thanks for the answer. I'm working on auto-create update PR in GitHub Actions.
