### ISSUE TITLE
`brew install libreoffice-language-pack` does not install the language pack.

### ISSUE THREAD

**Issue by dschuessler** [Homebrew/homebrew-cask#99377]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

`brew install libreoffice-language-pack` does not actually install the language pack. Instead this message appears.

```
To complete the installation of Cask libreoffice-language-pack, you must also
run the installer at:
  /usr/local/Caskroom/libreoffice-language-pack/7.1.0/LibreOffice Language Pack.app
🍺  libreoffice-language-pack was successfully installed!
```

So it appears that homebrew just downloaded the installer and did nothing with it but claimed a successful installation anyways. When entering an `install` command and being told that the installation was successful, I'd expect a successful installation.

#### Command that failed

```
brew install libreoffice-language-pack
```

The output of the various commands can be found here: https://gist.github.com/dschuessler/dd294019c8d310594b57538c74d108cc

**Comment by miccal** [comment]
This is by design as this Cask uses an `installer manual:`, which means that it is not possible to automate the install.
