### ISSUE TITLE
Google Drive File Stream install issue

### ISSUE THREAD

**Issue by heathflohre** [Homebrew/homebrew-cask#99478]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Run brew install google-drive-file-stream and receive error

#### Command that failed

```
brew install google-drive-file-stream
```

#### Output of command with `--verbose --debug`

```
Error: Could not find PKG source file 'GoogleDriveFileStream.pkg', found 'GoogleDrive.pkg' instead
```

#### Output of `brew doctor --verbose`

```
{{replace this}}
```

#### Output of `brew tap`

```
{{replace this}}
```

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/99419
