### ISSUE TITLE
Add browserpass extension

### ISSUE THREAD

**Issue by stweil** [Homebrew/homebrew-cask#99519]
### Description of feature/enhancement

The browserpass extension for the Firefox web browser allows easy access to a password store based on the command line program `pass` (for which there exists already a formula).

### Justification

It looks like browserpass is used my many people. While the installation of the browser part of browserpass can be easily managed within Firefox, an additional external component `browserpass-native` is required, too. Building that is difficult, and here Homebrew would help.

Some time ago there was already a pull request https://github.com/Homebrew/homebrew-core/pull/21039 which would have added the external component `browserpass-native` to `homebrew-core`.

### Example use case

Any website requiring a password in the web browser.

**Comment by stweil** [comment]
As far as I have understood the old discussion it suggested adding a cask for the browserpass add-on and the browserpass-native component instead of just a formula for the browserpass-native component.

That requires more work, but might be done. I just had a look on existing casks for Firefox add-ons and only found an outdated one for Adobe Flash (which is no longer supported), so that one should be removed. Are there better examples? Or should we reconsider adding simply a formula for `browserpass-native`?

**Comment by stweil** [comment]
CC'ing @amar1729 who wrote the old formula.

**Comment by vitorgalvao** [comment]
> Or should we reconsider adding simply a formula for `browserpass-native`?

Is it CLI-only open-source software? If yes, it should be a formula. If not, it should be a cask, but we don’t take cask requests (only PRs).

If I’ve missed something about your query, please let me know.

**Comment by stweil** [comment]
It's a CLI-only open-source software:

    % ls -l /opt/homebrew/bin/browserpass*
    -rwxr-xr-x  1 stefan  wheel  3932242  8 Feb 15:58 /opt/homebrew/bin/browserpass
    lrwxr-xr-x  1 stefan  wheel       52  8 Feb 15:46 /opt/homebrew/bin/browserpass-darwin64 -> ../Cellar/browserpass/3.0.7/bin/browserpass-darwin64
    % browserpass --version
    Browserpass host app version: 3.0.7
    % browserpass --help   
    Usage of browserpass:
      -v	print verbose output
      -version
        	print version and exit

Usually it is running as a background process which offers the services required by the Firefox add-on.

**Comment by stweil** [comment]
How can we solve the deadlock situation that `browserpass` was not accepted as a formula because it should be a cask, and now it is not accepted as a cask because it is a command line application which should be a formula?

Would it get a second chance of being added as a formula?

**Comment by vitorgalvao** [comment]
Missed that part. It can be submitted as a cask, yes.

**Comment by stweil** [comment]
Hm. Casks cannot use `bottle`. So how can I get a pre-built binaries for Intel and Arm macOS if nobody else offers them somewhere on the web?

**Comment by vitorgalvao** [comment]
> So how can I get pre-built binaries for Intel and Arm macOS if nobody else offers them somewhere on the web?

That is a problem. Casks can only use pre-compiled software and we only accept it from the official sources. So if they don’t offer it, we also can’t.

**Comment by stweil** [comment]
It would be much easier if Homebrew would accept a pull request for a formula.

**Comment by Amar1729** [comment]
@stweil - actually, the browserpass releases do include prebuilt binaries for darwin64 ([link](https://github.com/browserpass/browserpass-native/releases/tag/3.0.7)), but not ARM yet.

Another limitation that may prevent this from becoming a Cask is the fact that `browserpass` needs to generate a [JSON file](https://github.com/browserpass/browserpass-native/tree/master/browser-files) that defines allowed native messaging hosts (required by browser extensions that communication with native binaries) based on what browser the user uses. The JSON file must include the full path of the browserpass binary, and my tap's formula currently only does this by having a caveats section that asks the user to run a command after installation. Not sure how this would work as a Cask.

**Comment by stweil** [comment]
The limitation could be fixed for a formula which could check which browsers are available and create the required system-wide symbolic links using `sudo`.

I don't know whether that would be possible for a Cask, too.

**Comment by vitorgalvao** [comment]
> It would be much easier if Homebrew would accept a pull request for a formula.

I believe you but can’t help you with that. I deal with casks and don’t interfere in the decisions of the maintainers who deal with formulae.

> I don't know whether that would be possible for a Cask, too.

Technically you can do anything [in a `postflight` block](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/flight.md). In practice if it’s too complex (hard to maintain), we may reject it, particularly because I wouldn’t anticipate this being a popular cask.
