### ISSUE TITLE
There is no guide to install brew-cask in README.md

### ISSUE THREAD

**Issue by RollsBean** [Homebrew/homebrew-cask#99546]
#### Description of issue

I want to install `brew-cask`, but i couldn't find the guide to install brew-cask in `README.md`, it just show how to use it.

#### Command that failed

Actually，i follewed README and goto home brew to get command, but when i search `brew-cask`, only `brew install brew-cask-completion` show up and it works not well.

See `brew install brew-cask-completion` log:

```
Updating Homebrew...
Error: homebrew/completions was deprecated. This tap is now empty and all its contents were either deleted or migrated.```

**Comment by pnxdxt** [comment]
As written in the README _(note the humor)_ :

> To start using Homebrew Cask, you just need Homebrew installed.

To install a cask just do 

`brew install --cask $the_formula_of_the_app`

**Comment by miccal** [comment]
@pnxdxt is correct -- you do not need to install `cask`, it is built into `brew` and will auto-tap the `cask` repositories as required.
