### ISSUE TITLE
AnyDesk in Version 6.1.1 is a Universal App with arm64 Support

### ISSUE THREAD

**Issue by Knight1** [Homebrew/homebrew-cask#99638]
Hi!

The Cask 'AnyDesk' in Version 6.1.1 is arm64 compatible. But I do not have a clue how to mark it in the cask and the Website.

Link: https://blog.anydesk.com/de/wie-wir-anydesk-fuer-apple-silicon-optimiert-haben-ein-interview-mit-unserem-macos-entwickler/

Thanks!
Tobias

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/99639

**Comment by Knight1** [comment]
What about the Link here https://formulae.brew.sh/cask/anydesk#default? There is no mentioning about the arm64 in the .rb File.
