### ISSUE TITLE
Install MPD

### ISSUE THREAD

**Issue by entuccio** [Homebrew/homebrew-cask#99859]
Hello,

I have an old MAc Mini 2011 with Mac Os Sierra 10.12.6

If I try to install mpd with homebrew it says:

mpd: macOS Mojave or newer is required for this software.

I tried to install an old version with

brew install mpd@otherversion

but it doesn't work.

Any suggestion?

Thank you

**Comment by vitorgalvao** [comment]
`mpd` is a formula, not a cask; you’re looking for https://github.com/Homebrew/homebrew-core. But no, there’s no old formula for that and I doubt it’ll be made for such an older OS.

Next time, please don’t skip the template.
