### ISSUE TITLE
brew install hyperkit exited with 128

### ISSUE THREAD

**Issue by satishkrish-cloud** [Homebrew/homebrew-cask#99894]
#### General troubleshooting steps

- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

{{replace this}}

#### Command that failed

```
admin$ brew install hyperkit
==> Tapping homebrew/cask
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
fatal: the remote end hung up unexpectedly69.82 MiB | 5.68 MiB/s
fatal: early EOF
fatal: index-pack failed
Error: Failure while executing; `git clone https://github.com/Homebrew/homebrew-cask /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask --origin=origin` exited with 128.
C02PC1Fxxxxx:~ admin$ brew install alfred
==> Tapping homebrew/cask
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
fatal: the remote end hung up unexpectedly71.04 MiB | 6.36 MiB/s
fatal: early EOF
fatal: index-pack failed
Error: Failure while executing; `git clone https://github.com/Homebrew/homebrew-cask /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask --origin=origin` exited with 128.

```

#### Output of command with `--verbose --debug`

```
C02PC1Fxxxxx:~ admin$ brew install hyperkit --verbose --debug
/usr/local/Homebrew/Library/Homebrew/shims/scm/git --version
==> Tapping homebrew/cask
git clone https://github.com/Homebrew/homebrew-cask /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask --origin=origin
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
fatal: the remote end hung up unexpectedly73.86 MiB | 6.25 MiB/s
fatal: early EOF
fatal: index-pack failed
Error: Failure while executing; `git clone https://github.com/Homebrew/homebrew-cask /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask --origin=origin` exited with 128.
/usr/local/Homebrew/Library/Homebrew/utils.rb:321:in `safe_system'
/usr/local/Homebrew/Library/Homebrew/tap.rb:307:in `install'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/tap.rb:10:in `install_default_cask_tap_if_necessary'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:160:in `rescue in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:156:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'

```

#### Output of `brew doctor --verbose`

```
C02PC1Fxxxxx:~ admin$ brew doctor --verbose
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Suspicious https://github.com/Homebrew/homebrew-core git origin remote found.
The current git origin is:
  https://github.com/Homebrew/brew

With a non-standard origin, Homebrew won't update properly.
You can solve this by setting the origin remote:
  git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" remote set-url origin https://github.com/Homebrew/homebrew-core

```

#### Output of `brew tap`

``` 
C02PC1xxxx:~ admin$ brew tap
homebrew/core
powershell/tap
C02PC1xxxx:~ admin$ 

```

**Comment by miccal** [comment]
Please run the command suggested in you `brew doctor` output, and once this has been fixed try running `brew tap homebrew/cask`.

**Comment by satishkrish-cloud** [comment]
C02PC1Fxxxxx:~ admin$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Suspicious https://github.com/Homebrew/homebrew-core git origin remote found.
The current git origin is:
  https://github.com/Homebrew/brew

With a non-standard origin, Homebrew won't update properly.
You can solve this by setting the origin remote:
  git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" remote set-url origin https://github.com/Homebrew/homebrew-core
C02PC1Fxxxxx:~ admin$ git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" remote set-url origin https://github.com/Homebrew/homebrew-core
C02PC1FCFY0T:~ admin$ brew tap homebrew/cask
Updating Homebrew...
==> Tapping homebrew/cask
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (8/8), done.
fatal: the remote end hung up unexpectedly75.43 MiB | 6.33 MiB/s
fatal: early EOF
fatal: index-pack failed
Error: Failure while executing; `git clone https://github.com/Homebrew/homebrew-cask /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask --origin=origin` exited with 128.
C02PC1Fxxxxxx:~ admin$
